(()=>{
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),api=async(path,opt={})=>{const r=await fetch('/api/'+path,{...opt,headers:{'Content-Type':'application/json','Authorization':'Bearer '+(localStorage.getItem('cnine_card_api_token')||'')}}),d=await r.json();if(!r.ok)throw Error(d.error||'요청 실패');return d},roleIcon={선봉:'⚔',중견:'🛡',대장:'♛'};
const members=a=>`<div class="captain-lineup">${a.map(x=>`<div class="captain-member role-${esc(x.role)}"><span>${roleIcon[x.role]||'◆'} ${esc(x.role)}</span><div class="captain-member-identity"><img src="assets/ui/tiers/${esc(x.pvpTier?.id||'bronze')}.png" alt="${esc(x.pvpTier?.name||'브론즈')}"><b>${esc(x.nickname)}</b></div><small>${esc(x.pvpTier?.name||'브론즈')} · PVP ${Number(x.pvpScore||0).toLocaleString()}점</small><small>${Number(x.deck_power).toLocaleString()} 덱 전투력 · 5장</small></div>`).join('')}</div>`;
const topRank=t=>`<article class="captain-podium rank-${t.rank}"><em>${t.rank===1?'👑':t.rank===2?'🥈':'🥉'}</em><b>${esc(t.name)}</b><span>${Number(t.score).toLocaleString()}점</span><small>${t.wins}승 ${t.losses}패</small></article>`;
async function rankings(box){const d=await api('captain/ranking'),top=d.ranking.slice(0,3),rest=d.ranking.slice(3);box.innerHTML=`<section class="captain-rank-head"><button class="text-btn" id="capRankBack">← 내 팀</button><div><p class="eyebrow">WEEKLY TEAM RANKING</p><h2>대장전 주간 랭킹</h2><small>${esc(d.weekKey)} 주간 · 팀 승점 기준</small></div></section><div class="captain-podiums">${top.map(topRank).join('')}</div><div class="captain-rank-list">${rest.map(t=>`<div class="captain-rank-row"><b>${t.rank}</b><span>${esc(t.name)}<small>${t.members.map(m=>esc(m.nickname)).join(' · ')}</small></span><strong>${Number(t.score).toLocaleString()}점</strong></div>`).join('')||'<div class="empty-recent">추가 순위가 없습니다.</div>'}</div>`;document.getElementById('capRankBack').onclick=render}
async function render(){const box=document.getElementById('pvpContent');if(!box)return;box.innerHTML='<div class="captain-loading"><i></i><span>이번 주 대장전 정보를 불러오는 중...</span></div>';try{const d=await api('captain/status');if(!d.registered){box.innerHTML=`<section class="captain-lobby"><div class="captain-lobby-glow"></div><p class="eyebrow">WEEKLY 3 VS 3</p><h2>이번 주, 어제의 적이 오늘의 동지가 된다</h2><p>기존 PVP 5장 덱으로 참가하고 무작위 팀원과 일주일간 함께 싸우세요.</p><div class="captain-rule-grid"><div><b>3</b><span>랜덤 팀원</span></div><div><b>5</b><span>기존 PVP 덱</span></div><div><b>7D</b><span>주간 고정 팀</span></div></div><div class="captain-role-preview"><span>⚔ 선봉</span><i>→</i><span>🛡 중견</span><i>→</i><span>♛ 대장</span></div><button class="btn captain-main-btn" id="capReg">대장전 참가 등록</button><small>팀이 편성된 후에는 이번 주 동안 탈퇴할 수 없습니다.</small></section>`}
else if(!d.team){box.innerHTML=`<section class="captain-waiting"><div class="captain-search-orbit"><i></i><b>${d.waitingCount}</b><span>대기 인원</span></div><p class="eyebrow">TEAM MATCHING</p><h2>당신의 전우를 찾고 있습니다</h2><p>등록자 3명이 모이면 선봉·중견·대장이 자동으로 편성됩니다.</p><div class="captain-wait-slots"><div class="filled">YOU</div><div>?</div><div>?</div></div><button class="text-btn" id="capRefresh">새로고침</button><button class="btn ghost" id="capCancel">편성 전 참가 취소</button></section>`}
else box.innerHTML=`<section class="captain-team-card"><div class="captain-team-head"><div><p class="eyebrow">MY WEEKLY TEAM</p><h2>${esc(d.team.name)}</h2><small>팀명은 OWNER/ADMIN만 CMS에서 변경할 수 있습니다.</small></div><div class="captain-score"><b>${Number(d.team.score).toLocaleString()}</b><span>TEAM SCORE</span></div></div>${members(d.team.members)}<div class="captain-team-stats"><span>${d.team.wins}승</span><span>${d.team.losses}패</span><button class="text-btn" id="capRanking">주간 랭킹 보기</button></div></section><section class="captain-opponents"><div class="pvp-section-head"><div><p class="eyebrow">CHALLENGE</p><h2>상대 팀 선택</h2></div></div>${d.opponents.map(t=>`<article class="captain-opponent"><div class="captain-opponent-head"><b>${esc(t.name)}</b><strong>${Number(t.team_power).toLocaleString()}</strong></div>${members(t.members)}<button class="btn capFight" data-id="${t.id}">3:3 대장전 시작</button></article>`).join('')||'<div class="empty-recent">현재 도전 가능한 상대 팀이 없습니다.</div>'}</section>`;
document.getElementById('capReg')?.addEventListener('click',async()=>{if(!confirm('등록 후 팀이 편성되면 이번 주 동안 탈퇴할 수 없습니다. 참가할까요?'))return;try{await api('captain/register',{method:'POST'});render()}catch(e){alert(e.message)}});document.getElementById('capCancel')?.addEventListener('click',async()=>{try{await api('captain/register',{method:'DELETE'});render()}catch(e){alert(e.message)}});document.getElementById('capRefresh')?.addEventListener('click',render);document.getElementById('capRanking')?.addEventListener('click',()=>rankings(box));document.querySelectorAll('.capFight').forEach(b=>b.onclick=async()=>{if(!confirm('이 팀과 대장전을 시작할까요?'))return;try{const x=await api('captain/fight',{method:'POST',body:JSON.stringify({opponentTeamId:+b.dataset.id})});alert(`${x.result==='WIN'?'팀 승리':'팀 패배'} · ${x.scoreChange>0?'+':''}${x.scoreChange}점`);render()}catch(e){alert(e.message)}})}catch(e){box.innerHTML=`<div class="empty-recent captain-error">${esc(e.message)}</div>`}}
new MutationObserver(()=>{const nav=document.querySelector('.pvp-tabs');if(!nav||nav.querySelector('[data-captain]'))return;const b=document.createElement('button');b.dataset.captain='1';b.textContent='3:3 대장전';b.onclick=()=>{nav.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));render()};nav.insertBefore(b,nav.children[1]||null)}).observe(document.documentElement,{childList:true,subtree:true});
})();
