(function clanV1(global){
  'use strict';

  const state={data:null,loading:false,error:'',tab:'command',ctx:null};
  const ROLE_LABEL={ATTACK:'공격형',DEFENSE:'방어형',SPEED:'속도형',HP:'HP형',BALANCED:'균형형'};
  const WINDOW_LABEL={MORNING:'오전',DAY:'낮',EVENING:'저녁',NIGHT:'심야',FLEX:'유동'};
  const PHASE_LABEL={REGISTRATION:'시즌 참가 신청',DRAFT:'블라인드 드래프트',ACTIVE:'클랜전 진행',SETTLEMENT:'시즌 정산',COMPLETE:'시즌 종료'};
  const MARK_ICON={WOLF:'◆',RAVEN:'▲',LION:'♛',DRAGON:'◇',CROWN:'♜',SPEAR:'†',SHIELD:'⬡',PHOENIX:'✦'};
  const esc=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const number=value=>Math.max(0,Number(value)||0).toLocaleString();
  const time=value=>{const ms=Date.parse(String(value||''))-Date.now();if(!Number.isFinite(ms))return'일정 확인 중';if(ms<=0)return'전환 준비 중';const d=Math.floor(ms/86400000),h=Math.floor(ms%86400000/3600000),m=Math.floor(ms%3600000/60000);return d?`${d}일 ${h}시간`:h?`${h}시간 ${m}분`:`${Math.max(1,m)}분`};
  const mark=(team,classes='')=>`<span class="clan-mark ${classes}" style="--clan-primary:${esc(team?.primaryColor||'#31d7e8')};--clan-accent:${esc(team?.accentColor||'#e4f8ff')}" aria-hidden="true"><i>${MARK_ICON[team?.markKey]||'⬡'}</i></span>`;

  function loadingView(){return `<section class="clan-shell" id="clanRoot"><div class="clan-loading"><i></i><small>SOOPKETMON / CLAN NETWORK</small><h2>클랜 지휘망 연결 중</h2><p>시즌 스냅샷을 한 번만 불러오고 있습니다.</p></div></section>`}
  function view(){return loadingView()}

  function phaseHero(d){
    const season=d.season||{},mine=d.membership,phase=season.phase||'REGISTRATION',deadline=phase==='REGISTRATION'?season.registrationEndsAt:phase==='DRAFT'?season.nextPickDeadline||season.draftEndsAt:season.endsAt;
    return `<header class="clan-hero ${mine?'has-clan':''}" style="--clan-primary:${esc(mine?.primaryColor||'#31d7e8')};--clan-accent:${esc(mine?.accentColor||'#edfaff')}">
      <div class="clan-hero-grid" aria-hidden="true"></div><div class="clan-hero-copy"><small>SOOPKETMON / SEASON ${number(season.seasonNo)}</small><h2>${mine?`${esc(mine.name)} 작전본부`:'클랜 시스템'}</h2><p>${mine?esc(mine.slogan||'고정 인원 없이 매 시즌 새롭게 편성되는 전략 클랜입니다.'):'친목 고착 없이 실력과 활동으로 매 시즌 새롭게 편성됩니다.'}</p></div>
      <div class="clan-phase-card"><span>${esc(PHASE_LABEL[phase]||phase)}</span><b>${time(deadline)}</b><small>${phase==='DRAFT'?'다음 지명까지':'단계 종료까지'}</small></div>${mine?mark(mine,'hero-mark'):''}
    </header>`;
  }

  function ruleStrip(d){return `<div class="clan-rule-strip"><span><b>20</b> MAX ROSTER</span><span><b>BLIND</b> DRAFT</span><span><b>SNAKE</b> ORDER</span><span><b>V3</b> PIXIJS</span><span><b>0</b> VIEW LOG</span></div>`}
  function nav(d){const tabs=[['command','클랜 본부'],['roster','시즌 로스터'],['war','클랜전'],['rank','순위']];return `<nav class="clan-tabs" aria-label="클랜 메뉴">${tabs.map(([id,label])=>`<button type="button" data-clan-tab="${id}" class="${state.tab===id?'active':''}" ${(!d.membership&&['roster','war'].includes(id))?'disabled':''}>${label}</button>`).join('')}<button type="button" class="clan-refresh" data-clan-refresh aria-label="클랜 정보 새로고침">↻</button></nav>`}

  function registrationPanel(d){
    if(!d.verified)return `<section class="clan-panel clan-gate"><small>PLAY DK VERIFIED ONLY</small><h3>2차 인증이 필요합니다</h3><p>클랜은 PLAY DK 2차 인증 계정만 참여할 수 있습니다. 메시지함에서 인증을 완료한 뒤 돌아오세요.</p><button type="button" data-clan-route="messages">메시지함으로 이동</button></section>`;
    if(d.season?.phase!=='REGISTRATION')return `<section class="clan-panel clan-gate"><small>SEASON LOCKED</small><h3>이번 시즌 편성이 진행 중입니다</h3><p>다음 시즌 참가 신청이 열리면 새 로스터 풀에 등록할 수 있습니다.</p></section>`;
    const saved=d.registration||{};return `<section class="clan-panel clan-register"><div><small>SEASON ENTRY</small><h3>${saved.registered?'참가 정보 갱신':'시즌 참가 신청'}</h3><p>고정 가입이 아닙니다. 이번 시즌 종료 시 전원 드래프트 풀로 복귀합니다.</p></div><form data-clan-register-form><label><span>선호 역할</span><select name="preferredRole">${Object.entries(ROLE_LABEL).map(([key,label])=>`<option value="${key}" ${saved.preferredRole===key?'selected':''}>${label}</option>`).join('')}</select></label><label><span>주 활동 시간</span><select name="activityWindow">${Object.entries(WINDOW_LABEL).map(([key,label])=>`<option value="${key}" ${saved.activityWindow===key?'selected':''}>${label}</option>`).join('')}</select></label><button type="submit">${saved.registered?'참가 정보 갱신':'이번 시즌 참가'}</button></form><footer><i></i><span>랭크전 덱 5장이 V3 클랜전 덱으로 시즌 고정됩니다.</span></footer></section>`;
  }

  function identityPanel(d){const mine=d.membership;if(!mine?.isMaster)return'';return `<section class="clan-panel clan-identity"><header><div>${mark(mine)}<span><small>MASTER CONSOLE</small><h3>클랜 아이덴티티</h3></span></div><em>시즌 마스터 전용</em></header><form data-clan-identity-form><label><span>클랜 이름</span><input name="name" maxlength="16" value="${esc(mine.name)}" required></label><label><span>클랜 마크</span><select name="markKey">${Object.keys(MARK_ICON).map(key=>`<option value="${key}" ${mine.markKey===key?'selected':''}>${MARK_ICON[key]} ${key}</option>`).join('')}</select></label><label><span>주 색상</span><input name="primaryColor" type="color" value="${esc(mine.primaryColor||'#31d7e8')}"></label><label><span>보조 색상</span><input name="accentColor" type="color" value="${esc(mine.accentColor||'#e4f8ff')}"></label><label class="wide"><span>클랜 슬로건</span><input name="slogan" maxlength="60" value="${esc(mine.slogan||'')}"></label><button type="submit">클랜 정보 적용</button></form></section>`}

  function draftPanel(d){
    if(d.season?.phase!=='DRAFT')return'';const draft=d.draft;
    if(!d.membership)return `<section class="clan-panel clan-draft-wait"><small>BLIND DRAFT IN PROGRESS</small><h3>시스템 편성 진행 중</h3><p>닉네임과 이전 클랜을 숨긴 채 활동·랭크·역할 정보만으로 편성합니다.</p></section>`;
    if(!d.membership.isMaster)return `<section class="clan-panel clan-draft-wait"><small>SNAKE DRAFT</small><h3>${esc(draft?.currentClan?.name||'다른 클랜')} 지명 차례</h3><p>지명이 끝나면 로스터가 즉시 공개됩니다. 5분을 넘기면 시스템이 균형 후보를 자동 지명합니다.</p></section>`;
    if(!draft?.isMyTurn)return `<section class="clan-panel clan-draft-wait"><small>PICK ${number(draft?.pickNo)}</small><h3>${esc(draft?.currentClan?.name||'상대 클랜')} 지명 대기</h3><p>스네이크 순서에 따라 자동으로 우리 차례가 돌아옵니다.</p></section>`;
    return `<section class="clan-panel clan-draft-board"><header><div><small>BLIND CANDIDATE BOARD</small><h3>PICK ${number(draft.pickNo)} · 우리 클랜 지명</h3><p>후보의 닉네임·프로필·이전 소속은 지명 완료 전까지 노출되지 않습니다.</p></div><b>${time(d.season.nextPickDeadline)}</b></header><div class="clan-candidate-grid">${(d.candidates||[]).map((c,index)=>`<article><span class="candidate-code">C-${String(index+1).padStart(3,'0')}</span><div class="candidate-role"><b>${esc(ROLE_LABEL[c.preferredRole]||'균형형')}</b><small>${esc(WINDOW_LABEL[c.activityWindow]||'유동')} 활동</small></div><dl><div><dt>활동</dt><dd>${esc(c.activityBand)}</dd></div><div><dt>랭크</dt><dd>${esc(c.rankBand)}</dd></div><div><dt>기여</dt><dd>${number(c.contributionScore)}</dd></div><div><dt>균형점수</dt><dd>${number(c.totalScore)}</dd></div></dl><button type="button" data-clan-pick="${esc(c.candidateKey)}">이 후보 지명</button></article>`).join('')||'<p class="clan-empty">지명 가능한 후보가 없습니다.</p>'}</div></section>`;
  }

  function testControl(d){if(d.mode!=='TEST')return'';const phase=d.season?.phase,action=phase==='REGISTRATION'?'bootstrap':phase==='DRAFT'?'activate':'';return `<section class="clan-test-console"><div><small>OWNER CLOSED TEST</small><b>${phase==='ACTIVE'?'V3 클랜전 테스트 진행 중':phase==='DRAFT'?'드래프트 테스트 준비됨':'일반 유저에게 비공개 상태'}</b><span>${phase==='ACTIVE'?'테스트 종료 전까지 ON 전환 금지':'실데이터 보상·코인 지급 없이 편성 구조만 검증합니다.'}</span></div>${action?`<button type="button" data-clan-test="${action}">${action==='bootstrap'?'테스트 풀 구성 · 드래프트 시작':'남은 지명 자동 완료 · V3 개막'}</button>`:'<em>TEST MODE</em>'}</section>`}

  function commandView(d){if(!d.membership)return `${testControl(d)}${registrationPanel(d)}`;return `${testControl(d)}${identityPanel(d)}${draftPanel(d)}<section class="clan-command-grid"><article><small>SEASON POLICY</small><h3>고정 인원 없음</h3><p>시즌 종료와 함께 마스터를 포함한 전원이 풀로 복귀합니다.</p></article><article><small>AUTO MASTER</small><h3>활동·랭크·기여도 선발</h3><p>접속일·랭크전·영토전 집계 스냅샷으로 자동 선정됩니다.</p></article><article><small>DATABASE POLICY</small><h3>조회 로그 0건</h3><p>화면을 볼 때 로그를 적재하지 않고 시즌 집계값만 갱신합니다.</p></article><article><small>BATTLE CONTRACT</small><h3>PROJECT V V3</h3><p>고유효과·마법카드·장비 보정을 포함한 PixiJS 전투를 사용합니다.</p></article></section>`}

  function rosterView(d){const mine=d.membership;return `<section class="clan-roster-layout"><aside class="clan-panel clan-team-card">${mark(mine,'large')}<small>SEASON ${number(d.season?.seasonNo)} CLAN</small><h3>${esc(mine?.name||'클랜')}</h3><p>${esc(mine?.slogan||'')}</p><dl><div><dt>시즌 점수</dt><dd>${number(mine?.score)}</dd></div><div><dt>전적</dt><dd>${number(mine?.wins)}W ${number(mine?.losses)}L</dd></div><div><dt>정원</dt><dd>${number(mine?.memberCount)} / 20</dd></div></dl></aside><section class="clan-panel clan-roster"><header><small>SEASON ROSTER</small><h3>이번 시즌 편성</h3></header><div>${(d.roster||[]).map((m,index)=>`<article class="${m.memberRole==='MASTER'?'master':''}"><span>${String(index+1).padStart(2,'0')}</span><div><b>${esc(m.nickname)}</b><small>${m.memberRole==='MASTER'?'CLAN MASTER':esc(ROLE_LABEL[m.preferredRole]||'균형형')}</small></div><dl><dt>기여</dt><dd>${number(m.contributionScore)}</dd><dt>전적</dt><dd>${number(m.battleWins)}W ${number(m.battleLosses)}L</dd></dl></article>`).join('')||'<p class="clan-empty">드래프트 로스터를 구성 중입니다.</p>'}</div></section></section>`}

  function warView(d){
    if(d.season?.phase!=='ACTIVE')return `<section class="clan-panel clan-gate"><small>CLAN WAR STANDBY</small><h3>클랜전 개막 준비 중</h3><p>블라인드 드래프트가 끝나면 V3 클랜전 전장이 열립니다.</p></section>`;
    if(!d.war)return `<section class="clan-panel clan-gate"><small>ROUND BYE</small><h3>이번 라운드 상대 배정 대기</h3><p>대진 수가 홀수인 경우 다음 라운드로 자동 진출합니다.</p></section>`;
    const mine=d.membership,isA=Number(d.war.clanAId)===Number(mine.clanId),myScore=isA?d.war.scoreA:d.war.scoreB,enemyScore=isA?d.war.scoreB:d.war.scoreA,enemy=d.teams.find(t=>t.clanId===(isA?d.war.clanBId:d.war.clanAId));
    return `<section class="clan-war-score"><article style="--clan-primary:${esc(mine.primaryColor)}">${mark(mine)}<small>MY CLAN</small><h3>${esc(mine.name)}</h3><b>${number(myScore)}</b></article><div><small>ROUND ${number(d.war.roundNo)}</small><strong>VS</strong><span>${time(d.war.endsAt)} 남음</span></div><article class="enemy" style="--clan-primary:${esc(enemy?.primaryColor||'#ff556f')}">${mark(enemy)}<small>OPPONENT</small><h3>${esc(enemy?.name||'상대 클랜')}</h3><b>${number(enemyScore)}</b></article></section><section class="clan-panel clan-targets"><header><div><small>PROJECT V V3 TARGET LIST</small><h3>상대 클랜 전투원</h3><p>전투 시작 즉시 현재 라이브 V3 엔진으로 재생됩니다.</p></div><em>${number(d.war.battleCount)} BATTLES</em></header><div>${(d.opponents||[]).map((o,index)=>`<article><span>${String(index+1).padStart(2,'0')}</span><div><b>${esc(o.nickname)}</b><small>${esc(ROLE_LABEL[o.preferredRole]||'균형형')}</small></div><dl><dt>전적</dt><dd>${number(o.battleWins)}W ${number(o.battleLosses)}L</dd></dl><button type="button" data-clan-fight="${Number(o.userId)}">V3 전투</button></article>`).join('')||'<p class="clan-empty">상대 로스터를 불러오지 못했습니다.</p>'}</div></section>`;
  }

  function rankView(d){return `<section class="clan-panel clan-ranking"><header><small>SEASON CLAN RANKING</small><h3>클랜 순위</h3><p>점수 · 승리 · 드래프트 순서 기준</p></header><div>${(d.teams||[]).map((team,index)=>`<article class="${d.membership?.clanId===team.clanId?'mine':''}"><strong>${String(index+1).padStart(2,'0')}</strong>${mark(team)}<div><b>${esc(team.name)}</b><small>${esc(team.masterNickname)} · ${number(team.memberCount)}/20</small></div><dl><dt>SCORE</dt><dd>${number(team.score)}</dd><dt>RECORD</dt><dd>${number(team.wins)}W ${number(team.losses)}L</dd></dl></article>`).join('')||'<p class="clan-empty">드래프트가 시작되면 클랜 순위가 공개됩니다.</p>'}</div></section>`}

  function content(d){if(state.tab==='roster')return rosterView(d);if(state.tab==='war')return warView(d);if(state.tab==='rank')return rankView(d);return commandView(d)}
  function render(){const root=document.getElementById('clanRoot');if(!root)return;if(state.loading&&!state.data){root.outerHTML=loadingView();return}if(state.error&&!state.data){root.innerHTML=`<section class="clan-error"><small>CLAN NETWORK ERROR</small><h2>클랜 정보를 불러오지 못했습니다</h2><p>${esc(state.error)}</p><button type="button" data-clan-refresh>다시 연결</button></section>`;bindDom();return}const d=state.data;root.innerHTML=`${phaseHero(d)}${ruleStrip(d)}${nav(d)}<div class="clan-view">${content(d)}</div>`;bindDom()}

  async function load(force=false){if(state.loading)return;state.loading=true;state.error='';render();try{state.data=await state.ctx.apiRequest(`clan/overview${force?'?fresh=1':''}`,{},force?{timeoutMs:15000}:{ttl:2500,timeoutMs:15000})}catch(error){state.error=error.message||'클랜 서버 연결 실패'}finally{state.loading=false;render()}}
  async function mutate(path,body,button){if(button){button.disabled=true;button.dataset.label=button.textContent;button.textContent='처리 중'}try{const result=await state.ctx.apiRequest(path,{method:'POST',body:JSON.stringify(body)},{timeoutMs:20000});state.data=result.state||state.data;state.ctx.clearApiCache?.('clan/overview');render();return result}catch(error){alert(error.message||'요청을 처리하지 못했습니다.')}finally{if(button&&document.body.contains(button)){button.disabled=false;button.textContent=button.dataset.label||'다시 시도'}}}

  async function fight(targetUserId,button){
    if(button){button.disabled=true;button.textContent='V3 연결 중'}const ctx=state.ctx,modal=document.getElementById('modal'),mine=state.data?.membership,enemy=state.data?.opponents?.find(x=>Number(x.userId)===Number(targetUserId));
    try{
      await ctx.ensureFeatureResources('battleV2');if(!global.ProjectVBattleV3Live?.ready?.())throw new Error('V3 전투 리소스를 불러오지 못했습니다.');
      const early=ctx.prepareImmediateBattleV3Entry?.({modal,mode:'PVP',playerName:mine?.name||'MY CLAN',opponentName:enemy?.nickname||'OPPONENT'});let stage=early?.stage,phase=early?.phase,msg=early?.msg;if(phase)phase.textContent='클랜전 계산';
      const data=await ctx.apiRequest('clan/war/fight',{method:'POST',body:JSON.stringify({requestId:global.crypto?.randomUUID?.()||`${Date.now()}-${Math.random()}`,targetUserId})},{timeoutMs:25000});if(!data?.battleV2)throw new Error('클랜전 V3 전투 데이터를 받지 못했습니다.');
      const live=global.prepareBattleV2LiveLoading({modal,mode:'PVP',playerName:mine?.name||'MY CLAN',opponentName:data.opponent?.nickname||'OPPONENT'});stage=live.stage;phase=live.phase;msg=live.msg;ctx.ensureBattleSoundButton?.(stage);await global.playPvpBattleV2Live({stage,phase,msg,modal,data});
      const won=data.result==='WIN';stage.classList.add(won?'battle-win-v863':'battle-lose-v863');phase.textContent=won?'CLAN VICTORY':'CLAN DEFEAT';ctx.battleSfx?.(won?'victory':'defeat');msg.innerHTML=`<div class="clan-v3-result ${won?'win':'lose'}"><small>SOOPKETMON · CLAN WAR</small><strong>${won?'VICTORY':'DEFEAT'}</strong><div><b>${number(data.attackerPower)}</b><i>VS</i><b>${number(data.defenderPower)}</b></div><span>PROJECT V V3 · ${esc(data.battleV2?.result?.reason||'BATTLE')}</span><button type="button" data-clan-battle-close>클랜전으로 돌아가기</button></div>`;msg.classList.add('is-visible');
      const close=()=>{modal.__battleV2Renderer?.destroy?.();modal.__battleV2Renderer=null;modal.onclick=null;modal.className='modal';modal.innerHTML='';state.tab='war';ctx.renderShell('clan')};setTimeout(()=>{modal.onclick=close;modal.querySelector('[data-clan-battle-close]')?.addEventListener('click',event=>{event.stopPropagation();close()})},250);
    }catch(error){if(modal){modal.__battleV2Renderer?.destroy?.();modal.__battleV2Renderer=null;modal.className='modal';modal.innerHTML=''}alert(error.message||'클랜전 V3 전투를 시작하지 못했습니다.');if(button&&document.body.contains(button)){button.disabled=false;button.textContent='V3 전투'}}
  }

  function bindDom(){
    document.querySelectorAll('[data-clan-tab]').forEach(button=>button.onclick=()=>{state.tab=button.dataset.clanTab;render()});document.querySelectorAll('[data-clan-refresh]').forEach(button=>button.onclick=()=>load(true));document.querySelectorAll('[data-clan-route]').forEach(button=>button.onclick=()=>state.ctx.renderShell(button.dataset.clanRoute));
    document.querySelector('[data-clan-register-form]')?.addEventListener('submit',event=>{event.preventDefault();const form=event.currentTarget;void mutate('clan/register',{preferredRole:form.preferredRole.value,activityWindow:form.activityWindow.value},form.querySelector('button[type=submit]'))});
    document.querySelector('[data-clan-identity-form]')?.addEventListener('submit',event=>{event.preventDefault();const form=event.currentTarget;void mutate('clan/identity',{name:form.name.value,markKey:form.markKey.value,primaryColor:form.primaryColor.value,accentColor:form.accentColor.value,slogan:form.slogan.value},form.querySelector('button[type=submit]'))});
    document.querySelectorAll('[data-clan-pick]').forEach(button=>button.onclick=()=>{if(confirm('이 후보를 지명하면 되돌릴 수 없습니다. 진행할까요?'))void mutate('clan/draft/pick',{candidateKey:button.dataset.clanPick},button)});document.querySelectorAll('[data-clan-fight]').forEach(button=>button.onclick=()=>void fight(Number(button.dataset.clanFight),button));
    document.querySelectorAll('[data-clan-test]').forEach(button=>button.onclick=()=>{const action=button.dataset.clanTest;if(!confirm(action==='bootstrap'?'PLAY DK 인증·랭크전 덱 계정 최대 20명으로 비공개 테스트 풀을 구성할까요?':'남은 지명을 자동 완료하고 V3 클랜전을 개막할까요?'))return;void mutate(action==='bootstrap'?'clan/admin/test-bootstrap':'clan/admin/test-activate',action==='bootstrap'?{limit:20}:{},button)});
  }
  function bind(ctx){state.ctx=ctx;void load()}
  function stop(){state.loading=false}
  global.ClanV1={view,bind,stop,state};
})(window);
