(function clanV1(global){
  'use strict';

  const state={data:null,loading:false,error:'',tab:'command',ctx:null};
  const ROLE_LABEL={ATTACK:'공격형',DEFENSE:'방어형',SPEED:'속도형',HP:'HP형',BALANCED:'균형형'};
  const WINDOW_LABEL={MORNING:'오전',DAY:'낮',EVENING:'저녁',NIGHT:'심야',FLEX:'유동'};
  const PHASE_LABEL={REGISTRATION:'시즌 참가 신청',DRAFT:'블라인드 드래프트',ACTIVE:'클랜전 진행',SETTLEMENT:'시즌 정산',COMPLETE:'시즌 종료'};
  const PHASE_ORDER=['REGISTRATION','DRAFT','ACTIVE','SETTLEMENT','COMPLETE'];
  const MARK_ASSET={
    DK:'assets/ui/clan/marks/dk-clan-mark-v1.webp',SAMSUNG:'assets/ui/clan/marks/samsung-clan-mark-v1.webp',T1:'assets/ui/clan/marks/t1-clan-mark-v1.webp',HANWHA:'assets/ui/clan/marks/hanwha-clan-mark-v1.webp',
    LG:'assets/ui/clan/marks/lg-clan-mark-v1.webp',LOTTE:'assets/ui/clan/marks/lotte-clan-mark-v1.webp',FM:'assets/ui/clan/marks/fm-clan-mark-v1.webp',DC:'assets/ui/clan/marks/dc-clan-mark-v1.webp'
  };
  const esc=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const number=value=>Math.max(0,Number(value)||0).toLocaleString();
  const time=value=>{const ms=Date.parse(String(value||''))-Date.now();if(!Number.isFinite(ms))return'일정 확인 중';if(ms<=0)return'전환 준비 중';const d=Math.floor(ms/86400000),h=Math.floor(ms%86400000/3600000),m=Math.floor(ms%3600000/60000);return d?`${d}일 ${h}시간`:h?`${h}시간 ${m}분`:`${Math.max(1,m)}분`};
  const rosterLimit=d=>Math.max(1,Number(d?.rules?.maxMembers||d?.season?.maxMembers||22));
  const participantLimit=d=>Math.max(rosterLimit(d),Number(d?.rules?.maxParticipants||176));
  const mark=(team,classes='')=>{const key=String(team?.markKey||'DK').toUpperCase(),asset=MARK_ASSET[key]||MARK_ASSET.DK,label=`${team?.name||key} 클랜 마크`;return `<span class="clan-mark ${esc(classes)}" style="--clan-primary:${esc(team?.primaryColor||'#31d7e8')};--clan-accent:${esc(team?.accentColor||'#e4f8ff')}" role="img" aria-label="${esc(label)}"><img src="${asset}" width="384" height="384" alt="" decoding="async"></span>`};

  function loadingView(){return `<section class="clan-shell" id="clanRoot"><div class="clan-loading"><i></i><small>SOOPKETMON / CLAN NETWORK</small><h2>클랜 지휘망 연결 중</h2><p>시즌 스냅샷을 한 번만 불러오고 있습니다.</p></div></section>`}
  function view(){return loadingView()}

  function phaseHero(d){
    const season=d.season||{},mine=d.membership,phase=season.phase||'REGISTRATION',late=Boolean(season.lateRegistration),deadline=season.registrationOpen?season.registrationEndsAt:phase==='DRAFT'?season.nextPickDeadline||season.draftEndsAt:season.endsAt,phaseLabel=late?'추가 참가 신청':PHASE_LABEL[phase]||phase;
    return `<header class="clan-hero ${mine?'has-clan':''}" style="--clan-primary:${esc(mine?.primaryColor||'#31d7e8')};--clan-accent:${esc(mine?.accentColor||'#edfaff')}">
      <div class="clan-hero-media" aria-hidden="true"></div><div class="clan-hero-grid" aria-hidden="true"></div><div class="clan-hero-scan" aria-hidden="true"></div>
      <div class="clan-hero-copy"><span class="clan-access-signal"><i></i>${d.verificationExempt?'OWNER CLEARANCE':'CLAN OPERATIONS'}</span><small>SOOPKETMON / SEASON ${number(season.seasonNo)}</small><h2>${mine?`<em>${esc(mine.name)}</em> 작전본부`:'클랜 지휘국'}</h2><p>${mine?esc(mine.slogan||'고정 인원 없이 매 시즌 새롭게 편성되는 전략 클랜입니다.'):'친목 고착 없이 실력·활동·전투 기록으로 매 시즌 새로운 전선을 편성합니다.'}</p><div class="clan-hero-codes"><span>NODE C-${String(season.seasonNo||1).padStart(2,'0')}</span><span>ROSTER LIMIT ${number(rosterLimit(d))}</span><span>V3 LINK READY</span></div></div>
      <div class="clan-phase-card ${late?'is-late':''}"><small>OPERATION PHASE</small><div><span>${String(Math.max(1,PHASE_ORDER.indexOf(phase)+1)).padStart(2,'0')}</span><em>${esc(phaseLabel)}</em></div><b>${time(deadline)}</b><small>${season.registrationOpen?(late?'추가 신청 마감까지':'신청 마감까지'):phase==='DRAFT'?'다음 지명까지':'단계 종료까지'}</small></div>${mine?mark(mine,'hero-mark'):''}
    </header>`;
  }

  function ruleStrip(d){const policies=[['01',number(rosterLimit(d)),'MAX ROSTER'],['02','BLIND','DRAFT'],['03','RANDOM','MATCH'],['04','10','MAX ENERGY'],['05','60M','POINT RACE']];return `<div class="clan-rule-strip">${policies.map(([index,value,label])=>`<span><i>${index}</i><b>${value}</b><em>${label}</em></span>`).join('')}</div>`}
  function nav(d){const tabs=[['command','01','클랜 본부','COMMAND'],['roster','02','시즌 로스터','ROSTER'],['war','03','클랜전','WAR ROOM'],['rank','04','순위','RANKING']];return `<nav class="clan-tabs" aria-label="클랜 메뉴">${tabs.map(([id,index,label,en])=>`<button type="button" data-clan-tab="${id}" class="${state.tab===id?'active':''}" ${(!d.membership&&['roster','war'].includes(id))?'disabled':''}><i>${index}</i><span><b>${label}</b><small>${en}</small></span></button>`).join('')}<button type="button" class="clan-refresh" data-clan-refresh aria-label="클랜 정보 새로고침"><i></i><span><b>동기화</b><small>SYNC</small></span></button></nav>`}

  function seasonLockedPanel(d){
    const season=d.season||{},phase=season.phase||'DRAFT',current=Math.max(0,PHASE_ORDER.indexOf(phase)),deadline=phase==='DRAFT'?season.nextPickDeadline||season.draftEndsAt:season.endsAt;
    return `<section class="clan-season-lock"><div class="clan-lock-brief"><small>SEASON ${number(season.seasonNo)} / ROSTER CONTROL</small><span class="clan-lock-state"><i></i>편성 프로토콜 실행 중</span><h3>다음 투입을 위한<br><em>대기 명령</em></h3><p>현재 시즌 로스터는 잠겨 있습니다. 기존 편성이 끝나면 기록 스냅샷을 기준으로 다음 시즌 참가 창구가 자동 개방됩니다.</p><dl><div><dt>CURRENT PHASE</dt><dd>${esc(PHASE_LABEL[phase]||phase)}</dd></div><div><dt>TIME REMAIN</dt><dd>${time(deadline)}</dd></div></dl></div>
      <div class="clan-lock-radar" aria-hidden="true"><div class="radar-ring ring-a"></div><div class="radar-ring ring-b"></div><div class="radar-cross"></div><i class="radar-sweep"></i><span class="radar-core"><b>${String(current+1).padStart(2,'0')}</b><small>PHASE</small></span><em class="radar-point p1"></em><em class="radar-point p2"></em><em class="radar-point p3"></em></div>
      <aside class="clan-next-order"><small>NEXT DIRECTIVE</small><b>SEASON ${number(Number(season.seasonNo||0)+1)}</b><p>참가 신청이 열리면 선호 역할과 활동 시간을 다시 제출합니다.</p><div class="clan-phase-track">${PHASE_ORDER.map((key,index)=>`<span class="${index<current?'done':index===current?'active':''}"><i>${String(index+1).padStart(2,'0')}</i><b>${esc(PHASE_LABEL[key])}</b></span>`).join('')}</div></aside></section>`;
  }

  function registrationPanel(d){
    if(!d.verified)return `<section class="clan-panel clan-gate clan-access-gate"><small>ACCESS CLEARANCE REQUIRED</small><h3>클랜 지휘망 접근 승인 필요</h3><p>일반 계정은 PLAY DK 2차 인증을 완료해야 시즌 로스터에 참가할 수 있습니다.</p><button type="button" data-clan-route="messages"><span>2차 인증 화면으로 이동</span><i>→</i></button></section>`;
    if(!d.season?.registrationOpen)return seasonLockedPanel(d);
    const saved=d.registration||{},late=Boolean(d.season?.lateRegistration);return `<section class="clan-panel clan-register ${late?'is-late':''}"><div><small>${late?'LATE ENTRY · 19:00 CLOSE':'SEASON ENTRY'}</small><h3>${saved.registered?'참가 정보 갱신':late?'추가 참가 신청':'시즌 참가 신청'}</h3><p>${late?`클랜별 정원이 ${number(rosterLimit(d))}명으로 확장됐습니다. 19시 마감 뒤 기존 순서로 드래프트를 재개하고 21시에 클랜전이 시작됩니다.`:'고정 가입이 아닙니다. 이번 시즌 종료 시 전원 드래프트 풀로 복귀합니다.'}</p></div><form data-clan-register-form><label><span>선호 역할</span><select name="preferredRole">${Object.entries(ROLE_LABEL).map(([key,label])=>`<option value="${key}" ${saved.preferredRole===key?'selected':''}>${label}</option>`).join('')}</select></label><label><span>주 활동 시간</span><select name="activityWindow">${Object.entries(WINDOW_LABEL).map(([key,label])=>`<option value="${key}" ${saved.activityWindow===key?'selected':''}>${label}</option>`).join('')}</select></label><button type="submit">${saved.registered?'참가 정보 갱신':late?'추가 참가 확정':'이번 시즌 참가'}</button></form><footer><i></i><span>총 ${number(participantLimit(d))}명까지 신청 가능 · 실제 전투는 시작 순간의 최신 랭크전 덱 5장을 자동 반영합니다.</span></footer></section>`;
  }

  function identityPanel(d){const mine=d.membership;if(!mine?.isMaster)return'';return `<section class="clan-panel clan-identity"><header><div>${mark(mine)}<span><small>MASTER CONSOLE</small><h3>클랜 아이덴티티</h3></span></div><em>시즌 마스터 전용</em></header><form data-clan-identity-form><div class="clan-identity-fixed"><small>OFFICIAL IDENTITY</small><b>${esc(mine.name)} · ${esc(mine.markKey)}</b><span>클랜명·마크·팀 컬러는 공식 로스터로 고정됩니다.</span></div><label class="wide"><span>클랜 슬로건</span><input name="slogan" maxlength="60" value="${esc(mine.slogan||'')}" placeholder="이번 시즌 클랜 슬로건"></label><button type="submit">슬로건 적용</button></form></section>`}

  function catalogPanel(d){const clans=Array.isArray(d.officialClans)?d.officialClans:[];if(!clans.length)return'';return `<section class="clan-panel clan-catalog"><header><div><small>OFFICIAL CLAN ROSTER</small><h3>8개 공식 클랜</h3><p>클랜명·전용 마크·팀 컬러는 시즌이 바뀌어도 유지됩니다.</p></div><em>08 IDENTITIES</em></header><div class="clan-catalog-grid">${clans.map(clan=>{const active=(d.teams||[]).find(team=>team.markKey===clan.markKey);return `<article style="--clan-primary:${esc(clan.primaryColor)};--clan-accent:${esc(clan.accentColor)}">${mark(clan,'catalog-mark')}<span><small>${String(clan.order||0).padStart(2,'0')} · ${esc(clan.markKey)}</small><b>${esc(clan.name)}</b><em>${active?`${number(active.memberCount)} / ${number(rosterLimit(d))} · ${esc(active.masterNickname||'마스터 배정')}`:'시즌 배정 대기'}</em></span></article>`}).join('')}</div></section>`}

  function draftPanel(d){
    if(d.season?.phase!=='DRAFT')return'';const draft=d.draft;
    if(d.season?.lateRegistration)return `<section class="clan-panel clan-draft-wait clan-late-registration"><small>LATE REGISTRATION OPEN</small><h3>추가 참가 신청 접수 중</h3><p>클랜별 정원 ${number(rosterLimit(d))}명 확장에 맞춰 드래프트를 잠시 멈췄습니다. ${time(d.season.registrationEndsAt)} 뒤 현재 지명 순서부터 재개됩니다.</p><b>${time(d.season.registrationEndsAt)} 남음</b></section>`;
    if(!d.membership)return `<section class="clan-panel clan-draft-wait"><small>BLIND DRAFT IN PROGRESS</small><h3>시스템 편성 진행 중</h3><p>닉네임과 이전 클랜을 숨긴 채 활동·랭크·역할 정보만으로 편성합니다.</p></section>`;
    if(!d.membership.isMaster)return `<section class="clan-panel clan-draft-wait"><small>SNAKE DRAFT</small><h3>${esc(draft?.currentClan?.name||'다른 클랜')} 지명 차례</h3><p>지명이 끝나면 로스터가 즉시 공개됩니다. 5분을 넘기면 시스템이 균형 후보를 자동 지명합니다.</p></section>`;
    if(!draft?.isMyTurn)return `<section class="clan-panel clan-draft-wait"><small>PICK ${number(draft?.pickNo)}</small><h3>${esc(draft?.currentClan?.name||'상대 클랜')} 지명 대기</h3><p>스네이크 순서에 따라 자동으로 우리 차례가 돌아옵니다.</p></section>`;
    return `<section class="clan-panel clan-draft-board"><header><div><small>BLIND CANDIDATE BOARD</small><h3>PICK ${number(draft.pickNo)} · 우리 클랜 지명</h3><p>후보의 닉네임·프로필·이전 소속은 지명 완료 전까지 노출되지 않습니다.</p></div><b>${time(d.season.nextPickDeadline)}</b></header><div class="clan-candidate-grid">${(d.candidates||[]).map((c,index)=>`<article><span class="candidate-code">C-${String(index+1).padStart(3,'0')}</span><div class="candidate-role"><b>${esc(ROLE_LABEL[c.preferredRole]||'균형형')}</b><small>${esc(WINDOW_LABEL[c.activityWindow]||'유동')} 활동</small></div><dl><div><dt>활동</dt><dd>${esc(c.activityBand)}</dd></div><div><dt>랭크</dt><dd>${esc(c.rankBand)}</dd></div><div><dt>기여</dt><dd>${number(c.contributionScore)}</dd></div><div><dt>균형점수</dt><dd>${number(c.totalScore)}</dd></div></dl><button type="button" data-clan-pick="${esc(c.candidateKey)}">이 후보 지명</button></article>`).join('')||'<p class="clan-empty">지명 가능한 후보가 없습니다.</p>'}</div></section>`;
  }

  function testControl(d){if(d.mode!=='TEST')return'';const phase=d.season?.phase,late=Boolean(d.season?.lateRegistration),action=phase==='REGISTRATION'?'bootstrap':phase==='DRAFT'&&!late?'activate':phase==='ACTIVE'?'settle':'';return `<section class="clan-test-console"><div><small>OWNER CLOSED TEST</small><b>${late?'추가 참가 신청 접수 중':phase==='ACTIVE'?'60분 랜덤 승점전 테스트 진행 중':phase==='DRAFT'?'드래프트 테스트 준비됨':phase==='COMPLETE'?'테스트 시즌 정산 완료':'일반 유저에게 비공개 상태'}</b><span>${late?'추가 신청 마감 뒤 현재 드래프트 순서에서 재개합니다.':phase==='ACTIVE'?'시작 행동력 10·5분마다 1 회복·무전력 랜덤 매칭·최신 덱 반영을 검증합니다.':'TEST에서는 경제 보상을 지급하지 않고 편성·전적·정산만 검증합니다.'}</span></div>${action?`<button type="button" data-clan-test="${action}">${action==='bootstrap'?`최대 ${number(participantLimit(d))}명 테스트 풀 · 드래프트 시작`:action==='activate'?'남은 지명 완료 · 60분 1라운드 개막':'테스트 시즌 즉시 정산'}</button>`:'<em>TEST MODE</em>'}</section>`}

  function commandView(d){const catalog=catalogPanel(d);if(!d.membership)return `${testControl(d)}${registrationPanel(d)}${catalog}`;return `${testControl(d)}${identityPanel(d)}${draftPanel(d)}${catalog}<section class="clan-command-grid"><article data-code="01"><small>SEASON POLICY</small><h3>고정 인원 없음</h3><p>시즌 종료와 함께 마스터를 포함한 전원이 풀로 복귀합니다.</p></article><article data-code="02"><small>AUTO MASTER</small><h3>활동·랭크·기여도 선발</h3><p>접속일·랭크전·영토전 집계 스냅샷으로 자동 선정됩니다.</p></article><article data-code="03"><small>DATABASE POLICY</small><h3>조회 로그 0건</h3><p>화면을 볼 때 로그를 적재하지 않고 시즌 집계값만 갱신합니다.</p></article><article data-code="04"><small>BATTLE CONTRACT</small><h3>PROJECT V V3</h3><p>고유효과·마법카드·장비 보정을 포함한 PixiJS 전투를 사용합니다.</p></article></section>`}

  function rosterView(d){const mine=d.membership;return `<section class="clan-roster-layout"><aside class="clan-panel clan-team-card">${mark(mine,'large')}<small>SEASON ${number(d.season?.seasonNo)} CLAN</small><h3>${esc(mine?.name||'클랜')}</h3><p>${esc(mine?.slogan||'')}</p><dl><div><dt>시즌 점수</dt><dd>${number(mine?.score)}</dd></div><div><dt>전적</dt><dd>${number(mine?.wins)}W ${number(mine?.losses)}L</dd></div><div><dt>정원</dt><dd>${number(mine?.memberCount)} / ${number(rosterLimit(d))}</dd></div></dl></aside><section class="clan-panel clan-roster"><header><small>SEASON ROSTER</small><h3>이번 시즌 편성</h3></header><div>${(d.roster||[]).map((m,index)=>`<article class="${m.memberRole==='MASTER'?'master':''}"><span>${String(index+1).padStart(2,'0')}</span><div><b>${esc(m.nickname)}</b><small>${m.memberRole==='MASTER'?'CLAN MASTER':esc(ROLE_LABEL[m.preferredRole]||'균형형')}</small></div><dl><dt>기여</dt><dd>${number(m.contributionScore)}</dd><dt>전적</dt><dd>${number(m.battleWins)}W ${number(m.battleLosses)}L</dd></dl></article>`).join('')||'<p class="clan-empty">드래프트 로스터를 구성 중입니다.</p>'}</div></section></section>`}

  function warView(d){
    if(d.season?.phase!=='ACTIVE')return `<section class="clan-panel clan-gate"><small>CLAN WAR STANDBY</small><h3>클랜전 개막 준비 중</h3><p>블라인드 드래프트가 끝나면 V3 클랜전 전장이 열립니다.</p></section>`;
    if(!d.war)return `<section class="clan-panel clan-gate"><small>ROUND BYE</small><h3>이번 라운드 상대 배정 대기</h3><p>대진 수가 홀수인 경우 다음 라운드로 자동 진출합니다.</p></section>`;
    const mine=d.membership,isA=Number(d.war.clanAId)===Number(mine.clanId),myScore=isA?d.war.scoreA:d.war.scoreB,enemyScore=isA?d.war.scoreB:d.war.scoreA,enemy=d.teams.find(t=>t.clanId===(isA?d.war.clanBId:d.war.clanAId)),energy=d.war.energy||{},remaining=Number((energy.usesRemaining??d.war.attacksRemaining)||0),limit=Number(energy.useLimit||d.war.attackLimit||21),availableCount=Number(d.war.availableOpponentCount||0),open=d.war.status==='ACTIVE'&&energy.windowOpen!==false;
    if(!open)return `<section class="clan-war-score is-scheduled"><article style="--clan-primary:${esc(mine.primaryColor)}">${mark(mine)}<small>MY CLAN · POINT</small><h3>${esc(mine.name)}</h3><b>${number(myScore)}</b></article><div><small>ROUND ${number(d.war.roundNo)} · SCHEDULED</small><strong>VS</strong><em class="clan-war-ops">60분 승점 대진</em><span>${time(d.war.startsAt)} 후 개방</span></div><article class="enemy" style="--clan-primary:${esc(enemy?.primaryColor||'#ff556f')}">${mark(enemy)}<small>OPPONENT · POINT</small><h3>${esc(enemy?.name||'상대 클랜')}</h3><b>${number(enemyScore)}</b></article></section><section class="clan-panel clan-gate"><small>WAR WINDOW LOCKED</small><h3>정시 개방 대기</h3><p>개방 후 60분 동안 승리 1회당 1승점을 쌓습니다. 행동력은 10으로 시작해 5분마다 1씩 회복됩니다.</p></section>`;
    const canFight=energy.canAttack!==false&&remaining>0&&d.war.liveDeckReady!==false&&availableCount>0,label=remaining<=0?'개인 사용 상한 소진':Number(energy.available||0)<Number(energy.cost||1)?'행동력 회복 대기':d.war.liveDeckReady===false?'랭크전 덱 저장 필요':availableCount<=0?'매칭 풀 회복 대기':'랜덤 매칭 시작';
    return `<section class="clan-war-score"><article style="--clan-primary:${esc(mine.primaryColor)}">${mark(mine)}<small>MY CLAN · POINT</small><h3>${esc(mine.name)}</h3><b>${number(myScore)}</b></article><div><small>ROUND ${number(d.war.roundNo)} · 60 MIN</small><strong>VS</strong><em class="clan-war-ops clan-war-energy">행동력 ${number(energy.available)} / ${number(energy.cap)} · 사용 ${number(d.war.attacksUsed)} / ${number(limit)}</em><span>${time(d.war.endsAt)} 남음${energy.nextEnergyAt?` · 다음 +1 ${time(energy.nextEnergyAt)}`:''}</span></div><article class="enemy" style="--clan-primary:${esc(enemy?.primaryColor||'#ff556f')}">${mark(enemy)}<small>OPPONENT · POINT</small><h3>${esc(enemy?.name||'상대 클랜')}</h3><b>${number(enemyScore)}</b></article></section><section class="clan-panel clan-targets clan-random-match"><header><div><small>PROJECT V V3 · RANDOM QUEUE</small><h3>전투력 제한 없는 랜덤 매칭</h3><p>버튼을 누르는 순간 서버가 가능한 상대 1명을 무작위 배정합니다. 실제 전투는 양쪽의 최신 랭크전 덱 5장으로 계산됩니다.</p></div><em>${number(d.war.battleCount)} BATTLES · WIN +${number(d.rules?.scorePerWin||1)}</em></header><div class="clan-random-console"><i aria-hidden="true"></i><div><small>RANDOM OPPONENT POOL</small><b>${availableCount>0?`매칭 가능 ${number(availableCount)}명`:'매칭 풀 대기'}</b><span>동일 상대 1회 · 승리 클랜 +${number(d.rules?.scorePerWin||1)}승점 · 60분 총점으로 승부</span></div><button type="button" data-clan-fight ${canFight?'':'disabled'}>${label}</button></div></section>`;
  }

  function settlementPanel(d){if(!d.settlement)return'';const champion=(d.teams||[]).find(team=>Number(team.clanId)===Number(d.settlement.championClanId)),paid=d.settlement.rewardStatus==='PAID';return `<section class="clan-panel clan-settlement"><small>SEASON SETTLEMENT</small><h3>${esc(champion?.name||'시즌 우승 클랜')} 정산 완료</h3><p>${paid?'중복 방지 영수증으로 시즌 보상 지급이 완료됐습니다.':'TEST 또는 보상 OFF 상태로 경제 보상 없이 트로피·전적만 반영됐습니다.'}</p><em>${esc(d.settlement.rewardStatus||'DISABLED_TEST')}</em></section>`}
  function rankView(d){return `${settlementPanel(d)}<section class="clan-panel clan-ranking"><header><small>SEASON CLAN RANKING</small><h3>클랜 순위</h3><p>점수 · 승리 · 드래프트 순서 기준</p></header><div>${(d.teams||[]).map((team,index)=>`<article class="${d.membership?.clanId===team.clanId?'mine':''}"><strong>${String(index+1).padStart(2,'0')}</strong>${mark(team)}<div><b>${esc(team.name)}</b><small>${esc(team.masterNickname)} · ${number(team.memberCount)}/20</small></div><dl><dt>SCORE</dt><dd>${number(team.score)}</dd><dt>RECORD</dt><dd>${number(team.wins)}W ${number(team.losses)}L</dd></dl></article>`).join('')||'<p class="clan-empty">드래프트가 시작되면 클랜 순위가 공개됩니다.</p>'}</div></section>`}

  function content(d){if(state.tab==='roster')return rosterView(d);if(state.tab==='war')return warView(d);if(state.tab==='rank')return rankView(d);return commandView(d)}
  function render(){const root=document.getElementById('clanRoot');if(!root)return;if(state.loading&&!state.data){root.outerHTML=loadingView();return}if(state.error&&!state.data){root.innerHTML=`<section class="clan-error"><small>CLAN NETWORK ERROR</small><h2>클랜 정보를 불러오지 못했습니다</h2><p>${esc(state.error)}</p><button type="button" data-clan-refresh>다시 연결</button></section>`;bindDom();return}const d=state.data;root.innerHTML=`${phaseHero(d)}${ruleStrip(d)}${nav(d)}<div class="clan-view">${content(d)}</div>`;bindDom()}

  async function load(force=false){if(state.loading)return;state.loading=true;state.error='';render();try{state.data=await state.ctx.apiRequest(`clan/overview${force?'?fresh=1':''}`,{},force?{timeoutMs:15000}:{ttl:2500,timeoutMs:15000})}catch(error){state.error=error.message||'클랜 서버 연결 실패'}finally{state.loading=false;render()}}
  async function mutate(path,body,button){if(button){button.disabled=true;button.dataset.label=button.textContent;button.textContent='처리 중'}try{const result=await state.ctx.apiRequest(path,{method:'POST',body:JSON.stringify(body)},{timeoutMs:20000});state.data=result.state||state.data;state.ctx.clearApiCache?.('clan/overview');render();return result}catch(error){alert(error.message||'요청을 처리하지 못했습니다.')}finally{if(button&&document.body.contains(button)){button.disabled=false;button.textContent=button.dataset.label||'다시 시도'}}}

  async function fight(button){
    if(button){button.disabled=true;button.textContent='랜덤 상대 배정 중'}const ctx=state.ctx,modal=document.getElementById('modal'),mine=state.data?.membership;
    try{
      await ctx.ensureFeatureResources('battleV2');if(!global.ProjectVBattleV3Live?.ready?.())throw new Error('V3 전투 리소스를 불러오지 못했습니다.');
      const early=ctx.prepareImmediateBattleV3Entry?.({modal,mode:'PVP',playerName:mine?.name||'MY CLAN',opponentName:'RANDOM MATCH'});let stage=early?.stage,phase=early?.phase,msg=early?.msg;if(phase)phase.textContent='랜덤 상대 배정';
      const data=await ctx.apiRequest('clan/war/fight',{method:'POST',body:JSON.stringify({requestId:global.crypto?.randomUUID?.()||`${Date.now()}-${Math.random()}`})},{timeoutMs:25000});if(!data?.battleV2)throw new Error('클랜전 V3 전투 데이터를 받지 못했습니다.');
      const live=global.prepareBattleV2LiveLoading({modal,mode:'PVP',playerName:mine?.name||'MY CLAN',opponentName:data.opponent?.nickname||'OPPONENT'});stage=live.stage;phase=live.phase;msg=live.msg;ctx.ensureBattleSoundButton?.(stage);await global.playPvpBattleV2Live({stage,phase,msg,modal,data});
      const won=data.result==='WIN',point=number(data.clanWar?.pointsAwarded||1);stage.classList.add(won?'battle-win-v863':'battle-lose-v863');phase.textContent=won?'CLAN VICTORY':'CLAN DEFEAT';ctx.battleSfx?.(won?'victory':'defeat');msg.innerHTML=`<div class="clan-v3-result ${won?'win':'lose'}"><small>SOOPKETMON · CLAN WAR · RANDOM MATCH</small><strong>${won?'VICTORY':'DEFEAT'}</strong><div><b>${number(data.attackerPower)}</b><i>VS</i><b>${number(data.defenderPower)}</b></div><span>${won?`우리 클랜 +${point}승점`:`상대 클랜 +${point}승점`} · 최신 랭크전 덱 반영</span><button type="button" data-clan-battle-close>클랜전으로 돌아가기</button></div>`;msg.classList.add('is-visible');
      const close=()=>{modal.__battleV2Renderer?.destroy?.();modal.__battleV2Renderer=null;modal.onclick=null;modal.className='modal';modal.innerHTML='';state.tab='war';ctx.renderShell('clan')};setTimeout(()=>{modal.onclick=close;modal.querySelector('[data-clan-battle-close]')?.addEventListener('click',event=>{event.stopPropagation();close()})},250);
    }catch(error){if(modal){modal.__battleV2Renderer?.destroy?.();modal.__battleV2Renderer=null;modal.className='modal';modal.innerHTML=''}alert(error.message||'클랜전 V3 전투를 시작하지 못했습니다.');if(button&&document.body.contains(button)){button.disabled=false;button.textContent='랜덤 매칭 시작'}}
  }

  function bindDom(){
    document.querySelectorAll('[data-clan-tab]').forEach(button=>button.onclick=()=>{state.tab=button.dataset.clanTab;render()});document.querySelectorAll('[data-clan-refresh]').forEach(button=>button.onclick=()=>load(true));document.querySelectorAll('[data-clan-route]').forEach(button=>button.onclick=()=>state.ctx.renderShell(button.dataset.clanRoute));
    document.querySelector('[data-clan-register-form]')?.addEventListener('submit',event=>{event.preventDefault();const form=event.currentTarget;void mutate('clan/register',{preferredRole:form.preferredRole.value,activityWindow:form.activityWindow.value},form.querySelector('button[type=submit]'))});
    document.querySelector('[data-clan-identity-form]')?.addEventListener('submit',event=>{event.preventDefault();const form=event.currentTarget;void mutate('clan/identity',{slogan:form.slogan.value},form.querySelector('button[type=submit]'))});
    document.querySelectorAll('[data-clan-pick]').forEach(button=>button.onclick=()=>{if(confirm('이 후보를 지명하면 되돌릴 수 없습니다. 진행할까요?'))void mutate('clan/draft/pick',{candidateKey:button.dataset.clanPick},button)});document.querySelectorAll('[data-clan-fight]').forEach(button=>button.onclick=()=>void fight(button));
    document.querySelectorAll('[data-clan-test]').forEach(button=>button.onclick=()=>{const action=button.dataset.clanTest,limit=participantLimit(state.data),messages={bootstrap:`PLAY DK 인증·랭크전 덱 계정 최대 ${number(limit)}명으로 비공개 테스트 풀을 구성할까요?`,activate:'남은 지명을 자동 완료하고 V3 클랜전을 개막할까요?',settle:'현재 점수로 테스트 시즌을 즉시 정산할까요? 코인·아이템 보상은 지급되지 않습니다.'};if(!confirm(messages[action]||'테스트 작업을 실행할까요?'))return;const path=action==='bootstrap'?'clan/admin/test-bootstrap':action==='activate'?'clan/admin/test-activate':'clan/admin/test-settle';void mutate(path,action==='bootstrap'?{limit}: {},button)});
  }
  function bind(ctx){state.ctx=ctx;void load()}
  function stop(){state.loading=false}
  global.ClanV1={view,bind,stop,state};
})(window);
