import {jointAccountRequest as request} from './joint-account-transport.mjs';
import {LOOT_SOURCE_LABELS,PIG_COIN_IMAGE,pigCoinSourceSummary} from '../shared/loot-shop-policy-v1.mjs?v=7';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
// Historical card rows may reference this repository's raw GitHub assets.
// Serve those originals locally; never admit arbitrary external image URLs.
export function lootShopAsset(value){
 try{
  const url=new URL(String(value||''),'https://local.invalid');
  if(url.origin==='https://raw.githubusercontent.com'){
   const match=url.pathname.match(/^\/GoGosing1111\/cnine-card\/[A-Za-z0-9._-]+(\/assets\/.+)$/);
   return match?match[1]:'';
  }
  return url.origin==='https://local.invalid'&&url.pathname.startsWith('/assets/')?url.pathname:'';
 }catch{return '';}
}
const asset=lootShopAsset;
const fmt=v=>Number(v||0).toLocaleString('ko-KR');
const descriptions={SUPERSTAR_CHOICE:'등록된 SUPERSTAR 카드 중 원하는 카드 1장 선택',FUR_CHOICE:'등록된 FUR 카드 중 원하는 카드 1장 선택',F_BODY:'F바디 장비 1개 확정 지급',MYSTIC_EQUIPMENT:'미스틱 4종 중 각 25%로 장비 1개 랜덤 지급 · 꽝 없음',MERCENARY_PACK:'등록된 A·S등급 용병 중 카드 1장 획득',MERCENARY_SS_PACK:'등록된 SS등급 용병 중 카드 1장 확정 획득'};
const categoryArt={SUPERSTAR_CHOICE:'assets/ui/packs/superstar-card-pack-v1.png',FUR_CHOICE:'assets/ui/packs/limited-pack.png',F_BODY:'assets/ui/project-v/account-battle-suits/suits/battle-suit-appearance-02-orange-tactical-v1.png',MYSTIC_EQUIPMENT:'assets/ui/packs/prime-armory-equipment-box-v1.png',MERCENARY_PACK:'assets/ui/packs/hyper-pack-v2076.png',MERCENARY_SS_PACK:'assets/ui/packs/hyper-pack-v2076.png'};
const typeLabels={SUPERSTAR_CHOICE:'SUPERSTAR',FUR_CHOICE:'FUR',F_BODY:'F-BODY',MYSTIC_EQUIPMENT:'MYSTIC',MERCENARY_PACK:'MERCENARY · A—S',MERCENARY_SS_PACK:'MERCENARY · SS'};
const productArt=p=>asset(p.image)||asset(categoryArt[p.type]);
export function lootProductOptionsMarkup(p){
 const mystic=p.type==='MYSTIC_EQUIPMENT',mercenary=p.type==='MERCENARY_PACK',total=p.mercenaryWeights.A+p.mercenaryWeights.S;
 const note=p.type==='MERCENARY_SS_PACK'?'SS등급 100% · 등록된 SS 용병 중 균등 추첨으로 1장을 받습니다. 이미 보유한 용병도 나올 수 있습니다.':mystic?'미스틱 4종 중 각 25%로 1개를 받습니다. 꽝은 없으며 이미 보유한 장비도 나올 수 있습니다.':mercenary?['A','S'].map(rank=>rank+'등급 '+(p.mercenaryWeights[rank]/total*100).toFixed(2)+'%').join(' · ')+' · 등급 내 균등 추첨':'개봉 시 아래 카드 중 1장을 직접 선택합니다. 한정 카드의 잔여 수량에 따라 목록이 달라질 수 있습니다.';
 return `<h2>${esc(p.name)} 구성</h2><p class="loot-dialog-copy">${note}</p><div class="loot-choice-grid ${mystic?'loot-equipment-pool':''}">${p.options.map(c=>`<div class="loot-choice"><img src="${esc(asset(c.image))}" alt="" loading="lazy"><span>${esc(c.name)} · ${esc(mystic?c.chancePercent+'%':c.rank||c.grade)}</span></div>`).join('')}</div>`;
}
export function lootRewardMarkup(reward){
 const image=asset(reward.image),equipment=reward.kind==='EQUIPMENT';
 return `<h2>획득 완료</h2>${image?`<img class="loot-result" src="${esc(image)}" alt="">`:''}<p class="loot-dialog-copy"><strong>${esc(reward.name)}</strong><br>${equipment?'장비 1개를 획득했습니다.<br>장비 보관함에서 확인할 수 있습니다.':esc(reward.rank||reward.grade)+' 카드 1장을 획득했습니다.'}</p>`;
}
export function productMarkup(p,selected=false){return `<button class="loot-product" type="button" data-select="${esc(p.id)}" aria-pressed="${selected}"><img class="loot-product-thumb" src="${esc(productArt(p))}" alt=""><span><span class="loot-product-title">${esc(p.name)}</span><span class="loot-product-meta">${p.remaining===null?'교환 준비 중':p.remaining===0?'구매 완료':fmt(p.remaining)+'회 교환 가능'}</span></span><span class="loot-product-chevron" aria-hidden="true">›</span></button>`;}
export function inspectionMarkup(p,state){
 const choice=p.type.endsWith('_CHOICE'),gear=['F_BODY','MYSTIC_EQUIPMENT'].includes(p.type),ready=state.salesEnabled&&p.enabled,label=p.remaining===0?'구매 완료':!ready?'교환 준비 중':p.canBuy?(p.type==='MYSTIC_EQUIPMENT'?'랜덤 장비 교환':'확정 교환'):state.pigCoins<p.price?'피그 코인 부족':'현재 교환 불가';
 const hint=!ready?'상품과 가격이 확정되면 교환이 시작됩니다.':p.remaining===0?'이 상품의 계정 구매 한도를 모두 사용했습니다.':p.canBuy?'교환할 내용을 확인한 뒤 코인이 차감됩니다.':'보유 코인과 상품 상태를 확인하세요.';
 const detail=p.type==='MYSTIC_EQUIPMENT'?'4종 각 25% · 장비 1개':choice?'카드 1장 직접 선택':gear?'장비 1개 확정 지급':p.type==='MERCENARY_SS_PACK'?'SS등급 용병 1장 확정':'A·S등급 중 용병 1장';
 return `<div class="loot-stage" data-type="${esc(p.type)}"><div class="loot-stage-top"><span>SUPPLY DISPLAY</span><b>${choice?'선택팩':gear?'장비':'용병 카드팩'}</b></div><div class="loot-stage-orbit"></div><img class="loot-stage-art" src="${esc(productArt(p))}" alt="${esc(p.name)}"><div class="loot-stage-caption"><p>${typeLabels[p.type]}</p><span>${p.type==='MYSTIC_EQUIPMENT'?'4종 균등 추첨 · 상자는 품목 안내 이미지입니다.':choice?'원하는 카드를 선택하는 전리품':p.type==='MERCENARY_PACK'?'A·S등급 전용 상품 · 팩 외형은 공용 이미지입니다.':p.type==='MERCENARY_SS_PACK'?'SS등급 전용 상품 · 팩 외형은 공용 이미지입니다.':'전리품 교환소'}</span></div></div>
 <div class="loot-detail"><p class="loot-detail-label">${typeLabels[p.type]} / EXCHANGE</p><h2>${esc(p.name)}</h2><p class="loot-detail-description">${esc(descriptions[p.type])}</p><dl class="loot-detail-dl"><div><dt>획득 방식</dt><dd>${detail}</dd></div><div><dt>계정 구매 한도</dt><dd>${p.accountLimit===null?'설정 예정':fmt(p.accountLimit)+'회'}</dd></div><div><dt>남은 교환 횟수</dt><dd>${p.remaining===null?'설정 예정':fmt(p.remaining)+'회'}</dd></div></dl>${p.accountLimit&&p.accountLimit<=10?'<div class="loot-limit-dots" aria-hidden="true">'+Array.from({length:p.accountLimit},(_,i)=>'<i class="'+(i<p.bought?'used':'')+'"></i>').join('')+'</div>':''}<p class="loot-detail-note">구매 횟수는 계정에 누적됩니다.<br>${choice?'교환한 팩은 내 보관 팩에서 개봉할 수 있습니다.':gear?'교환한 장비는 장비 보관함으로 지급됩니다.':'등급별 확률과 등록 용병은 개봉 전에 확인할 수 있습니다.'}</p>${p.options?.length?`<button class="loot-pool-button" data-options="${esc(p.id)}">${choice?"선택 카드":gear?"장비·확률":"용병·확률"} 구성 보기 (${p.options.length}) ↗</button>`:""}<div class="loot-purchase-panel"><div class="loot-cost"><span>필요 피그 코인</span><strong class="${p.price===null?'unset':''}">${p.price===null?'가격 설정 예정':'<img src="/'+PIG_COIN_IMAGE+'" alt="">'+fmt(p.price)}</strong></div><button class="loot-buy" data-buy="${esc(p.id)}" ${p.canBuy?'':'disabled'}>${label}${p.canBuy?' <span aria-hidden="true">→</span>':''}</button><p class="loot-purchase-hint">${hint}</p></div></div>`;
}
export async function mountLootShop({api=request,root=document}={}){
 const byId=id=>root.getElementById(id),dialog=byId('lootDialog'),status=byId('lootStatus');let state=null,busy=false,selected=null,pending=null;
 function message(text,error=false){status.textContent=text;status.classList.toggle('error',error);}
 function drawSelection(){
  selected=state.products.find(p=>p.id===selected?.id)||state.products[0];
  for(const button of byId('lootProducts').querySelectorAll('[data-select]'))button.setAttribute('aria-pressed',String(button.dataset.select===selected?.id));
  byId('lootInspection').innerHTML=selected?inspectionMarkup(selected,state):'<p class="loot-empty">등록된 전리품이 없습니다.</p>';
 }
 function draw(){byId('lootBalance').textContent=state.pigCoins>=1e8?(state.pigCoins/1e8).toLocaleString('ko-KR',{maximumFractionDigits:1})+'억':fmt(state.pigCoins);byId('lootBalance').title=fmt(state.pigCoins);byId('lootBalance').setAttribute('aria-label',fmt(state.pigCoins));byId('lootProducts').innerHTML=state.products.map(p=>productMarkup(p,p.id===selected?.id)).join('');drawSelection();byId('lootProductCount').textContent=String(state.products.length).padStart(2,'0');byId('lootOwnedCount').textContent=fmt(state.ownedPacks.length);byId('lootStateLabel').textContent=state.salesEnabled?'교환 운영 중':'오픈 준비 중';byId('lootOwned').innerHTML=state.ownedPacks.length?state.ownedPacks.map(pack=>`<div class="loot-owned-row"><img src="${esc(productArt(pack.product))}" alt=""><span>${esc(pack.product.name)}</span><button data-pack="${esc(pack.id)}">개봉하기 ↗</button></div>`).join(''):'<p class="loot-empty">보관 중인 팩이 없습니다. 교환한 선택팩과 용병 팩이 여기에 보관됩니다.</p>';byId('lootSources').innerHTML=state.sources.map(s=>`<div class="loot-source"><b>${esc(LOOT_SOURCE_LABELS[s.code])}</b><span>${esc(pigCoinSourceSummary(s))}${state.rewardsEnabled&&s.enabled?'':' · 지급 준비 중'}</span></div>`).join('');message(state.salesEnabled?'피그 코인을 모아 원하는 전리품으로 교환하세요.':'상품 구성과 가격 확정 후 교환이 시작됩니다.');}
 async function load(){try{state=await api('loot-shop/state');draw();}catch(e){message(e.status===401?'로그인 후 전리품 상점을 이용할 수 있습니다. 로비에서 로그인해 주세요.':e.message,true);}}
 function show(html){byId('lootDialogContent').onchange=null;byId('lootDialogContent').innerHTML=html;if(!dialog.open)dialog.showModal();}
 function recoveryKey(){return `cnine_loot_pending_${state.accountId}`;}
 function savePending(){try{sessionStorage.setItem(recoveryKey(),JSON.stringify(pending));}catch{}}
 async function submit(path,body){if(busy)return;busy=true;pending={path,body,accountId:state.accountId};savePending();const button=byId('lootConfirm');if(button)button.disabled=true;try{
  const result=await api(path,{method:'POST',body});pending=null;try{sessionStorage.removeItem(recoveryKey());}catch{}state=result.state;draw();
  if(result.reward){show(lootRewardMarkup(result.reward));}else show(`<h2>교환 완료</h2><p class="loot-dialog-copy">${esc(result.product.name)}을 받았습니다.<br>${['F_BODY','MYSTIC_EQUIPMENT'].includes(result.product.type)?'장비 보관함에서 확인할 수 있습니다.':'아래 내 보관 팩에서 개봉할 수 있습니다.'}</p>`);
 }catch(e){message(e.message,true);if(e.status>=400&&e.status<500&&e.retryable!==true&&![408,423,429].includes(e.status)){pending=null;try{sessionStorage.removeItem(recoveryKey());}catch{}show(`<h2>교환을 진행할 수 없습니다</h2><p class="loot-dialog-copy">${esc(e.message)}</p>`);await load();return;}show(`<h2>교환 상태 확인</h2><p class="loot-dialog-copy">${esc(e.message)}</p><p class="loot-dialog-copy">같은 요청으로 다시 확인하면 중복 구매되지 않습니다.</p><button class="loot-action" id="lootRetry">다시 확인</button>`);byId('lootRetry').onclick=()=>submit(path,body);}finally{busy=false;}}
 byId('lootProducts').onclick=e=>{const button=e.target.closest('[data-select]');if(!button||busy)return;selected=state.products.find(p=>p.id===button.dataset.select);drawSelection();};
 byId('lootRefresh').onclick=()=>{if(!busy)void load();};
 byId('lootInspection').onclick=e=>{const optionsButton=e.target.closest('[data-options]');if(optionsButton&&!busy){const p=state.products.find(p=>p.id===optionsButton.dataset.options);show(lootProductOptionsMarkup(p));return;}const button=e.target.closest('[data-buy]');if(!button||busy||pending)return;selected=state.products.find(p=>p.id===button.dataset.buy);if(!selected?.canBuy)return;const product=selected;show(`<h2>${esc(product.name)}</h2><p class="loot-dialog-copy">${esc(descriptions[product.type])}<br>피그 코인 <strong>${fmt(product.price)}</strong>개를 사용합니다.<br>교환 후 ${fmt(product.remaining-1)}회 구매할 수 있습니다.</p><div class="loot-confirm"><p>이 상품은 계정별 구매 한도가 있습니다.</p><button class="loot-action" id="lootConfirm">${product.type==='MYSTIC_EQUIPMENT'?'랜덤 장비 교환':'확정 교환'}</button></div>`);byId('lootConfirm').onclick=()=>submit('loot-shop/purchase',{productId:product.id,requestId:crypto.randomUUID()});};
 byId('lootOwned').onclick=async e=>{const button=e.target.closest('[data-pack]');if(!button||busy||pending)return;busy=true;try{const pack=await api(`loot-shop/pack?id=${encodeURIComponent(button.dataset.pack)}`),choice=pack.product.type.endsWith('_CHOICE');show(`<h2>${esc(pack.product.name)}</h2><p class="loot-dialog-copy">${choice?'획득할 카드를 직접 선택하세요.':'용병 카드 1장을 획득합니다. 등급별 확률은 아래와 같습니다.'}</p>${choice?`<div class="loot-choice-grid">${pack.cards.map(c=>`<label class="loot-choice"><input type="radio" name="lootCard" value="${esc(c.id)}"><img src="${esc(asset(c.image))}" alt="" loading="lazy"><span>${esc(c.name)}</span></label>`).join('')}</div>`:`<p class="loot-dialog-copy">${pack.product.type==='MERCENARY_SS_PACK'?'SS등급 100%':['A','S'].map(rank=>`${rank}등급 ${(pack.product.mercenaryWeights[rank]/(pack.product.mercenaryWeights.A+pack.product.mercenaryWeights.S)*100).toFixed(2)}%`).join(' · ')}<br>등급 내 등록된 용병은 동일한 확률로 획득합니다.</p>`}<button class="loot-action" id="lootConfirm" ${choice?'disabled':''}>${choice?'선택 카드 받기':'팩 개봉하기'}</button>`);byId('lootDialogContent').onchange=()=>{byId('lootConfirm').disabled=!root.querySelector('input[name="lootCard"]:checked');};byId('lootConfirm').onclick=()=>{const selectedCard=root.querySelector('input[name="lootCard"]:checked')?.value;if(choice&&!selectedCard)return;submit('loot-shop/open',{packId:pack.packId,requestId:crypto.randomUUID(),...(choice?{cardId:selectedCard}:{})});};}catch(e){message(e.message,true);}finally{busy=false;}};
 dialog.addEventListener('cancel',e=>{if(busy)e.preventDefault();});dialog.querySelector('form').onsubmit=e=>{if(busy)e.preventDefault();};
 await load();if(state){try{const saved=JSON.parse(sessionStorage.getItem(recoveryKey())||'null');if(saved?.accountId===state.accountId&&['loot-shop/purchase','loot-shop/open'].includes(saved.path)&&saved.body?.requestId){pending=saved;show('<h2>진행 중인 교환 확인</h2><p class="loot-dialog-copy">이전 요청의 결과를 확인한 뒤 새로운 교환을 진행할 수 있습니다.</p><button class="loot-action" id="lootRetry">결과 확인</button>');byId('lootRetry').onclick=()=>submit(saved.path,saved.body);}}catch{}}
 return {reload:load};
}
if(typeof document!=='undefined'&&document.getElementById('lootRoot'))void mountLootShop();
