(()=>{
  'use strict';
  const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const fmt=value=>Number(value||0).toLocaleString('ko-KR');
  const requestId=()=>`WORKSHOP-${Date.now()}-${crypto.randomUUID?.()||Math.random().toString(36).slice(2)}`;
  const api=(path,options={})=>window.apiRequest(path,options,{ttl:0,timeoutMs:30000});
  let state=null,category='VEHICLE',selectedId=0,paymentByRecipe=new Map(),busy=false;

  function view(){return `<section class="workshop-v1668"><div class="workshop-ambient-v1668"><i></i><i></i><i></i></div><div id="workshopRootV1668" class="workshop-root-v1668"><div class="workshop-loading-v1668"><span></span><b>제작 설비 가동 중</b><small>레시피와 보유 재료를 확인하고 있습니다.</small></div></div></section>`}

  function paymentOptions(recipe){
    const mode=String(recipe.payment_mode||'COIN_OR_MASTER_STAR');
    if(mode==='COIN_ONLY')return[{id:'COIN',label:'코인',cost:recipe.coin_cost,icon:'◇'}];
    if(mode==='MASTER_STAR_ONLY')return[{id:'MASTER_STAR',label:'마스터의 별',cost:recipe.master_star_cost,icon:'✦'}];
    if(mode==='BOTH')return[{id:'BOTH',label:'코인 + 마스터의 별',cost:`${fmt(recipe.coin_cost)} + ${fmt(recipe.master_star_cost)}`,icon:'◆'}];
    return[{id:'COIN',label:'코인 조립',cost:recipe.coin_cost,icon:'◇'},{id:'MASTER_STAR',label:'마스터의 별 조립',cost:recipe.master_star_cost,icon:'✦'}];
  }
  function selectedRecipe(){const list=(state?.recipes||[]).filter(recipe=>recipe.category===category);return list.find(recipe=>Number(recipe.id)===Number(selectedId))||list[0]||null}
  function payment(recipe){const options=paymentOptions(recipe),current=paymentByRecipe.get(Number(recipe.id));return options.find(option=>option.id===current)?.id||options[0]?.id||'COIN'}
  function materialOwned(material){return Number(state?.inventory?.[material.item_code]?.quantity||0)}
  function affordability(recipe,paymentType){if(paymentType==='COIN')return Number(state.wallet.coin)>=Number(recipe.coin_cost);if(paymentType==='MASTER_STAR')return Number(state.wallet.masterStars)>=Number(recipe.master_star_cost);if(paymentType==='BOTH')return Number(state.wallet.coin)>=Number(recipe.coin_cost)&&Number(state.wallet.masterStars)>=Number(recipe.master_star_cost);return false}
  function canCraft(recipe){return !recipe.owned&&recipe.materials.every(material=>materialOwned(material)>=Number(material.quantity))&&affordability(recipe,payment(recipe))}

  function materialStrip(){
    const categoryCodes=[...new Set((state.recipes||[]).filter(recipe=>recipe.category===category).flatMap(recipe=>(recipe.materials||[]).map(material=>material.item_code)))];
    const codes=(categoryCodes.length?categoryCodes:['VEHICLE_PART_TIRE','VEHICLE_PART_FRAME','VEHICLE_PART_ENGINE']).slice(0,3);
    return `<div class="workshop-material-vault-v1668">${codes.map(code=>{const item=state.inventory?.[code]||{};return `<article><div><img src="${esc(item.image_url||'')}" alt="${esc(item.name||code)}"></div><span><small>CRAFT MATERIAL</small><b>${esc(item.name||code)}</b></span><strong>${fmt(item.quantity)}</strong></article>`}).join('')}</div>`;
  }
  function categoryTabs(){return `<nav class="workshop-tabs-v1668">${(state.categories||[]).map(item=>`<button type="button" data-workshop-category="${item.id}" class="${category===item.id?'active':''}" ${item.enabled?'':'disabled'}><i>${item.id==='VEHICLE'?'◆':'✧'}</i><span><b>${esc(item.name)}</b><small>${item.id==='VEHICLE'?'부품을 결합해 이동수단 완성':'장비 합성 확장 슬롯'}</small></span>${item.enabled?'':'<em>COMING SOON</em>'}</button>`).join('')}</nav>`}
  function recipeCard(recipe){const selected=Number(recipe.id)===Number(selectedId),ready=canCraft(recipe);return `<button type="button" class="workshop-recipe-card-v1668 ${selected?'active':''} ${recipe.owned?'owned':''}" data-workshop-recipe="${recipe.id}"><div class="workshop-recipe-image-v1668">${recipe.output_image?`<img src="${esc(recipe.output_image)}" alt="${esc(recipe.output_name)}">`:'<span>◆</span>'}${recipe.is_featured?'<em>FEATURED</em>':''}</div><div><small>${esc(recipe.output_rarity||recipe.category)}</small><b>${esc(recipe.name)}</b><span>${recipe.owned?'이미 보유':ready?'제작 가능':'재료 확인 필요'}</span></div><i>›</i></button>`}
  function materialRequirement(material){const owned=materialOwned(material),need=Number(material.quantity||0),enough=owned>=need;return `<article class="workshop-required-item-v1668 ${enough?'ready':'short'}"><div><img src="${esc(material.image_url||state.inventory?.[material.item_code]?.image_url||'')}" alt=""></div><span><small>${esc(material.item_name||material.item_code)}</small><b>${fmt(owned)} <i>/</i> ${fmt(need)}</b></span><em>${enough?'준비 완료':`${fmt(need-owned)}개 부족`}</em></article>`}
  function paymentPanel(recipe){const selected=payment(recipe);return `<div class="workshop-payment-v1668"><div class="workshop-section-title-v1668"><span><small>ASSEMBLY ENERGY</small><b>조립 비용 선택</b></span><em>한 가지 방식만 사용</em></div><div class="workshop-payment-options-v1668">${paymentOptions(recipe).map(option=>{const enough=affordability(recipe,option.id);return `<button type="button" data-workshop-payment="${option.id}" class="${selected===option.id?'active':''} ${enough?'':'short'}"><i>${option.icon}</i><span><small>${option.label}</small><b>${typeof option.cost==='number'?fmt(option.cost):option.cost}</b></span><em>${enough?'사용 가능':'부족'}</em></button>`}).join('')}</div></div>`}
  function detail(recipe){if(!recipe)return `<div class="workshop-empty-v1668"><i>⌁</i><b>등록된 제작 레시피가 없습니다.</b><span>CMS에서 제작 결과와 재료를 등록하면 이곳에 표시됩니다.</span></div>`;const ready=canCraft(recipe),vehicle=recipe.category==='VEHICLE',resultLabel=vehicle?'차량':'장비';return `<section class="workshop-blueprint-v1668"><div class="workshop-blueprint-head-v1668"><div><small>BLUEPRINT · ${esc(recipe.code)}</small><h2>${esc(recipe.name)}</h2><p>${esc(recipe.description||'보유 부품을 결합해 완성품을 제작합니다.')}</p></div><span class="workshop-rate-v1668"><small>SUCCESS</small><b>${Number(recipe.success_rate||100).toFixed(Number(recipe.success_rate)%1?1:0)}%</b></span></div><div class="workshop-assembly-stage-v1668"><div class="workshop-grid-floor-v1668"></div><div class="workshop-output-aura-v1668"></div>${recipe.output_image?`<img src="${esc(recipe.output_image)}" alt="${esc(recipe.output_name)}">`:'<span>◆</span>'}<div class="workshop-scan-v1668"></div><aside><small>OUTPUT</small><b>${esc(recipe.output_name)}</b><span>${esc(recipe.output_rarity)} · PVE +${fmt(recipe.output_pve)} · PVP +${fmt(recipe.output_pvp)}</span></aside></div><div class="workshop-materials-v1668"><div class="workshop-section-title-v1668"><span><small>REQUIRED COMPONENTS</small><b>필요 부품</b></span><em>${recipe.materials.filter(material=>materialOwned(material)>=Number(material.quantity)).length} / ${recipe.materials.length} 준비</em></div><div class="workshop-required-grid-v1668">${recipe.materials.map(materialRequirement).join('')}</div></div>${paymentPanel(recipe)}<button type="button" id="workshopCraftV1668" class="workshop-craft-button-v1668" ${ready&&!busy?'':'disabled'}><span>${recipe.owned?`이미 보유한 ${resultLabel}`:busy?'조립 공정 진행 중':ready?`${resultLabel} 제작 시작`:'재료 또는 비용 부족'}</span><small>${ready?`부품 투입 후 완성 ${resultLabel}이 ${vehicle?'차고':'장비함'}로 지급됩니다.`:'필요 수량과 보유 재화를 확인하세요.'}</small></button></section>`}

  function render(){
    const root=document.getElementById('workshopRootV1668');if(!root||!state)return;
    const list=(state.recipes||[]).filter(recipe=>recipe.category===category);if(!list.some(recipe=>Number(recipe.id)===Number(selectedId)))selectedId=Number(list[0]?.id||0);
    root.innerHTML=`<header class="workshop-hero-v1668"><div class="workshop-emblem-v1668"><i></i><b>W</b></div><div><small>SOOPKETMON MASTER WORKS</small><h1>제작소</h1><p>전장에서 회수한 재료를 설계도에 맞춰 새로운 장비로 완성합니다.</p></div><div class="workshop-wallet-v1668"><span><small>COIN</small><b>${fmt(state.wallet.coin)}</b></span><span><small>MASTER STAR</small><b>${fmt(state.wallet.masterStars)}</b></span></div></header>${materialStrip()}${categoryTabs()}<div class="workshop-main-v1668"><aside class="workshop-recipe-list-v1668"><div class="workshop-list-title-v1668"><small>AVAILABLE BLUEPRINTS</small><b>${category==='VEHICLE'?'차량 설계도':'장비 합성식'} ${list.length}</b></div>${list.map(recipeCard).join('')||'<p>공개된 레시피가 없습니다.</p>'}</aside>${detail(selectedRecipe())}</div><footer class="workshop-future-v1668"><i>✦</i><div><b>확장형 제작 엔진</b><span>차량 제작과 장비 합성은 같은 재료·레시피·영수증 구조를 사용합니다. 장비 합성 레시피가 등록되면 별도 업데이트 없이 이 제작소에서 열립니다.</span></div></footer>`;
    root.querySelectorAll('[data-workshop-category]').forEach(button=>button.onclick=()=>{category=button.dataset.workshopCategory;selectedId=0;render()});
    root.querySelectorAll('[data-workshop-recipe]').forEach(button=>button.onclick=()=>{selectedId=Number(button.dataset.workshopRecipe);render()});
    root.querySelectorAll('[data-workshop-payment]').forEach(button=>button.onclick=()=>{paymentByRecipe.set(Number(selectedRecipe()?.id),button.dataset.workshopPayment);render()});
    root.querySelector('#workshopCraftV1668')?.addEventListener('click',craft);
  }

  async function load(){const root=document.getElementById('workshopRootV1668');try{state=await api('workshop');render()}catch(error){if(root)root.innerHTML=`<div class="workshop-error-v1668"><b>제작소 연결 실패</b><span>${esc(error.message)}</span><button type="button">다시 시도</button></div>`;root?.querySelector('button')?.addEventListener('click',load)}}
  async function craft(){const recipe=selectedRecipe();if(!recipe||busy||!canCraft(recipe))return;const type=payment(recipe),label=type==='COIN'?`${fmt(recipe.coin_cost)}코인`:type==='MASTER_STAR'?`마스터의 별 ${fmt(recipe.master_star_cost)}개`:`${fmt(recipe.coin_cost)}코인 + 마스터의 별 ${fmt(recipe.master_star_cost)}개`;if(!confirm(`${recipe.name}\n\n부품과 ${label}를 사용해 제작하시겠습니까?`))return;busy=true;render();try{const data=await api('workshop/craft',{method:'POST',body:JSON.stringify({recipeId:recipe.id,paymentType:type,requestId:requestId()})});state=data.state||await api('workshop');syncUser(data);showResult(data);render()}catch(error){alert(error.message);state=await api('workshop').catch(()=>state);render()}finally{busy=false;render()}}
  function syncUser(data){try{const user=window.loadUser?.();if(user&&data.state?.wallet){user.coin=Number(data.state.wallet.coin);window.saveUser?.(user)}window.clearApiCache?.('inventory');window.clearApiCache?.('character');window.dispatchEvent(new CustomEvent('cnine:workshop-crafted',{detail:data}))}catch(_){}}
  function showResult(data){const modal=document.getElementById('modal');if(!modal)return;modal.className='modal show workshop-result-modal-v1668';modal.innerHTML=`<div class="workshop-result-v1668 ${data.success?'success':'failure'}"><div class="workshop-result-light-v1668"></div><small>ASSEMBLY ${data.success?'COMPLETE':'FAILED'}</small><h2>${data.success?'제작 완료':'제작 실패'}</h2>${data.output?.image?`<img src="${esc(data.output.image)}" alt="">`:'<i>◆</i>'}<b>${esc(data.output?.name||data.recipeName)}</b><p>${data.success?'완성품이 차고 또는 인벤토리에 지급되었습니다.':'투입한 재료는 소모되었습니다.'}</p><button type="button">확인</button></div>`;modal.querySelector('button').onclick=()=>{modal.className='modal';modal.innerHTML=''}}

  window.workshopView=view;
  window.bindWorkshopView=load;
})();
