const ITEM_CODE='BLACK_MIRACLE_PACK';
const SETTINGS_KEY='black_miracle_pack_settings_v1485';
const IMAGE='assets/ui/packs/black-miracle-pack-v1485-768.jpg';
const DEFAULTS={enabled:true,name:'블랙 미라클 팩',image:IMAGE,sources:{PVE:{enabled:true,rate:.01,quantity:1},PVE_AUTO:{enabled:true,rate:.005,quantity:1},PVP:{enabled:true,rate:.01,quantity:1},TOWER:{enabled:true,rate:.05,quantity:1},RAID:{enabled:true,rate:.1,quantity:1},RIFT:{enabled:true,rate:.1,quantity:1},CAPTAIN:{enabled:true,rate:.02,quantity:1}},rewards:{MYTHIC_EQUIPMENT:{rate:25},MYTHIC_VEHICLE:{rate:15},MASTER_STAR:{rate:35,min:50,max:100},COIN:{rate:25,min:1000000,max:1000000}},fallbackMasterStars:100};
let ready=null;
const number=(v,min,max,d=0)=>Math.max(min,Math.min(max,Number.isFinite(Number(v))?Number(v):d));
const integer=(v,min,max,d=0)=>Math.floor(number(v,min,max,d));
const bool=(v,d=true)=>v===undefined||v===null?d:(v===true||v===1||String(v)==='1');
const parse=(v,f)=>{try{return JSON.parse(v)||f}catch{return f}};
function clean(raw={}){const sources={};for(const [key,base] of Object.entries(DEFAULTS.sources)){const x=raw.sources?.[key]||{};sources[key]={enabled:bool(x.enabled,base.enabled),rate:number(x.rate,0,100,base.rate),quantity:integer(x.quantity,1,10,base.quantity)}}const rewards={};for(const [key,base] of Object.entries(DEFAULTS.rewards)){const x=raw.rewards?.[key]||{};rewards[key]={rate:number(x.rate,0,100,base.rate)};if(key==='MASTER_STAR'||key==='COIN'){rewards[key].min=integer(x.min,1,100000000,base.min);rewards[key].max=integer(x.max,rewards[key].min,100000000,base.max)}}return {enabled:bool(raw.enabled,true),name:String(raw.name||DEFAULTS.name).trim().slice(0,80),image:String(raw.image||IMAGE).trim().slice(0,500),sources,rewards,fallbackMasterStars:integer(raw.fallbackMasterStars,1,1000000,100)}}
async function ensure(env){if(ready)return ready;ready=(async()=>{await env.DB.batch([
  env.DB.prepare(`CREATE TABLE IF NOT EXISTS black_miracle_pack_drop_receipts(user_id INTEGER NOT NULL,source_type TEXT NOT NULL,reference_id TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'MISSED',quantity INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(user_id,source_type,reference_id))`),
  env.DB.prepare(`CREATE TABLE IF NOT EXISTS black_miracle_pack_open_receipts(request_id TEXT PRIMARY KEY,user_id INTEGER NOT NULL,status TEXT NOT NULL DEFAULT 'PENDING',response_json TEXT,error_message TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`),
  env.DB.prepare(`INSERT INTO inventory_items(code,name,subtitle,description,category,rarity,image_url,sort_order,is_active) VALUES(?,?,?,?,?,?,?,?,1) ON CONFLICT(code) DO UPDATE SET name=excluded.name,subtitle=excluded.subtitle,description=excluded.description,category=excluded.category,rarity=excluded.rarity,image_url=excluded.image_url,is_active=1,updated_at=CURRENT_TIMESTAMP`).bind(ITEM_CODE,DEFAULTS.name,'MYTHIC JACKPOT','신화 장비·신화 이동수단·마스터의 별·100만 코인 중 하나를 획득합니다.','JACKPOT','MYTHIC',IMAGE,8)
]);return true})().catch(e=>{ready=null;throw e});return ready}
export async function blackMiracleSettings(env,{fresh=false}={}){await ensure(env);const row=await env.DB.prepare('SELECT value FROM app_meta WHERE key=?').bind(SETTINGS_KEY).first();return clean(parse(row?.value,DEFAULTS))}
export async function saveBlackMiracleSettings(env,raw){const cfg=clean(raw),total=Object.values(cfg.rewards).reduce((s,x)=>s+x.rate,0);if(Math.abs(total-100)>.0001)throw new Error(`팩 내부 보상 확률 합계는 100%여야 합니다. 현재 ${total}%입니다.`);await ensure(env);await env.DB.batch([env.DB.prepare(`INSERT INTO app_meta(key,value,updated_at) VALUES(?,?,CURRENT_TIMESTAMP) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=CURRENT_TIMESTAMP`).bind(SETTINGS_KEY,JSON.stringify(cfg)),env.DB.prepare('UPDATE inventory_items SET name=?,image_url=?,is_active=1,updated_at=CURRENT_TIMESTAMP WHERE code=?').bind(cfg.name,cfg.image,ITEM_CODE)]);return cfg}
function pick(rows){let roll=Math.random()*rows.reduce((s,x)=>s+x.rate,0);for(const x of rows){roll-=x.rate;if(roll<0)return x.key}return rows.at(-1)?.key}
export async function rollBlackMiracleDrop(env,{userId,source,referenceId}){const cfg=await blackMiracleSettings(env),type=String(source||'').toUpperCase(),rule=cfg.sources[type],ref=String(referenceId||'').slice(0,160);if(!rule?.enabled||!ref)return null;const prior=await env.DB.prepare('SELECT status,quantity FROM black_miracle_pack_drop_receipts WHERE user_id=? AND source_type=? AND reference_id=?').bind(userId,type,ref).first();if(prior)return prior.status==='GRANTED'?{itemCode:ITEM_CODE,name:cfg.name,image:cfg.image,quantity:Number(prior.quantity),reused:true}:null;const won=Math.random()*100<rule.rate,qty=won?rule.quantity:0;await env.DB.prepare("INSERT OR IGNORE INTO black_miracle_pack_drop_receipts(user_id,source_type,reference_id,status,quantity) VALUES(?,?,?,?,?)").bind(userId,type,ref,won?'GRANTED':'MISSED',qty).run();if(!won)return null;await env.DB.batch([env.DB.prepare(`INSERT INTO cnine_user_inventory(user_id,item_code,quantity,unseen_quantity,created_at,updated_at) VALUES(?,?,?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT(user_id,item_code) DO UPDATE SET quantity=quantity+excluded.quantity,unseen_quantity=unseen_quantity+excluded.unseen_quantity,updated_at=CURRENT_TIMESTAMP`).bind(userId,ITEM_CODE,qty,qty),env.DB.prepare("INSERT INTO inventory_logs(user_id,item_code,change_amount,balance_after,reason,reference_type,reference_id) SELECT ?,?,?,quantity,'CONTENT_DROP',?,? FROM cnine_user_inventory WHERE user_id=? AND item_code=?").bind(userId,ITEM_CODE,qty,type,ref,userId,ITEM_CODE)]);return {itemCode:ITEM_CODE,name:cfg.name,image:cfg.image,quantity:qty}}
async function fallbackStars(env,userId,amount,requestId){await env.DB.batch([env.DB.prepare(`INSERT INTO cnine_user_inventory(user_id,item_code,quantity,unseen_quantity,created_at,updated_at) VALUES(?,'MASTER_STAR',?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT(user_id,item_code) DO UPDATE SET quantity=quantity+excluded.quantity,unseen_quantity=unseen_quantity+excluded.unseen_quantity,updated_at=CURRENT_TIMESTAMP`).bind(userId,amount,amount),env.DB.prepare("INSERT INTO inventory_logs(user_id,item_code,change_amount,balance_after,reason,reference_type,reference_id) SELECT ?,'MASTER_STAR',?,quantity,'BLACK_MIRACLE_REWARD','INVENTORY_USE',? FROM cnine_user_inventory WHERE user_id=? AND item_code='MASTER_STAR'").bind(userId,amount,requestId,userId)]);return {type:'MASTER_STAR',label:'마스터의 별',amount}}
export async function openBlackMiraclePack(env,{userId,requestId}){await ensure(env);const prior=await env.DB.prepare('SELECT status,response_json FROM black_miracle_pack_open_receipts WHERE request_id=? AND user_id=?').bind(requestId,userId).first();if(prior?.status==='COMPLETED')return parse(prior.response_json,null);const cfg=await blackMiracleSettings(env);if(cfg.enabled!==true)throw new Error('현재 블랙 미라클 팩 사용이 중지되어 있습니다. 드랍 및 보유 수량은 유지됩니다.');if(prior)throw new Error('같은 개봉 요청을 처리 중입니다.');await env.DB.prepare("INSERT INTO black_miracle_pack_open_receipts(request_id,user_id,status) VALUES(?,?,'PENDING')").bind(requestId,userId).run();let consumed=false;try{const used=await env.DB.prepare('UPDATE cnine_user_inventory SET quantity=quantity-1,unseen_quantity=MIN(unseen_quantity,quantity-1),updated_at=CURRENT_TIMESTAMP WHERE user_id=? AND item_code=? AND quantity>0').bind(userId,ITEM_CODE).run();if(!used.meta.changes)throw new Error('보유한 블랙 미라클 팩이 없습니다.');consumed=true;const kind=pick(Object.entries(cfg.rewards).map(([key,x])=>({key,rate:x.rate})));let reward=null;
if(kind==='MYTHIC_EQUIPMENT'){const item=await env.DB.prepare(`SELECT i.* FROM character_equipment_items i WHERE i.is_active=1 AND i.is_public=1 AND UPPER(i.rarity)='MYTHIC' ORDER BY RANDOM() LIMIT 1`).first();if(item){await env.DB.prepare(`INSERT INTO user_equipment_instances(user_id,equipment_id,source_type,source_id) VALUES(?,?,'BLACK_MIRACLE',?)`).bind(userId,item.id,requestId).run();reward={type:kind,label:'신화 장비',item:{id:Number(item.id),name:item.name,image:item.image_url||'',rarity:'MYTHIC',slot:item.slot}}}}
if(kind==='MYTHIC_VEHICLE'){const item=await env.DB.prepare(`SELECT g.* FROM character_garage_items g WHERE g.is_active=1 AND g.is_public=1 AND UPPER(g.rarity)='MYTHIC' AND NOT EXISTS(SELECT 1 FROM user_garage_vehicles u WHERE u.user_id=? AND u.garage_id=g.id) ORDER BY RANDOM() LIMIT 1`).bind(userId).first();if(item){await env.DB.prepare(`INSERT INTO user_garage_vehicles(user_id,garage_id,source_type,source_id) VALUES(?,?,'BLACK_MIRACLE',?)`).bind(userId,item.id,requestId).run();reward={type:kind,label:'신화 이동수단',item:{id:Number(item.id),name:item.name,image:item.image_url||'',rarity:'MYTHIC'}}}}
if(kind==='COIN'){const x=cfg.rewards.COIN,amount=integer(Math.random()*(x.max-x.min+1)+x.min,x.min,x.max,x.min);await env.DB.prepare('UPDATE users SET coin=coin+? WHERE id=?').bind(amount,userId).run();const user=await env.DB.prepare('SELECT coin FROM users WHERE id=?').bind(userId).first();await env.DB.prepare("INSERT INTO coin_logs(user_id,change_amount,balance_after,reason) VALUES(?,?,?,'BLACK_MIRACLE_PACK')").bind(userId,amount,user.coin).run();reward={type:kind,label:'코인',amount}}
if(kind==='MASTER_STAR'){const x=cfg.rewards.MASTER_STAR;reward=await fallbackStars(env,userId,integer(Math.random()*(x.max-x.min+1)+x.min,x.min,x.max,x.min),requestId)}if(!reward)reward=await fallbackStars(env,userId,cfg.fallbackMasterStars,requestId);const remaining=Number((await env.DB.prepare('SELECT quantity FROM cnine_user_inventory WHERE user_id=? AND item_code=?').bind(userId,ITEM_CODE).first())?.quantity||0),response={ok:true,itemCode:ITEM_CODE,remaining,reward,requestId};await env.DB.batch([env.DB.prepare("INSERT INTO inventory_logs(user_id,item_code,change_amount,balance_after,reason,reference_type,reference_id) VALUES(?,?,-1,?,'BLACK_MIRACLE_OPEN','INVENTORY_USE',?)").bind(userId,ITEM_CODE,remaining,requestId),env.DB.prepare("UPDATE black_miracle_pack_open_receipts SET status='COMPLETED',response_json=?,updated_at=CURRENT_TIMESTAMP WHERE request_id=? AND user_id=?").bind(JSON.stringify(response),requestId,userId)]);return response}catch(e){if(consumed)await env.DB.prepare('UPDATE cnine_user_inventory SET quantity=quantity+1,updated_at=CURRENT_TIMESTAMP WHERE user_id=? AND item_code=?').bind(userId,ITEM_CODE).run();await env.DB.prepare("UPDATE black_miracle_pack_open_receipts SET status='FAILED',error_message=?,updated_at=CURRENT_TIMESTAMP WHERE request_id=? AND user_id=?").bind(String(e.message).slice(0,300),requestId,userId).run();throw e}}
export async function handleBlackMiracleAdmin({path,request,env,deps}){if(!path.startsWith('admin/black-miracle-pack'))return null;const user=await deps.authenticate(request,env);if(!user||!['OWNER','ADMIN'].includes(String(user.role).toUpperCase()))return deps.json({error:'관리자 권한이 필요합니다.'},403);if(request.method==='GET')return deps.json({settings:await blackMiracleSettings(env)});if(request.method==='PATCH'){try{return deps.json({ok:true,settings:await saveBlackMiracleSettings(env,(await deps.readBody(request)).settings||{})})}catch(e){return deps.json({error:e.message},400)}}return deps.json({error:'지원하지 않는 요청입니다.'},405)}
export {ITEM_CODE as BLACK_MIRACLE_PACK_CODE};
