import { readRuntimeData, cacheRuntimeData } from './_runtime_data_cache.js';

export const CLAN_CAMP_HOURS = 8;
const SCHEMA_KEY = 'safe_runtime_upgrade_v2083_clan_prison_camp';
const rows = result => result?.results || [];
const sqlTime = ms => new Date(ms).toISOString().slice(0, 19).replace('T', ' ');
const changes = result => Number(result?.meta?.changes || 0);
const fail = (message, status = 400, code = '') => { throw Object.assign(new Error(message), { status, code }); };
export const canReleaseClanCaptives = user => String(user?.role || '').toUpperCase() === 'OWNER';

export function clanCampSchema(postgres = false) {
  const int = postgres ? 'BIGINT' : 'INTEGER';
  const id = postgres ? 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY' : 'INTEGER PRIMARY KEY AUTOINCREMENT';
  return [
    `CREATE TABLE IF NOT EXISTS clan_prison_camps (
      season_id ${int} PRIMARY KEY,season_no INTEGER NOT NULL,clan_id ${int} NOT NULL,
      clan_name TEXT NOT NULL,final_rank INTEGER NOT NULL,creation_token TEXT NOT NULL,
      jailed_at TEXT NOT NULL,jailed_until TEXT NOT NULL)`,
    `CREATE TABLE IF NOT EXISTS clan_prison_captives (
      season_id ${int} NOT NULL,user_id ${int} NOT NULL,member_role TEXT NOT NULL,
      released_at TEXT,released_by ${int},release_reason TEXT NOT NULL DEFAULT '',
      PRIMARY KEY(season_id,user_id))`,
    'CREATE INDEX IF NOT EXISTS idx_clan_captives_user ON clan_prison_captives(user_id,released_at,season_id)',
    `CREATE TABLE IF NOT EXISTS clan_prison_chat (
      id ${id},user_id ${int} NOT NULL,body TEXT NOT NULL,sender_was_captive INTEGER NOT NULL,
      created_at TEXT NOT NULL)`,
    `CREATE TABLE IF NOT EXISTS clan_prison_chat_cooldowns (
      user_id ${int} PRIMARY KEY,next_at_ms ${int} NOT NULL DEFAULT 0,token TEXT)`
  ];
}

export async function ensureClanCampSchema(env) {
  if (readRuntimeData(env, SCHEMA_KEY)) return;
  const marker = await env.DB.prepare('SELECT value FROM app_meta WHERE key=?').bind(SCHEMA_KEY).first();
  if (!marker) {
    const schema = clanCampSchema(env.DB.dialect === 'postgres');
    if (env.DB.dialect === 'postgres') await env.DB.execSchema(schema);
    else await env.DB.batch(schema.map(sql => env.DB.prepare(sql)));
    await env.DB.prepare('INSERT OR IGNORE INTO app_meta(key,value) VALUES(?,?)').bind(SCHEMA_KEY, '2083').run();
  }
  cacheRuntimeData(env, SCHEMA_KEY, true, 1800000);
}

// These statements MUST share the season-completion transaction. The creation
// token prevents retries from changing the roster, resetting a sentence or re-jailing released users.
export async function clanCampSettlementStatements(env, season, settings, rankedTeams, now = Date.now()) {
  if (settings.mode !== 'ON' || season?.phase !== 'SETTLEMENT' || rankedTeams.length < 2) return [];
  const completed = await env.DB.prepare("SELECT 1 FROM clan_wars WHERE season_id=? AND status='COMPLETED' AND round_no<1000 LIMIT 1").bind(season.id).first();
  if (!completed) return [];
  await ensureClanCampSchema(env);
  const last = rankedTeams.at(-1), token = crypto.randomUUID();
  return [
    env.DB.prepare(`DELETE FROM clan_prison_chat WHERE NOT EXISTS(SELECT 1 ${ACTIVE})`).bind(sqlTime(now)),
    env.DB.prepare(`INSERT OR IGNORE INTO clan_prison_camps
      (season_id,season_no,clan_id,clan_name,final_rank,creation_token,jailed_at,jailed_until)
      VALUES(?,?,?,?,?,?,?,?)`).bind(season.id, season.season_no, last.clan_id, last.name, rankedTeams.length,
        token, sqlTime(now), sqlTime(now + CLAN_CAMP_HOURS * 3600000)),
    env.DB.prepare(`INSERT OR IGNORE INTO clan_prison_captives(season_id,user_id,member_role)
      SELECT m.season_id,m.user_id,m.member_role FROM clan_members m
      JOIN clan_prison_camps c ON c.season_id=m.season_id AND c.clan_id=m.clan_id
      WHERE c.season_id=? AND c.creation_token=?`).bind(season.id, token),
    env.DB.prepare(`INSERT OR IGNORE INTO clan_prison_captives(season_id,user_id,member_role)
      SELECT c.season_id,t.master_user_id,'MASTER' FROM clan_prison_camps c
      JOIN clan_season_teams t ON t.season_id=c.season_id AND t.clan_id=c.clan_id
      WHERE c.season_id=? AND c.creation_token=?`).bind(season.id, token)
  ];
}

const ACTIVE = `FROM clan_prison_captives p JOIN clan_prison_camps c ON c.season_id=p.season_id
  WHERE p.released_at IS NULL AND c.jailed_until>?`;

export async function clanCampStatusForUser(env, userId, now = Date.now()) {
  await ensureClanCampSchema(env);
  const camp = await env.DB.prepare(`SELECT c.* ${ACTIVE} AND p.user_id=? ORDER BY c.jailed_until DESC LIMIT 1`)
    .bind(sqlTime(now), userId).first();
  if (!camp) return { incarcerated: false };
  return { incarcerated: true, facility: 'CLAN_CAMP', reason: `클랜 시즌 ${camp.season_no} · ${camp.clan_name} 최하위`,
    seasonId: Number(camp.season_id), seasonNo: Number(camp.season_no), clanName: camp.clan_name,
    jailedAt: camp.jailed_at, jailedUntil: camp.jailed_until, jailedByNickname: '행정부',
    remainingSeconds: Math.max(0, Math.ceil((Date.parse(camp.jailed_until.replace(' ', 'T') + 'Z') - now) / 1000)) };
}

export async function clanCampRoomState(env, user, prison, now = Date.now()) {
  await ensureClanCampSchema(env);
  const [inmates, messages] = await Promise.all([
    env.DB.prepare(`SELECT c.season_id,c.season_no,c.clan_name,c.final_rank,c.jailed_at,c.jailed_until,
      p.user_id,p.member_role,u.nickname FROM clan_prison_captives p
      JOIN clan_prison_camps c ON c.season_id=p.season_id JOIN users u ON u.id=p.user_id
      WHERE p.released_at IS NULL AND c.jailed_until>? ORDER BY c.season_id DESC,p.member_role,p.user_id`)
      .bind(sqlTime(now)).all(),
    env.DB.prepare(`SELECT q.*,u.nickname FROM (SELECT * FROM clan_prison_chat ORDER BY id DESC LIMIT 80) q
      JOIN users u ON u.id=q.user_id ORDER BY q.id`).all()
  ]);
  return { prison, sentenceHours: CLAN_CAMP_HOURS, serverNow: new Date(now).toISOString(),
    canRelease: canReleaseClanCaptives(user), viewerId: Number(user.id),
    inmates: rows(inmates).map(row => ({ seasonId: Number(row.season_id), seasonNo: Number(row.season_no),
      clanName: row.clan_name, finalRank: Number(row.final_rank), userId: Number(row.user_id),
      memberRole: row.member_role, nickname: row.nickname, jailedAt: row.jailed_at, jailedUntil: row.jailed_until })),
    chatEnabled: rows(inmates).length > 0,
    messages: rows(inmates).length ? rows(messages).map(row => ({ id: Number(row.id), userId: Number(row.user_id),
      nickname: row.nickname, body: row.body, senderWasCaptive: Number(row.sender_was_captive) === 1, createdAt: row.created_at })) : [] };
}

export async function sendClanCampChat(env, user, payload, now = Date.now()) {
  const body = String(payload?.body || '').replace(/[\u0000-\u001f\u007f]/g, ' ').replace(/\s+/g, ' ').trim();
  if (!body || Array.from(body).length > 200) fail('채팅은 1~200자로 입력하세요.');
  await ensureClanCampSchema(env);
  const date = sqlTime(now), token = crypto.randomUUID();
  const result = await env.DB.batch([
    env.DB.prepare('INSERT OR IGNORE INTO clan_prison_chat_cooldowns(user_id,next_at_ms) VALUES(?,0)').bind(user.id),
    env.DB.prepare(`UPDATE clan_prison_chat_cooldowns SET next_at_ms=?,token=? WHERE user_id=? AND next_at_ms<=?
      AND EXISTS(SELECT 1 ${ACTIVE})`).bind(now + 2000, token, user.id, now, date),
    env.DB.prepare(`INSERT INTO clan_prison_chat(user_id,body,sender_was_captive,created_at)
      SELECT ?,?,CASE WHEN EXISTS(SELECT 1 ${ACTIVE} AND p.user_id=?) THEN 1 ELSE 0 END,?
      WHERE EXISTS(SELECT 1 FROM clan_prison_chat_cooldowns WHERE user_id=? AND token=?)
      AND EXISTS(SELECT 1 ${ACTIVE})`).bind(user.id, body, date, user.id, date, user.id, token, date),
    env.DB.prepare('DELETE FROM clan_prison_chat WHERE id NOT IN (SELECT id FROM clan_prison_chat ORDER BY id DESC LIMIT 200)')
  ]);
  if (!changes(result[2])) {
    const active = await env.DB.prepare(`SELECT 1 ${ACTIVE} LIMIT 1`).bind(date).first();
    if (!active) fail('현재 수감자가 없어 포로수용소 채팅이 닫혀 있습니다.', 409, 'CLAN_CAMP_CHAT_CLOSED');
    fail('채팅은 2초에 한 번 보낼 수 있습니다.', 429, 'CLAN_CAMP_CHAT_RATE_LIMIT');
  }
  return { ok: true };
}

export async function releaseClanCaptives(env, user, payload, now = Date.now()) {
  if (!canReleaseClanCaptives(user)) fail('포로 석방은 OWNER 운영자만 할 수 있습니다.', 403);
  const seasonId = Number(payload?.seasonId), userId = payload?.userId == null ? null : Number(payload.userId);
  if (!Number.isSafeInteger(seasonId) || seasonId < 1 || (userId !== null && (!Number.isSafeInteger(userId) || userId < 1))) fail('석방 대상을 확인하세요.');
  await ensureClanCampSchema(env);
  const result = await env.DB.prepare(`UPDATE clan_prison_captives SET released_at=?,released_by=?,release_reason='운영자 석방'
    WHERE season_id=? AND released_at IS NULL ${userId === null ? '' : 'AND user_id=?'}
    AND EXISTS(SELECT 1 FROM clan_prison_camps c WHERE c.season_id=clan_prison_captives.season_id AND c.jailed_until>?)`)
    .bind(sqlTime(now), user.id, seasonId, ...(userId === null ? [] : [userId]), sqlTime(now)).run();
  return { ok: true, releasedCount: changes(result) };
}

export async function handleClanPrisonCamp({ path, request, env, deps }) {
  if (!path.startsWith('prison-camp/')) return null;
  const user = await deps.authenticate(request, env);
  if (!user) return deps.json({ error: '로그인이 필요합니다.' }, 401);
  try {
    const prison = await deps.prisonStatusForUser(env, user.id);
    if (prison.incarcerated && prison.facility !== 'CLAN_CAMP') return deps.json({ error: '수감 중에는 감옥을 벗어날 수 없습니다.', code: 'USER_INCARCERATED', prison }, 423);
    if (path === 'prison-camp/status' && request.method === 'GET') return deps.json(await clanCampRoomState(env, user, prison));
    if (path === 'prison-camp/chat' && request.method === 'POST') {
      await sendClanCampChat(env, user, await deps.readBody(request));
      return deps.json(await clanCampRoomState(env, user, await deps.prisonStatusForUser(env, user.id)), 201);
    }
    if (path === 'prison-camp/release' && request.method === 'POST') {
      const result = await releaseClanCaptives(env, user, await deps.readBody(request));
      return deps.json({ ...result, state: await clanCampRoomState(env, user, await deps.prisonStatusForUser(env, user.id)) });
    }
    return deps.json({ error: '지원하지 않는 요청입니다.' }, 405);
  } catch (error) {
    if (!error.status) throw error;
    return deps.json({ error: error.message, code: error.code || 'CLAN_CAMP_ERROR' }, error.status);
  }
}
