const DROP_CONTENTS=['PVE','PVP','RAID','RIFT','TOWER','TERRITORY','SEAL','DAILY_QUEST','ATTENDANCE','WAGO','MINERAL','VEHICLE','EQUIPMENT','CARD_DRAW'];
const DEFAULT_SETTINGS={enabled:true,dexButtonEnabled:false,prestigeEnabled:true,limitedEnabled:true,furEnabled:true,zenithEnabled:true,dropRates:Object.fromEntries(DROP_CONTENTS.map(code=>[code,0]))};
const ALLOWED_GRADES=new Set(['PRESTIGE','LIMITED','FUR','ZENITH']);
const TICKET_CODE='HIGH_GRADE_REROLL_TICKET';
const safeJson=(value,fallback={})=>{try{return JSON.parse(value)}catch{return fallback}};
const cleanSettings=value=>({enabled:value?.enabled!==false,dexButtonEnabled:value?.dexButtonEnabled===true,prestigeEnabled:value?.prestigeEnabled!==false,limitedEnabled:value?.limitedEnabled!==false,furEnabled:value?.furEnabled!==false,zenithEnabled:value?.zenithEnabled!==false,dropRates:Object.fromEntries(DROP_CONTENTS.map(code=>[code,Math.max(0,Math.min(100,Number(value?.dropRates?.[code]||0)))]))});
let settingsCache=null;
async function settings(env){const now=Date.now();if(settingsCache&&settingsCache.expiresAt>now)return settingsCache.value;const row=await env.DB.prepare("SELECT value FROM app_meta WHERE key='high_grade_reroll_settings_v1'").first(),value=cleanSettings({...DEFAULT_SETTINGS,...safeJson(row?.value||'{}',{})});settingsCache={value,expiresAt:now+30000};return value;}
async function ensureColumn(env,table,column,definition){const rows=await env.DB.prepare(`PRAGMA table_info(${table})`).all();if(!(rows.results||[]).some(row=>String(row.name)===column))await env.DB.prepare(`ALTER TABLE ${table} ADD COLUMN ${column} ${definition}`).run();}
let foundationReadyPromise=null;
export async function ensureHighGradeRerollFoundation(env){
  if(foundationReadyPromise)return foundationReadyPromise;
  foundationReadyPromise=(async()=>{
  await ensureColumn(env,'cards','reroll_material_enabled','INTEGER NOT NULL DEFAULT 1');
  await ensureColumn(env,'cards','reroll_result_enabled','INTEGER NOT NULL DEFAULT 1');
  await env.DB.batch([
    env.DB.prepare(`CREATE TABLE IF NOT EXISTS high_grade_reroll_ticket_receipts (request_id TEXT PRIMARY KEY,user_id INTEGER NOT NULL,grade TEXT NOT NULL,source_card_id TEXT NOT NULL,result_card_id TEXT NOT NULL,response_json TEXT NOT NULL,used_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`),
    env.DB.prepare(`CREATE TABLE IF NOT EXISTS high_grade_reroll_drop_receipts (user_id INTEGER NOT NULL,content_code TEXT NOT NULL,reference_id TEXT NOT NULL,won INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(user_id,content_code,reference_id))`),
    env.DB.prepare(`INSERT INTO inventory_items(code,name,subtitle,description,category,rarity,image_url,sort_order,is_active) VALUES('HIGH_GRADE_REROLL_TICKET','고등급 재뽑기권','HIGH GRADE REROLL TICKET','PRESTIGE·LIMITED·FUR·ZENITH 카드 1장을 같은 등급의 다른 고유효과 특성 카드로 재뽑습니다.','REROLL','SPECIAL','',109,1) ON CONFLICT(code) DO UPDATE SET name=excluded.name,subtitle=excluded.subtitle,description=excluded.description,category=excluded.category,rarity=excluded.rarity,sort_order=excluded.sort_order,is_active=1,updated_at=CURRENT_TIMESTAMP`),
    env.DB.prepare("INSERT INTO app_meta(key,value,updated_at) VALUES('high_grade_reroll_settings_v1',?,CURRENT_TIMESTAMP) ON CONFLICT(key) DO NOTHING").bind(JSON.stringify(DEFAULT_SETTINGS))
  ]);
  return true;
  })().catch(error=>{foundationReadyPromise=null;throw error});
  return foundationReadyPromise;
}
export async function grantHighGradeRerollDrop(env,{userId,content,referenceId}){
  const code=String(content||'').toUpperCase(),ref=String(referenceId||'').trim().slice(0,160);if(!userId||!DROP_CONTENTS.includes(code)||!ref)return null;await ensureHighGradeRerollFoundation(env);const cfg=await settings(env),rate=Math.max(0,Math.min(100,Number(cfg.dropRates?.[code]||0)));if(rate<=0)return null;
  const won=Math.random()*100<rate?1:0,inserted=await env.DB.prepare('INSERT OR IGNORE INTO high_grade_reroll_drop_receipts(user_id,content_code,reference_id,won) VALUES(?,?,?,?)').bind(userId,code,ref,won).run();if(!inserted.meta.changes)return null;if(!won)return {won:false,content:code,rate};
  await env.DB.batch([env.DB.prepare(`INSERT INTO cnine_user_inventory(user_id,item_code,quantity,unseen_quantity,created_at,updated_at) VALUES(?,?,1,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT(user_id,item_code) DO UPDATE SET quantity=quantity+1,unseen_quantity=unseen_quantity+1,updated_at=CURRENT_TIMESTAMP`).bind(userId,TICKET_CODE),env.DB.prepare("INSERT INTO inventory_logs(user_id,item_code,change_amount,balance_after,reason,reference_type,reference_id) SELECT ?,?,1,quantity,'CONTENT_DROP',?,? FROM cnine_user_inventory WHERE user_id=? AND item_code=?").bind(userId,TICKET_CODE,code,ref,userId,TICKET_CODE)]);return {won:true,content:code,rate,itemCode:TICKET_CODE,quantity:1};
}
function dominantRole(row){const stats=[['ATTACK',Number(row.attack_percent||0)],['DEFENSE',Number(row.defense_percent||0)],['SPEED',Number(row.speed_percent||0)],['HEALER',Number(row.hp_percent||0)]];const max=Math.max(...stats.map(item=>item[1]));return max>0?(stats.find(item=>item[1]===max)?.[0]||'NONE'):'NONE';}
function roleLabel(role){return {ATTACK:'공격형',DEFENSE:'방어형',SPEED:'속도형',HEALER:'회복형',NONE:'기본형'}[role]||role;}
async function ticketQuantity(env,userId){const row=await env.DB.prepare('SELECT quantity FROM cnine_user_inventory WHERE user_id=? AND item_code=?').bind(userId,TICKET_CODE).first();return Math.max(0,Number(row?.quantity||0));}
async function cardRows(env,where='',bind=[]){return (await env.DB.prepare(`SELECT c.id,c.title,c.rarity AS grade,c.image_url AS image,c.focus_x AS focusX,c.focus_y AS focusY,c.power_type AS powerType,c.base_power AS basePower,c.card_status AS cardStatus,c.is_active,COALESCE(rc.reroll_material_enabled,1) AS reroll_material_enabled,COALESCE(rc.reroll_result_enabled,1) AS reroll_result_enabled,m.name,COALESCE(e.attack_percent,0) attack_percent,COALESCE(e.defense_percent,0) defense_percent,COALESCE(e.hp_percent,0) hp_percent,COALESCE(e.speed_percent,0) speed_percent FROM cards_effective_v1210 c JOIN cards rc ON rc.id=c.id JOIN members m ON m.id=c.member_id LEFT JOIN card_unique_effects e ON e.card_id=c.id AND e.is_active=1 ${where}`).bind(...bind).all()).results||[];}
async function publicState(env,user){const cfg=await settings(env),quantity=await ticketQuantity(env,user.id);return {settings:cfg,ticketCode:TICKET_CODE,ticketQuantity:quantity,visible:cfg.enabled&&cfg.dexButtonEnabled&&quantity>0,inventoryUsable:cfg.enabled&&quantity>0};}
async function candidates(env,user,sourceCardId){
  const source=await env.DB.prepare(`SELECT uc.card_id,uc.quantity,uc.breakthrough_level,c.rarity AS grade,c.title,COALESCE(rc.reroll_material_enabled,1) AS reroll_material_enabled,COALESCE(e.attack_percent,0) attack_percent,COALESCE(e.defense_percent,0) defense_percent,COALESCE(e.hp_percent,0) hp_percent,COALESCE(e.speed_percent,0) speed_percent FROM user_cards uc JOIN cards_effective_v1210 c ON c.id=uc.card_id JOIN cards rc ON rc.id=c.id LEFT JOIN card_unique_effects e ON e.card_id=c.id AND e.is_active=1 WHERE uc.user_id=? AND uc.card_id=? AND COALESCE(uc.quantity,0)>0`).bind(user.id,String(sourceCardId)).first();
  if(!source)throw new Error('보유하지 않은 카드입니다.');
  const grade=String(source.grade||'').toUpperCase();if(!ALLOWED_GRADES.has(grade))throw new Error('PRESTIGE·LIMITED·FUR·ZENITH 카드만 재뽑기할 수 있습니다.');
  const quantity=await ticketQuantity(env,user.id);if(quantity<1)throw new Error('고등급 재뽑기권을 보유하고 있지 않습니다.');
  if(Number(source.reroll_material_enabled??1)!==1)throw new Error('이 카드는 재뽑기 재료로 사용할 수 없습니다.');
  const cfg=await settings(env),enabled=grade==='PRESTIGE'?cfg.prestigeEnabled:grade==='LIMITED'?cfg.limitedEnabled:grade==='FUR'?cfg.furEnabled:cfg.zenithEnabled;if(!cfg.enabled||!enabled)throw new Error(`${grade} 재뽑기가 현재 중지되어 있습니다.`);
  const sourceRole=dominantRole(source),pool=await cardRows(env,`WHERE UPPER(c.rarity)=? AND c.id<>? AND COALESCE(c.is_active,1)=1 AND COALESCE(c.card_status,'PUBLIC')='PUBLIC' AND COALESCE(rc.reroll_result_enabled,1)=1 AND NOT EXISTS (SELECT 1 FROM user_cards uc2 WHERE uc2.user_id=? AND uc2.card_id=c.id AND COALESCE(uc2.quantity,0)>0)`,[grade,String(sourceCardId),user.id]);
  const filtered=pool.map(card=>({...card,role:dominantRole(card),roleLabel:roleLabel(dominantRole(card))})).filter(card=>card.role!==sourceRole);
  return {source:{...source,id:String(source.card_id),role:sourceRole,roleLabel:roleLabel(sourceRole),breakthroughLevel:Number(source.breakthrough_level||0)},grade,candidates:filtered,ticketQuantity:quantity};
}
async function cardInDeck(env,userId,cardId){const checks=await Promise.all([env.DB.prepare("SELECT 1 ok FROM pve_decks WHERE user_id=? AND card_ids LIKE ? LIMIT 1").bind(userId,`%\"${cardId}\"%`).first(),env.DB.prepare("SELECT 1 ok FROM pvp_decks WHERE user_id=? AND card_ids LIKE ? LIMIT 1").bind(userId,`%\"${cardId}\"%`).first(),env.DB.prepare("SELECT 1 ok FROM pve_rift_runs WHERE user_id=? AND status='ACTIVE' AND deck_cards LIKE ? LIMIT 1").bind(userId,`%\"${cardId}\"%`).first()]).catch(()=>[]);return checks.some(Boolean);}
export async function handleHighGradeReroll({path,request,env,deps}){
  if(!(path.startsWith('high-grade-reroll')||path.startsWith('admin/high-grade-reroll')))return null;
  const {authenticate,readBody,json,requirePermission,writeAdminLog}=deps;await ensureHighGradeRerollFoundation(env);
  if(path==='high-grade-reroll/state'&&request.method==='GET'){const user=await authenticate(request,env);return user?json(await publicState(env,user)):json({error:'로그인이 필요합니다.'},401);}
  if(path==='high-grade-reroll/candidates'&&request.method==='GET'){const user=await authenticate(request,env);if(!user)return json({error:'로그인이 필요합니다.'},401);try{return json(await candidates(env,user,new URL(request.url).searchParams.get('sourceCardId')))}catch(error){return json({error:error.message},400)}}
  if(path==='high-grade-reroll/execute'&&request.method==='POST'){
    const user=await authenticate(request,env);if(!user)return json({error:'로그인이 필요합니다.'},401);const body=await readBody(request),sourceCardId=String(body.sourceCardId||''),requestId=String(body.requestId||'').slice(0,100);if(!sourceCardId||!requestId)return json({error:'재뽑기 요청 정보가 없습니다.'},400);
    const prior=await env.DB.prepare('SELECT response_json FROM high_grade_reroll_ticket_receipts WHERE user_id=? AND request_id=?').bind(user.id,requestId).first();if(prior?.response_json)return json(safeJson(prior.response_json,{}));let consumed=false;
    try{
      const data=await candidates(env,user,sourceCardId);if(!data.candidates.length)return json({error:'현재 고유효과 특성과 보유 카드를 제외하면 재뽑기 가능한 후보가 없습니다.'},409);const sourceQuantity=Math.max(1,Number(data.source.quantity||1));if(sourceQuantity<=1&&await cardInDeck(env,user.id,sourceCardId))return json({error:'덱에서 해당 카드를 먼저 해제하세요.'},409);
      const use=await env.DB.prepare('UPDATE cnine_user_inventory SET quantity=quantity-1,unseen_quantity=MIN(unseen_quantity,quantity-1),updated_at=CURRENT_TIMESTAMP WHERE user_id=? AND item_code=? AND quantity>0').bind(user.id,TICKET_CODE).run();if(!use.meta.changes)return json({error:'고등급 재뽑기권을 보유하고 있지 않습니다.'},409);consumed=true;
      const result=data.candidates[Math.floor(Math.random()*data.candidates.length)],sourceLevel=Number(data.source.breakthroughLevel||0),breakthroughTransferred=sourceQuantity===1,level=breakthroughTransferred?sourceLevel:0,remaining=Math.max(0,data.ticketQuantity-1),response={ok:true,grade:data.grade,ticketCode:TICKET_CODE,excludedRole:data.source.role,excludedRoleLabel:data.source.roleLabel,sourceCardId,resultCardId:String(result.id),sourceQuantityBefore:sourceQuantity,sourceQuantityAfter:sourceQuantity-1,breakthroughTransferred,breakthroughLevel:level,remaining,card:result};
      await env.DB.batch([env.DB.prepare(`UPDATE user_cards SET quantity=quantity-1,breakthrough_level=CASE WHEN quantity<=1 THEN 0 ELSE breakthrough_level END,last_obtained_at=CURRENT_TIMESTAMP WHERE user_id=? AND card_id=? AND quantity>0`).bind(user.id,sourceCardId),env.DB.prepare('DELETE FROM user_cards WHERE user_id=? AND card_id=? AND quantity<=0').bind(user.id,sourceCardId),env.DB.prepare(`INSERT INTO user_cards(user_id,card_id,quantity,breakthrough_level,first_obtained_at,last_obtained_at) VALUES(?,?,1,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT(user_id,card_id) DO UPDATE SET quantity=user_cards.quantity+1,breakthrough_level=MAX(user_cards.breakthrough_level,excluded.breakthrough_level),last_obtained_at=CURRENT_TIMESTAMP`).bind(user.id,String(result.id),level),env.DB.prepare(`INSERT INTO high_grade_reroll_ticket_receipts(request_id,user_id,grade,source_card_id,result_card_id,response_json) VALUES(?,?,?,?,?,?)`).bind(requestId,user.id,data.grade,sourceCardId,String(result.id),JSON.stringify(response)),env.DB.prepare("INSERT INTO inventory_logs(user_id,item_code,change_amount,balance_after,reason,reference_type,reference_id) VALUES(?,?,-1,?,'HIGH_GRADE_REROLL','CARD_REROLL',?)").bind(user.id,TICKET_CODE,remaining,requestId)]);return json(response);
    }catch(error){if(consumed)await env.DB.prepare('UPDATE cnine_user_inventory SET quantity=quantity+1,updated_at=CURRENT_TIMESTAMP WHERE user_id=? AND item_code=?').bind(user.id,TICKET_CODE).run().catch(()=>{});return json({error:error.message||'재뽑기에 실패했습니다.'},500)}
  }
  if(path==='admin/high-grade-reroll/settings'){const admin=await requirePermission(request,env,'SETTINGS');if(!admin)return json({error:'설정 권한이 없습니다.'},403);if(request.method==='GET')return json({settings:await settings(env)});if(request.method==='POST'){const body=await readBody(request),before=await settings(env),next=cleanSettings(body.settings||body);await env.DB.prepare("INSERT OR REPLACE INTO app_meta(key,value,updated_at) VALUES('high_grade_reroll_settings_v1',?,CURRENT_TIMESTAMP)").bind(JSON.stringify(next)).run();settingsCache={value:next,expiresAt:Date.now()+30000};if(writeAdminLog)await writeAdminLog(env,admin,'HIGH_GRADE_REROLL_SETTINGS','APP_META','high_grade_reroll_settings_v1',before,next);return json({ok:true,settings:next})}}
  return json({error:'지원하지 않는 요청입니다.'},404);
}
