const SETTINGS_KEY='idle_dungeon_settings_v1';
const ACTIVE_LEASE_MS=40000;
const DAILY_ACCOUNT_COIN_CAP=30000000;
const IDLE_RUN_LIMIT_HOURS=6;
const DEFAULT_SETTINGS={configVersion:4,mode:'TEST',enabled:true,maxOfflineHours:6,floorSeconds:20,minFloorSeconds:4,maxSpeedMultiplier:5,speedExponent:.65,combat:{hpMode:'POWER_SCALED',effectMode:'STORYBOOK',fixedBaseHp:1000000},difficulties:[
  {id:'NORMAL',name:'일반',index:1,maxFloor:100,requiredPowerStart:20000,requiredPowerEnd:130000,dailyCap:500000,monsterHpMultiplier:10},
  {id:'ABYSS',name:'심연',index:2,maxFloor:120,requiredPowerStart:80000,requiredPowerEnd:195000,dailyCap:750000,monsterHpMultiplier:15},
  {id:'DOOM',name:'종말',index:3,maxFloor:150,requiredPowerStart:130000,requiredPowerEnd:235000,dailyCap:1000000,monsterHpMultiplier:24}
]};
const clamp=(n,min,max)=>Math.max(min,Math.min(max,Number(n)||0));
const kstKey=(value=Date.now())=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(value));
function clean(raw={}){const source=Array.isArray(raw.difficulties)?raw.difficulties:DEFAULT_SETTINGS.difficulties,version=Number(raw.configVersion||0),legacyEconomy=version<2,legacyDifficulty=version<4,mode=['OFF','TEST','ON'].includes(String(raw.mode||'').toUpperCase())?String(raw.mode).toUpperCase():(raw.enabled===false?'OFF':'TEST'),hpMode=['POWER_SCALED','FIXED'].includes(String(raw.combat?.hpMode||'').toUpperCase())?String(raw.combat.hpMode).toUpperCase():'POWER_SCALED',effectMode=['STORYBOOK','CLASSIC','MINIMAL'].includes(String(raw.combat?.effectMode||'').toUpperCase())?String(raw.combat.effectMode).toUpperCase():'STORYBOOK',floorSeconds=clamp(raw.floorSeconds||20,5,300),minFloorSeconds=clamp(raw.minFloorSeconds??4,1,floorSeconds);return {configVersion:4,mode,enabled:mode!=='OFF',maxOfflineHours:clamp(raw.maxOfflineHours||6,1,24),floorSeconds,minFloorSeconds,maxSpeedMultiplier:clamp(raw.maxSpeedMultiplier??5,1,10),speedExponent:clamp(raw.speedExponent??.65,.1,2),combat:{hpMode,effectMode,fixedBaseHp:Math.floor(clamp(raw.combat?.fixedBaseHp||1000000,1000,1000000000))},difficulties:DEFAULT_SETTINGS.difficulties.map((base,i)=>{const x=source[i]||{},requiredPowerStart=legacyDifficulty?base.requiredPowerStart:(x.requiredPowerStart??base.requiredPowerStart),requiredPowerEnd=legacyDifficulty?base.requiredPowerEnd:(x.requiredPowerEnd??base.requiredPowerEnd);return {...base,name:String(x.name||base.name).slice(0,20),maxFloor:Math.floor(clamp(x.maxFloor||base.maxFloor,10,1000)),requiredPowerStart:Math.floor(clamp(requiredPowerStart,100,1000000000)),requiredPowerEnd:Math.floor(clamp(requiredPowerEnd,100,1000000000)),dailyCap:Math.floor(clamp(legacyEconomy?base.dailyCap:(x.dailyCap||base.dailyCap),1000,10000000)),monsterHpMultiplier:clamp(legacyDifficulty?base.monsterHpMultiplier:(x.monsterHpMultiplier??base.monsterHpMultiplier),.1,1000)}})};}
let foundationPromise=null,settingsCache=null,poolCache=null,maxPowerCache=null;
async function ensure(env){
  if(foundationPromise)return foundationPromise;
  foundationPromise=env.DB.batch([
    env.DB.prepare(`CREATE TABLE IF NOT EXISTS idle_dungeon_progress(user_id INTEGER PRIMARY KEY,difficulty TEXT NOT NULL DEFAULT 'NORMAL',unlocked_difficulty INTEGER NOT NULL DEFAULT 1,current_floor INTEGER NOT NULL DEFAULT 1,highest_floor INTEGER NOT NULL DEFAULT 0,run_started_at TEXT,last_settled_at TEXT,pending_coin INTEGER NOT NULL DEFAULT 0,daily_coin INTEGER NOT NULL DEFAULT 0,daily_key TEXT,total_coin INTEGER NOT NULL DEFAULT 0,total_resets INTEGER NOT NULL DEFAULT 0,version INTEGER NOT NULL DEFAULT 0,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`),
    env.DB.prepare(`CREATE TABLE IF NOT EXISTS idle_dungeon_claim_receipts(request_id TEXT PRIMARY KEY,user_id INTEGER NOT NULL,reward_coin INTEGER NOT NULL DEFAULT 0,response_json TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`),
    env.DB.prepare(`CREATE TABLE IF NOT EXISTS idle_dungeon_active_sessions(user_id INTEGER PRIMARY KEY,session_id TEXT NOT NULL,heartbeat_at TEXT NOT NULL,active_until TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`),
    env.DB.prepare(`INSERT OR IGNORE INTO app_meta(key,value,updated_at) VALUES(?,?,CURRENT_TIMESTAMP)`).bind(SETTINGS_KEY,JSON.stringify(DEFAULT_SETTINGS))
  ]).then(()=>true).catch(error=>{foundationPromise=null;throw error});
  return foundationPromise;
}
async function settings(env){const now=Date.now();if(settingsCache&&settingsCache.expiresAt>now)return settingsCache.value;const row=await env.DB.prepare('SELECT value FROM app_meta WHERE key=?').bind(SETTINGS_KEY).first();let value;try{value=clean(JSON.parse(row?.value||'{}'))}catch{value=clean()}settingsCache={value,expiresAt:now+10000};return value}
function seeded(value){let h=2166136261;for(const c of String(value)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return (h>>>0)/4294967295;}
async function pool(env){const now=Date.now();if(poolCache&&poolCache.expiresAt>now)return poolCache.value;const [battle,tower]=await env.DB.batch([
  env.DB.prepare(`SELECT id,name,replace(image_url,char(92),'/') image,battle_power basePower,is_boss isBoss,'BATTLE' source FROM battle_monsters WHERE is_active=1 AND (COALESCE(pve_enabled,1)=1 OR COALESCE(tower_enabled,0)=1) ORDER BY is_boss,COALESCE(pve_display_order,sort_order,0),id`),
  env.DB.prepare(`SELECT id,name,replace(image_url,char(92),'/') image,base_power basePower,is_boss isBoss,'TOWER' source FROM tower_monsters WHERE is_active=1 ORDER BY is_boss,sort_order,id`)
]);
  const seen=new Set(),all=[];for(const row of [...(battle.results||[]),...(tower.results||[])]){const key=`${row.source}:${row.id}`;if(!seen.has(key)){seen.add(key);all.push(row)}}poolCache={value:all,expiresAt:now+60000};return all;
}
function monsterAt(all,difficulty,floor,userId){const boss=floor%10===0,candidates=all.filter(x=>Boolean(x.isBoss)===boss),list=candidates.length?candidates:all;if(!list.length)return {id:0,name:boss?'심연의 군주':'성채의 망령',image:'assets/ui/idle-dungeon/moon-citadel-v1.png',basePower:1,isBoss:boss,source:'FALLBACK'};return list[Math.floor(seeded(`${userId}:${difficulty}:${floor}`)*list.length)%list.length];}
async function observedMaxPower(env,current){const now=Date.now();if(!maxPowerCache||maxPowerCache.expiresAt<=now){const [tower,raid]=await env.DB.batch([env.DB.prepare('SELECT player_power value FROM tower_clear_history WHERE player_power>0 ORDER BY player_power DESC LIMIT 1'),env.DB.prepare('SELECT total_power value FROM raid_participants WHERE total_power>0 ORDER BY total_power DESC LIMIT 1')]);maxPowerCache={value:Math.max(1,Number(tower.results?.[0]?.value||0),Number(raid.results?.[0]?.value||0)),expiresAt:now+300000}}return Math.max(maxPowerCache.value,Number(current||0));}
function coinPerClear(s,d){return Math.max(1,Math.round(Number(d.dailyCap||0)*Number(s.floorSeconds||20)/(Math.max(1,Number(s.maxOfflineHours||6))*3600)));}
function publicDifficulty(s,unlocked){return s.difficulties.map(x=>({...x,coinPerClear:coinPerClear(s,x),unlocked:x.index<=unlocked}));}
async function idleUniqueDeck(env,deck){const cards=Array.isArray(deck?.cards)?deck.cards:[],ids=[...new Set(cards.map(c=>String(c.id)).filter(Boolean))];if(!ids.length)return {cards,power:Math.max(1,Math.floor(Number(deck?.power||0)))};const marks=ids.map(()=>'?').join(','),rows=(await env.DB.prepare(`SELECT card_id,attack_percent,defense_percent,hp_percent,speed_percent,effect_name,effect_description,effect_type,trigger_type,effect_value,trigger_chance,max_activations FROM card_unique_effects WHERE is_active=1 AND scope_pve=1 AND card_id IN (${marks})`).bind(...ids).all()).results||[],effects=new Map(rows.map(x=>[String(x.card_id),{cardId:String(x.card_id),attackPercent:Number(x.attack_percent||0),defensePercent:Number(x.defense_percent||0),hpPercent:Number(x.hp_percent||0),speedPercent:Number(x.speed_percent||0),effectName:String(x.effect_name||''),effectDescription:String(x.effect_description||''),effectType:String(x.effect_type||'NONE'),triggerType:String(x.trigger_type||'PASSIVE'),effectValue:Number(x.effect_value||0),triggerChance:Math.max(0,Math.min(100,Number(x.trigger_chance??100))),maxActivations:Math.max(1,Number(x.max_activations||1))}]));const applied=cards.map(card=>({...card,uniqueAbility:effects.get(String(card.id))||card.uniqueAbility||null}));return {cards:applied,power:Math.max(1,Math.floor(Number(deck?.power||0)))};}
function encounterAt(cfg,d,floor,deckPower,maxObserved,all,userId){const monster=monsterAt(all,d.id,floor,userId),progress=(floor-1)/Math.max(1,d.maxFloor-1),curve=d.requiredPowerStart+(d.requiredPowerEnd-d.requiredPowerStart)*Math.pow(progress,1.38),isBoss=floor%10===0,final=floor===d.maxFloor,finalBarrier=final&&d.index===cfg.difficulties.length,baseRequired=Math.max(1,Math.floor(curve*(isBoss?1.08:1))),requiredPower=finalBarrier?Math.ceil(Math.max(baseRequired,maxObserved*1.18,deckPower*1.12)):baseRequired,powerRatio=deckPower/Math.max(1,requiredPower),canClear=powerRatio>=1,speedMultiplier=canClear?clamp(Math.pow(powerRatio,cfg.speedExponent),1,cfg.maxSpeedMultiplier):1,effectiveFloorSeconds=canClear?Math.max(cfg.minFloorSeconds,cfg.floorSeconds/speedMultiplier):cfg.floorSeconds;return {floor,monster,requiredPower,canClear,wipeOnFailure:!canClear,failureMode:canClear?null:'PARTY_WIPE',powerRatio:Number(powerRatio.toFixed(3)),speedMultiplier:Number(speedMultiplier.toFixed(3)),effectiveFloorSeconds:Number(effectiveFloorSeconds.toFixed(3)),isBoss,final,finalBarrier};}
function encounterSequence(cfg,d,startFloor,deckPower,maxObserved,all,userId,count=12){let floor=Math.max(1,Number(startFloor||1));const rows=[];for(let i=0;i<count;i++){const encounter=encounterAt(cfg,d,floor,deckPower,maxObserved,all,userId);rows.push(encounter);floor=!encounter.canClear||encounter.final?1:floor+1}return rows;}
function compute(state,cfg,deckPower,maxObserved,all,userId,now=Date.now()){
  const d=cfg.difficulties.find(x=>x.id===state.difficulty)||cfg.difficulties[0],today=kstKey(now);
  let daily=today===state.daily_key?Number(state.daily_coin||0):0,pending=Number(state.pending_coin||0),floor=Math.max(1,Number(state.current_floor||1)),highest=Number(state.highest_floor||0),unlocked=Number(state.unlocked_difficulty||1),resets=Number(state.total_resets||0),last=Date.parse(state.last_settled_at||state.run_started_at||new Date(now).toISOString());
  if(!Number.isFinite(last))last=now;
  const settlementStart=Math.max(last,now-cfg.maxOfflineHours*3600000),elapsed=Math.max(0,now-settlementStart),clearReward=coinPerClear(cfg,d),capLeft=Math.max(0,DAILY_ACCOUNT_COIN_CAP-daily);
  let remaining=elapsed,consumed=0,rewardSeconds=0,steps=0,clearedFloors=0,earned=0,failed=false,completed=false;
  while(steps<10000&&earned<capLeft){
    const encounter=encounterAt(cfg,d,floor,deckPower,maxObserved,all,userId),duration=Math.max(1000,Math.round(encounter.effectiveFloorSeconds*1000));
    if(remaining<duration)break;
    remaining-=duration;consumed+=duration;steps++;
    if(!encounter.canClear){floor=1;resets++;failed=true;continue}
    clearedFloors++;rewardSeconds+=duration/1000;earned=Math.min(capLeft,earned+clearReward);highest=Math.max(highest,floor);
    if(encounter.final){completed=true;unlocked=Math.min(cfg.difficulties.length,Math.max(unlocked,d.index+1));floor=1;resets++}
    else floor++;
  }
  const capReached=daily+earned>=DAILY_ACCOUNT_COIN_CAP,currentEncounter=encounterAt(cfg,d,floor,deckPower,maxObserved,all,userId);
  return {...state,difficulty:d.id,unlocked_difficulty:unlocked,current_floor:floor,highest_floor:highest,pending_coin:pending+earned,daily_coin:daily+earned,daily_key:today,total_resets:resets,last_settled_at:new Date(settlementStart+consumed).toISOString(),failed,completed,earned,steps,clearedFloors,coinPerClear:clearReward,consumedSeconds:consumed/1000,rewardSeconds,currentEncounter,monster:currentEncounter.monster,difficultyDailyCap:d.dailyCap,dailyCap:DAILY_ACCOUNT_COIN_CAP,capReached};
}
async function state(env,user,deckPower,now=Date.now()){
  await ensure(env);
  let [row,session]=await env.DB.batch([
    env.DB.prepare('SELECT * FROM idle_dungeon_progress WHERE user_id=?').bind(user.id),
    env.DB.prepare('SELECT * FROM idle_dungeon_active_sessions WHERE user_id=?').bind(user.id)
  ]);
  row=row.results?.[0]||null;session=session.results?.[0]||null;
  if(!row){
    await env.DB.prepare(`INSERT OR IGNORE INTO idle_dungeon_progress(user_id,daily_key) VALUES(?,?)`).bind(user.id,kstKey(now)).run();
    row=await env.DB.prepare('SELECT * FROM idle_dungeon_progress WHERE user_id=?').bind(user.id).first();
  }
  const cfg=await settings(env),all=await pool(env),maxObserved=await observedMaxPower(env,deckPower);
  const activeUntil=Date.parse(session?.active_until||''),heartbeatAt=Date.parse(session?.heartbeat_at||'');
  const hasSession=Boolean(session&&Number.isFinite(activeUntil)&&Number.isFinite(heartbeatAt));
  const liveViewConnected=hasSession&&activeUntil>now;
  const persistedRunning=Boolean(row.run_started_at),runStartedMs=Date.parse(row.run_started_at||'');
  const expired=hasSession&&!liveViewConnected;
  // The live-view heartbeat controls only the animation connection. Expedition
  // progress is authoritative in idle_dungeon_progress and continues server-side.
  const runDeadline=Number.isFinite(runStartedMs)?runStartedMs+IDLE_RUN_LIMIT_HOURS*3600000:now;
  const settlementEnd=persistedRunning?Math.min(now,runDeadline):Date.parse(row.last_settled_at||new Date(now).toISOString());
  const next=compute(row,cfg,deckPower,maxObserved,all,user.id,Number.isFinite(settlementEnd)?settlementEnd:now),today=kstKey(now);
  if(next.daily_key!==today){next.daily_key=today;next.daily_coin=0}
  const durationReached=persistedRunning&&now>=runDeadline,capReached=persistedRunning&&Boolean(next.capReached),autoStopped=durationReached||capReached;
  next.run_started_at=persistedRunning&&!autoStopped?row.run_started_at:null;
  next.stopReason=capReached?'DAILY_CAP':durationReached?'SIX_HOURS':null;
  const shouldPersist=next.steps>0||expired||autoStopped||String(next.daily_key)!==String(row.daily_key||'');
  if(shouldPersist)await env.DB.prepare(`UPDATE idle_dungeon_progress SET unlocked_difficulty=?,current_floor=?,highest_floor=?,run_started_at=?,last_settled_at=?,pending_coin=?,daily_coin=?,daily_key=?,total_resets=?,version=version+1,updated_at=CURRENT_TIMESTAMP WHERE user_id=?`).bind(next.unlocked_difficulty,next.current_floor,next.highest_floor,next.run_started_at,next.last_settled_at,next.pending_coin,next.daily_coin,next.daily_key,next.total_resets,user.id).run();
  if((expired||autoStopped)&&session)await env.DB.prepare('DELETE FROM idle_dungeon_active_sessions WHERE user_id=? AND session_id=?').bind(user.id,session.session_id).run();
  return {cfg,next,maxObserved,all,session:liveViewConnected&&!autoStopped?session:null,sessionActive:persistedRunning&&!autoStopped};
}
export async function handleIdleDungeon({path,request,env,deps}){if(!path.startsWith('idle-dungeon')&&!path.startsWith('admin/idle-dungeon'))return null;const {authenticate,readBody,json,isAdminRole,raidDeckPower}=deps;await ensure(env);const user=await authenticate(request,env);if(!user)return json({error:'로그인이 필요합니다.'},401);
  if(path==='admin/idle-dungeon'){if(!isAdminRole(user))return json({error:'권한이 없습니다.'},403);if(request.method==='GET')return json({settings:await settings(env)});const body=await readBody(request),value=clean(body);await env.DB.prepare('INSERT OR REPLACE INTO app_meta(key,value,updated_at) VALUES(?,?,CURRENT_TIMESTAMP)').bind(SETTINGS_KEY,JSON.stringify(value)).run();settingsCache={value,expiresAt:Date.now()+10000};return json({ok:true,settings:value});}
  const access=await settings(env),role=String(user.role||'').toUpperCase();if(access.mode==='OFF')return json({error:'현재 방치형 원정이 운영 중지 상태입니다.',code:'IDLE_DUNGEON_OFF'},503);if(access.mode==='TEST'&&role!=='OWNER')return json({error:'방치형 원정은 현재 OWNER 테스트 중입니다.',code:'IDLE_DUNGEON_TEST_LOCKED'},403);
  if(path==='idle-dungeon/heartbeat'&&request.method==='POST'){const b=await readBody(request),sessionId=String(b.sessionId||'').replace(/[^a-zA-Z0-9._:-]/g,'').slice(0,120),now=Date.now(),session=await env.DB.prepare('SELECT session_id,active_until FROM idle_dungeon_active_sessions WHERE user_id=?').bind(user.id).first();if(!sessionId||!session||session.session_id!==sessionId||Date.parse(session.active_until)<=now)return json({error:'원정 실행 연결이 종료되었습니다. 다시 시작하세요.',code:'IDLE_SESSION_EXPIRED'},409);const expiresAt=new Date(now+ACTIVE_LEASE_MS).toISOString(),updated=await env.DB.prepare('UPDATE idle_dungeon_active_sessions SET heartbeat_at=?,active_until=? WHERE user_id=? AND session_id=?').bind(new Date(now).toISOString(),expiresAt,user.id,sessionId).run();if(!updated.meta.changes)return json({error:'원정 실행 상태를 갱신하지 못했습니다.',code:'IDLE_SESSION_STALE'},409);return json({ok:true,running:true,expiresAt});}
  let stopRequest=null;if(path==='idle-dungeon/stop'&&request.method==='POST'){stopRequest=await readBody(request);const sessionId=String(stopRequest.sessionId||'').replace(/[^a-zA-Z0-9._:-]/g,'').slice(0,120),now=Date.now(),session=await env.DB.prepare('SELECT session_id,active_until FROM idle_dungeon_active_sessions WHERE user_id=?').bind(user.id).first();if(sessionId&&session?.session_id===sessionId&&Date.parse(session.active_until)>now)await env.DB.prepare('UPDATE idle_dungeon_active_sessions SET heartbeat_at=? WHERE user_id=? AND session_id=?').bind(new Date(now).toISOString(),user.id,sessionId).run();}
  let deck;try{deck=await raidDeckPower(env,user.id,null,'PVE')}catch(e){return json({error:'저장된 PVE 덱 5장을 먼저 편성하세요.'},400)}const idleDeck=await idleUniqueDeck(env,deck),data=await state(env,user,idleDeck.power),p=data.next,cfg=data.cfg;
  if(path==='idle-dungeon/status'){const difficulty=cfg.difficulties.find(x=>x.id===p.difficulty)||cfg.difficulties[0],encounters=encounterSequence(cfg,difficulty,p.current_floor,idleDeck.power,data.maxObserved,data.all,user.id),finalDifficulty=cfg.difficulties[cfg.difficulties.length-1],finalBarrierPower=encounterAt(cfg,finalDifficulty,finalDifficulty.maxFloor,idleDeck.power,data.maxObserved,data.all,user.id).requiredPower;return json({settings:{mode:cfg.mode,enabled:cfg.enabled,maxOfflineHours:cfg.maxOfflineHours,floorSeconds:cfg.floorSeconds,minFloorSeconds:cfg.minFloorSeconds,maxSpeedMultiplier:cfg.maxSpeedMultiplier,speedExponent:cfg.speedExponent,dailyAccountCoinCap:DAILY_ACCOUNT_COIN_CAP,combat:cfg.combat,difficulties:publicDifficulty(cfg,p.unlocked_difficulty)},progress:{difficulty:p.difficulty,currentFloor:p.current_floor,highestFloor:p.highest_floor,unlockedDifficulty:p.unlocked_difficulty,pendingCoin:p.pending_coin,dailyCoin:p.daily_coin,dailyCap:p.dailyCap,difficultyDailyCap:p.difficultyDailyCap,coinPerClear:p.coinPerClear,clearedFloors:p.clearedFloors,resets:p.total_resets,running:data.sessionActive,stopReason:p.stopReason||null,failed:p.failed,wiped:p.failed,completed:p.completed,requiredPower:p.currentEncounter.requiredPower,powerRatio:p.currentEncounter.powerRatio,speedMultiplier:p.currentEncounter.speedMultiplier,effectiveFloorSeconds:p.currentEncounter.effectiveFloorSeconds},deckPower:idleDeck.power,deckCards:idleDeck.cards.map(c=>({id:c.id,title:c.title,rarity:c.rarity||c.grade,image:c.image,power:c.power,uniqueAbility:c.uniqueAbility||null})),observedMaxPower:data.maxObserved,finalBarrierPower,monster:p.monster,encounter:p.currentEncounter,encounters,serverNow:new Date().toISOString()});}
  if(path==='idle-dungeon/start'&&request.method==='POST'){const b=await readBody(request),d=cfg.difficulties.find(x=>x.id===String(b.difficulty||'NORMAL').toUpperCase()),sessionId=(String(b.sessionId||crypto.randomUUID()).replace(/[^a-zA-Z0-9._:-]/g,'').slice(0,120)||crypto.randomUUID()),now=Date.now(),nowIso=new Date(now).toISOString(),expiresAt=new Date(now+ACTIVE_LEASE_MS).toISOString();if(!d||d.index>p.unlocked_difficulty)return json({error:'아직 해금되지 않은 난이도입니다.'},403);if(Number(p.daily_coin||0)>=DAILY_ACCOUNT_COIN_CAP)return json({error:'오늘 원정 코인 한도 3,000만에 도달하여 원정을 시작할 수 없습니다.',code:'IDLE_DAILY_CAP_REACHED'},409);const switching=Boolean(data.sessionActive),difficultyChanged=d.id!==p.difficulty,startFloor=difficultyChanged?1:Math.max(1,Number(p.current_floor||1)),preservedStart=switching&&p.run_started_at?String(p.run_started_at):nowIso,stopAtMs=Date.parse(preservedStart)+IDLE_RUN_LIMIT_HOURS*3600000;await env.DB.batch([env.DB.prepare(`UPDATE idle_dungeon_progress SET difficulty=?,current_floor=?,run_started_at=?,last_settled_at=?,version=version+1,updated_at=CURRENT_TIMESTAMP WHERE user_id=?`).bind(d.id,startFloor,preservedStart,nowIso,user.id),env.DB.prepare(`INSERT INTO idle_dungeon_active_sessions(user_id,session_id,heartbeat_at,active_until) VALUES(?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET session_id=excluded.session_id,heartbeat_at=excluded.heartbeat_at,active_until=excluded.active_until,created_at=CURRENT_TIMESTAMP`).bind(user.id,sessionId,nowIso,expiresAt)]);return json({ok:true,difficulty:d.id,currentFloor:startFloor,sessionId,expiresAt,switched:switching&&difficultyChanged,stopsAt:new Date(stopAtMs).toISOString()});}
  if(path==='idle-dungeon/stop'&&request.method==='POST'){await env.DB.batch([env.DB.prepare('UPDATE idle_dungeon_progress SET run_started_at=NULL,last_settled_at=CURRENT_TIMESTAMP,version=version+1,updated_at=CURRENT_TIMESTAMP WHERE user_id=?').bind(user.id),env.DB.prepare('DELETE FROM idle_dungeon_active_sessions WHERE user_id=?').bind(user.id)]);return json({ok:true,running:false,pendingCoin:p.pending_coin});}
  if(path==='idle-dungeon/claim'&&request.method==='POST'){const b=await readBody(request),rid=String(b.requestId||'').slice(0,120);if(!rid)return json({error:'요청 식별값이 필요합니다.'},400);const old=await env.DB.prepare('SELECT response_json FROM idle_dungeon_claim_receipts WHERE request_id=? AND user_id=?').bind(rid,user.id).first();if(old?.response_json)return json(JSON.parse(old.response_json));const amount=Math.max(0,Number(p.pending_coin||0)),coinAfter=Math.max(0,Number(user.coin||0))+amount,response={ok:true,rewardCoin:amount,coinAfter};if(amount<=0)return json(response);const latest=await env.DB.prepare('SELECT version,pending_coin FROM idle_dungeon_progress WHERE user_id=?').bind(user.id).first();if(Number(latest?.pending_coin||0)!==amount)return json({error:'보상 상태가 갱신되었습니다. 다시 확인하세요.'},409);const version=Number(latest.version||0),marker=version+1,responseJson=JSON.stringify(response),results=await env.DB.batch([env.DB.prepare(`INSERT INTO idle_dungeon_claim_receipts(request_id,user_id,reward_coin,response_json) SELECT ?,?,?,? FROM idle_dungeon_progress WHERE user_id=? AND pending_coin=? AND version=?`).bind(rid,user.id,amount,responseJson,user.id,amount,version),env.DB.prepare(`UPDATE idle_dungeon_progress SET pending_coin=0,total_coin=total_coin+?,version=version+1,updated_at=CURRENT_TIMESTAMP WHERE user_id=? AND pending_coin=? AND version=? AND EXISTS(SELECT 1 FROM idle_dungeon_claim_receipts WHERE request_id=? AND user_id=?)`).bind(amount,user.id,amount,version,rid,user.id),env.DB.prepare(`UPDATE users SET coin=coin+? WHERE id=? AND EXISTS(SELECT 1 FROM idle_dungeon_claim_receipts WHERE request_id=? AND user_id=?) AND EXISTS(SELECT 1 FROM idle_dungeon_progress WHERE user_id=? AND pending_coin=0 AND version=?)`).bind(amount,user.id,rid,user.id,user.id,marker),env.DB.prepare(`INSERT INTO coin_logs(user_id,change_amount,balance_after,reason) SELECT ?,?,coin,'방치형 원정 정산' FROM users WHERE id=? AND EXISTS(SELECT 1 FROM idle_dungeon_claim_receipts WHERE request_id=? AND user_id=?) AND EXISTS(SELECT 1 FROM idle_dungeon_progress WHERE user_id=? AND pending_coin=0 AND version=?)`).bind(user.id,amount,user.id,rid,user.id,user.id,marker)]);if(Number(results?.[0]?.meta?.changes||0)!==1||Number(results?.[1]?.meta?.changes||0)!==1||Number(results?.[2]?.meta?.changes||0)!==1)return json({error:'보상 상태가 갱신되었습니다. 다시 확인하세요.'},409);return json(response);}
  return json({error:'지원하지 않는 요청입니다.'},404);
}
