const SETTINGS_KEY='idle_dungeon_settings_v1';
const DEFAULT_SETTINGS={enabled:true,maxOfflineHours:6,floorSeconds:20,difficulties:[
  {id:'NORMAL',name:'일반',index:1,maxFloor:100,powerStart:.18,powerEnd:1.05,dailyCap:1000000},
  {id:'ABYSS',name:'심연',index:2,maxFloor:120,powerStart:.72,powerEnd:1.55,dailyCap:1300000},
  {id:'DOOM',name:'종말',index:3,maxFloor:150,powerStart:1.05,powerEnd:2.35,dailyCap:1500000}
]};
const clamp=(n,min,max)=>Math.max(min,Math.min(max,Number(n)||0));
const kstKey=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
function clean(raw={}){const source=Array.isArray(raw.difficulties)?raw.difficulties:DEFAULT_SETTINGS.difficulties;return {enabled:raw.enabled!==false,maxOfflineHours:clamp(raw.maxOfflineHours||6,1,24),floorSeconds:clamp(raw.floorSeconds||20,5,300),difficulties:DEFAULT_SETTINGS.difficulties.map((base,i)=>{const x=source[i]||{};return {...base,name:String(x.name||base.name).slice(0,20),maxFloor:Math.floor(clamp(x.maxFloor||base.maxFloor,10,1000)),powerStart:clamp(x.powerStart??base.powerStart,.01,20),powerEnd:clamp(x.powerEnd??base.powerEnd,.02,50),dailyCap:Math.floor(clamp(x.dailyCap||base.dailyCap,1000,10000000))}})};}
async function ensure(env){await env.DB.batch([
  env.DB.prepare(`CREATE TABLE IF NOT EXISTS idle_dungeon_progress(user_id INTEGER PRIMARY KEY,difficulty TEXT NOT NULL DEFAULT 'NORMAL',unlocked_difficulty INTEGER NOT NULL DEFAULT 1,current_floor INTEGER NOT NULL DEFAULT 1,highest_floor INTEGER NOT NULL DEFAULT 0,run_started_at TEXT,last_settled_at TEXT,pending_coin INTEGER NOT NULL DEFAULT 0,daily_coin INTEGER NOT NULL DEFAULT 0,daily_key TEXT,total_coin INTEGER NOT NULL DEFAULT 0,total_resets INTEGER NOT NULL DEFAULT 0,version INTEGER NOT NULL DEFAULT 0,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`),
  env.DB.prepare(`CREATE TABLE IF NOT EXISTS idle_dungeon_claim_receipts(request_id TEXT PRIMARY KEY,user_id INTEGER NOT NULL,reward_coin INTEGER NOT NULL DEFAULT 0,response_json TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`),
  env.DB.prepare(`INSERT OR IGNORE INTO app_meta(key,value,updated_at) VALUES(?,?,CURRENT_TIMESTAMP)`).bind(SETTINGS_KEY,JSON.stringify(DEFAULT_SETTINGS))
]);}
async function settings(env){const row=await env.DB.prepare('SELECT value FROM app_meta WHERE key=?').bind(SETTINGS_KEY).first();try{return clean(JSON.parse(row?.value||'{}'))}catch{return clean()}}
function seeded(value){let h=2166136261;for(const c of String(value)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return (h>>>0)/4294967295;}
async function pool(env){const [battle,tower]=await env.DB.batch([
  env.DB.prepare(`SELECT id,name,replace(image_url,char(92),'/') image,battle_power basePower,is_boss isBoss,'BATTLE' source FROM battle_monsters WHERE is_active=1 AND (COALESCE(pve_enabled,1)=1 OR COALESCE(tower_enabled,0)=1) ORDER BY is_boss,COALESCE(pve_display_order,sort_order,0),id`),
  env.DB.prepare(`SELECT id,name,replace(image_url,char(92),'/') image,base_power basePower,is_boss isBoss,'TOWER' source FROM tower_monsters WHERE is_active=1 ORDER BY is_boss,sort_order,id`)
]);
  const seen=new Set(),all=[];for(const row of [...(battle.results||[]),...(tower.results||[])]){const key=`${row.source}:${row.id}`;if(!seen.has(key)){seen.add(key);all.push(row)}}return all;
}
function monsterAt(all,difficulty,floor,userId){const boss=floor%10===0,candidates=all.filter(x=>Boolean(x.isBoss)===boss),list=candidates.length?candidates:all;if(!list.length)return {id:0,name:boss?'심연의 군주':'성채의 망령',image:'assets/ui/idle-dungeon/moon-citadel-v1.png',basePower:1,isBoss:boss,source:'FALLBACK'};return list[Math.floor(seeded(`${userId}:${difficulty}:${floor}`)*list.length)%list.length];}
async function observedMaxPower(env,current){const [tower,raid]=await env.DB.batch([env.DB.prepare('SELECT MAX(player_power) value FROM tower_clear_history WHERE player_power>0'),env.DB.prepare('SELECT MAX(total_power) value FROM raid_participants WHERE total_power>0')]);return Math.max(1,Number(tower.results?.[0]?.value||0),Number(raid.results?.[0]?.value||0),Number(current||0));}
function publicDifficulty(s,unlocked){return s.difficulties.map(x=>({...x,unlocked:x.index<=unlocked}));}
function compute(state,cfg,deckPower,maxObserved,all,userId,now=Date.now()){
  const d=cfg.difficulties.find(x=>x.id===state.difficulty)||cfg.difficulties[0],today=kstKey();let daily=today===state.daily_key?Number(state.daily_coin||0):0,pending=Number(state.pending_coin||0),floor=Math.max(1,Number(state.current_floor||1)),highest=Number(state.highest_floor||0),unlocked=Number(state.unlocked_difficulty||1),resets=Number(state.total_resets||0),last=Date.parse(state.last_settled_at||state.run_started_at||new Date(now).toISOString()),elapsed=Math.max(0,Math.min(now-last,cfg.maxOfflineHours*3600000)),steps=Math.min(5000,Math.floor(elapsed/(cfg.floorSeconds*1000))),rewardSeconds=steps*cfg.floorSeconds,capLeft=Math.max(0,d.dailyCap-daily),earned=Math.min(capLeft,Math.floor(rewardSeconds*d.dailyCap/(cfg.maxOfflineHours*3600))),failed=false,completed=false;
  for(let i=0;i<steps;i++){const progress=(floor-1)/Math.max(1,d.maxFloor-1),curve=d.powerStart+(d.powerEnd-d.powerStart)*Math.pow(progress,1.38),final=floor===d.maxFloor,finalBarrier=final&&d.index===cfg.difficulties.length,required=Math.floor((finalBarrier?Math.max(maxObserved*1.18,deckPower*1.12):deckPower*curve)*(floor%10===0?1.08:1));if(deckPower<required){floor=1;resets++;failed=true;continue}highest=Math.max(highest,floor);if(final){completed=true;unlocked=Math.min(cfg.difficulties.length,Math.max(unlocked,d.index+1));floor=1;resets++;continue}floor++;}
  const consumed=steps*cfg.floorSeconds*1000;return {...state,difficulty:d.id,unlocked_difficulty:unlocked,current_floor:floor,highest_floor:highest,pending_coin:pending+earned,daily_coin:daily+earned,daily_key:today,total_resets:resets,last_settled_at:new Date(last+consumed).toISOString(),failed,completed,earned,steps,monster:monsterAt(all,d.id,floor,userId),dailyCap:d.dailyCap};
}
async function state(env,user,deckPower){await ensure(env);let row=await env.DB.prepare('SELECT * FROM idle_dungeon_progress WHERE user_id=?').bind(user.id).first();if(!row){await env.DB.prepare(`INSERT OR IGNORE INTO idle_dungeon_progress(user_id,daily_key) VALUES(?,?)`).bind(user.id,kstKey()).run();row=await env.DB.prepare('SELECT * FROM idle_dungeon_progress WHERE user_id=?').bind(user.id).first()}const cfg=await settings(env),all=await pool(env),maxObserved=await observedMaxPower(env,deckPower),next=compute(row,cfg,deckPower,maxObserved,all,user.id);if(next.steps>0)await env.DB.prepare(`UPDATE idle_dungeon_progress SET unlocked_difficulty=?,current_floor=?,highest_floor=?,last_settled_at=?,pending_coin=?,daily_coin=?,daily_key=?,total_resets=?,version=version+1,updated_at=CURRENT_TIMESTAMP WHERE user_id=?`).bind(next.unlocked_difficulty,next.current_floor,next.highest_floor,next.last_settled_at,next.pending_coin,next.daily_coin,next.daily_key,next.total_resets,user.id).run();return {cfg,next,maxObserved,all};}
export async function handleIdleDungeon({path,request,env,deps}){if(!path.startsWith('idle-dungeon')&&!path.startsWith('admin/idle-dungeon'))return null;const {authenticate,readBody,json,isAdminRole,raidDeckPower}=deps;await ensure(env);const user=await authenticate(request,env);if(!user)return json({error:'로그인이 필요합니다.'},401);
  if(path==='admin/idle-dungeon'){if(!isAdminRole(user))return json({error:'권한이 없습니다.'},403);if(request.method==='GET')return json({settings:await settings(env)});const body=await readBody(request),value=clean(body);await env.DB.prepare('INSERT OR REPLACE INTO app_meta(key,value,updated_at) VALUES(?,?,CURRENT_TIMESTAMP)').bind(SETTINGS_KEY,JSON.stringify(value)).run();return json({ok:true,settings:value});}
  let deck;try{deck=await raidDeckPower(env,user.id,null,'PVE')}catch(e){return json({error:'저장된 PVE 덱 5장을 먼저 편성하세요.'},400)}const data=await state(env,user,deck.power),p=data.next,cfg=data.cfg;
  if(!cfg.enabled&&!isAdminRole(user))return json({error:'현재 방치형 원정이 운영 중지 상태입니다.'},503);
  if(path==='idle-dungeon/status')return json({settings:{enabled:cfg.enabled,maxOfflineHours:cfg.maxOfflineHours,floorSeconds:cfg.floorSeconds,difficulties:publicDifficulty(cfg,p.unlocked_difficulty)},progress:{difficulty:p.difficulty,currentFloor:p.current_floor,highestFloor:p.highest_floor,unlockedDifficulty:p.unlocked_difficulty,pendingCoin:p.pending_coin,dailyCoin:p.daily_coin,dailyCap:p.dailyCap,resets:p.total_resets,running:Boolean(p.run_started_at),failed:p.failed,completed:p.completed},deckPower:deck.power,observedMaxPower:data.maxObserved,finalBarrierPower:Math.ceil(Math.max(data.maxObserved*1.18,deck.power*1.12)),monster:p.monster,serverNow:new Date().toISOString()});
  if(path==='idle-dungeon/start'&&request.method==='POST'){const b=await readBody(request),d=cfg.difficulties.find(x=>x.id===String(b.difficulty||'NORMAL').toUpperCase());if(!d||d.index>p.unlocked_difficulty)return json({error:'아직 해금되지 않은 난이도입니다.'},403);await env.DB.prepare(`UPDATE idle_dungeon_progress SET difficulty=?,current_floor=1,run_started_at=CURRENT_TIMESTAMP,last_settled_at=CURRENT_TIMESTAMP,version=version+1,updated_at=CURRENT_TIMESTAMP WHERE user_id=?`).bind(d.id,user.id).run();return json({ok:true,difficulty:d.id});}
  if(path==='idle-dungeon/claim'&&request.method==='POST'){const b=await readBody(request),rid=String(b.requestId||'').slice(0,120);if(!rid)return json({error:'요청 식별값이 필요합니다.'},400);const old=await env.DB.prepare('SELECT response_json FROM idle_dungeon_claim_receipts WHERE request_id=? AND user_id=?').bind(rid,user.id).first();if(old?.response_json)return json(JSON.parse(old.response_json));const amount=Math.max(0,Number(p.pending_coin||0)),response={ok:true,rewardCoin:amount};const result=await env.DB.prepare(`UPDATE idle_dungeon_progress SET pending_coin=0,total_coin=total_coin+?,version=version+1,updated_at=CURRENT_TIMESTAMP WHERE user_id=? AND pending_coin=?`).bind(amount,user.id,amount).run();if(!result.meta.changes)return json({error:'보상 상태가 갱신되었습니다. 다시 확인하세요.'},409);await env.DB.batch([env.DB.prepare('UPDATE users SET coin=coin+? WHERE id=?').bind(amount,user.id),env.DB.prepare('INSERT INTO idle_dungeon_claim_receipts(request_id,user_id,reward_coin,response_json) VALUES(?,?,?,?)').bind(rid,user.id,amount,JSON.stringify(response)),env.DB.prepare(`INSERT INTO coin_logs(user_id,change_amount,balance_after,reason) SELECT ?,?,coin,'방치형 원정 정산' FROM users WHERE id=?`).bind(user.id,amount,user.id)]);return json(response);}
  return json({error:'지원하지 않는 요청입니다.'},404);
}
