import {validateMercenaryCombat} from '../shared/mercenary-combat-policy-v1.mjs';
import {MERCENARY_POWER_STANDARD} from '../shared/equipment-mercenary-power-v1.mjs';
import attachments from '../assets/ui/project-v/mercenaries/mercenary-attachment-points-v1.json' with {type:'json'};
const living=x=>x?.alive!==false&&x?.hp>0&&!x?.untargetable&&!x?.isBattleSuit;
const ordered=team=>team.filter(living).sort((a,b)=>a.slot-b.slot||String(a.id).localeCompare(String(b.id)));
const front=team=>{const all=ordered(team),rows=all.filter(x=>x.row==='FRONT');return rows.length?rows:all.slice(0,1);};
const weakest=team=>ordered(team).sort((a,b)=>a.hp/a.maxHp-b.hp/b.maxHp||a.slot-b.slot)[0];
export function buildMercenaryFighter(snapshot,side,mode,buildCardFighter){
 if(!snapshot)return null;
 if(snapshot.statMode==='RANK_FIXED'){
  const power=MERCENARY_POWER_STANDARD.basePowerByRank[snapshot.rank];
  if(!power||typeof buildCardFighter!=='function')throw Error('INVALID_MERCENARY_RANK_POWER');
  const base=buildCardFighter({id:snapshot.code,power,type:'NONE'},5,side,null,mode);
  snapshot={...snapshot,basePower:power,level:1,stats:{hp:base.maxHp,attack:base.attack,defense:base.defense,speed:base.speed}};
 }
 if(!/^V-\d{3}$/.test(snapshot.code)||!['A','B'].includes(side)||Object.values(snapshot.stats||{}).length!==4||Object.values(snapshot.stats).some(n=>!Number.isSafeInteger(n)||n<=0))throw Error('INVALID_MERCENARY_SNAPSHOT');
 for(const s of snapshot.skills||[]){const b=s.balance;if(!b||!Number.isFinite(b.damageRatio)||b.damageRatio<0||b.damageRatio>10000||!Number.isSafeInteger(Math.floor(snapshot.stats.attack*b.damageRatio))||!Number.isInteger(b.cost)||b.cost<0||!Number.isInteger(b.cooldownTurns)||b.cooldownTurns<0)throw Error('INVALID_MERCENARY_SKILL_BALANCE');}
 const config=validateMercenaryCombat(snapshot.combat),power=Math.round(snapshot.basePower*(1+config.powerGrowthPercentPerLevel*(snapshot.level-1)/100));
 return {...snapshot,id:`${side}:MERCENARY:${snapshot.code}`,cardId:snapshot.code,slot:5,side,battleMode:mode,row:snapshot.position==='FRONT'?'FRONT':'BACK',type:'MERCENARY',typeLabel:snapshot.role,actorKind:'MERCENARY',isMercenary:true,
  image:snapshot.sourceArt,name:snapshot.name,title:snapshot.name,grade:snapshot.rank,power,basePower:snapshot.basePower,equipmentShare:0,combat:config,skills:structuredClone(snapshot.skills||[]),
  attackStyle:snapshot.attackStyle||(['GUN','BOW'].includes(attachments.cards[snapshot.code]?.weaponKind)?'RANGED':attachments.cards[snapshot.code]?.weaponKind==='MAGIC'?'CAST':'MELEE'),
  maxHp:snapshot.stats.hp,hp:Math.round(snapshot.stats.hp*Math.max(0,Math.min(100,snapshot.startingHpPercent??100))/100),attack:snapshot.stats.attack,defense:snapshot.stats.defense,speed:snapshot.stats.speed,shield:0,maxShield:0,gauge:0,alive:(snapshot.startingHpPercent??100)>0,actions:0,damageDealt:0,healingDone:0,uniqueAbility:null};
}
// Uses the canonical battle's RNG, damage caps, knockout/revive handler and
// event clock. Each prepared action spends a normal actor turn. No recursive
// cast/proc chain is generated by counter, poison, support or follow-up hits.
export function mercenaryCombat({teams,hit,damage,knockout,emit,clock}){
 const all=()=>[...teams.A,...teams.B],states=new Map();
 const state=a=>{if(!states.has(a.id))states.set(a.id,{energy:a.combat?.energyMax||0,cooldown:new Map(),pending:null,used:new Set(),hits:0,basicCount:0,nextIndex:0});return states.get(a.id);};
 const buffs=new Map(),debuffs=new Map();
 const table=(map,a)=>{if(!map.has(a.id))map.set(a.id,{});return map.get(a.id);};
 const friendly=a=>ordered(teams[a.side]),enemies=a=>ordered(teams[a.side==='A'?'B':'A']);
 const send=(a,s,phase,t,data={})=>emit(`MERCENARY_${phase}`,{actorId:a.id,actorKind:'MERCENARY',skillId:s.id,skillName:s.name,mechanic:s.mechanic,skillPhaseIndex:['DOT','RIPOSTE'].includes(phase)?1:state(a).pending?.step||0,targetId:t?.id,...data,label:s.name});
 function targets(a,s){const en=enemies(a),fr=front(en),friends=friendly(a);
  if(['INTERCEPT_ONE_HIT','CLEANSE_THEN_MEND'].includes(s.mechanic))return [weakest(friends)].filter(Boolean);
  if(s.mechanic==='MELEE_PARRY_RIPOSTE')return [a];
  if(s.mechanic==='FRONT_SHARED_BARRIER')return front(friends);
  if(s.mechanic==='NEXT_BASIC_ORDER')return friends.filter(t=>!t.isMonster);
  if(['LOCKED_THREAT_SHOT','INFILTRATE_DELAYED_VENOM','UNDISTURBED_FIRST_SHOT'].includes(s.mechanic)){const back=en.filter(t=>t.row==='BACK');return [...(back.length?back:fr)].sort((a,b)=>(b.openingAttack??b.attack)-(a.openingAttack??a.attack)||a.slot-b.slot).slice(0,1);}
  if(s.mechanic==='FINISHER_WITH_RELOAD')return [weakest(en)].filter(Boolean);
  return fr.slice(0,['RIFT_MARK_DETONATION','ADVANCE_SUPPRESSION','FRONT_OFFENSE_VEIL'].includes(s.mechanic)?2:1);
 }
 function effect(a,s,t,amount,phase='HIT',dodge=false){
  if(!living(t))return {hit:false};const st=damage(t,Math.max(0,amount));a.damageDealt+=st.hpDamage+st.absorbed;
  send(a,s,phase,t,{damage:st.hpDamage,absorbed:st.absorbed,targetHpAfter:t.hp,targetMaxHp:t.maxHp,targetShieldAfter:t.shield,dodge});knockout(t);return {hit:!dodge,damage:st.hpDamage+st.absorbed};
 }
 function strike(a,s,t,multiplier=1,phase='HIT',opts={}){
  if(!living(t))return {hit:false};const st=state(a),veil=table(debuffs,a).veil;let scale=Number(s.balance.damageRatio)*multiplier;
  if(veil&&!opts.followup){scale*=1-veil.percent/100;delete table(debuffs,a).veil;}
  if(scale<=0)return effect(a,s,t,0,phase);
  const h=hit(a,t,scale);if(h.dodge){send(a,s,phase,t,{dodge:true,damage:0,targetHpAfter:t.hp,targetShieldAfter:t.shield});return {hit:false};}
  return effect(a,s,t,h.damage,phase);
 }
 function finish(a,s){const st=state(a);st.pending=null;if(['RIFT_MARK_DETONATION','TWO_BEAT_FOLLOWUP'].includes(s.mechanic))st.reload=true;send(a,s,'END');}
 function cancel(a,reason){const st=state(a),p=st.pending;if(!p)return;st.pending=null;if(['RIFT_MARK_DETONATION','TWO_BEAT_FOLLOWUP'].includes(p.skill.mechanic))st.reload=true;send(a,p.skill,'CANCEL',null,{reason});}
 function cleanse(target,onlyDot=false){const d=table(debuffs,target);for(const key of onlyDot?['poison','rift']:['poison','rift','armor','veil','restraint','offender'])if(d[key]){if(key==='armor')target.defense=d[key].original;delete d[key];return key;}return null;}
 function resolve(a,p){const s=p.skill,c=a.combat,st=state(a),ts=p.targets.map(id=>all().find(a=>a.id===id)).filter(living),b=table(buffs,a);
  if(!ts.length){cancel(a,'TARGET_LOST');return;}
  const once=(fn)=>{for(const t of ts)fn(t);finish(a,s);};
  switch(s.mechanic){
   case 'INTERCEPT_ONE_HIT':once(t=>{table(buffs,t).intercept={actor:a,skill:s,percent:c.interceptPercent,expires:a.actions+c.statusTurns};send(a,s,'BUFF',t,{effect:'INTERCEPT_ONE_HIT'});});break;
   case 'MELEE_PARRY_RIPOSTE':once(t=>{b.parry={skill:s,percent:c.parryPercent,expires:a.actions+c.statusTurns};send(a,s,'BUFF',t,{effect:'MELEE_PARRY_RIPOSTE'});});break;
   case 'NEXT_BASIC_ORDER':once(t=>{table(buffs,t).order={percent:c.orderPercent,source:a.id};send(a,s,'BUFF',t,{effect:'NEXT_BASIC_ORDER'});});break;
   case 'FRONT_SHARED_BARRIER':once(t=>{const buff=table(buffs,t),old=buff.mercBarrier||0,budget=Math.floor(a.attack*s.balance.damageRatio/p.targets.length),remaining=Math.min(old,t.shield);t.shield=Math.max(0,t.shield-remaining)+budget;t.maxShield=Math.max(t.maxShield,t.shield);buff.mercBarrier=budget;send(a,s,'BUFF',t,{effect:'SHIELD',amount:budget,targetShieldAfter:t.shield});});break;
   case 'FRONT_OFFENSE_VEIL':once(t=>{table(debuffs,t).veil={percent:c.veilPercent};send(a,s,'DEBUFF',t,{effect:'OFFENSIVE_SKILL_ONLY'});});break;
   case 'CLEANSE_THEN_MEND':
    if(!p.step){const removed=cleanse(ts[0],true);send(a,s,'CLEANSE',ts[0],{removed});p.step=1;p.due=a.actions+1;break;}
    once(t=>{const amount=Math.min(t.maxHp-t.hp,Math.floor(a.attack*s.balance.damageRatio*(1-Math.min(100,Number(t.healingReductionPercent||0))/100)));t.hp+=amount;a.healingDone+=amount;send(a,s,'HEAL',t,{amount,targetHpAfter:t.hp,targetMaxHp:t.maxHp});});break;
   case 'BREAK_ARMOR_WINDOW':once(t=>{const hadShield=t.shield>0;strike(a,s,t);if(hadShield&&living(t)){const d=table(debuffs,t),original=d.armor?.original??t.defense;d.armor={original,expires:t.actions+c.statusTurns};t.defense=original*(1-c.armorReductionPercent/100);send(a,s,'DEBUFF',t,{effect:'ARMOR_WINDOW',defenseAfter:t.defense});}});break;
   case 'ADVANCE_SUPPRESSION':once(t=>{strike(a,s,t,1/p.targets.length);if(living(t)&&!t.controlImmune&&!t.isBoss&&t.row==='FRONT'&&t.attackStyle==='MELEE'){t.gauge=Math.max(0,t.gauge-c.suppressGauge);send(a,s,'DEBUFF',t,{effect:'APPROACH_DELAY',targetGaugeAfter:t.gauge});}});break;
   case 'LOCKED_THREAT_SHOT':once(t=>strike(a,s,t));break;
   case 'UNDISTURBED_FIRST_SHOT':once(t=>{const focused=state(a).hits===p.hits;send(a,s,'FOCUS',t,{focused});strike(a,s,t,focused?1+c.focusBonusPercent/100:1);});break;
   case 'FINISHER_WITH_RELOAD':once(t=>{strike(a,s,t,t.hp/t.maxHp<=c.finisherHpPercent/100?1+c.finisherBonusPercent/100:1);if(living(t))st.reload=true;});break;
   case 'INTERRUPT_WINDUP':once(t=>{const h=strike(a,s,t);if(h.hit&&!t.controlImmune&&!t.isBoss&&state(t).pending)cancel(t,'INTERRUPTED');});break;
   case 'REPEAT_OFFENDER_RESTRAINT':once(t=>{const d=table(debuffs,t),marked=d.offender?.[a.id]||0;const h=strike(a,s,t);if(h.hit&&marked>=c.restraintHits){d.restraint=c.restraintPercent;if(d.offender)delete d.offender[a.id];send(a,s,'DEBUFF',t,{effect:'NEXT_BASIC_WEAKENED'});}});break;
   case 'INFILTRATE_DELAYED_VENOM':once(t=>{const h=strike(a,s,t,1-c.poisonPercent/100);if(h.hit&&living(t)&&!t.poisonImmune){table(debuffs,t).poison={actor:a,skill:s,damage:Math.floor(a.attack*s.balance.damageRatio*c.poisonPercent/100),due:t.actions+1};send(a,s,'DEBUFF',t,{effect:'POISON'});}});break;
   case 'RIFT_MARK_DETONATION':
    if(!p.step){for(const t of ts){const h=strike(a,s,t,.5/p.targets.length);if(h.hit&&living(t))table(debuffs,t).rift={actorId:a.id};}p.step=1;p.due=a.actions+1;}
    else{once(t=>{if(table(debuffs,t).rift?.actorId===a.id){delete table(debuffs,t).rift;strike(a,s,t,.5/p.targets.length,'HIT',{followup:true});}});}break;
   case 'TWO_BEAT_FOLLOWUP':case 'SAME_TARGET_CALIBRATION':{
    const total=s.mechanic==='SAME_TARGET_CALIBRATION'?3:2,index=p.step||0,t=ts[0];const h=strike(a,s,t,(total===3&&index===2?1.4:1)/total,'HIT',{followup:index>0});
    if(!h.hit||!living(t)||index+1>=total)finish(a,s);else{p.step=index+1;p.due=a.actions+1;}break;}
   default:throw Error(`UNSUPPORTED_MERCENARY_MECHANIC:${s.mechanic}`);
  }
 }
 for(const a of all()){a.openingAttack=a.attack;if(a.isMercenary)state(a);}
 return {
  beforeAction(a){
   for(const actor of all())if(!living(actor)&&state(actor).pending)cancel(actor,'CASTER_LOST');
   const d=table(debuffs,a),st=state(a),b=table(buffs,a);
   if(d.armor&&a.actions>=d.armor.expires){a.defense=d.armor.original;delete d.armor;}
   if(d.poison&&a.actions>=d.poison.due){const p=d.poison;delete d.poison;effect(p.actor,p.skill,a,p.damage,'DOT');if(!living(a))return true;}
   if(b.parry&&a.actions>=b.parry.expires)delete b.parry;
   if(!a.isMercenary)return false;
   if(a.stunned||a.silenced){if(st.pending)cancel(a,'CONTROLLED');return Boolean(a.stunned);}
   if(st.pending){if(a.silenced||a.stunned){cancel(a,'CONTROLLED');return true;}if(a.actions>=st.pending.due)resolve(a,st.pending);return true;}
   if(st.reload){a.gauge=Math.max(0,a.gauge-a.combat.reloadGauge);st.reload=false;return false;}
   const skills=a.skills||[];for(let i=0;i<skills.length;i++){const index=(st.nextIndex+i)%skills.length,s=skills[index];if(st.cooldown.get(s.id)>a.actions||st.energy<s.balance.cost||s.mechanic==='UNDISTURBED_FIRST_SHOT'&&st.used.has(s.id))continue;const selected=targets(a,s);if(!selected.length)continue;
    st.energy-=s.balance.cost;st.cooldown.set(s.id,a.actions+Math.max(1,s.balance.cooldownTurns));st.used.add(s.id);st.nextIndex=(index+1)%skills.length;st.pending={skill:s,targets:selected.map(t=>t.id),due:a.actions+a.combat.windupTurns,hits:st.hits,step:0};
    send(a,s,'WINDUP',selected[0],{targetIds:st.pending.targets,energyAfter:st.energy});return true;
   }return false;
  },
  basicMultiplier(a){const b=table(buffs,a),d=table(debuffs,a);let factor=1;if(b.order){factor*=1+b.order.percent/100;delete b.order;}if(d.restraint){factor*=1-d.restraint/100;delete d.restraint;}return factor;},
  beforeBasicDamage(a,t,amount){const buff=table(buffs,t),intercept=buff.intercept;
   if(intercept&&living(intercept.actor)&&intercept.actor.id!==t.id&&intercept.actor.actions<intercept.expires){delete buff.intercept;const share=Math.floor(amount*intercept.percent/100),protector=intercept.actor,result=damage(protector,share);a.damageDealt+=result.hpDamage+result.absorbed;send(protector,intercept.skill,'INTERCEPT',protector,{sourceAttackerId:a.id,damage:result.hpDamage,absorbed:result.absorbed,targetHpAfter:protector.hp,targetMaxHp:protector.maxHp,targetShieldAfter:protector.shield});knockout(protector);amount-=share;}
   if(buff.parry&&a.row==='FRONT'&&a.attackStyle==='MELEE'&&!a.counterImmune){const parry=buff.parry;delete buff.parry;amount=Math.floor(amount*(1-parry.percent/100));state(t).riposte={skill:parry.skill,target:a};}
   return amount;
  },
  onDamage(t,result){if(result.hpDamage+result.absorbed>0)state(t).hits++;const b=table(buffs,t);if(b.mercBarrier)b.mercBarrier=Math.max(0,b.mercBarrier-result.absorbed);},
  afterBasic(a,t,hit,{additional=false}={}){if(hit&&!additional){if(a.isMercenary)state(a).energy=Math.min(a.combat.energyMax,state(a).energy+a.combat.energyPerBasic);const d=table(debuffs,a);d.offender||={};for(const enemy of enemies(a).filter(e=>e.isMercenary&&e.skills?.some(s=>s.mechanic==='REPEAT_OFFENDER_RESTRAINT')))d.offender[enemy.id]=Math.min(10,(d.offender[enemy.id]||0)+1);}
   const r=state(t).riposte;delete state(t).riposte;if(r&&living(t)&&living(r.target))strike(t,r.skill,r.target,1,'RIPOSTE',{followup:true});
  },cleanse,cancel,state,buffs,debuffs,
 };
}
