import {apocalypseSealed,apocalypseHealing,clearApocalypseStatus} from './_apocalypse_legion.js';
import {validateMercenaryCombat} from '../shared/mercenary-combat-policy-v1.mjs';
import {MERCENARY_POWER_STANDARD} from '../shared/equipment-mercenary-power-v1.mjs';
import {MERCENARY_COMBAT_LINK,mercenaryEffectiveAttack} from '../shared/mercenary-combat-link-v2103.mjs';
import {mercenaryAttackStyle} from '../shared/mercenary-attack-style-v1.mjs';
import {isRangedMercenarySkill,rangedMercenaryProfile,rangedMercenaryPvpScale} from '../shared/mercenary-ranged-balance-v1.mjs';
import {isMercenaryGuardSkill,MERCENARY_GUARD_BASIC_SCALE} from '../shared/mercenary-guard-balance-v1.mjs';
import {isMercenaryMoonDrawSkill} from '../shared/mercenary-moon-draw-v1.mjs';
const living=x=>x?.alive!==false&&x?.hp>0&&!x?.untargetable&&!x?.isBattleSuit;
const ordered=team=>team.filter(living).sort((a,b)=>a.slot-b.slot||String(a.id).localeCompare(String(b.id)));
const front=team=>{const all=ordered(team),rows=all.filter(x=>x.row==='FRONT');return rows.length?rows:all.slice(0,1);};
const weakest=team=>ordered(team).sort((a,b)=>a.hp/a.maxHp-b.hp/b.maxHp||a.slot-b.slot)[0];
// Rank power is fixed while ordinary cards include unbounded equipment power.
// The mercenary remains targetable, but its reserved action is additional:
// released fighters act after each allied card action without replacing a card,
// advancing its gauge, or consuming the five-card battle's action budget.
// Natural mercenary turns clear the debt; suit shots and enemy turns cannot.
export function mercenaryTurnCadence(teams){
 const debt={A:0,B:0};
 const interval=side=>teams[side]?.some(a=>a.isMercenary&&a.statMode==='RANK_FIXED')?MERCENARY_COMBAT_LINK.regularActionsPerTurn:5;
 const regular=actor=>living(actor)&&!actor.isMonster&&!actor.isMercenary&&actor.actorKind!=='BATTLE_SUIT';
 return {
  pending(eligible=()=>true){
   return ['A','B'].flatMap(side=>debt[side]>=interval(side)?teams[side]?.filter(a=>a.isMercenary&&living(a)&&eligible(a))||[]:[])[0]||null;
  },
  select(actor){
   if(!regular(actor)||debt[actor.side]<interval(actor.side))return actor;
   return teams[actor.side]?.find(a=>a.isMercenary&&living(a))||actor;
  },
  acted(actor){
   if(actor.isMercenary)debt[actor.side]=0;
   else if(regular(actor))debt[actor.side]=Math.min(interval(actor.side),debt[actor.side]+1);
  }
 };
}
export function buildMercenaryFighter(snapshot,side,mode,buildCardFighter){
 if(!snapshot)return null;
 if(snapshot.statMode==='RANK_FIXED'){
  const power=MERCENARY_POWER_STANDARD.basePowerByRank[snapshot.rank];
  if(!power||typeof buildCardFighter!=='function')throw Error('INVALID_MERCENARY_RANK_POWER');
  const base=buildCardFighter({id:snapshot.code,power,type:'NONE'},5,side,null,mode);
  snapshot={...snapshot,basePower:power,level:1,stats:{hp:base.maxHp,attack:base.attack,defense:base.defense,speed:base.speed}};
 }
 if(!/^V-\d{3}$/.test(snapshot.code)||!['A','B'].includes(side)||Object.values(snapshot.stats||{}).length!==4||Object.values(snapshot.stats).some(n=>!Number.isSafeInteger(n)||n<=0))throw Error('INVALID_MERCENARY_SNAPSHOT');
 for(const s of snapshot.skills||[]){const b=s.balance;if(!b||!Number.isFinite(b.damageRatio)||b.damageRatio<0||b.damageRatio>10000||!Number.isSafeInteger(Math.floor(snapshot.stats.attack*b.damageRatio))||!Number.isInteger(b.cost)||b.cost<0||!Number.isInteger(b.cooldownTurns)||b.cooldownTurns<0)throw Error('INVALID_MERCENARY_SKILL_BALANCE');}
 const config=validateMercenaryCombat(snapshot.combat),power=Math.round(snapshot.basePower*(1+config.powerGrowthPercentPerLevel*(snapshot.level-1)/100));
 return {...snapshot,id:`${side}:MERCENARY:${snapshot.code}`,cardId:snapshot.code,slot:5,side,battleMode:mode,row:snapshot.position==='FRONT'?'FRONT':'BACK',type:'MERCENARY',typeLabel:snapshot.role,actorKind:'MERCENARY',isMercenary:true,
  image:snapshot.sourceArt,name:snapshot.name,title:snapshot.name,grade:snapshot.rank,power,basePower:snapshot.basePower,equipmentShare:0,combat:config,skills:structuredClone(snapshot.skills||[]),
  attackStyle:mercenaryAttackStyle(snapshot),
  maxHp:snapshot.stats.hp,hp:Math.round(snapshot.stats.hp*Math.max(0,Math.min(100,snapshot.startingHpPercent??100))/100),attack:snapshot.stats.attack,defense:snapshot.stats.defense,speed:snapshot.stats.speed,shield:0,maxShield:0,gauge:0,alive:(snapshot.startingHpPercent??100)>0,actions:0,damageDealt:0,healingDone:0,uniqueAbility:null};
}
// Uses the canonical battle's RNG, damage caps, knockout/revive handler and
// event clock. Sniper and sequential ranged fixes have separate action costs.
// Other prepared actions retain their normal actor turns. No recursive
// cast/proc chain is generated by counter, poison, support or follow-up hits.
export function mercenaryCombat({teams,hit,damage,knockout,emit,clock}){
 const all=()=>[...teams.A,...teams.B],states=new Map();
 const state=a=>{if(!states.has(a.id))states.set(a.id,{energy:a.combat?.energyMax||0,cooldown:new Map(),pending:null,used:new Set(),hits:0,basicCount:0,nextIndex:0});return states.get(a.id);};
 const buffs=new Map(),debuffs=new Map();
 const table=(map,a)=>{if(!map.has(a.id))map.set(a.id,{});return map.get(a.id);};
 const friendly=a=>ordered(teams[a.side]),enemies=a=>ordered(teams[a.side==='A'?'B':'A']);
 const send=(a,s,phase,t,data={})=>emit(`MERCENARY_${phase}`,{actorId:a.id,actorKind:'MERCENARY',skillId:s.id,skillName:s.name,mechanic:s.mechanic,skillPhaseIndex:['DOT','RIPOSTE'].includes(phase)?1:state(a).pending?.step||0,targetId:t?.id,...data,label:s.name});
 function targets(a,s){const en=enemies(a),fr=front(en),friends=friendly(a);
  if(isMercenaryGuardSkill(s))return [weakest(friends.filter(t=>t.id!==a.id&&!activeIntercept(t)))].filter(Boolean);
  if(s.mechanic==='CLEANSE_THEN_MEND')return [weakest(friends)].filter(Boolean);
  if(s.mechanic==='MELEE_PARRY_RIPOSTE')return [a];
  if(['FRONT_SHARED_BARRIER','FRONT_STAND_FAST'].includes(s.mechanic))return front(friends);
  if(s.mechanic==='NEXT_BASIC_ORDER')return friends.filter(t=>!t.isMonster);
  if(['LOCKED_THREAT_SHOT','INFILTRATE_DELAYED_VENOM','UNDISTURBED_FIRST_SHOT','ABYSS_SHIELD_ECHO'].includes(s.mechanic)){const back=en.filter(t=>t.row==='BACK');return [...(back.length?back:fr)].sort((a,b)=>(b.openingAttack??b.attack)-(a.openingAttack??a.attack)||a.slot-b.slot).slice(0,1);}
  if(['FINISHER_WITH_RELOAD','WOUNDED_MOON_DRAW','DANCING_TARGET_VOLLEY'].includes(s.mechanic))return [weakest(en)].filter(Boolean);
  if(s.mechanic==='DISTRIBUTED_CORAL_VOLLEY')return [...en].sort((a,b)=>a.hp/a.maxHp-b.hp/b.maxHp||a.slot-b.slot).slice(0,3);
  return fr.slice(0,['RIFT_MARK_DETONATION','ADVANCE_SUPPRESSION','FRONT_OFFENSE_VEIL'].includes(s.mechanic)?2:1);
 }
 function effect(a,s,t,amount,phase='HIT',dodge=false){
  if(!living(t))return {hit:false};const st=damage(t,Math.max(0,amount));a.damageDealt+=st.hpDamage+st.absorbed;
  send(a,s,phase,t,{damage:st.hpDamage,absorbed:st.absorbed,targetHpAfter:t.hp,targetMaxHp:t.maxHp,targetShieldAfter:t.shield,dodge});knockout(t);return {hit:!dodge,damage:st.hpDamage+st.absorbed,absorbed:st.absorbed};
 }
 function activeIntercept(t){
  const buff=table(buffs,t),ward=buff.intercept;
  if(ward&&(!living(t)||!living(ward.actor)||t.actions>=ward.expires)){delete buff.intercept;return null;}
  return ward||null;
 }
 function interceptDamage(a,t,amount){
  const ward=activeIntercept(t);if(!ward||amount<=0||ward.actor.id===t.id||ward.actor.stunned||ward.actor.silenced)return amount;
  delete table(buffs,t).intercept;
  const protector=ward.actor,share=Math.floor(amount*ward.percent/100),result=damage(protector,share),transferred=result.hpDamage+result.absorbed;
  a.damageDealt+=transferred;
  send(protector,ward.skill,'INTERCEPT',protector,{sourceAttackerId:a.id,protectedTargetId:t.id,damage:result.hpDamage,absorbed:result.absorbed,targetHpAfter:protector.hp,targetMaxHp:protector.maxHp,targetShieldAfter:protector.shield});
  knockout(protector);return amount-transferred;
 }
 function strike(a,s,t,multiplier=1,phase='HIT',opts={}){
  if(!living(t))return {hit:false};const veil=table(debuffs,a).veil,pvpScale=rangedMercenaryPvpScale(a,s);let scale=Number(s.balance.damageRatio)*multiplier*pvpScale;
  if(veil&&!opts.followup){scale*=1-veil.percent/100;delete table(debuffs,a).veil;}
  if(scale<=0)return effect(a,s,t,0,phase);
  const h=hit(a,t,scale,{rangedSkill:isRangedMercenarySkill(a,s),castShare:(opts.castShare??1)*pvpScale});if(h.dodge){send(a,s,phase,t,{dodge:true,damage:0,targetHpAfter:t.hp,targetShieldAfter:t.shield});return {hit:false};}
  // Only direct single-target skill impacts can consume the link. Area skills,
  // poison, counters and fixed boss effects retain their own damage paths.
  const single=phase==='HIT'&&!['RIFT_MARK_DETONATION','ADVANCE_SUPPRESSION','DISTRIBUTED_CORAL_VOLLEY'].includes(s.mechanic);
  return effect(a,s,t,single?interceptDamage(a,t,h.damage):h.damage,phase);
 }
 function finish(a,s){const st=state(a);st.pending=null;if(!isRangedMercenarySkill(a,s)&&['RIFT_MARK_DETONATION','TWO_BEAT_FOLLOWUP','WOUNDED_MOON_DRAW'].includes(s.mechanic))st.reload=true;send(a,s,'END');}
 function cancel(a,reason){const st=state(a),p=st.pending;if(!p)return;st.pending=null;if(!isRangedMercenarySkill(a,p.skill)&&['RIFT_MARK_DETONATION','TWO_BEAT_FOLLOWUP','WOUNDED_MOON_DRAW'].includes(p.skill.mechanic))st.reload=true;send(a,p.skill,'CANCEL',null,{reason});}
 function cleanse(target,onlyDot=false){if(!onlyDot&&Object.keys(target.apocalypseStatus||{}).length){clearApocalypseStatus(target);emit('APOCALYPSE_STATUS',{targetId:target.id,statuses:{},label:'정화'});return 'apocalypse';}const d=table(debuffs,target);for(const key of onlyDot?['poison','rift']:['poison','rift','thorn','oath','armor','veil','restraint','offender'])if(d[key]){if(key==='armor')target.defense=d[key].original;delete d[key];return key;}return null;}
 // Snipers fire within one action. Slow volleys start immediately but keep
 // one projectile per actor action, so they cannot burst three full hit caps.
 function resolveRanged(a,p){
  const s=p.skill,c=a.combat,mechanic=s.mechanic,sequential=rangedMercenaryProfile(a,s)==='SEQUENTIAL';
  const count=['SAME_TARGET_CALIBRATION','DANCING_TARGET_VOLLEY','PLATINUM_FOCUS_LOCK'].includes(mechanic)?3:
   ['ABYSS_SHIELD_ECHO','TWO_BEAT_FOLLOWUP'].includes(mechanic)?2:mechanic==='DISTRIBUTED_CORAL_VOLLEY'?p.targets.length:1;
  const totalScale=mechanic==='ABYSS_SHIELD_ECHO'?1+c.focusBonusPercent/100:
   mechanic==='OBSERVED_SHIELD_BREAK'?1+c.armorReductionPercent/100:mechanic==='FINISHER_WITH_RELOAD'?1+c.finisherBonusPercent/100:1;
  const start=p.step||0,end=sequential?start+1:count;
  for(let index=start;index<end&&living(a);index++){
   let t=all().find(t=>t.id===(p.currentTarget||p.targets[0]));
   if(mechanic==='DANCING_TARGET_VOLLEY')t=weakest(enemies(a).filter(t=>t.id!==p.previousTarget))||weakest(enemies(a));
   if(mechanic==='DISTRIBUTED_CORAL_VOLLEY')t=all().find(t=>t.id===p.targets[index]);
   if(!living(t))t=targets(a,s)[0];
   if(!t){finish(a,s);return;}
   p.step=index;
   if(index>0&&t.id!==(p.currentTarget||p.targets[0]))send(a,s,'WINDUP',t,{targetIds:[t.id],continuation:true});
   p.currentTarget=t.id;p.previousTarget=t.id;
   let scale=1/count;
   if(mechanic==='SAME_TARGET_CALIBRATION'&&index===2)scale=1.4/count;
   if(mechanic==='ABYSS_SHIELD_ECHO'&&index===1)scale+=c.focusBonusPercent/100;
   if(mechanic==='OBSERVED_SHIELD_BREAK')scale=1+c.armorReductionPercent/100;
   if(mechanic==='FINISHER_WITH_RELOAD')scale=1+c.finisherBonusPercent/100;
   const h=strike(a,s,t,scale,'HIT',{followup:index>0,castShare:sequential?1:scale/totalScale});
   if(h.hit&&living(t)&&mechanic==='PLATINUM_FOCUS_LOCK'&&!(p.weakened?.has(t.id))){(p.weakened||=new Set()).add(t.id);table(debuffs,t).veil={percent:c.veilPercent};send(a,s,'DEBUFF',t,{effect:'OFFENSIVE_SKILL_ONLY'});}
  }
  if(sequential&&end<count&&enemies(a).length){p.step=end;p.due=a.actions+1;return;}
  finish(a,s);
 }
 function resolve(a,p){const s=p.skill,c=a.combat,st=state(a),ts=p.targets.map(id=>all().find(a=>a.id===id)).filter(living),b=table(buffs,a);
  // A weakest-target draw frequently loses its target to an allied attack
  // during preparation. Spend the already-paid strike on the next legal enemy
  // within this action, without another windup turn, cost or cooldown reset.
  if(!ts.length&&isMercenaryMoonDrawSkill(s)){
   const replacement=targets(a,s)[0];
   if(replacement){p.targets=[replacement.id];ts.push(replacement);send(a,s,'WINDUP',replacement,{targetIds:p.targets,continuation:true,retargeted:true});}
  }
  if(!ts.length){cancel(a,'TARGET_LOST');return;}
  const once=(fn)=>{for(const t of ts)fn(t);finish(a,s);};
  switch(s.mechanic){
   // The nine authored tracers share one canonical hit, never nine full damage rolls.
   case 'TIDAL_BARRAGE':once(t=>strike(a,s,t));break;
   case 'DUEL_OATH':once(t=>{if(strike(a,s,t).hit&&living(t)){table(debuffs,t).oath={actorId:a.id,percent:c.parryPercent,expires:t.actions+c.statusTurns};send(a,s,'DEBUFF',t,{effect:'DUEL_OATH'});}});break;
   case 'OBSERVED_SHIELD_BREAK':once(t=>{const h=strike(a,s,t);if(h.hit&&living(t)&&t.shield>0){const budget=Math.min(t.shield,Math.floor(mercenaryEffectiveAttack(a)*s.balance.damageRatio*c.armorReductionPercent/100)),result=damage(t,budget);a.damageDealt+=result.absorbed;send(a,s,'DEBUFF',t,{effect:'SHIELD_ONLY_BREAK',amount:result.absorbed,targetShieldAfter:t.shield});}});break;
   case 'WOUNDED_MOON_DRAW':once(t=>strike(a,s,t,1+(1-t.hp/t.maxHp)*c.finisherBonusPercent/100));break;
   case 'FRONT_STAND_FAST':once(t=>{table(buffs,t).standfast={actor:a,skill:s,percent:c.interceptPercent,budget:Math.floor(mercenaryEffectiveAttack(a)*s.balance.damageRatio/p.targets.length),expires:a.actions+c.statusTurns};send(a,s,'BUFF',t,{effect:'FRONT_STAND_FAST'});});break;
   case 'THORN_RECOIL_SEAL':once(t=>{const h=strike(a,s,t,1-c.poisonPercent/100);if(h.hit&&living(t)){table(debuffs,t).thorn={actor:a,skill:s,damage:Math.floor(mercenaryEffectiveAttack(a)*s.balance.damageRatio*c.poisonPercent/100),expires:t.actions+c.statusTurns};send(a,s,'DEBUFF',t,{effect:'THORN_RECOIL_SEAL'});}});break;
   case 'ABYSS_SHIELD_ECHO':{
    const t=ts[0];if(!p.step){const h=strike(a,s,t,.5);if(!h.hit||!living(t)){finish(a,s);break;}p.absorbed=Math.min(h.absorbed||0,Math.floor(mercenaryEffectiveAttack(a)*s.balance.damageRatio*c.focusBonusPercent/100));p.step=1;p.due=a.actions+1;}
    else{const base=mercenaryEffectiveAttack(a)*s.balance.damageRatio;strike(a,s,t,.5+(base>0?p.absorbed/base:0),'HIT',{followup:true});finish(a,s);}break;}
   case 'DANCING_TARGET_VOLLEY':{
    const t=ts[0],index=p.step||0;strike(a,s,t,1/3,'HIT',{followup:index>0});if(index>=2){finish(a,s);break;}
    const next=weakest(enemies(a).filter(e=>e.id!==t.id))||weakest(enemies(a));if(!next){finish(a,s);break;}
    p.step=index+1;p.targets=[next.id];p.due=a.actions+1;send(a,s,'WINDUP',next,{targetIds:[next.id],continuation:true});break;}
   case 'PLATINUM_FOCUS_LOCK':{
    const t=ts[0],index=p.step||0,h=strike(a,s,t,1/3,'HIT',{followup:index>0});p.allHit=(p.allHit!==false)&&h.hit;
    if(!living(t)||index>=2){if(living(t)&&p.allHit){table(debuffs,t).veil={percent:c.veilPercent};send(a,s,'DEBUFF',t,{effect:'OFFENSIVE_SKILL_ONLY'});}finish(a,s);}else{p.step=index+1;p.due=a.actions+1;}break;}
   case 'DISTRIBUTED_CORAL_VOLLEY':{
    const index=p.step||0,t=all().find(t=>t.id===p.targets[index]);if(living(t))strike(a,s,t,1/p.targets.length,'HIT',{followup:index>0});
    if(index+1>=p.targets.length)finish(a,s);else{p.step=index+1;p.due=a.actions+1;}break;}
   case 'INTERCEPT_ONE_HIT':once(t=>{table(buffs,t).intercept={actor:a,skill:s,percent:c.interceptPercent,expires:t.actions+c.statusTurns};send(a,s,'BUFF',t,{effect:'INTERCEPT_ONE_HIT'});});break;
   case 'MELEE_PARRY_RIPOSTE':once(t=>{b.parry={skill:s,percent:c.parryPercent,expires:a.actions+c.statusTurns};send(a,s,'BUFF',t,{effect:'MELEE_PARRY_RIPOSTE'});});break;
   case 'NEXT_BASIC_ORDER':once(t=>{table(buffs,t).order={percent:c.orderPercent,source:a.id};send(a,s,'BUFF',t,{effect:'NEXT_BASIC_ORDER'});});break;
   case 'FRONT_SHARED_BARRIER':once(t=>{const buff=table(buffs,t),old=buff.mercBarrier||0,budget=Math.floor(mercenaryEffectiveAttack(a)*s.balance.damageRatio/p.targets.length),remaining=Math.min(old,t.shield);t.shield=Math.max(0,t.shield-remaining)+budget;t.maxShield=Math.max(t.maxShield,t.shield);buff.mercBarrier=budget;send(a,s,'BUFF',t,{effect:'SHIELD',amount:budget,targetShieldAfter:t.shield});});break;
   case 'FRONT_OFFENSE_VEIL':once(t=>{table(debuffs,t).veil={percent:c.veilPercent};send(a,s,'DEBUFF',t,{effect:'OFFENSIVE_SKILL_ONLY'});});break;
   case 'CLEANSE_THEN_MEND':
    if(!p.step){const removed=cleanse(ts[0],true);send(a,s,'CLEANSE',ts[0],{removed});p.step=1;p.due=a.actions+1;break;}
    once(t=>{const amount=apocalypseHealing(t,Math.min(t.maxHp-t.hp,Math.floor(mercenaryEffectiveAttack(a)*s.balance.damageRatio*(1-Math.min(100,Number(t.healingReductionPercent||0))/100))));t.hp+=amount;a.healingDone+=amount;send(a,s,'HEAL',t,{amount,targetHpAfter:t.hp,targetMaxHp:t.maxHp});});break;
   case 'BREAK_ARMOR_WINDOW':once(t=>{const hadShield=t.shield>0;strike(a,s,t);if(hadShield&&living(t)){const d=table(debuffs,t),original=d.armor?.original??t.defense;d.armor={original,expires:t.actions+c.statusTurns};t.defense=original*(1-c.armorReductionPercent/100);send(a,s,'DEBUFF',t,{effect:'ARMOR_WINDOW',defenseAfter:t.defense});}});break;
   case 'ADVANCE_SUPPRESSION':once(t=>{strike(a,s,t,1/p.targets.length);if(living(t)&&!t.controlImmune&&!t.isBoss&&t.row==='FRONT'&&t.attackStyle==='MELEE'){t.gauge=Math.max(0,t.gauge-c.suppressGauge);send(a,s,'DEBUFF',t,{effect:'APPROACH_DELAY',targetGaugeAfter:t.gauge});}});break;
   case 'LOCKED_THREAT_SHOT':once(t=>strike(a,s,t));break;
   case 'UNDISTURBED_FIRST_SHOT':once(t=>{const focused=state(a).hits===p.hits;send(a,s,'FOCUS',t,{focused});strike(a,s,t,focused?1+c.focusBonusPercent/100:1);});break;
   case 'FINISHER_WITH_RELOAD':once(t=>{strike(a,s,t,t.hp/t.maxHp<=c.finisherHpPercent/100?1+c.finisherBonusPercent/100:1);if(living(t))st.reload=true;});break;
   case 'INTERRUPT_WINDUP':once(t=>{const h=strike(a,s,t);if(h.hit&&!t.controlImmune&&!t.isBoss&&state(t).pending)cancel(t,'INTERRUPTED');});break;
   case 'REPEAT_OFFENDER_RESTRAINT':once(t=>{const d=table(debuffs,t),marked=d.offender?.[a.id]||0;const h=strike(a,s,t);if(h.hit&&marked>=c.restraintHits){d.restraint=c.restraintPercent;if(d.offender)delete d.offender[a.id];send(a,s,'DEBUFF',t,{effect:'NEXT_BASIC_WEAKENED'});}});break;
   case 'INFILTRATE_DELAYED_VENOM':once(t=>{const h=strike(a,s,t,1-c.poisonPercent/100);if(h.hit&&living(t)&&!t.poisonImmune){table(debuffs,t).poison={actor:a,skill:s,damage:Math.floor(mercenaryEffectiveAttack(a)*s.balance.damageRatio*c.poisonPercent/100),due:t.actions+1};send(a,s,'DEBUFF',t,{effect:'POISON'});}});break;
   case 'RIFT_MARK_DETONATION':
    if(!p.step){for(const t of ts){const h=strike(a,s,t,.5/p.targets.length);if(h.hit&&living(t))table(debuffs,t).rift={actorId:a.id};}p.step=1;p.due=a.actions+1;}
    else{once(t=>{if(table(debuffs,t).rift?.actorId===a.id){delete table(debuffs,t).rift;strike(a,s,t,.5/p.targets.length,'HIT',{followup:true});}});}break;
   case 'TWO_BEAT_FOLLOWUP':case 'SAME_TARGET_CALIBRATION':{
    const total=s.mechanic==='SAME_TARGET_CALIBRATION'?3:2,index=p.step||0,t=ts[0];const h=strike(a,s,t,(total===3&&index===2?1.4:1)/total,'HIT',{followup:index>0});
    if(!h.hit||!living(t)||index+1>=total)finish(a,s);else{p.step=index+1;p.due=a.actions+1;}break;}
   default:throw Error(`UNSUPPORTED_MERCENARY_MECHANIC:${s.mechanic}`);
  }
 }
 for(const a of all()){a.openingAttack=mercenaryEffectiveAttack(a);if(a.isMercenary)state(a);}
 return {
  beforeAction(a){
   for(const actor of all())if(!living(actor)&&state(actor).pending)cancel(actor,'CASTER_LOST');
   const d=table(debuffs,a),st=state(a),b=table(buffs,a);
   for(const key of ['thorn','oath'])if(d[key]&&a.actions>=d[key].expires)delete d[key];
   if(d.armor&&a.actions>=d.armor.expires){a.defense=d.armor.original;delete d.armor;}
   if(d.poison&&a.actions>=d.poison.due){const p=d.poison;delete d.poison;effect(p.actor,p.skill,a,p.damage,'DOT');if(!living(a))return true;}
   if(b.parry&&a.actions>=b.parry.expires)delete b.parry;
   if(!a.isMercenary)return false;
   if(!living(a))return true;
   if(apocalypseSealed(a)){if(st.pending)cancel(a,'APOCALYPSE_SEALED');return false;}
   if(a.stunned||a.silenced){if(st.pending)cancel(a,'CONTROLLED');return Boolean(a.stunned);}
   if(st.pending){if(a.silenced||a.stunned){cancel(a,'CONTROLLED');return true;}if(a.actions>=st.pending.due){if(isRangedMercenarySkill(a,st.pending.skill))resolveRanged(a,st.pending);else resolve(a,st.pending);}return true;}
   if(st.reload){a.gauge=Math.max(0,a.gauge-a.combat.reloadGauge);st.reload=false;return false;}
   const skills=a.skills||[];for(let i=0;i<skills.length;i++){const index=(st.nextIndex+i)%skills.length,s=skills[index],ranged=isRangedMercenarySkill(a,s);if(st.cooldown.get(s.id)>a.actions||st.energy<s.balance.cost||s.mechanic==='UNDISTURBED_FIRST_SHOT'&&st.used.has(s.id))continue;
    if(isMercenaryGuardSkill(s)&&friendly(a).some(t=>activeIntercept(t)?.actor.id===a.id))continue;
    const selected=targets(a,s);if(!selected.length)continue;
    st.energy-=s.balance.cost;st.cooldown.set(s.id,a.actions+Math.max(1,s.balance.cooldownTurns));st.used.add(s.id);st.nextIndex=(index+1)%skills.length;st.pending={skill:s,targets:selected.map(t=>t.id),due:a.actions+a.combat.windupTurns,hits:st.hits,step:0};
    send(a,s,'WINDUP',selected[0],{targetIds:st.pending.targets,energyAfter:st.energy});if(ranged)resolveRanged(a,st.pending);else if(isMercenaryGuardSkill(s)){resolve(a,st.pending);st.guardBasicAction=a.actions;return false;}return true;
   }return false;
  },
  basicMultiplier(a){const b=table(buffs,a),d=table(debuffs,a);let factor=state(a).guardBasicAction===a.actions?MERCENARY_GUARD_BASIC_SCALE:1;if(b.order){factor*=1+b.order.percent/100;delete b.order;}if(d.restraint){factor*=1-d.restraint/100;delete d.restraint;}return factor;},
  beforeBasicDamage(a,t,amount){const buff=table(buffs,t),d=table(debuffs,a);
   if(d.oath){const oath=d.oath;delete d.oath;if(oath.actorId===t.id&&a.actions<oath.expires)amount=Math.floor(amount*(1-oath.percent/100));}
   if(buff.standfast){const ward=buff.standfast;delete buff.standfast;if(living(ward.actor)&&ward.actor.actions<ward.expires){const saved=Math.min(ward.budget,Math.floor(amount*ward.percent/100));amount-=saved;send(ward.actor,ward.skill,'BUFF',t,{effect:'STAND_FAST_CONSUMED',amount:saved});}}

   amount=interceptDamage(a,t,amount);
   if(buff.parry&&a.row==='FRONT'&&a.attackStyle==='MELEE'&&!a.counterImmune){const parry=buff.parry;delete buff.parry;amount=Math.floor(amount*(1-parry.percent/100));state(t).riposte={skill:parry.skill,target:a};}
   return amount;
  },
  onDamage(t,result){if(result.hpDamage+result.absorbed>0)state(t).hits++;const b=table(buffs,t);if(b.mercBarrier)b.mercBarrier=Math.max(0,b.mercBarrier-result.absorbed);},
  afterBasic(a,t,hit,{additional=false}={}){if(hit&&!additional){if(a.isMercenary&&state(a).guardBasicAction!==a.actions)state(a).energy=Math.min(a.combat.energyMax,state(a).energy+a.combat.energyPerBasic);const d=table(debuffs,a);d.offender||={};for(const enemy of enemies(a).filter(e=>e.isMercenary&&e.skills?.some(s=>s.mechanic==='REPEAT_OFFENDER_RESTRAINT')))d.offender[enemy.id]=Math.min(10,(d.offender[enemy.id]||0)+1);}
   if(hit&&!additional){const d=table(debuffs,a),thorn=d.thorn;if(thorn){delete d.thorn;if(living(thorn.actor)&&living(a)&&a.actions<thorn.expires)effect(thorn.actor,thorn.skill,a,thorn.damage,'DOT');}}
   const r=state(t).riposte;delete state(t).riposte;if(r&&living(t)&&living(r.target))strike(t,r.skill,r.target,1,'RIPOSTE',{followup:true});
  },cleanse,cancel,state,buffs,debuffs,
 };
}
