const CASE_TABLE='prison_release_cases_v2031';
const CONTRIBUTION_TABLE='prison_release_contributions_v2031';
const HIT_COOLDOWN_TABLE='prison_hit_cooldowns_v2031';
const HIT_EVENT_TABLE='prison_hit_events_v2031';

export const PRISON_HIT_COOLDOWN_SECONDS=60;
export const PRISON_RELEASE_PRICE_MAX=1_000_000_000_000;

let foundationPromise=null;

const integer=value=>{const parsed=Number(value);return Number.isSafeInteger(parsed)?parsed:NaN};
const changes=result=>Number(result?.meta?.changes||0);
const cleanText=(value,max=160)=>String(value??'').trim().slice(0,max);
const validRequestId=value=>{const requestId=cleanText(value,120);return requestId.length>=8&&/^[A-Za-z0-9:_-]+$/.test(requestId)?requestId:''};

export function prisonReleaseProgress(collectedCoin,releasePrice){
  const collected=Math.max(0,integer(collectedCoin)||0),price=Math.max(0,integer(releasePrice)||0),remaining=price>0?Math.max(0,price-collected):0;
  return {collectedCoin:collected,releasePrice:price,remainingCoin:remaining,progressPercent:price>0?Math.max(0,Math.min(100,Math.floor(collected*10000/price)/100)):0,funded:price>0&&collected>=price};
}

export function prisonHitCooldownRemaining(nextAtMs,nowMs=Date.now()){
  const next=Math.max(0,integer(nextAtMs)||0),now=Math.max(0,integer(nowMs)||0);
  return Math.max(0,Math.ceil((next-now)/1000));
}

function schemaStatements(postgres=false){
  const idType=postgres?'BIGINT':'INTEGER',amountType=postgres?'BIGINT':'INTEGER',eventId=postgres?'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY':'INTEGER PRIMARY KEY AUTOINCREMENT';
  const nowDefault=postgres?"to_char(timezone('UTC',CURRENT_TIMESTAMP),'YYYY-MM-DD HH24:MI:SS')":'CURRENT_TIMESTAMP';
  return [
    `CREATE TABLE IF NOT EXISTS ${CASE_TABLE}(
      inmate_user_id ${idType} PRIMARY KEY,case_id TEXT NOT NULL UNIQUE,release_price ${amountType} NOT NULL DEFAULT 0,
      collected_coin ${amountType} NOT NULL DEFAULT 0,contribution_count INTEGER NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'ACTIVE',
      configured_by ${idType},configured_at TEXT,last_request_id TEXT,opened_at TEXT NOT NULL DEFAULT ${nowDefault},
      released_at TEXT,updated_at TEXT NOT NULL DEFAULT ${nowDefault})`,
    `CREATE INDEX IF NOT EXISTS idx_prison_release_case_status_v2031 ON ${CASE_TABLE}(status,updated_at)`,
    `CREATE TABLE IF NOT EXISTS ${CONTRIBUTION_TABLE}(
      request_id TEXT PRIMARY KEY,case_id TEXT NOT NULL,inmate_user_id ${idType} NOT NULL,contributor_user_id ${idType} NOT NULL,
      amount ${amountType} NOT NULL,status TEXT NOT NULL DEFAULT 'PENDING',created_at TEXT NOT NULL DEFAULT ${nowDefault},updated_at TEXT NOT NULL DEFAULT ${nowDefault})`,
    `CREATE INDEX IF NOT EXISTS idx_prison_release_contribution_case_v2031 ON ${CONTRIBUTION_TABLE}(case_id,status,created_at)`,
    `CREATE TABLE IF NOT EXISTS ${HIT_COOLDOWN_TABLE}(
      hitter_user_id ${idType} NOT NULL,inmate_user_id ${idType} NOT NULL,case_id TEXT NOT NULL,next_at_ms ${amountType} NOT NULL DEFAULT 0,
      last_request_id TEXT NOT NULL,hit_count INTEGER NOT NULL DEFAULT 0,updated_at TEXT NOT NULL DEFAULT ${nowDefault},PRIMARY KEY(hitter_user_id,inmate_user_id))`,
    `CREATE TABLE IF NOT EXISTS ${HIT_EVENT_TABLE}(
      id ${eventId},request_id TEXT NOT NULL UNIQUE,case_id TEXT NOT NULL,hitter_user_id ${idType} NOT NULL,
      inmate_user_id ${idType} NOT NULL,created_at TEXT NOT NULL DEFAULT ${nowDefault})`,
    `CREATE INDEX IF NOT EXISTS idx_prison_hit_event_case_v2031 ON ${HIT_EVENT_TABLE}(case_id,id DESC)`
  ];
}

export async function ensurePrisonCommunityFoundation(env){
  const db=env?.DB;if(!db)throw new Error('감옥 데이터베이스가 연결되지 않았습니다.');
  if(!foundationPromise){
    foundationPromise=(async()=>{
      const postgres=db?.dialect==='postgres',schema=schemaStatements(postgres);
      if(postgres&&typeof db.execSchema==='function')await db.execSchema(schema);
      else await db.batch(schema.map(sql=>db.prepare(sql)));
      return true;
    })().catch(error=>{foundationPromise=null;throw error});
  }
  return foundationPromise;
}

export function openPrisonReleaseCaseStatement(env,{inmateUserId,caseId=crypto.randomUUID(),onlyIfInactive=false}={}){
  const where=onlyIfInactive?` WHERE ${CASE_TABLE}.status<>'ACTIVE'`:'';
  return env.DB.prepare(`INSERT INTO ${CASE_TABLE}(inmate_user_id,case_id,release_price,collected_coin,contribution_count,status,configured_by,configured_at,last_request_id,opened_at,released_at,updated_at)
    VALUES(?,?,0,0,0,'ACTIVE',NULL,NULL,NULL,CURRENT_TIMESTAMP,NULL,CURRENT_TIMESTAMP)
    ON CONFLICT(inmate_user_id) DO UPDATE SET case_id=excluded.case_id,release_price=0,collected_coin=0,contribution_count=0,status='ACTIVE',
      configured_by=NULL,configured_at=NULL,last_request_id=NULL,opened_at=CURRENT_TIMESTAMP,released_at=NULL,updated_at=CURRENT_TIMESTAMP${where}`)
    .bind(integer(inmateUserId),cleanText(caseId,100));
}

export function closePrisonReleaseCaseStatement(env,{inmateUserId,status='ADMIN_RELEASED'}={}){
  return env.DB.prepare(`UPDATE ${CASE_TABLE} SET status=?,released_at=COALESCE(released_at,CURRENT_TIMESTAMP),updated_at=CURRENT_TIMESTAMP
    WHERE inmate_user_id=? AND status='ACTIVE'`).bind(cleanText(status,40).toUpperCase(),integer(inmateUserId));
}

async function ensureActiveCases(env){
  const rows=await env.DB.prepare(`SELECT p.user_id FROM user_prison_status p LEFT JOIN ${CASE_TABLE} c ON c.inmate_user_id=p.user_id AND c.status='ACTIVE'
    WHERE p.active=1 AND p.jailed_until>CURRENT_TIMESTAMP AND c.inmate_user_id IS NULL LIMIT 50`).all();
  const missing=rows?.results||[];
  if(missing.length)await env.DB.batch(missing.map(row=>openPrisonReleaseCaseStatement(env,{inmateUserId:Number(row.user_id),onlyIfInactive:true})));
}

async function activeCase(env,inmateUserId){
  await ensureActiveCases(env);
  return env.DB.prepare(`SELECT c.*,u.nickname FROM ${CASE_TABLE} c JOIN user_prison_status p ON p.user_id=c.inmate_user_id
    JOIN users u ON u.id=c.inmate_user_id WHERE c.inmate_user_id=? AND c.status='ACTIVE' AND p.active=1 AND p.jailed_until>CURRENT_TIMESTAMP`)
    .bind(inmateUserId).first();
}

export async function prisonCommunityRoomState(env,user,inmates=[]){
  await ensurePrisonCommunityFoundation(env);
  await ensureActiveCases(env);
  const [caseRows,cooldownRows,hitRows,contributionRows,viewerRow]=await env.DB.batch([
    env.DB.prepare(`SELECT c.*,a.nickname AS configured_by_nickname,
      (SELECT COUNT(*) FROM ${HIT_EVENT_TABLE} h WHERE h.case_id=c.case_id) AS hit_count
      FROM ${CASE_TABLE} c JOIN user_prison_status p ON p.user_id=c.inmate_user_id
      LEFT JOIN users a ON a.id=c.configured_by WHERE c.status='ACTIVE' AND p.active=1 AND p.jailed_until>CURRENT_TIMESTAMP`),
    env.DB.prepare(`SELECT hitter_user_id,inmate_user_id,case_id,next_at_ms,hit_count FROM ${HIT_COOLDOWN_TABLE} WHERE hitter_user_id=?`).bind(user.id),
    env.DB.prepare(`SELECT h.id,h.case_id,h.hitter_user_id AS hitterUserId,h.inmate_user_id AS inmateUserId,
      a.nickname AS hitterNickname,i.nickname AS inmateNickname,h.created_at AS createdAt
      FROM ${HIT_EVENT_TABLE} h JOIN users a ON a.id=h.hitter_user_id JOIN users i ON i.id=h.inmate_user_id
      JOIN ${CASE_TABLE} c ON c.case_id=h.case_id AND c.status='ACTIVE'
      ORDER BY h.id DESC LIMIT 24`),
    env.DB.prepare(`SELECT r.request_id,r.inmate_user_id AS inmateUserId,r.contributor_user_id AS contributorUserId,r.amount,
      a.nickname AS contributorNickname,i.nickname AS inmateNickname,r.created_at AS createdAt
      FROM ${CONTRIBUTION_TABLE} r JOIN users a ON a.id=r.contributor_user_id JOIN users i ON i.id=r.inmate_user_id
      JOIN ${CASE_TABLE} c ON c.case_id=r.case_id AND c.status='ACTIVE'
      WHERE r.status='COMPLETED' ORDER BY r.created_at DESC LIMIT 24`),
    env.DB.prepare('SELECT id,nickname,role,coin FROM users WHERE id=?').bind(user.id)
  ]);
  const cases=new Map((caseRows?.results||[]).map(row=>[Number(row.inmate_user_id),row]));
  const cooldowns=new Map((cooldownRows?.results||[]).map(row=>[Number(row.inmate_user_id),row]));
  const now=Date.now();
  const enriched=(Array.isArray(inmates)?inmates:[]).map(inmate=>{
    const inmateId=Number(inmate.userId||inmate.user_id||0),releaseCase=cases.get(inmateId),cooldown=cooldowns.get(inmateId);
    const progress=prisonReleaseProgress(releaseCase?.collected_coin,releaseCase?.release_price);
    const sameCase=releaseCase&&cooldown&&String(releaseCase.case_id)===String(cooldown.case_id),nextHitAtMs=sameCase?Math.max(0,Number(cooldown.next_at_ms||0)):0;
    return {...inmate,caseId:String(releaseCase?.case_id||''),...progress,contributionCount:Number(releaseCase?.contribution_count||0),releasePriceConfigured:progress.releasePrice>0,
      configuredByNickname:releaseCase?.configured_by_nickname||null,hitCount:Number(releaseCase?.hit_count||0),nextHitAtMs,hitCooldownRemainingSeconds:prisonHitCooldownRemaining(nextHitAtMs,now)};
  });
  const viewer=viewerRow?.results?.[0]||viewerRow||user;
  return {
    inmates:enriched,
    recentHits:(hitRows?.results||[]).map(row=>({...row,id:Number(row.id),hitterUserId:Number(row.hitterUserId),inmateUserId:Number(row.inmateUserId)})),
    recentContributions:(contributionRows?.results||[]).map(row=>({...row,inmateUserId:Number(row.inmateUserId),contributorUserId:Number(row.contributorUserId),amount:Number(row.amount||0)})),
    prisonCommunity:{version:2031,hitCooldownSeconds:PRISON_HIT_COOLDOWN_SECONDS,releasePriceMax:PRISON_RELEASE_PRICE_MAX,donationsRefundable:false},
    access:{canSetReleasePrice:String(viewer?.role||user?.role||'').trim().toUpperCase()==='OWNER'},
    viewer:{id:Number(viewer?.id||user.id),nickname:String(viewer?.nickname||user.nickname||''),role:String(viewer?.role||user.role||'USER'),coin:Number(viewer?.coin||0)}
  };
}

async function finalizeFundedRelease(env,inmateUserId,caseId){
  const commandPayload=JSON.stringify({reason:'영치금 모금 완료',message:'영치금 모금이 완료되어 석방되었습니다.'});
  const results=await env.DB.batch([
    env.DB.prepare(`UPDATE user_prison_status SET active=0,released_by=NULL,released_at=CURRENT_TIMESTAMP,release_reason='영치금 모금 완료',updated_at=CURRENT_TIMESTAMP
      WHERE user_id=? AND active=1 AND jailed_until>CURRENT_TIMESTAMP AND EXISTS(SELECT 1 FROM ${CASE_TABLE} WHERE inmate_user_id=? AND case_id=? AND status='ACTIVE' AND release_price>0 AND collected_coin>=release_price)`)
      .bind(inmateUserId,inmateUserId,caseId),
    env.DB.prepare(`INSERT INTO user_runtime_commands(user_id,command_type,payload_json,created_by,expires_at)
      SELECT ?,'PRISON_RELEASE',?,NULL,datetime('now','+30 minutes') WHERE EXISTS(
        SELECT 1 FROM user_prison_status p JOIN ${CASE_TABLE} c ON c.inmate_user_id=p.user_id
        WHERE p.user_id=? AND p.active=0 AND p.release_reason='영치금 모금 완료' AND c.case_id=? AND c.status='ACTIVE' AND c.collected_coin>=c.release_price)`)
      .bind(inmateUserId,commandPayload,inmateUserId,caseId),
    env.DB.prepare(`UPDATE ${CASE_TABLE} SET status='FUNDED_RELEASED',released_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP
      WHERE inmate_user_id=? AND case_id=? AND status='ACTIVE' AND release_price>0 AND collected_coin>=release_price
      AND EXISTS(SELECT 1 FROM user_prison_status WHERE user_id=? AND active=0 AND release_reason='영치금 모금 완료')`)
      .bind(inmateUserId,caseId,inmateUserId)
  ]);
  return changes(results?.[2])===1;
}

async function setReleasePrice(env,user,body,deps){
  if(String(user?.role||'').trim().toUpperCase()!=='OWNER')throw Object.assign(new Error('석방금은 OWNER만 설정할 수 있습니다.'),{status:403});
  const inmateUserId=integer(body.inmateUserId),releasePrice=integer(body.releasePrice);
  if(!Number.isSafeInteger(inmateUserId)||inmateUserId<1)throw Object.assign(new Error('수감자를 다시 선택해 주세요.'),{status:400});
  if(!Number.isSafeInteger(releasePrice)||releasePrice<0||releasePrice>PRISON_RELEASE_PRICE_MAX)throw Object.assign(new Error(`석방금은 0~${PRISON_RELEASE_PRICE_MAX.toLocaleString()}코인 사이의 정수로 설정하세요.`),{status:400});
  const releaseCase=await activeCase(env,inmateUserId);if(!releaseCase)throw Object.assign(new Error('현재 수감 중인 계정을 찾을 수 없습니다.'),{status:404});
  const updated=await env.DB.prepare(`UPDATE ${CASE_TABLE} SET release_price=?,configured_by=?,configured_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP
    WHERE inmate_user_id=? AND case_id=? AND status='ACTIVE'`).bind(releasePrice,user.id,inmateUserId,releaseCase.case_id).run();
  if(changes(updated)!==1)throw Object.assign(new Error('석방금 설정이 동시에 변경되었습니다. 다시 시도해 주세요.'),{status:409});
  let released=false;if(releasePrice>0&&Number(releaseCase.collected_coin||0)>=releasePrice)released=await finalizeFundedRelease(env,inmateUserId,String(releaseCase.case_id));
  if(released)await deps.clearPrisonChatIfEmpty(env);
  return {released,releasePrice,state:await deps.prisonRoomState(env,user)};
}

async function contributeReleaseFund(env,user,body,deps){
  const inmateUserId=integer(body.inmateUserId),amount=integer(body.amount),requestId=validRequestId(body.requestId||'');
  if(!Number.isSafeInteger(inmateUserId)||inmateUserId<1)throw Object.assign(new Error('수감자를 다시 선택해 주세요.'),{status:400});
  if(!Number.isSafeInteger(amount)||amount<1)throw Object.assign(new Error('영치금은 1코인 이상의 정수로 입력하세요.'),{status:400});
  if(!requestId)throw Object.assign(new Error('영치금 요청 번호가 올바르지 않습니다.'),{status:400});
  const prior=await env.DB.prepare(`SELECT * FROM ${CONTRIBUTION_TABLE} WHERE request_id=?`).bind(requestId).first();
  if(prior){
    if(Number(prior.contributor_user_id)!==Number(user.id)||Number(prior.inmate_user_id)!==inmateUserId||Number(prior.amount)!==amount)throw Object.assign(new Error('같은 요청 번호가 다른 영치금 납부에 사용되었습니다.'),{status:409});
    if(prior.status==='COMPLETED')return {replayed:true,released:false,amount,state:await deps.prisonRoomState(env,user)};
    throw Object.assign(new Error('동일한 영치금 요청을 처리 중입니다.'),{status:409});
  }
  const releaseCase=await activeCase(env,inmateUserId);if(!releaseCase)throw Object.assign(new Error('현재 수감 중인 계정을 찾을 수 없습니다.'),{status:404});
  const progress=prisonReleaseProgress(releaseCase.collected_coin,releaseCase.release_price);
  if(progress.releasePrice<1)throw Object.assign(new Error('OWNER가 아직 석방금을 설정하지 않았습니다.'),{status:409});
  if(progress.funded)throw Object.assign(new Error('이미 영치금 모금이 완료되었습니다.'),{status:409});
  if(amount>progress.remainingCoin)throw Object.assign(new Error(`남은 석방금 ${progress.remainingCoin.toLocaleString()}코인을 초과할 수 없습니다.`),{status:400});
  const donor=await env.DB.prepare('SELECT id,coin FROM users WHERE id=?').bind(user.id).first(),beforeCoin=Number(donor?.coin||0),afterCoin=beforeCoin-amount;
  if(beforeCoin<amount)throw Object.assign(new Error('보유 코인이 부족합니다.'),{status:409});
  await env.DB.batch([
    env.DB.prepare(`INSERT OR IGNORE INTO ${CONTRIBUTION_TABLE}(request_id,case_id,inmate_user_id,contributor_user_id,amount,status)
      VALUES(?,?,?,?,?,'PENDING')`).bind(requestId,releaseCase.case_id,inmateUserId,user.id,amount),
    env.DB.prepare(`UPDATE ${CASE_TABLE} SET collected_coin=collected_coin+?,contribution_count=contribution_count+1,last_request_id=?,updated_at=CURRENT_TIMESTAMP
      WHERE inmate_user_id=? AND case_id=? AND status='ACTIVE' AND release_price>0 AND collected_coin+?<=release_price
      AND EXISTS(SELECT 1 FROM ${CONTRIBUTION_TABLE} WHERE request_id=? AND contributor_user_id=? AND status='PENDING')
      AND EXISTS(SELECT 1 FROM users WHERE id=? AND coin=?)
      AND EXISTS(SELECT 1 FROM user_prison_status WHERE user_id=? AND active=1 AND jailed_until>CURRENT_TIMESTAMP)`)
      .bind(amount,requestId,inmateUserId,releaseCase.case_id,amount,requestId,user.id,user.id,beforeCoin,inmateUserId),
    env.DB.prepare(`UPDATE users SET coin=? WHERE id=? AND coin=? AND EXISTS(SELECT 1 FROM ${CASE_TABLE} WHERE inmate_user_id=? AND case_id=? AND last_request_id=?)
      AND EXISTS(SELECT 1 FROM ${CONTRIBUTION_TABLE} WHERE request_id=? AND status='PENDING')`)
      .bind(afterCoin,user.id,beforeCoin,inmateUserId,releaseCase.case_id,requestId,requestId),
    env.DB.prepare(`INSERT INTO coin_logs(user_id,change_amount,balance_after,reason)
      SELECT id,?,coin,'감옥 영치금 모금' FROM users WHERE id=? AND coin=?
      AND EXISTS(SELECT 1 FROM ${CASE_TABLE} WHERE inmate_user_id=? AND case_id=? AND last_request_id=?)
      AND EXISTS(SELECT 1 FROM ${CONTRIBUTION_TABLE} WHERE request_id=? AND status='PENDING')`)
      .bind(-amount,user.id,afterCoin,inmateUserId,releaseCase.case_id,requestId,requestId),
    env.DB.prepare(`UPDATE ${CONTRIBUTION_TABLE} SET status='COMPLETED',updated_at=CURRENT_TIMESTAMP WHERE request_id=? AND status='PENDING'
      AND EXISTS(SELECT 1 FROM users WHERE id=? AND coin=?)
      AND EXISTS(SELECT 1 FROM ${CASE_TABLE} WHERE inmate_user_id=? AND case_id=? AND last_request_id=?)`)
      .bind(requestId,user.id,afterCoin,inmateUserId,releaseCase.case_id,requestId)
  ]);
  const receipt=await env.DB.prepare(`SELECT status FROM ${CONTRIBUTION_TABLE} WHERE request_id=?`).bind(requestId).first();
  if(receipt?.status!=='COMPLETED'){
    await env.DB.prepare(`DELETE FROM ${CONTRIBUTION_TABLE} WHERE request_id=? AND status='PENDING'`).bind(requestId).run().catch(()=>{});
    throw Object.assign(new Error('잔액 또는 남은 석방금이 동시에 변경되었습니다. 다시 확인해 주세요.'),{status:409});
  }
  const savedCase=await env.DB.prepare(`SELECT case_id,release_price,collected_coin FROM ${CASE_TABLE} WHERE inmate_user_id=?`).bind(inmateUserId).first();
  let released=false;if(savedCase&&Number(savedCase.release_price)>0&&Number(savedCase.collected_coin)>=Number(savedCase.release_price))released=await finalizeFundedRelease(env,inmateUserId,String(savedCase.case_id));
  if(released)await deps.clearPrisonChatIfEmpty(env);
  return {replayed:false,released,amount,user:{id:user.id,nickname:user.nickname,role:user.role,coin:afterCoin},state:await deps.prisonRoomState(env,{...user,coin:afterCoin})};
}

async function hitInmate(env,user,body,deps){
  const inmateUserId=integer(body.inmateUserId),requestId=validRequestId(body.requestId||'');
  if(!Number.isSafeInteger(inmateUserId)||inmateUserId<1)throw Object.assign(new Error('때릴 수감자를 다시 선택해 주세요.'),{status:400});
  if(Number(user.id)===inmateUserId)throw Object.assign(new Error('자기 자신은 때릴 수 없습니다.'),{status:400});
  if(!requestId)throw Object.assign(new Error('때리기 요청 번호가 올바르지 않습니다.'),{status:400});
  const prior=await env.DB.prepare(`SELECT * FROM ${HIT_EVENT_TABLE} WHERE request_id=?`).bind(requestId).first();
  if(prior){
    if(Number(prior.hitter_user_id)!==Number(user.id)||Number(prior.inmate_user_id)!==inmateUserId)throw Object.assign(new Error('같은 요청 번호가 다른 때리기에 사용되었습니다.'),{status:409});
    return {replayed:true,eventId:Number(prior.id),state:await deps.prisonRoomState(env,user)};
  }
  const releaseCase=await activeCase(env,inmateUserId);if(!releaseCase)throw Object.assign(new Error('현재 수감 중인 계정을 찾을 수 없습니다.'),{status:404});
  const now=Date.now(),cooldown=await env.DB.prepare(`SELECT case_id,next_at_ms FROM ${HIT_COOLDOWN_TABLE} WHERE hitter_user_id=? AND inmate_user_id=?`).bind(user.id,inmateUserId).first();
  const remaining=String(cooldown?.case_id||'')===String(releaseCase.case_id)?prisonHitCooldownRemaining(cooldown?.next_at_ms,now):0;
  if(remaining>0)throw Object.assign(new Error(`${remaining}초 뒤에 다시 때릴 수 있습니다.`),{status:429,remainingSeconds:remaining});
  const nextAtMs=now+PRISON_HIT_COOLDOWN_SECONDS*1000;
  await env.DB.batch([
    env.DB.prepare(`INSERT INTO ${HIT_COOLDOWN_TABLE}(hitter_user_id,inmate_user_id,case_id,next_at_ms,last_request_id,hit_count,updated_at) VALUES(?,?,?,?,?,1,CURRENT_TIMESTAMP)
      ON CONFLICT(hitter_user_id,inmate_user_id) DO UPDATE SET case_id=excluded.case_id,next_at_ms=excluded.next_at_ms,
      last_request_id=excluded.last_request_id,hit_count=CASE WHEN ${HIT_COOLDOWN_TABLE}.case_id=excluded.case_id THEN ${HIT_COOLDOWN_TABLE}.hit_count+1 ELSE 1 END,updated_at=CURRENT_TIMESTAMP
      WHERE ${HIT_COOLDOWN_TABLE}.case_id<>excluded.case_id OR ${HIT_COOLDOWN_TABLE}.next_at_ms<=?`)
      .bind(user.id,inmateUserId,releaseCase.case_id,nextAtMs,requestId,now),
    env.DB.prepare(`INSERT INTO ${HIT_EVENT_TABLE}(request_id,case_id,hitter_user_id,inmate_user_id)
      SELECT ?,?,?,? WHERE EXISTS(SELECT 1 FROM ${HIT_COOLDOWN_TABLE}
        WHERE hitter_user_id=? AND inmate_user_id=? AND case_id=? AND last_request_id=?)`)
      .bind(requestId,releaseCase.case_id,user.id,inmateUserId,user.id,inmateUserId,releaseCase.case_id,requestId)
  ]);
  const event=await env.DB.prepare(`SELECT h.id,h.created_at AS createdAt,a.nickname AS hitterNickname,i.nickname AS inmateNickname
    FROM ${HIT_EVENT_TABLE} h JOIN users a ON a.id=h.hitter_user_id JOIN users i ON i.id=h.inmate_user_id WHERE h.request_id=?`).bind(requestId).first();
  if(!Number(event?.id||0)){
    const activeCooldown=await env.DB.prepare(`SELECT case_id,next_at_ms FROM ${HIT_COOLDOWN_TABLE} WHERE hitter_user_id=? AND inmate_user_id=?`).bind(user.id,inmateUserId).first();
    const activeRemaining=String(activeCooldown?.case_id||'')===String(releaseCase.case_id)?Math.max(1,prisonHitCooldownRemaining(activeCooldown?.next_at_ms,Date.now())):PRISON_HIT_COOLDOWN_SECONDS;
    throw Object.assign(new Error(`${activeRemaining}초 뒤에 다시 때릴 수 있습니다.`),{status:429,remainingSeconds:activeRemaining});
  }
  if(Number(event?.id||0)>0&&Number(event.id)%100===0)await env.DB.prepare(`DELETE FROM ${HIT_EVENT_TABLE} WHERE id NOT IN (SELECT id FROM ${HIT_EVENT_TABLE} ORDER BY id DESC LIMIT 2000)`).run().catch(()=>{});
  return {replayed:false,event:{...event,id:Number(event?.id||0),hitterUserId:Number(user.id),inmateUserId},nextHitAtMs:nextAtMs,state:await deps.prisonRoomState(env,user)};
}

export async function handlePrisonCommunity({path,request,env,deps}){
  if(!['prison/release-price','prison/fund','prison/hit'].includes(String(path)))return null;
  await ensurePrisonCommunityFoundation(env);
  const user=await deps.authenticate(request,env);if(!user)return deps.json({error:'로그인이 필요합니다.'},401);
  if(request.method!=='POST')return deps.json({error:'지원하지 않는 감옥 요청입니다.'},405);
  const body=await deps.readBody(request);
  try{
    if(path==='prison/release-price')return deps.json({ok:true,...await setReleasePrice(env,user,body,deps)});
    if(path==='prison/fund')return deps.json({ok:true,...await contributeReleaseFund(env,user,body,deps)});
    return deps.json({ok:true,...await hitInmate(env,user,body,deps)});
  }catch(error){
    const payload={error:error?.message||'감옥 요청 처리에 실패했습니다.'};if(Number(error?.remainingSeconds)>0)payload.remainingSeconds=Number(error.remainingSeconds);
    return deps.json(payload,Number(error?.status)||500);
  }
}

export const __prisonCommunityTest={CASE_TABLE,CONTRIBUTION_TABLE,HIT_COOLDOWN_TABLE,HIT_EVENT_TABLE,validRequestId,schemaStatements};
