const DEFAULTS={mode:'OFF',roundMinutes:60,energyMax:5,energyMinutes:15,normalCaptureWins:2,centerCaptureWins:3,winPoints:3,perfectBonus:1,territoryPoints:5,centerPoints:10,holdIntervalMinutes:5,holdPoints:1};
function safeJson(v,f){try{return JSON.parse(v||'')}catch{return f}}
function clamp(v,a,b){return Math.max(a,Math.min(b,Number(v)||0))}
function seedOf(text){let h=2166136261;for(const c of String(text)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
async function upgrade(env){
 const sql=[
 `CREATE TABLE IF NOT EXISTS territory_war_rounds(id INTEGER PRIMARY KEY AUTOINCREMENT,status TEXT NOT NULL DEFAULT 'RECRUITING',starts_at TEXT,ends_at TEXT,a_score INTEGER NOT NULL DEFAULT 0,b_score INTEGER NOT NULL DEFAULT 0,winner TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
 `CREATE TABLE IF NOT EXISTS territory_war_registrations(round_id INTEGER NOT NULL,user_id INTEGER NOT NULL,deck_power INTEGER NOT NULL DEFAULT 0,side TEXT,squad_no INTEGER,position INTEGER,deck_snapshot TEXT NOT NULL DEFAULT '[]',registered_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(round_id,user_id))`,
 `CREATE TABLE IF NOT EXISTS territory_war_territories(round_id INTEGER NOT NULL,code TEXT NOT NULL,name TEXT NOT NULL,kind TEXT NOT NULL DEFAULT 'NORMAL',owner TEXT NOT NULL DEFAULT 'NEUTRAL',capture_a INTEGER NOT NULL DEFAULT 0,capture_b INTEGER NOT NULL DEFAULT 0,garrison_squad_no INTEGER,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(round_id,code))`,
 `CREATE TABLE IF NOT EXISTS territory_war_energy(round_id INTEGER NOT NULL,user_id INTEGER NOT NULL,energy INTEGER NOT NULL DEFAULT 5,last_recharged_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(round_id,user_id))`,
 `CREATE TABLE IF NOT EXISTS territory_war_battles(id INTEGER PRIMARY KEY AUTOINCREMENT,request_id TEXT NOT NULL UNIQUE,round_id INTEGER NOT NULL,territory_code TEXT NOT NULL,attacker_side TEXT NOT NULL,attacker_squad_no INTEGER NOT NULL,defender_squad_no INTEGER,winner_side TEXT NOT NULL,a_wins INTEGER NOT NULL DEFAULT 0,b_wins INTEGER NOT NULL DEFAULT 0,points_awarded INTEGER NOT NULL DEFAULT 0,battle_summary TEXT NOT NULL DEFAULT '{}',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
 `CREATE INDEX IF NOT EXISTS idx_territory_war_reg_side ON territory_war_registrations(round_id,side,squad_no,position)`,
 `CREATE INDEX IF NOT EXISTS idx_territory_war_battles_round ON territory_war_battles(round_id,id DESC)`
 ]; await env.DB.batch(sql.map(x=>env.DB.prepare(x)));
 await env.DB.prepare("INSERT OR IGNORE INTO app_meta(key,value,updated_at) VALUES('territory_war_settings_v1',?,CURRENT_TIMESTAMP)").bind(JSON.stringify(DEFAULTS)).run();
}
async function settings(env){const r=await env.DB.prepare("SELECT value FROM app_meta WHERE key='territory_war_settings_v1'").first();return {...DEFAULTS,...safeJson(r?.value,{})}}
async function round(env){return env.DB.prepare("SELECT * FROM territory_war_rounds ORDER BY id DESC LIMIT 1").first()}
const MAP=[
 ['A0','A 본진','BASE_A','A'],['N1','서부 전초기지','NORMAL','A'],['N2','북부 협곡','NORMAL','NEUTRAL'],['N3','중앙 요새','CENTER','NEUTRAL'],['N4','남부 습지','NORMAL','NEUTRAL'],['N5','동부 전초기지','NORMAL','B'],['B0','B 본진','BASE_B','B']
];
const EDGES={A0:['N1'],N1:['A0','N2','N4'],N2:['N1','N3'],N3:['N2','N4','N5'],N4:['N1','N3','N5'],N5:['N3','N4','B0'],B0:['N5']};
async function createRound(env,cfg){const res=await env.DB.prepare("INSERT INTO territory_war_rounds(status,starts_at,ends_at) VALUES('RECRUITING',NULL,NULL)").run();const id=Number(res.meta.last_row_id);await env.DB.batch(MAP.map(x=>env.DB.prepare('INSERT INTO territory_war_territories(round_id,code,name,kind,owner) VALUES(?,?,?,?,?)').bind(id,...x)));return id}
async function currentOrCreate(env,cfg){let r=await round(env);if(!r)r=await env.DB.prepare('SELECT * FROM territory_war_rounds WHERE id=?').bind(await createRound(env,cfg)).first();return r}
function recharge(row,cfg){const last=Date.parse(String(row?.last_recharged_at||'').replace(' ','T')+'Z')||Date.now();const ticks=Math.floor((Date.now()-last)/(cfg.energyMinutes*60000));return {energy:Math.min(cfg.energyMax,Number(row?.energy??cfg.energyMax)+Math.max(0,ticks)),last:ticks>0?new Date(last+ticks*cfg.energyMinutes*60000).toISOString():row?.last_recharged_at}}
async function publicState(env,userId){const cfg=await settings(env);const r=await currentOrCreate(env,cfg);const [regs,territories,battles,mine]=await Promise.all([
 env.DB.prepare(`SELECT r.user_id,r.deck_power,r.side,r.squad_no,r.position,u.nickname FROM territory_war_registrations r JOIN users u ON u.id=r.user_id WHERE r.round_id=? ORDER BY r.side,r.squad_no,r.position`).bind(r.id).all(),
 env.DB.prepare('SELECT * FROM territory_war_territories WHERE round_id=? ORDER BY code').bind(r.id).all(),
 env.DB.prepare('SELECT * FROM territory_war_battles WHERE round_id=? ORDER BY id DESC LIMIT 20').bind(r.id).all(),
 env.DB.prepare('SELECT * FROM territory_war_registrations WHERE round_id=? AND user_id=?').bind(r.id,userId||0).first()
 ]);
 let energy=null;if(mine){const er=await env.DB.prepare('SELECT * FROM territory_war_energy WHERE round_id=? AND user_id=?').bind(r.id,userId).first();energy=recharge(er,cfg)}
 return {settings:cfg,round:r,registrations:regs.results||[],territories:territories.results||[],battles:(battles.results||[]).map(x=>({...x,battle:safeJson(x.battle_summary,{})})),mine,energy,edges:EDGES,serverNow:new Date().toISOString()};
}
async function formSides(env,r){const rows=(await env.DB.prepare(`SELECT * FROM territory_war_registrations WHERE round_id=? ORDER BY deck_power DESC,user_id`).bind(r.id).all()).results||[];let sumA=0,sumB=0,a=[],b=[];for(const row of rows){const target=sumA<=sumB?'A':'B';(target==='A'?a:b).push(row);if(target==='A')sumA+=Number(row.deck_power);else sumB+=Number(row.deck_power)}
 const stm=[];for(const [side,list] of [['A',a],['B',b]]){for(let i=0;i<list.length;i++){const squad=Math.floor(i/3)+1,pos=i%3+1;stm.push(env.DB.prepare('UPDATE territory_war_registrations SET side=?,squad_no=?,position=? WHERE round_id=? AND user_id=?').bind(side,squad,pos,r.id,list[i].user_id));stm.push(env.DB.prepare('INSERT OR REPLACE INTO territory_war_energy(round_id,user_id,energy,last_recharged_at) VALUES(?,?,?,CURRENT_TIMESTAMP)').bind(r.id,list[i].user_id,DEFAULTS.energyMax))}}
 if(stm.length)await env.DB.batch(stm);return {a:a.length,b:b.length,sumA,sumB}}
async function cardsFor(env,deps,userId){const [deck,set,eq,user]=await Promise.all([deps.pvpDeckSnapshot(env,userId),deps.battleSettings(env),deps.userEquipmentBonuses(env,userId),env.DB.prepare('SELECT id,role FROM users WHERE id=?').bind(userId).first()]);const powered=deck.map(c=>({...c,power:deps.cardBattlePower(c,c.breakthrough_level,set)}));let state=null;if(typeof deps.cardUniqueDeckStates==='function'){try{state=(await deps.cardUniqueDeckStates(env,[{user,cards:powered}],'PVP'))?.[0]||null}catch{}}const byId=new Map((state?.cards||[]).map(c=>[String(c.id),c.uniqueAbility||null]));return {cards:powered.map(c=>({...c,uniqueAbility:byId.get(String(c.id))||c.uniqueAbility||null})),equipment:Number(eq?.pvp||eq?.pvpBonus||0)}}
async function fightSquads(env,deps,roundId,aNo,bNo,requestId){const regs=(await env.DB.prepare(`SELECT user_id,side,squad_no,position FROM territory_war_registrations WHERE round_id=? AND ((side='A' AND squad_no=?) OR (side='B' AND squad_no=?)) ORDER BY side,position`).bind(roundId,aNo,bNo).all()).results||[];const A=regs.filter(x=>x.side==='A'),B=regs.filter(x=>x.side==='B');let aw=0,bw=0,duels=[];for(let i=0;i<3;i++){const ar=A[i],br=B[i];if(!ar&&!br)continue;if(ar&&!br){aw++;continue}if(br&&!ar){bw++;continue}const [ac,bc]=await Promise.all([cardsFor(env,deps,ar.user_id),cardsFor(env,deps,br.user_id)]);if(ac.cards.length!==5||bc.cards.length!==5){if(ac.cards.length===5)aw++;else if(bc.cards.length===5)bw++;continue}const battle=deps.createPvpBattleV2({attackerCards:ac.cards,defenderCards:bc.cards,attackerEquipmentBonus:ac.equipment,defenderEquipmentBonus:bc.equipment,seed:seedOf(`${requestId}:${i}`)});const winner=String(battle?.result?.winner||battle?.result?.winnerSide||'A');if(winner==='A')aw++;else bw++;duels.push({position:i+1,attackerUserId:ar.user_id,defenderUserId:br.user_id,winner,engine:battle.engine,result:battle.result,teams:battle.teams})}return {aw,bw,winner:aw>=bw?'A':'B',duels}}
export async function handleTerritoryWar({path,request,env,deps}){
 if(!path.startsWith('territory-war')&&!path.startsWith('admin/territory-war'))return null;await upgrade(env);const user=await deps.authenticate(request,env);if(!user)return deps.json({error:'로그인이 필요합니다.'},401);const admin=deps.isAdminRole(user);const cfg=await settings(env);const r=await currentOrCreate(env,cfg);
 if(path==='territory-war/state'&&request.method==='GET')return deps.json(await publicState(env,user.id));
 if(path==='territory-war/register'&&request.method==='POST'){if(r.status!=='RECRUITING')return deps.json({error:'현재 신청 기간이 아닙니다.'},409);const deck=await deps.pvpDeckSnapshot(env,user.id);if(deck.length!==5)return deps.json({error:'PVP 덱 5장을 먼저 편성하세요.'},400);const bs=await deps.battleSettings(env);const power=deck.reduce((s,c)=>s+deps.cardBattlePower(c,c.breakthrough_level,bs),0);await env.DB.prepare(`INSERT INTO territory_war_registrations(round_id,user_id,deck_power,deck_snapshot) VALUES(?,?,?,?) ON CONFLICT(round_id,user_id) DO UPDATE SET deck_power=excluded.deck_power,deck_snapshot=excluded.deck_snapshot,registered_at=CURRENT_TIMESTAMP`).bind(r.id,user.id,power,JSON.stringify(deck.map(x=>x.id))).run();return deps.json({ok:true,state:await publicState(env,user.id)});}
 if(path==='territory-war/attack'&&request.method==='POST'){if(r.status!=='ACTIVE')return deps.json({error:'영토전이 진행 중이 아닙니다.'},409);const body=await deps.readBody(request);const code=String(body.territoryCode||'').toUpperCase();const reqId=String(body.requestId||crypto.randomUUID()).slice(0,120);const old=await env.DB.prepare('SELECT battle_summary FROM territory_war_battles WHERE request_id=?').bind(reqId).first();if(old)return deps.json({ok:true,replayed:true,result:safeJson(old.battle_summary,{})});const mine=await env.DB.prepare('SELECT * FROM territory_war_registrations WHERE round_id=? AND user_id=?').bind(r.id,user.id).first();if(!mine?.side||!mine?.squad_no)return deps.json({error:'소대 편성이 완료되지 않았습니다.'},409);const target=await env.DB.prepare('SELECT * FROM territory_war_territories WHERE round_id=? AND code=?').bind(r.id,code).first();if(!target)return deps.json({error:'영토를 찾을 수 없습니다.'},404);if(target.kind.startsWith('BASE'))return deps.json({error:'본진은 직접 공격할 수 없습니다.'},400);const ownTerr=(await env.DB.prepare('SELECT code FROM territory_war_territories WHERE round_id=? AND owner=?').bind(r.id,mine.side).all()).results.map(x=>x.code);if(!ownTerr.some(x=>(EDGES[x]||[]).includes(code)))return deps.json({error:'아군 영토와 연결된 인접 지역만 공격할 수 있습니다.'},400);const er=await env.DB.prepare('SELECT * FROM territory_war_energy WHERE round_id=? AND user_id=?').bind(r.id,user.id).first();const rr=recharge(er,cfg);if(rr.energy<1)return deps.json({error:'소대 행동력이 부족합니다.'},409);await env.DB.prepare('INSERT OR REPLACE INTO territory_war_energy(round_id,user_id,energy,last_recharged_at) VALUES(?,?,?,?)').bind(r.id,user.id,rr.energy-1,rr.last||new Date().toISOString()).run();const enemy=mine.side==='A'?'B':'A';const enemySquads=(await env.DB.prepare('SELECT DISTINCT squad_no FROM territory_war_registrations WHERE round_id=? AND side=? AND squad_no IS NOT NULL ORDER BY squad_no').bind(r.id,enemy).all()).results||[];if(!enemySquads.length)return deps.json({error:'상대 진영 소대가 없습니다.'},409);const defNo=Number(target.garrison_squad_no||enemySquads[(seedOf(reqId)%enemySquads.length)].squad_no);const result=await fightSquads(env,deps,r.id,mine.side==='A'?mine.squad_no:defNo,mine.side==='B'?mine.squad_no:defNo,reqId);const winner=result.winner;const threshold=target.kind==='CENTER'?cfg.centerCaptureWins:cfg.normalCaptureWins;let ca=Number(target.capture_a),cb=Number(target.capture_b),owner=target.owner;if(winner==='A'){ca++;cb=Math.max(0,cb-1)}else{cb++;ca=Math.max(0,ca-1)}let captured=false;if(ca>=threshold){owner='A';ca=0;cb=0;captured=true}else if(cb>=threshold){owner='B';ca=0;cb=0;captured=true}const points=cfg.winPoints+(result.aw===3||result.bw===3?cfg.perfectBonus:0)+(captured?(target.kind==='CENTER'?cfg.centerPoints:cfg.territoryPoints):0);const payload={...result,territoryCode:code,captured,owner,points};await env.DB.batch([
 env.DB.prepare('UPDATE territory_war_territories SET owner=?,capture_a=?,capture_b=?,garrison_squad_no=?,updated_at=CURRENT_TIMESTAMP WHERE round_id=? AND code=?').bind(owner,ca,cb,mine.squad_no,r.id,code),
 env.DB.prepare(`UPDATE territory_war_rounds SET a_score=a_score+?,b_score=b_score+?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(winner==='A'?points:0,winner==='B'?points:0,r.id),
 env.DB.prepare(`INSERT INTO territory_war_battles(request_id,round_id,territory_code,attacker_side,attacker_squad_no,defender_squad_no,winner_side,a_wins,b_wins,points_awarded,battle_summary) VALUES(?,?,?,?,?,?,?,?,?,?,?)`).bind(reqId,r.id,code,mine.side,mine.squad_no,defNo,winner,result.aw,result.bw,points,JSON.stringify(payload))
 ]);return deps.json({ok:true,result:payload,state:await publicState(env,user.id)});}
 if(path==='admin/territory-war/settings'){if(!admin)return deps.json({error:'관리자 권한이 필요합니다.'},403);if(request.method==='POST'){const b=await deps.readBody(request);const next={...cfg,mode:['OFF','TEST','ON'].includes(String(b.mode||'').toUpperCase())?String(b.mode).toUpperCase():cfg.mode,roundMinutes:clamp(b.roundMinutes,10,10080),energyMax:clamp(b.energyMax,1,20),energyMinutes:clamp(b.energyMinutes,1,1440),normalCaptureWins:clamp(b.normalCaptureWins,1,10),centerCaptureWins:clamp(b.centerCaptureWins,1,20),winPoints:clamp(b.winPoints,0,100),perfectBonus:clamp(b.perfectBonus,0,100),territoryPoints:clamp(b.territoryPoints,0,1000),centerPoints:clamp(b.centerPoints,0,2000)};await env.DB.prepare("UPDATE app_meta SET value=?,updated_at=CURRENT_TIMESTAMP WHERE key='territory_war_settings_v1'").bind(JSON.stringify(next)).run();return deps.json({ok:true,settings:next})}return deps.json({settings:cfg,state:await publicState(env,user.id)});}
 if(path==='admin/territory-war/start'&&request.method==='POST'){if(!admin)return deps.json({error:'관리자 권한이 필요합니다.'},403);if(r.status!=='RECRUITING')return deps.json({error:'모집 중인 회차만 시작할 수 있습니다.'},409);const count=Number((await env.DB.prepare('SELECT COUNT(*) c FROM territory_war_registrations WHERE round_id=?').bind(r.id).first())?.c||0);if(count<6)return deps.json({error:'최소 6명의 신청자가 필요합니다.'},409);const formed=await formSides(env,r);const end=new Date(Date.now()+cfg.roundMinutes*60000).toISOString();await env.DB.prepare("UPDATE territory_war_rounds SET status='ACTIVE',starts_at=CURRENT_TIMESTAMP,ends_at=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(end,r.id).run();return deps.json({ok:true,formed,state:await publicState(env,user.id)});}
 if(path==='admin/territory-war/finish'&&request.method==='POST'){if(!admin)return deps.json({error:'관리자 권한이 필요합니다.'},403);const latest=await round(env);const winner=Number(latest.a_score)>Number(latest.b_score)?'A':Number(latest.b_score)>Number(latest.a_score)?'B':'DRAW';await env.DB.prepare("UPDATE territory_war_rounds SET status='FINISHED',winner=?,ends_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(winner,latest.id).run();await createRound(env,cfg);return deps.json({ok:true,winner});}
 return deps.json({error:'요청한 영토전 기능을 찾을 수 없습니다.'},404);
}
