const DEFAULTS={
 mode:'OFF',recruitmentHours:5,preparationMinutes:10,roundMinutes:120,
 energyMax:5,energyMinutes:20,normalCaptureWins:2,centerCaptureWins:3,
 battleWinPoints:1,territoryCapturePoints:3,centerCapturePoints:5,
 finalNormalPoints:5,finalCenterPoints:15,finalFrontierPoints:10,
 unguardedCaptureSeconds:30,leaderDelegateMinutes:30,
 normalGarrisonMax:2,centerGarrisonMax:3,recentBattleLimit:100,minParticipants:6,
 individualWinCoin:300,individualWinShards:5,individualWinDailyLimit:20,
 winnerCoin:5000,loserCoin:2000,drawCoin:3000,participationShards:50,contributionCoinPerPoint:100,settlementMinBattles:1
};
let upgradeReady=false;
function safeJson(v,f){try{return JSON.parse(v||'')}catch{return f}}
function clamp(v,a,b){return Math.max(a,Math.min(b,Number(v)||0))}
function seedOf(text){let h=2166136261;for(const c of String(text)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function sqlMs(v){if(!v)return NaN;return Date.parse(String(v).replace(' ','T')+(String(v).includes('Z')?'':'Z'))}
function iso(ms=Date.now()){return new Date(ms).toISOString()}
async function hasColumn(env,table,column){const rows=(await env.DB.prepare(`PRAGMA table_info(${table})`).all()).results||[];return rows.some(r=>r.name===column)}
async function addColumn(env,table,column,definition){if(!(await hasColumn(env,table,column)))await env.DB.prepare(`ALTER TABLE ${table} ADD COLUMN ${column} ${definition}`).run()}
async function upgrade(env){
 if(upgradeReady)return;
 const marker=await env.DB.prepare("SELECT value FROM app_meta WHERE key='safe_runtime_upgrade_v1376_territory_fast_state'").first();
 if(marker){upgradeReady=true;return}
 const sql=[
 `CREATE TABLE IF NOT EXISTS territory_war_rounds(id INTEGER PRIMARY KEY AUTOINCREMENT,status TEXT NOT NULL DEFAULT 'RECRUITING',starts_at TEXT,ends_at TEXT,a_score INTEGER NOT NULL DEFAULT 0,b_score INTEGER NOT NULL DEFAULT 0,winner TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
 `CREATE TABLE IF NOT EXISTS territory_war_registrations(round_id INTEGER NOT NULL,user_id INTEGER NOT NULL,deck_power INTEGER NOT NULL DEFAULT 0,side TEXT,squad_no INTEGER,position INTEGER,deck_snapshot TEXT NOT NULL DEFAULT '[]',registered_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(round_id,user_id))`,
 `CREATE TABLE IF NOT EXISTS territory_war_territories(round_id INTEGER NOT NULL,code TEXT NOT NULL,name TEXT NOT NULL,kind TEXT NOT NULL DEFAULT 'NORMAL',owner TEXT NOT NULL DEFAULT 'NEUTRAL',capture_a INTEGER NOT NULL DEFAULT 0,capture_b INTEGER NOT NULL DEFAULT 0,garrison_squad_no INTEGER,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(round_id,code))`,
 `CREATE TABLE IF NOT EXISTS territory_war_squads(round_id INTEGER NOT NULL,side TEXT NOT NULL,squad_no INTEGER NOT NULL,leader_user_id INTEGER,command_user_id INTEGER,current_territory TEXT,status TEXT NOT NULL DEFAULT 'STANDBY',energy INTEGER NOT NULL DEFAULT 5,last_recharged_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,last_action_at TEXT,wins INTEGER NOT NULL DEFAULT 0,losses INTEGER NOT NULL DEFAULT 0,contribution INTEGER NOT NULL DEFAULT 0,PRIMARY KEY(round_id,side,squad_no))`,
 `CREATE TABLE IF NOT EXISTS territory_war_orders(round_id INTEGER NOT NULL,side TEXT NOT NULL,squad_no INTEGER NOT NULL,action TEXT NOT NULL,target_code TEXT,state TEXT NOT NULL DEFAULT 'PENDING',completes_at TEXT,request_id TEXT,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(round_id,side,squad_no))`,
 `CREATE TABLE IF NOT EXISTS territory_war_battles(id INTEGER PRIMARY KEY AUTOINCREMENT,request_id TEXT NOT NULL UNIQUE,round_id INTEGER NOT NULL,territory_code TEXT NOT NULL,attacker_side TEXT NOT NULL,attacker_squad_no INTEGER NOT NULL,defender_squad_no INTEGER,winner_side TEXT NOT NULL,a_wins INTEGER NOT NULL DEFAULT 0,b_wins INTEGER NOT NULL DEFAULT 0,points_awarded INTEGER NOT NULL DEFAULT 0,battle_summary TEXT NOT NULL DEFAULT '{}',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
 `CREATE TABLE IF NOT EXISTS territory_war_rewards(round_id INTEGER NOT NULL,user_id INTEGER NOT NULL,side TEXT NOT NULL,result TEXT NOT NULL,coin INTEGER NOT NULL DEFAULT 0,shards INTEGER NOT NULL DEFAULT 0,contribution INTEGER NOT NULL DEFAULT 0,claimed_at TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(round_id,user_id))`,
 `CREATE TABLE IF NOT EXISTS territory_war_duel_reward_receipts(request_id TEXT NOT NULL,position INTEGER NOT NULL,round_id INTEGER NOT NULL,user_id INTEGER NOT NULL,coin INTEGER NOT NULL DEFAULT 0,shards INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(request_id,position,user_id))`,
 `CREATE INDEX IF NOT EXISTS idx_tw_reg_side ON territory_war_registrations(round_id,side,squad_no,position)`,
 `CREATE INDEX IF NOT EXISTS idx_tw_battles_round ON territory_war_battles(round_id,id DESC)`,
 `CREATE INDEX IF NOT EXISTS idx_tw_squad_location ON territory_war_squads(round_id,side,current_territory,status)`,
 `CREATE INDEX IF NOT EXISTS idx_tw_rewards_user ON territory_war_rewards(user_id,claimed_at)`,
 `CREATE INDEX IF NOT EXISTS idx_tw_duel_rewards_user_day ON territory_war_duel_reward_receipts(user_id,created_at)`
 ];
 await env.DB.batch(sql.map(x=>env.DB.prepare(x)));
 await addColumn(env,'territory_war_rounds','recruitment_ends_at','TEXT');
 await addColumn(env,'territory_war_rounds','formation_status',"TEXT NOT NULL DEFAULT 'WAITING'");
 await addColumn(env,'territory_war_rounds','formed_at','TEXT');
 await addColumn(env,'territory_war_rounds','settled_at','TEXT');
 await addColumn(env,'territory_war_rounds','final_territory_scored',"INTEGER NOT NULL DEFAULT 0");
 await addColumn(env,'territory_war_registrations','status',"TEXT NOT NULL DEFAULT 'WAITING'");
 await addColumn(env,'territory_war_registrations','wins','INTEGER NOT NULL DEFAULT 0');
 await addColumn(env,'territory_war_registrations','losses','INTEGER NOT NULL DEFAULT 0');
 await addColumn(env,'territory_war_registrations','contribution','INTEGER NOT NULL DEFAULT 0');
 await addColumn(env,'territory_war_territories','capture_side','TEXT');
 await addColumn(env,'territory_war_territories','capture_completes_at','TEXT');
 await env.DB.batch([env.DB.prepare("INSERT OR IGNORE INTO app_meta(key,value,updated_at) VALUES('territory_war_settings_v1',?,CURRENT_TIMESTAMP)").bind(JSON.stringify(DEFAULTS)),env.DB.prepare("INSERT OR REPLACE INTO app_meta(key,value,updated_at) VALUES('safe_runtime_upgrade_v1376_territory_fast_state','1',CURRENT_TIMESTAMP)")]);
 upgradeReady=true;
}
async function settings(env){const r=await env.DB.prepare("SELECT value FROM app_meta WHERE key='territory_war_settings_v1'").first();return {...DEFAULTS,...safeJson(r?.value,{})}}
async function round(env){return env.DB.prepare('SELECT * FROM territory_war_rounds ORDER BY id DESC LIMIT 1').first()}
const MAP=[['A0','A 본진','BASE_A','A'],['N1','서부 전초기지','NORMAL','A'],['N2','북부 협곡','NORMAL','NEUTRAL'],['N3','중앙 요새','CENTER','NEUTRAL'],['N4','남부 습지','NORMAL','NEUTRAL'],['N5','동부 전초기지','NORMAL','B'],['B0','B 본진','BASE_B','B']];
const EDGES={A0:['N1'],N1:['A0','N2','N4'],N2:['N1','N3'],N3:['N2','N4','N5'],N4:['N1','N3','N5'],N5:['N3','N4','B0'],B0:['N5']};
function baseCode(side){return side==='A'?'A0':'B0'}
async function createRound(env,cfg){const recruitEnd=iso(Date.now()+Number(cfg.recruitmentHours||5)*3600000);const res=await env.DB.prepare("INSERT INTO territory_war_rounds(status,recruitment_ends_at,formation_status) VALUES('RECRUITING',?,'WAITING')").bind(recruitEnd).run();const id=Number(res.meta.last_row_id);await env.DB.batch(MAP.map(x=>env.DB.prepare('INSERT INTO territory_war_territories(round_id,code,name,kind,owner) VALUES(?,?,?,?,?)').bind(id,...x)));await env.DB.batch([env.DB.prepare('DELETE FROM territory_war_orders WHERE round_id<?').bind(Math.max(0,id-1)),env.DB.prepare('DELETE FROM territory_war_battles WHERE round_id<?').bind(Math.max(0,id-1)),env.DB.prepare('DELETE FROM territory_war_squads WHERE round_id<?').bind(Math.max(0,id-1)),env.DB.prepare('DELETE FROM territory_war_territories WHERE round_id<?').bind(Math.max(0,id-1)),env.DB.prepare('DELETE FROM territory_war_registrations WHERE round_id<?').bind(Math.max(0,id-1)),env.DB.prepare('DELETE FROM territory_war_rewards WHERE claimed_at IS NOT NULL AND round_id<?').bind(Math.max(0,id-4)),env.DB.prepare("DELETE FROM territory_war_duel_reward_receipts WHERE created_at<datetime('now','-30 days')"),env.DB.prepare('DELETE FROM territory_war_rounds WHERE id<? AND id NOT IN (SELECT DISTINCT round_id FROM territory_war_rewards WHERE claimed_at IS NULL)').bind(Math.max(0,id-20))]);return id}
async function currentOrCreate(env,cfg){let r=await round(env);if(String(cfg.mode||'OFF').toUpperCase()==='OFF')return r||null;if(!r||['FINISHED','DISABLED'].includes(String(r.status||'')))r=await env.DB.prepare('SELECT * FROM territory_war_rounds WHERE id=?').bind(await createRound(env,cfg)).first();return r}
function recharge(row,cfg){const last=sqlMs(row?.last_recharged_at)||Date.now();const ticks=Math.max(0,Math.floor((Date.now()-last)/(cfg.energyMinutes*60000)));return {energy:Math.min(cfg.energyMax,Number(row?.energy??cfg.energyMax)+ticks),last:ticks>0?iso(last+ticks*cfg.energyMinutes*60000):(row?.last_recharged_at||iso())}}
function balancedGroups(list){const teamCount=Math.floor(list.length/3);if(!teamCount)return[];const selected=[...list].sort((a,b)=>Number(b.deck_power)-Number(a.deck_power)||Number(a.user_id)-Number(b.user_id));const groups=Array.from({length:teamCount},()=>[]);for(const row of selected.slice(0,teamCount*3)){const slot=groups.map((g,i)=>({i,n:g.length,p:g.reduce((s,x)=>s+Number(x.deck_power||0),0)})).filter(x=>x.n<3).sort((a,b)=>a.p-b.p||a.n-b.n)[0];groups[slot.i].push(row)}return groups.map(g=>g.sort((a,b)=>Number(b.deck_power)-Number(a.deck_power)).map((x,i)=>({...x,position:i+1})))}
async function acquireLock(env,keyName,ttl=300000){const token=crypto.randomUUID(),key=`territory_war_lock_${keyName}`;await env.DB.prepare('INSERT OR IGNORE INTO app_meta(key,value,updated_at) VALUES(?,?,CURRENT_TIMESTAMP)').bind(key,`RUNNING|${token}|${Date.now()}`).run();let row=await env.DB.prepare('SELECT value FROM app_meta WHERE key=?').bind(key).first();const parts=String(row?.value||'').split('|');if(parts[0]==='RUNNING'&&parts[1]===token)return{ok:true,key,token};if(parts[0]==='RUNNING'&&Date.now()-Number(parts[2]||0)>ttl){await env.DB.prepare('UPDATE app_meta SET value=?,updated_at=CURRENT_TIMESTAMP WHERE key=?').bind(`RUNNING|${token}|${Date.now()}`,key).run();row=await env.DB.prepare('SELECT value FROM app_meta WHERE key=?').bind(key).first();if(String(row?.value||'').includes(token))return{ok:true,key,token}}return{ok:false}}
async function releaseLock(env,lock){if(lock?.ok)await env.DB.prepare('DELETE FROM app_meta WHERE key=? AND value LIKE ?').bind(lock.key,`RUNNING|${lock.token}|%`).run()}
async function formSides(env,r,cfg){const lock=await acquireLock(env,`formation_${r.id}`);if(!lock.ok)return{status:'FORMING'};try{const rows=(await env.DB.prepare('SELECT * FROM territory_war_registrations WHERE round_id=? ORDER BY registered_at,user_id').bind(r.id).all()).results||[];if(rows.length<cfg.minParticipants){await env.DB.prepare("UPDATE territory_war_rounds SET formation_status='WAITING_MINIMUM',updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(r.id).run();return{status:'WAITING_MINIMUM',count:rows.length}}
 const ranked=[...rows].sort((a,b)=>Number(b.deck_power)-Number(a.deck_power)||Number(a.user_id)-Number(b.user_id));const A=[],B=[];let pa=0,pb=0;for(const row of ranked){const target=(A.length<B.length||(A.length===B.length&&pa<=pb))?A:B;target.push(row);if(target===A)pa+=Number(row.deck_power);else pb+=Number(row.deck_power)}
 const statements=[];let squads=0,reserves=0;for(const [side,list] of [['A',A],['B',B]]){const groups=balancedGroups(list);const used=new Set();groups.forEach((g,idx)=>{squads++;const no=idx+1,leader=g[0]?.user_id||null;statements.push(env.DB.prepare(`INSERT OR REPLACE INTO territory_war_squads(round_id,side,squad_no,leader_user_id,command_user_id,current_territory,status,energy,last_recharged_at,last_action_at) VALUES(?,?,?,?,?,?,'STANDBY',?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)`).bind(r.id,side,no,leader,leader,baseCode(side),cfg.energyMax));g.forEach(m=>{used.add(m.user_id);statements.push(env.DB.prepare("UPDATE territory_war_registrations SET side=?,squad_no=?,position=?,status='ASSIGNED' WHERE round_id=? AND user_id=?").bind(side,no,m.position,r.id,m.user_id))})});for(const m of list.filter(x=>!used.has(x.user_id))){reserves++;statements.push(env.DB.prepare("UPDATE territory_war_registrations SET side=?,squad_no=NULL,position=NULL,status='RESERVE' WHERE round_id=? AND user_id=?").bind(side,r.id,m.user_id))}}
 if(statements.length)await env.DB.batch(statements);await env.DB.prepare("UPDATE territory_war_rounds SET formation_status='COMPLETED',formed_at=CURRENT_TIMESTAMP,status='PREPARING',starts_at=?,ends_at=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(iso(Date.now()+cfg.preparationMinutes*60000),iso(Date.now()+(cfg.preparationMinutes+cfg.roundMinutes)*60000),r.id).run();return{status:'COMPLETED',a:A.length,b:B.length,aPower:pa,bPower:pb,squads,reserves};
 }finally{await releaseLock(env,lock)}}
async function connectedOwned(env,rid,side){const rows=(await env.DB.prepare('SELECT code,owner FROM territory_war_territories WHERE round_id=?').bind(rid).all()).results||[];const owned=new Set(rows.filter(x=>x.owner===side).map(x=>x.code)),seen=new Set(),q=[baseCode(side)];while(q.length){const x=q.shift();if(seen.has(x)||!owned.has(x))continue;seen.add(x);for(const n of EDGES[x]||[])if(owned.has(n))q.push(n)}return seen}
async function resolvePendingCaptures(env,r,cfg){if(!r||!['PREPARING','ACTIVE'].includes(r.status))return;const due=(await env.DB.prepare("SELECT * FROM territory_war_orders WHERE round_id=? AND action='CAPTURE' AND state='PENDING' AND completes_at<=CURRENT_TIMESTAMP").bind(r.id).all()).results||[];for(const o of due){const lock=await acquireLock(env,`capture_${r.id}_${o.target_code}`,60000);if(!lock.ok)continue;try{const terr=await env.DB.prepare('SELECT * FROM territory_war_territories WHERE round_id=? AND code=?').bind(r.id,o.target_code).first();const defenders=(await env.DB.prepare("SELECT COUNT(*) c FROM territory_war_squads WHERE round_id=? AND current_territory=? AND side<>? AND status NOT IN ('REORGANIZING')").bind(r.id,o.target_code,o.side).first())?.c||0;if(Number(defenders)>0){await env.DB.prepare("UPDATE territory_war_orders SET state='BLOCKED',updated_at=CURRENT_TIMESTAMP WHERE round_id=? AND side=? AND squad_no=?").bind(r.id,o.side,o.squad_no).run();continue}let ca=Number(terr.capture_a||0),cb=Number(terr.capture_b||0);if(o.side==='A'){ca++;cb=Math.max(0,cb-1)}else{cb++;ca=Math.max(0,ca-1)}const threshold=terr.owner==='NEUTRAL'?1:(terr.kind==='CENTER'?cfg.centerCaptureWins:cfg.normalCaptureWins);let owner=terr.owner,captured=false;if(ca>=threshold){owner='A';ca=0;cb=0;captured=true}else if(cb>=threshold){owner='B';ca=0;cb=0;captured=true}const points=captured?(terr.kind==='CENTER'?cfg.centerCapturePoints:cfg.territoryCapturePoints):0;await env.DB.batch([
 env.DB.prepare('UPDATE territory_war_territories SET owner=?,capture_a=?,capture_b=?,capture_side=NULL,capture_completes_at=NULL,updated_at=CURRENT_TIMESTAMP WHERE round_id=? AND code=?').bind(owner,ca,cb,r.id,o.target_code),
 env.DB.prepare("UPDATE territory_war_squads SET current_territory=?,status='GARRISON',last_action_at=CURRENT_TIMESTAMP WHERE round_id=? AND side=? AND squad_no=?").bind(o.target_code,r.id,o.side,o.squad_no),
 env.DB.prepare("UPDATE territory_war_orders SET state='COMPLETED',updated_at=CURRENT_TIMESTAMP WHERE round_id=? AND side=? AND squad_no=?").bind(r.id,o.side,o.squad_no),
 env.DB.prepare('UPDATE territory_war_rounds SET a_score=a_score+?,b_score=b_score+?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(o.side==='A'?points:0,o.side==='B'?points:0,r.id)
 ]);
 }finally{await releaseLock(env,lock)}}}
async function finalTerritoryScore(env,r,cfg){if(Number(r.final_territory_scored||0))return r;const rows=(await env.DB.prepare("SELECT code,kind,owner FROM territory_war_territories WHERE round_id=? AND owner IN ('A','B') AND kind NOT LIKE 'BASE%'").bind(r.id).all()).results||[];let a=0,b=0;for(const t of rows){let p=t.kind==='CENTER'?cfg.finalCenterPoints:cfg.finalNormalPoints;if((t.code==='N5'&&t.owner==='A')||(t.code==='N1'&&t.owner==='B'))p=cfg.finalFrontierPoints;if(t.owner==='A')a+=Number(p);else b+=Number(p)}await env.DB.prepare('UPDATE territory_war_rounds SET a_score=a_score+?,b_score=b_score+?,final_territory_scored=1,updated_at=CURRENT_TIMESTAMP WHERE id=? AND final_territory_scored=0').bind(a,b,r.id).run();return env.DB.prepare('SELECT * FROM territory_war_rounds WHERE id=?').bind(r.id).first()}
async function settleRound(env,r,cfg){if(!r||r.settled_at)return r;r=await finalTerritoryScore(env,r,cfg);const winner=Number(r.a_score)>Number(r.b_score)?'A':Number(r.b_score)>Number(r.a_score)?'B':'DRAW';const regs=(await env.DB.prepare('SELECT * FROM territory_war_registrations WHERE round_id=?').bind(r.id).all()).results||[];const stm=[];for(const m of regs){const battles=Number(m.wins||0)+Number(m.losses||0),eligible=battles>=Number(cfg.settlementMinBattles||1);const result=!eligible?'INELIGIBLE':winner==='DRAW'?'DRAW':m.side===winner?'WIN':'LOSE';const base=!eligible?0:result==='WIN'?cfg.winnerCoin:result==='LOSE'?cfg.loserCoin:cfg.drawCoin;const coin=Number(base||0)+(eligible?Number(m.contribution||0)*Number(cfg.contributionCoinPerPoint||0):0);stm.push(env.DB.prepare('INSERT OR IGNORE INTO territory_war_rewards(round_id,user_id,side,result,coin,shards,contribution) VALUES(?,?,?,?,?,?,?)').bind(r.id,m.user_id,m.side||'RESERVE',result,coin,eligible?cfg.participationShards:0,Number(m.contribution||0)))}if(stm.length)await env.DB.batch(stm);await env.DB.prepare("UPDATE territory_war_rounds SET status='FINISHED',winner=?,ends_at=COALESCE(ends_at,CURRENT_TIMESTAMP),settled_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(winner,r.id).run();return env.DB.prepare('SELECT * FROM territory_war_rounds WHERE id=?').bind(r.id).first()}
async function maybeAdvance(env,r,cfg,force=false){if(!r||String(cfg.mode||'OFF').toUpperCase()==='OFF')return r;if(r.status==='RECRUITING'&&(force||Date.now()>=sqlMs(r.recruitment_ends_at))){await formSides(env,r,cfg);r=await env.DB.prepare('SELECT * FROM territory_war_rounds WHERE id=?').bind(r.id).first()}if(r.status==='PREPARING'&&Date.now()>=sqlMs(r.starts_at)){await env.DB.prepare("UPDATE territory_war_rounds SET status='ACTIVE',updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(r.id).run();r=await env.DB.prepare('SELECT * FROM territory_war_rounds WHERE id=?').bind(r.id).first()}if(r.status==='ACTIVE'&&Date.now()>=sqlMs(r.ends_at))r=await settleRound(env,r,cfg);return r}
async function commandContext(env,r,userId,cfg){const mine=await env.DB.prepare('SELECT * FROM territory_war_registrations WHERE round_id=? AND user_id=?').bind(r.id,userId).first();if(!mine?.side||!mine?.squad_no)return{mine,squad:null,canCommand:false};const squad=await env.DB.prepare('SELECT * FROM territory_war_squads WHERE round_id=? AND side=? AND squad_no=?').bind(r.id,mine.side,mine.squad_no).first();let canCommand=Number(squad?.command_user_id||squad?.leader_user_id)===Number(userId);if(!canCommand&&Number(mine.position)>1){const idle=Date.now()-(sqlMs(squad?.last_action_at)||0);if(idle>=cfg.leaderDelegateMinutes*60000){const prior=await env.DB.prepare('SELECT user_id FROM territory_war_registrations WHERE round_id=? AND side=? AND squad_no=? AND position=? LIMIT 1').bind(r.id,mine.side,mine.squad_no,Number(mine.position)-1).first();if(prior){const priorId=Number(prior.user_id);const leaderIsPrior=priorId===Number(squad.command_user_id||squad.leader_user_id);if(leaderIsPrior){await env.DB.prepare('UPDATE territory_war_squads SET command_user_id=?,last_action_at=CURRENT_TIMESTAMP WHERE round_id=? AND side=? AND squad_no=?').bind(userId,r.id,mine.side,mine.squad_no).run();squad.command_user_id=userId;canCommand=true}}}}return{mine,squad,canCommand}}
async function publicState(env,userId){const cfg=await settings(env);let r=await currentOrCreate(env,cfg);if(String(cfg.mode||'OFF').toUpperCase()==='OFF'||!r)return{settings:cfg,round:r||{id:null,status:'DISABLED',a_score:0,b_score:0},registrations:[],territories:[],battles:[],mine:null,reward:null,squads:[],orders:[],squad:null,energy:null,canCommand:false,edges:EDGES,serverNow:iso(),disabled:true};r=await maybeAdvance(env,r,cfg,false);await resolvePendingCaptures(env,r,cfg);r=await env.DB.prepare('SELECT * FROM territory_war_rounds WHERE id=?').bind(r.id).first();const [regs,territories,battles,mine,reward,squads,orders]=await Promise.all([
 env.DB.prepare(`SELECT r.user_id,r.deck_power,r.side,r.squad_no,r.position,r.status,r.wins,r.losses,r.contribution,u.nickname FROM territory_war_registrations r JOIN users u ON u.id=r.user_id WHERE r.round_id=? ORDER BY r.side,r.squad_no,r.position,r.registered_at`).bind(r.id).all(),
 env.DB.prepare('SELECT * FROM territory_war_territories WHERE round_id=? ORDER BY code').bind(r.id).all(),
 env.DB.prepare('SELECT id,request_id,round_id,territory_code,attacker_side,attacker_squad_no,defender_squad_no,winner_side,a_wins,b_wins,points_awarded,created_at FROM territory_war_battles WHERE round_id=? ORDER BY id DESC LIMIT ?').bind(r.id,Math.min(Number(cfg.recentBattleLimit||100),20)).all(),
 env.DB.prepare('SELECT * FROM territory_war_registrations WHERE round_id=? AND user_id=?').bind(r.id,userId||0).first(),
 env.DB.prepare('SELECT * FROM territory_war_rewards WHERE user_id=? AND claimed_at IS NULL ORDER BY round_id DESC LIMIT 1').bind(userId||0).first(),
 env.DB.prepare('SELECT * FROM territory_war_squads WHERE round_id=? ORDER BY side,squad_no').bind(r.id).all(),
 env.DB.prepare("SELECT * FROM territory_war_orders WHERE round_id=? AND state IN ('PENDING','BLOCKED') ORDER BY updated_at").bind(r.id).all()
 ]);
 let squad=null,energy=null,canCommand=false;if(mine?.squad_no){squad=(squads.results||[]).find(x=>x.side===mine.side&&Number(x.squad_no)===Number(mine.squad_no));energy=recharge(squad,cfg);canCommand=Number(squad?.command_user_id||squad?.leader_user_id)===Number(userId)}return{settings:cfg,round:r,registrations:regs.results||[],territories:territories.results||[],battles:battles.results||[],mine,reward,squads:squads.results||[],orders:orders.results||[],squad,energy,canCommand,edges:EDGES,serverNow:iso()}}
async function cardsFor(env,deps,userId){const [deck,set,eq,user]=await Promise.all([deps.pvpDeckSnapshot(env,userId),deps.battleSettings(env),deps.userEquipmentBonuses(env,userId),env.DB.prepare('SELECT id,role FROM users WHERE id=?').bind(userId).first()]);const powered=deck.map(c=>({...c,power:deps.cardBattlePower(c,c.breakthrough_level,set)}));let state=null;if(typeof deps.cardUniqueDeckStates==='function'){try{state=(await deps.cardUniqueDeckStates(env,[{user,cards:powered}],'PVP'))?.[0]||null}catch{}}const byId=new Map((state?.cards||[]).map(c=>[String(c.id),c.uniqueAbility||null]));return{cards:powered.map(c=>({...c,uniqueAbility:byId.get(String(c.id))||c.uniqueAbility||null})),equipment:Number(eq?.pvp||eq?.pvpBonus||0)}}
async function fightSquads(env,deps,roundId,aNo,bNo,requestId){const regs=(await env.DB.prepare(`SELECT user_id,side,squad_no,position FROM territory_war_registrations WHERE round_id=? AND ((side='A' AND squad_no=?) OR (side='B' AND squad_no=?)) ORDER BY side,position`).bind(roundId,aNo,bNo).all()).results||[];const A=regs.filter(x=>x.side==='A'),B=regs.filter(x=>x.side==='B');let aw=0,bw=0,duels=[];for(let i=0;i<3;i++){const ar=A[i],br=B[i];if(!ar&&!br)continue;if(ar&&!br){aw++;continue}if(br&&!ar){bw++;continue}const[ac,bc]=await Promise.all([cardsFor(env,deps,ar.user_id),cardsFor(env,deps,br.user_id)]);if(ac.cards.length!==5||bc.cards.length!==5){if(ac.cards.length===5)aw++;else if(bc.cards.length===5)bw++;continue}const battle=deps.createPvpBattleV2({attackerCards:ac.cards,defenderCards:bc.cards,attackerEquipmentBonus:ac.equipment,defenderEquipmentBonus:bc.equipment,seed:seedOf(`${requestId}:${i}`)});const winner=String(battle?.result?.winner||battle?.result?.winnerSide||'A');if(winner==='A')aw++;else bw++;duels.push({position:i+1,attackerUserId:ar.user_id,defenderUserId:br.user_id,winner,engine:battle.engine,result:battle.result,teams:battle.teams})}return{aw,bw,winner:aw>=bw?'A':'B',duels}}
async function grantDuelWinRewards(env,result,requestId,roundId,cfg){
 const rewards=[];const coinEach=Number(cfg.individualWinCoin||0),shardsEach=Number(cfg.individualWinShards||0),dailyLimit=Math.max(0,Number(cfg.individualWinDailyLimit||0));
 for(const duel of result.duels||[]){const pos=Number(duel.position||0);const winnerUserId=String(duel.winner||'A')==='A'?Number(duel.attackerUserId):Number(duel.defenderUserId);if(!winnerUserId||(!coinEach&&!shardsEach))continue;
  const today=Number((await env.DB.prepare("SELECT COUNT(*) c FROM territory_war_duel_reward_receipts WHERE user_id=? AND created_at>=datetime('now','start of day')").bind(winnerUserId).first())?.c||0);if(dailyLimit>0&&today>=dailyLimit){rewards.push({position:pos,userId:winnerUserId,coin:0,shards:0,limited:true});continue}
  const rec=await env.DB.prepare('INSERT OR IGNORE INTO territory_war_duel_reward_receipts(request_id,position,round_id,user_id,coin,shards) VALUES(?,?,?,?,?,?)').bind(requestId,pos,roundId,winnerUserId,coinEach,shardsEach).run();if(!Number(rec?.meta?.changes||0)){rewards.push({position:pos,userId:winnerUserId,coin:0,shards:0,replayed:true});continue}
  const u=await env.DB.prepare('SELECT coins,card_shards FROM users WHERE id=?').bind(winnerUserId).first();const coins=Number(u?.coins||0)+coinEach,shards=Number(u?.card_shards||0)+shardsEach;const stm=[env.DB.prepare('UPDATE users SET coins=?,card_shards=? WHERE id=?').bind(coins,shards,winnerUserId)];if(coinEach)stm.push(env.DB.prepare("INSERT INTO coin_logs(user_id,change_amount,balance_after,reason) VALUES(?,?,?,'영토전 개별 전투 승리')").bind(winnerUserId,coinEach,coins));if(shardsEach)stm.push(env.DB.prepare("INSERT INTO shard_logs(user_id,change_amount,balance_after,reason,card_id) VALUES(?,?,?,'영토전 개별 전투 승리',NULL)").bind(winnerUserId,shardsEach,shards));await env.DB.batch(stm);rewards.push({position:pos,userId:winnerUserId,coin:coinEach,shards:shardsEach,limited:false})
 }return rewards
}
async function pruneBattles(env,rid,limit){await env.DB.prepare('DELETE FROM territory_war_battles WHERE round_id=? AND id NOT IN (SELECT id FROM territory_war_battles WHERE round_id=? ORDER BY id DESC LIMIT ?)').bind(rid,rid,limit).run()}
export async function handleTerritoryWar({path,request,env,deps}){
 if(!path.startsWith('territory-war')&&!path.startsWith('admin/territory-war'))return null;await upgrade(env);const user=await deps.authenticate(request,env);if(!user)return deps.json({error:'로그인이 필요합니다.'},401);const admin=deps.isAdminRole(user);
 if(path==='territory-war/state'&&request.method==='GET')return deps.json(await publicState(env,user.id));
 const cfg=await settings(env);let r=await currentOrCreate(env,cfg);if(r)r=await maybeAdvance(env,r,cfg,false);
 if(path==='territory-war/register'&&request.method==='POST'){if(String(cfg.mode||'OFF').toUpperCase()==='OFF')return deps.json({error:'영토전 운영이 중지되었습니다.'},409);if(!r||r.status!=='RECRUITING')return deps.json({error:'현재 신청 기간이 아닙니다.'},409);const deck=await deps.pvpDeckSnapshot(env,user.id);if(deck.length!==5)return deps.json({error:'PVP 덱 5장을 먼저 편성하세요.'},400);const bs=await deps.battleSettings(env);const power=deck.reduce((s,c)=>s+deps.cardBattlePower(c,c.breakthrough_level,bs),0);await env.DB.prepare(`INSERT INTO territory_war_registrations(round_id,user_id,deck_power,deck_snapshot,status) VALUES(?,?,?,?, 'WAITING') ON CONFLICT(round_id,user_id) DO UPDATE SET deck_power=excluded.deck_power,deck_snapshot=excluded.deck_snapshot,status='WAITING',registered_at=CURRENT_TIMESTAMP`).bind(r.id,user.id,power,JSON.stringify(deck.map(x=>x.id))).run();return deps.json({ok:true,state:await publicState(env,user.id)})}
 if(path==='territory-war/unregister'&&request.method==='POST'){if(String(cfg.mode||'OFF').toUpperCase()==='OFF')return deps.json({error:'영토전 운영이 중지되었습니다.'},409);if(!r||r.status!=='RECRUITING')return deps.json({error:'모집 중에만 신청을 취소할 수 있습니다.'},409);await env.DB.prepare('DELETE FROM territory_war_registrations WHERE round_id=? AND user_id=?').bind(r.id,user.id).run();return deps.json({ok:true,state:await publicState(env,user.id)})}
 if(path==='territory-war/claim'&&request.method==='POST'){const reward=await env.DB.prepare('SELECT * FROM territory_war_rewards WHERE user_id=? AND claimed_at IS NULL ORDER BY round_id DESC LIMIT 1').bind(user.id).first();if(!reward)return deps.json({error:'수령 가능한 보상이 없습니다.'},404);const u=await env.DB.prepare('SELECT coins,card_shards FROM users WHERE id=?').bind(user.id).first();const coin=Number(u?.coins||0)+Number(reward.coin||0),shards=Number(u?.card_shards||0)+Number(reward.shards||0);await env.DB.batch([env.DB.prepare('UPDATE users SET coins=?,card_shards=? WHERE id=?').bind(coin,shards,user.id),env.DB.prepare('UPDATE territory_war_rewards SET claimed_at=CURRENT_TIMESTAMP WHERE round_id=? AND user_id=? AND claimed_at IS NULL').bind(reward.round_id,user.id),env.DB.prepare("INSERT INTO coin_logs(user_id,change_amount,balance_after,reason) VALUES(?,?,?,'영토전 보상')").bind(user.id,reward.coin,coin),env.DB.prepare("INSERT INTO shard_logs(user_id,change_amount,balance_after,reason,card_id) VALUES(?,?,?,'영토전 보상',NULL)").bind(user.id,reward.shards,shards)]);return deps.json({ok:true,coin:reward.coin,shards:reward.shards,state:await publicState(env,user.id)})}
 if(path==='territory-war/move'&&request.method==='POST'){if(String(cfg.mode||'OFF').toUpperCase()==='OFF')return deps.json({error:'영토전 운영이 중지되었습니다.'},409);if(!r||r.status!=='ACTIVE')return deps.json({error:'영토전 진행 중에만 이동할 수 있습니다.'},409);const b=await deps.readBody(request),code=String(b.territoryCode||'').toUpperCase();const ctx=await commandContext(env,r,user.id,cfg);if(!ctx.canCommand)return deps.json({error:'현재 소대 지휘권이 없습니다.'},403);const target=await env.DB.prepare('SELECT * FROM territory_war_territories WHERE round_id=? AND code=?').bind(r.id,code).first();if(!target||target.owner!==ctx.mine.side)return deps.json({error:'아군 영토로만 이동할 수 있습니다.'},400);if(!(EDGES[ctx.squad.current_territory]||[]).includes(code)&&ctx.squad.current_territory!==code)return deps.json({error:'인접한 아군 영토로만 이동할 수 있습니다.'},400);const max=target.kind==='CENTER'?cfg.centerGarrisonMax:target.kind.startsWith('BASE')?9999:cfg.normalGarrisonMax;const stationed=Number((await env.DB.prepare("SELECT COUNT(*) c FROM territory_war_squads WHERE round_id=? AND side=? AND current_territory=? AND status<>'MOVING'").bind(r.id,ctx.mine.side,code).first())?.c||0);if(ctx.squad.current_territory!==code&&stationed>=max)return deps.json({error:`해당 영토의 주둔 소대 한도(${max})에 도달했습니다.`},409);await env.DB.batch([env.DB.prepare("UPDATE territory_war_squads SET current_territory=?,status='GARRISON',last_action_at=CURRENT_TIMESTAMP WHERE round_id=? AND side=? AND squad_no=?").bind(code,r.id,ctx.mine.side,ctx.mine.squad_no),env.DB.prepare('DELETE FROM territory_war_orders WHERE round_id=? AND side=? AND squad_no=?').bind(r.id,ctx.mine.side,ctx.mine.squad_no)]);return deps.json({ok:true,state:await publicState(env,user.id)})}
 if(path==='territory-war/cancel-order'&&request.method==='POST'){if(String(cfg.mode||'OFF').toUpperCase()==='OFF')return deps.json({error:'영토전 운영이 중지되었습니다.'},409);const ctx=await commandContext(env,r,user.id,cfg);if(!ctx.canCommand)return deps.json({error:'현재 소대 지휘권이 없습니다.'},403);await env.DB.batch([env.DB.prepare('DELETE FROM territory_war_orders WHERE round_id=? AND side=? AND squad_no=?').bind(r.id,ctx.mine.side,ctx.mine.squad_no),env.DB.prepare("UPDATE territory_war_squads SET status='GARRISON',last_action_at=CURRENT_TIMESTAMP WHERE round_id=? AND side=? AND squad_no=?").bind(r.id,ctx.mine.side,ctx.mine.squad_no)]);return deps.json({ok:true,state:await publicState(env,user.id)})}
 if(path==='territory-war/attack'&&request.method==='POST'){
  if(String(cfg.mode||'OFF').toUpperCase()==='OFF')return deps.json({error:'영토전 운영이 중지되었습니다.'},409);if(!r||r.status!=='ACTIVE')return deps.json({error:'영토전이 진행 중이 아닙니다.'},409);const body=await deps.readBody(request);const code=String(body.territoryCode||'').toUpperCase();const reqId=String(body.requestId||crypto.randomUUID()).slice(0,120);const old=await env.DB.prepare('SELECT battle_summary FROM territory_war_battles WHERE request_id=?').bind(reqId).first();if(old)return deps.json({ok:true,replayed:true,result:safeJson(old.battle_summary,{})});const ctx=await commandContext(env,r,user.id,cfg);if(!ctx.mine?.squad_no)return deps.json({error:ctx.mine?.status==='RESERVE'?'예비대는 이번 회차 공격에 참여할 수 없습니다.':'소대 편성이 완료되지 않았습니다.'},409);if(!ctx.canCommand)return deps.json({error:'소대장 또는 임시 지휘권자만 작전을 실행할 수 있습니다.'},403);const target=await env.DB.prepare('SELECT * FROM territory_war_territories WHERE round_id=? AND code=?').bind(r.id,code).first();if(!target)return deps.json({error:'영토를 찾을 수 없습니다.'},404);if(target.kind.startsWith('BASE'))return deps.json({error:'본진은 직접 공격할 수 없습니다.'},400);const connected=await connectedOwned(env,r.id,ctx.mine.side);if(!connected.has(ctx.squad.current_territory))return deps.json({error:'현재 소대 위치가 본진과 단절되어 공격 출발점으로 사용할 수 없습니다.'},409);if(!(EDGES[ctx.squad.current_territory]||[]).includes(code))return deps.json({error:'현재 소대가 위치한 영토와 인접한 지역만 공격할 수 있습니다.'},400);if(target.owner===ctx.mine.side)return deps.json({error:'아군 영토는 공격 대신 이동을 선택하세요.'},400);const rr=recharge(ctx.squad,cfg);if(rr.energy<1)return deps.json({error:'소대 행동력이 부족합니다.'},409);const lock=await acquireLock(env,`battle_${r.id}_${code}`,90000);if(!lock.ok)return deps.json({error:'해당 영토에서 다른 교전이 진행 중입니다. 잠시 후 다시 시도하세요.'},409);try{
   const defenders=(await env.DB.prepare("SELECT * FROM territory_war_squads WHERE round_id=? AND current_territory=? AND side<>? AND status NOT IN ('REORGANIZING') ORDER BY squad_no").bind(r.id,code,ctx.mine.side).all()).results||[];
   await env.DB.prepare("UPDATE territory_war_squads SET energy=?,last_recharged_at=?,status='MOVING',last_action_at=CURRENT_TIMESTAMP WHERE round_id=? AND side=? AND squad_no=?").bind(rr.energy-1,rr.last,r.id,ctx.mine.side,ctx.mine.squad_no).run();
   if(!defenders.length){const completes=iso(Date.now()+cfg.unguardedCaptureSeconds*1000);await env.DB.batch([env.DB.prepare(`INSERT OR REPLACE INTO territory_war_orders(round_id,side,squad_no,action,target_code,state,completes_at,request_id,updated_at) VALUES(?,?,?,'CAPTURE',?,'PENDING',?,?,CURRENT_TIMESTAMP)`).bind(r.id,ctx.mine.side,ctx.mine.squad_no,code,completes,reqId),env.DB.prepare('UPDATE territory_war_territories SET capture_side=?,capture_completes_at=?,updated_at=CURRENT_TIMESTAMP WHERE round_id=? AND code=?').bind(ctx.mine.side,completes,r.id,code)]);return deps.json({ok:true,pending:true,result:{territoryCode:code,captureCompletesAt:completes,points:0},state:await publicState(env,user.id)})}
   const defender=defenders[0],aNo=ctx.mine.side==='A'?ctx.mine.squad_no:defender.squad_no,bNo=ctx.mine.side==='B'?ctx.mine.squad_no:defender.squad_no;const result=await fightSquads(env,deps,r.id,aNo,bNo,reqId);const winner=result.winner,threshold=target.owner==='NEUTRAL'?1:(target.kind==='CENTER'?cfg.centerCaptureWins:cfg.normalCaptureWins);let ca=Number(target.capture_a||0),cb=Number(target.capture_b||0),owner=target.owner;if(winner==='A'){ca++;cb=Math.max(0,cb-1)}else{cb++;ca=Math.max(0,ca-1)}let captured=false;if(ca>=threshold){owner='A';ca=0;cb=0;captured=true}else if(cb>=threshold){owner='B';ca=0;cb=0;captured=true}const points=cfg.battleWinPoints+(captured?(target.kind==='CENTER'?cfg.centerCapturePoints:cfg.territoryCapturePoints):0);const payload={...result,territoryCode:code,captured,owner,points};const winSquad=winner===ctx.mine.side?ctx.squad:defender,loseSquad=winner===ctx.mine.side?defender:ctx.squad;const memberIds=(await env.DB.prepare('SELECT user_id,side FROM territory_war_registrations WHERE round_id=? AND ((side=? AND squad_no=?) OR (side=? AND squad_no=?))').bind(r.id,ctx.mine.side,ctx.mine.squad_no,defender.side,defender.squad_no).all()).results||[];const stats=memberIds.map(m=>env.DB.prepare('UPDATE territory_war_registrations SET wins=wins+?,losses=losses+?,contribution=contribution+? WHERE round_id=? AND user_id=?').bind(m.side===winner?1:0,m.side===winner?0:1,m.side===winner?points:0,r.id,m.user_id));await env.DB.batch([
 env.DB.prepare('UPDATE territory_war_territories SET owner=?,capture_a=?,capture_b=?,capture_side=NULL,capture_completes_at=NULL,updated_at=CURRENT_TIMESTAMP WHERE round_id=? AND code=?').bind(owner,ca,cb,r.id,code),
 env.DB.prepare("UPDATE territory_war_squads SET current_territory=?,status='GARRISON',wins=wins+1,contribution=contribution+?,last_action_at=CURRENT_TIMESTAMP WHERE round_id=? AND side=? AND squad_no=?").bind(code,points,r.id,winner,winSquad.squad_no),
 env.DB.prepare("UPDATE territory_war_squads SET status='GARRISON',losses=losses+1,last_action_at=CURRENT_TIMESTAMP WHERE round_id=? AND side=? AND squad_no=?").bind(r.id,loseSquad.side,loseSquad.squad_no),
 env.DB.prepare('UPDATE territory_war_rounds SET a_score=a_score+?,b_score=b_score+?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(winner==='A'?points:0,winner==='B'?points:0,r.id),
 env.DB.prepare(`INSERT INTO territory_war_battles(request_id,round_id,territory_code,attacker_side,attacker_squad_no,defender_squad_no,winner_side,a_wins,b_wins,points_awarded,battle_summary) VALUES(?,?,?,?,?,?,?,?,?,?,?)`).bind(reqId,r.id,code,ctx.mine.side,ctx.mine.squad_no,defender.squad_no,winner,result.aw,result.bw,points,JSON.stringify(payload)),
 env.DB.prepare('DELETE FROM territory_war_orders WHERE round_id=? AND side=? AND squad_no=?').bind(r.id,ctx.mine.side,ctx.mine.squad_no),...stats
 ]);payload.individualRewards=await grantDuelWinRewards(env,result,reqId,r.id,cfg);await env.DB.prepare('UPDATE territory_war_battles SET battle_summary=? WHERE request_id=?').bind(JSON.stringify(payload),reqId).run();await pruneBattles(env,r.id,cfg.recentBattleLimit);return deps.json({ok:true,result:payload,state:await publicState(env,user.id)});
  }finally{await releaseLock(env,lock)}}
 if(path==='admin/territory-war/settings'){if(!admin)return deps.json({error:'관리자 권한이 필요합니다.'},403);if(request.method==='POST'){const b=await deps.readBody(request);const next={...cfg,mode:['OFF','TEST','ON'].includes(String(b.mode||'').toUpperCase())?String(b.mode).toUpperCase():cfg.mode,recruitmentHours:clamp(b.recruitmentHours,1,168),preparationMinutes:clamp(b.preparationMinutes,0,1440),roundMinutes:clamp(b.roundMinutes,10,10080),energyMax:clamp(b.energyMax,1,20),energyMinutes:clamp(b.energyMinutes,1,1440),normalCaptureWins:clamp(b.normalCaptureWins,1,10),centerCaptureWins:clamp(b.centerCaptureWins,1,20),battleWinPoints:clamp(b.battleWinPoints,0,100),territoryCapturePoints:clamp(b.territoryCapturePoints,0,1000),centerCapturePoints:clamp(b.centerCapturePoints,0,2000),finalNormalPoints:clamp(b.finalNormalPoints,0,1000),finalCenterPoints:clamp(b.finalCenterPoints,0,2000),finalFrontierPoints:clamp(b.finalFrontierPoints,0,2000),unguardedCaptureSeconds:clamp(b.unguardedCaptureSeconds,5,600),leaderDelegateMinutes:clamp(b.leaderDelegateMinutes,1,1440),normalGarrisonMax:clamp(b.normalGarrisonMax,1,20),centerGarrisonMax:clamp(b.centerGarrisonMax,1,20),recentBattleLimit:clamp(b.recentBattleLimit,10,200),individualWinCoin:clamp(b.individualWinCoin,0,100000000),individualWinShards:clamp(b.individualWinShards,0,1000000),individualWinDailyLimit:clamp(b.individualWinDailyLimit,0,1000),winnerCoin:clamp(b.winnerCoin,0,100000000),loserCoin:clamp(b.loserCoin,0,100000000),drawCoin:clamp(b.drawCoin,0,100000000),participationShards:clamp(b.participationShards,0,1000000),contributionCoinPerPoint:clamp(b.contributionCoinPerPoint,0,1000000),settlementMinBattles:clamp(b.settlementMinBattles,0,1000)};await env.DB.prepare("UPDATE app_meta SET value=?,updated_at=CURRENT_TIMESTAMP WHERE key='territory_war_settings_v1'").bind(JSON.stringify(next)).run();if(next.mode==='OFF'){const latest=await round(env);if(latest&&['RECRUITING','PREPARING','ACTIVE'].includes(String(latest.status||'')))await env.DB.batch([env.DB.prepare("UPDATE territory_war_rounds SET status='DISABLED',updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(latest.id),env.DB.prepare("DELETE FROM territory_war_orders WHERE round_id=? AND state IN ('PENDING','BLOCKED')").bind(latest.id),env.DB.prepare("UPDATE territory_war_territories SET capture_side=NULL,capture_completes_at=NULL,updated_at=CURRENT_TIMESTAMP WHERE round_id=?").bind(latest.id)]);}else{const latest=await round(env);if(!latest||['FINISHED','DISABLED'].includes(String(latest.status||'')))await createRound(env,next);}return deps.json({ok:true,settings:next,state:await publicState(env,user.id)})}return deps.json({settings:cfg,state:await publicState(env,user.id)})}
 if(path==='admin/territory-war/commander'&&request.method==='POST'){if(!admin)return deps.json({error:'관리자 권한이 필요합니다.'},403);const b=await deps.readBody(request);await env.DB.prepare('UPDATE territory_war_squads SET command_user_id=?,last_action_at=CURRENT_TIMESTAMP WHERE round_id=? AND side=? AND squad_no=?').bind(Number(b.userId),r.id,String(b.side||'').toUpperCase(),Number(b.squadNo)).run();return deps.json({ok:true,state:await publicState(env,user.id)})}
 if(path==='admin/territory-war/start'&&request.method==='POST'){if(!admin)return deps.json({error:'관리자 권한이 필요합니다.'},403);if(String(cfg.mode||'OFF').toUpperCase()==='OFF')return deps.json({error:'운영 모드를 TEST 또는 ON으로 변경하세요.'},409);if(!r||r.status!=='RECRUITING')return deps.json({error:'모집 중인 회차만 편성할 수 있습니다.'},409);r=await maybeAdvance(env,r,cfg,true);return deps.json({ok:true,state:await publicState(env,user.id)})}
 if(path==='admin/territory-war/finish'&&request.method==='POST'){if(!admin)return deps.json({error:'관리자 권한이 필요합니다.'},403);if(!r)return deps.json({error:'종료할 회차가 없습니다.'},409);const finished=await settleRound(env,r,cfg);if(String(cfg.mode||'OFF').toUpperCase()!=='OFF')await createRound(env,cfg);return deps.json({ok:true,winner:finished.winner,state:await publicState(env,user.id)})}
 return deps.json({error:'요청한 영토전 기능을 찾을 수 없습니다.'},404)
}
