import test from 'node:test';
import assert from 'node:assert/strict';
import {createState,polish,probabilities,eligible,coinCost} from './source/model.mjs';
test('Five intervals select the five options and add exactly one step',()=>{for(let i=0;i<5;i++){const input=createState();const {state,receipt}=polish(input,'roll',i/5+.01);assert.equal(receipt.selected,i);assert.equal(state.levels.reduce((a,b)=>a+b),1);assert.equal(input.total,0);assert.equal(state.stones,99);assert.equal(state.coins,200000-coinCost(input));}});
test('A capped option cannot be selected and its probability is redistributed',()=>{const input={...createState(),levels:[10,0,0,0,0],total:10};assert.deepEqual(eligible(input),[1,2,3,4]);assert.deepEqual(probabilities(input),[0,25,25,25,25]);for(let i=0;i<4;i++)assert.equal(polish(input,'r'+i,i/4+.01).receipt.selected,i+1);});
test('A repeated receipt never consumes a second stone or rolls again',()=>{const first=polish(createState(),'same',.01);const retry=polish(first.state,'same',.99);assert.equal(retry.receipt,first.receipt);assert.equal(retry.state,first.state);assert.equal(retry.state.total,1);});
test('Twenty rolls finish the specimen without exceeding individual caps',()=>{let state=createState();for(let i=0;i<20;i++)state=polish(state,'r'+i,0).state;assert.deepEqual(state.levels,[10,10,0,0,0]);assert.equal(state.total,20);assert.deepEqual(probabilities(state),[0,0,0,0,0]);assert.throws(()=>polish(state,'extra',.1),/완료/);});
test('Insufficient material and invalid samples leave input unchanged',()=>{for(const bad of [{...createState(),stones:0},{...createState(),coins:0}]){const snapshot=JSON.stringify(bad);assert.throws(()=>polish(bad,'denied',.3),/부족/);assert.equal(JSON.stringify(bad),snapshot);}for(const value of [-.1,1,NaN])assert.throws(()=>polish(createState(),'bad',value),/sample/);});
test('Separate equipment specimens do not share growth or receipts',()=>{const first=polish(createState(),'a',.4).state,second=createState();assert.equal(first.total,1);assert.equal(second.total,0);assert.equal(Object.keys(second.receipts).length,0);});
