import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { PGlite } from '@electric-sql/pglite';
import { JointSQLiteDB } from './helpers/joint-db.mjs';
import { __postgresCompatTest } from '../functions/_postgres_d1_compat.js';
import { ensureRuntimeFoundation } from '../functions/_runtime_foundation.js';
import { ACHIEVEMENT_TITLES_KEY, ACHIEVEMENT_TITLE_POWER_KEY, ensureAchievementTitles, readCollectionMastery, collectionMasteryMet, syncAchievementTitles } from '../functions/_achievement_titles.js';

const schema = `
CREATE TABLE app_meta(key TEXT PRIMARY KEY,value TEXT,updated_at TEXT);
CREATE TABLE character_titles(id INTEGER PRIMARY KEY AUTOINCREMENT,code TEXT UNIQUE,name TEXT,description TEXT,badge_text TEXT,image_url TEXT,pve_power INTEGER,unlock_type TEXT,unlock_config_json TEXT,style_preset TEXT,is_active INTEGER,is_public INTEGER,sort_order INTEGER);
CREATE TABLE user_character_titles(user_id INTEGER,title_id INTEGER,source_type TEXT,source_id TEXT,PRIMARY KEY(user_id,title_id));
CREATE TABLE cards_effective_v1210(id TEXT PRIMARY KEY,is_active INTEGER,card_status TEXT);
CREATE TABLE user_cards(user_id INTEGER,card_id TEXT,quantity INTEGER,PRIMARY KEY(user_id,card_id));
CREATE TABLE character_garage_items(id INTEGER PRIMARY KEY,is_active INTEGER,is_public INTEGER);
CREATE TABLE user_garage_vehicles(user_id INTEGER,garage_id INTEGER,PRIMARY KEY(user_id,garage_id));
CREATE TABLE pvp_season_settlements(id INTEGER PRIMARY KEY,season_name TEXT,status TEXT,started_at TEXT,completed_at TEXT);
CREATE TABLE pvp_season_settlement_ranks(settlement_id INTEGER,user_id INTEGER,tier_id TEXT,tier_name TEXT,final_rank INTEGER,season_score INTEGER,wins INTEGER,losses INTEGER);
CREATE TABLE clan_season_settlements(season_id INTEGER,champion_clan_id INTEGER,status TEXT,reward_status TEXT,completed_at TEXT);
CREATE TABLE clan_seasons(id INTEGER,phase TEXT);
CREATE TABLE clan_organizations(id INTEGER);
CREATE TABLE clan_members(season_id INTEGER,clan_id INTEGER,user_id INTEGER,joined_at TEXT);
CREATE TABLE clan_championship_rewards(season_id INTEGER,user_id INTEGER,reward_type TEXT,reward_amount INTEGER,status TEXT,completed_at TEXT);
CREATE TABLE clan_championships(season_id INTEGER,winner_clan_id INTEGER,status TEXT,reward_status TEXT,completed_at TEXT);
CREATE TABLE clan_championship_members(season_id INTEGER,user_id INTEGER,clan_id INTEGER);
CREATE TABLE ranked_duo_trophies_v2(season_id TEXT,user_id INTEGER,acquired_at TEXT,PRIMARY KEY(season_id,user_id));
`;

async function fixture(t, postgres) {
  let fail = () => false, reads = 0, DB, pg;
  if (postgres) {
    pg = new PGlite();
    await pg.exec("CREATE FUNCTION sqlite_now() RETURNS text LANGUAGE SQL STABLE AS $$SELECT to_char(timezone('UTC',CURRENT_TIMESTAMP),'YYYY-MM-DD HH24:MI:SS')$$;CREATE FUNCTION sqlite_datetime(text) RETURNS text LANGUAGE SQL STABLE AS $$SELECT CASE WHEN $1='now' THEN sqlite_now() ELSE to_char(timezone('UTC',$1::timestamptz),'YYYY-MM-DD HH24:MI:SS') END$$;");
    await pg.exec(schema.replaceAll('INTEGER PRIMARY KEY AUTOINCREMENT','BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY'));
    DB = new __postgresCompatTest.PostgresD1Database({ async query(input) {
      const sql = typeof input === 'string' ? input : input.text, values = typeof input === 'string' ? [] : input.values || [];
      if (fail(sql, values)) throw Error('INJECTED_FAILURE');
      if (/^\s*(SELECT|WITH)/.test(sql)) reads++;
      const r = await pg.query(sql, values); return { ...r, rowCount: r.affectedRows ?? r.rows.length };
    } });
  } else {
    DB = new JointSQLiteDB(); DB.sql.exec(schema);
    const execute = DB.execute.bind(DB), prepare = DB.prepare.bind(DB);
    DB.execute = stmt => { if (fail(stmt.source, stmt.values)) throw Error('INJECTED_FAILURE'); return execute(stmt); };
    DB.prepare = sql => { if (/^\s*(SELECT|WITH)/.test(sql)) reads++; return prepare(sql); };
  }
  t.after(() => pg ? pg.close() : DB.sql.close());
  const env = { DB }, p = (sql, ...args) => DB.prepare(sql).bind(...args);
  return { DB, env, p, fail: predicate => { fail = predicate; }, reads: () => reads };
}

test('exact collection thresholds: no rounding, empty catalogues cannot qualify', () => {
  const cards = { owned: 5, total: 5 };
  assert.equal(collectionMasteryMet(cards, { owned: 9, total: 10 }), true);
  assert.equal(collectionMasteryMet(cards, { owned: 8, total: 10 }), false);
  assert.equal(collectionMasteryMet(cards, { owned: 17, total: 19 }), false);
  assert.equal(collectionMasteryMet(cards, { owned: 18, total: 19 }), true);
  assert.equal(collectionMasteryMet({ owned: 4, total: 5 }, { owned: 10, total: 10 }), false);
  assert.equal(collectionMasteryMet({ owned: 0, total: 0 }, { owned: 10, total: 10 }), false);
  assert.equal(collectionMasteryMet(cards, { owned: 0, total: 0 }), false);
});

for (const postgres of [false, true]) {
  const label = postgres ? 'PostgreSQL' : 'SQLite';
  test(`${label}: new marker seeds on an already initialized installation; failed seed rolls back and preserves CMS edits on retry`, async t => {
    const f = await fixture(t, postgres);
    await f.p("INSERT INTO app_meta(key,value) VALUES('old-foundation','1')").run();
    const initialize = () => ensureRuntimeFoundation(f.env, Symbol('new'), ['old-foundation', ACHIEVEMENT_TITLES_KEY, ACHIEVEMENT_TITLE_POWER_KEY], () => ensureAchievementTitles(f.env));
    f.fail((sql, args) => /INSERT.*character_titles/i.test(sql) && args[0] === 'TROPHY_HUNTER');
    await assert.rejects(initialize, /INJECTED_FAILURE/);
    assert.equal(Number((await f.p('SELECT COUNT(*) n FROM character_titles').first()).n), 0);
    assert.equal(await f.p('SELECT value FROM app_meta WHERE key=?', ACHIEVEMENT_TITLES_KEY).first(), null);
    f.fail(() => false); await initialize(); await initialize();
    const titles = (await f.p('SELECT * FROM character_titles ORDER BY id').all()).results;
    assert.deepEqual(titles.map(x => x.name), ['폐인', '우승청부사']);
    assert.deepEqual(titles.map(x => Number(x.pve_power)), [50000, 75000]);
    await f.p("UPDATE character_titles SET description='CMS 보존',is_active=0 WHERE code='TROPHY_HUNTER'").run();
    await f.p('DELETE FROM app_meta WHERE key=?', ACHIEVEMENT_TITLES_KEY).run(); await ensureAchievementTitles(f.env);
    const edited = await f.p("SELECT * FROM character_titles WHERE code='TROPHY_HUNTER'").first();
    assert.equal(edited.description, 'CMS 보존'); assert.equal(Number(edited.is_active), 0);
  });

  test(`${label}: existing zero-power titles upgrade atomically once, retain ownership and preserve later CMS power edits`, async t => {
    const f = await fixture(t, postgres); await ensureAchievementTitles(f.env);
    await f.p('UPDATE character_titles SET pve_power=0').run();
    await f.p("INSERT INTO user_character_titles SELECT 7,id,'ACHIEVEMENT',code FROM character_titles").run();
    await f.p('DELETE FROM app_meta WHERE key=?', ACHIEVEMENT_TITLE_POWER_KEY).run();
    const initialize = () => ensureRuntimeFoundation(f.env, Symbol('upgrade'), [ACHIEVEMENT_TITLES_KEY, ACHIEVEMENT_TITLE_POWER_KEY], () => ensureAchievementTitles(f.env));
    const powers = async () => (await f.p('SELECT pve_power FROM character_titles ORDER BY id').all()).results.map(r => Number(r.pve_power));
    f.fail((sql,args) => /UPDATE character_titles/i.test(sql) && args[1] === 'TROPHY_HUNTER');
    await assert.rejects(initialize, /INJECTED_FAILURE/);
    assert.deepEqual(await powers(), [0, 0], 'second update failure rolls back both values');
    assert.equal(await f.p('SELECT value FROM app_meta WHERE key=?', ACHIEVEMENT_TITLE_POWER_KEY).first(), null);
    f.fail(() => false);
    const batch = f.DB.batch.bind(f.DB); let lost = true;
    f.DB.batch = async rows => { const result = await batch(rows); if (lost) { lost=false; throw Error('LOST_RESPONSE'); } return result; };
    await assert.rejects(initialize, /LOST_RESPONSE/);
    await initialize();
    assert.deepEqual(await powers(), [50000, 75000]);
    assert.equal(Number((await f.p('SELECT COUNT(*) n FROM user_character_titles WHERE user_id=7').first()).n), 2);
    await f.p("UPDATE character_titles SET pve_power=80000 WHERE code='TROPHY_HUNTER'").run();
    await initialize(); await ensureAchievementTitles(f.env);
    assert.deepEqual(await powers(), [50000, 80000], 'redeployment cannot overwrite an operator edit after the approved update');
  });

  test(`${label}: visible distinct card/vehicle ownership, official trophy kinds, atomic grants and lost-response retries`, async t => {
    const f = await fixture(t, postgres); await ensureAchievementTitles(f.env);
    for (let i = 1; i <= 10; i++) {
      await f.p("INSERT INTO cards_effective_v1210 VALUES(?,1,'PUBLIC')", 'c'+i).run();
      await f.p('INSERT INTO user_cards VALUES(7,?,100)', 'c'+i).run();
      await f.p('INSERT INTO character_garage_items VALUES(?,1,1)', i).run();
      if (i < 10) await f.p('INSERT INTO user_garage_vehicles VALUES(7,?)', i).run();
    }
    await f.p("INSERT INTO cards_effective_v1210 VALUES('inactive',0,'PUBLIC'),('hidden',1,'DRAFT'),('retired',1,'RETIRED')").run();
    await f.p('INSERT INTO character_garage_items VALUES(11,0,1),(12,1,0)').run();
    await f.p("INSERT INTO user_cards VALUES(7,'inactive',999),(8,'c10',1)").run();
    await f.p("UPDATE user_cards SET quantity=0 WHERE user_id=7 AND card_id='c10'").run();
    let mastery = await readCollectionMastery(f.env,7);
    assert.deepEqual(mastery, { cards: { owned:9,total:10 }, vehicles: { owned:9,total:10 } });
    assert.equal(collectionMasteryMet(mastery.cards, mastery.vehicles), false, 'extra inactive holdings cannot replace missing public cards');
    await f.p("UPDATE user_cards SET quantity=1 WHERE user_id=7 AND card_id='c10'").run();
    // Three official kinds: ranked champion, a 3-season challenger streak, regular clan winner.
    for (let i = 1; i <= 3; i++) {
      await f.p("INSERT INTO pvp_season_settlements VALUES(?,?,'COMPLETED',?,?)", i, '시즌'+i, `2026-08-0${i}`, `2026-08-0${i}`).run();
      await f.p("INSERT INTO pvp_season_settlement_ranks VALUES(?,7,'challenger','챌린저',1,3000,10,0)",i).run();
    }
    await f.p("INSERT INTO clan_seasons VALUES(1,'CHAMPIONS')").run();
    await f.p('INSERT INTO clan_organizations VALUES(8)').run();
    await f.p("INSERT INTO clan_members VALUES(1,8,7,'2026-07-01')").run();
    await f.p("INSERT INTO clan_season_settlements VALUES(1,8,'COMPLETED','PAID','2026-08-02')").run();
    const firstStart = performance.now(), firstReads = f.reads();
    const first = await syncAchievementTitles(f.env,7);
    t.diagnostic(`initial achievement sync: ${f.reads()-firstReads} read queries, ${(performance.now()-firstStart).toFixed(2)} ms in isolated fixture`);
    assert.equal(first.granted.length,1); assert.equal(first.progress.TROPHY_HUNTER.owned,3);
    assert.equal(first.progress.TROPHY_HUNTER.complete,false, 'three ranked winner copies still count as one kind');
    // An undelivered / test champions receipt is not a fourth kind.
    await f.p("INSERT INTO clan_championships VALUES(2,8,'COMPLETED','DISABLED_TEST','2026-08-10')").run();
    await f.p('INSERT INTO clan_championship_members VALUES(2,7,8)').run();
    await f.p("INSERT INTO clan_championship_rewards VALUES(2,7,'CLAN_CHAMPIONS_TROPHY',1,'PENDING',NULL)").run();
    assert.equal((await syncAchievementTitles(f.env,7)).progress.TROPHY_HUNTER.owned,3);
    await f.p("UPDATE clan_championship_rewards SET status='SENT',completed_at='2026-08-10'").run();
    assert.equal((await syncAchievementTitles(f.env,7)).progress.TROPHY_HUNTER.owned,3);
    await f.p("UPDATE clan_championships SET reward_status='SENT'").run();
    await f.p('DELETE FROM user_character_titles WHERE user_id=7').run();
    const hunter = await f.p("SELECT id FROM character_titles WHERE code='TROPHY_HUNTER'").first();
    f.fail((sql,args) => /INSERT.*user_character_titles/i.test(sql) && Number(args[1])===Number(hunter.id));
    await assert.rejects(() => syncAchievementTitles(f.env,7), /INJECTED_FAILURE/);
    assert.equal(Number((await f.p('SELECT COUNT(*) n FROM user_character_titles').first()).n),0,'second grant failure rolls back the first');
    f.fail(() => false);
    const batch = f.DB.batch.bind(f.DB); let lost = true;
    f.DB.batch = async rows => { const result = await batch(rows); if (lost) { lost=false; throw Error('LOST_RESPONSE'); } return result; };
    await assert.rejects(() => syncAchievementTitles(f.env,7), /LOST_RESPONSE/);
    const before = f.reads(), retryStart = performance.now(); const again = await syncAchievementTitles(f.env,7);
    const retryMs = performance.now()-retryStart;
    assert.deepEqual(again, { granted:[],progress:{} }); assert.equal(f.reads()-before,1,'earned achievements skip collection and history scans');
    assert.equal(Number((await f.p('SELECT COUNT(*) n FROM user_character_titles WHERE user_id=7').first()).n),2);
    assert.equal((await syncAchievementTitles(f.env,8)).granted.length,0,'another player cannot inherit honors');
    // Permanent duo receipts can supply the fourth kind independently of the cup.
    await f.p("INSERT INTO app_meta(key,value) VALUES('ranked_duo_auto_schema_v2','1')").run();
    await f.p("INSERT INTO ranked_duo_trophies_v2 VALUES('d1',7,'2026-09-01'),('d2',7,'2026-09-02')").run();
    await f.p("UPDATE clan_championships SET reward_status='DISABLED_TEST'").run();
    await f.p('DELETE FROM user_character_titles WHERE title_id=?',hunter.id).run();
    const concurrent = await Promise.all([syncAchievementTitles(f.env,7),syncAchievementTitles(f.env,7)]);
    assert.equal(concurrent.flatMap(r=>r.granted).length,1,'concurrent reads grant exactly once');
    assert.equal(concurrent[0].progress.TROPHY_HUNTER.owned,4);
    await f.p('DELETE FROM user_character_titles WHERE title_id=?',hunter.id).run();
    f.DB.batch = async rows => {
      await f.p("UPDATE character_titles SET unlock_type='MANUAL' WHERE id=?",hunter.id).run();
      return batch(rows);
    };
    assert.deepEqual((await syncAchievementTitles(f.env,7)).granted,[],'CMS manual switch during the scan is checked again at grant time');
    assert.equal(Number((await f.p('SELECT COUNT(*) n FROM user_character_titles WHERE title_id=?',hunter.id).first()).n),0);
    t.diagnostic(`already-owned sync: 1 query; ${retryMs.toFixed(2)} ms in isolated fixture`);
  });
}

test('runtime foundation includes the new marker and every live surface loads the new styles', () => {
  const read = path => readFileSync(new URL('../'+path,import.meta.url),'utf8');
  const server = read('functions/_equipment.js');
  assert.match(server,/Z_SWORD_APPEARANCE_KEY,ACHIEVEMENT_TITLES_KEY,ACHIEVEMENT_TITLE_POWER_KEY/);
  assert.match(server,/await ensureAchievementTitles\(env\)/);
  assert.match(server,/syncAchievementTitles\(env,user.id\)/);
  for (const path of ['index.html','admin/index.html','js/app.js']) assert.match(read(path),/achievement-titles-20260927.css/);
  for (const path of ['index.html','js/app.js','admin/index.html']) assert.match(read(path),/achievementTitles=20260927/);
  assert.match(read('js/player-card-v2052.js'),/pc-equipped-title public-title-badge title-style-/);
  assert.match(read('js/character-loadout-v2.js'),/clv2-title-emblem/);
});
