import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {PGlite} from '@electric-sql/pglite';
import {__postgresCompatTest} from '../functions/_postgres_d1_compat.js';
import {auctionFixture} from './helpers/auction-fixture-20260926.mjs';

test('100억 and 1000억 bids debit and accumulate the exact amount once, including retries and refunds', async t => {
  const f = await auctionFixture(t);
  let total = 0;
  for (const amount of [10_000_000_000, 100_000_000_000]) {
    const id = 'large-' + amount, response = await f.bid(amount, id);
    total += amount;
    assert.equal(response.status, 200);
    assert.equal(response.body.state.mine.totalBid, total);
    assert.equal(f.row('SELECT coin FROM users').coin, 1_000_000_000_000 - total);
    assert.equal((await f.bid(amount, id)).body.replayed, true);
    assert.equal(f.row('SELECT coin FROM users').coin, 1_000_000_000_000 - total);
  }
  assert.equal(f.row('SELECT COUNT(*) n FROM coin_logs').n, 2);
  assert.equal(f.row('SELECT SUM(amount) amount FROM auction_coin_debits_v1574').amount, total);
  const refund = await f.request('auction/admin/cancel', {auctionId: 1});
  assert.equal(refund.body.refundTotal, total);
  assert.equal(f.row('SELECT coin FROM users').coin, 1_000_000_000_000);
  assert.equal((await f.request('auction/admin/cancel', {auctionId: 1})).status, 404);
  assert.equal(f.row('SELECT coin FROM users').coin, 1_000_000_000_000);
});

test('out-of-guide bids update totals without scheduling or broadcasting a popup', async t => {
  const f = await auctionFixture(t);
  for (const amount of [999, 10001, 10_000_000_000, 100_000_000_000]) {
    const id = 'silent-' + amount;
    assert.equal((await f.bid(amount, id)).status, 200);
    const event = await f.event(id);
    const scheduled = await f.request('auction/schedule-event', {eventId: event.body.event.id});
    assert.equal(scheduled.body.event, null);
    assert.deepEqual((await f.request('auction/events?auctionId=1&after=0')).body.events, []);
  }
  assert.equal(f.row('SELECT COUNT(*) n FROM auction_bid_schedule_v1567').n, 0);
  assert.equal(f.row('SELECT total_bid FROM auction_bidders_v1553').total_bid, 110_000_011_000);
});

test('matching guide boundaries still broadcast BGM and messages once', async t => {
  const f = await auctionFixture(t);
  for (const amount of [1000, 10000]) {
    const id = 'bgm-' + amount;
    await f.bid(amount, id);
    const event = (await f.event(id)).body.event;
    const scheduled = await f.request('auction/schedule-event', {eventId: event.id});
    assert.equal(scheduled.body.event.bgm_url, '/assets/audio/auction-test.mp3');
    assert.equal(scheduled.body.event.message, '입찰 검수');
    const replay = await f.request('auction/schedule-event', {eventId: (await f.event(id)).body.event.id});
    assert.equal(replay.body.event.presentation_starts_at, scheduled.body.event.presentation_starts_at);
  }
  assert.equal(f.row('SELECT COUNT(*) n FROM auction_bid_schedule_v1567').n, 2);
  assert.equal((await f.request('auction/events?auctionId=1&after=0')).body.events.length, 2);
});

test('previously queued non-BGM messages are omitted from the event stream', async t => {
  const f = await auctionFixture(t);
  await f.bid(500, 'old-silent');
  const silent = (await f.event('old-silent')).body.event;
  f.sql.prepare('INSERT INTO auction_bid_schedule_v1567(event_id,auction_id,starts_at,ends_at) VALUES(?,1,?,?)')
    .run(silent.id, new Date().toISOString(), new Date(Date.now() + 60000).toISOString());
  await f.bid(1000, 'new-bgm');
  const bgm = (await f.event('new-bgm')).body.event;
  await f.request('auction/schedule-event', {eventId: bgm.id});
  const events = (await f.request('auction/events?auctionId=1&after=0')).body.events;
  assert.deepEqual(events.map(event => event.id), [bgm.id]);
});

test('PostgreSQL executes 100억/1000억 bid SQL, rollback, retries and refunds without integer overflow', async t => {
  const f = await auctionFixture(t), pg = new PGlite();
  t.after(() => pg.close());
  const helpers = readFileSync(new URL('../scripts/postgres-runtime-compat.sql', import.meta.url), 'utf8');
  await pg.exec(helpers.slice(helpers.indexOf('CREATE OR REPLACE FUNCTION sqlite_datetime'), helpers.indexOf('CREATE OR REPLACE FUNCTION sqlite_date(')));
  await pg.exec("CREATE FUNCTION sqlite_now() RETURNS text LANGUAGE SQL STABLE AS $$SELECT to_char(timezone('UTC',CURRENT_TIMESTAMP),'YYYY-MM-DD HH24:MI:SS')$$;");
  // Match the existing PostgreSQL migration's 64-bit INTEGER mapping.
  for (const {name, sql} of f.sql.prepare("SELECT name,sql FROM sqlite_master WHERE type='table' AND name<>'sqlite_sequence'").all()) {
    await pg.exec(sql.replace(/INTEGER PRIMARY KEY AUTOINCREMENT/g, 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY')
      .replace(/\bINTEGER\b/g, 'BIGINT').replace(/CURRENT_TIMESTAMP/g, 'sqlite_now()'));
    for (const row of f.sql.prepare('SELECT * FROM ' + name).all()) {
      const entries = Object.entries(row);
      await pg.query(`INSERT INTO ${name}(${entries.map(([key]) => key).join(',')}) VALUES(${entries.map((_, i) => '$' + (i + 1)).join(',')})`, entries.map(([, value]) => value));
    }
  }
  let failLog = false;
  __postgresCompatTest.clearPostgresCatalogCache();
  f.env.DB = new __postgresCompatTest.PostgresD1Database({async query(input) {
    const text = typeof input === 'string' ? input : input.text;
    if (failLog && text.includes('INSERT INTO coin_logs')) throw Error('PostgreSQL rollback check');
    const result = await pg.query(text, typeof input === 'string' ? [] : input.values || []);
    const rows = result.rows.map(row => Object.fromEntries(Object.entries(row).map(([key, value]) => [key, typeof value === 'bigint' ? Number(value) : value])));
    return {...result, rows, rowCount: result.affectedRows ?? rows.length};
  }});
  const coin = async () => Number((await pg.query('SELECT coin FROM users WHERE id=1')).rows[0].coin);
  failLog = true;
  await assert.rejects(f.bid(100_000_000_000, 'pg-retry'), /PostgreSQL rollback check/);
  assert.equal(await coin(), 1_000_000_000_000);
  failLog = false;
  for (const [amount, id] of [[100_000_000_000, 'pg-retry'], [10_000_000_000, 'pg-second']]) {
    assert.equal((await f.bid(amount, id)).status, 200);
    assert.equal((await f.bid(amount, id)).body.replayed, true);
  }
  assert.equal(await coin(), 890_000_000_000);
  const receipt = (await pg.query('SELECT SUM(amount) amount,COUNT(*) count FROM auction_coin_debits_v1574')).rows[0];
  assert.equal(Number(receipt.amount), 110_000_000_000);
  assert.equal(Number(receipt.count), 2);
  assert.equal((await f.request('auction/admin/cancel', {auctionId: 1})).body.refundTotal, 110_000_000_000);
  assert.equal(await coin(), 1_000_000_000_000);
});

test('invalid or excessive amounts are rejected without silently changing the bid', async t => {
  const f = await auctionFixture(t);
  for (const amount of [0, -1, 1.5, null, 'bad', 100_000_000_001, Number.MAX_SAFE_INTEGER]) {
    assert.equal((await f.bid(amount)).status, 400, String(amount));
  }
  assert.equal(f.row('SELECT coin FROM users').coin, 1_000_000_000_000);
  assert.equal(f.row('SELECT COUNT(*) n FROM auction_coin_debits_v1574').n, 0);
});

test('insufficient funds and an interrupted large bid never leave a partial debit', async t => {
  const f = await auctionFixture(t);
  f.sql.exec('UPDATE users SET coin=1000000000');
  assert.equal((await f.bid(100_000_000_000, 'insufficient')).status, 409);
  assert.equal(f.row('SELECT coin FROM users').coin, 1_000_000_000);
  assert.equal(f.row('SELECT COUNT(*) n FROM auction_bidders_v1553').n, 0);
  f.sql.exec('UPDATE users SET coin=1000000000000');
  f.faults.sql = 'INSERT INTO coin_logs';
  await assert.rejects(f.bid(100_000_000_000, 'retry-transaction'), /injected transaction failure/);
  assert.equal(f.row('SELECT coin FROM users').coin, 1_000_000_000_000);
  assert.equal(f.row('SELECT COUNT(*) n FROM auction_bidders_v1553').n, 0);
  f.faults.sql = '';
  assert.equal((await f.bid(100_000_000_000, 'retry-transaction')).body.state.mine.totalBid, 100_000_000_000);
  await f.bid(100_000_000_000, 'retry-transaction');
  assert.equal(f.row('SELECT coin FROM users').coin, 900_000_000_000);
});

test('CMS BGM ranges preserve 100억 and 1000억 boundaries', async t => {
  const f = await auctionFixture(t);
  await f.request('auction/admin/bgm-rules', {rules: [{minBid: 10_000_000_000, maxBid: 100_000_000_000, bgmUrl: '/high-bid.mp3', duration: 40}]});
  assert.equal(f.row('SELECT min_bid FROM auction_bgm_rules_v1554').min_bid, 10_000_000_000);
  assert.equal(f.row('SELECT max_bid FROM auction_bgm_rules_v1554').max_bid, 100_000_000_000);
  await f.bid(100_000_000_000, 'high-bgm');
  const event = (await f.event('high-bgm')).body.event;
  assert.equal((await f.request('auction/schedule-event', {eventId: event.id})).body.event.bgm_url, '/high-bid.mp3');
});
