import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
import {__postgresCompatTest} from '../functions/_postgres_d1_compat.js';
import {DC_AVATAR,DC_GRANT_KEY,DC_EXPECTED_EFFECTS,releaseDcHiHeeya} from '../scripts/ops/avatar-dc-hi-heeya-release.mjs';
let fixtureId=0;
async function fixture(){
 const pg=new PGlite(),api=await import('../functions/_avatar.js?dc-release-test='+fixtureId++);
 await pg.exec(`CREATE FUNCTION sqlite_now() RETURNS text LANGUAGE SQL STABLE AS $$SELECT to_char(timezone('UTC',CURRENT_TIMESTAMP),'YYYY-MM-DD HH24:MI:SS')$$;
  CREATE TABLE app_meta(key TEXT PRIMARY KEY,value TEXT,updated_at TEXT);
  CREATE TABLE admin_logs(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,admin_id BIGINT,action_type TEXT,target_type TEXT,target_id TEXT,before_data TEXT,after_data TEXT);
  CREATE TABLE users(id BIGINT PRIMARY KEY,nickname TEXT,role TEXT,coin BIGINT,status TEXT);
  INSERT INTO users VALUES(1,'DC master','OWNER',777,'ACTIVE'),(2,'DC member','USER',888,'ACTIVE'),(3,'Other clan','USER',999,'ACTIVE');
  CREATE TABLE clan_seasons(id BIGINT PRIMARY KEY,season_no INTEGER,phase TEXT);
  INSERT INTO clan_seasons VALUES(5,2,'ACTIVE');
  CREATE TABLE clan_organizations(id BIGINT PRIMARY KEY,name TEXT UNIQUE,is_active INTEGER);
  INSERT INTO clan_organizations VALUES(7,'DC',1),(8,'Other',1);
  CREATE TABLE clan_members(season_id BIGINT,clan_id BIGINT,user_id BIGINT,member_role TEXT,PRIMARY KEY(season_id,user_id));
  INSERT INTO clan_members VALUES(5,7,1,'MASTER'),(5,7,2,'MEMBER'),(5,8,3,'MEMBER');
  INSERT INTO app_meta VALUES('avatar_settings_v1','{"mode":"ON","shopEnabled":true,"version":3}',NULL);`);
 const client={async query(input,values){const r=await pg.query(typeof input==='string'?input:input.text,typeof input==='string'?values||[]:input.values||[]);return {...r,rowCount:r.affectedRows??r.rows.length}}};
 const db=new __postgresCompatTest.PostgresD1Database(client),env={DB:db};
 await api.ensureAvatarFoundation(env);
 await pg.exec("UPDATE avatar_catalog_v1 SET effect_type='COIN_GAIN_PERCENT',effect_value=75,is_active=1,is_public=1,version=3 WHERE code='T1_JOEUN'");
 await pg.query("DELETE FROM avatar_effect_options_v1 WHERE avatar_code='T1_JOEUN'");
 for(const effect of DC_EXPECTED_EFFECTS)await pg.query("INSERT INTO avatar_effect_options_v1(avatar_code,option_order,effect_type,effect_value) VALUES('T1_JOEUN',$1,$2,$3)",[effect.option_order,effect.effect_type,effect.effect_value]);
 const plan={expectedSeasonId:5,expectedClanId:7,expectedRecipientIds:[1,2]};
 const q=async(sql,values=[])=>(await pg.query(sql,values)).rows;
 const call=(id,path,body)=>api.handleAvatar({env,path,deps:{authenticate:async()=>({id,role:'USER'}),readBody:r=>r.json(),json:(body,status=200)=>({body,status})},request:new Request('https://qa.test/api/'+path,body?{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}:{})});
 return {pg,api,env,db,plan,q,call};
}
async function assertAbsent(q){
 assert.equal((await q('SELECT * FROM avatar_catalog_v1 WHERE code=$1',[DC_AVATAR.code])).length,0);
 assert.equal((await q('SELECT * FROM avatar_effect_options_v1 WHERE avatar_code=$1',[DC_AVATAR.code])).length,0);
 assert.equal((await q('SELECT * FROM avatar_user_ownership_v1 WHERE avatar_code=$1',[DC_AVATAR.code])).length,0);
 assert.equal((await q('SELECT * FROM app_meta WHERE key=$1',[DC_GRANT_KEY])).length,0);
}

test('DC members receive the same T1 options for exactly eleven days; replay and expiry preserve the contract',async()=>{
 const {pg,api,env,db,plan,q,call}=await fixture();
 try{
  const catalogBefore=await q('SELECT * FROM avatar_catalog_v1 ORDER BY code'),effectsBefore=await q('SELECT * FROM avatar_effect_options_v1 ORDER BY avatar_code,option_order'),usersBefore=await q('SELECT * FROM users ORDER BY id');
  const result=await releaseDcHiHeeya(db,plan);
  assert.equal((await q("SELECT * FROM admin_logs WHERE action_type='CLAN_AVATAR_TIMED_GRANT'")).length,1);assert.ok(result.grantAuditId);assert.equal(result.granted,2);assert.equal(result.durationDays,11);assert.deepEqual(result.effects,DC_EXPECTED_EFFECTS);
  assert.deepEqual(result.recipients.map(r=>r.userId),[1,2]);
  const utc=value=>Date.parse(value.replace(' ','T')+'Z');
  assert.equal(utc(result.expiresAt)-utc(result.acquiredAt),11*86400000);
  assert.deepEqual(await q('SELECT * FROM avatar_user_loadout_v1'),[]);
  assert.deepEqual(await q('SELECT * FROM users ORDER BY id'),usersBefore);
  assert.deepEqual(await q('SELECT * FROM avatar_catalog_v1 WHERE code<>$1 ORDER BY code',[DC_AVATAR.code]),catalogBefore);
  assert.deepEqual(await q('SELECT * FROM avatar_effect_options_v1 WHERE avatar_code<>$1 ORDER BY avatar_code,option_order',[DC_AVATAR.code]),effectsBefore);
  const originalOwnership=await q('SELECT * FROM avatar_user_ownership_v1 ORDER BY user_id');
  await q("UPDATE clan_members SET clan_id=8 WHERE user_id=2");
  assert.deepEqual(await releaseDcHiHeeya(db,plan),{...result,replayed:true});
  assert.deepEqual(await q('SELECT * FROM avatar_user_ownership_v1 ORDER BY user_id'),originalOwnership);
  const owned=(await call(1,'avatar/catalog')).body.avatars.find(a=>a.code===DC_AVATAR.code);
  assert.equal(owned.owned,true);assert.equal(owned.expiresAt,result.expiresAt);
  assert.deepEqual(owned.effects,[{type:'COIN_GAIN_PERCENT',value:75},{type:'RAID_EXTRA_ENTRY',value:10}]);
  assert.equal((await call(3,'avatar/catalog')).body.avatars.find(a=>a.code===DC_AVATAR.code).owned,false);
  assert.equal((await call(3,'avatar/equip',{avatarCode:DC_AVATAR.code})).status,404);
  assert.equal((await call(1,'avatar/purchase',{avatarCode:DC_AVATAR.code,requestId:'dc-not-for-sale'})).status,404);
  assert.equal((await call(1,'avatar/equip',{avatarCode:DC_AVATAR.code})).status,200);
  const equipped=await api.equippedAvatarEffect(env,1);
  assert.deepEqual(equipped.effects,owned.effects);
  assert.equal(api.applyAvatarCoinGain(100,equipped).total,175);
  assert.equal(api.applyAvatarRaidEntryBonus(3,equipped).limit,13);
  for(const file of [equipped.lobbyImage,equipped.lobbyMobileImage,equipped.equipmentImage])assert.ok((await readFile(new URL('../'+file,import.meta.url))).length>0);
  await q('UPDATE avatar_user_ownership_v1 SET expires_at=sqlite_now() WHERE user_id=1 AND avatar_code=$1',[DC_AVATAR.code]);
  const expired=(await call(1,'avatar/catalog')).body.avatars.find(a=>a.code===DC_AVATAR.code);
  assert.equal(expired.owned,false);assert.equal(expired.equipped,false);
  assert.equal(await api.equippedAvatarEffect(env,1),null);
  assert.equal((await call(1,'avatar/equip',{avatarCode:DC_AVATAR.code})).status,404);
  assert.deepEqual(await q('SELECT * FROM users ORDER BY id'),usersBefore);
 }finally{await pg.close()}
});

test('a changed DC roster aborts without catalog, effects, ownership or receipt writes',async()=>{
 const {pg,db,plan,q}=await fixture();try{await q('UPDATE clan_members SET clan_id=8 WHERE user_id=2');await assert.rejects(releaseDcHiHeeya(db,plan),/recipients changed/);await assertAbsent(q);}finally{await pg.close()}
});
test('changed T1 options abort instead of silently copying stale values',async()=>{
 const {pg,db,plan,q}=await fixture();try{await q("UPDATE avatar_effect_options_v1 SET effect_value=5 WHERE avatar_code='T1_JOEUN' AND option_order=1");await assert.rejects(releaseDcHiHeeya(db,plan),/options changed/);await assertAbsent(q);}finally{await pg.close()}
});
test('an occupied serial is preserved and blocks registration and grants',async()=>{
 const {pg,db,plan,q}=await fixture();try{await q("UPDATE avatar_catalog_v1 SET serial='A-22' WHERE code='T1_JOEUN'");await assert.rejects(releaseDcHiHeeya(db,plan),/already exists/);await assertAbsent(q);assert.equal((await q("SELECT serial FROM avatar_catalog_v1 WHERE code='T1_JOEUN'"))[0].serial,'A-22');}finally{await pg.close()}
});
test('a recipient insert failure rolls back the new avatar and both copied effects',async()=>{
 const {pg,db,plan,q}=await fixture();try{await q("ALTER TABLE avatar_user_ownership_v1 ADD CONSTRAINT dc_failure CHECK(user_id<>2 OR avatar_code<>'DC_HI_HEEYA')");await assert.rejects(releaseDcHiHeeya(db,plan),/dc_failure/);await assertAbsent(q);}finally{await pg.close()}
});

test('dry run rolls back catalog, recipients, audit and receipt',async()=>{const {pg,db,plan,q}=await fixture();try{const r=await releaseDcHiHeeya(db,{...plan,dryRun:true});assert.equal(r.rolledBack,true);assert.equal(r.granted,2);await assertAbsent(q);assert.deepEqual(await q('SELECT * FROM admin_logs'),[]);}finally{await pg.close()}});
