import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
import {__postgresCompatTest} from '../functions/_postgres_d1_compat.js';
import {LOTTE_AVATAR,LOTTE_GRANT_KEY,LOTTE_EXPECTED_EFFECTS,releaseLotteAyoon} from '../scripts/ops/avatar-lotte-ayoon-release-20260924.mjs';
let fixtureId=0;
async function fixture(){
 const pg=new PGlite(),api=await import('../functions/_avatar.js?lotte-release-test='+fixtureId++);
 await pg.exec(`CREATE FUNCTION sqlite_now() RETURNS text LANGUAGE SQL STABLE AS $$SELECT to_char(timezone('UTC',CURRENT_TIMESTAMP),'YYYY-MM-DD HH24:MI:SS')$$;
  CREATE TABLE app_meta(key TEXT PRIMARY KEY,value TEXT,updated_at TEXT);
  CREATE TABLE users(id BIGINT PRIMARY KEY,nickname TEXT,role TEXT,coin BIGINT,status TEXT);
  INSERT INTO users VALUES(1,'Lotte master','USER',777,'ACTIVE'),(5209,'김아윤','USER',888,'ACTIVE'),(3,'Other clan','OWNER',999,'ACTIVE');
  CREATE TABLE clan_seasons(id BIGINT PRIMARY KEY,season_no INTEGER,phase TEXT,ends_at TEXT);
  INSERT INTO clan_seasons VALUES(5,2,'ACTIVE',to_char(timezone('UTC',CURRENT_TIMESTAMP)+interval '30 days','YYYY-MM-DD"T"HH24:MI:SS"Z"'));
  CREATE TABLE clan_organizations(id BIGINT PRIMARY KEY,name TEXT UNIQUE,is_active INTEGER);
  INSERT INTO clan_organizations VALUES(6,'롯데',1),(8,'Other',1);
  CREATE TABLE clan_members(season_id BIGINT,clan_id BIGINT,user_id BIGINT,member_role TEXT,PRIMARY KEY(season_id,user_id));
  INSERT INTO clan_members VALUES(5,6,1,'MASTER'),(5,6,5209,'MEMBER'),(5,8,3,'MEMBER');
  CREATE TABLE admin_logs(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,admin_id BIGINT,action_type TEXT,target_type TEXT,target_id TEXT,before_data TEXT,after_data TEXT);
  INSERT INTO app_meta VALUES('avatar_settings_v1','{"mode":"ON","shopEnabled":true,"version":3}',NULL);`);
 const client={async query(input,values){const r=await pg.query(typeof input==='string'?input:input.text,typeof input==='string'?values||[]:input.values||[]);return {...r,rowCount:r.affectedRows??r.rows.length}}};
 const db=new __postgresCompatTest.PostgresD1Database(client),env={DB:db};
 await api.ensureAvatarFoundation(env);
 await pg.exec("UPDATE avatar_catalog_v1 SET effect_type='COIN_GAIN_PERCENT',effect_value=75,is_active=1,is_public=1,version=3 WHERE code='T1_JOEUN'");
 await pg.query("DELETE FROM avatar_effect_options_v1 WHERE avatar_code='T1_JOEUN'");
 for(const effect of LOTTE_EXPECTED_EFFECTS)await pg.query("INSERT INTO avatar_effect_options_v1(avatar_code,option_order,effect_type,effect_value) VALUES('T1_JOEUN',$1,$2,$3)",[effect.option_order,effect.effect_type,effect.effect_value]);
 const expiry=(await pg.query('SELECT ends_at FROM clan_seasons WHERE id=5')).rows[0].ends_at;
 const plan={expectedSeasonId:5,expectedClanId:6,expectedRecipientIds:[1,5209],expectedSeasonEndsAt:expiry};
 const q=async(sql,values=[])=>(await pg.query(sql,values)).rows;
 const call=(id,path,body)=>api.handleAvatar({env,path,deps:{authenticate:async()=>({id,role:'USER'}),readBody:r=>r.json(),json:(body,status=200)=>({body,status})},request:new Request('https://qa.test/api/'+path,body?{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}:{})});
 return {pg,api,env,db,plan,q,call};
}
async function assertAbsent(q){
 assert.equal((await q('SELECT * FROM avatar_catalog_v1 WHERE code=$1',[LOTTE_AVATAR.code])).length,0);
 assert.equal((await q('SELECT * FROM avatar_effect_options_v1 WHERE avatar_code=$1',[LOTTE_AVATAR.code])).length,0);
 assert.equal((await q('SELECT * FROM avatar_user_ownership_v1 WHERE avatar_code=$1',[LOTTE_AVATAR.code])).length,0);
 assert.equal((await q('SELECT * FROM app_meta WHERE key=$1',[LOTTE_GRANT_KEY])).length,0);
}

test('Lotte members receive the same T1 options for exactly the remaining season; replay and expiry preserve the contract',async()=>{
 const {pg,api,env,db,plan,q,call}=await fixture();
 try{
  const catalogBefore=await q('SELECT * FROM avatar_catalog_v1 ORDER BY code'),effectsBefore=await q('SELECT * FROM avatar_effect_options_v1 ORDER BY avatar_code,option_order'),usersBefore=await q('SELECT * FROM users ORDER BY id');
  const result=await releaseLotteAyoon(db,plan);
  assert.equal(result.granted,2);assert.equal(result.seasonEndsAt,plan.expectedSeasonEndsAt);assert.deepEqual(result.effects,LOTTE_EXPECTED_EFFECTS);
  assert.deepEqual(result.recipients.map(r=>r.userId),[1,5209]);
  const utc=value=>Date.parse(value.replace(' ','T')+'Z');
  assert.equal(utc(result.expiresAt),Date.parse(plan.expectedSeasonEndsAt));
  assert.deepEqual(await q('SELECT * FROM avatar_user_loadout_v1'),[]);
  assert.deepEqual(await q('SELECT * FROM users ORDER BY id'),usersBefore);
  assert.deepEqual(await q('SELECT * FROM avatar_catalog_v1 WHERE code<>$1 ORDER BY code',[LOTTE_AVATAR.code]),catalogBefore);
  assert.deepEqual(await q('SELECT * FROM avatar_effect_options_v1 WHERE avatar_code<>$1 ORDER BY avatar_code,option_order',[LOTTE_AVATAR.code]),effectsBefore);
  const originalOwnership=await q('SELECT * FROM avatar_user_ownership_v1 ORDER BY user_id');
  await q("UPDATE clan_members SET clan_id=8 WHERE user_id=5209");
  assert.deepEqual(await releaseLotteAyoon(db,plan),{...result,replayed:true});
  assert.deepEqual(await q('SELECT * FROM avatar_user_ownership_v1 ORDER BY user_id'),originalOwnership);
  const owned=(await call(1,'avatar/catalog')).body.avatars.find(a=>a.code===LOTTE_AVATAR.code);
  assert.equal(owned.owned,true);assert.equal(owned.expiresAt,result.expiresAt);
  assert.deepEqual(owned.effects,[{type:'COIN_GAIN_PERCENT',value:75},{type:'RAID_EXTRA_ENTRY',value:10}]);
  assert.equal((await call(3,'avatar/catalog')).body.avatars.find(a=>a.code===LOTTE_AVATAR.code).owned,false);
  assert.equal((await call(3,'avatar/equip',{avatarCode:LOTTE_AVATAR.code})).status,404);
  assert.equal((await call(1,'avatar/purchase',{avatarCode:LOTTE_AVATAR.code,requestId:'lotte-not-for-sale'})).status,404);
  assert.equal((await call(1,'avatar/equip',{avatarCode:LOTTE_AVATAR.code})).status,200);
  const equipped=await api.equippedAvatarEffect(env,1);
  assert.deepEqual(equipped.effects,owned.effects);
  assert.equal(api.applyAvatarCoinGain(100,equipped).total,175);
  assert.equal(api.applyAvatarRaidEntryBonus(3,equipped).limit,13);
  for(const file of [equipped.lobbyImage,equipped.lobbyMobileImage,equipped.equipmentImage])assert.ok((await readFile(new URL('../'+file,import.meta.url))).length>0);
  await q('UPDATE avatar_user_ownership_v1 SET expires_at=sqlite_now() WHERE user_id=1 AND avatar_code=$1',[LOTTE_AVATAR.code]);
  const expired=(await call(1,'avatar/catalog')).body.avatars.find(a=>a.code===LOTTE_AVATAR.code);
  assert.equal(expired.owned,false);assert.equal(expired.equipped,false);
  assert.equal(await api.equippedAvatarEffect(env,1),null);
  assert.equal((await call(1,'avatar/equip',{avatarCode:LOTTE_AVATAR.code})).status,404);
  assert.deepEqual(await q('SELECT * FROM users ORDER BY id'),usersBefore);
 }finally{await pg.close()}
});

test('a changed Lotte roster aborts without catalog, effects, ownership or receipt writes',async()=>{
 const {pg,db,plan,q}=await fixture();try{await q('UPDATE clan_members SET clan_id=8 WHERE user_id=5209');await assert.rejects(releaseLotteAyoon(db,plan),/recipients changed/);await assertAbsent(q);}finally{await pg.close()}
});
test('changed T1 options abort instead of silently copying stale values',async()=>{
 const {pg,db,plan,q}=await fixture();try{await q("UPDATE avatar_effect_options_v1 SET effect_value=5 WHERE avatar_code='T1_JOEUN' AND option_order=1");await assert.rejects(releaseLotteAyoon(db,plan),/options changed/);await assertAbsent(q);}finally{await pg.close()}
});
test('an occupied serial is preserved and blocks registration and grants',async()=>{
 const {pg,db,plan,q}=await fixture();try{await q("UPDATE avatar_catalog_v1 SET serial='A-26' WHERE code='T1_JOEUN'");await assert.rejects(releaseLotteAyoon(db,plan),/already exists/);await assertAbsent(q);assert.equal((await q("SELECT serial FROM avatar_catalog_v1 WHERE code='T1_JOEUN'"))[0].serial,'A-26');}finally{await pg.close()}
});
test('a recipient insert failure rolls back the new avatar and both copied effects',async()=>{
 const {pg,db,plan,q}=await fixture();try{await q("ALTER TABLE avatar_user_ownership_v1 ADD CONSTRAINT lotte_failure CHECK(user_id<>5209 OR avatar_code<>'LOTTE_AYOON')");await assert.rejects(releaseLotteAyoon(db,plan),/lotte_failure/);await assertAbsent(q);}finally{await pg.close()}
});

test("a changed or expired season end aborts the complete grant",async()=>{for(const end of ["2000-01-01T00:00:00.000Z","2099-01-01T00:00:00.000Z"]){const {pg,db,plan,q}=await fixture();try{await q("UPDATE clan_seasons SET ends_at=$1",[end]);await assert.rejects(releaseLotteAyoon(db,plan),/end changed or expired/);await assertAbsent(q);}finally{await pg.close()}}});

test("audit failure rolls catalog, effects, ownership and receipt back together",async()=>{const {pg,db,plan,q}=await fixture();try{await q("ALTER TABLE admin_logs ADD CONSTRAINT audit_failure CHECK(admin_id<0)");await assert.rejects(releaseLotteAyoon(db,plan),/audit_failure/);await assertAbsent(q);}finally{await pg.close()}});
