import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
import {__postgresCompatTest} from '../functions/_postgres_d1_compat.js';
import {LG_AVATAR,LG_GRANT_KEY,LG_EXPECTED_EFFECTS,releaseLgHiHeeya} from '../scripts/ops/avatar-lg-hi-heeya-release-20260930.mjs';
let id=0;
async function fixture(){
 const pg=new PGlite(),api=await import('../functions/_avatar.js?lg-heeya-test='+id++);
 await pg.exec(`CREATE FUNCTION sqlite_now() RETURNS text LANGUAGE SQL STABLE AS $$SELECT to_char(timezone('UTC',CURRENT_TIMESTAMP),'YYYY-MM-DD HH24:MI:SS')$$;
 CREATE TABLE app_meta(key TEXT PRIMARY KEY,value TEXT,updated_at TEXT);
 CREATE TABLE admin_logs(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,admin_id BIGINT,action_type TEXT,target_type TEXT,target_id TEXT,before_data TEXT,after_data TEXT);
 CREATE TABLE users(id BIGINT PRIMARY KEY,nickname TEXT,role TEXT,coin BIGINT,status TEXT);
 INSERT INTO users VALUES(1,'owner','OWNER',777,'ACTIVE'),(2,'LG master','USER',888,'ACTIVE'),(3,'LG member','USER',999,'ACTIVE'),(4,'Other','USER',444,'ACTIVE');
 CREATE TABLE clan_seasons(id BIGINT PRIMARY KEY,season_no INTEGER,phase TEXT,ends_at TEXT);
 INSERT INTO clan_seasons VALUES(6,3,'ACTIVE','2099-10-11T13:00:00.000Z');
 CREATE TABLE clan_organizations(id BIGINT PRIMARY KEY,name TEXT UNIQUE,is_active INTEGER);
 INSERT INTO clan_organizations VALUES(5,'LG',1),(7,'Other',1);
 CREATE TABLE clan_members(season_id BIGINT,clan_id BIGINT,user_id BIGINT,member_role TEXT,PRIMARY KEY(season_id,user_id));
 INSERT INTO clan_members VALUES(6,5,2,'MASTER'),(6,5,3,'MEMBER'),(6,7,4,'MEMBER');
 INSERT INTO app_meta VALUES('avatar_settings_v1','{"mode":"ON","shopEnabled":true,"version":3}',NULL);`);
 const q=async(sql,values=[])=>(await pg.query(sql,values)).rows;
 const client={async query(input,values){const r=await pg.query(typeof input==='string'?input:input.text,typeof input==='string'?values||[]:input.values||[]);return {...r,rowCount:r.affectedRows??r.rows.length};}};
 const db=new __postgresCompatTest.PostgresD1Database(client),env={DB:db};await api.ensureAvatarFoundation(env);
 await q("INSERT INTO avatar_catalog_v1(code,serial,name,effect_type,effect_value,is_active,is_public,version) VALUES('FM_DIMWOOS','A-21','한복 디임2','DROP_RATE_PERCENT',30,1,1,3)");
 for(const e of LG_EXPECTED_EFFECTS)await q("INSERT INTO avatar_effect_options_v1(avatar_code,option_order,effect_type,effect_value) VALUES('FM_DIMWOOS',$1,$2,$3)",[e.option_order,e.effect_type,e.effect_value]);
 await q("INSERT INTO avatar_user_ownership_v1(user_id,avatar_code,source_type,expires_at) VALUES(2,'FM_DIMWOOS','ADMIN',NULL)");
 await q("INSERT INTO avatar_user_loadout_v1(user_id,avatar_code,updated_at) VALUES(2,'FM_DIMWOOS','2020-01-01 00:00:00')");
 const plan={expectedSeasonId:6,expectedClanId:5,expectedRecipientIds:[2,3],expectedSeasonEndsAt:'2099-10-11T13:00:00.000Z',expectedSourceVersion:3};
 const snapshot=async()=>Object.fromEntries(await Promise.all(['users','clan_members','avatar_catalog_v1','avatar_effect_options_v1','avatar_user_ownership_v1','avatar_user_loadout_v1','app_meta','admin_logs'].map(async name=>[name,await q('SELECT * FROM '+name+' ORDER BY 1,2')])));
 const call=(userId,path,body)=>api.handleAvatar({env,path,deps:{authenticate:async()=>({id:userId,role:'USER'}),readBody:r=>r.json(),json:(body,status=200)=>({body,status})},request:new Request('https://qa.test/api/'+path,body?{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}:{})});
 return {pg,q,db,api,env,plan,snapshot,call};
}
test('LG-only grant clones all four options to the exact season end; replay, equip and expiry are safe',async()=>{
 const f=await fixture();try{
  const before=await f.snapshot(),r=await releaseLgHiHeeya(f.db,f.plan),after=await f.snapshot();
  assert.equal(r.granted,2);assert.equal(r.expiresAt,'2099-10-11 13:00:00');assert.deepEqual(r.effects,LG_EXPECTED_EFFECTS);
  for(const name of ['users','clan_members','avatar_user_loadout_v1'])assert.deepEqual(after[name],before[name]);
  assert.deepEqual(after.avatar_catalog_v1.filter(a=>a.code!==LG_AVATAR.code),before.avatar_catalog_v1);
  assert.deepEqual(after.avatar_effect_options_v1.filter(a=>a.avatar_code!==LG_AVATAR.code),before.avatar_effect_options_v1);
  assert.deepEqual(after.avatar_user_ownership_v1.filter(a=>a.avatar_code!==LG_AVATAR.code),before.avatar_user_ownership_v1);
  assert.equal(after.admin_logs.length,1);
  assert.equal((await releaseLgHiHeeya(f.db,f.plan)).replayed,true);assert.deepEqual(await f.snapshot(),after);
  const avatar=(await f.call(2,'avatar/catalog')).body.avatars.find(a=>a.code===LG_AVATAR.code);
  assert.equal(avatar.owned,true);assert.equal(avatar.expiresAt,r.expiresAt);
  assert.deepEqual(avatar.effects,LG_EXPECTED_EFFECTS.map(e=>({type:e.effect_type,value:e.effect_value})));
  assert.equal((await f.call(4,'avatar/equip',{avatarCode:LG_AVATAR.code})).status,404);
  assert.equal((await f.call(2,'avatar/purchase',{avatarCode:LG_AVATAR.code,requestId:'not-for-sale-lg'})).status,404);
  assert.equal((await f.call(2,'avatar/equip',{avatarCode:LG_AVATAR.code})).status,200);
  const equipped=await f.api.equippedAvatarEffect(f.env,2);assert.deepEqual(equipped.effects,avatar.effects);
  assert.equal(f.api.applyAvatarCoinGain(100,equipped).total,200);assert.equal(f.api.applyAvatarRaidEntryBonus(3,equipped).limit,13);
  for(const file of [equipped.lobbyImage,equipped.lobbyMobileImage,equipped.equipmentImage])assert.ok((await readFile(new URL('../'+file,import.meta.url))).length);
  await f.q('UPDATE avatar_user_ownership_v1 SET expires_at=sqlite_now() WHERE avatar_code=$1',[LG_AVATAR.code]);
  assert.equal(await f.api.equippedAvatarEffect(f.env,2),null);assert.equal((await f.call(2,'avatar/equip',{avatarCode:LG_AVATAR.code})).status,404);
 }finally{await f.pg.close();}
});
for(const [kind,sql] of [
 ['changed roster','UPDATE clan_members SET clan_id=7 WHERE user_id=3'],
 ['changed source option',"UPDATE avatar_effect_options_v1 SET effect_value=5 WHERE avatar_code='FM_DIMWOOS' AND option_order=1"],
 ['changed season end',"UPDATE clan_seasons SET ends_at='2099-10-12T13:00:00.000Z' WHERE id=6"],
 ['serial collision',"UPDATE avatar_catalog_v1 SET serial='A-27' WHERE code='FM_DIMWOOS'"],
 ['partial grant failure',"ALTER TABLE avatar_user_ownership_v1 ADD CONSTRAINT reject_lg CHECK(user_id<>3 OR avatar_code<>'LG_HI_HEEYA')"],
 ['audit failure',"ALTER TABLE admin_logs ADD CONSTRAINT reject_audit CHECK(action_type='REJECT')"]
])test(kind+' rolls back catalog, options, ownership and receipt together',async()=>{
 const f=await fixture();try{await f.q(sql);const before=await f.snapshot();await assert.rejects(releaseLgHiHeeya(f.db,f.plan));assert.deepEqual(await f.snapshot(),before);}finally{await f.pg.close();}
});
test('dry run performs and rolls back the complete operation',async()=>{const f=await fixture();try{const before=await f.snapshot(),r=await releaseLgHiHeeya(f.db,{...f.plan,dryRun:true});assert.equal(r.rolledBack,true);assert.equal(r.granted,2);assert.deepEqual(await f.snapshot(),before);}finally{await f.pg.close();}});
test('the live loader ships the LG-only full-body layout and refreshed resources',async()=>{
 const read=name=>readFile(new URL('../'+name,import.meta.url),'utf8'),[renderer,css,app,index]=await Promise.all(['js/character-loadout-v2.js','css/character-loadout-v2.css','js/app.js','index.html'].map(read));
 assert.ok(renderer.includes('data-avatar-code='));
 assert.match(css,/data-avatar-code='LG_HI_HEEYA'[\s\S]*?bottom: 15%/);
 assert.match(app,/character-loadout-v2\.css[^']*lgHeeya=20260930/);
 assert.match(app,/character-loadout-v2\.js[^']*lgHeeya=20260930/);
 assert.match(index,/js\/app\.js[^"]*lgHeeya=20260930/);
});

