import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
import {__postgresCompatTest} from '../functions/_postgres_d1_compat.js';
import {LOTTE_UNIFORM_CATALOGS as catalogs,LOTTE_UNIFORM_GRANT_KEY as key,EXPECTED_EFFECTS as effects,releaseLotteUniforms} from '../scripts/ops/avatar-lotte-joeun-bongsoon-release-20260930.mjs';
let fixtureId=0;
const codes=catalogs.map(a=>a.code);
async function fixture(){
 const pg=new PGlite(),api=await import('../functions/_avatar.js?lotte-uniform-test='+fixtureId++);
 await pg.exec(`CREATE FUNCTION sqlite_now() RETURNS text LANGUAGE SQL STABLE AS $$SELECT to_char(timezone('UTC',CURRENT_TIMESTAMP),'YYYY-MM-DD HH24:MI:SS')$$;
 CREATE TABLE app_meta(key TEXT PRIMARY KEY,value TEXT,updated_at TEXT);
 CREATE TABLE users(id BIGINT PRIMARY KEY,nickname TEXT,role TEXT,coin BIGINT,status TEXT);
 INSERT INTO users VALUES(1,'Lotte master','USER',777,'ACTIVE'),(2,'Lotte member','USER',888,'ACTIVE'),(3,'Other clan','OWNER',999,'ACTIVE');
 CREATE TABLE clan_seasons(id BIGINT PRIMARY KEY,season_no INTEGER,phase TEXT,ends_at TEXT);
 INSERT INTO clan_seasons VALUES(6,3,'ACTIVE',to_char(timezone('UTC',CURRENT_TIMESTAMP)+interval '30 days','YYYY-MM-DD"T"HH24:MI:SS"Z"'));
 CREATE TABLE clan_organizations(id BIGINT PRIMARY KEY,name TEXT UNIQUE,is_active INTEGER);
 INSERT INTO clan_organizations VALUES(6,'롯데',1),(8,'Other',1);
 CREATE TABLE clan_members(season_id BIGINT,clan_id BIGINT,user_id BIGINT,member_role TEXT,PRIMARY KEY(season_id,user_id));
 INSERT INTO clan_members VALUES(6,6,1,'MASTER'),(6,6,2,'MEMBER'),(6,8,3,'MEMBER');
 CREATE TABLE admin_logs(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,admin_id BIGINT,action_type TEXT,target_type TEXT,target_id TEXT,before_data TEXT,after_data TEXT);
 INSERT INTO app_meta VALUES('avatar_settings_v1','{"mode":"ON","shopEnabled":true,"version":3}',NULL);`);
 const client={async query(input,values){const r=await pg.query(typeof input==='string'?input:input.text,typeof input==='string'?values||[]:input.values||[]);return {...r,rowCount:r.affectedRows??r.rows.length}}};
 const db=new __postgresCompatTest.PostgresD1Database(client),env={DB:db};
 await api.ensureAvatarFoundation(env);
 const source={...catalogs[0],code:'FM_DIMWOOS',serial:'A-21',name:'한복 디임2'};
 await pg.query('INSERT INTO avatar_catalog_v1('+Object.keys(source).join(',')+',version) VALUES('+Object.keys(source).map((_,i)=>'$'+(i+1)).join(',')+',3)',Object.values(source));
 for(const e of effects)await pg.query("INSERT INTO avatar_effect_options_v1(avatar_code,option_order,effect_type,effect_value) VALUES('FM_DIMWOOS',$1,$2,$3)",[e.option_order,e.effect_type,e.effect_value]);
 const q=async(sql,values=[])=>(await pg.query(sql,values)).rows;
 const plan={expectedSeasonId:6,expectedClanId:6,expectedRecipientIds:[1,2],expectedSeasonEndsAt:(await q('SELECT ends_at FROM clan_seasons WHERE id=6'))[0].ends_at,expectedSourceVersion:3};
 const call=(id,path,body)=>api.handleAvatar({env,path,deps:{authenticate:async()=>({id,role:'USER'}),requirePermission:async()=>({id:3,role:'OWNER'}),readBody:r=>r.json(),json:(body,status=200)=>({body,status})},request:new Request('https://qa.test/api/'+path,body?{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}:{})});
 return {pg,api,env,db,plan,q,call};
}
async function absent(q){
 for(const table of ['avatar_catalog_v1','avatar_effect_options_v1','avatar_user_ownership_v1']){
  const field=table==='avatar_catalog_v1'?'code':'avatar_code';
  assert.equal((await q('SELECT * FROM '+table+' WHERE '+field+'=ANY($1::text[])',[codes])).length,0);
 }
 assert.equal((await q('SELECT * FROM app_meta WHERE key=$1',[key])).length,0);
 assert.equal((await q('SELECT * FROM admin_logs')).length,0);
}
test('both Lotte uniforms inherit all Hanbok Diim2 options, grant only the current clan until season end, and preserve replay/expiry/equipment contracts',async()=>{
 const {pg,api,env,db,plan,q,call}=await fixture();
 try{
  const before=await q('SELECT * FROM avatar_catalog_v1 ORDER BY code'),beforeEffects=await q('SELECT * FROM avatar_effect_options_v1 ORDER BY avatar_code,option_order'),users=await q('SELECT * FROM users ORDER BY id');
  const result=await releaseLotteUniforms(db,plan);
  assert.equal(result.recipientCount,2);assert.equal(result.totalGranted,4);assert.deepEqual(result.effects,effects);
  assert.equal(Date.parse(result.expiresAt.replace(' ','T')+'Z'),Date.parse(plan.expectedSeasonEndsAt));
  assert.deepEqual(await q('SELECT * FROM avatar_user_loadout_v1'),[]);
  assert.deepEqual(await q('SELECT * FROM users ORDER BY id'),users);
  assert.deepEqual(await q('SELECT * FROM avatar_catalog_v1 WHERE NOT(code=ANY($1::text[])) ORDER BY code',[codes]),before);
  assert.deepEqual(await q('SELECT * FROM avatar_effect_options_v1 WHERE NOT(avatar_code=ANY($1::text[])) ORDER BY avatar_code,option_order',[codes]),beforeEffects);
  const ownership=await q('SELECT * FROM avatar_user_ownership_v1 ORDER BY user_id,avatar_code');
  await q('UPDATE clan_members SET clan_id=8 WHERE user_id=2');
  await q("UPDATE avatar_catalog_v1 SET description='CMS edited' WHERE code=$1",[codes[0]]);
  assert.deepEqual(await releaseLotteUniforms(db,plan),{...result,replayed:true});
  assert.deepEqual(await q('SELECT * FROM avatar_user_ownership_v1 ORDER BY user_id,avatar_code'),ownership);
  assert.equal((await q('SELECT description FROM avatar_catalog_v1 WHERE code=$1',[codes[0]]))[0].description,'CMS edited');
  assert.equal((await q('SELECT * FROM admin_logs')).length,1);
  const cms=(await call(3,'admin/avatars')).body.avatars;
  for(let i=0;i<codes.length;i++){
   const avatar=cms.find(a=>a.code===codes[i]);assert.ok(avatar.active&&avatar.public&&!avatar.saleEnabled);
   assert.equal(avatar.serial,catalogs[i].serial);assert.equal(avatar.acquisitionType,'EVENT');
   const owned=(await call(i+1,'avatar/catalog')).body.avatars.find(a=>a.code===codes[i]);
   assert.equal(owned.owned,true);assert.equal(owned.expiresAt,result.expiresAt);
   assert.deepEqual(owned.effects,effects.map(e=>({type:e.effect_type,value:e.effect_value})));
   assert.equal((await call(3,'avatar/equip',{avatarCode:codes[i]})).status,404);
   assert.equal((await call(i+1,'avatar/purchase',{avatarCode:codes[i],requestId:'not-for-sale-'+i})).status,404);
   assert.equal((await call(i+1,'avatar/equip',{avatarCode:codes[i]})).status,200);
   const equipped=await api.equippedAvatarEffect(env,i+1);
   assert.equal(equipped.name,catalogs[i].name);assert.deepEqual(equipped.effects,owned.effects);
   assert.equal(api.applyAvatarCoinGain(100,equipped).total,200);assert.equal(api.applyAvatarRaidEntryBonus(3,equipped).limit,13);
   for(const file of [equipped.lobbyImage,equipped.lobbyMobileImage,equipped.equipmentImage])assert.ok((await readFile(new URL('../'+file,import.meta.url))).length>0);
   await q('UPDATE avatar_user_ownership_v1 SET expires_at=sqlite_now() WHERE user_id=$1 AND avatar_code=$2',[i+1,codes[i]]);
   assert.equal(await api.equippedAvatarEffect(env,i+1),null);
   assert.equal((await call(i+1,'avatar/equip',{avatarCode:codes[i]})).status,404);
  }
  assert.deepEqual(await q('SELECT * FROM users ORDER BY id'),users);
 }finally{await pg.close();}
});
test('changed membership or source options stop both registrations and all grants',async()=>{
 for(const mutation of ["UPDATE clan_members SET clan_id=8 WHERE user_id=2","UPDATE avatar_effect_options_v1 SET effect_value=1 WHERE avatar_code='FM_DIMWOOS' AND option_order=1","UPDATE avatar_catalog_v1 SET version=4 WHERE code='FM_DIMWOOS'"]){
  const {pg,db,plan,q}=await fixture();try{await q(mutation);await assert.rejects(releaseLotteUniforms(db,plan),/changed/);await absent(q);}finally{await pg.close();}
 }
});
test('changed or expired season refuses stale expiration without writing',async()=>{
 for(const end of ['2000-01-01T00:00:00Z','2099-01-01T00:00:00Z']){
  const {pg,db,plan,q}=await fixture();try{await q('UPDATE clan_seasons SET ends_at=$1',[end]);await assert.rejects(releaseLotteUniforms(db,plan),/end changed or expired/);await absent(q);}finally{await pg.close();}
 }
});
test('occupied serial blocks new avatars and preserves existing catalog',async()=>{
 const {pg,db,plan,q}=await fixture();try{await q("UPDATE avatar_catalog_v1 SET serial='A-28' WHERE code='FM_DIMWOOS'");await assert.rejects(releaseLotteUniforms(db,plan),/already exists/);await absent(q);}finally{await pg.close();}
});
test('a failure in the second avatar grant rolls back the first avatar and every ownership row',async()=>{
 const {pg,db,plan,q}=await fixture();try{await q("ALTER TABLE avatar_user_ownership_v1 ADD CONSTRAINT second_avatar_failure CHECK(avatar_code<>'LOTTE_NAMU_BONGSOON' OR user_id<>2)");await assert.rejects(releaseLotteUniforms(db,plan),/second_avatar_failure/);await absent(q);}finally{await pg.close();}
});
test('audit failure rolls back both avatars, options, grants and receipt',async()=>{
 const {pg,db,plan,q}=await fixture();try{await q('ALTER TABLE admin_logs ADD CONSTRAINT audit_failure CHECK(admin_id<0)');await assert.rejects(releaseLotteUniforms(db,plan),/audit_failure/);await absent(q);}finally{await pg.close();}
});

