import test from 'node:test';
import assert from 'node:assert/strict';
import {PGlite} from '@electric-sql/pglite';
import {apply,verify,CODE} from '../scripts/ops/bini-gift-transfer-20261003.mjs';

async function fixture(){
 const db=new PGlite();
 await db.exec(`
 CREATE TABLE users(id BIGINT PRIMARY KEY,nickname TEXT,status TEXT,role TEXT,coin BIGINT DEFAULT 123);
 INSERT INTO users(id,nickname,status,role) VALUES(1,'관리자','ACTIVE','OWNER'),(4595,'비니','ACTIVE','USER'),(5504,'비_니','ACTIVE','USER');
 CREATE TABLE inventory_items(code TEXT PRIMARY KEY,name TEXT,is_active BIGINT);
 INSERT INTO inventory_items VALUES('PINGDU_THANKS_GIFT_BOX','핑두의 감사 선물',1);
 CREATE TABLE cnine_user_inventory(user_id BIGINT,item_code TEXT,quantity BIGINT,unseen_quantity BIGINT,created_at TEXT,updated_at TEXT,PRIMARY KEY(user_id,item_code));
 INSERT INTO cnine_user_inventory VALUES(4595,'PINGDU_THANKS_GIFT_BOX',1,0,'original','original'),(5504,'PINGDU_THANKS_GIFT_BOX',0,0,'original','original'),(4595,'MASTER_STAR',999,3,'original','original');
 CREATE TABLE user_messages(id BIGINT PRIMARY KEY,user_id BIGINT,title TEXT,campaign_key TEXT);
 INSERT INTO user_messages VALUES(182636,4595,'희야방 사은품','heeya-room-thanks-gift-20261003-v1');
 CREATE TABLE user_message_rewards(id BIGINT PRIMARY KEY,message_id BIGINT,user_id BIGINT,reward_type TEXT,reward_amount BIGINT,claimed_at TEXT);
 INSERT INTO user_message_rewards VALUES(179198,182636,4595,'PINGDU_THANKS_GIFT_BOX',1,'2026-10-03 12:44:56');
 CREATE TABLE inventory_logs(id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 54206183) PRIMARY KEY,user_id BIGINT,item_code TEXT,change_amount BIGINT,balance_after BIGINT,reason TEXT,reference_type TEXT,reference_id TEXT,admin_id BIGINT,created_at TEXT);
 INSERT INTO inventory_logs VALUES(54206182,4595,'PINGDU_THANKS_GIFT_BOX',1,1,'MESSAGE_REWARD','USER_MESSAGE','182636',NULL,'original');
 CREATE TABLE joint_operations_v1(request_id TEXT PRIMARY KEY,user_id BIGINT,kind TEXT,status TEXT);
 CREATE TABLE admin_logs(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,admin_id BIGINT,action_type TEXT,target_type TEXT,target_id TEXT,before_data TEXT,after_data TEXT,created_at TEXT);
 CREATE TABLE app_meta(key TEXT PRIMARY KEY,value TEXT,updated_at TEXT);
 CREATE TABLE user_mutation_locks_v1520(user_id BIGINT PRIMARY KEY,token TEXT,action_path TEXT,lease_until_ms BIGINT,updated_at TEXT);
 `);
 return {db,client:{query:(sql,args=[])=>db.query(sql,args)}};
}
async function snapshot(db){
 const state={};
 for(const table of ['users','cnine_user_inventory','user_messages','user_message_rewards','inventory_logs','admin_logs','app_meta','user_mutation_locks_v1520','joint_operations_v1'])state[table]=(await db.query(`SELECT * FROM ${table} ORDER BY 1,2`)).rows;
 return state;
}

test('moves exactly one unopened gift, preserves other assets/history and replays without regranting even after opening',async()=>{
 const {db,client}=await fixture();try{
  const before=await snapshot(db);
  await apply(client,{dryRun:true});assert.deepEqual(await snapshot(db),before);
  const receipt=await apply(client);assert.equal(receipt.sourceAfter,0);assert.equal(receipt.destinationAfter,1);
  assert.equal((await verify(client)).verified,true);
  const after=await snapshot(db);
  for(const table of ['users','user_messages','user_message_rewards','joint_operations_v1'])assert.deepEqual(after[table],before[table]);
  assert.deepEqual(after.cnine_user_inventory.filter(x=>x.item_code!==CODE),before.cnine_user_inventory.filter(x=>x.item_code!==CODE));
  assert.deepEqual(after.inventory_logs[0],before.inventory_logs[0]);assert.equal(after.inventory_logs.length,3);
  assert.equal(after.admin_logs.length,1);assert.equal(after.user_mutation_locks_v1520.length,0);
  await db.exec("UPDATE cnine_user_inventory SET quantity=0,unseen_quantity=0 WHERE user_id=5504 AND item_code='PINGDU_THANKS_GIFT_BOX'");
  const opened=await snapshot(db);assert.equal((await apply(client)).replayed,true);assert.deepEqual(await snapshot(db),opened);
  assert.equal((await verify(client)).verified,true);
 }finally{await db.close();}
});

test('destination credit failure and late audit failure each roll back debit, credit and ledgers together',async()=>{
 const {db,client}=await fixture();try{
  await db.exec('ALTER TABLE cnine_user_inventory ADD CONSTRAINT fail_credit CHECK(user_id<>5504 OR quantity=0)');
  let before=await snapshot(db);await assert.rejects(apply(client),/fail_credit/);assert.deepEqual(await snapshot(db),before);
  await db.exec('ALTER TABLE cnine_user_inventory DROP CONSTRAINT fail_credit; ALTER TABLE admin_logs ADD CONSTRAINT fail_audit CHECK(false)');
  before=await snapshot(db);await assert.rejects(apply(client),/fail_audit/);assert.deepEqual(await snapshot(db),before);
 }finally{await db.close();}
});

test('changed identity, consumed gift and in-progress operations stop the transfer without side effects',async()=>{
 const {db,client}=await fixture();try{
  const rejected=async pattern=>{const before=await snapshot(db);await assert.rejects(apply(client),pattern);assert.deepEqual(await snapshot(db),before);};
  await db.exec("UPDATE users SET nickname='비니2' WHERE id=4595");await rejected(/identity changed/);
  await db.exec("UPDATE users SET nickname='비니' WHERE id=4595; UPDATE cnine_user_inventory SET quantity=0 WHERE user_id=4595 AND item_code='PINGDU_THANKS_GIFT_BOX'");await rejected(/no longer available/);
  await db.exec("UPDATE cnine_user_inventory SET quantity=1 WHERE user_id=4595 AND item_code='PINGDU_THANKS_GIFT_BOX'; INSERT INTO joint_operations_v1 VALUES('opening',4595,'PINGDU_THANKS_GIFT_OPEN','PENDING')");await rejected(/Gift operation in progress/);
  await db.exec("DELETE FROM joint_operations_v1; INSERT INTO user_mutation_locks_v1520 VALUES(5504,'other','other',9999999999999,'original')");await rejected(/Account operation in progress/);
  await db.exec("DELETE FROM user_mutation_locks_v1520; INSERT INTO inventory_logs(user_id,item_code,change_amount,balance_after) VALUES(4595,'PINGDU_THANKS_GIFT_BOX',-1,0)");await rejected(/unopened gift changed/);
 }finally{await db.close();}
});
