import test from 'node:test';
import assert from 'node:assert/strict';
import {PGlite} from '@electric-sql/pglite';
import {grantBongsoonRecruitmentGift,TARGETS,INITIALLY_UNPAID,ITEM_CODE,ITEM_NAME,PLAN_HASH} from '../scripts/ops/bongsoon-recruitment-gift-20261002.mjs';

async function fixture(t){
 const db=new PGlite();t.after(()=>db.close());
 await db.exec(`CREATE TABLE users(id BIGINT PRIMARY KEY,nickname TEXT,role TEXT,status TEXT,coin BIGINT DEFAULT 123);
 INSERT INTO users VALUES(1,'관리자','OWNER','ACTIVE',123);
 CREATE TABLE user_second_verifications(user_id BIGINT,provider TEXT,provider_user_id TEXT);
 CREATE TABLE inventory_items(code TEXT PRIMARY KEY,name TEXT,is_active BIGINT);
 CREATE TABLE cnine_user_inventory(user_id BIGINT,item_code TEXT,quantity BIGINT,unseen_quantity BIGINT,created_at TEXT,updated_at TEXT,PRIMARY KEY(user_id,item_code));
 CREATE TABLE inventory_logs(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id BIGINT,item_code TEXT,change_amount BIGINT,balance_after BIGINT,reason TEXT,reference_type TEXT,reference_id TEXT,admin_id BIGINT,created_at TEXT);
 CREATE TABLE admin_logs(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,admin_id BIGINT,action_type TEXT,target_type TEXT,target_id TEXT,before_data TEXT,after_data TEXT,created_at TEXT);
 CREATE TABLE user_message_rewards(user_id BIGINT,message_id BIGINT,reward_type TEXT);
 CREATE TABLE app_meta(key TEXT PRIMARY KEY,value TEXT,updated_at TEXT);
 INSERT INTO cnine_user_inventory VALUES(1,'RECRUITMENT_GIFT_BOX',7,0,'original','original'),(71,'MASTER_STAR',900,3,'original','original');`);
 for(const target of TARGETS){
  await db.query("INSERT INTO users VALUES($1,$2,'USER','ACTIVE',123)",[target.userId,target.nickname]);
  await db.query("INSERT INTO user_second_verifications VALUES($1,'PLAYDK',$2)",[target.userId,target.playdkId]);
  for(const id of target.priorGrantIds)await db.query("INSERT INTO inventory_logs(id,user_id,item_code,change_amount,balance_after,reference_id) VALUES($1,$2,$3,1,1,'earlier-grant')",[id,target.userId,ITEM_CODE]);
  if(target.existingOnceMarker)await db.query("INSERT INTO app_meta VALUES($1,$2,'original')",['ops:recruitment-gift-once:user:'+target.userId+':v1',JSON.stringify({status:'COMPLETED',userId:target.userId,itemCode:ITEM_CODE,operationKey:'earlier-operation'})]);
 }
 await db.query('INSERT INTO inventory_items VALUES($1,$2,1)',[ITEM_CODE,ITEM_NAME]);
 const snapshot=async()=>{const out={};for(const table of ['users','cnine_user_inventory','inventory_logs','admin_logs','app_meta'])out[table]=(await db.query('SELECT * FROM '+table+' ORDER BY 1,2')).rows;return out;};
 return {db,snapshot,grant:options=>grantBongsoonRecruitmentGift(db,{expectedPlanHash:PLAN_HASH,...options})};
}

test('ten unpaid accounts receive one; 41 previously paid/consumed accounts and unrelated balances stay unchanged; dry-run and retry are idempotent',async t=>{
 const f=await fixture(t),before=await f.snapshot();assert.equal(INITIALLY_UNPAID.length,10);
 assert.equal((await f.grant({dryRun:true})).verification.granted,10);assert.deepEqual(await f.snapshot(),before);
 const applied=await f.grant(),after=await f.snapshot();assert.equal(applied.verification.granted,10);assert.equal(applied.verification.skipped,41);assert.equal(applied.receipt.held.length,4);
 assert.ok(applied.receipt.allocations.every(x=>x.after.quantity==='1'&&x.after.unseenQuantity==='1'));assert.deepEqual(after.users,before.users);
 assert.deepEqual(after.cnine_user_inventory.filter(x=>x.item_code!==ITEM_CODE||Number(x.user_id)===1),before.cnine_user_inventory);
 for(const row of before.app_meta)assert.deepEqual(after.app_meta.find(x=>x.key===row.key),row);
 assert.ok(!after.cnine_user_inventory.some(x=>applied.receipt.skipped.some(s=>s.userId===Number(x.user_id))&&x.item_code===ITEM_CODE));
 assert.equal((await f.grant()).replayed,true);assert.deepEqual(await f.snapshot(),after);
});

test('grants, unclaimed mail and owned stock appearing after inspection are excluded before crediting',async t=>{
 const f=await fixture(t),[mail,prior,owned]=INITIALLY_UNPAID;
 await f.db.query('INSERT INTO user_message_rewards VALUES($1,1,$2)',[mail.userId,ITEM_CODE]);
 await f.db.query("INSERT INTO inventory_logs(user_id,item_code,change_amount,balance_after,reference_id) VALUES($1,$2,1,1,'another-admin-grant')",[prior.userId,ITEM_CODE]);
 await f.db.query("INSERT INTO cnine_user_inventory VALUES($1,$2,1,0,'original','original')",[owned.userId,ITEM_CODE]);
 const result=await f.grant();assert.equal(result.verification.granted,7);assert.equal(result.verification.skipped,44);
 assert.ok([mail,prior,owned].every(x=>result.receipt.skipped.some(s=>s.userId===x.userId)));
});

test('audit failure rolls back all accounts and once markers, and identity mismatch blocks the operation',async t=>{
 const f=await fixture(t);await f.db.exec('ALTER TABLE admin_logs ADD CONSTRAINT forced_failure CHECK(false)');const before=await f.snapshot();
 await assert.rejects(f.grant(),/forced_failure/);assert.deepEqual(await f.snapshot(),before);
 await f.db.exec('ALTER TABLE admin_logs DROP CONSTRAINT forced_failure');
 await f.db.query("UPDATE users SET nickname='변경된계정' WHERE id=$1",[INITIALLY_UNPAID[0].userId]);const changed=await f.snapshot();
 await assert.rejects(f.grant(),/AssertionError/);assert.deepEqual(await f.snapshot(),changed);
 await f.db.query('UPDATE users SET nickname=$2 WHERE id=$1',[INITIALLY_UNPAID[0].userId,INITIALLY_UNPAID[0].nickname]);
 assert.equal((await f.grant()).verification.granted,10);assert.equal((await f.grant()).replayed,true);
});
