import test from 'node:test';
import assert from 'node:assert/strict';
import {PGlite} from '@electric-sql/pglite';
import {grantBongsoonSuitCores,OPERATION_KEY,TARGET,GIFTS} from '../scripts/ops/bongsoon-suit-cores-20261007.mjs';

async function fixture(){
 const db=new PGlite();
 await db.exec(`CREATE TABLE users(id BIGINT PRIMARY KEY,nickname TEXT,role TEXT,status TEXT,coin BIGINT DEFAULT 123,card_shards BIGINT DEFAULT 456,magic_crystals BIGINT DEFAULT 789);
  INSERT INTO users(id,nickname,role,status) VALUES(1,'관리자','OWNER','ACTIVE'),(5426,'나무늘봉순','USER','ACTIVE'),(66,'다른 계정','USER','ACTIVE');
  CREATE TABLE inventory_items(code TEXT PRIMARY KEY,name TEXT,is_active BIGINT);
  CREATE TABLE cnine_user_inventory(user_id BIGINT,item_code TEXT,quantity BIGINT,unseen_quantity BIGINT,created_at TEXT,updated_at TEXT,PRIMARY KEY(user_id,item_code));
  CREATE TABLE inventory_logs(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id BIGINT,item_code TEXT,change_amount BIGINT,balance_after BIGINT,reason TEXT,reference_type TEXT,reference_id TEXT,admin_id BIGINT,created_at TEXT);
  CREATE TABLE admin_logs(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,admin_id BIGINT,action_type TEXT,target_type TEXT,target_id TEXT,before_data TEXT,after_data TEXT,created_at TEXT);
  CREATE TABLE user_skill_chip_loadout_v2046(user_id BIGINT,slot_no BIGINT,item_code TEXT,updated_at TEXT,PRIMARY KEY(user_id,slot_no));
  INSERT INTO user_skill_chip_loadout_v2046 VALUES(5426,1,'SKILL_CHIP_ROCKET_LAUNCHER','original');
  CREATE TABLE app_meta(key TEXT PRIMARY KEY,value TEXT,updated_at TEXT);
  INSERT INTO cnine_user_inventory VALUES(5426,'EMPEROR_ENERGY',12,2,'original','original'),(5426,'MASTER_STAR',900,5,'original','original'),(66,'SKILL_CHIP_OCTA_SEEKER',7,1,'original','original');`);
 for(const gift of GIFTS)await db.query('INSERT INTO inventory_items VALUES($1,$2,1)',[gift.code,gift.name]);
 return {db,client:{async query(sql,args=[]){const r=await db.query(sql,args);return {...r,rowCount:r.affectedRows??r.rows.length};}}};
}
async function snapshot(db){const result={};for(const table of ['users','inventory_items','cnine_user_inventory','inventory_logs','admin_logs','app_meta','user_skill_chip_loadout_v2046'])result[table]=(await db.query(`SELECT * FROM ${table} ORDER BY 1,2`)).rows;return result;}


test('two requested cores add exact amounts with atomic rollback and duplicate retry protection',async()=>{
 const {db,client}=await fixture();try{
  const before=await snapshot(db);const dry=await grantBongsoonSuitCores(client,{dryRun:true});assert.equal(dry.dryRun,true);assert.deepEqual(await snapshot(db),before);
  const result=await grantBongsoonSuitCores(client),after=await snapshot(db);assert.equal(result.verification.verified,true);
  assert.deepEqual(result.receipt.allocations.map(x=>[x.code,x.after.quantity]),[['SUIT_CORE_4','20'],['SUIT_CORE_5','10']]);
  const unrelated=r=>Number(r.user_id)!==5426||!GIFTS.some(g=>g.code===r.item_code);
  assert.deepEqual(after.cnine_user_inventory.filter(unrelated),before.cnine_user_inventory.filter(unrelated));
  for(const key of ['users','inventory_items','user_skill_chip_loadout_v2046'])assert.deepEqual(after[key],before[key]);
  assert.equal(after.inventory_logs.length,2);assert.equal(after.admin_logs.length,1);assert.equal(after.app_meta.length,1);
  assert.equal((await grantBongsoonSuitCores(client)).replayed,true);assert.deepEqual(await snapshot(db),after);
 }finally{await db.close();}
});
test('failure on second material log or receipt rolls back both grants and allows one retry',async()=>{
 const {db,client}=await fixture();try{
  for(const [table,constraint] of [['inventory_logs',"item_code<>'SUIT_CORE_5'"],['app_meta','false']]){
   await db.exec(`ALTER TABLE ${table} ADD CONSTRAINT forced_failure CHECK(${constraint})`);const before=await snapshot(db);
   await assert.rejects(grantBongsoonSuitCores(client),/forced_failure/);assert.deepEqual(await snapshot(db),before);await db.exec(`ALTER TABLE ${table} DROP CONSTRAINT forced_failure`);
  }
  assert.equal((await grantBongsoonSuitCores(client)).verification.verified,true);
 }finally{await db.close();}
});
test('ambiguous account fails before any allocation',async()=>{
 const {db,client}=await fixture();try{
  await db.exec("INSERT INTO users(id,nickname,role,status) VALUES(5427,'나무늘 봉순','USER','ACTIVE')");const before=await snapshot(db);
  await assert.rejects(grantBongsoonSuitCores(client),/Exactly one/);assert.deepEqual(await snapshot(db),before);
 }finally{await db.close();}
});

test('existing core inventory increases by 20 while absent core 5 is created once',async()=>{
 const {db,client}=await fixture();try{
  await db.exec("INSERT INTO cnine_user_inventory VALUES(5426,'SUIT_CORE_4',1,0,'original','original')");
  const result=await grantBongsoonSuitCores(client);
  assert.deepEqual(result.receipt.allocations[0].before,{quantity:'1',unseenQuantity:'0'});
  assert.deepEqual(result.receipt.allocations[0].after,{quantity:'21',unseenQuantity:'20'});
  const after=await snapshot(db);assert.equal((await grantBongsoonSuitCores(client)).replayed,true);assert.deepEqual(await snapshot(db),after);
 }finally{await db.close();}
});
