import test from 'node:test';import assert from 'node:assert/strict';
import {PGlite} from '@electric-sql/pglite';
import {BOREAS,registerBoreas,verifyBoreas} from '../scripts/ops/boreas-omega-vehicle-20260917.mjs';
const asset={url:'https://cnine-card.pages.dev/'+BOREAS.image,sha256:BOREAS.sha256};
async function fixture(){
 const db=new PGlite();
 await db.exec(`CREATE TABLE users(id BIGINT PRIMARY KEY,role TEXT,status TEXT);
 INSERT INTO users VALUES(1,'OWNER','ACTIVE');
 CREATE TABLE app_meta(key TEXT PRIMARY KEY,value TEXT NOT NULL);
 INSERT INTO app_meta VALUES('black_miracle_pack_settings_v1485','{"powerRewards":{"vehicle":{"overrides":{}}}}');
 CREATE TABLE admin_logs(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,admin_id BIGINT,action_type TEXT,target_type TEXT,target_id TEXT,before_data TEXT,after_data TEXT);
 CREATE TABLE character_garage_items(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,code TEXT UNIQUE,name TEXT,rarity TEXT,image_url TEXT,description TEXT,total_power BIGINT,pve_power BIGINT,pvp_power BIGINT,is_active BIGINT,is_public BIGINT,sort_order BIGINT,draw_enabled BIGINT,draw_weight DOUBLE PRECISION,duplicate_shards BIGINT);
 INSERT INTO character_garage_items(code,name,rarity,total_power,pve_power,pvp_power,sort_order) VALUES('SOLARIS_OMEGA','솔라리스 - Ω','MYTHIC',350000,315000,35000,113);`);
 return db;
}
test('registration is atomic, idempotent and leaves reward configuration untouched',async()=>{
 const db=await fixture();try{
 const before=(await db.query('SELECT * FROM app_meta')).rows;
 const first=await registerBoreas(db,asset);assert.equal(first.replayed,false);assert.equal(first.item.name,BOREAS.name);
 assert.equal((await registerBoreas(db,asset)).replayed,true);
 assert.equal((await db.query('SELECT count(*)::int n FROM character_garage_items')).rows[0].n,2);
 assert.equal((await db.query('SELECT count(*)::int n FROM admin_logs')).rows[0].n,1);
 assert.equal((await verifyBoreas(db)).item.code,BOREAS.code);
 assert.deepEqual((await db.query("SELECT * FROM app_meta WHERE key='black_miracle_pack_settings_v1485'")).rows,before);
 }finally{await db.close();}
});
test('changed baseline or unverified asset cannot create a vehicle',async()=>{
 const db=await fixture();try{
 await assert.rejects(registerBoreas(db,{...asset,sha256:'wrong'}),/hash mismatch/);
 await db.query("UPDATE character_garage_items SET total_power=1 WHERE code='SOLARIS_OMEGA'");
 await assert.rejects(registerBoreas(db,asset));
 assert.equal((await db.query('SELECT count(*)::int n FROM character_garage_items')).rows[0].n,1);
 }finally{await db.close();}
});
test('audit failure rolls back the vehicle and receipt',async()=>{
 const db=await fixture();try{
 await db.exec('DROP TABLE admin_logs');
 await assert.rejects(registerBoreas(db,asset));
 assert.equal((await db.query('SELECT count(*)::int n FROM character_garage_items')).rows[0].n,1);
 assert.equal((await db.query("SELECT count(*)::int n FROM app_meta WHERE key LIKE 'ops:%'")).rows[0].n,0);
 }finally{await db.close();}
});
