import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {PGlite} from '@electric-sql/pglite';
import {__postgresCompatTest} from '../functions/_postgres_d1_compat.js';
import {coupSchema} from '../functions/_coup_schema.js';
import {imprisonByChief,handleChiefPrison,CHIEF_ARREST_MESSAGE} from '../functions/_chief_prison.js';

async function fixture(t){
  const pg=new PGlite();t.after(()=>pg.close());let failure='',beforeBatch=null;
  await pg.exec("CREATE FUNCTION sqlite_now() RETURNS TEXT LANGUAGE SQL STABLE AS $$ SELECT to_char(timezone('UTC',CURRENT_TIMESTAMP),'YYYY-MM-DD HH24:MI:SS') $$;");
  await pg.exec("CREATE FUNCTION sqlite_json_extract(value TEXT,path TEXT) RETURNS TEXT LANGUAGE SQL IMMUTABLE AS $$ SELECT value::jsonb ->> substring(path from 3) $$;");
  const DB=new __postgresCompatTest.PostgresD1Database({async query(input){
    const sql=typeof input==='string'?input:input.text;
    if(sql==='BEGIN'&&beforeBatch){const fn=beforeBatch;beforeBatch=null;await fn();}
    if(failure&&sql.includes(failure))throw Error('INJECTED_FAILURE');
    const r=await pg.query(sql,typeof input==='string'?[]:input.values||[]);return {...r,rowCount:r.affectedRows??r.rows.length};
  }}),env={DB},p=(sql,...args)=>DB.prepare(sql).bind(...args);
  await DB.execSchema([
    'CREATE TABLE app_meta(key TEXT PRIMARY KEY,value TEXT,updated_at TEXT)',
    "CREATE TABLE users(id BIGINT PRIMARY KEY,nickname TEXT,role TEXT,status TEXT DEFAULT 'ACTIVE',coin BIGINT DEFAULT 123456)",
    "CREATE TABLE chief_power_uses(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,appointment_id TEXT,user_id BIGINT,power_type TEXT,period_key TEXT,use_slot BIGINT,starts_at TEXT,ends_at TEXT,details_json TEXT,UNIQUE(appointment_id,power_type,period_key,use_slot))",
    "CREATE TABLE user_prison_status(user_id BIGINT PRIMARY KEY,active INTEGER,reason TEXT,jailed_by BIGINT,jailed_at TEXT,jailed_until TEXT,released_by BIGINT,released_at TEXT,release_reason TEXT,updated_at TEXT)",
    'CREATE TABLE user_runtime_commands(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id BIGINT,command_type TEXT,payload_json TEXT,created_by BIGINT,expires_at TEXT)',
    'CREATE TABLE admin_logs(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,admin_id BIGINT,action_type TEXT,target_type TEXT,target_id TEXT,before_data TEXT,after_data TEXT)',
    'CREATE TABLE prison_release_cases_v2031(inmate_user_id BIGINT PRIMARY KEY,case_id TEXT UNIQUE,release_price BIGINT,collected_coin BIGINT,contribution_count BIGINT,status TEXT,configured_by BIGINT,configured_at TEXT,last_request_id TEXT,opened_at TEXT,released_at TEXT,updated_at TEXT)',
    ...coupSchema(true)
  ]);
  await p("INSERT INTO users(id,nickname,role) VALUES(7,'현 족장','USER'),(8,'대상 유저','USER'),(9,'다른 유저','USER'),(1,'운영자','OWNER')").run();
  const appointment={id:'active-chief',userId:7,active:true,startsAt:new Date(Date.now()-60000).toISOString(),endsAt:new Date(Date.now()+3600000).toISOString()};
  await p("INSERT INTO app_meta(key,value) VALUES('chief_appointment_v1',?)",JSON.stringify(appointment)).run();
  const user={id:7,nickname:'현 족장',role:'USER'},body={userId:8,durationMinutes:60,reason:'검수 사유',requestId:crypto.randomUUID()};
  let facility=null,locks=0;
  const deps={json:(data,status=200)=>Response.json(data,{status}),readBody:r=>r.json(),ensurePrisonFoundation:async()=>{},
    withUserMutationLock:async(_env,id,path,work)=>{assert.equal(id,Number(body.userId));assert.equal(path,'chief/prison');locks++;return work();},
    prisonStatusForUser:async(_env,id)=>facility?{incarcerated:true,facility}:{incarcerated:Boolean(await p('SELECT 1 FROM user_prison_status WHERE user_id=? AND active=1 AND jailed_until>CURRENT_TIMESTAMP',id).first())}};
  const call=(path='chief/prison',method='POST',a=appointment,actor=user)=>handleChiefPrison({path:path.split('?')[0],request:new Request('https://local.test/api/'+path,{method,...(method==='POST'?{body:JSON.stringify(body)}:{})}),env,user:actor,appointment:a,deps});
  return {pg,env,p,user,appointment,body,deps,call,setFacility:v=>facility=v,fail:v=>failure=v,race:fn=>beforeBatch=fn,get locks(){return locks;}};
}
const tables=['user_prison_status','user_runtime_commands','prison_release_cases_v2031','chief_power_uses','admin_logs'];
async function counts(f){return Promise.all(tables.map(async table=>Number((await f.p('SELECT COUNT(*) n FROM '+table).first()).n)));}

test('current chief arrests into ordinary prison with exact notice, bail case, receipt and audit; replay preserves sentence and coins',async t=>{
  const f=await fixture(t),result=await imprisonByChief(f.env,f.user,f.appointment,f.body,f.deps);
  assert.equal(result.prison.facility,'PRISON');assert.equal(result.prison.remainingSeconds,3600);assert.deepEqual(await counts(f),[1,1,1,1,1]);
  const command=await f.p('SELECT * FROM user_runtime_commands').first(),payload=JSON.parse(command.payload_json);
  assert.equal(payload.source,'CHIEF');assert.equal(payload.message,CHIEF_ARREST_MESSAGE);assert.equal(payload.message,'최고사령부에서 당신을 체포하였습니다');assert.equal(command.expires_at,result.prison.jailedUntil);
  const before=await f.p('SELECT * FROM user_prison_status').first();
  const replay=await (await f.call()).json();assert.equal(replay.replayed,true);assert.deepEqual(await f.p('SELECT * FROM user_prison_status').first(),before);assert.deepEqual(await counts(f),[1,1,1,1,1]);
  assert.equal(Number((await f.p('SELECT SUM(coin) n FROM users').first()).n),123456*4);
  f.body.reason='변경 사유';assert.equal((await f.call()).status,409);assert.deepEqual(await counts(f),[1,1,1,1,1]);
});

test('chief search and action reject outsiders, expired/suspended chiefs, owner targets, self, invalid duration, and existing prisoners',async t=>{
  const f=await fixture(t);
  for(const a of [{...f.appointment,active:false},{...f.appointment,userId:9}])for(const route of ['chief/prison','chief/prison/users?q=유저'])assert.equal((await f.call(route,route.includes('users')?'GET':'POST',a)).status,403);
  let response=await f.call('chief/prison/users?q=유저','GET');assert.equal(response.status,200);const users=(await response.json()).users;assert.deepEqual(users.map(x=>Number(x.id)).sort(),[8,9]);assert.ok(users.every(x=>Object.keys(x).sort().join(',')==='id,nickname'));
  for(const minutes of [9,361,10.5,0]){f.body.durationMinutes=minutes;assert.equal((await f.call()).status,400);}f.body.durationMinutes=60;
  f.body.userId=1;assert.equal((await f.call()).status,403);f.body.userId=7;assert.equal((await f.call()).status,400);f.body.userId=8;
  for(const facility of ['PRISON','CLAN_CAMP','DEATH_GAME']){f.setFacility(facility);assert.equal((await f.call()).status,409);}f.setFacility(null);
  assert.deepEqual(await counts(f),[0,0,0,0,0]);
});

test('audit failure rolls back sentence, command, bail and receipt; in-transaction chief duty guard prevents stale authority',async t=>{
  const f=await fixture(t);f.fail('INSERT INTO admin_logs');assert.equal((await f.call()).status,409);assert.deepEqual(await counts(f),[0,0,0,0,0]);f.fail('');
  await f.p("INSERT INTO chief_duty_cases_v2115 VALUES('active-chief','trial','OPEN')").run();assert.equal((await f.call()).status,409);assert.deepEqual(await counts(f),[0,0,0,0,0]);
  await f.p('DELETE FROM chief_duty_cases_v2115').run();await f.p("UPDATE app_meta SET value=? WHERE key='chief_appointment_v1'",JSON.stringify({...f.appointment,endsAt:new Date(Date.now()-1000).toISOString()})).run();
  assert.equal((await f.call()).status,409);assert.deepEqual(await counts(f),[0,0,0,0,0]);
  await f.p("UPDATE app_meta SET value=? WHERE key='chief_appointment_v1'",JSON.stringify(f.appointment)).run();
  f.race(()=>f.pg.query("UPDATE users SET role='OWNER' WHERE id=8"));assert.equal((await f.call()).status,409);assert.deepEqual(await counts(f),[0,0,0,0,0]);
  await f.p("UPDATE users SET role='USER' WHERE id=8").run();assert.equal((await f.call()).status,200);
});

test('real player entry exposes only the chief action and keeps prison gate; both live commands and locked login show the arrest notice',()=>{
  const read=path=>readFileSync(new URL('../'+path,import.meta.url),'utf8'),chief=read('functions/_chief.js'),api=read('functions/api/[[path]].js'),app=read('js/app.js'),index=read('index.html');
  assert.ok(chief.indexOf('const user=await authenticate')<chief.indexOf("if(path==='chief/prison'"));
  assert.ok(api.indexOf("if(!prisonExempt)")<api.indexOf('const chiefResponse=await handleChief'));
  assert.match(api,/ensurePrisonFoundation,prisonStatusForUser,withUserMutationLock:withJointUserMutationLock/);
  assert.match(read('js/chief-system-v1.js'),/data-chief-prison/);
  assert.match(app,/if\(!camp\)void window\.ChiefPrison\?\.checkArrestNotice\(prisonUiState\)/);
  assert.match(app,/renderLockedPrison\(\);\s*window\.ChiefPrison\?\.showArrestNotice\(command,prisonUiState\)/);
  for(const file of ['js/chief-prison-v1.js?v=20261006','css/chief-prison-v1.css?v=20261006'])assert.ok(index.includes(file));
});
