import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { PGlite } from '@electric-sql/pglite';
import { __postgresCompatTest } from '../functions/_postgres_d1_compat.js';
import { coupSchema } from '../functions/_coup_schema.js';
import { extendDiimTerm, chiefExtensionReceipt, chiefExtensionNotice, claimChiefExtensionNotice, CHIEF_EXTENSION_ID } from '../functions/_chief_extension.js';

async function fixture(t) {
  const pg=new PGlite();t.after(()=>pg.close());let failure='',race=null;
  await pg.exec("CREATE FUNCTION sqlite_now() RETURNS TEXT LANGUAGE SQL STABLE AS $$ SELECT to_char(timezone('UTC',CURRENT_TIMESTAMP),'YYYY-MM-DD HH24:MI:SS') $$");
  await pg.exec("CREATE FUNCTION sqlite_json_extract(value TEXT,path TEXT) RETURNS TEXT LANGUAGE SQL IMMUTABLE AS $$ SELECT value::jsonb ->> substring(path from 3) $$");
  const DB=new __postgresCompatTest.PostgresD1Database({async query(input){
    const sql=typeof input==='string'?input:input.text;
    if(sql==='BEGIN'&&race){const fn=race;race=null;await fn()}
    if(failure&&sql.includes(failure))throw Error('INJECTED_FAILURE');
    const result=await pg.query(sql,typeof input==='string'?[]:input.values||[]);
    return {...result,rowCount:result.affectedRows??result.rows.length};
  }}),env={DB},p=(sql,...args)=>DB.prepare(sql).bind(...args);
  await DB.execSchema([
    'CREATE TABLE app_meta(key TEXT PRIMARY KEY,value TEXT,updated_at TEXT)',
    'CREATE TABLE users(id BIGINT PRIMARY KEY,nickname TEXT,status TEXT)',
    'CREATE TABLE admin_logs(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,admin_id BIGINT,action_type TEXT,target_type TEXT,target_id TEXT,before_data TEXT,after_data TEXT)',
    'CREATE TABLE chief_power_uses(appointment_id TEXT,power_type TEXT,use_slot INTEGER)',...coupSchema(true)
  ]);
  const current={id:'diim-10th',userId:4773,nickname:'진짜디임',ordinal:10,startsAt:new Date(Date.now()-86400000).toISOString(),endsAt:new Date(Date.now()+2*86400000).toISOString(),inaugurationVersion:12345,appointedBy:1,source:'PLAY DK 투표'};
  await p("INSERT INTO app_meta(key,value) VALUES('chief_appointment_v1',?)",JSON.stringify(current)).run();
  await p("INSERT INTO users VALUES(4773,'진짜디임','ACTIVE')").run();
  await p("INSERT INTO chief_power_uses VALUES('diim-10th','TOWER_RESET',1)").run();
  const owner={id:1,role:'OWNER'},body={appointmentId:current.id,endsAt:current.endsAt};
  return {env,p,pg,current,owner,body,apply:()=>extendDiimTerm(env,owner,body),fail:v=>failure=v,race:fn=>race=fn};
}

test('one extension adds seven days to the old end, preserves identity and usage, and atomically publishes the receipt',async t=>{
  const f=await fixture(t);assert.equal((await chiefExtensionNotice(f.env,20)).notice,null);
  const result=await f.apply(),saved=JSON.parse((await f.p("SELECT value FROM app_meta WHERE key='chief_appointment_v1'").first()).value);
  assert.equal(Date.parse(saved.endsAt)-Date.parse(f.current.endsAt),7*86400000);
  assert.deepEqual(saved,{...f.current,endsAt:result.receipt.endsAt,extensionId:CHIEF_EXTENSION_ID});
  assert.deepEqual((await f.p('SELECT * FROM chief_power_uses').all()).results,[{appointment_id:'diim-10th',power_type:'TOWER_RESET',use_slot:1}]);
  assert.equal(Number((await f.p('SELECT COUNT(*) n FROM admin_logs').first()).n),1);
  assert.equal((await f.apply()).replayed,true);assert.deepEqual(await chiefExtensionReceipt(f.env),result.receipt);
  assert.equal(Number((await f.p('SELECT COUNT(*) n FROM admin_logs').first()).n),1);
  const notice=await chiefExtensionNotice(f.env,20);assert.equal(notice.notice.endsAt,saved.endsAt);assert.equal('appliedBy' in notice.notice,false);
});

test('outsiders, wrong target, expired term, stale term, and suspended duty cannot extend or publish',async t=>{
  const f=await fixture(t);
  await assert.rejects(()=>extendDiimTerm(f.env,{id:2,role:'ADMIN'},f.body),/OWNER/);
  const write=value=>f.p("UPDATE app_meta SET value=? WHERE key='chief_appointment_v1'",JSON.stringify(value)).run();
  for(const change of [{userId:5},{id:'replacement'},{endsAt:new Date(Date.now()-1000).toISOString()},{endsAt:new Date(Date.now()+9*86400000).toISOString()}]){
    await write({...f.current,...change});await assert.rejects(f.apply);assert.equal(await chiefExtensionReceipt(f.env),null);
  }
  await write(f.current);await f.p("INSERT INTO chief_duty_cases_v2115 VALUES('diim-10th','trial','OPEN')").run();
  await assert.rejects(f.apply);assert.equal(await chiefExtensionReceipt(f.env),null);
  assert.equal(Number((await f.p('SELECT COUNT(*) n FROM admin_logs').first()).n),0);
});

test('audit failure rolls back term and notice; a racing replacement or edit is never overwritten',async t=>{
  const f=await fixture(t);f.fail('INSERT INTO admin_logs');await assert.rejects(f.apply);f.fail('');
  assert.equal(await chiefExtensionReceipt(f.env),null);
  assert.deepEqual(JSON.parse((await f.p("SELECT value FROM app_meta WHERE key='chief_appointment_v1'").first()).value),f.current);
  const changed={...f.current,ordinal:11};
  f.race(()=>f.pg.query("UPDATE app_meta SET value=$1 WHERE key='chief_appointment_v1'",[JSON.stringify(changed)]));
  await assert.rejects(f.apply);assert.equal(await chiefExtensionReceipt(f.env),null);
  assert.deepEqual(JSON.parse((await f.p("SELECT value FROM app_meta WHERE key='chief_appointment_v1'").first()).value),changed);
});

test('server receipt suppresses repeat display per account and permits only the same lost-response retry',async t=>{
  const f=await fixture(t);await f.apply();
  const body={id:CHIEF_EXTENSION_ID,requestId:'first-tab-request-12345'};
  assert.equal((await claimChiefExtensionNotice(f.env,20,body)).show,true);
  assert.equal((await chiefExtensionNotice(f.env,20)).complete,true);
  assert.equal((await claimChiefExtensionNotice(f.env,20,{...body,requestId:'other-tab-request-12345'})).show,false);
  assert.equal((await claimChiefExtensionNotice(f.env,20,body)).show,true);
  assert.equal((await claimChiefExtensionNotice(f.env,21,{...body,requestId:'other-user-request-12345'})).show,true);
  await assert.rejects(()=>claimChiefExtensionNotice(f.env,22,{...body,id:'other-event'}),/올바르지/);
  await f.p("UPDATE app_meta SET value=? WHERE key='chief_appointment_v1'",JSON.stringify({...f.current,id:'new-chief'})).run();
  assert.equal((await chiefExtensionNotice(f.env,22)).complete,true);
  assert.equal((await claimChiefExtensionNotice(f.env,22,body)).show,false);
});

test('production loader includes the real illustration; only notice access is exempted for prisoners',()=>{
  const read=path=>readFileSync(new URL('../'+path,import.meta.url),'utf8'),index=read('index.html'),api=read('functions/api/[[path]].js'),chief=read('functions/_chief.js');
  for(const file of ['css/chief-extension-notice-v1.css?v=20261011','js/chief-extension-notice-v1.js?v=20261011'])assert.ok(index.includes(file));
  assert.match(read('js/chief-extension-notice-v1.js'),/diim-regime-extension-20261011.webp/);
  assert.ok(readFileSync(new URL('../assets/ui/chief/diim-regime-extension-20261011.webp',import.meta.url)).length>100000);
  const exempt=api.slice(api.indexOf('const prisonExempt='),api.indexOf('if(!prisonExempt)'));
  assert.ok(exempt.includes("path==='chief/extension-notice'"));assert.ok(!exempt.includes("path.startsWith('chief/')"));
  assert.ok(chief.indexOf('const user=await authenticate')<chief.indexOf("if(path==='chief/extension-notice')"));
});
