import test from 'node:test';
import assert from 'node:assert/strict';
import {PGlite} from '@electric-sql/pglite';
import {__clanTest as clan} from '../functions/_clan.js';
import {transferDcMaster,OPERATION_KEY} from '../scripts/ops/clan-dc-master-transfer-20260929.mjs';

const now=Date.parse('2026-09-29T13:22:00Z');
async function fixture(t){
  const pg=new PGlite();t.after(()=>pg.close());
  await pg.exec(clan.FOUNDATION_SQL.map(s=>s.replaceAll('INTEGER PRIMARY KEY AUTOINCREMENT','BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY').replaceAll('INTEGER','BIGINT').replaceAll('CURRENT_TIMESTAMP',"'2026-09-29 12:40:21'")).join(';'));
  await pg.exec("CREATE TABLE app_meta(key TEXT PRIMARY KEY,value TEXT); CREATE TABLE users(id BIGINT PRIMARY KEY,nickname TEXT,role TEXT,status TEXT); CREATE TABLE admin_logs(admin_id BIGINT,action_type TEXT,target_type TEXT,target_id TEXT,before_data TEXT,after_data TEXT)");
  const client={async query(sql,args=[]){const r=await pg.query(sql,args);return{...r,rowCount:r.affectedRows??r.rows.length}}};
  await pg.exec("INSERT INTO users VALUES(1,'OWNER','OWNER','ACTIVE'),(290,'Mild7','USER','ACTIVE'),(3011,'오일바른가지','USER','ACTIVE'); INSERT INTO clan_seasons(id,season_no,phase,registration_ends_at,draft_ends_at,starts_at,ends_at,draft_pick_count,next_pick_deadline) VALUES(6,3,'DRAFT','2026-09-29T12:26:49.107Z','2026-09-29T13:26:49.107Z','2026-09-29T13:00:00Z','2026-10-06T13:00:00Z',520,'2026-09-29T13:22:30Z'); INSERT INTO clan_season_teams(season_id,clan_id,master_user_id,draft_position) VALUES(6,8,290,7),(6,7,4235,6); INSERT INTO clan_members(season_id,clan_id,user_id,member_role,draft_pick_no) VALUES(6,8,290,'MASTER',0),(6,8,3011,'MEMBER',57),(6,8,71,'MEMBER',56); INSERT INTO clan_draft_pool(season_id,user_id,candidate_key,status,drafted_clan_id,pick_no) VALUES(6,290,'old-master','MASTER',8,0),(6,3011,'new-master','DRAFTED',8,57),(6,71,'other-member','DRAFTED',8,56)");
  await client.query("INSERT INTO app_meta(key,value) VALUES('clan_redraft_v20260916:6',$1)",[JSON.stringify({quotas:{8:18}})]);
  const snapshot=async()=>Object.fromEntries(await Promise.all(['clan_seasons','clan_season_teams','clan_members','clan_draft_pool','clan_draft_locks','app_meta','admin_logs'].map(async table=>[table,(await client.query(`SELECT row_to_json(t) row FROM ${table} t ORDER BY row_to_json(t)::text`)).rows.map(r=>r.row)])));
  return{client,snapshot};
}
test('DC-only transfer preserves members, picks and timer; repeat execution leaves the new state untouched',async t=>{
  const f=await fixture(t),before=await f.snapshot();await transferDcMaster(f.client,{dryRun:true,now});assert.deepEqual(await f.snapshot(),before);
  const result=await transferDcMaster(f.client,{now});assert.equal(result.receipt.to.userId,3011);assert.equal(result.receipt.from.role,'MEMBER');
  const after=await f.snapshot();assert.deepEqual(after.clan_seasons,before.clan_seasons);assert.equal(after.clan_members.length,3);assert.equal(after.clan_draft_locks.length,0);assert.equal(after.admin_logs.length,1);
  assert.equal(after.clan_members.find(m=>m.user_id===3011).draft_pick_no,57);assert.ok(after.app_meta.some(r=>r.key===OPERATION_KEY+':before'));
  assert.equal((await transferDcMaster(f.client,{now:now+1})).replayed,true);assert.deepEqual(await f.snapshot(),after);
});
test('a late audit failure rolls back the entire leadership handover and retry succeeds',async t=>{
  const f=await fixture(t),before=await f.snapshot(),query=f.client.query.bind(f.client);
  f.client.query=(sql,args)=>sql.startsWith('INSERT INTO admin_logs')?Promise.reject(Error('audit failed')):query(sql,args);
  await assert.rejects(transferDcMaster(f.client,{now}),/audit failed/);assert.deepEqual(await f.snapshot(),before);
  f.client.query=query;assert.equal((await transferDcMaster(f.client,{now})).receipt.to.userId,3011);
});
test('in-flight draft and wrong-clan target cannot partially change a leader',async t=>{
  const f=await fixture(t);await f.client.query("INSERT INTO clan_draft_locks(season_id,token,expires_at) VALUES(6,'busy','2026-09-29T13:23:00Z')");
  const busy=await f.snapshot();await assert.rejects(transferDcMaster(f.client,{now}),/DRAFT_BUSY/);assert.deepEqual(await f.snapshot(),busy);
  await f.client.query('DELETE FROM clan_draft_locks');await f.client.query('UPDATE clan_members SET clan_id=7 WHERE user_id=3011');
  const wrong=await f.snapshot();await assert.rejects(transferDcMaster(f.client,{now}),/Target must already belong to DC/);assert.deepEqual(await f.snapshot(),wrong);
});
