import test from 'node:test';
import assert from 'node:assert/strict';
import {PGlite} from '@electric-sql/pglite';
import before from '../preview/avatar-clan-hanbok-v1/before-images.json' with {type:'json'};
import {replaceClanAvatarsWithHanbok,CLAN_HANBOK_CODES} from '../scripts/ops/clan-avatar-hanbok-20260927.mjs';
async function fixture(){const db=new PGlite();await db.exec(`CREATE TABLE users(id BIGINT PRIMARY KEY,role TEXT,status TEXT,coin BIGINT);INSERT INTO users VALUES(1,'OWNER','ACTIVE',777),(2,'USER','ACTIVE',888);
 CREATE TABLE avatar_catalog_v1(code TEXT PRIMARY KEY,name TEXT,version INTEGER,lobby_image TEXT,lobby_mobile_image TEXT,equipment_image TEXT,role_label TEXT,description TEXT,accent TEXT,updated_at TEXT,acquisition_type TEXT,coin_price BIGINT,effect_type TEXT,effect_value INTEGER,is_active INTEGER,is_public INTEGER,sale_enabled INTEGER);
 CREATE TABLE avatar_effect_options_v1(avatar_code TEXT,option_order INTEGER,effect_type TEXT,effect_value INTEGER,PRIMARY KEY(avatar_code,option_order));
 CREATE TABLE avatar_user_ownership_v1(user_id BIGINT,avatar_code TEXT,expires_at TEXT,source_type TEXT);CREATE TABLE avatar_user_loadout_v1(user_id BIGINT,avatar_code TEXT,updated_at TEXT);
 CREATE TABLE app_meta(key TEXT PRIMARY KEY,value TEXT,updated_at TEXT);CREATE TABLE admin_logs(id BIGSERIAL PRIMARY KEY,admin_id BIGINT,action_type TEXT,target_type TEXT,target_id TEXT,before_data TEXT,after_data TEXT);`);
 const q=async(sql,args=[])=>(await db.query(sql,args)).rows;
 for(const r of before){const fields=Object.keys(r);await q('INSERT INTO avatar_catalog_v1('+fields.join(',')+',updated_at,acquisition_type,coin_price,effect_type,effect_value,is_active,is_public,sale_enabled) VALUES('+fields.map((_,i)=>'$'+(i+1)).join(',')+",'original','EVENT',NULL,'COIN_GAIN_PERCENT',75,1,1,0)",Object.values(r));
  await q("INSERT INTO avatar_effect_options_v1 VALUES($1,0,'COIN_GAIN_PERCENT',75),($1,1,'RAID_EXTRA_ENTRY',10)",[r.code]);await q("INSERT INTO avatar_user_ownership_v1 VALUES(2,$1,'2020-01-01','CLAN'),(1,$1,'2030-01-01','CLAN')",[r.code]);await q("INSERT INTO avatar_user_loadout_v1 VALUES(2,$1,'original')",[r.code]);}
 await q("INSERT INTO avatar_catalog_v1(code,name,version) VALUES('UNRELATED','기존 아바타',9)");
 const snapshot=async()=>Object.fromEntries(await Promise.all(['users','avatar_catalog_v1','avatar_effect_options_v1','avatar_user_ownership_v1','avatar_user_loadout_v1','app_meta','admin_logs'].map(async t=>[t,await q('SELECT * FROM '+t+' ORDER BY 1,2')])));
 const run=async()=>{await db.exec('BEGIN');try{const r=await replaceClanAvatarsWithHanbok(q);await db.exec('COMMIT');return r;}catch(e){await db.exec('ROLLBACK');throw e;}};
 return {db,q,run,snapshot};}
test('all eight art sets change once; expired ownership, loadouts, options, wallets and unrelated avatars stay intact',async()=>{const f=await fixture();try{const a=await f.snapshot(),r=await f.run(),b=await f.snapshot();assert.equal(r.count,8);assert.deepEqual(r.changes.map(c=>c.code),CLAN_HANBOK_CODES);for(const key of ['users','avatar_effect_options_v1','avatar_user_ownership_v1','avatar_user_loadout_v1'])assert.deepEqual(b[key],a[key]);assert.deepEqual(b.avatar_catalog_v1.find(c=>c.code==='UNRELATED'),a.avatar_catalog_v1.find(c=>c.code==='UNRELATED'));assert.equal((await f.run()).replayed,true);assert.deepEqual(await f.snapshot(),b);}finally{await f.db.close();}});
for(const kind of ['missing','changed-art','audit-failure'])test(kind+' rolls back the complete eight-avatar operation',async()=>{const f=await fixture();try{if(kind==='missing')await f.q("DELETE FROM avatar_catalog_v1 WHERE code='T1_JOEUN'");if(kind==='changed-art')await f.q("UPDATE avatar_catalog_v1 SET equipment_image='operator-change.png' WHERE code='T1_JOEUN'");if(kind==='audit-failure')await f.db.exec("ALTER TABLE admin_logs ADD CONSTRAINT reject_audit CHECK(action_type='REJECT')");const a=await f.snapshot();await assert.rejects(f.run);assert.deepEqual(await f.snapshot(),a);}finally{await f.db.close();}});
