import test from 'node:test';
import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { PGlite } from '@electric-sql/pglite';
import { readFileSync } from 'node:fs';
import vm from 'node:vm';
import { __clanTest } from '../functions/_clan.js';
import { __postgresCompatTest } from '../functions/_postgres_d1_compat.js';
import { CLAN_RANKED_TEAMS_SQL } from '../functions/_clan_ranking.js';
import { clanParticipationSchema, prepareClanParticipationSettings } from '../functions/_clan_participation.js';
import { CHAMPIONS_DEFAULTS, cleanChampionsSettings, validateChampionsSettings, championsSchema, ensureChampionsSchema,
  championsNextWindow, startChampions, advanceChampions, championsPublicState, championsMemberEligible,
  championsBattleSettings, deliverChampionsRewards } from '../functions/_clan_champions.js';

const read = path => readFileSync(new URL('../' + path, import.meta.url), 'utf8');
const settings = (extra = {}) => ({ ...__clanTest.CLAN_ADMIN_SETTINGS_DEFAULTS, mode: 'ON', ...extra });
class SQLiteDB {
  sql = new DatabaseSync(':memory:'); failAt = '';
  prepare(source) { const db = this; return { source, values: [], bind(...values) { this.values = values; return this; },
    async first() { return db.sql.prepare(source).get(...this.values) || null; },
    async all() { return { results: db.sql.prepare(source).all(...this.values) }; },
    async run() { const row = db.sql.prepare(source).run(...this.values); return { meta: { changes: Number(row.changes), last_row_id: Number(row.lastInsertRowid) } }; } }; }
  async batch(statements) {
    this.sql.exec('BEGIN');
    try {
      const results = statements.map(statement => {
        if (this.failAt && statement.source.includes(this.failAt)) throw new Error('INJECTED_FAILURE');
        const row = this.sql.prepare(statement.source).run(...statement.values);
        return { meta: { changes: Number(row.changes), last_row_id: Number(row.lastInsertRowid) } };
      });
      this.sql.exec('COMMIT'); return results;
    } catch (error) { this.sql.exec('ROLLBACK'); throw error; }
  }
}
async function fixture(t, postgres = false) {
  const schema = [...__clanTest.FOUNDATION_SQL, ...clanParticipationSchema(),
    `CREATE TABLE app_meta(key TEXT PRIMARY KEY,value TEXT,updated_at TEXT DEFAULT CURRENT_TIMESTAMP)`,
    `CREATE TABLE users(id INTEGER PRIMARY KEY,nickname TEXT,coin INTEGER DEFAULT 0,card_shards INTEGER DEFAULT 0)`,
    `CREATE TABLE clan_season_settlements(season_id INTEGER PRIMARY KEY,champion_clan_id INTEGER,status TEXT,reward_status TEXT,processing_token TEXT,updated_at TEXT DEFAULT CURRENT_TIMESTAMP,completed_at TEXT)`,
    `CREATE TABLE clan_reward_receipts(season_id INTEGER,user_id INTEGER,clan_id INTEGER,reward_tier TEXT,status TEXT,coin INTEGER,card_shards INTEGER,updated_at TEXT DEFAULT CURRENT_TIMESTAMP,completed_at TEXT,PRIMARY KEY(season_id,user_id))`,
    `CREATE TABLE user_messages(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER,sender_type TEXT,title TEXT,body TEXT,message_type TEXT,campaign_key TEXT)`,
    `CREATE TABLE user_message_rewards(id INTEGER PRIMARY KEY AUTOINCREMENT,message_id INTEGER,user_id INTEGER,reward_type TEXT,reward_amount INTEGER,UNIQUE(message_id,reward_type))`
  ];
  let DB, pg, failAt = '';
  if (postgres) {
    pg = new PGlite(); t.after(() => pg.close());
    await pg.exec(`CREATE FUNCTION sqlite_now() RETURNS TEXT LANGUAGE SQL STABLE AS $$ SELECT to_char(timezone('UTC',CURRENT_TIMESTAMP),'YYYY-MM-DD HH24:MI:SS') $$;
      CREATE FUNCTION sqlite_datetime(VARIADIC parts text[]) RETURNS TEXT LANGUAGE SQL STABLE AS $$ SELECT to_char(timezone('UTC',CURRENT_TIMESTAMP)+COALESCE(parts[2]::interval,interval '0 seconds'),'YYYY-MM-DD HH24:MI:SS') $$;`);
    await pg.exec(schema.map(sql => sql.replaceAll('INTEGER PRIMARY KEY AUTOINCREMENT', 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY').replaceAll('INTEGER', 'BIGINT').replaceAll('CURRENT_TIMESTAMP', 'sqlite_now()')).join(';'));
    DB = new __postgresCompatTest.PostgresD1Database({ async query(input) {
      const source = typeof input === 'string' ? input : input.text;
      if (failAt && source.includes(failAt)) throw new Error('INJECTED_FAILURE');
      const r = await pg.query(source, typeof input === 'string' ? [] : input.values || []);
      return { ...r, rowCount: r.affectedRows ?? r.rows.length };
    } });
  } else { DB = new SQLiteDB(); t.after(() => DB.sql.close()); DB.sql.exec(schema.join(';')); }
  const env = { DB }, p = (sql, ...args) => DB.prepare(sql).bind(...args);
  await ensureChampionsSchema(env); await ensureChampionsSchema(env);
  const now = Date.now(), season = { id: 7, season_no: 4, phase: 'SETTLEMENT' };
  await p("INSERT INTO clan_seasons(id,season_no,phase,registration_ends_at,draft_ends_at,starts_at,ends_at) VALUES(7,4,'SETTLEMENT',?,?,?,?)", ...Array(4).fill(new Date(now).toISOString())).run();
  for (const [id, name, score] of [[9, 'DK', 21], [6, '한화', 18], [2, '삼성', 15], [1, 'T1', 12]]) {
    await p('INSERT INTO clan_organizations(id,name,mark_key) VALUES(?,?,?)', id, name, {9:'DK',6:'HANWHA',2:'SAMSUNG',1:'T1'}[id]).run();
    await p('INSERT INTO clan_season_teams(season_id,clan_id,master_user_id,draft_position,score,wins) VALUES(7,?,?,?,?,5)', id, id * 10, 10 - id, score).run();
    for (const userId of [id * 10, id * 10 + 1]) {
      await p('INSERT INTO users(id,nickname,coin) VALUES(?,?,100)', userId, name + userId).run();
      await p('INSERT INTO clan_members(season_id,clan_id,user_id) VALUES(7,?,?)', id, userId).run();
    }
  }
  const rank = () => p(CLAN_RANKED_TEAMS_SQL, 7).all().then(r => r.results);
  const cup = () => p('SELECT * FROM clan_championships WHERE season_id=7').first();
  const war = round => p('SELECT * FROM clan_wars WHERE season_id=7 AND round_no=?', round).first();
  const fresh = () => p('SELECT * FROM clan_seasons WHERE id=7').first();
  return { env, p, now, season, rank, cup, war, fresh, fail(value) { failAt = value; DB.failAt = value; } };
}

test('championship CMS defaults are enabled, rewards unset; numeric/time validation and partial saves', () => {
  assert.equal(CHAMPIONS_DEFAULTS.championsEnabled, true);
  assert.equal(CHAMPIONS_DEFAULTS.championsRewardsEnabled, false);
  assert.equal(CHAMPIONS_DEFAULTS.championsCoin, 0);
  assert.equal(cleanChampionsSettings({ championsOpenTime: '7:05' }).championsOpenTime, '07:05');
  assert.equal(__clanTest.cleanClanAdminSettings({ mode:'ON' }, settings({ championsCoin: 5000000000 })).championsCoin, 5000000000);
  for (const value of [-1, 1.5, Infinity, Number.MAX_SAFE_INTEGER + 1, null, ''])
    assert.throws(() => validateChampionsSettings({ championsCoin: value }, settings()));
  assert.throws(() => validateChampionsSettings({ championsOpenTime:'24:00' }, settings()));
  assert.throws(() => validateChampionsSettings({}, settings({ championsRewardsEnabled: true })));
  assert.throws(() => validateChampionsSettings({}, settings({ mode:'TEST', championsCoin:1, championsRewardsEnabled:true })));
});

test('KST next-day scheduling skips closed weekdays and never opens in the past', () => {
  const at = Date.parse('2026-09-08T13:00:00Z');
  assert.equal(new Date(championsNextWindow(at, 1, settings())).toISOString(), '2026-09-09T12:00:00.000Z');
  assert.equal(new Date(championsNextWindow(at, 1, settings({openDays:[5]}))).toISOString(), '2026-09-11T12:00:00.000Z');
});

for (const postgres of [false, true]) {
  const backend = postgres ? 'PostgreSQL adapter' : 'SQLite';
  test(`${backend}: CMS opening/editing cannot replace championship-frozen participation rules`, async t=>{
    const f=await fixture(t,postgres),s=settings({participationEnabled:true,participationEffectiveAt:new Date(f.now-86400000).toISOString(),battleParticipationRewardsEnabled:true,battleParticipationCoin:101});
    await startChampions(f.env,f.season,s,await f.rank(),f.now);
    await f.p("UPDATE clan_wars SET starts_at=?,ends_at=? WHERE round_no=1001",new Date(f.now-1000).toISOString(),new Date(f.now+3600000).toISOString()).run();
    const changed={...s,battleParticipationCoin:777,initialEnergy:1};
    await prepareClanParticipationSettings(f.env,changed,{...changed,battleParticipationCoin:999},f.now);
    assert.equal(Number((await f.p('SELECT COUNT(*) count FROM clan_participation_round_rules').first()).count),0);
    const admin=await __clanTest.clanAdminState(f.env,changed);
    assert.equal(admin.participationRuntime.battleCoin,101);
    assert.equal(admin.participationRuntime.scorePolicy,'ATTACKER_PARTICIPATION_V1');
    assert.equal(JSON.parse((await f.p('SELECT rules_json FROM clan_participation_round_rules WHERE round_no=1001').first()).rules_json).initialEnergy,10);
  });
  test(`${backend}: actual regular settlement pays once then playoffs open; stale requests cannot cancel them`, async t=>{
    const f=await fixture(t,postgres),s=settings({rewardsEnabled:true,winnerCoin:5000,runnerUpCoin:1200,participationCoin:10});
    const result=await __clanTest.settleSeason(f.env,f.season,s);
    assert.equal(result.phase,'CHAMPIONS');assert.equal((await f.war(1001)).status,'SCHEDULED');
    assert.equal(Number((await f.p('SELECT coin FROM users WHERE id=90').first()).coin),5110);
    assert.equal(Number((await f.p('SELECT coin FROM users WHERE id=60').first()).coin),1310);
    await __clanTest.settleSeason(f.env,f.season,s);
    assert.equal((await f.war(1001)).status,'SCHEDULED');
    assert.equal(Number((await f.p('SELECT coin FROM users WHERE id=90').first()).coin),5110);
    assert.equal(Number((await f.p('SELECT trophies FROM clan_organizations WHERE id=9').first()).trophies),1);
    assert.equal(Number((await f.p('SELECT COUNT(*) count FROM clan_reward_receipts').first()).count),8);
  });
  test(`${backend}: top 3 freeze → semifinal → final → exactly-once extra reward, normal standings unchanged`, async t => {
    const f = await fixture(t, postgres), s = settings({ championsRewardsEnabled:true, championsCoin:5000000000, championsMysticEnergy:50 });
    const ranked = await f.rank();
    await Promise.all([startChampions(f.env, f.season, s, ranked, f.now), startChampions(f.env, f.season, s, ranked, f.now)]);
    assert.equal((await f.fresh()).phase, 'CHAMPIONS');
    const cup = await f.cup(), semi = await f.war(1001);
    assert.deepEqual(JSON.parse(cup.seeds_json).map(x=>x.clanId), [9,6,2]);
    assert.deepEqual([Number(semi.clan_a_id), Number(semi.clan_b_id)], [6,2]);
    assert.equal(await f.war(1002), null);
    assert.equal(Number((await f.p('SELECT COUNT(*) count FROM clan_championship_members').first()).count), 6);
    assert.equal(await championsMemberEligible(f.env, 7, 10, 1), false);
    assert.equal(await championsMemberEligible(f.env, 7, 60, 6), true);
    const frozen = await championsBattleSettings(f.env, await f.fresh(), { ...s, initialEnergy:1, mode:'TEST' });
    assert.equal(frozen.initialEnergy, 10); assert.equal(frozen.mode, 'TEST');
    await f.p('UPDATE clan_wars SET score_a=230,score_b=230 WHERE id=?', semi.id).run();
    await advanceChampions(f.env, await f.fresh(), s, Date.parse(semi.ends_at));
    assert.equal(Number((await f.war(1001)).winner_clan_id), 6, 'higher seed wins a tie, not lower numeric clan id');
    const final = await f.war(1002);
    assert.deepEqual([Number(final.clan_a_id),Number(final.clan_b_id)], [9,6]);
    await f.p('UPDATE clan_wars SET score_a=170,score_b=190 WHERE id=?', final.id).run();
    await advanceChampions(f.env, await f.fresh(), s, Date.parse(final.ends_at));
    assert.equal((await f.fresh()).phase, 'COMPLETE');
    assert.equal(Number((await f.cup()).winner_clan_id), 6);
    assert.equal((await f.cup()).reward_status, 'SENT');
    await Promise.all([deliverChampionsRewards(f.env,7,s),deliverChampionsRewards(f.env,7,s)]);
    const messages = (await f.p('SELECT * FROM user_message_rewards ORDER BY user_id,reward_type').all()).results;
    assert.equal(messages.length, 4);
    assert.deepEqual(messages.map(x=>Number(x.user_id)), [60,60,61,61]);
    assert.equal(Number(messages[0].reward_amount), 5000000000);
    assert.deepEqual((await f.rank()).map(x=>[Number(x.clan_id),Number(x.score),Number(x.wins),Number(x.combat_points)]), ranked.map(x=>[Number(x.clan_id),Number(x.score),Number(x.wins),Number(x.combat_points)]));
    assert.equal(Number((await f.p('SELECT SUM(coin) coin FROM users').first()).coin), 800, 'only standard messages, no direct wallet mutation');
    assert.equal(Number((await f.p('SELECT SUM(trophies) trophies FROM clan_organizations').first()).trophies), 0, 'postseason does not double-add regular season trophies');
    const history = await championsPublicState(f.env,8,s); assert.equal(history.historical,true); assert.equal(history.seasonId,7);
    await startChampions(f.env, { ...f.season, phase:'COMPLETE' },s,ranked,f.now);
    assert.equal(Number((await f.p('SELECT COUNT(*) count FROM clan_wars').first()).count),2);
  });

  test(`${backend}: pending battles delay advancement, late resolution reschedules a future final`, async t => {
    const f=await fixture(t,postgres),s=settings(); await startChampions(f.env,f.season,s,await f.rank(),f.now);
    const semi=await f.war(1001);
    await f.p("INSERT INTO clan_war_battles(request_id,season_id,war_id,attacker_clan_id,defender_clan_id,attacker_user_id,defender_user_id,battle_seed,status) VALUES('pending-1',7,?,6,2,60,20,1,'RESOLVING')",semi.id).run();
    const late=Date.parse((await f.cup()).final_starts_at)+3600000;
    await advanceChampions(f.env,await f.fresh(),s,late);
    assert.equal((await f.war(1001)).status,'ACTIVE'); assert.equal(await f.war(1002),null);
    await f.p("UPDATE clan_war_battles SET status='COMPLETED'").run();
    await advanceChampions(f.env,await f.fresh(),s,late);
    assert.ok(Date.parse((await f.war(1002)).starts_at)>late);
    assert.equal((await f.cup()).reward_status,'AWAITING_CONFIG');
  });

  test(`${backend}: reward rollback/retry, original roster retained, late CMS config only once`, async t => {
    const f=await fixture(t,postgres),s=settings(); await startChampions(f.env,f.season,s,await f.rank(),f.now);
    await f.p("UPDATE clan_championships SET status='COMPLETED',winner_clan_id=6").run();
    await f.p('DELETE FROM clan_members WHERE user_id=61').run();
    await f.p('INSERT INTO clan_members(season_id,clan_id,user_id) VALUES(7,6,999)').run();
    const configured=settings({championsRewardsEnabled:true,championsCoin:1234,championsMysticEnergy:30});
    f.fail('INSERT INTO user_message_rewards');
    await assert.rejects(()=>deliverChampionsRewards(f.env,7,configured,{configurePending:true}),/INJECTED_FAILURE/);
    assert.equal(Number((await f.p('SELECT COUNT(*) count FROM user_messages').first()).count),0);
    assert.equal(Number((await f.p('SELECT COUNT(*) count FROM clan_championship_rewards').first()).count),0);
    f.fail('');
    await deliverChampionsRewards(f.env,7,{...configured,championsCoin:999999},{configurePending:true});
    assert.equal(Number((await f.p("SELECT reward_amount FROM user_message_rewards WHERE reward_type='COIN' LIMIT 1").first()).reward_amount),1234);
    assert.deepEqual((await f.p('SELECT DISTINCT user_id FROM user_messages ORDER BY user_id').all()).results.map(r=>Number(r.user_id)),[60,61]);
    assert.equal((await f.cup()).reward_status,'SENT');
  });
}

test('TEST mode never generates real messages, even after switching to ON',async t=>{
  const f=await fixture(t),s=settings({mode:'TEST',championsRewardsEnabled:true,championsCoin:300});
  await startChampions(f.env,f.season,s,await f.rank(),f.now);
  assert.equal((await championsBattleSettings(f.env,await f.fresh(),{...s,mode:'ON'})).mode,'TEST');
  await f.p("UPDATE clan_championships SET status='COMPLETED',winner_clan_id=6").run();
  await deliverChampionsRewards(f.env,7,{...s,mode:'ON'},{configurePending:true});
  assert.equal((await f.cup()).reward_status,'DISABLED_TEST');
  assert.equal(Number((await f.p('SELECT COUNT(*) count FROM user_messages').first()).count),0);
});

for(const reason of ['disabled','fewer teams','historical'])test(`${reason}: no unintended playoff or reward creation`,async t=>{
  const f=await fixture(t),s=settings({championsEnabled:reason!=='disabled'}),ranked=await f.rank();
  if(reason==='historical')await f.p("UPDATE clan_seasons SET phase='COMPLETE'").run();
  await startChampions(f.env,await f.fresh(),s,reason==='fewer teams'?ranked.slice(0,2):ranked,f.now);
  assert.equal((await f.fresh()).phase,'COMPLETE');assert.equal(await f.cup(),null);
  assert.equal(Number((await f.p('SELECT COUNT(*) count FROM clan_wars').first()).count),0);
  assert.equal(Number((await f.p('SELECT COUNT(*) count FROM user_messages').first()).count),0);
});

test('live/CMS expose the bracket, reward editor and scoped cache versions; no replacement combat engine',()=>{
  const client=read('js/clan-v1.js'),cms=read('admin/clan-war-admin-v1943.js'),server=read('functions/_clan.js');
  assert.match(client, /\['champions','05','챔피언스리그','CHAMPIONS'\]/);
  assert.match(client, /동점 시 정규시즌 상위 시드 진출/);
  assert.match(client, /global\.playPvpBattleV2Live/);
  assert.match(server, /championsMemberEligible\(env,season.id,user.id,mine.clan_id\)/);
  assert.match(server, /settings=await championsBattleSettings/);
  assert.match(cms, /cwChampionsMysticEnergy/);
  assert.match(cms, /SEND_CHAMPIONS_REWARDS/);
  assert.match(read('index.html'), /clan-champions-v2071.css\?v=2071-clan-champions/);
  assert.match(read('admin/index.html'), /clan-war-admin-v1943.js\?v=2071-clan-champions/);
});

test('bracket renderer handles empty, active and historical results without raw HTML/name injection',()=>{
  const code=read('js/clan-v1.js').replace('global.ClanV1={view,bind,stop,state};','global.ClanV1={championsView};');
  const sandbox={window:{},Date,Map,Number,String};vm.runInNewContext(code,sandbox);
  const render=sandbox.window.ClanV1.championsView;
  const empty=render({champions:{status:'UPCOMING'}});assert.match(empty,/정규시즌 1위/);assert.doesNotMatch(empty,/clan-cup-team is-winner/);
  const html=render({champions:{seeds:[{seed:1,clanId:1,name:'<img onerror=alert(1)>'}],status:'COMPLETED',winnerClanId:1,rewardStatus:'AWAITING_CONFIG'}});
  assert.doesNotMatch(html,/<img onerror/);assert.match(html,/&lt;img/);assert.match(html,/OWNER 보상 설정 대기/);
});
