import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {PGlite} from '@electric-sql/pglite';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import {__clanTest} from '../functions/_clan.js';
import {__postgresCompatTest} from '../functions/_postgres_d1_compat.js';
import {CLAN_RANKED_TEAMS_SQL} from '../functions/_clan_ranking.js';
import {CLAN_CAMP_HOURS,ensureClanCampSchema,clanCampSettlementStatements,clanCampStatusForUser,
  clanCampRoomState,sendClanCampChat,releaseClanCaptives,handleClanPrisonCamp} from '../functions/_clan_prison_camp.js';

const read=path=>readFileSync(new URL('../'+path,import.meta.url),'utf8');
const settings={...__clanTest.CLAN_ADMIN_SETTINGS_DEFAULTS,mode:'ON',rewardsEnabled:false,championsEnabled:false};
const season={id:7,season_no:3,phase:'SETTLEMENT'};
const owner={id:999,nickname:'운영자',role:'OWNER'},captive={id:201,nickname:'수감자',role:'USER'},visitor={id:101,nickname:'방문객',role:'USER'};
const date=ms=>new Date(ms).toISOString().slice(0,19).replace('T',' ');

async function fixture(t,postgres){
  const schema=[...__clanTest.FOUNDATION_SQL,
    'CREATE TABLE app_meta(key TEXT PRIMARY KEY,value TEXT,updated_at TEXT DEFAULT CURRENT_TIMESTAMP)',
    'CREATE TABLE users(id INTEGER PRIMARY KEY,nickname TEXT,role TEXT,coin INTEGER DEFAULT 0,card_shards INTEGER DEFAULT 0)',
    `CREATE TABLE clan_season_settlements(season_id INTEGER PRIMARY KEY,champion_clan_id INTEGER,status TEXT,reward_status TEXT,processing_token TEXT,updated_at TEXT DEFAULT CURRENT_TIMESTAMP,completed_at TEXT)`];
  let DB,failAt='',sql;
  if(postgres){
    sql=new PGlite();t.after(()=>sql.close());
    await sql.exec(`CREATE FUNCTION sqlite_now() RETURNS TEXT LANGUAGE SQL STABLE AS $$ SELECT to_char(timezone('UTC',CURRENT_TIMESTAMP),'YYYY-MM-DD HH24:MI:SS') $$;
      CREATE FUNCTION sqlite_datetime(VARIADIC parts text[]) RETURNS TEXT LANGUAGE SQL STABLE AS $$ SELECT to_char(timezone('UTC',CURRENT_TIMESTAMP)+COALESCE(parts[2]::interval,interval '0 seconds'),'YYYY-MM-DD HH24:MI:SS') $$;`);
    await sql.exec(schema.map(s=>s.replaceAll('INTEGER PRIMARY KEY AUTOINCREMENT','BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY').replaceAll('INTEGER','BIGINT').replaceAll('CURRENT_TIMESTAMP','sqlite_now()')).join(';'));
    DB=new __postgresCompatTest.PostgresD1Database({async query(input){const source=typeof input==='string'?input:input.text;if(failAt&&source.includes(failAt))throw new Error('INJECTED_FAILURE');const r=await sql.query(source,typeof input==='string'?[]:input.values||[]);return{...r,rowCount:r.affectedRows??r.rows.length}}});
  }else{
    sql=new DatabaseSync(':memory:');t.after(()=>sql.close());sql.exec(schema.join(';'));
    DB={prepare(source){return{source,values:[],bind(...v){this.values=v;return this},async first(){return sql.prepare(source).get(...this.values)||null},async all(){return{results:sql.prepare(source).all(...this.values)}},async run(){if(failAt&&source.includes(failAt))throw new Error('INJECTED_FAILURE');const r=sql.prepare(source).run(...this.values);return{meta:{changes:Number(r.changes),last_row_id:Number(r.lastInsertRowid)}}}}},async batch(stmts){sql.exec('BEGIN');try{const r=[];for(const s of stmts)r.push(await s.run());sql.exec('COMMIT');return r}catch(e){sql.exec('ROLLBACK');throw e}}};
  }
  const env={DB},p=(s,...v)=>DB.prepare(s).bind(...v),now=Math.floor(Date.now()/1000)*1000;
  await ensureClanCampSchema(env);await ensureClanCampSchema(env);
  await p("INSERT INTO clan_seasons(id,season_no,phase,registration_ends_at,draft_ends_at,starts_at,ends_at) VALUES(7,3,'SETTLEMENT',?,?,?,?)",...Array(4).fill(date(now))).run();
  for(const id of [1,2]){
    await p('INSERT INTO clan_organizations(id,name,mark_key) VALUES(?,?,?)',id,id===1?'DK':'DC',id===1?'DK':'DC').run();
    await p('INSERT INTO clan_season_teams(season_id,clan_id,master_user_id,draft_position,score,wins) VALUES(7,?,?,?,?,?)',id,id*100+1,id,id===1?21:3,id===1?7:1).run();
    for(let i=1;i<=22;i++){
      await p('INSERT INTO users(id,nickname,role) VALUES(?,?,?)',id*100+i,'클랜원'+(id*100+i),i===22?'OWNER':'USER').run();
      await p('INSERT INTO clan_members(season_id,clan_id,user_id,member_role) VALUES(7,?,?,?)',id,id*100+i,i===1?'MASTER':'MEMBER').run();
    }
  }
  await p("INSERT INTO users(id,nickname,role) VALUES(999,'운영자','OWNER')").run();
  await p("INSERT INTO clan_wars(id,season_id,round_no,clan_a_id,clan_b_id,status,starts_at,ends_at,score_a,score_b) VALUES(1,7,1,1,2,'COMPLETED',?,?,20000,10000)",date(now-3600000),date(now-1000)).run();
  const ranks=(await p(CLAN_RANKED_TEAMS_SQL,7).all()).results;
  return{env,p,now,ranks,fail(value){failAt=value},async sentence(){const statements=await clanCampSettlementStatements(env,season,settings,ranks,now);await DB.batch(statements)}};
}

for(const pg of [false,true]){
  const label=pg?'PostgreSQL':'SQLite';
  test(`${label}: actual season settlement captures all 22 last-place members, including master/OWNER, exactly once`,async t=>{
    const f=await fixture(t,pg);await __clanTest.settleSeason(f.env,season,settings);
    const camp=await f.p('SELECT * FROM clan_prison_camps').first();
    assert.equal(Number(camp.clan_id),2);assert.equal(Number(camp.final_rank),2);assert.equal(CLAN_CAMP_HOURS,8);
    assert.equal(Date.parse(camp.jailed_until.replace(' ','T')+'Z')-Date.parse(camp.jailed_at.replace(' ','T')+'Z'),28800000);
    assert.equal(Number((await f.p('SELECT COUNT(*) n FROM clan_prison_captives').first()).n),22);
    assert.equal((await clanCampStatusForUser(f.env,201)).incarcerated,true);
    assert.equal((await clanCampStatusForUser(f.env,222)).incarcerated,true);
    assert.equal((await clanCampStatusForUser(f.env,101)).incarcerated,false);
    await releaseClanCaptives(f.env,owner,{seasonId:7,userId:201});
    await f.p('DELETE FROM clan_members WHERE user_id=202').run();
    await f.p("UPDATE clan_members SET clan_id=2 WHERE user_id=101").run();
    await __clanTest.settleSeason(f.env,season,settings);
    await f.env.DB.batch(await clanCampSettlementStatements(f.env,season,settings,f.ranks,f.now+10000));
    assert.equal((await clanCampStatusForUser(f.env,201)).incarcerated,false);
    assert.equal((await clanCampStatusForUser(f.env,202)).incarcerated,true);
    assert.equal((await clanCampStatusForUser(f.env,101)).incarcerated,false);
    assert.equal((await f.p('SELECT jailed_until FROM clan_prison_camps').first()).jailed_until,camp.jailed_until);
  });
  test(`${label}: failure rolls back camp, roster and season completion; retry cannot partially jail`,async t=>{
    const f=await fixture(t,pg);f.fail('INSERT INTO clan_prison_captives');
    // The SQLite source still contains OR IGNORE before PostgreSQL translation.
    if(!pg)f.fail('INSERT OR IGNORE INTO clan_prison_captives');
    await assert.rejects(__clanTest.settleSeason(f.env,season,settings),/INJECTED_FAILURE/);
    f.fail('');assert.equal(Number((await f.p('SELECT COUNT(*) n FROM clan_prison_camps').first()).n),0);
    assert.equal((await f.p('SELECT status FROM clan_season_settlements').first()).status,'PROCESSING');
    await f.p('UPDATE clan_season_settlements SET updated_at=?',date(f.now-120000)).run();
    await __clanTest.settleSeason(f.env,season,settings);
    assert.equal(Number((await f.p('SELECT COUNT(*) n FROM clan_prison_captives').first()).n),22);
    assert.equal((await f.p('SELECT status FROM clan_season_settlements').first()).status,'COMPLETED');
  });
  test(`${label}: eight-hour boundary and OWNER individual/all release are enforced server-side`,async t=>{
    const f=await fixture(t,pg);await f.sentence();
    assert.equal((await clanCampStatusForUser(f.env,201,f.now+28800000-1)).incarcerated,true);
    assert.equal((await clanCampStatusForUser(f.env,201,f.now+28800000)).incarcerated,false);
    await assert.rejects(releaseClanCaptives(f.env,visitor,{seasonId:7,userId:201}),e=>e.status===403);
    await assert.rejects(releaseClanCaptives(f.env,{role:'ADMIN'},{seasonId:7}),e=>e.status===403);
    await assert.rejects(releaseClanCaptives(f.env,owner,{seasonId:7,userId:0}),e=>e.status===400);
    assert.equal((await releaseClanCaptives(f.env,owner,{seasonId:7,userId:201},f.now)).releasedCount,1);
    assert.equal((await releaseClanCaptives(f.env,owner,{seasonId:7,userId:201},f.now)).releasedCount,0);
    const receipt=await f.p('SELECT * FROM clan_prison_captives WHERE user_id=201').first();assert.equal(Number(receipt.released_by),999);assert.equal(receipt.release_reason,'운영자 석방');
    assert.equal((await releaseClanCaptives(f.env,owner,{seasonId:7},f.now)).releasedCount,21);
    assert.equal((await clanCampRoomState(f.env,visitor,{incarcerated:false},f.now)).chatEnabled,false);
  });
  test(`${label}: chat records captive/visitor roles, Unicode length, cooldown, closed room and rollback`,async t=>{
    const f=await fixture(t,pg);await f.sentence();
    await sendClanCampChat(f.env,captive,{body:'<img onerror=alert(1)> 포로 메시지'},f.now);
    await sendClanCampChat(f.env,visitor,{body:'면회\n왔어요'},f.now);
    let state=await clanCampRoomState(f.env,visitor,{incarcerated:false},f.now);
    assert.equal(state.messages[0].senderWasCaptive,true);assert.equal(state.messages[1].senderWasCaptive,false);
    assert.equal(state.messages[1].body,'면회 왔어요');assert.equal(state.inmates.length,22);
    await assert.rejects(sendClanCampChat(f.env,captive,{body:'연속 전송'},f.now+1999),e=>e.status===429);
    await sendClanCampChat(f.env,captive,{body:'😀'.repeat(200)},f.now+2000);
    await assert.rejects(sendClanCampChat(f.env,captive,{body:'😀'.repeat(201)},f.now+4000),e=>e.status===400);
    f.fail('DELETE FROM clan_prison_chat');
    await assert.rejects(sendClanCampChat(f.env,captive,{body:'실패'},f.now+4000),/INJECTED_FAILURE/);f.fail('');
    await sendClanCampChat(f.env,captive,{body:'재시도 성공'},f.now+4000);
    await releaseClanCaptives(f.env,owner,{seasonId:7},f.now+5000);
    await assert.rejects(sendClanCampChat(f.env,captive,{body:'폐쇄 이후'},f.now+8000),e=>e.status===409);
  });
  test(`${label}: TEST/OFF, unplayed, incomplete and single-team seasons do not sentence; ranking ties reuse official order`,async t=>{
    const f=await fixture(t,pg);
    for(const mode of ['OFF','TEST'])assert.deepEqual(await clanCampSettlementStatements(f.env,season,{...settings,mode},f.ranks),[]);
    assert.deepEqual(await clanCampSettlementStatements(f.env,{...season,phase:'ACTIVE'},settings,f.ranks),[]);
    assert.deepEqual(await clanCampSettlementStatements(f.env,season,settings,f.ranks.slice(0,1)),[]);
    await f.p('UPDATE clan_season_teams SET score=3,wins=1').run();
    await f.p('UPDATE clan_wars SET score_a=1000,score_b=2000').run();
    const ranks=(await f.p(CLAN_RANKED_TEAMS_SQL,7).all()).results;
    assert.equal(Number(ranks.at(-1).clan_id),1);
    await f.env.DB.batch(await clanCampSettlementStatements(f.env,season,settings,ranks,f.now));
    assert.equal((await clanCampStatusForUser(f.env,101,f.now)).incarcerated,true);
    assert.equal((await clanCampStatusForUser(f.env,201,f.now)).incarcerated,false);
    await f.p("UPDATE clan_wars SET status='CANCELLED'").run();
    assert.deepEqual(await clanCampSettlementStatements(f.env,season,settings,ranks),[]);
  });
}

test('HTTP routes require authentication, enforce release permission, and keep disciplinary inmates in their own prison',async t=>{
  const f=await fixture(t,false);await f.sentence();
  const json=(data,status=200)=>new Response(JSON.stringify(data),{status});
  const call=(path,method,user,body={},statusFn=clanCampStatusForUser)=>handleClanPrisonCamp({path:'prison-camp/'+path,request:new Request('http://local/'+path,{method,...(method==='POST'?{body:JSON.stringify(body)}:{})}),env:f.env,deps:{authenticate:async()=>user,readBody:r=>r.json(),json,prisonStatusForUser:statusFn}});
  assert.equal((await call('status','GET',null)).status,401);
  assert.equal((await call('release','POST',visitor,{seasonId:7})).status,403);
  assert.equal((await call('status','GET',captive,{},async()=>({incarcerated:true}))).status,423);
  assert.equal((await call('status','DELETE',visitor)).status,405);
  const room=await (await call('status','GET',captive)).json();assert.equal(room.prison.facility,'CLAN_CAMP');assert.equal(room.canRelease,false);
});

test('live menu, lock screen, common API guard and release gate include the camp; player text is escaped',()=>{
  const app=read('js/app.js'),api=read('functions/api/[[path]].js'),index=read('index.html'),source=read('js/clan-prison-camp-v2083.js');
  assert.match(app,/prisoncamp:\(user\)=>window.ClanPrisonCamp.view\(user\)/);
  assert.match(app,/if\(tab==='prisoncamp'\)window.ClanPrisonCamp\?\.bind\(loadUser\(\)\)/);
  assert.match(app,/facility==='CLAN_CAMP'&&window.ClanPrisonCamp/);
  assert.match(api,/return status.incarcerated\?status:await clanCampStatusForUser\(env,userId\)/);
  assert.ok(api.indexOf('handleClanPrisonCamp({path')<api.indexOf('const prisonExempt='));
  assert.match(api,/await reconcileClanCampSeason\(env\)/);
  const navigation=app.match(/function navGroupForTab\(tab\)\{[\s\S]*?\n\}/)[0];
  assert.equal(vm.runInNewContext(navigation+";navGroupForTab('prisoncamp')"),'administration');
  assert.match(index,/clan-prison-camp-v2083.css/);assert.match(index,/clan-prison-camp-v2083.js/);
  assert.match(read('js/soopketmon-v21-exact-shell-adapter.js'),/title: '포로수용소', group: 'administration'/);
  assert.match(read('js/soopketmon-v21-runtime-router.js'),/prisoncamp: \{ shell: 'prisoncamp' \}/);
  assert.match(JSON.parse(read('package.json')).scripts['test:prison'],/clan-prison-camp-v2083/);
  assert.match(source,/esc\(row.body\)/);assert.match(source,/esc\(row.nickname\)/);
  const context={window:{}};vm.runInNewContext(source,context);
  const html=context.window.ClanPrisonCamp.view({},true);assert.match(html,/포로수용소/);assert.doesNotMatch(html,/data-camp-exit/);
  assert.ok(readFileSync(new URL('../assets/ui/prison/clan-camp-block-v2083.png',import.meta.url)).length>100000);
});
