import test from 'node:test';
import assert from 'node:assert/strict';
import {PGlite} from '@electric-sql/pglite';
import {__clanTest as clan} from '../functions/_clan.js';
import {removeMild7FromDc} from '../scripts/ops/clan-dc-mild7-remove-20260929.mjs';
async function fixture(t){
  const pg=new PGlite();t.after(()=>pg.close());
  await pg.exec(clan.FOUNDATION_SQL.map(s=>s.replaceAll('INTEGER PRIMARY KEY AUTOINCREMENT','BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY').replaceAll('INTEGER','BIGINT').replaceAll('CURRENT_TIMESTAMP',"'2026-09-29 12:26:48'")).join(';'));
  await pg.exec("CREATE TABLE app_meta(key TEXT PRIMARY KEY,value TEXT); CREATE TABLE users(id BIGINT PRIMARY KEY,nickname TEXT,role TEXT,status TEXT); CREATE TABLE admin_logs(admin_id BIGINT,action_type TEXT,target_type TEXT,target_id TEXT,before_data TEXT,after_data TEXT); CREATE TABLE clan_faction_state(season_id BIGINT PRIMARY KEY,revision INTEGER,state_json TEXT,last_action TEXT)");
  const client={async query(sql,args=[]){const r=await pg.query(sql,args);return{...r,rowCount:r.affectedRows??r.rows.length}}};
  await pg.exec("INSERT INTO users VALUES(1,'OWNER','OWNER','ACTIVE'),(290,'Mild7','USER','ACTIVE'); INSERT INTO clan_seasons(id,season_no,phase,registration_ends_at,draft_ends_at,starts_at,ends_at,draft_pick_count) VALUES(6,3,'ACTIVE','2026-09-29T12:26:49Z','2026-09-29T13:26:49Z','2026-10-01T12:00:00Z','2026-10-11T13:00:00Z',617); INSERT INTO clan_season_teams(season_id,clan_id,master_user_id,draft_position) VALUES(6,8,3011,7); INSERT INTO clan_members(season_id,clan_id,user_id,member_role,draft_pick_no) VALUES(6,8,290,'MEMBER',0),(6,8,3011,'MASTER',57),(6,8,71,'MEMBER',56); INSERT INTO clan_draft_pool(season_id,user_id,candidate_key,status,drafted_clan_id,pick_no) VALUES(6,290,'target','DRAFTED',8,0),(6,3011,'master','MASTER',8,57),(6,71,'other','DRAFTED',8,56)");
  await client.query("INSERT INTO app_meta VALUES('clan_redraft_v20260916:6',$1)",[JSON.stringify({quotas:{8:18}})]);
  await client.query("INSERT INTO clan_faction_state VALUES(6,2,$1,'scheduler')",[JSON.stringify({formations:{8:{a:[290,3011]},7:{b:[777]}},captains:{8:{a:290}},battles:[],pools:{8:5000}})]);
  const snapshot=async()=>Object.fromEntries(await Promise.all(['clan_seasons','clan_season_teams','clan_members','clan_draft_pool','clan_faction_state','app_meta','admin_logs'].map(async table=>[table,(await client.query(`SELECT row_to_json(t) row FROM ${table} t ORDER BY row_to_json(t)::text`)).rows.map(r=>r.row)])));
  return{client,snapshot};
}
test('only Mild7 is removed; captain and formation references clear, leadership and quota persist, replay is harmless',async t=>{
  const f=await fixture(t),before=await f.snapshot();await removeMild7FromDc(f.client,{dryRun:true});assert.deepEqual(await f.snapshot(),before);
  const result=await removeMild7FromDc(f.client);assert.equal(result.receipt.afterCount,2);
  const after=await f.snapshot();assert.deepEqual(after.clan_seasons,before.clan_seasons);assert.deepEqual(after.clan_season_teams,before.clan_season_teams);
  assert.equal(after.clan_draft_pool.find(p=>p.user_id===290).status,'WITHDRAWN');
  const faction=JSON.parse(after.clan_faction_state[0].state_json);assert.deepEqual(faction.formations[8].a,[3011]);assert.deepEqual(faction.captains[8],{});assert.equal(faction.pools[8],5000);assert.deepEqual(faction.formations[7],{b:[777]});
  assert.equal((await removeMild7FromDc(f.client)).replayed,true);assert.deepEqual(await f.snapshot(),after);
});
test('audit failure rolls back all membership, pool and faction changes; retry completes once',async t=>{
  const f=await fixture(t),before=await f.snapshot(),query=f.client.query.bind(f.client);f.client.query=(sql,args)=>sql.startsWith('INSERT INTO admin_logs')?Promise.reject(Error('audit failed')):query(sql,args);
  await assert.rejects(removeMild7FromDc(f.client),/audit failed/);assert.deepEqual(await f.snapshot(),before);f.client.query=query;assert.equal((await removeMild7FromDc(f.client)).receipt.removedUserId,290);
});
test('changed master or ongoing battle blocks removal with no partial writes',async t=>{
  const f=await fixture(t);await f.client.query('UPDATE clan_season_teams SET master_user_id=290');const changed=await f.snapshot();await assert.rejects(removeMild7FromDc(f.client),/DC master/);assert.deepEqual(await f.snapshot(),changed);
  await f.client.query('UPDATE clan_season_teams SET master_user_id=3011');await f.client.query("INSERT INTO clan_wars(season_id,clan_a_id,clan_b_id,status,starts_at,ends_at) VALUES(6,8,7,'ACTIVE','2026-09-29T13:00:00Z','2026-09-29T14:00:00Z')");const busy=await f.snapshot();await assert.rejects(removeMild7FromDc(f.client),/Clan war is active/);assert.deepEqual(await f.snapshot(),busy);
});
