import test from 'node:test';
import assert from 'node:assert/strict';
import {PGlite} from '@electric-sql/pglite';
import {__clanTest as clan} from '../functions/_clan.js';
import {restartBalancedClanDraft,EMPTY_TABLES,OPERATION_KEY,PRESERVED_MASTERS,ADDED_MASTER} from '../scripts/ops/clan-balanced-redraft-20260929.mjs';

const now=Date.parse('2026-09-29T12:20:00Z');
async function fixture(t){
  const pg=new PGlite();t.after(()=>pg.close());
  const schema=clan.FOUNDATION_SQL.map(s=>s.replaceAll('INTEGER PRIMARY KEY AUTOINCREMENT','BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY').replaceAll('INTEGER','BIGINT').replaceAll('CURRENT_TIMESTAMP',"'2026-09-29 12:00:00'"));
  await pg.exec(schema.join(';'));
  for(const table of EMPTY_TABLES.filter(name=>!['clan_wars','clan_war_battles'].includes(name)))await pg.exec(`CREATE TABLE ${table}(season_id BIGINT)`);
  await pg.exec("CREATE TABLE app_meta(key TEXT PRIMARY KEY,value TEXT,updated_at TEXT); CREATE TABLE users(id BIGINT PRIMARY KEY,nickname TEXT,role TEXT,status TEXT); CREATE TABLE clan_faction_state(season_id BIGINT PRIMARY KEY,revision INTEGER,state_json TEXT,last_action TEXT); CREATE TABLE admin_logs(admin_id BIGINT,action_type TEXT,target_type TEXT,target_id TEXT,before_data TEXT,after_data TEXT)");
  const client={async query(sql,values=[]){const r=await pg.query(sql,values);return{...r,rowCount:r.affectedRows??r.rows.length}}};
  // PGlite executes multiple SET statements through exec, like PostgreSQL's simple query.
  const query=client.query.bind(client);client.query=async(sql,values=[])=>sql.startsWith('SET LOCAL lock_timeout')?(await pg.exec(sql))[0]:query(sql,values);
  await client.query("INSERT INTO users VALUES(1,'QA OWNER','OWNER','ACTIVE')");
  await client.query("INSERT INTO app_meta(key,value) VALUES('clan_settings_v1',$1)",[JSON.stringify({mode:'ON',draftPickSeconds:30,openDays:[0,2,4,6],warOpenTime:'21:00',warDurationMinutes:60})]);
  await client.query("INSERT INTO clan_seasons(id,season_no,phase,registration_ends_at,draft_ends_at,starts_at,ends_at,draft_pick_count,next_pick_deadline) VALUES(6,3,'DRAFT','2026-09-29T12:00:00.000Z','2026-09-29T13:00:00.000Z','2026-09-29T13:00:00.000Z','2026-10-06T13:00:00.000Z',70,'2026-09-29T12:20:25.000Z')");
  await client.query('INSERT INTO clan_faction_state VALUES(6,2,$1,$2)',[JSON.stringify({districts:[{owner:0,defense:'',protectedUntil:0,taxRemainder:0}],formations:{},captains:{},battles:[],events:[],sessionPlan:[{status:'SKIPPED',reason:'UNAVAILABLE_WINDOW'}]}),'scheduler-skip-token']);
  for(let i=0;i<8;i++)await client.query('INSERT INTO clan_organizations(id,name,mark_key) VALUES($1,$2,$3)',[i+1,clan.OFFICIAL_CLAN_CATALOG[i].name,clan.OFFICIAL_CLAN_CATALOG[i].markKey]);
  const ids=[...PRESERVED_MASTERS,ADDED_MASTER,...Array.from({length:132},(_,i)=>10001+i)];
  for(let i=0;i<ids.length;i++){
    const master=i<7,drafted=i>=7&&i<17,status=master?'MASTER':drafted?'DRAFTED':'AVAILABLE',clanId=master?i+1:drafted?2:null;
    await client.query('INSERT INTO clan_draft_pool(season_id,user_id,candidate_key,status,drafted_clan_id,pick_no,master_score,preferred_role) VALUES(6,$1,$2,$3,$4,$5,$6,$7)',[ids[i],'old-'+ids[i],status,clanId,master?0:drafted?i-6:null,master?1000:ids[i]===ADDED_MASTER?900:500,'ATTACK']);
    if(master)await client.query('INSERT INTO clan_season_teams(season_id,clan_id,master_user_id,draft_position) VALUES(6,$1,$2,$3)',[i+1,ids[i],i]);
    if(master||drafted)await client.query('INSERT INTO clan_members(season_id,clan_id,user_id,member_role,preferred_role,draft_pick_no) VALUES(6,$1,$2,$3,$4,$5)',[clanId,ids[i],master?'MASTER':'MEMBER','ATTACK',master?0:i-6]);
  }
  const snapshot=async()=>Object.fromEntries(await Promise.all(['clan_seasons','clan_season_teams','clan_members','clan_draft_pool','app_meta','admin_logs','clan_faction_state','clan_draft_locks'].map(async table=>[table,(await client.query(`SELECT row_to_json(t) AS row FROM ${table} t ORDER BY row_to_json(t)::text`)).rows.map(r=>r.row)])));
  return{client,snapshot};
}

test('audited restart preserves seven masters, adds the next candidate and invalidates all old picks atomically',async t=>{
  const f=await fixture(t),before=await f.snapshot();
  const dry=await restartBalancedClanDraft(f.client,{dryRun:true,now});assert.equal(dry.receipt.invalidatedPicks,10);assert.deepEqual(await f.snapshot(),before);
  const result=await restartBalancedClanDraft(f.client,{now});assert.equal(result.receipt.addedMaster.userId,ADDED_MASTER);
  assert.deepEqual(Object.values(result.receipt.quotas).sort((a,b)=>a-b),[17,17,17,17,18,18,18,18]);
  const after=await f.snapshot();assert.equal(after.clan_members.length,8);assert.equal(after.clan_draft_pool.filter(p=>p.status==='AVAILABLE').length,132);
  assert.equal(after.clan_seasons[0].draft_pick_count,0);assert.equal(after.clan_seasons[0].draft_ends_at,'2026-09-29T13:20:00.000Z');
  assert.ok(after.app_meta.some(r=>r.key===OPERATION_KEY+':before'));assert.equal(after.admin_logs.length,1);assert.equal(after.clan_draft_locks.length,0);
  await f.client.query('UPDATE clan_seasons SET draft_pick_count=1 WHERE id=6');
  assert.equal((await restartBalancedClanDraft(f.client,{now:now+1000})).replayed,true);
  assert.equal((await f.client.query('SELECT draft_pick_count FROM clan_seasons WHERE id=6')).rows[0].draft_pick_count,1);
});

test('audit failure rolls back reset, master addition, candidate keys, archive and lock; retry succeeds',async t=>{
  const f=await fixture(t),before=await f.snapshot(),query=f.client.query.bind(f.client);
  f.client.query=(sql,args)=>sql.startsWith('INSERT INTO admin_logs')?Promise.reject(Error('injected audit failure')):query(sql,args);
  await assert.rejects(restartBalancedClanDraft(f.client,{now}),/injected audit/);assert.deepEqual(await f.snapshot(),before);
  f.client.query=query;assert.equal((await restartBalancedClanDraft(f.client,{now})).replayed,false);
});

test('in-flight picks, changed masters and existing battle activity reject a reset without partial writes',async t=>{
  const f=await fixture(t);
  await f.client.query("INSERT INTO clan_draft_locks(season_id,token,expires_at) VALUES(6,'active-pick','2026-09-29T12:20:30.000Z')");
  const busy=await f.snapshot();await assert.rejects(restartBalancedClanDraft(f.client,{now}),/DRAFT_BUSY/);assert.deepEqual(await f.snapshot(),busy);
  await f.client.query('DELETE FROM clan_draft_locks');await f.client.query('UPDATE clan_season_teams SET master_user_id=999 WHERE clan_id=1');
  const changed=await f.snapshot();await assert.rejects(restartBalancedClanDraft(f.client,{now}),/Existing masters changed/);assert.deepEqual(await f.snapshot(),changed);
  await f.client.query('UPDATE clan_season_teams SET master_user_id=$1 WHERE clan_id=1',[PRESERVED_MASTERS[0]]);await f.client.query('INSERT INTO clan_participation_progress VALUES(6)');
  const active=await f.snapshot();await assert.rejects(restartBalancedClanDraft(f.client,{now}),/already has season activity/);assert.deepEqual(await f.snapshot(),active);
});
