import test from 'node:test';
import assert from 'node:assert/strict';
import {PGlite} from '@electric-sql/pglite';
import {__clanTest as clan} from '../functions/_clan.js';
import {transferDkMaster,OPERATION_KEY} from '../scripts/ops/clan-dk-master-transfer-20261001.mjs';
const now=Date.parse('2026-10-01T11:43:00Z');
async function fixture(t){
 const pg=new PGlite();t.after(()=>pg.close());
 await pg.exec(clan.FOUNDATION_SQL.map(s=>s.replaceAll('INTEGER PRIMARY KEY AUTOINCREMENT','BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY').replaceAll('INTEGER','BIGINT').replaceAll('CURRENT_TIMESTAMP',"'2026-09-29 12:40:21'")).join(';'));
 await pg.exec("CREATE TABLE app_meta(key TEXT PRIMARY KEY,value TEXT); CREATE TABLE users(id BIGINT PRIMARY KEY,nickname TEXT,role TEXT,status TEXT); CREATE TABLE admin_logs(admin_id BIGINT,action_type TEXT,target_type TEXT,target_id TEXT,before_data TEXT,after_data TEXT)");
 const client={async query(sql,args=[]){const r=await pg.query(sql,args);return {...r,rowCount:r.affectedRows??r.rows.length};}};
 await pg.exec("INSERT INTO users VALUES(1,'OWNER','OWNER','ACTIVE'),(360,'라피e','USER','ACTIVE'),(521,'대저동토마토','USER','ACTIVE'); INSERT INTO clan_organizations(id,name,is_active) VALUES(1,'DK',1); INSERT INTO clan_seasons(id,season_no,phase,registration_ends_at,draft_ends_at,starts_at,ends_at,draft_pick_count,next_pick_deadline) VALUES(6,3,'ACTIVE','2026-09-29T12:26:49.107Z','2026-09-29T13:26:49.107Z','2026-09-29T13:00:00Z','2026-10-06T13:00:00Z',520,'2026-09-29T13:22:30Z'); INSERT INTO clan_season_teams(season_id,clan_id,master_user_id,draft_position) VALUES(6,1,360,0),(6,7,4235,6); INSERT INTO clan_members(season_id,clan_id,user_id,member_role,draft_pick_no,contribution_score,battle_wins) VALUES(6,1,360,'MASTER',0,32,8),(6,1,521,'MEMBER',57,28,7),(6,1,71,'MEMBER',56,99,15); INSERT INTO clan_draft_pool(season_id,user_id,candidate_key,status,drafted_clan_id,pick_no) VALUES(6,360,'old-master','MASTER',1,0),(6,521,'new-master','DRAFTED',1,57),(6,71,'other-member','DRAFTED',1,56)");
 await client.query('INSERT INTO app_meta(key,value) VALUES($1,$2)',['clan_redraft_v20260916:6',JSON.stringify({quotas:{1:18}})]);
 const snapshot=async()=>Object.fromEntries(await Promise.all(['clan_seasons','clan_season_teams','clan_members','clan_draft_pool','clan_draft_locks','app_meta','admin_logs'].map(async table=>[table,(await client.query(`SELECT row_to_json(t) row FROM ${table} t ORDER BY row_to_json(t)::text`)).rows.map(r=>r.row)])));
 return {client,snapshot};
}
test('DK handover preserves picks, scores, members and schedule; dry-run and retry are safe',async t=>{
 const f=await fixture(t),before=await f.snapshot();await transferDkMaster(f.client,{dryRun:true,now});assert.deepEqual(await f.snapshot(),before);
 const result=await transferDkMaster(f.client,{now});assert.equal(result.receipt.to.userId,521);assert.equal(result.receipt.from.role,'MEMBER');
 const after=await f.snapshot();assert.deepEqual(after.clan_seasons,before.clan_seasons);assert.equal(after.clan_members.length,3);assert.equal(after.clan_draft_locks.length,0);assert.equal(after.admin_logs.length,1);
 assert.equal(after.clan_members.find(m=>m.user_id===521).draft_pick_no,57);assert.equal(after.clan_members.find(m=>m.user_id===521).contribution_score,28);assert.equal(after.clan_members.find(m=>m.user_id===360).battle_wins,8);
 assert.ok(after.app_meta.some(r=>r.key===OPERATION_KEY+':before'));
 assert.equal((await transferDkMaster(f.client,{now:now+1})).replayed,true);assert.deepEqual(await f.snapshot(),after);
});
test('a late audit failure rolls back every leadership write and a retry succeeds',async t=>{
 const f=await fixture(t),before=await f.snapshot(),query=f.client.query.bind(f.client);
 f.client.query=(sql,args)=>sql.startsWith('INSERT INTO admin_logs')?Promise.reject(Error('audit failed')):query(sql,args);
 await assert.rejects(transferDkMaster(f.client,{now}),/audit failed/);assert.deepEqual(await f.snapshot(),before);
 f.client.query=query;assert.equal((await transferDkMaster(f.client,{now})).receipt.to.userId,521);
});
test('draft activity, a changed master and a wrong-clan target cannot partially change leadership',async t=>{
 const f=await fixture(t);await f.client.query('INSERT INTO clan_draft_locks(season_id,token,expires_at) VALUES(6,$1,$2)',['busy',new Date(now+10000).toISOString()]);
 const busy=await f.snapshot();await assert.rejects(transferDkMaster(f.client,{now}),/DRAFT_BUSY/);assert.deepEqual(await f.snapshot(),busy);
 await f.client.query('DELETE FROM clan_draft_locks');await f.client.query('UPDATE clan_season_teams SET master_user_id=99 WHERE clan_id=1');
 const changed=await f.snapshot();await assert.rejects(transferDkMaster(f.client,{now}),/DK master changed/);assert.deepEqual(await f.snapshot(),changed);
 await f.client.query('UPDATE clan_season_teams SET master_user_id=360 WHERE clan_id=1');await f.client.query('UPDATE clan_members SET clan_id=7 WHERE user_id=521');
 const wrong=await f.snapshot();await assert.rejects(transferDkMaster(f.client,{now}),/Target must already belong to DK/);assert.deepEqual(await f.snapshot(),wrong);
});
