import fs from 'node:fs';import assert from 'node:assert/strict';import os from 'node:os';import path from 'node:path';
import {pathToFileURL} from 'node:url';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE?pathToFileURL(process.env.PLAYWRIGHT_MODULE).href:'playwright');
const base=process.env.FACTION_QA_ORIGIN||'http://127.0.0.1:8963';
const output=fs.mkdtempSync(path.join(os.tmpdir(),'faction-sessions-review-'));
const browser=await chromium.launch({channel:'chrome',headless:true}),checks=[],errors=[];
const check=(value,name)=>{assert.ok(value,name);checks.push(name);};
try{
 for(const viewport of [{width:1440,height:1000},{width:390,height:844},{width:320,height:740}]){
  await fetch(base+'/api/preview/reset',{method:'POST'});
  const page=await browser.newPage({viewport,serviceWorkers:'block'}),requests=[];page.on('pageerror',error=>errors.push(error.message));page.on('request',request=>requests.push(request.url()));
  await page.goto(base+'/preview/clan-faction-v1/');await page.locator('.fw-session-strip').waitFor();
  await page.evaluate(()=>document.fonts.ready);
  check(await page.locator('.fw-zone').count()===25,`${viewport.width}: original map retained`);
  check(await page.locator('.fw-session-times>div').count()===2,`${viewport.width}: two schedules`);
  check((await page.locator('.fw-stats').textContent()).includes('300억'),`${viewport.width}: reward visible`);
  check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`${viewport.width}: no page overflow`);
  await page.screenshot({path:path.join(output,`map-${viewport.width}.png`),fullPage:true});
  await page.locator('.fw-map-panel').scrollIntoViewIfNeeded();
  await page.screenshot({path:path.join(output,`map-scrolled-${viewport.width}.png`)});
  await page.locator('.fw-detail').scrollIntoViewIfNeeded();
  await page.screenshot({path:path.join(output,`detail-${viewport.width}.png`)});
  await page.locator('[data-fw-tab="treasury"]').first().click();await page.locator('.fw-vault strong').waitFor();
  check((await page.locator('.fw-vault').textContent()).includes('300억'),`${viewport.width}: 300억 reward tab`);
  check(await page.locator('[data-fw-collect]').count()===0,`${viewport.width}: no tax collection action`);
  const requestStart=requests.length;await fetch(base+'/api/preview/session?phase=end',{method:'POST'});
  if(viewport.width!==390)await page.locator('[data-fw-reload]').first().click();
  await page.locator('.fw-session-result').first().waitFor();
  check((await page.locator('.fw-session-result').first().textContent()).includes('300억'),`${viewport.width}: delivered result`);
  if(viewport.width===390)check(requests.slice(requestStart).every(url=>!url.includes('/api/clan/faction/alerts')),'visible session polling reuses overview alerts without duplicate lifecycle calls');
  await page.locator('.fw-session-result').first().scrollIntoViewIfNeeded();
  await page.screenshot({path:path.join(output,`rewards-${viewport.width}.png`),fullPage:true});
  await fetch(base+'/api/preview/session?phase=closed',{method:'POST'});await page.locator('[data-fw-reload]').first().click();
  await page.locator('.fw-session-strip h3').filter({hasText:'종료'}).waitFor();
  await page.locator('[data-fw-tab="map"]').first().click();
  check(await page.locator('[data-fw-launch]').isDisabled(),`${viewport.width}: closed session cannot launch`);
  await page.locator('[data-fw-tab="formation"]').first().click();
  check(await page.locator('[data-fw-save]').isEnabled(),`${viewport.width}: lineup editable while waiting`);
  await fetch(base+'/api/preview/reset',{method:'POST'});await fetch(base+'/api/preview/session?phase=territory',{method:'POST'});
  await page.reload();await page.locator('.fw-session-strip h3').filter({hasText:'영토전'}).waitFor();
  check(await page.locator('[data-fw-launch]').isDisabled(),`${viewport.width}: territory war blocks launch`);
  check((await page.locator('.fw-session-pause').textContent()).includes('재개 후'),`${viewport.width}: paused session shows remaining play time`);
  await page.locator('.fw-session-strip').scrollIntoViewIfNeeded();
  await page.screenshot({path:path.join(output,`paused-${viewport.width}.png`)});
  await fetch(base+'/api/preview/session?phase=resume',{method:'POST'});await page.locator('[data-fw-reload]').first().click();
  // Do not match the old "영토전 진행 중" paused heading before the refresh arrives.
  await page.locator('.fw-session-strip h3').filter({hasText:/^세력전 .*진행 중$/}).waitFor();
  check((await page.locator('.fw-session-pause').textContent()).includes('종료 후 재개'),`${viewport.width}: resumed schedule is visible`);
  check(await page.locator('[data-fw-launch]').isEnabled(),`${viewport.width}: resumed session reopens combat`);
  await fetch(base+'/api/preview/session?phase=deferred',{method:'POST'});await page.locator('[data-fw-reload]').first().click();
  await page.locator('.fw-session-queue').waitFor();
  check((await page.locator('.fw-session-times').textContent()).includes('순연'),`${viewport.width}: overlapping second round is queued, not skipped`);
  await fetch(base+'/api/preview/session?phase=end',{method:'POST'});await page.locator('[data-fw-reload]').first().click();
  await page.locator('.fw-session-strip h3').filter({hasText:'2회차 진행 중'}).waitFor();
  const deferred=await (await fetch(base+'/api/clan/faction/overview')).json();
  check(deferred.sessions.current.endsAt-deferred.sessions.current.startsAt===10800000,`${viewport.width}: deferred second round receives a full 3h`);
  await page.locator('.fw-session-strip').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(output,`deferred-${viewport.width}.png`)});
  await page.close();
 }
 check(errors.length===0,'No browser exceptions: '+errors.join('; '));
 console.log(JSON.stringify({passed:checks.length,errors,output}));
}finally{await browser.close();}
