import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {PGlite} from '@electric-sql/pglite';
import {readFileSync} from 'node:fs';
import {__clanTest as clan,reconcileClanDraft} from '../functions/_clan.js';
import {__postgresCompatTest} from '../functions/_postgres_d1_compat.js';
import {runDraftSchedule,nextAlarmAt,ensureDraftAlarm,handleDraftAlarm} from '../workers/clan-draft/src/schedule.js';

const iso=ms=>new Date(ms).toISOString(),base=Date.parse('2026-09-15T14:00:00Z');
const settings={...clan.CLAN_ADMIN_SETTINGS_DEFAULTS,mode:'ON',draftPickSeconds:30};
class SQLiteDB{
  sql=new DatabaseSync(':memory:');
  prepare(source){const db=this;return{source,values:[],bind(...values){this.values=values;return this},async first(){return db.sql.prepare(source).get(...this.values)||null},async all(){return{results:db.sql.prepare(source).all(...this.values)}},async run(){const r=db.sql.prepare(source).run(...this.values);return{meta:{changes:Number(r.changes),last_row_id:Number(r.lastInsertRowid)}}}}}
  async batch(statements){this.sql.exec('BEGIN');try{const r=statements.map(s=>{const row=this.sql.prepare(s.source).run(...s.values);return{meta:{changes:Number(row.changes)}}});this.sql.exec('COMMIT');return r}catch(error){this.sql.exec('ROLLBACK');throw error}}
}
async function fixture(t,{postgres=false,registration=false,teamCount=3,candidateCount=6}={}){
  const schema=[...clan.FOUNDATION_SQL,
    'CREATE TABLE app_meta(key TEXT PRIMARY KEY,value TEXT,updated_at TEXT DEFAULT CURRENT_TIMESTAMP)',
    'CREATE TABLE users(id INTEGER PRIMARY KEY,nickname TEXT,last_login_at TEXT)',
    'CREATE TABLE attendance_logs(user_id INTEGER,attendance_date TEXT)',
    'CREATE TABLE pvp_profiles(user_id INTEGER,season_score INTEGER,wins INTEGER,losses INTEGER)',
    'CREATE TABLE territory_war_v3_rounds(id INTEGER PRIMARY KEY)',
    'CREATE TABLE territory_war_v3_users(user_id INTEGER,round_id INTEGER,attacks INTEGER,defense_wins INTEGER,front_finishes INTEGER,damage INTEGER)'];
  let DB;
  if(postgres){
    const pg=new PGlite();t.after(()=>pg.close());
    await pg.exec("CREATE FUNCTION sqlite_now() RETURNS TEXT LANGUAGE SQL STABLE AS $$ SELECT to_char(timezone('UTC',CURRENT_TIMESTAMP),'YYYY-MM-DD HH24:MI:SS') $$;");
    await pg.exec(schema.map(s=>s.replaceAll('INTEGER PRIMARY KEY AUTOINCREMENT','BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY').replaceAll('INTEGER','BIGINT').replaceAll('CURRENT_TIMESTAMP','sqlite_now()')).join(';'));
    DB=new __postgresCompatTest.PostgresD1Database({async query(input){const r=await pg.query(typeof input==='string'?input:input.text,typeof input==='string'?[]:input.values||[]);return{...r,rowCount:r.affectedRows??r.rows.length}}});
  }else{DB=new SQLiteDB();DB.sql.exec(schema.join(';'));t.after(()=>DB.sql.close())}
  let clock=base;t.mock.method(Date,'now',()=>clock);
  const p=(s,...args)=>DB.prepare(s).bind(...args),env={DB};
  await p("INSERT INTO app_meta(key,value) VALUES('safe_runtime_upgrade_v1820_clan_v1','1')").run();
  await p("INSERT INTO app_meta(key,value) VALUES('clan_settings_v1',?)",JSON.stringify(settings)).run();
  await p('INSERT INTO clan_seasons(id,season_no,phase,registration_ends_at,draft_ends_at,starts_at,ends_at,next_pick_deadline) VALUES(1,2,?,?,?,?,?,?)',registration?'REGISTRATION':'DRAFT',iso(registration?base+60000:base),iso(base+86400000),iso(base+86400000),iso(base+8*86400000),registration?null:iso(base+30000)).run();
  for(let i=1;i<=teamCount;i++){
    await p('INSERT INTO clan_organizations(id,name,mark_key) VALUES(?,?,?)',i,clan.OFFICIAL_CLAN_CATALOG[i-1].name,clan.OFFICIAL_CLAN_CATALOG[i-1].markKey).run();
    if(!registration){await p('INSERT INTO clan_season_teams(season_id,clan_id,master_user_id,draft_position) VALUES(1,?,?,?)',i,i,i-1).run();await p("INSERT INTO clan_members(season_id,clan_id,user_id,member_role) VALUES(1,?,?,'MASTER')",i,i).run()}
  }
  for(let i=101;i<101+candidateCount;i++){await p('INSERT INTO users(id,nickname,last_login_at) VALUES(?,?,?)',i,'Synthetic '+i,iso(base)).run();await p("INSERT INTO clan_draft_pool(season_id,user_id,candidate_key,total_score) VALUES(1,?,?,?)",i,'candidate-'+i,500-i).run()}
  const fresh=()=>p('SELECT * FROM clan_seasons WHERE id=1').first(),ctx=async()=>clan.draftContext(env,await fresh()),candidate=()=>p("SELECT * FROM clan_draft_pool WHERE status='AVAILABLE' ORDER BY user_id LIMIT 1").first();
  return{env,p,fresh,ctx,candidate,at(ms){clock=base+ms},skip:async()=>clan.autoDraftDue(env,await fresh(),settings),pick:async(extra={})=>clan.makeDraftPick(env,await fresh(),(await ctx()).current,await candidate(),settings,extra)};
}

for(const postgres of [false,true])test(`${postgres?'PostgreSQL':'SQLite'}: 30s pass never drafts; catch-up and replays preserve deadlines`,async t=>{
  const f=await fixture(t,{postgres});f.at(29999);await f.skip();assert.equal((await f.fresh()).draft_pick_count,0);
  f.at(30000);await f.skip();assert.equal((await f.ctx()).current.clan_id,2);assert.equal((await f.fresh()).next_pick_deadline,iso(base+60000));
  assert.equal((await f.p("SELECT COUNT(*) count FROM clan_draft_pool WHERE status='AVAILABLE'").first()).count,6);
  assert.equal((await f.p('SELECT COUNT(*) count FROM clan_members').first()).count,3);
  await f.skip();assert.equal((await f.fresh()).draft_pick_count,1);
  f.at(90000);await f.skip();assert.equal((await f.ctx()).current.clan_id,2);assert.equal((await f.fresh()).draft_pick_count,4); // last team does not receive a second absent turn
  f.at(600000);await f.skip();assert.equal((await f.fresh()).draft_pick_count,29);assert.equal((await f.fresh()).next_pick_deadline,iso(base+630000));
  f.at(601000);await f.skip();assert.equal((await f.fresh()).draft_pick_count,29);
});

test('manual picks reset the 30s clock, keep snake double-picks, and reject expired/stale turns',async t=>{
  const f=await fixture(t);f.at(10000);await f.pick();assert.equal((await f.fresh()).next_pick_deadline,iso(base+40000));
  assert.equal((await f.p("SELECT COUNT(*) count FROM clan_draft_pool WHERE status='DRAFTED'").first()).count,1);
  f.at(40000);await assert.rejects(f.pick(),/제한 시간/);await f.skip();assert.equal((await f.ctx()).current.clan_id,3);
  f.at(41000);await assert.rejects(f.pick({expectedPickNo:1}),/순서가 변경/);await f.pick();assert.equal((await f.ctx()).current.clan_id,3);
  assert.equal((await f.fresh()).next_pick_deadline,iso(base+71000));
});

test('concurrent timeout and duplicate pick requests cannot consume a turn twice',async t=>{
  const f=await fixture(t);f.at(30000);await Promise.all([f.skip(),f.skip(),f.skip()]);assert.equal((await f.fresh()).draft_pick_count,1);
  f.at(31000);const season=await f.fresh(),team=(await f.ctx()).current,candidate=await f.candidate();
  const results=await Promise.allSettled([1,2].map(()=>clan.makeDraftPick(f.env,season,team,candidate,settings)));
  assert.equal(results.filter(r=>r.status==='fulfilled').length,1);
  assert.equal((await f.p("SELECT COUNT(*) count FROM clan_draft_pool WHERE status='DRAFTED'").first()).count,1);
});

test('full clans are passed without blocking; a sole remaining clan still has timed turns',async t=>{
  const f=await fixture(t);
  for(const clanId of [1,2])for(let n=1;n<=21;n++)await f.p('INSERT INTO clan_members(season_id,clan_id,user_id) VALUES(1,?,?)',clanId,clanId*1000+n).run();
  await f.skip();assert.equal((await f.ctx()).current.clan_id,3);
  f.at(30000);await f.skip();assert.equal((await f.ctx()).current.clan_id,3);assert.equal((await f.fresh()).next_pick_deadline,iso(base+60000));
  await f.pick();assert.equal((await f.ctx()).current.clan_id,3);
});

test('registration close + one hour completes remaining rosters and generates wars once',async t=>{
  const f=await fixture(t);f.at(3600000);await f.skip();assert.equal((await f.fresh()).phase,'ACTIVE');
  assert.equal((await f.p("SELECT COUNT(*) count FROM clan_draft_pool WHERE status='AVAILABLE'").first()).count,0);
  assert.equal((await f.p('SELECT COUNT(*) count FROM clan_wars').first()).count,3);
  await reconcileClanDraft(f.env);assert.equal((await f.p('SELECT COUNT(*) count FROM clan_wars').first()).count,3);
});

for(const postgres of [false,true])test(`${postgres?'PostgreSQL':'SQLite'}: a full 176-player pool is completed at one hour without duplicate membership`,async t=>{
  const f=await fixture(t,{postgres,teamCount:8,candidateCount:168});
  f.at(3590000);await f.skip();assert.equal((await f.p("SELECT COUNT(*) count FROM clan_draft_pool WHERE status='AVAILABLE'").first()).count,168);
  await f.pick();assert.equal((await f.fresh()).next_pick_deadline,iso(base+3600000));
  f.at(3600000);await assert.rejects(f.pick(),/제한 시간/);
  await Promise.all([f.skip(),f.skip()]);assert.equal((await f.fresh()).phase,'ACTIVE');
  assert.equal((await f.p("SELECT COUNT(*) count FROM clan_draft_pool WHERE status='AVAILABLE'").first()).count,0);
  assert.equal((await f.p('SELECT COUNT(*) count FROM clan_members').first()).count,176);
  for(const team of (await f.ctx()).teams)assert.equal(Number(team.member_count),22);
  assert.equal((await f.p('SELECT COUNT(*) count FROM clan_wars').first()).count,28);
  await f.skip();assert.equal((await f.p('SELECT COUNT(*) count FROM clan_members').first()).count,176);
});

test('a delayed start cannot move the one-hour deadline or make the final alarm wait for a longer turn',async t=>{
  const f=await fixture(t,{registration:true});f.at(1800000);await reconcileClanDraft(f.env);
  const season=await f.fresh();assert.equal(season.draft_ends_at,iso(base+3660000));
  assert.equal(clan.nextDraftCheckAt({...season,next_pick_deadline:iso(base+3700000)}),iso(base+3660000));
  f.at(3660000);await reconcileClanDraft(f.env);assert.equal((await f.fresh()).phase,'ACTIVE');
});

test('new seasons ignore legacy draft days and use one hour after registration',async t=>{
  const f=await fixture(t);await f.p("UPDATE clan_seasons SET phase='COMPLETE'").run();
  const season=await clan.createSeason(f.env,{...settings,draftDays:14});
  assert.equal(Date.parse(season.draft_ends_at)-Date.parse(season.registration_ends_at),3600000);
});

test('failed final assignment rolls back all members and can safely resume',async t=>{
  const f=await fixture(t);f.at(3600000);const batch=f.env.DB.batch.bind(f.env.DB);
  f.env.DB.batch=statements=>batch([...statements,f.env.DB.prepare('INSERT INTO synthetic_missing_table VALUES(1)')]);
  await assert.rejects(f.skip(),/synthetic_missing_table/);
  assert.equal((await f.fresh()).phase,'DRAFT');
  assert.equal((await f.p("SELECT COUNT(*) count FROM clan_draft_pool WHERE status='AVAILABLE'").first()).count,6);
  assert.equal((await f.p('SELECT COUNT(*) count FROM clan_members').first()).count,3);
  f.env.DB.batch=batch;await f.skip();assert.equal((await f.fresh()).phase,'ACTIVE');
});

test('viewer-independent lifecycle starts after registration closes; ON gate and concurrent starts are safe',async t=>{
  const f=await fixture(t,{registration:true});await reconcileClanDraft(f.env);assert.equal((await f.fresh()).phase,'REGISTRATION');
  f.at(60000);await f.p("UPDATE app_meta SET value=? WHERE key='clan_settings_v1'",JSON.stringify({...settings,mode:'TEST'})).run();
  await reconcileClanDraft(f.env);assert.equal((await f.fresh()).phase,'REGISTRATION');
  await f.p("UPDATE app_meta SET value=? WHERE key='clan_settings_v1'",JSON.stringify(settings)).run();
  await Promise.all([reconcileClanDraft(f.env),reconcileClanDraft(f.env)]);
  assert.equal((await f.fresh()).phase,'DRAFT');assert.equal((await f.fresh()).next_pick_deadline,iso(base+90000));
  assert.equal((await f.p('SELECT COUNT(*) count FROM clan_season_teams').first()).count,2);
  await f.pick();await clan.beginDraft(f.env,await f.fresh(),settings);assert.equal((await f.fresh()).draft_pick_count,1);
});

test('alarm scheduler closes DB connections on success and failure and records actual alarm execution',async()=>{
  let closed=0,opened=0,heartbeat;
  const openDatabase=async()=>{opened++;return{db:{prepare:()=>({bind:value=>({run:async()=>{heartbeat=JSON.parse(value)}})})},close:async()=>{closed++}}};
  const result=await runDraftSchedule({HYPERDRIVE:{connectionString:'synthetic'}},{openDatabase,now:()=>base,reconcile:async()=>({phase:'DRAFT',nextCheckAt:iso(base+30000)})});
  assert.equal(opened,1);assert.equal(opened,closed);assert.equal(heartbeat.source,'DURABLE_ALARM');assert.equal(heartbeat.checkedAt,iso(base));assert.equal(result.phase,'DRAFT');
  await assert.rejects(runDraftSchedule({HYPERDRIVE:{}},{openDatabase,reconcile:async()=>{throw Error('synthetic failure')}}),/synthetic failure/);assert.equal(opened,closed);
});

test('durable alarms preserve earlier timers, wake at deadlines, and survive DB errors',async()=>{
  let alarm=null;const history=[];
  const storage={async getAlarm(){return alarm},async setAlarm(at){alarm=at;history.push(at)}};
  await ensureDraftAlarm(storage,base);assert.equal(alarm,base+1000);
  await ensureDraftAlarm(storage,base+100);assert.equal(history.length,1);
  await handleDraftAlarm(storage,{}, {now:()=>base,run:async()=>{assert.equal(alarm,base+60000);return{phase:'DRAFT',nextCheckAt:iso(base+30000)}}});
  assert.equal(alarm,base+30000);
  await ensureDraftAlarm(storage,base+1000);assert.equal(alarm,base+30000);
  await assert.rejects(handleDraftAlarm(storage,{}, {now:()=>base+30000,run:async()=>{throw Error('offline')}}),/offline/);
  assert.equal(alarm,base+90000);
  assert.equal(nextAlarmAt({nextCheckAt:iso(base-1)},base),base+5000);
  assert.equal(nextAlarmAt({nextCheckAt:iso(base+86400000)},base),base+60000);
  assert.equal(nextAlarmAt({phase:'OFF'},base),base+60000);
});

test('30s defaults, public countdown and scheduled deployment are included in the release',()=>{
  assert.equal(clan.cleanClanAdminSettings({}).draftPickSeconds,30);
  assert.equal(clan.cleanClanAdminSettings({draftDays:1}).draftDays,1);
  assert.equal(clan.cleanClanAdminSettings({draftDays:14,draftMinutes:1440}).draftMinutes,60);
  const client=readFileSync(new URL('../js/clan-v1.js',import.meta.url),'utf8');
  assert.match(client,/data-clan-deadline/);assert.match(client,/pickNo:state.data.draft\?\.pickNo/);assert.doesNotMatch(client,/5분을 넘기면|시스템이 균형 후보를 자동 지명/);
  const config=JSON.parse(readFileSync(new URL('../workers/clan-draft/wrangler.jsonc',import.meta.url),'utf8'));
  assert.deepEqual(config.triggers.crons,['* * * * *']);assert.equal(config.workers_dev,false);
  assert.deepEqual(config.durable_objects.bindings,[{name:'CLAN_DRAFT_ALARM',class_name:'ClanDraftAlarm'}]);
  assert.deepEqual(config.migrations[0].new_sqlite_classes,['ClanDraftAlarm']);
  const scripts=JSON.parse(readFileSync(new URL('../package.json',import.meta.url),'utf8')).scripts;
  assert.match(scripts['deploy:production'],/^npm run release:gate && .*workers\/clan-draft\/wrangler.jsonc/);
});
