import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {PGlite} from '@electric-sql/pglite';
import {__postgresCompatTest} from '../functions/_postgres_d1_compat.js';
import {__clanTest as clan,reconcileClanDraft} from '../functions/_clan.js';
import {championsSchema} from '../functions/_clan_champions.js';
import {clanChampionsFollowupKey as key,clanChampionsFollowupReceiptKey as receiptKey,clanChampionsFollowupTimes,openClanChampionsFollowup} from '../functions/_clan_champions_followup.js';

const end=Date.parse('2026-09-28T14:00:00Z'),draft=Date.parse('2026-09-29T12:00:00Z'),iso=ms=>new Date(ms).toISOString();
const settings={...clan.CLAN_ADMIN_SETTINGS_DEFAULTS,mode:'ON',openDays:[0,2,4,6],warOpenTime:'21:00',warDurationMinutes:60,seasonDays:7};
const plan={version:1,seasonId:1,enabled:true,draftRule:'NEXT_DAY_21_KST',registrationRule:'AFTER_CHAMPIONS_COMPLETE'};
async function fixture(t,postgres=false){
 let clock=end,DB;t.mock.method(Date,'now',()=>clock);
 const schema=[...clan.FOUNDATION_SQL,...championsSchema(),
  'CREATE TABLE app_meta(key TEXT PRIMARY KEY,value TEXT,updated_at TEXT DEFAULT CURRENT_TIMESTAMP)',
  'CREATE TABLE users(id INTEGER PRIMARY KEY,nickname TEXT,last_login_at TEXT)',
  'CREATE TABLE attendance_logs(user_id INTEGER,attendance_date TEXT)',
  'CREATE TABLE pvp_profiles(user_id INTEGER,season_score INTEGER,wins INTEGER,losses INTEGER)',
  'CREATE TABLE territory_war_v3_rounds(id INTEGER PRIMARY KEY)',
  'CREATE TABLE territory_war_v3_users(user_id INTEGER,round_id INTEGER,attacks INTEGER,defense_wins INTEGER,front_finishes INTEGER,damage INTEGER)'];
 if(postgres){
  const pg=new PGlite();t.after(()=>pg.close());
  await pg.exec("CREATE FUNCTION sqlite_now() RETURNS TEXT LANGUAGE SQL STABLE AS $$ SELECT '2026-09-28 14:00:00'::TEXT $$; CREATE FUNCTION sqlite_date(value TEXT,modifier TEXT) RETURNS TEXT LANGUAGE SQL STABLE AS $$ SELECT to_char((CASE WHEN value='now' THEN CURRENT_TIMESTAMP ELSE value::timestamptz END)+modifier::interval,'YYYY-MM-DD') $$; CREATE FUNCTION sqlite_datetime(value TEXT,modifier TEXT) RETURNS TEXT LANGUAGE SQL STABLE AS $$ SELECT to_char((CASE WHEN value='now' THEN sqlite_now()::timestamp ELSE value::timestamp END)+modifier::interval,'YYYY-MM-DD HH24:MI:SS') $$;");
  await pg.exec(schema.map(s=>s.replaceAll('INTEGER PRIMARY KEY AUTOINCREMENT','BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY').replaceAll('INTEGER','BIGINT').replaceAll('CURRENT_TIMESTAMP','sqlite_now()')).join(';'));
  DB=new __postgresCompatTest.PostgresD1Database({async query(input){const r=await pg.query(typeof input==='string'?input:input.text,typeof input==='string'?[]:input.values||[]);return{...r,rowCount:r.affectedRows??r.rows.length}}});
 }else{
  const sql=new DatabaseSync(':memory:');t.after(()=>sql.close());sql.function('current_timestamp',()=>iso(clock).slice(0,19).replace('T',' '));sql.exec(schema.join(';'));
  DB={prepare(source){return{source,values:[],bind(...values){this.values=values;return this},async first(){return sql.prepare(source).get(...this.values)||null},async all(){return{results:sql.prepare(source).all(...this.values)}},async run(){const r=sql.prepare(source).run(...this.values);return{meta:{changes:Number(r.changes),last_row_id:Number(r.lastInsertRowid)}}}}},async batch(statements){sql.exec('BEGIN');try{const r=statements.map(s=>{const out=sql.prepare(s.source).run(...s.values);return{meta:{changes:Number(out.changes)}}});sql.exec('COMMIT');return r}catch(e){sql.exec('ROLLBACK');throw e}}};
 }
 const env={DB},p=(s,...v)=>DB.prepare(s).bind(...v);
 await p("INSERT INTO app_meta(key,value) VALUES('safe_runtime_upgrade_v1820_clan_v1','1')").run();
 await p("INSERT INTO app_meta(key,value) VALUES('clan_settings_v1',?)",JSON.stringify(settings)).run();
 await p('INSERT INTO app_meta(key,value) VALUES(?,?)',key(1),JSON.stringify(plan)).run();
 await p("INSERT INTO clan_seasons(season_no,phase,registration_ends_at,draft_ends_at,starts_at,ends_at) VALUES(2,'CHAMPIONS',?,?,?,?)",iso(end-86400000),iso(end-82800000),iso(end-7200000),iso(end)).run();
 await p("INSERT INTO clan_championships(season_id,status,seeds_json,settings_json,creation_token,semifinal_starts_at,final_starts_at,reward_status) VALUES(1,'FINAL',?,?,'qa',?,?,'SENT')",JSON.stringify([{clanId:1},{clanId:2},{clanId:3}]),JSON.stringify(settings),iso(end-7200000),iso(end-3600000)).run();
 await p("INSERT INTO clan_wars(season_id,round_no,clan_a_id,clan_b_id,status,starts_at,ends_at,score_a,score_b) VALUES(1,1002,1,2,'ACTIVE',?,?,5,2)",iso(end-3600000),iso(end)).run();
 await p("INSERT INTO clan_members(season_id,clan_id,user_id) VALUES(1,1,999)").run();
 return{env,p,at:ms=>{clock=ms},previous:()=>p('SELECT * FROM clan_seasons WHERE id=1').first(),next:()=>p('SELECT * FROM clan_seasons WHERE season_no=3').first(),async finish(){await p("UPDATE clan_seasons SET phase='COMPLETE' WHERE id=1").run();await p("UPDATE clan_championships SET status='COMPLETED',completed_at=? WHERE season_id=1",'2026-09-28 14:00:00').run()}};
}

test('next Korean calendar day at 21:00 includes midnight, month and year boundaries',()=>{
 for(const [completed,expected] of [['2026-09-28T14:00:00Z','2026-09-29T12:00:00.000Z'],['2026-09-28 14:00:00','2026-09-29T12:00:00.000Z'],['2026-09-28T15:00:00Z','2026-09-30T12:00:00.000Z'],['2026-12-31T14:59:59Z','2027-01-01T12:00:00.000Z']]){
  const times=clanChampionsFollowupTimes(completed,7);assert.equal(times.registrationEndsAt,expected);assert.equal(Date.parse(times.draftEndsAt)-Date.parse(expected),3600000);
 }
});

for(const postgres of [false,true]){
 const label=postgres?'PostgreSQL':'SQLite';
 test(`${label}: unattended final completion opens season 3 once and preserves history`,async t=>{
  const f=await fixture(t,postgres);f.at(end-1);
  assert.equal((await reconcileClanDraft(f.env)).nextCheckAt,iso(end));assert.equal(await f.next(),null);
  f.at(end);const result=await reconcileClanDraft(f.env);assert.equal(result.phase,'REGISTRATION');assert.equal(result.nextCheckAt,iso(draft));
  const next=await f.next();assert.equal(next.registration_ends_at,iso(draft));assert.equal(next.draft_ends_at,iso(draft+3600000));
  assert.equal((await f.previous()).phase,'COMPLETE');assert.equal((await f.p('SELECT status FROM clan_wars WHERE season_id=1').first()).status,'COMPLETED');
  assert.equal((await f.p('SELECT COUNT(*) n FROM clan_members WHERE season_id=1').first()).n,1);assert.equal((await f.p('SELECT COUNT(*) n FROM clan_draft_pool').first()).n,0);
  await reconcileClanDraft(f.env);await openClanChampionsFollowup(f.env,await f.previous(),settings);
  assert.equal((await f.p('SELECT COUNT(*) n FROM clan_seasons').first()).n,2);assert.deepEqual(await f.next(),next);
  assert.equal((await clan.createSeason(f.env,settings)).id,next.id);
  assert.equal((await f.p("SELECT value FROM app_meta WHERE key='clan_settings_v1'").first()).value,JSON.stringify(settings));
 });
 test(`${label}: transition rollback and reward retry cannot leave a half-created season`,async t=>{
  const f=await fixture(t,postgres);await f.finish();const batch=f.env.DB.batch.bind(f.env.DB);
  f.env.DB.batch=statements=>batch([...statements,f.env.DB.prepare('INSERT INTO synthetic_missing_table VALUES(1)')]);
  await assert.rejects(openClanChampionsFollowup(f.env,await f.previous(),settings),/synthetic_missing_table/);
  assert.equal(await f.next(),null);assert.equal(await f.p('SELECT value FROM app_meta WHERE key=?',receiptKey(1)).first(),null);
  f.env.DB.batch=batch;
  await f.p("UPDATE clan_championships SET reward_status='PENDING',reward_json='[]' WHERE season_id=1").run();
  await assert.rejects(openClanChampionsFollowup(f.env,await f.previous(),settings),/보상 설정/);assert.equal(await f.next(),null);
  await f.p("UPDATE clan_championships SET reward_status='SENT' WHERE season_id=1").run();
  const next=await openClanChampionsFollowup(f.env,await f.previous(),settings);assert.equal(next.season_no,3);
  assert.equal((await f.p('SELECT COUNT(*) n FROM joint_atomic_guards_v1').first()).n,0);
 });
 test(`${label}: draft begins at 21:00; regular wars keep Tue Thu Sat Sun 21:00–22:00`,async t=>{
  const f=await fixture(t,postgres);await f.finish();const next=await clan.createSeason(f.env,settings);
  for(let i=1;i<=8;i++)await f.p('INSERT INTO clan_organizations(id,name,mark_key) VALUES(?,?,?)',i,clan.OFFICIAL_CLAN_CATALOG[i-1].name,clan.OFFICIAL_CLAN_CATALOG[i-1].markKey).run();
  for(let i=1;i<=4;i++){await f.p('INSERT INTO users(id,nickname,last_login_at) VALUES(?,?,?)',i,`QA ${i}`,iso(end)).run();await f.p('INSERT INTO clan_draft_pool(season_id,user_id,candidate_key) VALUES(?,?,?)',next.id,i,`qa-${i}`).run()}
  f.at(draft-1);assert.equal((await reconcileClanDraft(f.env)).phase,'REGISTRATION');
  f.at(draft);assert.equal((await reconcileClanDraft(f.env)).phase,'DRAFT');assert.equal((await f.next()).next_pick_deadline,iso(draft+30000));
  f.at(draft+3600000);await reconcileClanDraft(f.env);assert.equal((await f.next()).phase,'ACTIVE');
  const wars=(await f.p('SELECT * FROM clan_wars WHERE season_id=?',next.id).all()).results;
  assert.ok(wars.length);assert.equal(wars[0].starts_at,'2026-10-01T12:00:00.000Z');
  for(const war of wars){const local=new Date(Date.parse(war.starts_at)+9*3600000);assert.ok([0,2,4,6].includes(local.getUTCDay()));assert.equal(local.getUTCHours(),21);assert.equal(Date.parse(war.ends_at)-Date.parse(war.starts_at),3600000)}
 });
}

test('unarmed seasons and TEST mode cannot automatically advance or create a season',async t=>{
 const f=await fixture(t);await f.p('DELETE FROM app_meta WHERE key=?',key(1)).run();
 await reconcileClanDraft(f.env);assert.equal((await f.previous()).phase,'CHAMPIONS');assert.equal(await f.next(),null);
 await f.p('INSERT INTO app_meta(key,value) VALUES(?,?)',key(1),JSON.stringify(plan)).run();
 await f.p("UPDATE app_meta SET value=? WHERE key='clan_settings_v1'",JSON.stringify({...settings,mode:'TEST'})).run();
 assert.equal((await reconcileClanDraft(f.env)).phase,'TEST');assert.equal(await f.next(),null);
});
