import test from 'node:test';
import assert from 'node:assert/strict';
import {factionFixture} from './helpers/clan-faction-fixture.mjs';
import {mutateFaction,factionOverview,handleClanFaction} from '../functions/_clan_faction.js';
import {factionStrikeDamage,splitFactionTax} from '../functions/_clan_faction_model.js';
import {FACTION_RULES as R} from '../shared/clan-faction-rules-v1.mjs';
const call=(f,kind,body={},user=f.user)=>mutateFaction(f.env,f.season,user,kind,{requestId:crypto.randomUUID(),...body},f.deps);
const formation={attack1:[1,2,3],attack2:[4,5],defense1:[6,7,8],defense2:[9,10]};
for(const postgres of [false,true])test(`${postgres?'PostgreSQL':'SQLite'} ACTIVE faction season opens before the first regular match`,async t=>{
  const f=await factionFixture({postgres});t.after(()=>f.close());
  f.season.starts_at=new Date(f.clock.now+7200000).toISOString();
  await f.p('UPDATE clan_seasons SET starts_at=? WHERE id=?',f.season.starts_at,f.season.id).run();
  assert.equal((await factionOverview(f.env,f.season,f.user,f.deps)).season.active,true);
  await call(f,'formation',{formation});
  assert.equal((await call(f,'launch',{districtId:'11680',squad:'attack1'})).captured,true);
  f.season.phase='DRAFT';await f.p("UPDATE clan_seasons SET phase='DRAFT' WHERE id=?",f.season.id).run();
  assert.equal((await factionOverview(f.env,f.season,f.user,f.deps)).season.active,false);
  await assert.rejects(call(f,'launch',{districtId:'11710',squad:'attack2'}),/시즌/);
});
for(const postgres of [false,true])test(`${postgres?'PostgreSQL':'SQLite'} faction state, authority, HP, tax and retry invariants`,async t=>{
  const f=await factionFixture({postgres});t.after(()=>f.close());
  const before=await f.p('SELECT * FROM clan_season_teams ORDER BY clan_id').all();
  const other=await f.p('SELECT * FROM users WHERE id=2').first();
  await assert.rejects(call(f,'formation',{formation},other),/클랜장/);
  await assert.rejects(call(f,'formation',{formation:{...formation,defense2:[1]}}),/하나의 부대/);
  await assert.rejects(call(f,'formation',{formation:{...formation,attack1:[101]}}),/현재 클랜원/);
  await call(f,'formation',{formation});
  const launch={requestId:'neutral-capture-unique',districtId:'11680',squad:'attack1'};
  const captured=await call(f,'launch',launch);assert.equal(captured.captured,true);
  assert.equal((await call(f,'launch',launch)).replayed,true);
  await assert.rejects(call(f,'launch',{...launch,districtId:'11710'}),/다른 작업/);
  await assert.rejects(call(f,'launch',{districtId:'11710',squad:'attack1'}),/재출정/);
  await call(f,'garrison',{districtId:'11680',squad:'defense1'});
  const t1=await f.p('SELECT * FROM users WHERE id=101').first();
  await call(f,'formation',{formation:{attack1:[101,102,103],attack2:[104],defense1:[106,107],defense2:[108]}},t1);
  await assert.rejects(call(f,'launch',{districtId:'11680',squad:'attack1'},t1),/점령 보호/);
  f.clock.now+=R.protectionMs+1;
  const invasion=await call(f,'launch',{districtId:'11680',squad:'attack1'},t1);
  const defender=await f.p('SELECT * FROM users WHERE id=6').first();
  const alerts=await factionOverview(f.env,f.season,defender,f.deps,{alertsOnly:true});assert.equal(alerts.alerts[0].attackerClan,'T1');assert.equal(alerts.alerts[0].attackerName,'T1 지휘관');
  assert.equal((await factionOverview(f.env,f.season,f.user,f.deps,{alertsOnly:true})).alerts.length,0);
  await assert.rejects(call(f,'formation',{formation}),/교전/);
  await assert.rejects(call(f,'strike',{battleId:invasion.battleId},other),/편성된/);
  const strike={requestId:'faction-strike-same-key',battleId:invasion.battleId,damage:999999999};
  const hit=await call(f,'strike',strike,t1);assert.equal(hit.damage,150000);assert.equal(hit.defenderHp,850000);assert.equal(f.buildCalls(),1);
  assert.equal((await call(f,'strike',strike,t1)).replayed,true);assert.equal(f.buildCalls(),1);
  await assert.rejects(call(f,'strike',{battleId:invasion.battleId},t1),/다음 교전/);
  for(let i=0;i<6;i++){f.clock.now+=R.strikeCooldownMs;await call(f,'strike',{battleId:invasion.battleId},t1);}
  const won=await factionOverview(f.env,f.season,t1,f.deps);assert.equal(won.districts.find(d=>d.id==='11680').owner,2);assert.equal(won.battles[0].winner,2);
  await assert.rejects(call(f,'strike',{battleId:invasion.battleId},defender),/종료/);
  const claim={requestId:'tax-claim-once-ever'};
  f.setFailure('INSERT INTO clan_faction_wallets');await assert.rejects(call(f,'collect',claim),/INJECTED/);f.setFailure('');
  assert.equal((await f.p('SELECT * FROM clan_faction_receipts WHERE request_key=?','1:'+claim.requestId).all()).results.length,0);
  const paid=await call(f,'collect',claim);assert.ok(paid.total>=2000000);assert.equal(paid.members,12);
  assert.equal((await call(f,'collect',claim)).replayed,true);
  const wallets=(await f.p('SELECT * FROM clan_faction_wallets').all()).results;assert.equal(wallets.reduce((n,w)=>n+Number(w.balance),0),paid.total);
  assert.deepEqual((await f.p('SELECT * FROM clan_season_teams ORDER BY clan_id').all()).results,before.results);
  assert.equal(Number((await f.p('SELECT SUM(coin) amount FROM users').first()).amount),9600);
  await f.p("UPDATE clan_seasons SET phase='COMPLETE' WHERE id=7").run();f.season.phase='COMPLETE';
  await assert.rejects(call(f,'launch',{districtId:'11110',squad:'attack2'}),/시즌/);
});
test('simultaneous launch and finishing hits use compare-and-swap',async t=>{
  const f=await factionFixture({seeded:true});t.after(()=>f.close());
  const a=await Promise.allSettled([call(f,'launch',{districtId:'11680',squad:'attack1'}),call(f,'launch',{districtId:'11680',squad:'attack2'})]);
  assert.equal(a.filter(r=>r.status==='fulfilled').length,1);
  const battle=a.find(r=>r.status==='fulfilled').value;
  const row=await f.p('SELECT state_json FROM clan_faction_state WHERE season_id=7').first(),s=JSON.parse(row.state_json);s.battles[0].defenderHp=100000;
  await f.p('UPDATE clan_faction_state SET state_json=? WHERE season_id=7',JSON.stringify(s)).run();
  const ids=s.battles[0].attackers.slice(0,2),users=await Promise.all(ids.map(id=>f.p('SELECT * FROM users WHERE id=?',id).first()));
  const hits=await Promise.allSettled(users.map(u=>call(f,'strike',{battleId:battle.battleId},u)));
  assert.equal(hits.filter(r=>r.status==='fulfilled').length,1);
  const view=await factionOverview(f.env,f.season,f.user,f.deps);assert.equal(view.events.filter(e=>e.kind==='CAPTURE'&&e.districtId==='11680').length,1);
});
test('claim retry, season cutoff and real V3 normalized HP including mercenaries',async t=>{
  const f=await factionFixture({seeded:true,realBattle:true});t.after(()=>f.close());
  const b=await call(f,'launch',{districtId:'11680',squad:'attack1'}),hit=await call(f,'strike',{battleId:b.battleId});
  assert.equal(hit.battleV2.engine,'BATTLE_ENGINE_V2_PVP');assert.equal(hit.battleV2.teams.A.cards.length,5);assert.ok(hit.damage>=0&&hit.damage<=150000);
  const healthy={teams:{B:{cards:[{maxHp:100}],mercenaries:[{maxHp:100}]}},result:{final:{B:[{hp:100}],mercenaries:{B:[{hp:100}]}}}};
  assert.equal(factionStrikeDamage(healthy),0);healthy.result.final.B[0].hp=0;assert.equal(factionStrikeDamage(healthy),75000);
  f.clock.now=Date.parse(f.season.ends_at)+100000;const ended=await factionOverview(f.env,f.season,f.user,f.deps);assert.equal(ended.battles[0].status,'COMPLETED');
  f.clock.now+=86400000;assert.equal((await factionOverview(f.env,f.season,f.user,f.deps)).tax.pool,ended.tax.pool);
  assert.deepEqual(splitFactionTax(10,[3,1,2]),[{userId:1,amount:4},{userId:2,amount:3},{userId:3,amount:3}]);
});
test('simultaneous identical claim pays once and archived season remains collectable',async t=>{
  const f=await factionFixture({seeded:true});t.after(()=>f.close());
  const body={requestId:'concurrent-tax-same-key'};
  const replies=await Promise.all([call(f,'collect',body),call(f,'collect',body)]);
  assert.equal(replies.filter(r=>r.replayed).length,1);
  assert.equal(Number((await f.p('SELECT SUM(balance) n FROM clan_faction_wallets').first()).n),replies[0].total);
  f.clock.now+=3600000;
  const end=new Date(f.clock.now).toISOString();await f.p("UPDATE clan_seasons SET phase='COMPLETE',ends_at=? WHERE id=7",end).run();
  const current={id:8,season_no:3,phase:'ACTIVE',starts_at:end,ends_at:new Date(f.clock.now+86400000).toISOString()};
  await f.p('INSERT INTO clan_seasons VALUES(?,?,?,?,?)',8,3,'ACTIVE',current.starts_at,current.ends_at).run();
  const fresh=await factionOverview(f.env,current,f.user,f.deps);assert.ok(fresh.tax.pendingSeasons[0].pool>0);
  const response=await handleClanFaction({path:'clan/faction/collect',request:new Request('http://local/api/clan/faction/collect',{method:'POST',body:JSON.stringify({requestId:'archived-tax-claim',seasonId:7})}),env:f.env,user:f.user,season:current,mode:'ON',deps:{...f.deps,readBody:r=>r.json(),json:(d,status=200)=>new Response(JSON.stringify(d),{status})}});
  assert.equal(response.status,200);const result=await response.json();assert.equal(result.seasonId,7);
  assert.equal((await factionOverview(f.env,current,f.user,f.deps)).tax.pendingSeasons.length,0);
});
