import test from 'node:test';
import assert from 'node:assert/strict';
import {PGlite} from '@electric-sql/pglite';
import {grantDiimRecruitmentGift,TARGETS,ITEM_CODE,ITEM_NAME,PLAN_HASH} from '../scripts/ops/diim-recruitment-gift-20261001.mjs';

async function fixture(t){
 const db=new PGlite();t.after(()=>db.close());
 await db.exec(`CREATE TABLE users(id BIGINT PRIMARY KEY,nickname TEXT,role TEXT,status TEXT,coin BIGINT DEFAULT 123);
 INSERT INTO users VALUES(1,'관리자','OWNER','ACTIVE',123);
 CREATE TABLE user_second_verifications(user_id BIGINT,provider TEXT,provider_user_id TEXT);
 CREATE TABLE inventory_items(code TEXT PRIMARY KEY,name TEXT,is_active BIGINT);
 CREATE TABLE cnine_user_inventory(user_id BIGINT,item_code TEXT,quantity BIGINT,unseen_quantity BIGINT,created_at TEXT,updated_at TEXT,PRIMARY KEY(user_id,item_code));
 CREATE TABLE inventory_logs(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id BIGINT,item_code TEXT,change_amount BIGINT,balance_after BIGINT,reason TEXT,reference_type TEXT,reference_id TEXT,admin_id BIGINT,created_at TEXT);
 CREATE TABLE admin_logs(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,admin_id BIGINT,action_type TEXT,target_type TEXT,target_id TEXT,before_data TEXT,after_data TEXT,created_at TEXT);
 CREATE TABLE user_message_rewards(user_id BIGINT,message_id BIGINT,reward_type TEXT);
 CREATE TABLE app_meta(key TEXT PRIMARY KEY,value TEXT,updated_at TEXT);
 INSERT INTO cnine_user_inventory VALUES(1,'RECRUITMENT_GIFT_BOX',7,0,'original','original'),(22,'MASTER_STAR',900,3,'original','original');`);
 for(const target of TARGETS){
  await db.query("INSERT INTO users VALUES($1,$2,'USER','ACTIVE',123)",[target.userId,target.nickname]);
  await db.query("INSERT INTO user_second_verifications VALUES($1,'PLAYDK',$2)",[target.userId,target.playdkId]);
  for(const id of target.priorGrantIds)await db.query("INSERT INTO inventory_logs(id,user_id,item_code,change_amount,balance_after,reference_id) VALUES($1,$2,$3,1,1,'earlier-grant')",[id,target.userId,ITEM_CODE]);
 }
 await db.query('INSERT INTO inventory_items VALUES($1,$2,1)',[ITEM_CODE,ITEM_NAME]);
 const snapshot=async()=>{const out={};for(const table of ['users','cnine_user_inventory','inventory_logs','admin_logs','app_meta'])out[table]=(await db.query('SELECT * FROM '+table+' ORDER BY 1,2')).rows;return out;};
 return {db,snapshot,grant:options=>grantDiimRecruitmentGift(db,{expectedPlanHash:PLAN_HASH,...options})};
}

test('only 34 never-paid accounts receive one; 24 previously paid accounts stay excluded, including consumed boxes',async t=>{
 const f=await fixture(t),before=await f.snapshot();assert.equal((await f.grant({dryRun:true})).verification.granted,34);assert.deepEqual(await f.snapshot(),before);
 const applied=await f.grant(),after=await f.snapshot();assert.equal(applied.verification.granted,34);assert.equal(applied.verification.skipped,24);
 assert.ok(applied.receipt.allocations.every(x=>x.after.quantity==='1'&&x.after.unseenQuantity==='1'));assert.deepEqual(after.users,before.users);
 assert.deepEqual(after.cnine_user_inventory.filter(x=>x.item_code!==ITEM_CODE||Number(x.user_id)===1),before.cnine_user_inventory);
 assert.ok(!after.cnine_user_inventory.some(x=>applied.receipt.skipped.some(s=>s.userId===Number(x.user_id))&&x.item_code===ITEM_CODE));
 assert.equal((await f.grant()).replayed,true);assert.deepEqual(await f.snapshot(),after);
});

test('newly found prior grants and unclaimed gift messages are excluded before crediting',async t=>{
 const f=await fixture(t),pending=TARGETS.filter(x=>!x.priorGrantIds.length);
 await f.db.query('INSERT INTO user_message_rewards VALUES($1,1,$2)',[pending[0].userId,ITEM_CODE]);
 await f.db.query("INSERT INTO inventory_logs(user_id,item_code,change_amount,balance_after,reference_id) VALUES($1,$2,1,1,'another-admin-grant')",[pending[1].userId,ITEM_CODE]);
 const result=await f.grant();assert.equal(result.verification.granted,32);assert.equal(result.verification.skipped,26);assert.ok(pending.slice(0,2).every(x=>result.receipt.skipped.some(s=>s.userId===x.userId)));
});

test('audit failure rolls back all accounts and once markers before one successful retry',async t=>{
 const f=await fixture(t);await f.db.exec('ALTER TABLE admin_logs ADD CONSTRAINT forced_failure CHECK(false)');const before=await f.snapshot();
 await assert.rejects(f.grant(),/forced_failure/);assert.deepEqual(await f.snapshot(),before);
 await f.db.exec('ALTER TABLE admin_logs DROP CONSTRAINT forced_failure');assert.equal((await f.grant()).verification.granted,34);assert.equal((await f.grant()).replayed,true);
});
