import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
import {inspect,apply,verify,KEY} from '../scripts/ops/diim-x-s-octa-revoke-20260928.mjs';

async function fixture(){
 const db=new PGlite();
 await db.exec(`CREATE ROLE cnine_migrator;
 CREATE TABLE users(id BIGINT PRIMARY KEY,nickname TEXT,role TEXT,status TEXT,coin BIGINT DEFAULT 10,card_shards BIGINT DEFAULT 20,magic_crystals BIGINT DEFAULT 30);
 INSERT INTO users(id,nickname,role,status) VALUES(1,'관리자','OWNER','ACTIVE'),(4773,'진짜디임','USER','ACTIVE'),(66,'다른 계정','USER','ACTIVE');
 CREATE TABLE character_equipment_items(id BIGINT PRIMARY KEY,code TEXT,name TEXT,slot TEXT,is_active BIGINT);
 INSERT INTO character_equipment_items VALUES(47,'BATTLE_SUIT_S_BODY','S-BODY','BATTLE_SUIT',1),(49,'BATTLE_SUIT_X_BODY','X-BODY','BATTLE_SUIT',1),(33,'SHOES','신발','SHOES',1);
 CREATE TABLE user_equipment_instances(id BIGINT PRIMARY KEY,user_id BIGINT,equipment_id BIGINT,source_type TEXT DEFAULT 'ADMIN',source_id TEXT DEFAULT '1',request_id TEXT,acquired_at TEXT DEFAULT 'original');
 CREATE TABLE user_equipment_loadout(user_id BIGINT,slot TEXT,instance_id BIGINT REFERENCES user_equipment_instances(id),updated_at TEXT DEFAULT 'original',PRIMARY KEY(user_id,slot));
 CREATE TABLE equipment_forge_states_v1(user_id BIGINT,instance_id BIGINT REFERENCES user_equipment_instances(id),enhance_level BIGINT,revision BIGINT);
 CREATE TABLE cnine_user_inventory(user_id BIGINT,item_code TEXT,quantity BIGINT,unseen_quantity BIGINT,created_at TEXT,updated_at TEXT,PRIMARY KEY(user_id,item_code));
 CREATE TABLE user_skill_chip_loadout_v2046(user_id BIGINT,slot_no BIGINT,item_code TEXT,updated_at TEXT DEFAULT 'original',PRIMARY KEY(user_id,slot_no));
 CREATE TABLE inventory_logs(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id BIGINT,item_code TEXT,change_amount BIGINT,balance_after BIGINT,reason TEXT,reference_type TEXT,reference_id TEXT,admin_id BIGINT,created_at TEXT);
 CREATE TABLE admin_logs(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,admin_id BIGINT,action_type TEXT,target_type TEXT,target_id TEXT,before_data TEXT,after_data TEXT,created_at TEXT);
 CREATE TABLE app_meta(key TEXT PRIMARY KEY,value TEXT,updated_at TEXT);
 CREATE TABLE user_mutation_locks_v1520(user_id BIGINT PRIMARY KEY,token TEXT,action_path TEXT,lease_until_ms BIGINT,updated_at TEXT);
 INSERT INTO app_meta VALUES('equipment_counts_v1_ready','1','original');`);
 const triggerSql=await readFile(new URL('../scripts/ops/equipment-counts-v1-20260921.sql',import.meta.url),'utf8');
 await db.exec(triggerSql.split('-- ============================== 2.')[0]);
 await db.exec(`INSERT INTO user_equipment_instances(id,user_id,equipment_id) VALUES(100,4773,47),(101,4773,47),(102,4773,49),(103,4773,33),(200,66,49);
 INSERT INTO user_equipment_loadout(user_id,slot,instance_id) VALUES(4773,'BATTLE_SUIT',101),(4773,'SHOES',103),(66,'BATTLE_SUIT',200);
 INSERT INTO equipment_forge_states_v1 VALUES(4773,102,3,1),(4773,103,10,7);
 INSERT INTO cnine_user_inventory VALUES(4773,'SKILL_CHIP_OCTA_SEEKER',1,1,'original','original'),(4773,'OTHER',9,0,'original','original'),(66,'SKILL_CHIP_OCTA_SEEKER',2,0,'original','original');
 INSERT INTO user_skill_chip_loadout_v2046(user_id,slot_no,item_code) VALUES(4773,1,'SKILL_CHIP_ROCKET_LAUNCHER'),(4773,2,'SKILL_CHIP_HELICOPTER_AIRSTRIKE'),(4773,3,'SKILL_CHIP_OCTA_SEEKER'),(66,1,'SKILL_CHIP_OCTA_SEEKER');`);
 return {db,client:{query:(sql,args=[])=>db.query(sql,args)}};
}
async function snapshot(db){const state={};for(const table of ['users','user_equipment_instances','user_equipment_counts_v1','user_equipment_loadout','equipment_forge_states_v1','cnine_user_inventory','user_skill_chip_loadout_v2046','inventory_logs','admin_logs','app_meta','user_mutation_locks_v1520'])state[table]=(await db.query(`SELECT * FROM ${table} ORDER BY 1,2`)).rows;return state;}

test('one X and one equipped chip are revoked atomically, S/other accounts remain, and retries preserve newly acquired items',async()=>{
 const {db,client}=await fixture();try{
  const reviewed=await inspect(client),before=await snapshot(db);
  assert.equal((await apply(client,reviewed,{dryRun:true})).dryRun,true);assert.deepEqual(await snapshot(db),before);
  const receipt=await apply(client,reviewed);assert.equal(receipt.revokedQuantity,1);assert.equal((await verify(client)).verified,true);
  const after=await snapshot(db);
  assert.deepEqual(after.users,before.users);assert.deepEqual(after.user_equipment_loadout,before.user_equipment_loadout);
  assert.deepEqual(after.user_equipment_instances,before.user_equipment_instances.filter(x=>Number(x.id)!==102));
  assert.deepEqual(after.equipment_forge_states_v1,before.equipment_forge_states_v1.filter(x=>Number(x.instance_id)!==102));
  const unrelated=x=>Number(x.user_id)!==4773||x.item_code!=='SKILL_CHIP_OCTA_SEEKER';
  assert.deepEqual(after.cnine_user_inventory.filter(unrelated),before.cnine_user_inventory.filter(unrelated));
  assert.deepEqual(after.user_skill_chip_loadout_v2046,before.user_skill_chip_loadout_v2046.filter(unrelated));
  assert.equal(after.inventory_logs.length,1);assert.equal(Number(after.inventory_logs[0].change_amount),-1);assert.equal(after.inventory_logs[0].reference_id,KEY);
  assert.equal(after.admin_logs.length,1);assert.equal(after.user_mutation_locks_v1520.length,0);
  await db.exec("INSERT INTO user_equipment_instances(id,user_id,equipment_id) VALUES(104,4773,49); UPDATE cnine_user_inventory SET quantity=1 WHERE user_id=4773 AND item_code='SKILL_CHIP_OCTA_SEEKER'");
  const acquired=await snapshot(db);assert.equal((await apply(client,reviewed)).replayed,true);assert.deepEqual(await snapshot(db),acquired);
 }finally{await db.close();}
});
test('late audit failure rolls back equipment, count trigger, chip slot and ledger; changed reviewed state is rejected',async()=>{
 const {db,client}=await fixture();try{
  const reviewed=await inspect(client);await db.exec('ALTER TABLE admin_logs ADD CONSTRAINT forced_failure CHECK(false)');
  const before=await snapshot(db);await assert.rejects(apply(client,reviewed),/forced_failure/);assert.deepEqual(await snapshot(db),before);
  await db.exec('ALTER TABLE admin_logs DROP CONSTRAINT forced_failure');
  await db.exec("UPDATE cnine_user_inventory SET quantity=2 WHERE user_id=4773 AND item_code='SKILL_CHIP_OCTA_SEEKER'");
  const changed=await snapshot(db);await assert.rejects(apply(client,reviewed),/Reviewed inventory changed/);assert.deepEqual(await snapshot(db),changed);
  await db.exec("UPDATE cnine_user_inventory SET quantity=1 WHERE user_id=4773 AND item_code='SKILL_CHIP_OCTA_SEEKER'");
  assert.equal((await apply(client,reviewed)).replayed,false);assert.equal((await verify(client)).verified,true);
 }finally{await db.close();}
});
