import test from 'node:test';
import assert from 'node:assert/strict';
import {PGlite} from '@electric-sql/pglite';
import {grantDiimOctaSeekerChip,OPERATION_KEY,TARGET,ITEM_CODE,ITEM_NAME} from '../scripts/ops/diim-octaseeker-grant-20260928.mjs';

async function fixture(){
 const db=new PGlite();
 await db.exec(`CREATE TABLE users(id BIGINT PRIMARY KEY,nickname TEXT,role TEXT,status TEXT,coin BIGINT DEFAULT 123,card_shards BIGINT DEFAULT 456,magic_crystals BIGINT DEFAULT 789);
  INSERT INTO users(id,nickname,role,status) VALUES(1,'관리자','OWNER','ACTIVE'),(4773,'진짜디임','USER','ACTIVE'),(66,'다른 계정','USER','ACTIVE');
  CREATE TABLE inventory_items(code TEXT PRIMARY KEY,name TEXT,is_active BIGINT);
  CREATE TABLE cnine_user_inventory(user_id BIGINT,item_code TEXT,quantity BIGINT,unseen_quantity BIGINT,created_at TEXT,updated_at TEXT,PRIMARY KEY(user_id,item_code));
  CREATE TABLE inventory_logs(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id BIGINT,item_code TEXT,change_amount BIGINT,balance_after BIGINT,reason TEXT,reference_type TEXT,reference_id TEXT,admin_id BIGINT,created_at TEXT);
  CREATE TABLE admin_logs(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,admin_id BIGINT,action_type TEXT,target_type TEXT,target_id TEXT,before_data TEXT,after_data TEXT,created_at TEXT);
  CREATE TABLE user_skill_chip_loadout_v2046(user_id BIGINT,slot_no BIGINT,item_code TEXT,updated_at TEXT,PRIMARY KEY(user_id,slot_no));
  INSERT INTO user_skill_chip_loadout_v2046 VALUES(4773,1,'SKILL_CHIP_ROCKET_LAUNCHER','original');
  CREATE TABLE app_meta(key TEXT PRIMARY KEY,value TEXT,updated_at TEXT);
  INSERT INTO cnine_user_inventory VALUES(4773,'SKILL_CHIP_OCTA_SEEKER',2,0,'original','original'),(4773,'MASTER_STAR',900,5,'original','original'),(66,'SKILL_CHIP_OCTA_SEEKER',7,1,'original','original');`);
 await db.query('INSERT INTO inventory_items VALUES($1,$2,1)',[ITEM_CODE,ITEM_NAME]);
 return {db,client:{async query(sql,args=[]){const r=await db.query(sql,args);return {...r,rowCount:r.affectedRows??r.rows.length};}}};
}
async function snapshot(db){const result={};for(const table of ['users','inventory_items','cnine_user_inventory','inventory_logs','admin_logs','app_meta','user_skill_chip_loadout_v2046'])result[table]=(await db.query(`SELECT * FROM ${table} ORDER BY 1,2`)).rows;return result;}

test('increments only the target skill chip by one and retries never grant twice, with existing or missing inventory',async()=>{
 for(const existing of [true,false]){
  const {db,client}=await fixture();try{
   if(!existing)await db.query('DELETE FROM cnine_user_inventory WHERE user_id=$1 AND item_code=$2',[TARGET.id,ITEM_CODE]);
   const before=await snapshot(db);assert.equal((await grantDiimOctaSeekerChip(client,{dryRun:true})).dryRun,true);assert.deepEqual(await snapshot(db),before);
   const receipt=await grantDiimOctaSeekerChip(client),after=await snapshot(db);
   assert.equal(receipt.amount,1);assert.equal(receipt.after.quantity,existing?'3':'1');assert.equal(receipt.after.unseenQuantity,'1');
   assert.equal(receipt.before.quantity,existing?'2':'0');
   const unrelated=row=>Number(row.user_id)!==TARGET.id||row.item_code!==ITEM_CODE;
   assert.deepEqual(after.cnine_user_inventory.filter(unrelated),before.cnine_user_inventory.filter(unrelated));
   for(const key of ['users','inventory_items','user_skill_chip_loadout_v2046'])assert.deepEqual(after[key],before[key]);
   assert.equal(after.inventory_logs.length,1);assert.equal(Number(after.inventory_logs[0].change_amount),1);
   assert.equal(after.inventory_logs[0].reference_id,OPERATION_KEY);assert.equal(after.admin_logs.length,1);assert.equal(after.app_meta.length,1);
   assert.equal((await grantDiimOctaSeekerChip(client)).replayed,true);assert.deepEqual(await snapshot(db),after);
  }finally{await db.close();}
 }
});
test('ledger, audit or receipt failures roll back the grant and allow one successful retry',async()=>{
 for(const table of ['inventory_logs','admin_logs','app_meta']){
  const {db,client}=await fixture();try{
   await db.exec(`ALTER TABLE ${table} ADD CONSTRAINT forced_failure CHECK(false)`);
   const before=await snapshot(db);await assert.rejects(grantDiimOctaSeekerChip(client),/forced_failure/);assert.deepEqual(await snapshot(db),before);
   await db.exec(`ALTER TABLE ${table} DROP CONSTRAINT forced_failure`);
   assert.equal((await grantDiimOctaSeekerChip(client)).after.quantity,'3');
   assert.equal((await grantDiimOctaSeekerChip(client)).replayed,true);
  }finally{await db.close();}
 }
});
test('wrong, inactive or ambiguous account, changed item and orphan ledger fail without mutations',async()=>{
 for(const change of [
  "UPDATE users SET nickname='다른 이름' WHERE id=4773",
  "UPDATE users SET status='BANNED' WHERE id=4773",
  "INSERT INTO users(id,nickname,role,status) VALUES(4774,'진짜 디임','USER','ACTIVE')",
  "UPDATE inventory_items SET is_active=0",
  "UPDATE inventory_items SET name='다른 아이템'",
  `INSERT INTO inventory_logs(user_id,item_code,reference_id) VALUES(4773,'SKILL_CHIP_OCTA_SEEKER','${OPERATION_KEY}')`
 ]){
  const {db,client}=await fixture();try{await db.exec(change);const before=await snapshot(db);await assert.rejects(grantDiimOctaSeekerChip(client));assert.deepEqual(await snapshot(db),before);}finally{await db.close();}
 }
});
