import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {PGlite} from '@electric-sql/pglite';
import {EMPEROR_ITEMS,OPERATION_KEY,registerEmperorCatalog,assertInitialCatalog} from '../scripts/ops/emperor-equipment-cms-v1.mjs';

async function setup(){
  const db=new PGlite();
  await db.exec(`CREATE TABLE character_equipment_items(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,code TEXT NOT NULL UNIQUE,name TEXT NOT NULL,slot TEXT NOT NULL,subtype TEXT NOT NULL DEFAULT '',rarity TEXT NOT NULL DEFAULT 'NORMAL',image_url TEXT NOT NULL DEFAULT '',description TEXT NOT NULL DEFAULT '',total_power BIGINT NOT NULL DEFAULT 0,pve_power BIGINT NOT NULL DEFAULT 0,pvp_power BIGINT NOT NULL DEFAULT 0,is_active BIGINT NOT NULL DEFAULT 1,is_public BIGINT NOT NULL DEFAULT 1,sort_order BIGINT NOT NULL DEFAULT 0,supply_enabled BIGINT NOT NULL DEFAULT 1,supply_weight DOUBLE PRECISION NOT NULL DEFAULT 1);
    CREATE TABLE app_meta(key TEXT PRIMARY KEY,value TEXT NOT NULL);
    INSERT INTO character_equipment_items(code,name,slot,subtype,rarity,total_power,pve_power,pvp_power) VALUES('MYSTIC_EXISTING','미스틱 슈트','TOP','TOP','MYTHIC',50000,45000,5000);`);
  return db;
}

test('four exact approved PNG assets and correct slots',async()=>{
  assert.equal(new Set(EMPEROR_ITEMS.map(item=>item.code)).size,4);
  assert.equal(EMPEROR_ITEMS.find(item=>item.code==='EMPEROR_DUAL_DISK').slot,'ACCESSORY');
  for(const item of EMPEROR_ITEMS){
    const bytes=await readFile(new URL(`../assets/items/${item.file}`,import.meta.url));
    assert.equal(createHash('sha256').update(bytes).digest('hex'),item.sha256);
    assert.equal(bytes.subarray(0,8).toString('hex'),'89504e470d0a1a0a');
    assert.equal(bytes.readUInt32BE(16),1254);assert.equal(bytes.readUInt32BE(20),1254);
  }
});

test('public CMS registration has zero stats, no supply, and preserves existing equipment',async()=>{
  const db=await setup();try{
    const before=(await db.query("SELECT * FROM character_equipment_items WHERE code='MYSTIC_EXISTING'")).rows;
    const result=await registerEmperorCatalog(db);
    assert.equal(result.alreadyRegistered,false);assertInitialCatalog(result.items);
    assert.deepEqual((await db.query("SELECT * FROM character_equipment_items WHERE code='MYSTIC_EXISTING'")).rows,before);
    const publicRows=(await db.query("SELECT code FROM character_equipment_items WHERE code LIKE 'EMPEROR_%' AND is_active=1 AND is_public=1")).rows;
    assert.equal(publicRows.length,4);
    assert.equal((await db.query("SELECT id FROM character_equipment_items WHERE code LIKE 'EMPEROR_%' AND (supply_enabled=1 OR rarity='MYTHIC')")).rows.length,0);
    assert.equal((await db.query('SELECT key FROM app_meta WHERE key=$1',[OPERATION_KEY])).rows.length,1);
  }finally{await db.close()}
});

test('retries preserve later owner settings and never insert duplicates',async()=>{
  const db=await setup();try{
    await registerEmperorCatalog(db);
    await db.query("UPDATE character_equipment_items SET total_power=987654,pve_power=888888,pvp_power=98766,rarity='MYTHIC' WHERE code='EMPEROR_TOP'");
    const repeated=await registerEmperorCatalog(db);
    assert.equal(repeated.alreadyRegistered,true);
    const top=repeated.items.find(item=>item.code==='EMPEROR_TOP');
    assert.equal(Number(top.total_power),987654);assert.equal(top.rarity,'MYTHIC');
    assert.equal((await db.query("SELECT id FROM character_equipment_items WHERE code LIKE 'EMPEROR_%'")).rows.length,4);
  }finally{await db.close()}
});

test('preexisting same-name item blocks the entire registration without overwrite',async()=>{
  const db=await setup();try{
    await db.query("INSERT INTO character_equipment_items(code,name,slot) VALUES('OWNER_CUSTOM','엠퍼러 슈트','TOP')");
    await assert.rejects(registerEmperorCatalog(db),/Existing Emperor/);
    assert.equal((await db.query('SELECT id FROM character_equipment_items')).rows.length,2);
    assert.equal((await db.query('SELECT key FROM app_meta')).rows.length,0);
  }finally{await db.close()}
});

test('failed insert rolls back all four rows and receipt',async()=>{
  const db=await setup();try{
    await db.exec("ALTER TABLE character_equipment_items ADD CHECK(code<>'EMPEROR_SHOES')");
    await assert.rejects(registerEmperorCatalog(db));
    assert.equal((await db.query('SELECT id FROM character_equipment_items')).rows.length,1);
    assert.equal((await db.query('SELECT key FROM app_meta')).rows.length,0);
  }finally{await db.close()}
});
