import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
import {EQUIPMENT,OPERATION_KEY,grantEumsuniMysticPlus9} from '../scripts/ops/eumsuni-mystic-plus9-grant-20260924.mjs';

async function fixture(){
 const db=new PGlite();
 await db.exec(`CREATE TABLE users(id BIGINT PRIMARY KEY,nickname TEXT,role TEXT,status TEXT,coin BIGINT DEFAULT 123,card_shards BIGINT DEFAULT 456,magic_crystals BIGINT DEFAULT 789);
 INSERT INTO users(id,nickname,role,status) VALUES(1,'관리자','OWNER','ACTIVE'),(65,'음순이','USER','ACTIVE'),(66,'다른 계정','USER','ACTIVE');
 CREATE TABLE character_equipment_items(id BIGINT PRIMARY KEY,code TEXT,name TEXT,slot TEXT,rarity TEXT,is_active INT,is_public INT);
 CREATE TABLE user_equipment_instances(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id BIGINT NOT NULL,equipment_id BIGINT NOT NULL,source_type TEXT DEFAULT 'ADMIN',source_id TEXT DEFAULT '',request_id TEXT,acquired_at TEXT DEFAULT 'original');
 CREATE TABLE equipment_forge_states_v1(instance_id BIGINT PRIMARY KEY,user_id BIGINT NOT NULL,level INT CHECK(level BETWEEN 0 AND 10),revision INT);
 CREATE TABLE user_equipment_loadout(user_id BIGINT,slot TEXT,instance_id BIGINT,updated_at TEXT,PRIMARY KEY(user_id,slot));
 CREATE TABLE app_meta(key TEXT PRIMARY KEY,value TEXT,updated_at TEXT);INSERT INTO app_meta VALUES('equipment_counts_v1_ready','1','original');
 CREATE TABLE admin_logs(id BIGSERIAL PRIMARY KEY,admin_id BIGINT,action_type TEXT,target_type TEXT,target_id TEXT,before_data TEXT,after_data TEXT);`);
 // Run the production count triggers so grant/rollback tests cover UI quantities too.
 const sql=await readFile(new URL('../scripts/ops/equipment-counts-v1-20260921.sql',import.meta.url),'utf8');
 await db.exec(sql.slice(sql.indexOf('CREATE TABLE IF NOT EXISTS user_equipment_counts_v1'),sql.indexOf('-- ============================== 2. 경계 id')).replace(/GRANT SELECT, INSERT, UPDATE, DELETE ON user_equipment_counts_v1 TO cnine_migrator;/,''));
 for(const item of EQUIPMENT)await db.query("INSERT INTO character_equipment_items VALUES($1,$2,$3,$4,'MYTHIC',1,1)",[item.id,item.code,item.name,item.slot]);
 await db.exec(`INSERT INTO character_equipment_items VALUES(33,'SHOES','미스틱 슈즈','SHOES','MYTHIC',1,1);
 INSERT INTO user_equipment_instances(user_id,equipment_id,request_id) VALUES(65,32,'old-bottom'),(65,34,'old-top'),(65,33,'old-shoes'),(66,35,'other-user');
 INSERT INTO equipment_forge_states_v1 VALUES(1,65,10,7),(2,65,4,5),(4,66,8,4);
 INSERT INTO user_equipment_loadout VALUES(65,'BOTTOM',1,'original'),(65,'TOP',2,'original');`);
 const client={async query(sql,args=[]){const result=await db.query(sql,args);return {...result,rowCount:result.affectedRows??result.rows.length};}};
 return {db,client};
}
async function snapshot(db){const result={};for(const table of ['users','character_equipment_items','user_equipment_instances','equipment_forge_states_v1','user_equipment_counts_v1','user_equipment_loadout','app_meta','admin_logs'])result[table]=(await db.query(`SELECT * FROM ${table} ORDER BY 1,2`)).rows;return result;}

test('grants exactly three NEW +9 copies, preserves old +10/other items and loadout, counts once, and never replays twice',async()=>{
 const {db,client}=await fixture();try{
  const before=await snapshot(db),receipt=await grantEumsuniMysticPlus9(client),after=await snapshot(db);
  assert.deepEqual(receipt.items.map(item=>[item.id,item.level,item.quantity]),[[32,9,1],[34,9,1],[35,9,1]]);
  assert.deepEqual(receipt.countsBefore.map(row=>row.quantity),['1','1','0']);assert.deepEqual(receipt.countsAfter.map(row=>row.quantity),['2','2','1']);
  assert.equal(after.user_equipment_instances.length,before.user_equipment_instances.length+3);
  assert.deepEqual(after.user_equipment_instances.filter(row=>Number(row.id)<=4),before.user_equipment_instances);
  assert.deepEqual(after.equipment_forge_states_v1.filter(row=>Number(row.instance_id)<=4),before.equipment_forge_states_v1);
  assert.ok(after.equipment_forge_states_v1.filter(row=>Number(row.instance_id)>4).every(row=>row.level===9&&Number(row.user_id)===65));
  assert.deepEqual(after.users,before.users);assert.deepEqual(after.character_equipment_items,before.character_equipment_items);assert.deepEqual(after.user_equipment_loadout,before.user_equipment_loadout);
  assert.equal(after.admin_logs.length,1);assert.equal(after.app_meta.filter(row=>row.key===OPERATION_KEY).length,1);
  assert.equal((await grantEumsuniMysticPlus9(client)).replayed,true);assert.deepEqual(await snapshot(db),after);
 }finally{await db.close();}
});

test('enhancement or audit failure rolls all instances, enhanced levels, counts and receipt back together',async()=>{
 for(const fail of ['forge','audit']){const {db,client}=await fixture();try{
  await db.exec(fail==='forge'?"ALTER TABLE equipment_forge_states_v1 ADD CONSTRAINT forced_failure CHECK(level<>9)":"ALTER TABLE admin_logs ADD CONSTRAINT forced_failure CHECK(admin_id<0)");
  const before=await snapshot(db);await assert.rejects(grantEumsuniMysticPlus9(client),/forced_failure/);assert.deepEqual(await snapshot(db),before);
 }finally{await db.close();}}
});

test('wrong target identity or changed catalog aborts with no grant',async()=>{
 for(const change of ["UPDATE users SET nickname='다른 이름' WHERE id=65","UPDATE character_equipment_items SET is_active=0 WHERE id=35"]){const {db,client}=await fixture();try{
  await db.exec(change);const before=await snapshot(db);await assert.rejects(grantEumsuniMysticPlus9(client));assert.deepEqual(await snapshot(db),before);
 }finally{await db.close();}}
});
