import test from 'node:test';
import assert from 'node:assert/strict';
import {PGlite} from '@electric-sql/pglite';
import {configureHanbokAvatars,grantHanbokAwards,NAMES,EFFECTS} from '../scripts/ops/hanbok-awards-20260928.mjs';
const old={T1_JOEUN:'T1 조은',KANGGUYEOL_DK:'DK 강구열',FM_ORIKKUNG:'FM 오리꿍',FM_DIMWOOS:'FM 딤우스',DC_HI_HEEYA:'DC 하이희야',DK_NAMU_BONGSOON:'DK 나무늘봉순',LG_JUSEONG:'LG 주성',LOTTE_AYOON:'롯데 아윤'};
const targets=[{userId:'2',nickname:'수령자',avatarCode:'FM_DIMWOOS',providerId:'linked'},{userId:'2',nickname:'수령자',avatarCode:'T1_JOEUN',providerId:'linked'},{userId:'3',nickname:'영구보유',avatarCode:'T1_JOEUN'}];
async function fixture(){const db=new PGlite();await db.exec(`CREATE TABLE users(id BIGINT PRIMARY KEY,nickname TEXT,role TEXT,status TEXT,coin BIGINT);INSERT INTO users VALUES(1,'운영자','OWNER','ACTIVE',10),(2,'수령자','USER','ACTIVE',20),(3,'영구보유','USER','ACTIVE',30);
CREATE TABLE avatar_catalog_v1(code TEXT PRIMARY KEY,name TEXT,role_label TEXT,description TEXT,effect_type TEXT,effect_value INTEGER,equipment_image TEXT,is_active INTEGER,is_public INTEGER,sale_enabled INTEGER,version INTEGER,updated_at TEXT);
CREATE TABLE avatar_effect_options_v1(avatar_code TEXT,option_order INTEGER,effect_type TEXT,effect_value INTEGER,PRIMARY KEY(avatar_code,option_order));
CREATE TABLE avatar_user_ownership_v1(user_id BIGINT,avatar_code TEXT,source_type TEXT,source_ref TEXT,acquired_at TEXT,expires_at TEXT,PRIMARY KEY(user_id,avatar_code));
CREATE TABLE avatar_user_loadout_v1(user_id BIGINT PRIMARY KEY,avatar_code TEXT,updated_at TEXT);
CREATE TABLE user_second_verifications(user_id BIGINT,provider TEXT,provider_user_id TEXT);
CREATE TABLE app_meta(key TEXT PRIMARY KEY,value TEXT,updated_at TEXT);
CREATE TABLE admin_logs(id BIGSERIAL PRIMARY KEY,admin_id BIGINT,action_type TEXT,target_type TEXT,target_id TEXT,before_data TEXT,after_data TEXT);
INSERT INTO user_second_verifications VALUES(2,'PLAYDK','linked');
INSERT INTO avatar_user_ownership_v1 VALUES(2,'FM_DIMWOOS','EVENT','original','old','2020-01-01'),(3,'T1_JOEUN','OLD_PERMANENT','keep','old',NULL),(2,'KANGGUYEOL_DK','EVENT','unrelated','old','2020-02-01');
INSERT INTO avatar_user_loadout_v1 VALUES(2,'KANGGUYEOL_DK','old');`);
const q=async(sql,args=[])=>(await db.query(sql,args)).rows;
for(const [code,name] of Object.entries(old)){await q("INSERT INTO avatar_catalog_v1 VALUES($1,$2,'클랜',$3,'COIN_GAIN_PERCENT',75,$4,1,1,0,2,'old')",[code,name,name+'의 한복입니다.','preview/avatar-clan-hanbok-v1/assets/'+code+'.webp']);await q("INSERT INTO avatar_effect_options_v1 VALUES($1,0,'COIN_GAIN_PERCENT',75),($1,1,'RAID_EXTRA_ENTRY',10)",[code]);}
await q("INSERT INTO avatar_catalog_v1 VALUES('HANBOK_DIIM','한복디임','원본','보존','DROP_RATE_PERCENT',30,'original.webp',1,1,0,3,'old')");for(const e of EFFECTS)await q("INSERT INTO avatar_effect_options_v1 VALUES('HANBOK_DIIM',$1,$2,$3)",[e.option_order,e.effect_type,e.effect_value]);
const run=async work=>{await db.exec('BEGIN');try{const r=await work(q);await db.exec('COMMIT');return r;}catch(e){await db.exec('ROLLBACK');throw e;}};
const snapshot=async()=>Object.fromEntries(await Promise.all(['users','avatar_catalog_v1','avatar_effect_options_v1','avatar_user_ownership_v1','avatar_user_loadout_v1','app_meta','admin_logs'].map(async t=>[t,await q('SELECT * FROM '+t+' ORDER BY 1,2')])));
return {db,q,run,snapshot};}
test('eight names/options match original hanbok; permanent grants upgrade expired, preserve permanent and unrelated accounts; replay is inert',async()=>{const f=await fixture();try{const a=await f.snapshot();const meta=await f.run(configureHanbokAvatars);assert.equal(meta.count,8);const r=await f.run(q=>grantHanbokAwards(q,targets));assert.equal(r.count,3);assert.equal(r.new,1);assert.equal(r.upgraded,1);assert.equal(r.alreadyPermanent,1);const b=await f.snapshot();assert.deepEqual(b.users,a.users);assert.deepEqual(b.avatar_user_loadout_v1,a.avatar_user_loadout_v1);assert.deepEqual(b.avatar_catalog_v1.find(x=>x.code==='HANBOK_DIIM'),a.avatar_catalog_v1.find(x=>x.code==='HANBOK_DIIM'));for(const [code,name] of Object.entries(NAMES)){const row=b.avatar_catalog_v1.find(x=>x.code===code);assert.equal(row.name,name);assert.equal(row.effect_type,'DROP_RATE_PERCENT');assert.equal(row.effect_value,30);assert.equal(row.version,3);}assert.equal((await f.run(configureHanbokAvatars)).replayed,true);assert.equal((await f.run(q=>grantHanbokAwards(q,targets))).replayed,true);assert.deepEqual(await f.snapshot(),b);}finally{await f.db.close();}});
test('reference option drift rolls back every catalog name and option',async()=>{const f=await fixture();try{await f.q("UPDATE avatar_effect_options_v1 SET effect_value=99 WHERE avatar_code='HANBOK_DIIM' AND option_order=1");const a=await f.snapshot();await assert.rejects(f.run(configureHanbokAvatars),/Reference options changed/);assert.deepEqual(await f.snapshot(),a);}finally{await f.db.close();}});
test('wrong recipient identity and audit failure both roll back the whole grant batch',async()=>{const f=await fixture();try{await f.run(configureHanbokAvatars);const a=await f.snapshot();await assert.rejects(f.run(q=>grantHanbokAwards(q,targets.map(t=>({...t,...(t.userId==='2'?{providerId:'wrong'}:{})})))),/PLAY DK identity changed/);assert.deepEqual(await f.snapshot(),a);await f.q("ALTER TABLE admin_logs ADD CONSTRAINT reject_grant CHECK(action_type<>'HANBOK_PERMANENT_AWARDS')");await assert.rejects(f.run(q=>grantHanbokAwards(q,targets)),/reject_grant/);assert.deepEqual(await f.snapshot(),a);}finally{await f.db.close();}});
