import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import {pathToFileURL} from 'node:url';
import assert from 'node:assert/strict';
import {cityFixture} from './helpers/jokgak-city-fixture.mjs';
import {handleJokgakCity} from '../functions/_jokgak_city.js';
import {readCitySettings,saveCitySettings} from '../functions/_jokgak_city_settings.js';
import {cityLifeKey} from '../shared/jokgak-city-life-v1.mjs';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE?pathToFileURL(process.env.PLAYWRIGHT_MODULE).href:'playwright');
const origin=process.env.CITY_QA_ORIGIN||'http://127.0.0.1:8918',out=process.env.CITY_QA_DIR||fs.mkdtempSync(path.join(os.tmpdir(),'city-life-'));
fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({channel:'chrome',headless:true}),checks=[],errors=[];
const owner={id:80,role:'OWNER',nickname:'도시 관리자'};
try{
  for(const width of [1440,390]){
    const cleanup=[],f=await cityFixture({after:fn=>cleanup.push(fn)}),context=await browser.newContext({viewport:{width,height:960},isMobile:width<600,hasTouch:width<600});let actor=f.users.get(1);
    try{
      const p=(await readCitySettings(f.env)).policy;p.mode='TEST';p.testUserIds=[1,2];await saveCitySettings(f.env,owner,p,f.now);await f.join(1);await f.join(2);
      const setLife=async patch=>{const row=await f.p('SELECT value FROM app_meta WHERE key=?',cityLifeKey(1)).first();await f.p('UPDATE app_meta SET value=? WHERE key=?',JSON.stringify({...JSON.parse(row.value),...patch}),cityLifeKey(1)).run();};
      await setLife({hunger:15,wellness:65});
      const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
      await page.addInitScript(now=>{window.__CITY_TIME__=now;Date.now=()=>window.__CITY_TIME__;localStorage.setItem('cnine_battle_sound','OFF');localStorage.setItem('cnine_admin_token','CITY_LIFE_ISOLATED');},f.now);
      const advance=async ms=>{f.advance(ms);await page.evaluate(now=>window.__CITY_TIME__=now,f.now);};
      await page.route('**/api/**',async route=>{
        const req=route.request(),url=new URL(req.url());const response=await handleJokgakCity({path:url.pathname.slice(5),env:f.env,deps:{...f.deps,authenticate:async()=>actor,json:(data,status=200)=>Response.json(data,{status})},request:new Request(req.url(),{method:req.method(),headers:req.headers(),...(['GET','HEAD'].includes(req.method())?{}:{body:req.postData()})})});
        await route.fulfill(response?{status:response.status,body:await response.text(),contentType:'application/json'}:{json:{items:[],cards:[],visible:false,enabled:false}});
      });
      await page.route('**/__city-life-qa/',route=>route.fulfill({contentType:'text/html',body:'<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><body style="margin:0;background:#080d18"><main></main><script>function loadUser(){return '+JSON.stringify(actor)+'}</script><script src="/js/jokgak-city-v1.js?v=life-qa"></script><script>document.querySelector("main").innerHTML=JokgakCity.view();JokgakCity.bind();</script></body></html>'}));
      const visit=async()=>{await page.goto(origin+'/__city-life-qa/',{waitUntil:'domcontentloaded'});await page.locator('.jc-needs').waitFor();};
      const close=async()=>page.locator('.jc-dialog [data-city-dialog-close]').last().click();
      const go=async place=>{await page.locator(`.jc-pin[data-city-place="${place}"]`).click();await page.locator(`.jc-pin[data-city-place="${place}"].selected`).waitFor();const b=page.locator('[data-city-action="move"]');if(!await b.isDisabled())await b.click();await page.locator(`.jc-pin.current[data-city-place="${place}"]`).waitFor();};
      const service=async action=>{await page.locator(`[data-city-action="${action}"]`).first().click();await page.locator('[data-city-confirm]').click();await page.locator('.jc-dialog h2').filter({hasText:'완료'}).waitFor();await close();};
      await visit();assert.equal(await page.locator('[data-city-cash]').textContent(),'10,000원');assert.match(await page.locator('.jc-cash').textContent(),/테스트 현금/);assert.equal(await page.locator('.jc-pin').count(),10);assert.match(await page.locator('[data-need="hunger"]').textContent(),/15/);await go('RESTAURANT');await page.screenshot({path:path.join(out,`${width}-restaurant.png`),fullPage:true});await service('eat');assert.match(await page.locator('[data-need="hunger"]').textContent(),/75/);assert.equal(await page.locator('[data-city-cash]').textContent(),'9,000원');checks.push(`${width}: meal costs 1,000 city cash and restores hunger`);
      await advance(5000);await go('SHOP');await page.screenshot({path:path.join(out,`${width}-shop.png`),fullPage:true});await service('buy');assert.match(await page.locator('.jc-bag').textContent(),/휴대 도시락/);await advance(5000);await page.locator('[data-city-action="use"]').click();await page.locator('.jc-dialog h2').filter({hasText:'완료'}).waitFor();await close();assert.match(await page.locator('[data-need="hunger"]').textContent(),/100/);assert.equal((await f.p('SELECT coin FROM users WHERE id=1').first()).coin,123456);assert.equal(await page.locator('[data-city-cash]').textContent(),'7,500원');checks.push(`${width}: TEST purchase costs cash, carried use is free and game coin stays unchanged`);
      await advance(5000);await f.p("UPDATE jokgak_city_players_v1 SET location='SHOP',health=10 WHERE user_id=1").run();await f.p("UPDATE jokgak_city_players_v1 SET location='SHOP' WHERE user_id=2").run();await f.action(2,'attack',{targetId:1});await page.locator('[data-city-refresh]').click();await page.locator('.jc-death-screen').waitFor();assert.equal(await page.locator('[data-death-clock]').textContent(),'03:00');assert.match(await page.locator('.jc-death-screen').textContent(),/참가자 2/);assert.match(await page.locator('.jc-death-screen').textContent(),/병원/);await page.screenshot({path:path.join(out,`${width}-death.png`),fullPage:true});
      await advance(60000);await page.reload({waitUntil:'domcontentloaded'});await page.locator('[data-death-clock]').filter({hasText:'02:00'}).waitFor();checks.push(`${width}: killer, hospital and server countdown survive reload`);
      await page.evaluate(()=>{JokgakCity.stop();document.querySelector('main').innerHTML='<h1 style="color:white">다른 콘텐츠 진행 중</h1>';});await page.locator('.jc-death-global').waitFor();assert.equal(await page.locator('[data-global-death-clock]').textContent(),'02:00');await page.screenshot({path:path.join(out,`${width}-global-death.png`),fullPage:true});checks.push(`${width}: death countdown remains in other content without modal blocking`);
      await advance(120000);await visit();await page.locator('.jc-pin.current[data-city-place="HOSPITAL"]').waitFor();assert.equal(await page.locator('.jc-death-screen').count(),0);assert.match(await page.locator('.jc-vitals').textContent(),/100/);assert.equal(await page.locator('[data-city-cash]').textContent(),'7,500원');checks.push(`${width}: hospital respawn preserves city cash after reload`);
      await setLife({wellness:20,hunger:5,at:f.now});await f.p("UPDATE jokgak_city_players_v1 SET location='HOME' WHERE user_id=1").run();await page.locator('[data-city-refresh]').click();await page.locator('.jc-health-alert').waitFor();await page.locator('.jc-services h3').filter({hasText:'병원 진료'}).waitFor();await page.screenshot({path:path.join(out,`${width}-hospital.png`),fullPage:true});await service('treat');assert.equal(await page.locator('.jc-health-alert').count(),0);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));assert.equal(await page.locator('[data-city-cash]').textContent(),'5,500원');checks.push(`${width}: treatment costs 2,000 city cash and releases hospital restriction`);
      actor=owner;await page.route('**/admin/',route=>route.fulfill({contentType:'text/html',body:fs.readFileSync(new URL('../admin/index.html',import.meta.url),'utf8').replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'').replace('</body>','<script type="module" src="/admin/jokgak-city-admin-v1.mjs"></script></body>')}));
      await page.goto(origin+'/admin/#jokgak-city',{waitUntil:'domcontentloaded'});await page.evaluate(()=>{document.body.classList.remove('auth-guest');document.body.classList.add('auth-active');document.getElementById('cms').hidden=false;document.getElementById('roleBadge').textContent='OWNER';});await page.locator('[data-tab="life"]').click();await page.locator('[data-path="cash.startingCash"]').fill('30000');await page.locator('[data-path="life.meal.price"]').fill('1234');await page.locator('[data-path="life.hungerPerHour"]').fill('18');await page.locator('[data-path="life.supplies.1.wellness"]').fill('30');await page.locator('.city-cms-save button').click();await page.locator('.city-cms-note').filter({hasText:'저장 완료'}).waitFor();await page.locator('[data-reload]').click();await page.locator('.city-cms-note').filter({hasText:'불러왔습니다'}).waitFor();assert.equal(await page.locator('[data-path="cash.startingCash"]').inputValue(),'30000');assert.equal(await page.locator('[data-path="life.meal.price"]').inputValue(),'1234');assert.equal((await readCitySettings(f.env)).policy.life.supplies[1].wellness,30);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:path.join(out,`${width}-cms-life.png`),fullPage:true});checks.push(`${width}: CMS life and shop settings persist and fit screen`);
    }finally{await context.close();for(const fn of cleanup)await fn();}
  }
  assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'life-browser-report.json'),JSON.stringify({checks,errors},null,2)+'\n');console.log(JSON.stringify({out,checks:checks.length,errors}));
}finally{await browser.close();}
