import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {pathToFileURL} from 'node:url';
import {cityFixture} from './helpers/jokgak-city-fixture.mjs';
import {handleJokgakCity} from '../functions/_jokgak_city.js';
import {readCitySettings,saveCitySettings} from '../functions/_jokgak_city_settings.js';
const {chromium}=await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE).href);
const origin='http://127.0.0.1:8918',out=process.env.CITY_QA_DIR||'docs/qa/jokgak-city-career-20261010';fs.mkdirSync(out,{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true}),checks=[],errors=[];
try{for(const width of [1440,390]){
 const cleanup=[],f=await cityFixture({after:fn=>cleanup.push(fn)}),id=f.roles.POLICE;const policy=(await readCitySettings(f.env)).policy;policy.career.enabled=true;await saveCitySettings(f.env,{id:80,role:'OWNER'},policy,f.now);await f.join(id);await f.join(f.roles.GANG);let actor=f.users.get(id);
 const page=await browser.newPage({viewport:{width,height:960},reducedMotion:'reduce'});page.on('pageerror',e=>errors.push(e.message));
 try{
  await page.addInitScript(now=>{window.__CITY_TIME__=now;Date.now=()=>window.__CITY_TIME__;localStorage.setItem('cnine_admin_token','ISOLATED_CITY_CAREER');},f.now);
  const advance=async ms=>{f.advance(ms);await page.evaluate(now=>window.__CITY_TIME__=now,f.now);};
  await page.route('**/api/**',async route=>{const req=route.request(),url=new URL(req.url()),response=await handleJokgakCity({path:url.pathname.slice(5),env:f.env,deps:{...f.deps,authenticate:async()=>actor,json:(v,status=200)=>Response.json(v,{status})},request:new Request(req.url(),{method:req.method(),headers:req.headers(),...(['GET','HEAD'].includes(req.method())?{}:{body:req.postData()})})});await route.fulfill(response?{status:response.status,body:await response.text(),contentType:'application/json'}:{json:{items:[],cards:[],enabled:false}});});
  await page.route('**/__city-career-qa/',route=>route.fulfill({contentType:'text/html',body:`<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><body style="margin:0;background:#080d18"><main></main><script>function loadUser(){return ${JSON.stringify(actor)}};</script><script src="/js/jokgak-city-v1.js"></script><script>document.querySelector('main').innerHTML=JokgakCity.view();JokgakCity.bind();</script></body></html>`}));
  await page.goto(origin+'/__city-career-qa/',{waitUntil:'domcontentloaded'});await page.locator('.jc-dashboard-id strong').filter({hasText:'참가자'}).waitFor();await page.evaluate(()=>document.fonts.ready);
  assert.equal(await page.locator('.jc-pin').count(),11);assert.equal(await page.locator('.jc-profile').count(),0);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:path.join(out,`${width}-map.png`),fullPage:true});checks.push(`${width}: compact HUD, map and roster are visible with no horizontal overflow`);
  const open=async tab=>{await page.locator(`.jc-desk-launchers [data-city-desk="${tab}"]`).click();await page.locator('.jc-desk[open]').waitFor();};
  const tab=async tab=>{await page.locator(`.jc-desk-tabs [data-city-desk="${tab}"]`).click();};
  const close=async()=>{await page.keyboard.press('Escape');await page.locator('.jc-desk').waitFor({state:'detached'});};
  const shot=async name=>{assert.ok(await page.locator('.jc-desk-content').evaluate(n=>n.scrollWidth<=n.clientWidth+1));await page.locator('.jc-desk').screenshot({path:path.join(out,`${width}-${name}.png`)});};
  await open('profile');assert.match(await page.locator('.jc-profile-job').textContent(),/경찰/);assert.match(await page.locator('[data-need="health"]').textContent(),/150/);await shot('profile');await close();checks.push(`${width}: profile popup retains HP150, hunger, health and weapon detail; Escape closes`);
  await page.locator('.jc-service-launch').click();await page.locator('[data-city-action="buyWeapon"][data-city-product="PIPE"]').click();await page.locator('[data-city-confirm]').click();await page.locator('.jc-armory [data-city-action="equipWeapon"][data-city-product="PIPE"]').waitFor();await advance(5000);await tab('inventory');await page.locator('.jc-mini-weapons [data-city-action="equipWeapon"]').click();await page.locator('.jc-mini-weapons .is-equipped').waitFor();await shot('inventory');assert.equal(await page.locator('.jc-dashboard-cash b').textContent(),'8,000원');checks.push(`${width}: popup market purchase, inventory equip and cash update`);
  await tab('career');await shot('career');await page.locator('.jc-employment [data-city-place="POLICE"]').click();await page.locator('.jc-pin.selected[data-city-place="POLICE"]').waitFor();await page.locator('[data-city-action="move"]').click();await page.locator('.jc-pin.current[data-city-place="POLICE"]').waitFor();await open('career');await page.locator('[data-city-action="employment"]').click();await page.locator('.jc-employment button').filter({hasText:'등록 완료'}).waitFor();await page.locator('[data-city-action="workStart"][data-city-product="PATROL"]').click();await page.locator('.jc-active-work').waitFor();assert.ok(await page.locator('[data-city-action="workFinish"]').isDisabled());await shot('work');await advance(300000);await page.waitForFunction(()=>!document.querySelector('[data-city-action="workFinish"]')?.disabled);await page.locator('[data-city-action="workFinish"]').click();await page.locator('.jc-active-work').waitFor({state:'detached'});assert.equal(await page.locator('.jc-dashboard-cash b').textContent(),'8,900원');checks.push(`${width}: employment, timed patrol and one 900-won salary claim`);
  await tab('police');await page.locator('.jc-police-people article').waitFor();assert.match(await page.locator('.jc-police-header').textContent(),/실적 1/);await shot('police');await tab('protection');assert.match(await page.locator('.jc-protection-rules').textContent(),/선제공격하면 즉시 해제/);await shot('protection');await close();checks.push(`${width}: police directory and protection rules show in dedicated popups`);
  await advance(3600000);await page.locator('[data-city-refresh]').click();await page.waitForFunction(()=>document.querySelector('.jc-dashboard-cash b')?.textContent==='11,900원');checks.push(`${width}: hourly police income is credited without a claim button`);
  actor={id:80,nickname:'관리자',role:'OWNER'};await page.route('**/admin/',r=>r.fulfill({contentType:'text/html',body:fs.readFileSync(new URL('../admin/index.html',import.meta.url),'utf8').replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'').replace('</body>','<script type="module" src="/admin/jokgak-city-admin-v1.mjs"></script></body>')}));await page.goto(origin+'/admin/#jokgak-city',{waitUntil:'domcontentloaded'});await page.evaluate(()=>{document.body.classList.remove('auth-guest');document.body.classList.add('auth-active');document.getElementById('cms').hidden=false;document.getElementById('roleBadge').textContent='OWNER';});await page.locator('[data-tab="career"]').click();assert.equal(await page.locator('[data-path="career.rates.0.cash"]').inputValue(),'2000');assert.equal(await page.locator('[data-path="career.resetCash"]').inputValue(),'10000');await page.locator('[data-path="career.rates.0.cash"]').fill('2100');await page.locator('.city-cms-save button').click();await page.locator('.city-cms-note').filter({hasText:'저장 완료'}).waitFor();assert.equal((await readCitySettings(f.env)).policy.career.rates[0].cash,2100);assert.equal((await readCitySettings(f.env)).policy.mode,'ON');await page.screenshot({path:path.join(out,`${width}-cms.png`),fullPage:true});checks.push(`${width}: CMS saves wages, shift cash, jobs and rank policy while preserving mode`);
 }catch(e){await page.screenshot({path:path.join(out,`${width}-failure.png`),fullPage:true});fs.writeFileSync(path.join(out,`${width}-failure.json`),JSON.stringify({message:e.message,errors,body:await page.locator('body').textContent()},null,2));throw e;}finally{await page.close();for(const fn of cleanup)await fn();}
}assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'browser.json'),JSON.stringify({checks,errors,accounts:'isolated fixtures'},null,2));console.log(JSON.stringify({out,checks:checks.length,errors}));}finally{await browser.close();}
