import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import assert from 'node:assert/strict';
import {pathToFileURL} from 'node:url';
import {cityFixture} from './helpers/jokgak-city-fixture.mjs';
import {handleJokgakCity} from '../functions/_jokgak_city.js';
import {readCitySettings} from '../functions/_jokgak_city_settings.js';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE?pathToFileURL(process.env.PLAYWRIGHT_MODULE).href:'playwright');
const origin=process.env.CITY_QA_ORIGIN||'http://127.0.0.1:8918',out=process.env.CITY_QA_DIR||fs.mkdtempSync(path.join(os.tmpdir(),'city-expansion-'));
fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({channel:'chrome',headless:true}),checks=[],errors=[];
try{
 for(const width of [1440,390]){
  const cleanup=[],f=await cityFixture({after:fn=>cleanup.push(fn)}),id=f.roles.POLICE;await f.join(id);let actor=f.users.get(id);
  const page=await browser.newPage({viewport:{width,height:960},reducedMotion:'reduce'});page.on('pageerror',e=>errors.push(e.message));
  try{
   await page.addInitScript(now=>{window.__CITY_TIME__=now;Date.now=()=>window.__CITY_TIME__;localStorage.setItem('cnine_admin_token','ISOLATED_CITY_EXPANSION');},f.now);
   const advance=async ms=>{f.advance(ms);await page.evaluate(now=>window.__CITY_TIME__=now,f.now);};
   await page.route('**/api/**',async route=>{const req=route.request(),url=new URL(req.url()),response=await handleJokgakCity({path:url.pathname.slice(5),env:f.env,deps:{...f.deps,authenticate:async()=>actor,json:(v,status=200)=>Response.json(v,{status})},request:new Request(req.url(),{method:req.method(),headers:req.headers(),...(['GET','HEAD'].includes(req.method())?{}:{body:req.postData()})})});await route.fulfill(response?{status:response.status,body:await response.text(),contentType:'application/json'}:{json:{items:[],cards:[],enabled:false}});});
   await page.route('**/__city-expansion-qa/',route=>route.fulfill({contentType:'text/html',body:`<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><body style="margin:0;background:#080d18"><main></main><script>function loadUser(){return ${JSON.stringify(actor)}};</script><script src="/js/jokgak-city-v1.js"></script><script>document.querySelector('main').innerHTML=JokgakCity.view();JokgakCity.bind();</script></body></html>`}));
   const visit=async n=>{actor=f.users.get(n);await page.goto(origin+'/__city-expansion-qa/',{waitUntil:'domcontentloaded'});await page.evaluate(now=>window.__CITY_TIME__=now,f.now);await page.locator('.jc-profile-job').waitFor();await page.evaluate(()=>document.fonts.ready);};
   const select=async location=>{await page.locator(`.jc-pin[data-city-place="${location}"]`).click();await page.waitForFunction(p=>document.querySelector('.jc-pin.selected')?.dataset.cityPlace===p,location);};
   const buy=async code=>{await page.locator(`.jc-armory [data-city-action="buyWeapon"][data-city-product="${code}"]`).click();await page.locator('[data-city-confirm]').click();await page.waitForFunction(p=>document.querySelector(`.jc-mini-weapons [data-city-product="${p}"]`),code);};
   await visit(id);assert.equal(await page.locator('.jc-pin').count(),11);assert.match(await page.locator('[data-need="health"]').textContent(),/150/);assert.match(await page.locator('.jc-city-loadout').textContent(),/100,000/);
   await buy('PIPE');assert.equal(await page.locator('[data-city-cash]').textContent(),'8,000원');assert.match(await page.locator('.jc-city-loadout').textContent(),/맨손/);await advance(5000);await page.locator('.jc-mini-weapons [data-city-action="equipWeapon"]').click();await page.locator('.jc-city-loadout').filter({hasText:'쇠파이프'}).waitFor();assert.match(await page.locator('.jc-city-loadout').textContent(),/200,000/);assert.match(await page.locator('.jc-mini-weapons .is-equipped em').textContent(),/장착 중/);checks.push(`${width}: police HP150, 11 places, 2000-won purchase and explicit equip update whole-team power`);
   await page.screenshot({path:path.join(out,`${width}-market.png`),fullPage:true});
   await buy('PISTOL');await advance(5000);await page.locator('.jc-mini-weapons [data-city-product="PISTOL"]').click();await page.locator('.jc-city-loadout').filter({hasText:'권총'}).waitFor();assert.equal(await page.locator('[data-city-cash]').textContent(),'0원');assert.match(await page.locator('.jc-city-loadout').textContent(),/300,000/);assert.equal(await page.locator('.jc-mini-weapons .is-equipped').count(),1);assert.ok(await page.locator('.jc-armory [data-city-product="RIFLE"]').isDisabled());await page.locator('.jc-mini-inventory').screenshot({path:path.join(out,`${width}-inventory.png`)});checks.push(`${width}: inventory switches one equipped weapon and blocks unaffordable rifle`);
   await select('MOTEL');await page.locator('[data-city-action="move"]').click();await page.locator('.jc-pin.current[data-city-place="MOTEL"]').waitFor();await page.locator('[data-city-action="rest"]').click();await page.locator('[data-city-action="checkout"]').waitFor();assert.match(await page.locator('[data-city-condition]').textContent(),/휴식/);await page.locator('.jc-motel').screenshot({path:path.join(out,`${width}-motel.png`)});checks.push(`${width}: motel admission shows private room, 15-minute countdown and checkout`);
   await advance(900000);await page.locator('.jc-pin.current[data-city-place="HOME"]').waitFor();await select('MOTEL');assert.ok(await page.locator('[data-city-action="rest"]').isDisabled());assert.match(await page.locator('.jc-motel').textContent(),/재이용/);checks.push(`${width}: expired rest moves home and retains one-hour reuse cooldown`);
   await select('HOSPITAL');await page.locator('[data-city-action="move"]').click();await page.locator('.jc-facility-banner').waitFor();assert.match(await page.locator('.jc-facility-banner').textContent(),/5:00/);await page.locator('.jc-facility-banner').screenshot({path:path.join(out,`${width}-hospital.png`)});await advance(300000);await page.waitForFunction(()=>!document.querySelector('.jc-pin.current[data-city-place="HOSPITAL"]'));checks.push(`${width}: hospital has five-minute countdown and automatic exit`);
   await f.join(f.roles.DOCTOR,'HOSPITAL');await visit(f.roles.DOCTOR);await select('HOSPITAL');assert.match(await page.locator('.jc-facility-banner').textContent(),/의료진 상주 가능/);await advance(360000);await page.locator('[data-city-refresh]').click();await page.locator('.jc-pin.current[data-city-place="HOSPITAL"]').waitFor();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));checks.push(`${width}: doctors may remain and the page has no horizontal overflow`);
   actor={id:80,nickname:'관리자',role:'OWNER'};await page.route('**/admin/',r=>r.fulfill({contentType:'text/html',body:fs.readFileSync(new URL('../admin/index.html',import.meta.url),'utf8').replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'').replace('</body>','<script type="module" src="/admin/jokgak-city-admin-v1.mjs"></script></body>')}));await page.goto(origin+'/admin/#jokgak-city',{waitUntil:'domcontentloaded'});await page.evaluate(()=>{document.body.classList.remove('auth-guest');document.body.classList.add('auth-active');document.getElementById('cms').hidden=false;document.getElementById('roleBadge').textContent='OWNER';});await page.locator('[data-tab="expansion"]').click();assert.equal(await page.locator('[data-path="arsenal.weapons.0.price"]').inputValue(),'2000');assert.equal(await page.locator('[data-path="facilities.motel.stayMs"]').inputValue(),'15');assert.equal(await page.locator('[data-path="facilities.hospital.maxStayMs"]').inputValue(),'5');await page.locator('[data-path="arsenal.weapons.0.price"]').fill('2100');await page.locator('.city-cms-save button').click();await page.locator('.city-cms-note').filter({hasText:'저장 완료'}).waitFor();assert.equal((await readCitySettings(f.env)).policy.arsenal.weapons[0].price,2100);assert.equal((await readCitySettings(f.env)).policy.mode,'ON');await page.screenshot({path:path.join(out,`${width}-cms.png`),fullPage:true});checks.push(`${width}: CMS weapon prices and facilities save while preserving ON`);
  }catch(error){await page.screenshot({path:path.join(out,`${width}-failure.png`),fullPage:true});fs.writeFileSync(path.join(out,`${width}-failure.json`),JSON.stringify({error:error.message,errors,body:await page.locator('body').textContent()},null,2));throw error;}finally{await page.close();for(const fn of cleanup)await fn();}
 }
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'expansion-browser.json'),JSON.stringify({checks,errors,accounts:'isolated fixtures',battle:'separate real V3 playback test'},null,2));console.log(JSON.stringify({out,checks:checks.length,errors}));
}finally{await browser.close();}
