import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import assert from 'node:assert/strict';
import {pathToFileURL} from 'node:url';
import {cityFixture} from './helpers/jokgak-city-fixture.mjs';
import {cityStatus,handleJokgakCity} from '../functions/_jokgak_city.js';
import {readCitySettings} from '../functions/_jokgak_city_settings.js';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE?pathToFileURL(process.env.PLAYWRIGHT_MODULE).href:'playwright');
const origin=process.env.CITY_QA_ORIGIN||'http://127.0.0.1:8918',out=process.env.CITY_QA_DIR||fs.mkdtempSync(path.join(os.tmpdir(),'city-roles-'));
fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({channel:'chrome',headless:true}),checks=[],errors=[];
try{
 for(const width of [1440,390]){
  const cleanup=[],f=await cityFixture({after:fn=>cleanup.push(fn)}),beg=f.roles.BEGGAR,donor=f.roles.CITIZEN,gang=f.roles.GANG;
  for(const id of [beg,donor,gang])await f.join(id);let actor=f.users.get(beg);
  const page=await browser.newPage({viewport:{width,height:960},reducedMotion:'reduce'});page.on('pageerror',e=>errors.push(e.message));
  try{
   await page.addInitScript(now=>{window.__CITY_TIME__=now;Date.now=()=>window.__CITY_TIME__;localStorage.setItem('cnine_battle_sound','OFF');localStorage.setItem('cnine_admin_token','ISOLATED_CITY_ROLES');},f.now);
   const advance=async ms=>{f.advance(ms);await page.evaluate(now=>window.__CITY_TIME__=now,f.now);};
   await page.route('**/api/**',async route=>{const req=route.request(),url=new URL(req.url()),response=await handleJokgakCity({path:url.pathname.slice(5),env:f.env,deps:{...f.deps,authenticate:async()=>actor,json:(v,status=200)=>Response.json(v,{status})},request:new Request(req.url(),{method:req.method(),headers:req.headers(),...(['GET','HEAD'].includes(req.method())?{}:{body:req.postData()})})});await route.fulfill(response?{status:response.status,body:await response.text(),contentType:'application/json'}:{json:{items:[],cards:[],enabled:false}});});
   await page.route('**/__city-roles-qa/',route=>route.fulfill({contentType:'text/html',body:`<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><body style="margin:0;background:#080d18"><main></main><script>function loadUser(){return ${JSON.stringify(actor)}};window.ensureFeatureResources=async()=>{};window.prepareBattleV2LiveLoading=()=>({stage:Object.assign(document.createElement('div'),{innerHTML:'<header class="battle-v3-header"><strong></strong><small></small></header>'}),host:document.createElement('div')});window.playPvpBattleV2Live=async()=>{};</script><script src="/js/jokgak-city-v1.js"></script><script>document.querySelector('main').innerHTML=JokgakCity.view();JokgakCity.bind();</script></body></html>`}));
   const visit=async id=>{actor=f.users.get(id);await page.goto(origin+'/__city-roles-qa/',{waitUntil:'domcontentloaded'});await page.evaluate(now=>window.__CITY_TIME__=now,f.now);await page.locator('.jc-profile-job').waitFor();};
   await visit(beg);await page.locator('[data-city-action="alms"]').click();await page.locator('.jc-role-skill p').filter({hasText:'도움을 요청하고 있습니다'}).waitFor();assert.ok(await page.locator('[data-city-action="beg"]').isDisabled());await page.screenshot({path:path.join(out,`${width}-beggar-skill.png`),fullPage:true});checks.push(`${width}: beggar has both skills and a shared cooldown`);
   await visit(donor);await page.locator('.jc-beg-toast').waitFor();assert.match(await page.locator('.jc-beg-toast').textContent(),/동냥 중이에요/);const bounds=await page.evaluate(()=>{const a=document.querySelector('.jc-beg-toast').getBoundingClientRect(),b=document.querySelector('.jc-map-stage').getBoundingClientRect();return a.right<=b.right&&a.bottom<=b.bottom&&a.left>=b.left;});assert.ok(bounds);await page.locator('.jc-map-stage').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,`${width}-alms-map.png`),animations:'disabled'});checks.push(`${width}: small donation prompt stays inside the bottom-right map corner`);
   await page.locator('[data-city-donate]').click();await page.locator('[data-city-cash]').filter({hasText:'9,900원'}).waitFor();assert.equal((await cityStatus(f.env,f.users.get(beg),'MARKET',0,f.now)).mine.cash,10100);await page.waitForFunction(()=>!document.querySelector('.jc-beg-toast'));checks.push(`${width}: Give moves 100 won, updates profile and removes the request`);
   await advance(61000);await f.action(beg,'beg');await page.locator('[data-city-refresh]').click();await page.locator('.jc-beg-toast').waitFor();await page.locator('[data-city-decline]').click();await page.waitForFunction(()=>!document.querySelector('.jc-beg-toast'));assert.equal(await page.locator('[data-city-cash]').textContent(),'9,900원');checks.push(`${width}: decline closes the request without spending`);
   await advance(61000);await f.action(beg,'alms');await page.locator('[data-city-refresh]').click();await page.locator('.jc-beg-toast').waitFor();await advance(30000);await page.waitForFunction(()=>!document.querySelector('.jc-beg-toast'));checks.push(`${width}: server deadline removes expired prompts`);
   await f.p('UPDATE jokgak_city_players_v1 SET health=100,next_action_at=0,protected_until=0').run();f.deps.prepareCityBattle=async()=>({battleV2:{result:{winner:'B'}}});await page.locator('[data-city-refresh]').click();await page.locator(`.jc-person[data-city-person="${gang}"]`).click();await page.locator('[data-city-action="attack"]').click();await page.locator('.jc-battle-result').waitFor();assert.match(await page.locator('.jc-battle-result').textContent(),/교전 패배/);assert.match(await page.locator('.jc-combat-hp').textContent(),/75 \/ 100/);assert.match(await page.locator('[data-need="health"]').textContent(),/75/);await page.screenshot({path:path.join(out,`${width}-attacker-defeat.png`)});await page.locator('.jc-battle-result button').click();checks.push(`${width}: losing attacker sees 25 HP loss, remaining 75 and an updated profile`);
   await visit(gang);assert.match(await page.locator('.jc-gang-skill').textContent(),/20%/);assert.match(await page.locator('.jc-gang-skill').textContent(),/4,000원/);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));checks.push(`${width}: gang profile shows kill-only 20% / 4,000 won`);
   actor={id:80,nickname:'관리자',role:'OWNER'};await page.route('**/admin/',r=>r.fulfill({contentType:'text/html',body:fs.readFileSync(new URL('../admin/index.html',import.meta.url),'utf8').replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'').replace('</body>','<script type="module" src="/admin/jokgak-city-admin-v1.mjs"></script></body>')}));await page.goto(origin+'/admin/#jokgak-city',{waitUntil:'domcontentloaded'});await page.evaluate(()=>{document.body.classList.remove('auth-guest');document.body.classList.add('auth-active');document.getElementById('cms').hidden=false;document.getElementById('roleBadge').textContent='OWNER';});await page.locator('[data-tab="roles"]').click();await page.locator('[data-role="BEGGAR"]').click();assert.equal(await page.locator('[data-path="roles.1.begCash"]').inputValue(),'100');await page.locator('[data-path="roles.1.begDurationMs"]').fill('25');await page.locator('[data-role="GANG"]').click();assert.equal(await page.locator('[data-path="roles.5.killTheftMaxCash"]').inputValue(),'4000');await page.locator('.city-cms-save button').click();await page.locator('.city-cms-note').filter({hasText:'저장 완료'}).waitFor();assert.equal((await readCitySettings(f.env)).policy.roles[1].begDurationMs,25000);checks.push(`${width}: CMS beggar and gang settings load and save`);
  }finally{await page.close();for(const fn of cleanup)await fn();}
 }
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'roles-browser.json'),JSON.stringify({checks,errors,battlePlayback:'stubbed; actual city action handler and wallets'},null,2));console.log(JSON.stringify({out,checks:checks.length,errors}));
}finally{await browser.close();}
