import test from 'node:test';
import assert from 'node:assert/strict';
import {PGlite} from '@electric-sql/pglite';
import {grantLichEntries,OPERATION_KEY,ITEM_CODE,ITEM_NAME} from '../scripts/ops/lich-entry-three-grant-20261001.mjs';

async function fixture(t){
 const db=new PGlite();t.after(()=>db.close());
 await db.exec(`CREATE TABLE users(id BIGINT PRIMARY KEY,nickname TEXT,role TEXT,status TEXT,coin BIGINT DEFAULT 123);
 INSERT INTO users(id,nickname,role,status) VALUES(1,'관리자','OWNER','ACTIVE'),(88,'0수표','USER','ACTIVE'),(1195,'씨나인택갓','USER','ACTIVE'),(1768,'핫시','USER','ACTIVE');
 CREATE TABLE inventory_items(code TEXT PRIMARY KEY,name TEXT,is_active BIGINT);
 CREATE TABLE cnine_user_inventory(user_id BIGINT,item_code TEXT,quantity BIGINT,unseen_quantity BIGINT,created_at TEXT,updated_at TEXT,PRIMARY KEY(user_id,item_code));
 CREATE TABLE inventory_logs(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id BIGINT,item_code TEXT,change_amount BIGINT,balance_after BIGINT,reason TEXT,reference_type TEXT,reference_id TEXT,admin_id BIGINT,created_at TEXT);
 CREATE TABLE admin_logs(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,admin_id BIGINT,action_type TEXT,target_type TEXT,target_id TEXT,before_data TEXT,after_data TEXT,created_at TEXT);
 CREATE TABLE app_meta(key TEXT PRIMARY KEY,value TEXT,updated_at TEXT);
 INSERT INTO cnine_user_inventory VALUES(88,'LICH_KING_ENTRY_TICKET',2,0,'original','original'),(88,'MASTER_STAR',900,3,'original','original'),(1,'LICH_KING_ENTRY_TICKET',8,1,'original','original');`);
 await db.query('INSERT INTO inventory_items VALUES($1,$2,1)',[ITEM_CODE,ITEM_NAME]);
 const client={query:async(sql,args=[])=>sql.includes(' AS kst')?{rows:[{kst:'2026-10-01'}]}:db.query(sql,args)};
 const snapshot=async()=>{const data={};for(const table of ['users','inventory_items','cnine_user_inventory','inventory_logs','admin_logs','app_meta'])data[table]=(await db.query('SELECT * FROM '+table+' ORDER BY 1,2')).rows;return data;};
 return {db,client,snapshot};
}

test('dry run rolls back, exactly three accounts receive ten tickets, and replay cannot duplicate',async t=>{
 const f=await fixture(t),before=await f.snapshot();
 const dry=await grantLichEntries(f.client,{dryRun:true});assert.equal(dry.dryRun,true);assert.deepEqual(await f.snapshot(),before);
 const result=await grantLichEntries(f.client),after=await f.snapshot();assert.equal(result.receipt.totalGranted,30);assert.equal(result.verification.grantLogs,3);
 assert.deepEqual(result.receipt.allocations.map(x=>[x.userId,x.before.quantity,x.after.quantity]),[[88,'2','12'],[1195,'0','10'],[1768,'0','10']]);
 assert.deepEqual(after.users,before.users);assert.deepEqual(after.inventory_items,before.inventory_items);
 assert.deepEqual(after.cnine_user_inventory.filter(x=>x.item_code!==ITEM_CODE||Number(x.user_id)===1),before.cnine_user_inventory.filter(x=>x.item_code!==ITEM_CODE||Number(x.user_id)===1));
 assert.equal(after.inventory_logs.length,3);assert.ok(after.inventory_logs.every(x=>x.reference_id===OPERATION_KEY));assert.equal(after.admin_logs.length,1);
 assert.equal((await grantLichEntries(f.client)).replayed,true);assert.deepEqual(await f.snapshot(),after);
});

test('a mid-grant ledger failure rolls back every account and a retry grants once',async t=>{
 const f=await fixture(t);await f.db.exec('ALTER TABLE inventory_logs ADD CONSTRAINT forced_failure CHECK(user_id<>1195)');const before=await f.snapshot();
 await assert.rejects(grantLichEntries(f.client),/forced_failure/);assert.deepEqual(await f.snapshot(),before);
 await f.db.exec('ALTER TABLE inventory_logs DROP CONSTRAINT forced_failure');assert.equal((await grantLichEntries(f.client)).verification.totalGranted,30);
});

test('a changed recipient identity blocks the operation without writing inventory',async t=>{
 const f=await fixture(t);await f.db.query("UPDATE users SET nickname='다른 계정' WHERE id=1768");const before=await f.snapshot();
 await assert.rejects(grantLichEntries(f.client));assert.deepEqual(await f.snapshot(),before);
});
