import test from 'node:test';import assert from 'node:assert/strict';
import {lootFixture} from './helpers/loot-shop-db.mjs';
import {LOOT_SHOP_DEFAULTS,validateLootShopPolicy} from '../shared/loot-shop-policy-v1.mjs';
import {pigCoinBalance,purchaseLootProduct,openLootPack,pigCoinRewardStatements,lootShopState,saveLootShopPolicy,handleLootShop,LOOT_SHOP_KEY} from '../functions/_loot_shop.js';
const id=()=>crypto.randomUUID();
test('unconfigured economy stays OFF; prices, caps and weights must be explicit',()=>{assert.equal(validateLootShopPolicy(LOOT_SHOP_DEFAULTS).salesEnabled,false);for(const value of [0,-1,4,1.5,'2']){const p=structuredClone(LOOT_SHOP_DEFAULTS);p.products[0].accountLimit=value;assert.throws(()=>validateLootShopPolicy(p));}const p=structuredClone(LOOT_SHOP_DEFAULTS);p.products[0].enabled=true;assert.throws(()=>validateLootShopPolicy(p));});
for(const postgres of [false,true]){const label=postgres?'PostgreSQL':'SQLite';
 test(`${label}: lifetime cap, replay and account isolation`,async t=>{const f=await lootFixture(t,{postgres}),requestId=id(),body={productId:'f_body',requestId};const a=await purchaseLootProduct(f.env,f.user,body);assert.equal(a.state.pigCoins,475);assert.equal((await purchaseLootProduct(f.env,f.user,body)).replayed,true);assert.equal(await pigCoinBalance(f.env,7),475);await assert.rejects(()=>purchaseLootProduct(f.env,{id:8},body),{code:'JOINT_REQUEST_CONFLICT'});await purchaseLootProduct(f.env,f.user,{productId:'f_body',requestId:id()});await assert.rejects(()=>purchaseLootProduct(f.env,f.user,{productId:'f_body',requestId:id()}));assert.equal(await pigCoinBalance(f.env,7),450);assert.equal(Number((await f.p('SELECT COUNT(*) n FROM user_equipment_instances WHERE user_id=7 AND equipment_id=37').first()).n),2);});
 test(`${label}: failed delivery rolls back debit, purchase count, and ledger`,async t=>{const f=await lootFixture(t,{postgres}),body={productId:'f_body',requestId:id()};f.fail('INSERT INTO user_equipment_instances');await assert.rejects(()=>purchaseLootProduct(f.env,f.user,body));assert.equal(await pigCoinBalance(f.env,7),500);assert.equal((await f.p('SELECT * FROM loot_shop_purchases_v1').all()).results.length,0);assert.equal((await f.p('SELECT * FROM pig_coin_ledger_v1').all()).results.length,0);f.fail('');assert.equal((await purchaseLootProduct(f.env,f.user,body)).state.pigCoins,475);});
 test(`${label}: false entitlement predicate grants zero coins; each content pays only once`,async t=>{const f=await lootFixture(t,{postgres});for(const source of ['TERRITORY','CLAN','CORE_RAID']){await f.DB.batch(await pigCoinRewardStatements(f.env,{userId:7,source,referenceId:'round-1',guardSql:'1=0',rewardSql:()=>({sql:'?',bindings:[30]})}));assert.equal(await pigCoinBalance(f.env,7),500+['TERRITORY','CLAN','CORE_RAID'].indexOf(source)*30);for(let i=0;i<2;i++)await f.DB.batch(await pigCoinRewardStatements(f.env,{userId:7,source,referenceId:'round-1',guardSql:'1=1',rewardSql:()=>({sql:'?',bindings:[30]})}));}assert.equal(await pigCoinBalance(f.env,7),590);f.shopPolicy.rewardsEnabled=false;await f.setShop(f.shopPolicy);assert.deepEqual(await pigCoinRewardStatements(f.env,{userId:7,source:'TERRITORY',referenceId:'round-2',guardSql:'1=1'}),[]);});
 test(`${label}: choice pack selects eligible card, preserves pack on failure and never double opens`,async t=>{const f=await lootFixture(t,{postgres}),packId=id();await purchaseLootProduct(f.env,f.user,{productId:'superstar_choice',requestId:packId});await assert.rejects(()=>openLootPack(f.env,f.user,{packId,requestId:id(),cardId:'fur1'}));const body={packId,requestId:id(),cardId:'ss1'};f.fail('INSERT INTO user_cards');await assert.rejects(()=>openLootPack(f.env,f.user,body));assert.equal((await lootShopState(f.env,f.user)).ownedPacks.length,1);f.fail('');const r=await openLootPack(f.env,f.user,body);assert.equal(r.reward.id,'ss1');await openLootPack(f.env,f.user,body);assert.equal(Number((await f.p("SELECT quantity FROM user_cards WHERE user_id=7 AND card_id='ss1'").first()).quantity),1);await assert.rejects(()=>openLootPack(f.env,f.user,{...body,requestId:id()}));});
 test(`${label}: mercenary packs always grant one A/S card and freeze rolls for retry`,async t=>{const f=await lootFixture(t,{postgres}),packId=id();await purchaseLootProduct(f.env,f.user,{productId:'mercenary_pack',requestId:packId});const body={packId,requestId:id()};f.fail('INSERT INTO mercenary_card_acquisitions_v1');await assert.rejects(()=>openLootPack(f.env,f.user,body,{randomInt:()=>0}));f.fail('');const r=await openLootPack(f.env,f.user,body,{randomInt:()=>{throw Error('reroll');}});assert.equal(r.reward.rank,'A');assert.equal((await lootShopState(f.env,f.user)).ownedPacks.length,0);assert.equal((await openLootPack(f.env,f.user,body)).replayed,true);});
 test(`${label}: OFF, insufficient balance, inactive equipment, and stale CMS edits reject safely`,async t=>{const f=await lootFixture(t,{postgres});await f.p('UPDATE pig_coin_wallets_v1 SET balance=0 WHERE user_id=7').run();await assert.rejects(()=>purchaseLootProduct(f.env,f.user,{productId:'f_body',requestId:id()}));await f.p('UPDATE pig_coin_wallets_v1 SET balance=500 WHERE user_id=7').run();await f.p('UPDATE character_equipment_items SET is_active=0 WHERE id=37').run();await assert.rejects(()=>purchaseLootProduct(f.env,f.user,{productId:'f_body',requestId:id()}));f.shopPolicy.salesEnabled=false;await f.setShop(f.shopPolicy);await assert.rejects(()=>purchaseLootProduct(f.env,f.user,{productId:'fur_choice',requestId:id()}));await assert.rejects(()=>saveLootShopPolicy(f.env,{id:8,role:'USER'},f.shopPolicy),{code:'JOINT_PERMISSION'});assert.equal(await pigCoinBalance(f.env,7),500);});
}
test('route requires login, OWNER for CMS, same-origin JSON and exact fields',async t=>{const f=await lootFixture(t),req=(path,options={})=>new Request(`https://game.test/api/${path}`,options);let r=await handleLootShop({path:'loot-shop/state',request:req('loot-shop/state'),env:f.env,deps:f.deps});assert.equal(r.status,401);r=await handleLootShop({path:'loot-shop/purchase',request:req('loot-shop/purchase',{method:'POST',headers:{authorization:'Bearer local-account-7','content-type':'application/json'},body:'{}'}),env:f.env,deps:f.deps});assert.equal(r.status,403);});
