import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {MERCENARY_CMS_SEED as seed} from '../functions/_mercenary_cms_seed.js';
import {S_SKILL_IDS} from '../shared/mercenary-s-skills-v2.mjs';
import {expandMercenarySkillCatalog} from '../shared/mercenary-cms-model-v1.mjs';
import {prepareSSkillAssignments} from '../shared/mercenary-s-skill-assignment-v3.mjs';
const plan=JSON.parse(fs.readFileSync(new URL('../preview/project-v-mercenary-system-v1/skill-s-ss-plan-v3.json',import.meta.url)));
function prior(){const d=structuredClone(seed.document);d.skills=d.skills.filter(s=>!S_SKILL_IDS.includes(s.id));for(const r of d.mercenaries)r.rank=plan.targets.find(t=>t.code===r.code)?.rank||(['V-021','V-046','V-049'].includes(r.code)?'SSS':['V-044','V-045','V-047','V-048'].includes(r.code)?'SS':'C');d.assignments.find(r=>r.code==='V-021').skillIds=['MS-021'];d.assignments.find(r=>r.code==='V-036').skillIds=['MS-032'];d.mercenaries[0].notes='운영자 검수 메모 보존';d.skills[0].balance={damageRatio:2.3,cooldownTurns:7,cost:30};d.skills[0].name='운영자 이름 보존';return d;}
test('catalog upgrade retains every previous edit and never assigns on read',()=>{
 const d=prior(),before=structuredClone(d),next=expandMercenarySkillCatalog(d,seed.document,seed.catalog);assert.deepEqual(d,before);assert.deepEqual(next.mercenaries,d.mercenaries);assert.deepEqual(next.settings,d.settings);assert.deepEqual(next.assignments,d.assignments);assert.deepEqual(next.skills.slice(0,d.skills.length),d.skills);assert.equal(next.skills.length,33);assert.ok(next.skills.filter(s=>S_SKILL_IDS.includes(s.id)).every(s=>s.review==='PENDING'&&s.balance.damageRatio===null));
});
test('explicit assignment covers S6 and SS8, preserves other ranks and existing chosen skills, and is idempotent',()=>{
 const d=prior(),next=prepareSSkillAssignments(d,seed.document,seed.catalog,{...plan,targets:[...plan.targets,{code:'V-044',rank:'SS',skillId:'MS-044'},{code:'V-045',rank:'SS',skillId:'MS-045'},{code:'V-047',rank:'SS',skillId:'MS-047'},{code:'V-048',rank:'SS',skillId:'MS-048'}]});assert.equal(plan.targets.filter(t=>t.rank==='S').length,6);assert.equal(plan.targets.filter(t=>t.rank==='SS').length,8);for(const t of plan.targets)assert.ok(next.assignments.find(r=>r.code===t.code).skillIds.includes(t.skillId));assert.deepEqual(next.assignments.find(r=>r.code==='V-021').skillIds,['MS-021']);assert.deepEqual(next.assignments.find(r=>r.code==='V-036').skillIds,['MS-032','MS-036']);assert.ok(next.assignments.filter(r=>!plan.targets.some(t=>t.code===r.code)).every(r=>JSON.stringify(r)===JSON.stringify(d.assignments.find(s=>s.code===r.code))));assert.deepEqual(prepareSSkillAssignments(next,seed.document,seed.catalog,{...plan,targets:[...plan.targets,{code:'V-044',rank:'SS',skillId:'MS-044'},{code:'V-045',rank:'SS',skillId:'MS-045'},{code:'V-047',rank:'SS',skillId:'MS-047'},{code:'V-048',rank:'SS',skillId:'MS-048'}]}),next);assert.equal(next.runtimeEnabled,false);
});
test('partial previous catalogs and changed live rank scope cannot erase or expand assignments',()=>{
 const d=prior();d.skills.pop();assert.throws(()=>expandMercenarySkillCatalog(d,seed.document,seed.catalog));
 const rank=prior();rank.mercenaries.find(r=>r.code==='V-001').rank='A';assert.throws(()=>prepareSSkillAssignments(rank,seed.document,seed.catalog,{...plan,targets:[...plan.targets,{code:'V-044',rank:'SS',skillId:'MS-044'},{code:'V-045',rank:'SS',skillId:'MS-045'},{code:'V-047',rank:'SS',skillId:'MS-047'},{code:'V-048',rank:'SS',skillId:'MS-048'}]}));
 const extra=prior();extra.mercenaries.find(r=>r.code==='V-002').rank='S';assert.throws(()=>prepareSSkillAssignments(extra,seed.document,seed.catalog,{...plan,targets:[...plan.targets,{code:'V-044',rank:'SS',skillId:'MS-044'},{code:'V-045',rank:'SS',skillId:'MS-045'},{code:'V-047',rank:'SS',skillId:'MS-047'},{code:'V-048',rank:'SS',skillId:'MS-048'}]}));
 assert.throws(()=>prepareSSkillAssignments(prior(),seed.document,seed.catalog,{...plan,authority:'INFERRED'}));
});
