import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import assert from 'node:assert/strict';import {pathToFileURL} from 'node:url';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE?pathToFileURL(process.env.PLAYWRIGHT_MODULE).href:'playwright');
const base=process.env.LIMITED_QA_ORIGIN||'http://127.0.0.1:4319',out=process.env.LIMITED_QA_DIR||fs.mkdtempSync(path.join(os.tmpdir(),'limited-mercenary-qa-')),browser=await chromium.launch({channel:'chrome',headless:true}),checks=[],errors=[],failed=[];
const check=(v,s)=>{assert.ok(v,s);checks.push(s);};
try{
 for(const viewport of process.env.LIMITED_QA_CMS_ONLY==='1'?[]:[{width:1440,height:1000},{width:390,height:844}]){
  const page=await browser.newPage({viewport,serviceWorkers:'block'}),label=viewport.width+'px';page.on('pageerror',e=>errors.push(label+': '+e.message));page.on('response',r=>{if(r.status()>=400&&new URL(r.url()).origin===base)failed.push(r.status()+' '+new URL(r.url()).pathname);});
  await page.addInitScript(()=>{localStorage.setItem('cnine_card_api_token','local-limited-qa');localStorage.setItem('cnine_card_user_v10',JSON.stringify({id:7,nickname:'검수'}));});
  await page.goto(base+'/mercenary-codex/?view=all',{waitUntil:'domcontentloaded'});await page.locator('.roster-row').first().waitFor();await page.locator('#limitedView').click();check(await page.locator('.roster-row').count()===6,label+' limited tab displays six cards');check(await page.locator('#limitedView').getAttribute('aria-selected')==='true',label+' selected tab updates');check(new URL(page.url()).searchParams.get('view')==='limited',label+' limited deep link is retained');
  await page.locator('[data-code="V-996"]').click();await page.locator('.limited-art-card .source-art').evaluate(img=>img.decode());await page.locator('.limited-art-card .card-frame').evaluate(img=>img.decode());check(await page.locator('.limited-lock').textContent().then(s=>s.includes('획득 · 편성 불가')),label+' acquisition and deployment lock is explicit');check(await page.locator('[data-equip]').count()===0,label+' no equip action');check(await page.locator('.combat-panel a[href*="pack=hyper"]').count()===0,label+' no acquisition link');check((await page.locator('.card-frame').getAttribute('src')).includes('frame-valter-slim-v3'),label+' Valter uses selected V3 frame');
  await page.locator('#sdTab').click();await page.locator('.sd-display img').evaluate(img=>img.decode());check(await page.locator('#sdTab').getAttribute('aria-selected')==='true',label+' approved SSS SD opens');await page.locator('#artTab').click();await page.screenshot({path:path.join(out,'limited-'+label+'.png'),fullPage:true});check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),label+' no horizontal overflow');
  await page.locator('[data-code="V-990"]').click();check(await page.locator('.limited-record').textContent().then(s=>s.includes('미정')),label+' unconfirmed rank stays unset');check(await page.locator('#sdTab').isDisabled(),label+' missing SD stays unavailable');
  await page.reload();await page.locator('.roster-row').first().waitFor();check(await page.locator('.roster-row').count()===6,label+' reload retains limited tab');
  await page.locator('#allView').click();check(await page.locator('.roster-row').count()>6,label+' general codex still works');await page.locator('#ownedView').click();check(await page.locator('.roster-row').count()===0,label+' owned roster does not claim locked limited cards');
  await page.goto(base+'/preview/mercenary-crimson-silver-knight-battle-v1/?v=17-valter-sss-limited#battle',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>!document.getElementById('play').disabled,{},{timeout:45000});await page.locator('#impact').click();check(await page.locator('iframe').count()===1,label+' SSS battle preview initializes');await page.screenshot({path:path.join(out,'valter-preview-'+label+'.png'),fullPage:true});await page.close();
 }
 const page=await browser.newPage({viewport:{width:1440,height:1000},serviceWorkers:'block'});page.on('pageerror',e=>errors.push('CMS: '+e.message));await page.goto(base+'/review/limited#mercenaries/limited',{waitUntil:'domcontentloaded'});await page.locator('[data-limited-rate="SSS"]').waitFor();check(await page.locator('[data-limited-weight]').count()===6,'CMS displays separate six-card limited pool');await page.locator('[data-limited-rate="SSS"]').fill('0.0001');await page.locator('[data-limited-save]').click();await page.waitForFunction(()=>document.querySelector('[data-limited-root]')?.textContent.includes('저장 완료'));check(await page.locator('[data-limited-root]').textContent().then(s=>s.includes('획득 잠금 유지')),'CMS save keeps acquisition locked');await page.screenshot({path:path.join(out,'limited-cms-desktop.png'),fullPage:true});await page.setViewportSize({width:390,height:844});check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'CMS mobile has no horizontal overflow');await page.screenshot({path:path.join(out,'limited-cms-mobile.png'),fullPage:true});await page.close();
 check(errors.length===0,'no browser JavaScript errors: '+errors.join(' | '));check(failed.length===0,'all local assets load: '+failed.join(' | '));fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({checks,errors,failed},null,2));console.log(JSON.stringify({passed:checks.length,out,errors,failed}));
}finally{await browser.close();}
