import test from 'node:test';
import assert from 'node:assert/strict';
import {PGlite} from '@electric-sql/pglite';
import {swapNamsudaengHanbok} from '../scripts/ops/namsudaeng-hanbok-swap-20260928.mjs';
async function fixture(){const db=new PGlite();await db.exec(`CREATE TABLE users(id BIGINT PRIMARY KEY,nickname TEXT,status TEXT,role TEXT,coin BIGINT);INSERT INTO users VALUES(1,'운영자','ACTIVE','OWNER',123),(183,'남수댕','ACTIVE','USER',456),(200,'다른계정','ACTIVE','USER',789);
CREATE TABLE user_second_verifications(user_id BIGINT,provider TEXT,provider_user_id TEXT);INSERT INTO user_second_verifications VALUES(183,'PLAYDK','c6762516');
CREATE TABLE avatar_catalog_v1(code TEXT PRIMARY KEY,name TEXT,is_active INTEGER,is_public INTEGER);INSERT INTO avatar_catalog_v1 VALUES('DC_HI_HEEYA','한복 하이희야',1,1),('FM_DIMWOOS','한복 디임2',1,1);
CREATE TABLE avatar_user_ownership_v1(user_id BIGINT,avatar_code TEXT,source_type TEXT,source_ref TEXT,acquired_at TEXT,expires_at TEXT,PRIMARY KEY(user_id,avatar_code));
INSERT INTO avatar_user_ownership_v1 VALUES(183,'DC_HI_HEEYA','EVENT','clan','old','2030-01-01'),(183,'FM_DIMWOOS','ADMIN_GRANT','awards','earlier',NULL),(183,'OTHER','EVENT','keep','old','2031-01-01'),(200,'DC_HI_HEEYA','EVENT','keep','old',NULL);
CREATE TABLE avatar_user_loadout_v1(user_id BIGINT PRIMARY KEY,avatar_code TEXT,updated_at TEXT);INSERT INTO avatar_user_loadout_v1 VALUES(183,'DC_HI_HEEYA','preserve-cooldown'),(200,'DC_HI_HEEYA','other');
CREATE TABLE app_meta(key TEXT PRIMARY KEY,value TEXT,updated_at TEXT);CREATE TABLE admin_logs(id BIGSERIAL PRIMARY KEY,admin_id BIGINT,action_type TEXT,target_type TEXT,target_id TEXT,before_data TEXT,after_data TEXT);`);
const q=async(sql,args=[])=>(await db.query(sql,args)).rows,run=async()=>{await db.exec('BEGIN');try{const r=await swapNamsudaengHanbok(q);await db.exec('COMMIT');return r;}catch(e){await db.exec('ROLLBACK');throw e;}},snapshot=async()=>Object.fromEntries(await Promise.all(['users','avatar_user_ownership_v1','avatar_user_loadout_v1','app_meta','admin_logs'].map(async t=>[t,await q('SELECT * FROM '+t+' ORDER BY 1,2')])));return {db,q,run,snapshot};}
test('revoke only Heeya, preserve existing permanent Diim2, replace equipped Heeya without resetting cooldown; replay is inert',async()=>{const f=await fixture();try{const a=await f.snapshot(),r=await f.run(),b=await f.snapshot();assert.equal(r.revoked,1);assert.equal(r.granted,0);assert.equal(r.alreadyPermanent,true);assert.equal(r.equippedReplaced,true);assert.deepEqual(b.users,a.users);assert.deepEqual(b.avatar_user_ownership_v1,a.avatar_user_ownership_v1.filter(x=>!(Number(x.user_id)===183&&x.avatar_code==='DC_HI_HEEYA')));assert.deepEqual(b.avatar_user_loadout_v1,a.avatar_user_loadout_v1.map(x=>Number(x.user_id)===183?{...x,avatar_code:'FM_DIMWOOS'}:x));assert.equal((await f.run()).replayed,true);assert.deepEqual(await f.snapshot(),b);}finally{await f.db.close();}});
test('missing Diim2 is granted permanently while a different equipped avatar stays intact',async()=>{const f=await fixture();try{await f.q("DELETE FROM avatar_user_ownership_v1 WHERE user_id=183 AND avatar_code='FM_DIMWOOS'");await f.q("UPDATE avatar_user_loadout_v1 SET avatar_code='OTHER' WHERE user_id=183");const r=await f.run();assert.equal(r.granted,1);assert.equal(r.equippedReplaced,false);assert.equal((await f.q("SELECT expires_at FROM avatar_user_ownership_v1 WHERE user_id=183 AND avatar_code='FM_DIMWOOS'"))[0].expires_at,null);assert.equal((await f.q('SELECT avatar_code FROM avatar_user_loadout_v1 WHERE user_id=183'))[0].avatar_code,'OTHER');}finally{await f.db.close();}});
test('audit failure rolls back the revoke, replacement and receipt',async()=>{const f=await fixture();try{await f.q("ALTER TABLE admin_logs ADD CONSTRAINT reject_audit CHECK(action_type='REJECT')");const a=await f.snapshot();await assert.rejects(f.run,/reject_audit/);assert.deepEqual(await f.snapshot(),a);}finally{await f.db.close();}});
