import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {createHash} from 'node:crypto';
import sharp from 'sharp';
import {PGlite} from '@electric-sql/pglite';
import {AKAZA,OPERATION_KEY,registerNightmareAkaza} from '../scripts/ops/nightmare-akaza-release-20261007.mjs';
import {pveDifficultyRuntime} from '../functions/_pve_nightmare.js';
import {createPveBattleV2} from '../functions/_battle_v2_preview.js';

const profile={battlePower:1450000,rewardCoin:80000,hpPercent:300,attackPercent:380,defensePercent:300,speedPercent:300,rewardPercent:800,bossUltimateCapPercent:400};
const settings={enabled:true,bossUltimateUnlocked:true,bossProfiles:{70:profile},unrelated:'PRESERVE'};
const ultimate={ultimate_enabled:1,ultimate_name:'',ultimate_description:'',ultimate_trigger:'CHANCE',ultimate_chance:100,ultimate_damage_percent:15,ultimate_max_uses:1,ultimate_target:'ALL',ultimate_theme:'CRIMSON',ultimate_warning_text:'BOSS ULTIMATE',ultimate_shake:1,ultimate_zoom:1,ultimate_media_url:'assets/effects/gold.mp4',ultimate_sound_url:'',ultimate_duration_ms:10000,ultimate_volume_percent:35,ultimate_force_cast:1,ultimate_pve_damage_percent:15,ultimate_tower_damage_percent:15};
const assets=[AKAZA.sourceArt,AKAZA.battleSprite].map(path=>({path,verified:true,sha256:createHash('sha256').update(fs.readFileSync(new URL('../'+path,import.meta.url))).digest('hex')}));
async function fixture(){
 const db=new PGlite();
 await db.exec(`CREATE TABLE app_meta(key text PRIMARY KEY,value text,updated_at text);
 CREATE TABLE battle_monsters(id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 79) PRIMARY KEY,name text,image_url text,battle_power bigint,reward_coin bigint,is_boss int,is_active int,sort_order int,monster_category text,pve_tab text,pve_display_order int,pve_enabled int,tower_enabled int,tower_only int,${Object.entries(ultimate).map(([k,v])=>k+(typeof v==='number'?' integer':' text')).join(',')});
 CREATE TABLE users(id bigint PRIMARY KEY,role text,status text);INSERT INTO users VALUES(1,'OWNER','ACTIVE');
 CREATE TABLE admin_logs(id serial PRIMARY KEY,admin_id bigint,action_type text,target_type text,target_id text,before_data text,after_data text);`);
 const anchor={id:70,name:'골 D. 로저',image_url:'assets/tower/goldd.jpg',battle_power:1000,reward_coin:100,is_boss:1,is_active:1,sort_order:34,pve_tab:'NIGHTMARE',pve_display_order:34,pve_enabled:1,...ultimate};
 await db.query('INSERT INTO battle_monsters('+Object.keys(anchor).join(',')+') VALUES('+Object.keys(anchor).map((_,i)=>'$'+(i+1)).join(',')+')',Object.values(anchor));
 await db.query('INSERT INTO app_meta(key,value) VALUES($1,$2)',['battle_nightmare_settings_v1',JSON.stringify(settings)]);
 return {db,client:{query:(sql,args)=>db.query(sql,args)}};
}

test('original attachment and unmodified transparent full-body SD resolve only in the Nightmare/Hunt battle adapter',async()=>{
 const read=p=>fs.readFileSync(new URL('../'+p,import.meta.url));
 const evidence=JSON.parse(read('assets/ui/project-v/monsters/nightmare-akaza-v1/manifest.json'));
 assert.equal(evidence.pixelEdits,false);
 for(const file of evidence.files)assert.equal(createHash('sha256').update(read(file.path)).digest('hex').toUpperCase(),file.sha256);
 assert.equal(evidence.files[0].sha256,'A2060FE4D1478077D4B033C1A2045655154C2D24B88A418784E038E65AA50AEC');
 const {data,info}=await sharp(read(AKAZA.battleSprite)).raw().toBuffer({resolveWithObject:true});
 assert.equal(info.channels,4);assert.equal(info.width,1254);assert.equal(info.height,1254);
 let clear=0;for(let y=0;y<info.height;y++)for(let x=0;x<info.width;x++){
  const a=data[(y*info.width+x)*4+3];if(a===0)clear++;
  if(x===0||y===0||x===info.width-1||y===info.height-1)assert.ok(a<=1,'Visible pixels reach canvas edge');
 }
 assert.ok(clear/(info.width*info.height)>.6);
 const manifest=JSON.parse(read('assets/ui/project-v/monsters/hunt-tower/manifest-v1.json'));
 const sandbox={};vm.runInNewContext(read('js/project-v-monster-battle-art-adapter-v1.js').toString(),sandbox);
 const adapter=sandbox.ProjectVMonsterBattleArt.createAdapter({manifest});
 const original={id:79,image:AKAZA.sourceArt,name:AKAZA.name};
 const adapted=adapter.adaptBattlePayload({monster:original},{mode:'NIGHTMARE'});
 assert.equal(original.image,AKAZA.sourceArt);assert.ok(adapted.monster.image.startsWith('/'+AKAZA.battleSprite+'?v='));
 assert.equal(adapter.resolveForV3(original,{mode:'TOWER'}),null);assert.equal(adapter.resolveForV3(original,{mode:'APOCALYPSE'}),null);
 assert.equal(adapter.resolveForV3({id:70},{mode:'NIGHTMARE'}).name,'골 D. 로저');
 assert.ok(sandbox.ProjectVMonsterBattleArt.constants.MANIFEST_URL.includes('nm=20261007-akaza'));
 assert.ok(read('js/app.js').toString().includes('project-v-monster-battle-art-adapter-v1.js?v=5.5.0-apocalypse-legion&nm=20261007-akaza'));
});

test('registration is atomic, preserves Gold Roger, rolls back dry runs and replays without a second boss',async()=>{
 const {db,client}=await fixture();
 try{
  const before=(await db.query('SELECT * FROM battle_monsters WHERE id=70')).rows[0];
  const dry=await registerNightmareAkaza(client);
  assert.equal(dry.committed,false);assert.equal(dry.registered.displayOrder,35);
  assert.equal((await db.query('SELECT id FROM battle_monsters WHERE id=79')).rows.length,0);
  await assert.rejects(registerNightmareAkaza(client,{commit:true}),/Published asset not verified/);
  const failing={query:(sql,args)=>sql.startsWith('INSERT INTO admin_logs')?Promise.reject(Error('injected audit failure')):client.query(sql,args)};
  await assert.rejects(registerNightmareAkaza(failing,{commit:true,assets}),/injected audit failure/);
  assert.deepEqual(JSON.parse((await db.query("SELECT value FROM app_meta WHERE key='battle_nightmare_settings_v1'")).rows[0].value),settings);
  assert.equal((await db.query('SELECT id FROM battle_monsters WHERE id=79')).rows.length,0);
  const saved=await registerNightmareAkaza(client,{commit:true,assets});
  assert.equal(saved.committed,true);
  const after=JSON.parse((await db.query("SELECT value FROM app_meta WHERE key='battle_nightmare_settings_v1'")).rows[0].value);
  assert.deepEqual(after.bossProfiles[70],profile);assert.equal(after.unrelated,'PRESERVE');
  assert.equal(after.bossProfiles[79].battlePower,1800000);assert.equal(after.bossProfiles[79].rewardCoin,80000);
  assert.deepEqual((await db.query('SELECT * FROM battle_monsters WHERE id=70')).rows[0],before);
  const row=(await db.query('SELECT * FROM battle_monsters WHERE id=79')).rows[0];
  assert.equal(Number(row.tower_enabled),0);assert.equal(row.ultimate_media_url,'');assert.equal(row.ultimate_sound_url,'');
  assert.equal(Number(row.ultimate_pve_damage_percent),15);
  assert.equal((await registerNightmareAkaza(client,{commit:true,assets})).replayed,true);
  assert.equal((await db.query('SELECT id FROM admin_logs')).rows.length,1);
  assert.equal((await db.query('SELECT key FROM app_meta WHERE key=$1',[OPERATION_KEY])).rows.length,1);
  assert.equal(Number((await db.query("INSERT INTO battle_monsters(name) VALUES('NEXT CMS BOSS') RETURNING id")).rows[0].id),80);
 }finally{await db.close();}
});

test('CMS OFF and occupied IDs block registration without changes',async()=>{
 const {db,client}=await fixture();
 try{
  await db.query('UPDATE app_meta SET value=$1',[JSON.stringify({...settings,enabled:false})]);
  await assert.rejects(registerNightmareAkaza(client),/OFF switch/);
  await db.query('UPDATE app_meta SET value=$1',[JSON.stringify(settings)]);
  await db.query("INSERT INTO battle_monsters(id,name) VALUES(79,'Existing boss')");
  await assert.rejects(registerNightmareAkaza(client),/occupied ID/);
  assert.equal((await db.query('SELECT id FROM admin_logs')).rows.length,0);
 }finally{await db.close();}
});

test('Akaza uses the common Nightmare opening ultimate and a single boss with inherited rewards',()=>{
 const runtime=pveDifficultyRuntime({nightmare:{...settings,bossProfiles:{...settings.bossProfiles,79:{...profile,battlePower:1800000}}}},{id:79,name:'아카자',is_boss:1,pve_tab:'NIGHTMARE',battle_power:1800000});
 assert.equal(runtime.effectiveRewardCoin,640000);assert.equal(runtime.effectiveBattlePower,5832000);
 assert.equal(runtime.bossUltimateCapPercent,400);
 const cards=Array.from({length:5},(_,i)=>({id:'QA'+i,name:'QA',grade:'ZENITH',power:500000,power_type:'ATTACK'}));
 const battle=createPveBattleV2({cards,monster:runtime.engineMonster,seed:7,bossUltimatePercent:15,bossUltimateCapPercent:400});
 assert.equal(battle.teams.B.cards.length,1);
 const casts=battle.result.timeline.filter(e=>e.type==='BOSS_ULTIMATE');assert.equal(casts.length,1);assert.equal(casts[0].damagePercent,15);
 assert.equal(battle.result.timeline.some(e=>e.type==='APOCALYPSE_SKILL'),false);
});
