import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {PGlite} from '@electric-sql/pglite';
import {__postgresCompatTest} from '../functions/_postgres_d1_compat.js';
import {handleSkillChips} from '../functions/_skill_chips.js';

const ROCKET='SKILL_CHIP_ROCKET_LAUNCHER',HELI='SKILL_CHIP_HELICOPTER_AIRSTRIKE',OCTA='SKILL_CHIP_OCTA_SEEKER',BOX='PRIME_EQUIPMENT_SUPPLY_BOX';
let fixtureId=0;
class SqliteD1 {
  constructor(){this.db=new DatabaseSync(':memory:');}
  prepare(sql){
    const owner=this;
    return {values:[],bind(...values){this.values=values;return this},async first(){return owner.db.prepare(sql).get(...this.values)||null},async all(){return {results:owner.db.prepare(sql).all(...this.values)}},
      async run(){const result=owner.db.prepare(sql).run(...this.values);return {meta:{changes:Number(result.changes)},results:[]}}};
  }
  async batch(statements){this.db.exec('BEGIN');try{const results=[];for(const s of statements)results.push(await s.run());this.db.exec('COMMIT');return results}catch(error){this.db.exec('ROLLBACK');throw error}}
}
async function fixture(t,dialect){
  const pg=dialect==='postgres'?new PGlite():null;
  const db=pg?new __postgresCompatTest.PostgresD1Database({async query(input,values){const r=await pg.query(typeof input==='string'?input:input.text,typeof input==='string'?values||[]:input.values||[]);return {...r,rowCount:r.affectedRows??r.rows.length}}}):new SqliteD1();
  const exec=sql=>pg?pg.exec(sql):db.db.exec(sql),env={DB:db};
  t.after(()=>pg?pg.close():db.db.close());
  if(pg)await exec("CREATE FUNCTION sqlite_now() RETURNS text LANGUAGE SQL STABLE AS $$SELECT to_char(timezone('UTC',CURRENT_TIMESTAMP),'YYYY-MM-DD HH24:MI:SS')$$");
  const now=pg?'sqlite_now()':'CURRENT_TIMESTAMP',identity=pg?'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY':'INTEGER PRIMARY KEY';
  await exec(`
    CREATE TABLE app_meta(key TEXT PRIMARY KEY,value TEXT,updated_at TEXT DEFAULT ${now});
    INSERT INTO app_meta(key,value) VALUES('safe_runtime_upgrade_v1985_prime_draw_live','1');
    CREATE TABLE users(id INTEGER PRIMARY KEY,coin BIGINT,role TEXT);
    INSERT INTO users VALUES(7,1234567,'OWNER');
    CREATE TABLE inventory_items(code TEXT PRIMARY KEY,name TEXT NOT NULL,subtitle TEXT,description TEXT,category TEXT,rarity TEXT,image_url TEXT,sort_order INTEGER,is_active INTEGER DEFAULT 1,updated_at TEXT DEFAULT ${now});
    CREATE TABLE cnine_user_inventory(user_id INTEGER,item_code TEXT,quantity INTEGER NOT NULL DEFAULT 0,unseen_quantity INTEGER NOT NULL DEFAULT 0,created_at TEXT DEFAULT ${now},updated_at TEXT DEFAULT ${now},PRIMARY KEY(user_id,item_code));
    INSERT INTO cnine_user_inventory(user_id,item_code,quantity,unseen_quantity) VALUES(7,'${BOX}',12,12),(7,'EQUIPMENT_SUPPLY_BOX',25,25);
    CREATE TABLE character_equipment_items(id INTEGER PRIMARY KEY,code TEXT,name TEXT,rarity TEXT,image_url TEXT,description TEXT,slot TEXT,total_power INTEGER,pve_power INTEGER,pvp_power INTEGER,sort_order INTEGER,is_active INTEGER,is_public INTEGER);
    INSERT INTO character_equipment_items VALUES(1,'EQUIP_1','기본 장비','RARE','','','WEAPON',100,100,100,1,1,1);
    CREATE TABLE character_garage_items(id INTEGER PRIMARY KEY,code TEXT,name TEXT,rarity TEXT,image_url TEXT,description TEXT,total_power INTEGER,pve_power INTEGER,pvp_power INTEGER,sort_order INTEGER,is_active INTEGER,is_public INTEGER);
    INSERT INTO character_garage_items VALUES(1,'VEHICLE_1','기본 차량','RARE','','',100,100,100,1,1,1);
    CREATE TABLE avatar_catalog_v1(code TEXT PRIMARY KEY,name TEXT,lobby_image TEXT,description TEXT,role_label TEXT,accent TEXT,sort_order INTEGER,is_active INTEGER,is_public INTEGER);
    CREATE TABLE avatar_user_ownership_v1(user_id INTEGER,avatar_code TEXT,source_type TEXT,source_ref TEXT,acquired_at TEXT,expires_at TEXT,PRIMARY KEY(user_id,avatar_code));
    CREATE TABLE user_equipment_instances(id ${identity},user_id INTEGER,equipment_id INTEGER,source_type TEXT,source_id TEXT,request_id TEXT UNIQUE);
    CREATE TABLE inventory_logs(id ${identity},user_id INTEGER,item_code TEXT,change_amount INTEGER,balance_after INTEGER,reason TEXT,reference_type TEXT,reference_id TEXT);
  `);
  const api=await import('../functions/_prime_draw.js?prime-chips='+fixtureId++);
  await api.ensurePrimeDrawFoundation(env);
  await exec(`INSERT INTO prime_equipment_draw_pool_v1985(equipment_id,entry_code,source_weight,source_probability,boost_multiplier,draw_weight,pool_version) VALUES(1,'EQUIP_1',100,100,1,100,'PRIME_EQUIPMENT_V1985_1');
    INSERT INTO prime_vehicle_draw_pool_v1985(garage_id,entry_code,source_weight,source_probability,boost_multiplier,draw_weight,pool_version) VALUES(1,'VEHICLE_1',100,100,1,100,'PRIME_VEHICLE_V1985_1');`);
  const q=async(sql,...values)=>(await db.prepare(sql).bind(...values).all()).results;
  const deps={authenticate:async()=>({id:7,role:'OWNER'}),readBody:r=>r.json(),json:(body,status=200)=>({body,status})};
  const call=(path,body,role='OWNER')=>api.handlePrimeDraw({path,env,deps:{...deps,authenticate:async()=>({id:7,role})},request:new Request('https://test.invalid/api/'+path,body===undefined?{}:{method:'POST',body:JSON.stringify(body)})});
  const save=(weights,kind='equipment',role='OWNER')=>call('admin/prime-draw/pool',{kind,entries:[{poolKey:kind==='equipment'?'EQUIPMENT:EQUIP_1':'VEHICLE:VEHICLE_1',drawWeight:100-Object.values(weights).reduce((a,b)=>a+b,0)},...Object.entries(weights).map(([code,drawWeight])=>({poolKey:'INVENTORY_ITEM:'+code,drawWeight}))]},role);
  const open=(requestId,count=1)=>call('equipment/prime-supply-box/open',{requestId,count,poolVersion:'PRIME_EQUIPMENT_V1985_1'});
  const quantity=async(code)=>(await q('SELECT quantity FROM cnine_user_inventory WHERE user_id=7 AND item_code=?',code))[0]?.quantity||0;
  return {api,env,db,pg,exec,q,call,save,open,quantity,deps};
}

for(const dialect of ['sqlite','postgres']){
  test(`${dialect}: CMS exposes the three chip candidates without assigning rewards or changing probabilities`,async t=>{
    const f=await fixture(t,dialect),before=await f.q('SELECT * FROM prime_equipment_draw_pool_v1985');
    const {body,status}=await f.call('admin/prime-draw/status');assert.equal(status,200);
    const chips=body.catalog.inventory_item.filter(row=>row.category==='SKILL_CHIP');
    assert.deepEqual(chips.map(row=>[row.code,row.name,row.rewardType]),[[ROCKET,'로켓런처 스킬칩','INVENTORY_ITEM'],[HELI,'헬기폭격 스킬칩','INVENTORY_ITEM'],[OCTA,'8방향 유도탄 스킬칩','INVENTORY_ITEM']]);
    assert.ok(chips.every(row=>row.image.endsWith('.webp')));
    assert.equal(body.catalog.inventory_item.filter(row=>row.category==='MATERIAL').length,6);
    assert.deepEqual(body.equipment.pool.entries.map(row=>[row.code,row.drawWeight]),[['EQUIP_1',100]]);
    assert.deepEqual(await f.q('SELECT * FROM prime_equipment_draw_pool_v1985'),before);
    assert.deepEqual(await f.q('SELECT * FROM prime_draw_extra_pool_v1987'),[]);
    assert.equal(await f.quantity(ROCKET),0);assert.equal(await f.quantity(HELI),0);assert.equal(await f.quantity(OCTA),0);
    await f.call('admin/prime-draw/status');
    assert.deepEqual(await f.q('SELECT * FROM prime_draw_extra_pool_v1987'),[]);
  });

  test(`${dialect}: manual chip probabilities persist, fresh opens grant stackable chips once and they can be equipped`,async t=>{
    const f=await fixture(t,dialect);
    const saved=await f.save({[ROCKET]:40,[HELI]:60});assert.equal(saved.status,200);
    assert.deepEqual(saved.body.pool.entries.filter(row=>row.category==='SKILL_CHIP').map(row=>[row.code,row.drawWeight]),[[HELI,60],[ROCKET,40]]);
    const publicConfig=await f.call('equipment/prime-supply-box/config');
    assert.equal(publicConfig.body.pool.entries.length,2);
    for(const [index,code] of [ROCKET,HELI].entries()){
      assert.equal((await f.save({[code]:100})).status,200);
      const opened=await f.open('chip-'+code,3);assert.equal(opened.status,200);
      assert.equal(opened.body.remainingQuantity,12-(index+1)*3);
      assert.ok(opened.body.results.every(row=>row.type==='INVENTORY_ITEM'&&row.item.code===code&&row.item.category==='SKILL_CHIP'));
      assert.deepEqual(opened.body.aggregated.map(row=>[row.code,row.count,row.category]),[[code,3,'SKILL_CHIP']]);
      assert.equal(await f.quantity(code),3);
      assert.equal((await f.q('SELECT unseen_quantity FROM cnine_user_inventory WHERE user_id=7 AND item_code=?',code))[0].unseen_quantity,3);
      assert.deepEqual(await f.open('chip-'+code,3),opened,'same receipt must replay without granting twice');
      assert.equal(await f.quantity(code),3);
      const equipped=await handleSkillChips({path:'character/skill-chips/equip',env:f.env,deps:f.deps,request:new Request('https://test.invalid/equip',{method:'POST',body:JSON.stringify({slot:index+1,code})})});
      assert.equal(equipped.status,200);assert.equal(equipped.body.skillChips.loadout[index],code);assert.equal(await f.quantity(code),3);
    }
    assert.equal((await f.open('stack-chip',2)).status,200);assert.equal(await f.quantity(HELI),5);
    assert.equal(await f.quantity(BOX),4);assert.equal(await f.quantity('EQUIPMENT_SUPPLY_BOX'),25);
    assert.deepEqual(await f.q('SELECT * FROM user_equipment_instances'),[]);
    assert.deepEqual(await f.q('SELECT * FROM avatar_user_ownership_v1'),[]);
    assert.equal((await f.q("SELECT COUNT(*) n FROM inventory_logs WHERE reason='PRIME_EQUIPMENT_REWARD'"))[0].n,3);
    assert.equal((await f.q('SELECT coin FROM users WHERE id=7'))[0].coin,1234567);
    assert.equal((await f.open('too-many',5)).status,409);assert.equal(await f.quantity(BOX),4);
  });

  test(`${dialect}: inactive, unapproved and vehicle chip assignments are rejected without mutating the pool`,async t=>{
    const f=await fixture(t,dialect);
    const before=await f.q('SELECT * FROM prime_equipment_draw_pool_v1985');
    assert.equal((await f.save({[ROCKET]:10},'equipment','USER')).status,403);
    assert.equal((await f.save({[ROCKET]:10},'vehicle')).status,409);
    await f.exec("INSERT INTO inventory_items(code,name,category) VALUES('UNAPPROVED_CHIP','unapproved','SKILL_CHIP')");
    assert.equal((await f.save({UNAPPROVED_CHIP:10})).status,409);
    await f.db.prepare('UPDATE inventory_items SET is_active=0 WHERE code=?').bind(ROCKET).run();
    assert.equal((await f.save({[ROCKET]:10})).status,409);
    assert.deepEqual(await f.q('SELECT * FROM prime_equipment_draw_pool_v1985'),before);
    assert.deepEqual(await f.q('SELECT * FROM prime_draw_extra_pool_v1987'),[]);
    const status=await f.call('admin/prime-draw/status');
    assert.deepEqual(status.body.catalog.inventory_item.filter(row=>row.category==='SKILL_CHIP').map(row=>row.code),[HELI,OCTA]);
    assert.equal((await f.save({[HELI]:100})).status,200);
    await f.db.prepare('UPDATE inventory_items SET is_active=0 WHERE code=?').bind(HELI).run();
    assert.equal((await f.open('inactive-chip')).status,503);assert.equal(await f.quantity(BOX),12);
  });

  test(`${dialect}: a suppressed box debit cannot grant free chips or complete a receipt`,async t=>{
    const f=await fixture(t,dialect);await f.save({[HELI]:100});
    if(f.pg)await f.exec(`CREATE FUNCTION suppress_box_debit() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.item_code='${BOX}' THEN RETURN NULL; END IF; RETURN NEW; END $$;
      CREATE TRIGGER suppress_box_debit BEFORE UPDATE ON cnine_user_inventory FOR EACH ROW EXECUTE FUNCTION suppress_box_debit();`);
    else await f.exec(`CREATE TRIGGER suppress_box_debit BEFORE UPDATE ON cnine_user_inventory WHEN NEW.item_code='${BOX}' BEGIN SELECT RAISE(IGNORE); END;`);
    await assert.rejects(()=>f.open('box-debit-failed',2),/not.null|null value/i);
    assert.equal(await f.quantity(BOX),12);assert.equal(await f.quantity(HELI),0);
    assert.deepEqual(await f.q('SELECT * FROM inventory_logs'),[]);
    assert.deepEqual(await f.q('SELECT * FROM prime_draw_open_receipts_v1985'),[]);
  });

  for(const event of ['INSERT','UPDATE'])test(`${dialect}: a zero-row chip ${event} rolls back box debit, reward logs and receipt`,async t=>{
    const f=await fixture(t,dialect);
    await f.save({[ROCKET]:100});
    if(event==='UPDATE')await f.exec(`INSERT INTO cnine_user_inventory(user_id,item_code,quantity,unseen_quantity) VALUES(7,'${ROCKET}',5,2)`);
    const before=await f.q('SELECT * FROM cnine_user_inventory ORDER BY item_code');
    if(f.pg)await f.exec(`CREATE FUNCTION suppress_chip() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.item_code='${ROCKET}' THEN RETURN NULL; END IF; RETURN NEW; END $$;
      CREATE TRIGGER suppress_chip BEFORE ${event} ON cnine_user_inventory FOR EACH ROW EXECUTE FUNCTION suppress_chip();`);
    else await f.exec(`CREATE TRIGGER suppress_chip BEFORE ${event} ON cnine_user_inventory WHEN NEW.item_code='${ROCKET}' BEGIN SELECT RAISE(IGNORE); END;`);
    await assert.rejects(()=>f.open('suppressed-chip',2),/not.null|null value/i);
    assert.deepEqual(await f.q('SELECT * FROM cnine_user_inventory ORDER BY item_code'),before);
    assert.deepEqual(await f.q('SELECT * FROM inventory_logs'),[]);
    assert.deepEqual(await f.q('SELECT * FROM prime_draw_open_receipts_v1985'),[]);
    await f.exec(f.pg?'DROP TRIGGER suppress_chip ON cnine_user_inventory':'DROP TRIGGER suppress_chip');
    assert.equal((await f.open('suppressed-chip',2)).status,200);
    assert.equal(await f.quantity(ROCKET),event==='UPDATE'?7:2);
    assert.equal(await f.quantity(BOX),10);
  });
}
