import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,stat} from 'node:fs/promises';
import {PRISON_HIT_COOLDOWN_SECONDS,PRISON_RELEASE_PRICE_MAX,prisonHitCooldownRemaining,prisonReleaseProgress} from '../functions/_prison_community.js';

const [server,communityServer,client,menu,cms,css,index,packageRaw]=await Promise.all([
  readFile(new URL('../functions/api/[[path]].js',import.meta.url),'utf8'),
  readFile(new URL('../functions/_prison_community.js',import.meta.url),'utf8'),
  readFile(new URL('../js/app.js',import.meta.url),'utf8'),
  readFile(new URL('../js/soopketmon-v21-exact-shell-adapter.js',import.meta.url),'utf8'),
  readFile(new URL('../admin/admin-v1276.js',import.meta.url),'utf8'),
  readFile(new URL('../css/prison-v1950.css',import.meta.url),'utf8'),
  readFile(new URL('../index.html',import.meta.url),'utf8'),
  readFile(new URL('../package.json',import.meta.url),'utf8')
]);
const packageJson=JSON.parse(packageRaw);

test('감옥 foundation과 10분~6시간 서버 검증을 고정한다',()=>{
  assert.match(server,/CREATE TABLE IF NOT EXISTS user_prison_status/);
  assert.match(server,/CREATE TABLE IF NOT EXISTS prison_chat_messages/);
  assert.match(server,/const postgres=env\.DB\?\.dialect==='postgres'/);
  assert.match(server,/BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY/);
  assert.match(server,/typeof env\.DB\.execSchema==='function'\)await env\.DB\.execSchema\(schema\)/);
  assert.match(server,/to_char\(timezone\('UTC',CURRENT_TIMESTAMP\),'YYYY-MM-DD HH24:MI:SS'\)/);
  assert.match(server,/if\(path==='health'\)[\s\S]*await ensurePrisonFoundation\(env\)[\s\S]*prisonSchema:true/);
  assert.match(server,/durationMinutes<10\|\|durationMinutes>360/);
  assert.match(server,/jailed_until>CURRENT_TIMESTAMP/);
  assert.match(server,/release_reason=CASE WHEN release_reason='' THEN '형기 만료'/);
  assert.match(server,/command_type,payload_json,created_by,expires_at\)\s*VALUES\(\?,'PRISON_LOCK'/);
  assert.match(server,/VALUES\(\?,'PRISON_RELEASE'/);
});

test('수감자는 모든 하위 콘텐츠 라우터보다 먼저 423으로 차단된다',()=>{
  const gate=server.indexOf("code:'USER_INCARCERATED'");
  const firstSubsystem=server.indexOf('const evolutionResponse=await handleEvolution');
  assert.ok(gate>0&&firstSubsystem>gate,'수감 게이트가 하위 콘텐츠 라우터보다 먼저 실행되어야 한다');
  assert.match(server,/const prisonExempt=.*path\.startsWith\('admin\/'\)/s);
  for(const route of ["path==='auth/logout'","path==='me/summary'","path==='user/runtime-command'","path==='prison/status'","path==='prison/chat'"])assert.match(server,new RegExp(route.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));
  assert.match(server,/return json\(\{error:'수감 중에는 감옥을 벗어날 수 없습니다\.',code:'USER_INCARCERATED',prison\},423\)/);
});

test('수감자는 전체 프로필 조회 없이 로그인 성공 후 즉시 감옥으로 진입한다',()=>{
  assert.match(server,/function prisonLoginProfile\(user\)/);
  assert.match(server,/const prison=await prisonStatusForUser\(env,user\.id\);\s*const loginUser=prison\.incarcerated\?prisonLoginProfile\(user\):await profile\(env,user\)/);
  assert.match(server,/user:loginUser,prison/);
  assert.match(client,/applyPrisonStatus\(d\.prison\|\|\{incarcerated:false\}\);if\(isPrisonLocked\(\)\)return renderLockedPrison\(\)/);
});

test('처리 완료된 수감·석방 명령은 다시 내려주지 않는다',()=>{
  assert.match(server,/FROM \(\s*SELECT id,command_type,payload_json,created_at,expires_at,acknowledged_at FROM user_runtime_commands\s*WHERE user_id=\? AND expires_at>datetime\('now'\) ORDER BY id DESC LIMIT 1\s*\) latest WHERE acknowledged_at IS NULL/);
  assert.match(server,/UPDATE user_runtime_commands SET acknowledged_at=COALESCE\(acknowledged_at,CURRENT_TIMESTAMP\)/);
  assert.match(client,/commandType==='PRISON_RELEASE'/);
});

test('감옥 공개 채팅은 인증·길이·속도 제한과 역할 표식을 가진다',()=>{
  assert.match(server,/path==='prison\/chat'/);
  assert.match(server,/Array\.from\(body\)\.length>200/);
  assert.match(server,/created_at>datetime\('now','-2 seconds'\)/);
  assert.match(server,/sender_was_incarcerated/);
  assert.match(server,/DELETE FROM prison_chat_messages WHERE NOT EXISTS/);
  assert.match(server,/code:'PRISON_CHAT_CLOSED'/);
  assert.match(server,/SELECT \?,\?,\? WHERE EXISTS\(SELECT 1 FROM user_prison_status WHERE active=1 AND jailed_until>CURRENT_TIMESTAMP\)/);
  assert.match(server,/chatEnabled:inmates\.length>0/);
  assert.match(client,/PUBLIC CELL CHAT/);
  assert.match(client,/수감자·방문객 공용/);
  assert.match(client,/escapeHtml\(message\.body/);
  assert.match(client,/syncPrisonDom\(\{forceChatBottom:true\}\)/);
  assert.match(client,/function prisonChatEnabled\(\)/);
  assert.match(client,/수감자가 있을 때만 채팅할 수 있습니다/);
  assert.match(css,/\.prison-side\{[^}]*height:710px;max-height:710px;overflow:hidden/);
  assert.match(css,/\.prison-chat-log\{[^}]*overflow-y:auto;overscroll-behavior:contain/);
  assert.match(css,/@media\(max-width:720px\)[\s\S]*\.prison-side,\.prison-lock-shell \.prison-side\{[^}]*grid-template-rows:auto auto 430px/);
});

test('영치금 석방은 OWNER 설정·원자 납부·모금 완료 석방을 고정한다',()=>{
  assert.equal(PRISON_RELEASE_PRICE_MAX,1_000_000_000_000);
  assert.deepEqual(prisonReleaseProgress(25,100),{collectedCoin:25,releasePrice:100,remainingCoin:75,progressPercent:25,funded:false});
  assert.equal(prisonReleaseProgress(100,100).funded,true);
  assert.match(communityServer,/const CASE_TABLE='prison_release_cases_v2031'/);
  assert.match(communityServer,/const CONTRIBUTION_TABLE='prison_release_contributions_v2031'/);
  assert.match(communityServer,/CREATE TABLE IF NOT EXISTS \$\{CASE_TABLE\}/);
  assert.match(communityServer,/CREATE TABLE IF NOT EXISTS \$\{CONTRIBUTION_TABLE\}/);
  assert.match(communityServer,/석방금은 OWNER만 설정할 수 있습니다/);
  assert.match(communityServer,/releasePrice<0\|\|releasePrice>PRISON_RELEASE_PRICE_MAX/);
  assert.match(communityServer,/INSERT OR IGNORE INTO \$\{CONTRIBUTION_TABLE\}/);
  assert.match(communityServer,/UPDATE users SET coin=\? WHERE id=\? AND coin=\?/);
  assert.match(communityServer,/last_request_id=\?/);
  assert.match(communityServer,/status='FUNDED_RELEASED'/);
  assert.match(communityServer,/command_type,payload_json,created_by,expires_at\)\s*SELECT \?,'PRISON_RELEASE'/);
  assert.match(server,/STRICT_MUTATION_LOCK_ACTIONS=new Set\(\[[^\]]*'prison\/fund'/);
  assert.match(server,/openPrisonReleaseCaseStatement\(env,\{inmateUserId:userId\}\)/);
  assert.match(server,/closePrisonReleaseCaseStatement\(env,\{inmateUserId:userId,status:'ADMIN_RELEASED'\}\)/);
});

test('수감자 때리기는 60초 서버 쿨타임·중복 영수증·자기 공격 차단을 가진다',()=>{
  assert.equal(PRISON_HIT_COOLDOWN_SECONDS,60);
  assert.equal(prisonHitCooldownRemaining(61_000,1_000),60);
  assert.equal(prisonHitCooldownRemaining(1_000,61_000),0);
  assert.match(communityServer,/const HIT_COOLDOWN_TABLE='prison_hit_cooldowns_v2031'/);
  assert.match(communityServer,/const HIT_EVENT_TABLE='prison_hit_events_v2031'/);
  assert.match(communityServer,/CREATE TABLE IF NOT EXISTS \$\{HIT_COOLDOWN_TABLE\}/);
  assert.match(communityServer,/CREATE TABLE IF NOT EXISTS \$\{HIT_EVENT_TABLE\}/);
  assert.match(communityServer,/자기 자신은 때릴 수 없습니다/);
  assert.match(communityServer,/nextAtMs=now\+PRISON_HIT_COOLDOWN_SECONDS\*1000/);
  assert.match(communityServer,/ON CONFLICT\(hitter_user_id,inmate_user_id\) DO UPDATE/);
  assert.match(communityServer,/last_request_id=excluded\.last_request_id/);
  assert.match(communityServer,/next_at_ms<=\?/);
  assert.match(communityServer,/SELECT \* FROM \$\{HIT_EVENT_TABLE\} WHERE request_id=\?/);
});

test('전체 메뉴 맨 아래에 행정부·감옥이 연결된다',()=>{
  assert.match(menu,/administration: Object\.freeze\(\{ title: '행정부', routes: Object\.freeze\(\['treasury', 'prison'\]\) \}\)/);
  assert.match(menu,/MENU_GROUP_ORDER = Object\.freeze\(\[[^\]]*'market', 'administration'\]\)/);
  assert.match(menu,/prison: Object\.freeze\(\{ title: '감옥', group: 'administration', icon: 'prison' \}\)/);
  assert.match(client,/prison: prisonView/);
});

test('잠금 화면은 계정명·평상·피격 죄수 캐릭터·창살·남은 형기와 전용 배경을 렌더링한다',async()=>{
  assert.match(client,/id="prisonSceneName"/);
  assert.match(client,/prisoner-cartoon-servile-v1\.png/);
  assert.match(client,/prisoner-cartoon-hit-v2031\.png/);
  assert.match(client,/data-prison-fund/);
  assert.match(client,/data-prison-price/);
  assert.match(client,/data-prison-hit/);
  assert.match(client,/function playPrisonHitEffect/);
  assert.match(client,/focusedState=focused\?/,'5초 상태 갱신이 입력 중인 영치금·석방금을 지우면 안 된다');
  assert.match(client,/function prisonBarsMarkup/);
  assert.match(client,/id="prisonCountdown"/);
  assert.match(client,/function renderLockedPrison/);
  assert.match(css,/prison-cell-background-v1\.png/);
  assert.match(css,/\.prison-bars i/);
  assert.match(index,/css\/prison-v1950\.css\?v=2031-prison-community/);
  const [background,character,hitCharacter,hitPng]=await Promise.all([
    stat(new URL('../assets/ui/prison/prison-cell-background-v1.png',import.meta.url)),
    stat(new URL('../assets/ui/prison/prisoner-cartoon-servile-v1.png',import.meta.url)),
    stat(new URL('../assets/ui/prison/prisoner-cartoon-hit-v2031.png',import.meta.url)),
    readFile(new URL('../assets/ui/prison/prisoner-cartoon-hit-v2031.png',import.meta.url))
  ]);
  assert.ok(background.size>100_000);
  assert.ok(character.size>100_000);
  assert.ok(hitCharacter.size>100_000);
  assert.equal(hitPng.subarray(1,4).toString(),'PNG');
  assert.equal(hitPng.readUInt32BE(16),1024);
  assert.equal(hitPng.readUInt32BE(20),1536);
  assert.equal(hitPng[25],6,'피격 스프라이트는 RGBA 투명 PNG여야 한다');
});

test('수감 계정 콜드 스타트는 V21 부트 로딩을 즉시 해제한다',()=>{
  const start=client.indexOf('function renderLockedPrison');
  const end=client.indexOf('window.PrisonV1',start);
  const lockedRender=client.slice(start,end);
  assert.ok(start>0&&end>start,'감옥 잠금 렌더러를 찾을 수 있어야 한다');
  assert.match(lockedRender,/document\.body\.classList\.add\('prison-locked','v21-ui-ready'\)/);
  assert.match(lockedRender,/document\.documentElement\.dataset\.v21UiReady='1'/);
  assert.match(index,/body\.v21-renewal-required #app\{visibility:hidden\}/);
  assert.match(index,/body\.v21-ui-ready \.v21-renewal-boot\{display:none\}/);
  assert.match(index,/js\/app\.js\?v=2031-prison-community/);
});

test('CMS는 현재 수감 상태와 10분~6시간 입력, 즉시 석방을 제공한다',()=>{
  assert.match(cms,/id="prisonDuration"/);
  assert.match(cms,/id="prisonDuration" type="number" min="10" max="360" step="1" value="60"/);
  assert.match(cms,/prisonUserAction\('PRISON'\)/);
  assert.match(cms,/prisonUserAction\('PRISON_RELEASE'\)/);
  assert.match(cms,/PVE·PVP·영토전 등 모든 콘텐츠/);
  assert.match(cms,/prison_jailed_until/);
});

test('감옥 회귀 검사가 운영 출시 게이트에 포함된다',()=>{
  assert.match(packageJson.scripts['test:prison']||'',/prison-system-v1950\.test\.mjs/);
  assert.match(packageJson.scripts['release:gate']||'',/npm run test:prison/);
});
