import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import vm from 'node:vm';
import { deathGameFixture } from './helpers/prison-death-game-fixture.mjs';
import { adminCampState, operateAdminCamp, handlePrisonCampAdmin } from '../functions/_prison_camp_admin.js';
import { clanCampStatusForUser, clanCampRoomState } from '../functions/_clan_prison_camp.js';

const owner = { id: 999, role: 'OWNER' };
const request = (extra = {}) => ({ userId: 101, expectedNickname: '참가자 하나', action: 'JAIL', durationMinutes: 120, reason: '검수 전용', requestId: crypto.randomUUID(), ...extra });
async function fixture(t, pg) {
  const f = await deathGameFixture(pg); t.after(() => f.close());
  const schema = ["ALTER TABLE users ADD COLUMN status TEXT DEFAULT 'ACTIVE'",
    `CREATE TABLE admin_logs(id ${pg ? 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY' : 'INTEGER PRIMARY KEY AUTOINCREMENT'},admin_id INTEGER,action_type TEXT,target_type TEXT,target_id TEXT,before_data TEXT,after_data TEXT)`];
  if (pg) await f.env.DB.execSchema(schema);
  else for (const statement of schema) await f.p(statement).run();
  return f;
}
const count = async (f, table) => Number((await f.p(`SELECT COUNT(*) n FROM ${table}`).first()).n);

for (const pg of [false, true]) {
  const label = pg ? 'PostgreSQL' : 'SQLite';
  test(`${label}: 120-minute camp sentence reaches existing game gate/room without touching wallet or disciplinary prison`, async t => {
    const f = await fixture(t, pg), body = request(), result = await operateAdminCamp(f.env, owner, body, f.now);
    assert.equal(result.ok, true); assert.equal(result.state.camps[0].canRelease, true);
    const camp = await clanCampStatusForUser(f.env, 101, f.now);
    assert.equal(camp.facility, 'CLAN_CAMP'); assert.equal(camp.sourceType, 'ADMIN');
    assert.equal(Date.parse(camp.jailedUntil.replace(' ', 'T') + 'Z') - Date.parse(camp.jailedAt.replace(' ', 'T') + 'Z'), 7200000);
    const room = await clanCampRoomState(f.env, { id: 101 }, camp, f.now);
    assert.equal(room.inmates[0].userId, 101); assert.equal(room.sentenceHours, 2);
    assert.equal(Number((await f.p('SELECT coin FROM users WHERE id=101').first()).coin), 123456);
    assert.equal(await count(f, 'user_prison_status'), 0); assert.equal(await count(f, 'admin_logs'), 1);
    assert.equal((await clanCampStatusForUser(f.env, 101, f.now + 7200000)).incarcerated, false);
    assert.equal((await adminCampState(f.env, owner, 101, f.now + 7200000)).camps.length, 0);
  });
  test(`${label}: OWNER, exact target, duration, reason and active-sentence guards`, async t => {
    const f = await fixture(t, pg);
    for (const role of ['USER', 'ADMIN', 'SUPPORT', 'CARD_MANAGER']) await assert.rejects(operateAdminCamp(f.env, { id: 102, role }, request(), f.now), { status: 403 });
    for (const durationMinutes of [0, -1, 1.1, 10081, Infinity, 'no']) await assert.rejects(operateAdminCamp(f.env, owner, request({ durationMinutes }), f.now), { status: 400 });
    await assert.rejects(operateAdminCamp(f.env, owner, request({ reason: ' ' }), f.now), { status: 400 });
    await assert.rejects(operateAdminCamp(f.env, owner, request({ expectedNickname: '다른 사람' }), f.now), { status: 409 });
    await f.p("UPDATE users SET status='BANNED' WHERE id=101").run();
    await assert.rejects(operateAdminCamp(f.env, owner, request(), f.now), { status: 409 });
    await f.p("UPDATE users SET status='ACTIVE' WHERE id=101").run();
    await f.p("INSERT INTO user_prison_status(user_id,active,jailed_until) VALUES(101,1,'9999-01-01 00:00:00')").run();
    await assert.rejects(operateAdminCamp(f.env, owner, request(), f.now), { status: 409 });
    assert.equal(await count(f, 'event_prison_camps'), 0); assert.equal(await count(f, 'admin_logs'), 0);
  });
  test(`${label}: repeated/concurrent requests and lost COMMIT response cannot extend or duplicate detention`, async t => {
    const f = await fixture(t, pg), body = request();
    const outcomes = await Promise.all([operateAdminCamp(f.env, owner, body, f.now), operateAdminCamp(f.env, owner, body, f.now)]);
    assert.equal(outcomes.filter(r => r.replayed).length, 1);
    const replay = await operateAdminCamp(f.env, owner, body, f.now + 60000);
    assert.equal(replay.result.jailedUntil, outcomes[0].result.jailedUntil);
    await assert.rejects(operateAdminCamp(f.env, owner, { ...body, durationMinutes: 60 }, f.now), { status: 409 });
    await assert.rejects(operateAdminCamp(f.env, owner, request(), f.now), { status: 409 });
    assert.equal(await count(f, 'admin_logs'), 1);
    const other = request({ userId: 102, expectedNickname: '참가자 둘' });
    f.loseCommit(); await assert.rejects(operateAdminCamp(f.env, owner, other, f.now), /LOST_COMMIT_RESPONSE/);
    assert.equal((await operateAdminCamp(f.env, owner, other, f.now + 5000)).replayed, true);
    assert.equal(await count(f, 'event_prison_camps'), 2); assert.equal(await count(f, 'admin_logs'), 2);
  });
  test(`${label}: audit failure rolls back receipt/sentence; manual release preserves death and clan/coup restrictions`, async t => {
    const f = await fixture(t, pg), body = request();
    f.fail('INSERT INTO admin_logs'); await assert.rejects(operateAdminCamp(f.env, owner, body, f.now), /INJECTED_FAILURE/);
    assert.equal(await count(f, 'event_prison_camps'), 0); assert.equal(await count(f, 'event_prison_captives'), 0);
    assert.equal(await f.p('SELECT value FROM app_meta WHERE key=?', `prison_camp_admin:v1:${body.requestId}`).first(), null);
    f.fail(''); const jailed = await operateAdminCamp(f.env, owner, body, f.now);
    for (const source of ['DEATH_GAME', 'COUP']) {
      await f.p("INSERT INTO event_prison_camps VALUES(?,?,?,'기존 제한','2026-01-01 00:00:00','9999-01-01 00:00:00')", source, source, source).run();
      await f.p("INSERT INTO event_prison_captives(event_id,user_id,member_role) VALUES(?,101,'MEMBER')", source).run();
    }
    const release = request({ action: 'RELEASE', eventId: jailed.result.eventId, reason: 'CMS 수동 석방' });
    f.fail('INSERT INTO admin_logs'); await assert.rejects(operateAdminCamp(f.env, owner, release, f.now), /INJECTED_FAILURE/);
    assert.equal((await f.p('SELECT released_at FROM event_prison_captives WHERE event_id=?', jailed.result.eventId).first()).released_at, null);
    f.fail(''); f.loseCommit(); await assert.rejects(operateAdminCamp(f.env, owner, release, f.now), /LOST_COMMIT_RESPONSE/);
    const done = await operateAdminCamp(f.env, owner, release, f.now);
    assert.equal(done.replayed, true); assert.equal(done.state.camps.length, 2);
    assert.ok(done.state.camps.every(c => !c.canRelease));
    assert.equal((await clanCampStatusForUser(f.env, 101, f.now)).facility, 'DEATH_GAME');
    assert.equal(await count(f, 'admin_logs'), 2);
    // Replaying the original jail after release must not imprison them again.
    assert.equal((await operateAdminCamp(f.env, owner, body, f.now)).state.camps.length, 2);
    await assert.rejects(operateAdminCamp(f.env, owner, request({ action: 'RELEASE', eventId: 'DEATH_GAME' }), f.now), { status: 400 });
  });
}

test('CMS route enforces existing USER_MANAGE + OWNER checks and never accepts a GET mutation', async t => {
  const f = await fixture(t, false);
  let actor = owner;
  const deps = { requirePermission: async (_r, _e, permission) => { assert.equal(permission, 'USER_MANAGE'); return actor; }, json: (body, status = 200) => Response.json(body, { status }), readBody: request => request.json() };
  const call = (path, options) => handlePrisonCampAdmin({ path, request: new Request(`https://example.test/api/${path}?userId=101`, options), env: f.env, deps });
  assert.equal((await call('admin/prison-camp/status')).status, 200);
  assert.equal((await call('admin/prison-camp/action')).status, 405);
  actor = { id: 102, role: 'SUPPORT' };
  assert.equal((await call('admin/prison-camp/status')).status, 403);
  assert.equal((await call('admin/prison-camp/action', { method: 'POST', body: JSON.stringify(request()) })).status, 403);
  assert.equal(await count(f, 'event_prison_camps'), 0);
});

test('production CMS wires the addon after core, scripts parse, and game status/room polling remains connected', () => {
  const read = path => readFileSync(new URL('../' + path, import.meta.url), 'utf8');
  const html = read('admin/index.html'), js = read('admin/prison-camp-admin-20260924.js');
  assert.ok(html.indexOf('prison-camp-admin-20260924.js?v=1') > html.indexOf('admin-v1276.js'));
  assert.ok(html.includes('prison-camp-admin-20260924.css?v=1'));
  new vm.Script(js);
  assert.match(js, /state\.role !== 'OWNER'/); assert.match(js, /crypto\.randomUUID/);
  assert.match(js, /selected !== userId/); assert.match(js, /cnine_camp_admin_pending/);
  const api = read('functions/api/[[path]].js');
  assert.match(api, /handlePrisonCampAdmin\(\{path,request,env,deps:\{requirePermission,readBody,json\}\}\)/);
  assert.match(api, /clanCampStatusForUser\(env,userId\)/);
  assert.match(read('js/app.js'), /if\(data\?\.prison\)applyPrisonStatus\(data\.prison\)/);
  assert.match(read('js/clan-prison-camp-v2083.js'), /!next\.prison\?\.incarcerated/);
});
