import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import {PGlite} from '@electric-sql/pglite';
import {__postgresCompatTest} from '../functions/_postgres_d1_compat.js';
import {handlePrisonCommunity,ensurePrisonCommunityFoundation,PRISON_RELEASE_PRICE_MAX} from '../functions/_prison_community.js';

const MAX=5_000_000_000_000;

test('PostgreSQL: 영치금 본인 차단·5조 한도·원자 납부·재시도',async t=>{
  const sql=new PGlite();t.after(()=>sql.close());
  await sql.exec(`
    CREATE FUNCTION sqlite_now() RETURNS TEXT LANGUAGE SQL STABLE AS $$ SELECT to_char(timezone('UTC',CURRENT_TIMESTAMP),'YYYY-MM-DD HH24:MI:SS') $$;
    CREATE FUNCTION sqlite_datetime(VARIADIC parts text[]) RETURNS TEXT LANGUAGE SQL STABLE AS $$ SELECT to_char(timezone('UTC',CURRENT_TIMESTAMP)+COALESCE(parts[2]::interval,interval '0 seconds'),'YYYY-MM-DD HH24:MI:SS') $$;
    CREATE TABLE users(id BIGINT PRIMARY KEY,nickname TEXT,role TEXT,coin BIGINT);
    CREATE TABLE user_prison_status(user_id BIGINT PRIMARY KEY,active INTEGER,jailed_until TEXT,released_by BIGINT,released_at TEXT,release_reason TEXT,updated_at TEXT);
    CREATE TABLE user_runtime_commands(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id BIGINT,command_type TEXT,payload_json TEXT,created_by BIGINT,expires_at TEXT);
    CREATE TABLE coin_logs(user_id BIGINT,change_amount BIGINT,balance_after BIGINT,reason TEXT);
  `);
  let failAt='';
  const DB=new __postgresCompatTest.PostgresD1Database({async query(input){
    const source=typeof input==='string'?input:input.text;
    if(failAt&&source.includes(failAt))throw new Error('INJECTED_FAILURE');
    const result=await sql.query(source,typeof input==='string'?[]:input.values||[]);
    return {...result,rowCount:result.affectedRows??result.rows.length};
  }});
  const env={DB};await ensurePrisonCommunityFoundation(env);
  const read=async query=>(await sql.query(query)).rows;
  const seed=async()=>{
    failAt='';
    await sql.exec(`TRUNCATE users,user_prison_status,user_runtime_commands,coin_logs,prison_release_cases_v2031,prison_release_contributions_v2031;
      INSERT INTO users VALUES(1,'수감자','USER',6000000000000),(2,'다른 수감자','USER',6000000000000),(3,'방문객','USER',6000000000000),(9,'운영자','OWNER',0);
      INSERT INTO user_prison_status(user_id,active,jailed_until) VALUES(1,1,'2099-01-01 00:00:00'),(2,1,'2099-01-01 00:00:00');
      INSERT INTO prison_release_cases_v2031(inmate_user_id,case_id,release_price) VALUES(1,'case-one',${MAX}),(2,'case-two',${MAX});`);
  };
  const request=async(id,body,path='prison/fund',role='USER')=>handlePrisonCommunity({path,request:{method:'POST'},env,deps:{
    authenticate:async()=>({id,nickname:'유저'+id,role}),readBody:async()=>body,json:(data,status=200)=>({data,status}),
    prisonRoomState:async()=>({}),clearPrisonChatIfEmpty:async()=>{}
  }});
  const fund=(id,amount,requestId)=>request(id,{inmateUserId:1,amount,requestId});
  const snapshot=async()=>({users:await read('SELECT * FROM users ORDER BY id'),cases:await read('SELECT * FROM prison_release_cases_v2031 ORDER BY inmate_user_id'),
    receipts:await read('SELECT * FROM prison_release_contributions_v2031'),logs:await read('SELECT * FROM coin_logs')});

  await t.test('본인 납부는 USER·OWNER와 문자열 ID 모두 차감 전 403',async()=>{
    await seed();const before=await snapshot();
    for(const role of ['USER','OWNER']){
      const result=await request('1',{inmateUserId:'1',amount:MAX,requestId:'self-fund-'+role},'prison/fund',role);
      assert.equal(result.status,403);assert.match(result.data.error,/본인의 영치금/);
    }
    assert.deepEqual(await snapshot(),before);
  });
  await t.test('OWNER만 0~5조 설정 가능, 초과·소수·음수는 저장하지 않는다',async()=>{
    await seed();assert.equal(PRISON_RELEASE_PRICE_MAX,MAX);
    const set=(releasePrice,role='OWNER')=>request(9,{inmateUserId:1,releasePrice},'prison/release-price',role);
    assert.equal((await set(MAX)).status,200);
    for(const value of [MAX+1,-1,0.5,Number.MAX_SAFE_INTEGER+1])assert.equal((await set(value)).status,400);
    assert.equal((await set(1,'USER')).status,403);
    assert.equal(Number((await read('SELECT release_price FROM prison_release_cases_v2031 WHERE inmate_user_id=1'))[0].release_price),MAX);
    assert.equal((await set(0)).status,200);
  });
  await t.test('방문객 4조+1조 납부·석방·재시도는 정확히 한 번 반영된다',async()=>{
    await seed();
    assert.equal((await fund(3,4e12,'visitor-first')).status,200);
    assert.equal((await fund(3,4e12,'visitor-first')).data.replayed,true);
    assert.equal((await fund(3,1,'visitor-first')).status,409);
    assert.equal((await fund(3,1e12,'visitor-last')).data.released,true);
    assert.equal((await fund(3,1e12,'visitor-last')).data.replayed,true);
    assert.equal(Number((await read('SELECT coin FROM users WHERE id=3'))[0].coin),1e12);
    const saved=(await read('SELECT * FROM prison_release_cases_v2031 WHERE inmate_user_id=1'))[0];
    assert.equal(Number(saved.collected_coin),MAX);assert.equal(Number(saved.contribution_count),2);assert.equal(saved.status,'FUNDED_RELEASED');
    assert.equal(Number((await read('SELECT active FROM user_prison_status WHERE user_id=1'))[0].active),0);
    assert.equal((await read('SELECT * FROM user_runtime_commands')).length,1);
    assert.equal((await read('SELECT * FROM coin_logs')).length,2);
  });
  await t.test('다른 수감자에게는 기존대로 모금할 수 있다',async()=>{
    await seed();assert.equal((await fund(2,MAX,'other-inmate')).status,200);
    assert.equal(Number((await read('SELECT coin FROM users WHERE id=2'))[0].coin),1e12);
  });
  await t.test('5조 거래 중 오류는 잔액·모금·영수증을 함께 복구하고 같은 번호로 재시도 가능',async()=>{
    await seed();const before=await snapshot();failAt='INSERT INTO coin_logs';
    assert.equal((await fund(3,MAX,'rollback-fund')).status,500);failAt='';
    assert.deepEqual(await snapshot(),before);
    assert.equal((await fund(3,MAX,'rollback-fund')).status,200);
    assert.equal((await fund(3,MAX,'rollback-fund')).data.replayed,true);
    assert.equal((await read('SELECT * FROM coin_logs')).length,1);
  });
  await t.test('남은 모금액 초과 및 잔액 부족은 무차감',async()=>{
    await seed();let before=await snapshot();
    assert.equal((await fund(3,MAX+1,'too-much-fund')).status,400);assert.deepEqual(await snapshot(),before);
    await sql.exec('UPDATE users SET coin=1 WHERE id=3');before=await snapshot();
    assert.equal((await fund(3,MAX,'not-enough-fund')).status,409);assert.deepEqual(await snapshot(),before);
  });
});

const source=readFileSync(new URL('../js/app.js',import.meta.url),'utf8');
function clientFixture(){
  const alerts=[],requests=[],input={value:String(MAX)};
  const context=vm.createContext({window:{},loadUser:()=>({serverUserId:1,coin:MAX}),escapeHtml:value=>String(value),
    document:{getElementById:()=>input},alert:message=>alerts.push(message),confirm:()=>false,apiRequest:(...args)=>requests.push(args)});
  vm.runInContext(source.slice(source.indexOf('const PRISON_DEFAULT_HIT_COOLDOWN_SECONDS'),source.indexOf('window.PrisonV1=')),context);
  vm.runInContext('globalThis.state=prisonUiState',context);
  Object.assign(context.state,{viewer:{id:1,coin:MAX},selectedInmateId:1,inmates:[{userId:1,nickname:'수감자',releasePrice:MAX,collectedCoin:1e12,remainingCoin:4e12,progressPercent:20}]});
  return {context,alerts,requests};
}
test('금액 표시는 만·억·조 단위이며 단위 경계에서 반올림으로 늘리지 않는다',()=>{
  const {context}=clientFixture();
  for(const [value,label] of [[0,'0'],[9999,'9,999'],[10000,'1만'],[1e10,'100억'],[1e12,'1조'],[MAX,'5조'],[1.2345e12,'1.23조'],[1e12-1,'9,999.99억']])assert.equal(context.prisonCoin(value),label);
});
test('본인 영치금은 입력·버튼을 숨기고 직접 호출도 API 전 차단한다',async()=>{
  const {context,alerts,requests}=clientFixture();const html=context.prisonCommunityPanelHtml();
  assert.match(html,/본인의 영치금은 직접 납부할 수 없습니다/);assert.doesNotMatch(html,/prisonFundAmount|data-prison-fund/);
  await context.contributePrisonFund();assert.equal(alerts.length,1);assert.equal(requests.length,0);
});
test('타인 모금·OWNER 입력은 5조 정수를 유지하고 화면은 단위로 표시한다',async()=>{
  const {context,alerts}=clientFixture();context.state.viewer.id=9;context.state.access.canSetReleasePrice=true;
  const html=context.prisonCommunityPanelHtml();assert.match(html,/id="prisonFundAmount"/);assert.match(html,/id="prisonReleasePriceInput"[^>]*max="5000000000000"/);
  assert.match(html,/>1조<|>5조</);assert.match(html,/최대 5조/);
  await context.setPrisonReleasePrice();assert.equal(alerts.length,0);
});
