import test from 'node:test';
import assert from 'node:assert/strict';
import {PGlite} from '@electric-sql/pglite';
import baseline from './fixtures/pve-reform-baseline-20261008.json' with {type:'json'};
import {migratePortalRate,inspectReform,activateReform,buildReformPlan} from '../scripts/ops/pve-reform-20261008.mjs';
import {PVE_REFORM_VERSION} from '../shared/pve-reform-20261008.mjs';
async function fixture(t){
 const c=new PGlite();t.after(()=>c.close());
 await c.exec(`CREATE TABLE app_meta(key TEXT PRIMARY KEY,value TEXT,updated_at TEXT);
 CREATE TABLE users(id BIGINT PRIMARY KEY,role TEXT,status TEXT);
 INSERT INTO users VALUES(1,'OWNER','ACTIVE');
 CREATE TABLE battle_monsters(id BIGINT PRIMARY KEY,is_active BIGINT,tower_enabled BIGINT);
 CREATE TABLE tower_seasons(id BIGINT PRIMARY KEY,name TEXT,status TEXT,starts_at TEXT,ends_at TEXT,max_floor BIGINT,created_at TEXT,updated_at TEXT);
 CREATE TABLE tower_floor_ranges(id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1000) PRIMARY KEY,season_id BIGINT,monster_id BIGINT,start_floor BIGINT,end_floor BIGINT,power_override BIGINT,reward_coin BIGINT,is_boss BIGINT,is_active BIGINT,created_at TEXT,updated_at TEXT);
 CREATE TABLE tower_floors(id BIGINT PRIMARY KEY,season_id BIGINT,floor_no BIGINT,monster_id BIGINT,power_override BIGINT,reward_coin BIGINT,is_boss BIGINT,is_active BIGINT,created_at TEXT,updated_at TEXT);
 CREATE TABLE unified_drop_bindings_v1667(id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 5000) PRIMARY KEY,source_type TEXT,source_id TEXT,trigger_type TEXT,pool_id BIGINT,priority BIGINT,is_enabled BIGINT,created_at TEXT,updated_at TEXT);
 CREATE TABLE cow_room_portal_rolls_v1(id TEXT PRIMARY KEY,user_id BIGINT,state TEXT CHECK(state IN('MISSED','OPEN','CONSUMED')),rate_percent BIGINT);
 INSERT INTO cow_room_portal_rolls_v1 VALUES('old',7,'OPEN',2),('used',8,'CONSUMED',3);
 CREATE TABLE tower_user_progress(user_id BIGINT,season_id BIGINT,current_floor BIGINT,highest_floor BIGINT);
 INSERT INTO tower_user_progress VALUES(7,1,71,70);
 CREATE TABLE expedition_v3_runs_v1(request_id TEXT,state TEXT,response_json TEXT);
 INSERT INTO expedition_v3_runs_v1 VALUES('pending','PREPARED','frozen-result');
 CREATE TABLE admin_logs(id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,admin_id BIGINT,action_type TEXT,target_type TEXT,target_id TEXT,before_data TEXT,after_data TEXT,created_at TEXT);`);
 for(const [table,rows] of [['app_meta',baseline.meta],['tower_seasons',[baseline.season]],['tower_floor_ranges',baseline.ranges],['tower_floors',baseline.floors],['unified_drop_bindings_v1667',baseline.bindings]])for(const row of rows){const keys=Object.keys(row);await c.query(`INSERT INTO ${table}(${keys.join(',')}) VALUES(${keys.map((_,i)=>'$'+(i+1)).join(',')})`,Object.values(row));}
 for(const id of new Set(baseline.ranges.map(r=>Number(r.monster_id))))await c.query('INSERT INTO battle_monsters VALUES($1,1,1)',[id]);
 const proof=async()=>({origin:'https://cnine-card.pages.dev',version:PVE_REFORM_VERSION,runtimeMatchesCommittedBuild:true,portalRatePercent:0.5,commit:'a'.repeat(40),checkedAt:new Date().toISOString(),beforeSha256:(await inspectReform(c)).beforeSha256});
 return {c,proof};
}
test('PostgreSQL: rate migration, atomic reform, exact tower totals and reset replay preserve accounts',async t=>{
 const {c,proof}=await fixture(t);await migratePortalRate(c);await migratePortalRate(c);
 await c.query("INSERT INTO cow_room_portal_rolls_v1 VALUES('decimal',7,'OPEN',0.5)");
 assert.equal((await c.query("SELECT rate_percent FROM cow_room_portal_rolls_v1 WHERE id='decimal'")).rows[0].rate_percent,0.5);
 const applied=await activateReform(c,await proof());assert.equal(applied.receipt.portalReset.count,2);assert.equal(applied.receipt.portalReset.users,1);
 const rows=(await c.query('SELECT * FROM tower_floor_ranges WHERE is_active=1 ORDER BY start_floor')).rows;
 assert.equal(rows.length,100);assert.equal(rows.reduce((n,r)=>n+Number(r.reward_coin),0),99950000000);
 assert.equal(Number(rows[69].power_override),20000000);assert.equal(Number(rows[99].power_override),200000000);
 assert.equal(Number(rows[99].reward_coin),20000000000);
 assert.equal((await c.query("SELECT state FROM cow_room_portal_rolls_v1 WHERE id='used'")).rows[0].state,'CONSUMED');
 assert.equal(Number((await c.query('SELECT current_floor FROM tower_user_progress')).rows[0].current_floor),71);
 assert.equal((await c.query('SELECT response_json FROM expedition_v3_runs_v1')).rows[0].response_json,'frozen-result');
 await c.query("INSERT INTO cow_room_portal_rolls_v1 VALUES('new',7,'OPEN',0.5)");
 assert.equal((await activateReform(c,await proof())).replayed,true);
 assert.equal((await c.query("SELECT state FROM cow_room_portal_rolls_v1 WHERE id='new'")).rows[0].state,'OPEN');
 assert.equal((await c.query('SELECT * FROM admin_logs')).rows.length,1);
 assert.equal((await c.query("SELECT * FROM unified_drop_bindings_v1667 WHERE source_id IN('FURNACE_ELITE','FURNACE_ABYSS')")).rows.length,2);
});
test('PostgreSQL: stale preview and late database failure leave CMS and OPEN portals intact',async t=>{
 const {c,proof}=await fixture(t);await migratePortalRate(c);const original=await inspectReform(c),p=await proof();
 await assert.rejects(()=>activateReform(c,{...p,beforeSha256:'f'.repeat(64)}),/CMS changed/);
 await c.exec("ALTER TABLE admin_logs ADD CONSTRAINT reject_test CHECK(action_type<>'PVE_REFORM')");
 await assert.rejects(()=>activateReform(c,p),/reject_test/);
 assert.equal((await inspectReform(c)).beforeSha256,original.beforeSha256);
 assert.equal((await c.query("SELECT state FROM cow_room_portal_rolls_v1 WHERE id='old'")).rows[0].state,'OPEN');
 assert.equal((await inspectReform(c)).receipt,null);
});
test('baseline plan preserves early monster identity and creates the approved tiers',()=>{
 const plan=buildReformPlan(baseline);assert.equal(plan.tower[0].monsterId,Number(baseline.ranges[0].monster_id));
 assert.deepEqual(plan.scrap.difficulties.map(r=>r.clearCoin),[50000000,100000000,200000000,300000000,800000000]);
 assert.deepEqual(plan.cow.clearCoin,[500000000,1500000000,3000000000]);
});
