import test from 'node:test';
import assert from 'node:assert/strict';
import {PGlite} from '@electric-sql/pglite';
import {MERCENARY_CMS_SEED as seed} from '../functions/_mercenary_cms_seed.js';
import {MERCENARY_ACCOUNTING_SCHEMA} from '../functions/_mercenary_draw_accounting.js';
import {grantRagnielToTwo} from '../scripts/ops/ragniel-two-grant-20260928.mjs';
async function fixture(){const db=new PGlite();await db.exec(`CREATE TABLE users(id BIGINT PRIMARY KEY,nickname TEXT,role TEXT,status TEXT,coin BIGINT,card_shards BIGINT,magic_crystals BIGINT);
INSERT INTO users VALUES(1,'운영자','OWNER','ACTIVE',1,2,3),(303,'[C9]족쪽이','USER','ACTIVE',4,5,6),(1255,'전게씹선미아웃','USER','ACTIVE',7,8,9),(22,'다른유저','USER','ACTIVE',10,11,12);
CREATE TABLE mercenary_draw_config_v1(id INTEGER PRIMARY KEY,payload_json TEXT);INSERT INTO mercenary_draw_config_v1 VALUES(1,'{}');
CREATE TABLE mercenary_cms_documents_v1(doc_key TEXT PRIMARY KEY,revision INTEGER,payload_json TEXT);
CREATE TABLE user_mercenary_loadout_v1(user_id BIGINT PRIMARY KEY,mercenary_code TEXT,revision INTEGER);INSERT INTO user_mercenary_loadout_v1 VALUES(303,'V-049',5),(1255,'V-021',6);
CREATE TABLE user_mercenary_growth_v1(user_id BIGINT,mercenary_code TEXT,level INTEGER,experience BIGINT,revision INTEGER,PRIMARY KEY(user_id,mercenary_code));INSERT INTO user_mercenary_growth_v1 VALUES(1255,'V-046',12,345,4);
CREATE TABLE app_meta(key TEXT PRIMARY KEY,value TEXT,updated_at TEXT);CREATE TABLE admin_logs(id BIGSERIAL PRIMARY KEY,admin_id BIGINT,action_type TEXT,target_type TEXT,target_id TEXT,before_data TEXT,after_data TEXT);`);
for(const sql of MERCENARY_ACCOUNTING_SCHEMA)await db.exec(sql);await db.query("INSERT INTO mercenary_cms_documents_v1 VALUES('config',71,$1)",[JSON.stringify(seed.document)]);await db.exec("INSERT INTO user_mercenary_cards_v1 VALUES(303,'V-049',1,0,'original','original'),(1255,'V-046',2,1,'original','original'),(22,'V-046',1,0,'other','other')");
const q=async(sql,args=[])=>(await db.query(sql,args)).rows,run=async()=>{await db.exec('BEGIN');try{const r=await grantRagnielToTwo(q);await db.exec('COMMIT');return r;}catch(e){await db.exec('ROLLBACK');throw e;}},snapshot=async()=>Object.fromEntries(await Promise.all(['users','user_mercenary_cards_v1','mercenary_card_acquisitions_v1','mercenary_card_atomic_guard_v1','user_mercenary_loadout_v1','user_mercenary_growth_v1','mercenary_cms_documents_v1','mercenary_draw_config_v1','app_meta','admin_logs'].map(async t=>[t,await q('SELECT * FROM '+t+' ORDER BY 1,2')])));return {db,q,run,snapshot};}
test('one permanent SSS Ragniel each, existing copy accounting and other mercenaries/formation/balances preserved; retry adds nothing',async()=>{const f=await fixture();try{const a=await f.snapshot(),r=await f.run(),b=await f.snapshot();assert.equal(r.count,2);assert.equal(r.rank,'SSS');assert.equal(r.permanent,true);assert.deepEqual(r.recipients.map(x=>[x.userId,x.beforeCopies,x.totalCopies,x.duplicateCount]),[[303,0,1,0],[1255,2,3,2]]);assert.equal(b.mercenary_card_acquisitions_v1.length,2);assert.equal(b.admin_logs.length,2);for(const t of ['users','mercenary_card_atomic_guard_v1','user_mercenary_loadout_v1','user_mercenary_growth_v1','mercenary_cms_documents_v1','mercenary_draw_config_v1'])assert.deepEqual(b[t],a[t]);assert.deepEqual(b.user_mercenary_cards_v1.filter(x=>Number(x.user_id)===22||x.mercenary_code==='V-049'),a.user_mercenary_cards_v1.filter(x=>Number(x.user_id)===22||x.mercenary_code==='V-049'));assert.equal((await f.run()).replayed,true);assert.deepEqual(await f.snapshot(),b);}finally{await f.db.close();}});
test('failure while auditing second account rolls both grants, acquisitions and receipt back',async()=>{const f=await fixture();try{await f.q("ALTER TABLE admin_logs ADD CONSTRAINT reject_second CHECK(target_id<>'1255')");const a=await f.snapshot();await assert.rejects(f.run,/reject_second/);assert.deepEqual(await f.snapshot(),a);}finally{await f.db.close();}});
test('acquisition OFF and changed recipient both prevent all grants',async()=>{const f=await fixture();try{await f.q('UPDATE mercenary_draw_config_v1 SET payload_json=$1 WHERE id=1',[JSON.stringify({cardRules:{cardWeights:{'V-046':0}}})]);let a=await f.snapshot();await assert.rejects(f.run,/acquisition is OFF/);assert.deepEqual(await f.snapshot(),a);await f.q("UPDATE mercenary_draw_config_v1 SET payload_json='{}' WHERE id=1");await f.q("UPDATE users SET nickname='다른이름' WHERE id=1255");a=await f.snapshot();await assert.rejects(f.run);assert.deepEqual(await f.snapshot(),a);}finally{await f.db.close();}});
