import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import {PGlite} from '@electric-sql/pglite';
import {JointSQLiteDB} from './helpers/joint-db.mjs';
import {__postgresCompatTest} from '../functions/_postgres_d1_compat.js';
import {ensureWeeklyRaidBossesV1,weeklyRaidBossSettings,weeklyRaidBossForKst,WEEKLY_RAID_SETTINGS_KEY} from '../functions/_raid_weekly_bosses_v1.js';
import {readWeeklyRaidCms,saveWeeklyRaidCms,normalizeWeeklyRaidConfig} from '../functions/_raid_weekly_cms_v2141.js';
import {cleanRaidSettingsV1293,defaultRaidSettingsV1293,raidRewardPlanV1293,raidCombatSnapshotV1293} from '../functions/_raid_overhaul.js';

const schema=`CREATE TABLE app_meta(key TEXT PRIMARY KEY,value TEXT,updated_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE raid_bosses(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT,image_url TEXT,max_hp INTEGER,defense_rate REAL,is_active INTEGER,sort_order INTEGER,updated_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE admin_logs(id INTEGER PRIMARY KEY AUTOINCREMENT,admin_id INTEGER,action_type TEXT,target_type TEXT,target_id TEXT,before_data TEXT,after_data TEXT);
CREATE TABLE raid_instances(id INTEGER PRIMARY KEY,boss_id INTEGER,current_hp INTEGER);
INSERT INTO app_meta(key,value) VALUES('safe_runtime_upgrade_v2140_weekly_raid_bosses','1');
INSERT INTO raid_bosses(name,max_hp,defense_rate,is_active) VALUES('나가토',199000000,18,1),('요리이치',192000000,23,1),('이치고',204000000,24,1),('센쥬 하시라마',190000000,24,1),('오비토',186000000,25,1),('길가메시',198000000,26,1),('마이트 가이',216000000,27,1);
INSERT INTO raid_instances VALUES(77,4,123456);`;
async function fixture(t,postgres){
  let DB,pg,fail='';
  if(postgres){
    pg=new PGlite();await pg.exec("CREATE FUNCTION sqlite_now() RETURNS TEXT LANGUAGE SQL STABLE AS $$ SELECT to_char(timezone('UTC',CURRENT_TIMESTAMP),'YYYY-MM-DD HH24:MI:SS') $$");
    await pg.exec(schema.replaceAll('INTEGER PRIMARY KEY AUTOINCREMENT','BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY').replaceAll('INTEGER','BIGINT').replaceAll('CURRENT_TIMESTAMP','sqlite_now()'));
    DB=new __postgresCompatTest.PostgresD1Database({async query(input){const sql=typeof input==='string'?input:input.text;if(fail&&sql.includes(fail))throw Error('INJECTED_FAILURE');const r=await pg.query(sql,typeof input==='string'?[]:input.values||[]);return {...r,rowCount:r.affectedRows??r.rows.length};}});
  }else{DB=new JointSQLiteDB();DB.sql.exec(schema);}
  t.after(()=>pg?pg.close():DB.sql.close());
  return {env:{DB},p:(sql,...args)=>DB.prepare(sql).bind(...args),fail:value=>{fail=value;DB.failAt=value;}};
}
const owner={id:1,role:'OWNER'};
for(const postgres of [false,true]){
  test(`${postgres?'PostgreSQL':'SQLite'}: 기존 7종 마커가 있어도 3종으로 교정하고 저장된 HP·진행 방·반복 실행을 보존한다`,async t=>{
    const f=await fixture(t,postgres);await ensureWeeklyRaidBossesV1(f.env);const data=await readWeeklyRaidCms(f.env);
    assert.deepEqual(data.bosses.map(b=>b.code),['NAGATO','YORIICHI','ICHIGO']);assert.equal(data.days.length,7);
    assert.equal(data.bosses[0].maxHp,199000000);assert.equal(data.bosses[0].defenseRate,18);
    assert.equal(Number((await f.p('SELECT COUNT(*) n FROM raid_bosses WHERE is_active=1').first()).n),3);
    assert.equal(Number((await f.p('SELECT current_hp FROM raid_instances WHERE id=77').first()).current_hp),123456);
    await ensureWeeklyRaidBossesV1(f.env);assert.equal(Number((await f.p('SELECT COUNT(*) n FROM raid_bosses').first()).n),7);
  });
  test(`${postgres?'PostgreSQL':'SQLite'}: CMS 저장·재조회가 요일·궁극기·쫄몹·100억 보상에 반영되고 이전 방은 고정된다`,async t=>{
    const f=await fixture(t,postgres),before=await readWeeklyRaidCms(f.env),draft=structuredClone(before.config);
    const original=cleanRaidSettingsV1293(weeklyRaidBossSettings(defaultRaidSettingsV1293(),before.bosses[0]));
    draft.rotation[2]='ICHIGO';const edited=draft.bosses.ICHIGO;
    edited.bossAttackPower=9000;edited.bossAttackIntervalMs=2000;edited.ultimate={everyAttacks:2,multiplier:2.75};edited.minionGuardRatio=0;
    edited.minions[0].maxHp=333333;edited.minions[1].spawnAtHpPct=.4;
    edited.rewards={participation:[{type:'COIN',amount:10000000000}],clear:[{type:'CORE_RAID_ENTRY_TICKET',amount:7}],minionClear:[{type:'MASTER_STAR',amount:4}],rareDrops:[{type:'CORE_RAID_ENTRY_TICKET',amount:2,chance:0}],damageMilestones:[],rankRewards:[]};
    const saved=await saveWeeklyRaidCms(f.env,owner,draft),loaded=await readWeeklyRaidCms(f.env);assert.deepEqual(saved,loaded);
    const today=weeklyRaidBossForKst(Date.parse('2026-09-22T12:00:00+09:00'),loaded.config.rotation,loaded.bosses);assert.equal(today.code,'ICHIGO');
    const cfg=cleanRaidSettingsV1293(weeklyRaidBossSettings(defaultRaidSettingsV1293(),today));
    assert.equal(cfg.participationCoin,10000000000);assert.equal(cfg.clearCoin,0);assert.equal(cfg.rewardShards,0);
    assert.equal(cfg.bossAttackPower,9000);assert.equal(cfg.bossAttackIntervalMs,2000);assert.equal(cfg.bossProfile.ultimate.multiplier,2.75);assert.equal(cfg.bossProfile.minionGuardRatio,0);assert.equal(cfg.bossProfile.minions[0].maxHp,333333);
    const plan=raidRewardPlanV1293({cfg,instanceId:8,userId:3,totalDamage:10,finalRank:1,cleared:true,minionsDefeated:2});assert.equal(plan.coin,10000000000);assert.equal(plan.inventoryRewards.find(r=>r.itemCode==='CORE_RAID_ENTRY_TICKET').amount,7);assert.equal(plan.inventoryRewards.find(r=>r.itemCode==='MASTER_STAR').amount,8);
    assert.equal(original.bossAttackPower,Math.floor(5800000/2300));assert.equal(original.bossProfile.minions[0].maxHp,22000000);assert.equal(original.rewards.participation[0].amount,3000000);
    const snap=raidCombatSnapshotV1293([{userId:1,totalPower:10000000,totalDamage:100}],{max_hp:1,status:'BATTLE',starts_at:'2026-09-22T00:00:00Z'},cfg,Date.parse('2026-09-22T00:00:05Z'));
    assert.equal(snap.ultimateCasts,1);assert.ok(snap.bossHp>100000000);
    await assert.rejects(saveWeeklyRaidCms(f.env,owner,draft),e=>e.status===409);
    assert.equal(Number((await f.p('SELECT COUNT(*) n FROM admin_logs').first()).n),1);
  });
  test(`${postgres?'PostgreSQL':'SQLite'}: 감사 실패는 설정도 롤백하고 비OWNER·초과 코인·외부 보스는 차단한다`,async t=>{
    const f=await fixture(t,postgres),initial=await readWeeklyRaidCms(f.env),draft=structuredClone(initial.config);
    f.fail('INSERT INTO admin_logs');await assert.rejects(saveWeeklyRaidCms(f.env,owner,draft),/INJECTED_FAILURE/);f.fail('');assert.deepEqual((await readWeeklyRaidCms(f.env)).config,initial.config);
    await assert.rejects(saveWeeklyRaidCms(f.env,{id:2,role:'ADMIN'},draft),e=>e.status===403);
    draft.rotation[0]='HASHIRAMA';await assert.rejects(saveWeeklyRaidCms(f.env,owner,draft),e=>e.status===400);draft.rotation=[...initial.config.rotation];
    draft.bosses.NAGATO.rewards.clear=[{type:'COIN',amount:10000000001}];await assert.rejects(saveWeeklyRaidCms(f.env,owner,draft),e=>e.status===400);
    assert.equal((await f.p('SELECT value FROM app_meta WHERE key=?',WEEKLY_RAID_SETTINGS_KEY).first()).value,'{}');
  });
}
test('7일 표시에서 같은 보스가 반복돼도 TODAY는 당일 한 곳만 표시한다',()=>{
  const app=readFileSync(new URL('../js/app.js',import.meta.url),'utf8'),start=app.indexOf('function raidWeeklyBossStrip('),end=app.indexOf('\nfunction raidMinionMarkup',start);
  const render=vm.runInNewContext(`(${app.slice(start,end)})`,{escapeHtml:s=>String(s)});
  const cfg=normalizeWeeklyRaidConfig(),weeklyBosses=cfg.rotation.map((code,weekday)=>({code,weekday,dayLabel:weekday,name:code}));
  const html=render({weeklyBosses,todayBoss:weeklyBosses[1]});assert.equal((html.match(/<em>TODAY<\/em>/g)||[]).length,1);
});
test('보스 방어 CMS 수치는 실제 HP 감소와 기여 피해 양쪽에 동일하게 적용된다',()=>{
  const base={...defaultRaidSettingsV1293(),phase2Enabled:false,bossProfile:{maxHp:200000000,minions:[],minionGuardRatio:0,defenseRate:0}};
  const party=[{userId:1,totalPower:10000000,totalDamage:12000000}],room={max_hp:200000000,status:'BATTLE',starts_at:'2026-09-22T00:00:00Z'},now=Date.parse('2026-09-22T00:00:10Z');
  const undefended=raidCombatSnapshotV1293(party,room,base,now),defended=raidCombatSnapshotV1293(party,room,{...base,bossProfile:{...base.bossProfile,defenseRate:50}},now);
  assert.equal(200000000-defended.bossHp,(200000000-undefended.bossHp)/2);assert.equal(defended.states[0].shownDamage,undefended.states[0].shownDamage/2);
});
