import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {PGlite} from '@electric-sql/pglite';
import {__postgresCompatTest} from '../functions/_postgres_d1_compat.js';
import {handleEquipment,publicEquippedTitleMap} from '../functions/_equipment.js';
import {RAID_BUS_DRIVER_TITLE_KEY,ensureRaidBusDriverTitle} from '../functions/_raid_bus_driver_title.js';

const schema=`CREATE TABLE app_meta(key TEXT PRIMARY KEY,value TEXT,updated_at TEXT);
 CREATE TABLE character_titles(id INTEGER PRIMARY KEY AUTOINCREMENT,code TEXT UNIQUE,name TEXT,description TEXT,badge_text TEXT,image_url TEXT,pve_power INTEGER,unlock_type TEXT,unlock_config_json TEXT,style_preset TEXT,is_active INTEGER,is_public INTEGER,sort_order INTEGER);
 CREATE TABLE users(id INTEGER PRIMARY KEY);
 CREATE TABLE user_character_titles(user_id INTEGER,title_id INTEGER,source_type TEXT,source_id TEXT,expires_at TEXT,PRIMARY KEY(user_id,title_id));
 CREATE TABLE user_title_loadout(user_id INTEGER PRIMARY KEY,title_id INTEGER,updated_at TEXT);`;
async function fixture(t,postgres){
 let DB,pg,sqlite,fail=()=>false;
 if(postgres){
  pg=new PGlite();await pg.exec("CREATE FUNCTION sqlite_now() RETURNS text LANGUAGE SQL STABLE AS $$SELECT to_char(timezone('UTC',CURRENT_TIMESTAMP),'YYYY-MM-DD HH24:MI:SS')$$;");
  await pg.exec(schema.replaceAll('INTEGER PRIMARY KEY AUTOINCREMENT','BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY'));
  DB=new __postgresCompatTest.PostgresD1Database({async query(input){const sql=typeof input==='string'?input:input.text,args=typeof input==='string'?[]:input.values||[];if(fail(sql,args))throw Error('INJECTED_FAILURE');const r=await pg.query(sql,args);return {...r,rowCount:r.affectedRows??r.rows.length};}});
 }else{
  sqlite=new DatabaseSync(':memory:');sqlite.exec(schema);
  const prepare=(sql,args=[])=>({bind(...v){return prepare(sql,v)},async first(){return sqlite.prepare(sql).get(...args)||null},async all(){return {results:sqlite.prepare(sql).all(...args)}},async run(){if(fail(sql,args))throw Error('INJECTED_FAILURE');return {meta:{changes:Number(sqlite.prepare(sql).run(...args).changes)}}});
  DB={prepare,async batch(rows){sqlite.exec('BEGIN');try{const result=[];for(const row of rows)result.push(await row.run());sqlite.exec('COMMIT');return result;}catch(e){sqlite.exec('ROLLBACK');throw e;}}};
 }
 t.after(()=>pg?pg.close():sqlite.close());
 const env={DB},p=(sql,...args)=>DB.prepare(sql).bind(...args);
 // This focused route fixture supplies the current title schema; unrelated
 // equipment/suit migrations are outside this catalogue addition.
 const prepare=DB.prepare.bind(DB);
 DB.prepare=sql=>sql.startsWith('SELECT key,value FROM app_meta WHERE key IN')?{bind(...keys){return{async all(){return{results:keys.map(key=>({key,value:'1'}))}}}}}:prepare(sql);
 const call=(path,body,user)=>handleEquipment({path,env,request:new Request('https://game.test/api/'+path,{method:'POST',body:JSON.stringify(body)}),deps:{authenticate:async()=>user,readBody:r=>r.json(),json:(body,status=200)=>({status,body})}});
 return {env,p,call,fail:fn=>{fail=fn}};
}
for(const postgres of [false,true]){
 const label=postgres?'PostgreSQL':'SQLite';
 test(`${label}: manual zero-power title registration is atomic, retry-safe and preserves CMS edits`,async t=>{
  const f=await fixture(t,postgres);f.fail(sql=>sql.startsWith('INSERT INTO app_meta'));
  await assert.rejects(()=>ensureRaidBusDriverTitle(f.env),/INJECTED_FAILURE/);
  assert.equal(Number((await f.p('SELECT COUNT(*) n FROM character_titles').first()).n),0);
  f.fail(()=>false);await ensureRaidBusDriverTitle(f.env);await ensureRaidBusDriverTitle(f.env);
  const row=await f.p('SELECT * FROM character_titles').first();
  assert.deepEqual([row.code,row.name,row.unlock_type,row.style_preset,Number(row.pve_power),Number(row.is_active),Number(row.is_public)],['RAID_BUS_DRIVER','버스기사','MANUAL','BUS_DRIVER',0,1,1]);
  assert.equal(Number((await f.p('SELECT COUNT(*) n FROM user_character_titles').first()).n),0);
  await f.p('UPDATE character_titles SET pve_power=300,is_public=0').run();await ensureRaidBusDriverTitle(f.env);
  assert.equal(Number((await f.p('SELECT pve_power FROM character_titles').first()).pve_power),300);
  await f.p('DELETE FROM app_meta WHERE key=?',RAID_BUS_DRIVER_TITLE_KEY).run();await ensureRaidBusDriverTitle(f.env);
  assert.equal(Number((await f.p('SELECT is_public FROM character_titles').first()).is_public),0);
  assert.equal(Number((await f.p('SELECT COUNT(*) n FROM character_titles').first()).n),1);
 });
 test(`${label}: only OWNER can manually grant, retries do not duplicate, unowned equip is denied and public title preserves the bus appearance`,async t=>{
  const f=await fixture(t,postgres);await ensureRaidBusDriverTitle(f.env);await f.p('INSERT INTO users VALUES(7),(8),(9)').run();
  const id=Number((await f.p('SELECT id FROM character_titles').first()).id),body={userId:8,titleId:id};
  assert.equal((await f.call('admin/title-grant',body,null)).status,403);
  assert.equal((await f.call('admin/title-grant',body,{id:9,role:'USER'})).status,403);
  for(let i=0;i<2;i++)assert.equal((await f.call('admin/title-grant',body,{id:7,role:'OWNER'})).status,200);
  const owned=(await f.p('SELECT * FROM user_character_titles').all()).results;assert.equal(owned.length,1);assert.equal(Number(owned[0].user_id),8);assert.equal(owned[0].source_type,'ADMIN');
  assert.equal(Number((await f.p('SELECT COUNT(*) n FROM user_title_loadout').first()).n),0,'grant does not auto-equip');
  assert.equal((await f.call('character/title/equip',{titleId:id},{id:9,role:'USER'})).status,404);
  await f.p('INSERT INTO user_title_loadout(user_id,title_id) VALUES(?,?)',8,id).run();
  const titles=await publicEquippedTitleMap(f.env,[8,9]);assert.equal(titles['8'].stylePreset,'BUS_DRIVER');assert.equal(titles['8'].fontPreset,'DISPLAY');assert.equal(titles['8'].image,'/assets/ui/titles/raid-bus-driver-v1.png');assert.equal(titles['9'],undefined);
  assert.equal((await f.call('admin/title-grant',{...body,action:'REVOKE'},{id:7,role:'OWNER'})).status,200);
  assert.equal(Number((await f.p('SELECT COUNT(*) n FROM user_character_titles').first()).n),0);assert.deepEqual(await publicEquippedTitleMap(f.env,[8]),{});
 });
}
