import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {duoFixture} from './helpers/ranked-duo-db.mjs';
import {prepareDuoAutomation,reconcileDuoSeason} from '../functions/_ranked_duo_seasons.js';
import {duoLifecycle} from '../functions/_ranked_duo.js';
import {copyRankedDuoPolicy,DUO_WEEKLY_POLICY_KEY} from '../shared/ranked-duo-weekly-v3.mjs';
import {duoTiers} from '../shared/ranked-duo-season-v2.mjs';

// Execute the production initializer SQL: a new Worker isolate used to rewrite
// all three titles, invalidate the global rating policy, and restart pairing.
const source=readFileSync(new URL('../functions/api/[[path]].js',import.meta.url),'utf8');
const titleSql=[...source.matchAll(/env\.DB\.prepare\(`(INSERT INTO character_titles[^`]*VALUES\('TITLE_RANKED_[^`]*)`\)/g)].map(m=>m[1]);
assert.equal(titleSql.length,3);
const day=86400000;

for(const postgres of [false,'pipeline'])test(`${postgres||'SQLite'} repeated ranked title initialization preserves policy and allows automatic duo start`,async t=>{
 const f=await duoFixture(t,{postgres});
 const titleSchema=`DROP TABLE character_titles;CREATE TABLE character_titles(id INTEGER PRIMARY KEY AUTOINCREMENT,code TEXT UNIQUE,name TEXT,description TEXT,badge_text TEXT,image_url TEXT,pve_power BIGINT,unlock_type TEXT,unlock_config_json TEXT,is_active INTEGER,is_public INTEGER,sort_order INTEGER,style_preset TEXT,updated_at TEXT)`;
 if(f.pg)await f.pg.exec(titleSchema.replace('INTEGER PRIMARY KEY AUTOINCREMENT','BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY'));else f.native.exec(titleSchema);
 await prepareDuoAutomation(f.env);
 const seed=()=>f.DB.batch(titleSql.map(sql=>f.DB.prepare(sql)));
 const revision=async()=>Number((await f.p('SELECT revision FROM ranked_duo_policy_version_v1 WHERE id=1').first()).revision);
 await seed();
 const initial=await revision(),before=(await f.p('SELECT * FROM character_titles ORDER BY id').all()).results;
 for(let i=0;i<5;i++)await seed();
 assert.equal(await revision(),initial,'unchanged title seeds must not invalidate duo profiles');
 assert.deepEqual((await f.p('SELECT * FROM character_titles ORDER BY id').all()).results,before);

 // Repair outdated display fields while preserving CMS power/art and ownership.
 await f.p("UPDATE character_titles SET name=NULL,is_active=0,is_public=NULL,style_preset='OLD',pve_power=12345,image_url='/custom.png' WHERE code='TITLE_RANKED_CHALLENGER'").run();
 const damaged=await revision();await seed();
 assert.equal(await revision(),damaged+1);
 const repaired=await f.p("SELECT * FROM character_titles WHERE code='TITLE_RANKED_CHALLENGER'").first();
 assert.equal(repaired.id,before[0].id);assert.equal(repaired.name,'챌린저★★★★');assert.equal(Number(repaired.is_active),1);assert.equal(Number(repaired.is_public),1);assert.equal(repaired.style_preset,'CHALLENGER');
 assert.equal(Number(repaired.pve_power),12345);assert.equal(repaired.image_url,'/custom.png');
 await seed();assert.equal(await revision(),damaged+1);

 const settings={enabled:true,seasonName:'시즌 2',startsAt:new Date(f.clock()).toISOString(),endsAt:new Date(f.clock()+8*day).toISOString(),energy:{maxEnergy:5,rechargeMinutes:30,costPerBattle:1},initialScore:1000,winScore:24,loseScore:16,winCoin:250000,...duoTiers()};
 await f.p('INSERT INTO app_meta(key,value) VALUES(?,?)',DUO_WEEKLY_POLICY_KEY,JSON.stringify(copyRankedDuoPolicy(settings,new Date(f.clock()).toISOString()))).run();
 const tick=()=>reconcileDuoSeason(f.env,{settings,deps:f.deps,now:f.clock()});
 await tick();for(const user of [2,3,4,5])assert.equal((await f.call('ranked-duo/join',{user,method:'POST'})).status,200);
 f.advance(day);await tick();
 const seasonId=(await duoLifecycle.currentSeason(f.env)).id;
 for(let i=0;i<6;i++){
  await seed();await tick();
  if((await duoLifecycle.currentSeason(f.env)).status==='ACTIVE')break;
 }
 const active=await duoLifecycle.currentSeason(f.env);
 assert.equal(active.id,seasonId);assert.equal(active.status,'ACTIVE');assert.equal(Number(active.participant_count),4);
 assert.equal(Number((await f.p('SELECT COUNT(*) n FROM ranked_duo_teams_v1 WHERE season_id=?',seasonId).first()).n),2);
 assert.equal(Number((await f.p('SELECT COUNT(*) n FROM ranked_duo_entries_v1 WHERE season_id=? AND team_id IS NULL',seasonId).first()).n),0);
 const admission=await f.call('ranked-duo/match',{user:2,method:'POST'});
 assert.equal(admission.status,200,JSON.stringify(admission));assert.ok(admission.data.token);
});
