import test from 'node:test';
import assert from 'node:assert/strict';
import {PGlite} from '@electric-sql/pglite';
import plan from '../scripts/ops/recruitment-gift-corrections-20261002.targets.json' with {type:'json'};
import {apply,verify,PLAN_HASH,TARGETS,ROOMS,ITEM_CODE} from '../scripts/ops/recruitment-gift-corrections-20261002.mjs';

async function fixture(t){
 const db=new PGlite();t.after(()=>db.close());
 await db.exec(`CREATE TABLE users(id BIGINT PRIMARY KEY,nickname TEXT,role TEXT,status TEXT,coin BIGINT DEFAULT 123);
 INSERT INTO users VALUES(1,'관리자','OWNER','ACTIVE',123);
 CREATE TABLE user_second_verifications(user_id BIGINT,provider TEXT,provider_user_id TEXT);
 CREATE TABLE inventory_items(code TEXT PRIMARY KEY,name TEXT,is_active BIGINT);INSERT INTO inventory_items VALUES('RECRUITMENT_GIFT_BOX','영입전 사은품',1);
 CREATE TABLE cnine_user_inventory(user_id BIGINT,item_code TEXT,quantity BIGINT,unseen_quantity BIGINT,created_at TEXT,updated_at TEXT,PRIMARY KEY(user_id,item_code));
 CREATE TABLE inventory_logs(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id BIGINT,item_code TEXT,change_amount BIGINT,balance_after BIGINT,reason TEXT,reference_type TEXT,reference_id TEXT,admin_id BIGINT,created_at TEXT);
 CREATE TABLE joint_operations_v1(request_id TEXT PRIMARY KEY,user_id BIGINT,kind TEXT,status TEXT,plan_json TEXT);
 CREATE TABLE admin_logs(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,admin_id BIGINT,action_type TEXT,target_type TEXT,target_id TEXT,before_data TEXT,after_data TEXT,created_at TEXT);
 CREATE TABLE user_message_rewards(user_id BIGINT,message_id BIGINT,reward_type TEXT);
 CREATE TABLE app_meta(key TEXT PRIMARY KEY,value TEXT,updated_at TEXT);
 INSERT INTO cnine_user_inventory VALUES(1,'RECRUITMENT_GIFT_BOX',99,0,'original','original'),(88,'MASTER_STAR',700,3,'original','original');`);
 for(const target of TARGETS){
  await db.query("INSERT INTO users VALUES($1,$2,'USER','ACTIVE',123)",[target.userId,target.nickname]);
  await db.query("INSERT INTO user_second_verifications VALUES($1,'PLAYDK',$2)",[target.userId,target.playdkId]);
  await db.query("INSERT INTO cnine_user_inventory VALUES($1,$2,2,0,'original','original')",[target.userId,ITEM_CODE]);
  await db.query("INSERT INTO app_meta VALUES($1,'legacy-global-once','original')",['ops:recruitment-gift-once:user:'+target.userId+':v1']);
 }
 for(const grant of plan.reviewedGrants)await db.query('INSERT INTO inventory_logs(id,user_id,item_code,change_amount,balance_after,reference_type,reference_id) VALUES($1,$2,$3,$4,1,$5,$6)',[grant.id,grant.userId,ITEM_CODE,grant.amount,grant.referenceType,grant.referenceId]);
 for(const room of ROOMS)await db.query("INSERT INTO app_meta VALUES($1,$2,'original')",[room.originalOperationKey,JSON.stringify({status:'COMPLETED',operationKey:room.originalOperationKey,itemCode:ITEM_CODE,allocations:room.originalPaid})]);
 for(const evidence of plan.manualEvidence){
  await db.query("INSERT INTO joint_operations_v1 VALUES($1,$2,'RECRUITMENT_GIFT_GRANT','COMPLETED',$3)",[evidence.requestId,evidence.userId,JSON.stringify({amount:evidence.amount,adminId:evidence.adminId})]);
  await db.query("INSERT INTO admin_logs(id,admin_id,action_type,target_id,after_data) VALUES($1,$2,'RECRUITMENT_GIFT_GRANT',$3,$4)",[evidence.auditId,evidence.adminId,String(evidence.userId),JSON.stringify({requestId:evidence.requestId,itemCode:ITEM_CODE,amount:evidence.amount})]);
 }
 const snapshot=async()=>{const out={};for(const table of ['users','cnine_user_inventory','inventory_logs','admin_logs','app_meta'])out[table]=(await db.query('SELECT * FROM '+table+' ORDER BY 1,2')).rows;return out;};
 return {db,snapshot,run:options=>apply(db,{expectedPlanHash:PLAN_HASH,...options})};
}

test('each room grants its missing copy despite past gifts and legacy markers; original and CMS manual grants are excluded, with 55 boxes for 42 accounts',async t=>{
 const f=await fixture(t),before=await f.snapshot();const preview=await f.run({dryRun:true});assert.equal(preview.receipt.totalBoxes,55);assert.deepEqual(await f.snapshot(),before);
 const result=await f.run(),after=await f.snapshot();assert.equal(result.receipt.uniqueRecipients,42);assert.equal(result.receipt.accountChanges.filter(row=>row.amount===2).length,13);
 assert.deepEqual(result.receipt.rooms.map(room=>room.recipients.filter(row=>row.source==='CORRECTION_GRANTED').length),[19,36]);
 assert.deepEqual(after.users,before.users);for(const row of before.app_meta)assert.deepEqual(after.app_meta.find(next=>next.key===row.key),row);
 assert.deepEqual(after.cnine_user_inventory.filter(row=>row.item_code!==ITEM_CODE||Number(row.user_id)===1),before.cnine_user_inventory.filter(row=>row.item_code!==ITEM_CODE||Number(row.user_id)===1));
 for(const row of result.receipt.accountChanges){assert.equal(BigInt(row.after.quantity)-BigInt(row.before.quantity),BigInt(row.amount));if(plan.manualEvidence.some(m=>m.userId===row.userId))assert.equal(row.amount,0);}
 assert.equal((await verify(f.db)).verification.campaignMarkers,109);assert.equal((await f.run()).replayed,true);assert.deepEqual(await f.snapshot(),after);
});

test('a newly completed manual payment excludes both room corrections for that account; unmatched manual proof blocks payment',async t=>{
 const f=await fixture(t),request='late-manual-request-88';
 await f.db.query("INSERT INTO inventory_logs(user_id,item_code,change_amount,balance_after,reference_type,reference_id) VALUES(88,$1,1,3,'V3_JOINT',$2)",[ITEM_CODE,request]);
 const incomplete=await f.snapshot();await assert.rejects(f.run(),/Unreviewed joint grant/);assert.deepEqual(await f.snapshot(),incomplete);
 await f.db.query("INSERT INTO joint_operations_v1 VALUES($1,88,'RECRUITMENT_GIFT_GRANT','COMPLETED',$2)",[request,JSON.stringify({amount:1,adminId:5663})]);
 await f.db.query("INSERT INTO admin_logs(admin_id,action_type,target_id,after_data) VALUES(5663,'RECRUITMENT_GIFT_GRANT','88',$1)",[JSON.stringify({requestId:request,itemCode:ITEM_CODE,amount:1})]);
 const result=await f.run();assert.equal(result.receipt.totalBoxes,53);assert.equal(result.receipt.uniqueRecipients,41);assert.equal(result.receipt.accountChanges.find(row=>row.userId===88).amount,0);
 assert.deepEqual(result.receipt.rooms.map(room=>room.recipients.filter(row=>row.source==='CORRECTION_GRANTED').length),[18,35]);
});

test('late audit failure and pending manual grants roll back every room, marker and inventory delta; clean retry commits once',async t=>{
 const f=await fixture(t);await f.db.exec("ALTER TABLE admin_logs ADD CONSTRAINT forced_failure CHECK(action_type<>'OPS_RECRUITMENT_GIFT_CAMPAIGN_CORRECTION')");const before=await f.snapshot();
 await assert.rejects(f.run(),/forced_failure/);assert.deepEqual(await f.snapshot(),before);await f.db.exec('ALTER TABLE admin_logs DROP CONSTRAINT forced_failure');
 await f.db.query("INSERT INTO joint_operations_v1 VALUES('pending-manual-request-88',88,'RECRUITMENT_GIFT_GRANT','PENDING','{}')");await assert.rejects(f.run(),/Pending manual/);assert.deepEqual(await f.snapshot(),before);
 await f.db.query("DELETE FROM joint_operations_v1 WHERE request_id='pending-manual-request-88'");assert.equal((await f.run()).receipt.totalBoxes,55);assert.equal((await f.run()).replayed,true);
});
