import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {PGlite} from '@electric-sql/pglite';
import {__postgresCompatTest} from '../functions/_postgres_d1_compat.js';
import {handleEquipment,publicEquippedTitleMap} from '../functions/_equipment.js';
import {SECRET_POLICE_TITLE_KEY,ensureSecretPoliceTitle} from '../functions/_secret_police_title.js';

const schema=`CREATE TABLE app_meta(key TEXT PRIMARY KEY,value TEXT,updated_at TEXT);
 CREATE TABLE character_titles(id INTEGER PRIMARY KEY AUTOINCREMENT,code TEXT UNIQUE,name TEXT,description TEXT,badge_text TEXT,image_url TEXT,pve_power INTEGER,unlock_type TEXT,unlock_config_json TEXT,style_preset TEXT,is_active INTEGER,is_public INTEGER,sort_order INTEGER);
 CREATE TABLE users(id INTEGER PRIMARY KEY);
 CREATE TABLE user_character_titles(user_id INTEGER,title_id INTEGER,source_type TEXT,source_id TEXT,expires_at TEXT,PRIMARY KEY(user_id,title_id));
 CREATE TABLE user_title_loadout(user_id INTEGER PRIMARY KEY,title_id INTEGER,updated_at TEXT);`;
async function fixture(t,postgres){
 let DB,pg,sqlite,fail=()=>false;
 if(postgres){
  pg=new PGlite();await pg.exec("CREATE FUNCTION sqlite_now() RETURNS text LANGUAGE SQL STABLE AS $$SELECT to_char(timezone('UTC',CURRENT_TIMESTAMP),'YYYY-MM-DD HH24:MI:SS')$$;");
  await pg.exec(schema.replaceAll('INTEGER PRIMARY KEY AUTOINCREMENT','BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY'));
  DB=new __postgresCompatTest.PostgresD1Database({async query(input){const sql=typeof input==='string'?input:input.text,args=typeof input==='string'?[]:input.values||[];if(fail(sql,args))throw Error('INJECTED_FAILURE');const r=await pg.query(sql,args);return {...r,rowCount:r.affectedRows??r.rows.length};}});
 }else{
  sqlite=new DatabaseSync(':memory:');sqlite.exec(schema);
  const prepare=(sql,args=[])=>({bind(...v){return prepare(sql,v)},async first(){return sqlite.prepare(sql).get(...args)||null},async all(){return {results:sqlite.prepare(sql).all(...args)}},async run(){if(fail(sql,args))throw Error('INJECTED_FAILURE');return {meta:{changes:Number(sqlite.prepare(sql).run(...args).changes)}};}});
  DB={prepare,async batch(rows){sqlite.exec('BEGIN');try{const result=[];for(const row of rows)result.push(await row.run());sqlite.exec('COMMIT');return result;}catch(e){sqlite.exec('ROLLBACK');throw e;}}};
 }
 t.after(()=>pg?pg.close():sqlite.close());const env={DB},p=(sql,...args)=>DB.prepare(sql).bind(...args);
 // This title-only fixture already has its schema; unrelated foundations stay out.
 const prepare=DB.prepare.bind(DB);DB.prepare=sql=>sql.startsWith('SELECT key,value FROM app_meta WHERE key IN')?{bind(...keys){return{async all(){return{results:keys.map(key=>({key,value:'1'}))}}}}}:prepare(sql);
 await p("INSERT INTO character_titles(code,name,pve_power,unlock_type,unlock_config_json,is_active,is_public) VALUES('GAMBLING_KING','도박왕',75000,'PREDICTION_HITS','{}',1,1)").run();
 const call=(path,body,user)=>handleEquipment({path,env,request:new Request('https://game.test/api/'+path,{method:'POST',body:JSON.stringify(body)}),deps:{authenticate:async()=>user,readBody:r=>r.json(),json:(body,status=200)=>({status,body})}});
 return {env,p,call,fail:fn=>{fail=fn}};
}
for(const postgres of [false,true]){
 const label=postgres?'PostgreSQL':'SQLite';
 test(`${label}: registration copies current gambling power atomically, grants no users and preserves later CMS edits`,async t=>{
  const f=await fixture(t,postgres);f.fail(sql=>sql.startsWith('INSERT INTO app_meta'));
  await assert.rejects(()=>ensureSecretPoliceTitle(f.env),/INJECTED_FAILURE/);
  assert.equal(Number((await f.p("SELECT COUNT(*) n FROM character_titles WHERE code='SECRET_POLICE'").first()).n),0);
  assert.equal(await f.p('SELECT value FROM app_meta WHERE key=?',SECRET_POLICE_TITLE_KEY).first(),null);
  f.fail(()=>false);await ensureSecretPoliceTitle(f.env);await ensureSecretPoliceTitle(f.env);
  const row=await f.p("SELECT * FROM character_titles WHERE code='SECRET_POLICE'").first();
  assert.deepEqual([row.code,row.name,row.unlock_type,row.style_preset,Number(row.pve_power),Number(row.is_active),Number(row.is_public)],['SECRET_POLICE','비밀경찰','MANUAL','SECRET_POLICE',75000,1,1]);
  assert.deepEqual(JSON.parse(row.unlock_config_json),{fontPreset:'SERIF'});assert.equal(row.image_url,'/assets/ui/titles/secret-police-v1.webp');
  assert.equal(Number((await f.p('SELECT COUNT(*) n FROM user_character_titles').first()).n),0);
  await f.p("UPDATE character_titles SET pve_power=88000 WHERE code='GAMBLING_KING'").run();
  await f.p("UPDATE character_titles SET pve_power=72000,is_public=0 WHERE code='SECRET_POLICE'").run();
  await f.p('DELETE FROM app_meta WHERE key=?',SECRET_POLICE_TITLE_KEY).run();await ensureSecretPoliceTitle(f.env);
  const saved=await f.p("SELECT * FROM character_titles WHERE code='SECRET_POLICE'").first();assert.equal(Number(saved.pve_power),72000);assert.equal(Number(saved.is_public),0);
  assert.equal(Number((await f.p("SELECT COUNT(*) n FROM character_titles WHERE code='SECRET_POLICE'").first()).n),1);
 });
 test(`${label}: missing reference cannot register a zero-power title or completion marker`,async t=>{
  const f=await fixture(t,postgres);await f.p("DELETE FROM character_titles WHERE code='GAMBLING_KING'").run();await ensureSecretPoliceTitle(f.env);
  assert.equal(Number((await f.p('SELECT COUNT(*) n FROM character_titles').first()).n),0);assert.equal(await f.p('SELECT value FROM app_meta WHERE key=?',SECRET_POLICE_TITLE_KEY).first(),null);
  await f.p("INSERT INTO character_titles(code,pve_power) VALUES('GAMBLING_KING',81234)").run();await ensureSecretPoliceTitle(f.env);
  assert.equal(Number((await f.p("SELECT pve_power FROM character_titles WHERE code='SECRET_POLICE'").first()).pve_power),81234);
 });
 test(`${label}: existing OWNER grant and ownership checks apply, public badge retains the PP style`,async t=>{
  const f=await fixture(t,postgres);await ensureSecretPoliceTitle(f.env);await f.p('INSERT INTO users VALUES(7),(8),(9)').run();
  const id=Number((await f.p("SELECT id FROM character_titles WHERE code='SECRET_POLICE'").first()).id),body={userId:8,titleId:id};
  for(const user of [null,{id:9,role:'USER'}])assert.equal((await f.call('admin/title-grant',body,user)).status,403);
  for(let i=0;i<2;i++)assert.equal((await f.call('admin/title-grant',body,{id:7,role:'OWNER'})).status,200);
  const owned=(await f.p('SELECT * FROM user_character_titles').all()).results;assert.equal(owned.length,1);assert.equal(Number(owned[0].user_id),8);assert.equal(owned[0].source_type,'ADMIN');
  assert.equal(Number((await f.p('SELECT COUNT(*) n FROM user_title_loadout').first()).n),0);
  assert.equal((await f.call('character/title/equip',{titleId:id},{id:9,role:'USER'})).status,404);
  await f.p('INSERT INTO user_title_loadout(user_id,title_id) VALUES(?,?)',8,id).run();
  const titles=await publicEquippedTitleMap(f.env,[8,9]);assert.equal(titles['8'].stylePreset,'SECRET_POLICE');assert.equal(titles['8'].fontPreset,'SERIF');assert.equal(titles['8'].image,'/assets/ui/titles/secret-police-v1.webp');assert.equal(titles['9'],undefined);
  assert.equal((await f.call('admin/title-grant',{...body,action:'REVOKE'},{id:7,role:'OWNER'})).status,200);assert.deepEqual(await publicEquippedTitleMap(f.env,[8]),{});
 });
}
