import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {PGlite} from '@electric-sql/pglite';
import {__postgresCompatTest} from '../functions/_postgres_d1_compat.js';
import {SUIT_CORE_BOX,SUIT_CORE_BOX_WEIGHTS} from '../shared/suit-core-box-v1.mjs';

const ROCKET='SKILL_CHIP_ROCKET_LAUNCHER',HELI='SKILL_CHIP_HELICOPTER_AIRSTRIKE',OCTA='SKILL_CHIP_OCTA_SEEKER',BOX='PRIME_EQUIPMENT_SUPPLY_BOX';
let fixtureId=0;
class SqliteD1 {
  constructor(){this.db=new DatabaseSync(':memory:');}
  prepare(sql){
    const owner=this;
    return {values:[],bind(...values){this.values=values;return this},async first(){return owner.db.prepare(sql).get(...this.values)||null},async all(){return {results:owner.db.prepare(sql).all(...this.values)}},
      async run(){const result=owner.db.prepare(sql).run(...this.values);return {meta:{changes:Number(result.changes)},results:[]}}};
  }
  async batch(statements){this.db.exec('BEGIN');try{const results=[];for(const s of statements)results.push(await s.run());this.db.exec('COMMIT');return results}catch(error){this.db.exec('ROLLBACK');throw error}}
}
async function fixture(t,dialect){
  const pg=dialect==='postgres'?new PGlite():null;
  const db=pg?new __postgresCompatTest.PostgresD1Database({async query(input,values){const r=await pg.query(typeof input==='string'?input:input.text,typeof input==='string'?values||[]:input.values||[]);return {...r,rowCount:r.affectedRows??r.rows.length}}}):new SqliteD1();
  const exec=sql=>pg?pg.exec(sql):db.db.exec(sql),env={DB:db};
  t.after(()=>pg?pg.close():db.db.close());
  if(pg)await exec("CREATE FUNCTION sqlite_now() RETURNS text LANGUAGE SQL STABLE AS $$SELECT to_char(timezone('UTC',CURRENT_TIMESTAMP),'YYYY-MM-DD HH24:MI:SS')$$");
  const now=pg?'sqlite_now()':'CURRENT_TIMESTAMP',identity=pg?'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY':'INTEGER PRIMARY KEY';
  await exec(`
    CREATE TABLE app_meta(key TEXT PRIMARY KEY,value TEXT,updated_at TEXT DEFAULT ${now});
    INSERT INTO app_meta(key,value) VALUES('safe_runtime_upgrade_v1985_prime_draw_live','1');
    CREATE TABLE coin_logs(id ${identity},user_id INTEGER,change_amount BIGINT,balance_after BIGINT,reason TEXT);
    CREATE TABLE users(id INTEGER PRIMARY KEY,coin BIGINT,role TEXT);
    INSERT INTO users VALUES(7,1234567,'OWNER');
    CREATE TABLE inventory_items(code TEXT PRIMARY KEY,name TEXT NOT NULL,subtitle TEXT,description TEXT,category TEXT,rarity TEXT,image_url TEXT,sort_order INTEGER,is_active INTEGER DEFAULT 1,updated_at TEXT DEFAULT ${now});
    CREATE TABLE cnine_user_inventory(user_id INTEGER,item_code TEXT,quantity INTEGER NOT NULL DEFAULT 0,unseen_quantity INTEGER NOT NULL DEFAULT 0,created_at TEXT DEFAULT ${now},updated_at TEXT DEFAULT ${now},PRIMARY KEY(user_id,item_code));
    INSERT INTO cnine_user_inventory(user_id,item_code,quantity,unseen_quantity) VALUES(7,'${BOX}',12,12),(7,'EQUIPMENT_SUPPLY_BOX',25,25);
    CREATE TABLE character_equipment_items(id INTEGER PRIMARY KEY,code TEXT,name TEXT,rarity TEXT,image_url TEXT,description TEXT,slot TEXT,total_power INTEGER,pve_power INTEGER,pvp_power INTEGER,sort_order INTEGER,is_active INTEGER,is_public INTEGER);
    INSERT INTO character_equipment_items VALUES(1,'EQUIP_1','기본 장비','RARE','','','WEAPON',100,100,100,1,1,1);
    CREATE TABLE character_garage_items(id INTEGER PRIMARY KEY,code TEXT,name TEXT,rarity TEXT,image_url TEXT,description TEXT,total_power INTEGER,pve_power INTEGER,pvp_power INTEGER,sort_order INTEGER,is_active INTEGER,is_public INTEGER);
    INSERT INTO character_garage_items VALUES(1,'VEHICLE_1','기본 차량','RARE','','',100,100,100,1,1,1);
    CREATE TABLE avatar_catalog_v1(code TEXT PRIMARY KEY,name TEXT,lobby_image TEXT,description TEXT,role_label TEXT,accent TEXT,sort_order INTEGER,is_active INTEGER,is_public INTEGER);
    CREATE TABLE avatar_user_ownership_v1(user_id INTEGER,avatar_code TEXT,source_type TEXT,source_ref TEXT,acquired_at TEXT,expires_at TEXT,PRIMARY KEY(user_id,avatar_code));
    CREATE TABLE user_equipment_instances(id ${identity},user_id INTEGER,equipment_id INTEGER,source_type TEXT,source_id TEXT,request_id TEXT UNIQUE);
    CREATE TABLE inventory_logs(id ${identity},user_id INTEGER,item_code TEXT,change_amount INTEGER,balance_after INTEGER,reason TEXT,reference_type TEXT,reference_id TEXT);
  `);
  const api=await import('../functions/_prime_draw.js?prime-chips='+fixtureId++);
  await api.ensurePrimeDrawFoundation(env);
  await exec(`INSERT INTO prime_equipment_draw_pool_v1985(equipment_id,entry_code,source_weight,source_probability,boost_multiplier,draw_weight,pool_version) VALUES(1,'EQUIP_1',100,100,1,100,'PRIME_EQUIPMENT_V1985_1');
    INSERT INTO prime_vehicle_draw_pool_v1985(garage_id,entry_code,source_weight,source_probability,boost_multiplier,draw_weight,pool_version) VALUES(1,'VEHICLE_1',100,100,1,100,'PRIME_VEHICLE_V1985_1');`);
  const q=async(sql,...values)=>(await db.prepare(sql).bind(...values).all()).results;
  const deps={authenticate:async()=>({id:7,role:'OWNER'}),readBody:r=>r.json(),json:(body,status=200)=>({body,status})};
  const call=(path,body,role='OWNER')=>api.handlePrimeDraw({path,env,deps:{...deps,authenticate:async()=>({id:7,role})},request:new Request('https://test.invalid/api/'+path,body===undefined?{}:{method:'POST',body:JSON.stringify(body)})});
  const save=(weights,kind='equipment',role='OWNER')=>call('admin/prime-draw/pool',{kind,entries:[{poolKey:kind==='equipment'?'EQUIPMENT:EQUIP_1':'VEHICLE:VEHICLE_1',drawWeight:100-Object.values(weights).reduce((a,b)=>a+b,0)},...Object.entries(weights).map(([code,drawWeight])=>({poolKey:'INVENTORY_ITEM:'+code,drawWeight}))]},role);
  const open=(requestId,count=1)=>call('equipment/prime-supply-box/open',{requestId,count,poolVersion:'PRIME_EQUIPMENT_V1985_1'});
  const quantity=async(code)=>(await q('SELECT quantity FROM cnine_user_inventory WHERE user_id=7 AND item_code=?',code))[0]?.quantity||0;
  return {api,env,db,pg,exec,q,call,save,open,quantity,deps};
}

const CORE_BOX=SUIT_CORE_BOX.itemCode;
const entries=SUIT_CORE_BOX_WEIGHTS.map(row=>({poolKey:'INVENTORY_ITEM:'+row.code,drawWeight:row.weight}));
async function enable(f,rows=entries){return f.call('admin/prime-draw/pool',{kind:'suit_core',settings:{shopEnabled:true,openEnabled:true},entries:rows});}
const purchase=(f,id,count=1,expectedUnitPrice=SUIT_CORE_BOX.unitPrice)=>f.call('suit-core-box/purchase',{requestId:id,count,expectedUnitPrice});
const openCore=(f,id,count=1)=>f.call('suit-core-box/open',{requestId:id,count,poolVersion:SUIT_CORE_BOX.poolVersion});
const wallet=async f=>Number((await f.q('SELECT coin FROM users WHERE id=7'))[0].coin);

for(const dialect of ['sqlite','postgres']){
  test(`${dialect}: dedicated core pool is off until configured, isolated, four grades only and lightweight`,async t=>{
    const f=await fixture(t,dialect),before=await f.q('SELECT * FROM prime_equipment_draw_pool_v1985');
    const initial=await f.call('suit-core-box/config');assert.equal(initial.status,200);assert.equal(initial.body.shop.enabled,false);assert.equal(initial.body.openEnabled,false);
    assert.equal(initial.body.shop.unitPrice,1000000000);assert.equal(initial.body.maxPurchase,9007199);
    assert.equal((await enable(f)).status,200);
    const current=await f.call('suit-core-box/config');assert.equal(current.body.shop.enabled,true);
    assert.deepEqual(current.body.pool.entries.map(row=>[row.code,row.drawWeight]),SUIT_CORE_BOX_WEIGHTS.map(row=>[row.code,row.weight]));
    assert.ok(current.body.pool.entries.every(row=>!row.presentation.enabled&&!row.removable));
    const admin=await f.call('admin/prime-draw/status');assert.equal(admin.body.suit_core.name,'슈트코어 전용 상자');
    const forbidden=[...entries.slice(0,3),{poolKey:'INVENTORY_ITEM:SUIT_CORE_5',drawWeight:.2}];
    assert.equal((await enable(f,forbidden)).status,409);
    assert.equal((await enable(f,entries.slice(0,3))).status,400);
    assert.equal((await f.call('admin/prime-draw/pool',{kind:'suit_core',entries},'USER')).status,403);
    await f.db.prepare('UPDATE inventory_items SET is_active=0 WHERE code=?').bind('SUIT_CORE_4').run();
    assert.equal((await purchase(f,'inactive')).status,503,'missing grade must stop sales, never silently reweight');
    assert.deepEqual(await f.q('SELECT * FROM prime_equipment_draw_pool_v1985'),before);
  });
  test(`${dialect}: trillion-coin bulk purchase and 500-box atomic opening grant exactly once`,async t=>{
    const f=await fixture(t,dialect);await enable(f);await f.exec('UPDATE users SET coin=1000000000000 WHERE id=7');
    assert.equal((await purchase(f,'wrong-price',1,100000)).status,409);
    assert.equal((await purchase(f,'unsafe-amount',9007200)).status,400);
    assert.equal((await purchase(f,'fraction',1.5)).status,400);
    const bought=await purchase(f,'bulk-core-buy',1000);assert.equal(bought.status,200);assert.equal(bought.body.totalPrice,1000000000000);assert.equal(await wallet(f),0);assert.equal(Number(await f.quantity(CORE_BOX)),1000);
    assert.deepEqual(await purchase(f,'bulk-core-buy',1000),bought);assert.equal(Number(await f.quantity(CORE_BOX)),1000);
    assert.equal((await purchase(f,'insufficient',1)).status,409);
    assert.equal((await openCore(f,'too-large',501)).status,400);
    const opened=await openCore(f,'core-batch-500',500);assert.equal(opened.status,200);assert.equal(opened.body.kind,'suit_core');assert.equal(opened.body.remainingQuantity,500);
    assert.equal(opened.body.results.length,500);assert.equal(opened.body.aggregated.reduce((n,r)=>n+r.count,0),500);assert.deepEqual(opened.body.specialQueue,[]);
    assert.ok(opened.body.results.every(row=>row.type==='INVENTORY_ITEM'&&/^SUIT_CORE_[1-4]$/.test(row.item.code)));
    assert.deepEqual(await openCore(f,'core-batch-500',500),opened);assert.equal(Number(await f.quantity(CORE_BOX)),500);
    const rest=await openCore(f,'core-second-batch',500);assert.equal(rest.status,200);assert.equal(rest.body.remainingQuantity,0);
    let total=0;for(const row of SUIT_CORE_BOX_WEIGHTS)total+=Number(await f.quantity(row.code));assert.equal(total,1000);
    assert.equal(Number(await f.quantity(BOX)),12);assert.equal(Number(await f.quantity('EQUIPMENT_SUPPLY_BOX')),25);
    assert.deepEqual(await f.q('SELECT * FROM user_equipment_instances'),[]);assert.deepEqual(await f.q('SELECT * FROM avatar_user_ownership_v1'),[]);
    assert.equal((await f.q('SELECT COUNT(*) n FROM coin_logs'))[0].n,1);
    assert.equal((await f.call('equipment/prime-supply-box/open',{requestId:'core-batch-500',count:1})).status,409);
  });
  test(`${dialect}: failed purchased-box delivery rolls back coins, inventory and receipt; same ID retries`,async t=>{
    const f=await fixture(t,dialect);await enable(f);await f.exec('UPDATE users SET coin=10000000000 WHERE id=7');
    if(f.pg)await f.exec(`CREATE FUNCTION suppress_core_purchase() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.item_code='${CORE_BOX}' THEN RETURN NULL; END IF; RETURN NEW; END $$;CREATE TRIGGER suppress_core_purchase BEFORE INSERT ON cnine_user_inventory FOR EACH ROW EXECUTE FUNCTION suppress_core_purchase();`);
    else await f.exec(`CREATE TRIGGER suppress_core_purchase BEFORE INSERT ON cnine_user_inventory WHEN NEW.item_code='${CORE_BOX}' BEGIN SELECT RAISE(IGNORE); END;`);
    await assert.rejects(()=>purchase(f,'purchase-delivery-failure',10),/not.null|null value/i);
    assert.equal(await wallet(f),10000000000);assert.equal(Number(await f.quantity(CORE_BOX)),0);assert.deepEqual(await f.q('SELECT * FROM prime_draw_purchase_receipts_v1985'),[]);assert.deepEqual(await f.q('SELECT * FROM coin_logs'),[]);
    await f.exec(f.pg?'DROP TRIGGER suppress_core_purchase ON cnine_user_inventory':'DROP TRIGGER suppress_core_purchase');
    assert.equal((await purchase(f,'purchase-delivery-failure',10)).status,200);assert.equal(await wallet(f),0);assert.equal(Number(await f.quantity(CORE_BOX)),10);
  });
  test(`${dialect}: failed core reward rolls back box debit, grants and receipt`,async t=>{
    const f=await fixture(t,dialect);await enable(f,entries.map((row,i)=>({...row,drawWeight:i===0?100:0})));await f.exec(`INSERT INTO cnine_user_inventory(user_id,item_code,quantity) VALUES(7,'${CORE_BOX}',10)`);
    if(f.pg)await f.exec("CREATE FUNCTION suppress_core_reward() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.item_code='SUIT_CORE_1' THEN RETURN NULL; END IF; RETURN NEW; END $$;CREATE TRIGGER suppress_core_reward BEFORE INSERT ON cnine_user_inventory FOR EACH ROW EXECUTE FUNCTION suppress_core_reward();");
    else await f.exec("CREATE TRIGGER suppress_core_reward BEFORE INSERT ON cnine_user_inventory WHEN NEW.item_code='SUIT_CORE_1' BEGIN SELECT RAISE(IGNORE); END;");
    await assert.rejects(()=>openCore(f,'reward-failure',10),/not.null|null value/i);
    assert.equal(Number(await f.quantity(CORE_BOX)),10);assert.equal(Number(await f.quantity('SUIT_CORE_1')),0);assert.deepEqual(await f.q('SELECT * FROM prime_draw_open_receipts_v1985'),[]);assert.deepEqual(await f.q('SELECT * FROM inventory_logs'),[]);
    await f.exec(f.pg?'DROP TRIGGER suppress_core_reward ON cnine_user_inventory':'DROP TRIGGER suppress_core_reward');
    assert.equal((await openCore(f,'reward-failure',10)).status,200);assert.equal(Number(await f.quantity(CORE_BOX)),0);assert.equal(Number(await f.quantity('SUIT_CORE_1')),10);
  });
}
