import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import {PGlite} from '@electric-sql/pglite';
import {__postgresCompatTest} from '../functions/_postgres_d1_compat.js';
import {ensureRuntimeFoundation} from '../functions/_runtime_foundation.js';
import {SUPPORTER_BLUE_BEAST_TITLES_KEY,ensureSupporterBlueBeastTitles,readChallengerTotal,syncBlueBeastTitle} from '../functions/_supporter_blue_beast_titles.js';

const schema=`CREATE TABLE app_meta(key TEXT PRIMARY KEY,value TEXT,updated_at TEXT);
 CREATE TABLE character_titles(id INTEGER PRIMARY KEY AUTOINCREMENT,code TEXT UNIQUE,name TEXT,description TEXT,badge_text TEXT,image_url TEXT,pve_power INTEGER,unlock_type TEXT,unlock_config_json TEXT,style_preset TEXT,is_active INTEGER,is_public INTEGER,sort_order INTEGER);
 CREATE TABLE user_character_titles(user_id INTEGER,title_id INTEGER,source_type TEXT,source_id TEXT,PRIMARY KEY(user_id,title_id));
 CREATE TABLE pvp_season_settlements(id INTEGER PRIMARY KEY,status TEXT,completed_at TEXT);
 CREATE TABLE pvp_season_settlement_ranks(settlement_id INTEGER,user_id INTEGER,tier_id TEXT,final_rank INTEGER);`;
async function fixture(t,postgres){
 let DB,pg,sqlite,fail=()=>false;
 if(postgres){
  pg=new PGlite();await pg.exec("CREATE FUNCTION sqlite_now() RETURNS text LANGUAGE SQL STABLE AS $$SELECT to_char(timezone('UTC',CURRENT_TIMESTAMP),'YYYY-MM-DD HH24:MI:SS')$$;");
  await pg.exec(schema.replaceAll('INTEGER PRIMARY KEY AUTOINCREMENT','BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY'));
  DB=new __postgresCompatTest.PostgresD1Database({async query(input){
   const sql=typeof input==='string'?input:input.text,args=typeof input==='string'?[]:input.values||[];
   if(fail(sql,args))throw Error('INJECTED_FAILURE');const r=await pg.query(sql,args);return {...r,rowCount:r.affectedRows??r.rows.length};
  }});
 }else{
  sqlite=new DatabaseSync(':memory:');sqlite.exec(schema);
  const prepare=(sql,args=[])=>({bind(...v){return prepare(sql,v)},async first(){return sqlite.prepare(sql).get(...args)||null},
   async all(){return {results:sqlite.prepare(sql).all(...args)}},async run(){
    if(fail(sql,args))throw Error('INJECTED_FAILURE');const r=sqlite.prepare(sql).run(...args);return {meta:{changes:Number(r.changes)}};
   }});
  DB={prepare,async batch(rows){sqlite.exec('BEGIN');try{const results=[];for(const row of rows)results.push(await row.run());sqlite.exec('COMMIT');return results;}catch(e){sqlite.exec('ROLLBACK');throw e;}}};
 }
 t.after(()=>pg?pg.close():sqlite.close());
 const env={DB},p=(sql,...args)=>DB.prepare(sql).bind(...args);
 async function history(count=10){
  // Alternate Challenger and missing seasons: this is cumulative, not a streak.
  for(let i=1;i<=count*2;i++){
   await p("INSERT INTO pvp_season_settlements VALUES(?,'COMPLETED','2026-09-01')",i).run();
   if(i%2===0)await p("INSERT INTO pvp_season_settlement_ranks VALUES(?,7,'challenger',20)",i).run();
  }
 }
 return {env,DB,p,history,fail:fn=>{fail=fn}};
}

for(const postgres of [false,true]){
 const label=postgres?'PostgreSQL':'SQLite';
 test(`${label}: one-time catalogue upgrade is atomic and preserves subsequent CMS settings`,async t=>{
  const f=await fixture(t,postgres);
  await f.p("INSERT INTO app_meta(key,value) VALUES('older-title-seed','1')").run();
  const upgrade=()=>ensureRuntimeFoundation(f.env,Symbol.for('test-supporter-title-upgrade'),['older-title-seed',SUPPORTER_BLUE_BEAST_TITLES_KEY],()=>ensureSupporterBlueBeastTitles(f.env));
  f.fail(sql=>sql.startsWith('INSERT INTO app_meta'));
  await assert.rejects(upgrade,/INJECTED_FAILURE/);
  assert.equal(Number((await f.p('SELECT COUNT(*) n FROM character_titles').first()).n),0);
  f.fail(()=>false);await upgrade();
  const rows=(await f.p('SELECT * FROM character_titles ORDER BY sort_order').all()).results;
  assert.deepEqual(rows.map(r=>[r.name,Number(r.pve_power),r.unlock_type]),[['서포터',75000,'MANUAL'],['푸른 맹수',70000,'CHALLENGER_TOTAL']]);
  assert.equal(rows[0].description,'운영에 도움을 주신 감사 칭호');
  assert.deepEqual(JSON.parse(rows[1].unlock_config_json),{count:10});
  assert.equal(Number((await f.p('SELECT COUNT(*) n FROM user_character_titles').first()).n),0,'catalogue creation grants neither title');
  await f.p("UPDATE character_titles SET pve_power=72000,unlock_config_json='{"+'"count":12'+"}' WHERE code='BLUE_BEAST'").run();
  await ensureSupporterBlueBeastTitles(f.env);
  assert.equal(Number((await f.p("SELECT pve_power FROM character_titles WHERE code='BLUE_BEAST'").first()).pve_power),72000);
  assert.equal(Number((await f.p('SELECT COUNT(*) n FROM character_titles').first()).n),2);
 });
 test(`${label}: 9/10 boundary, nonconsecutive records, recorded tiers and completed settlements only`,async t=>{
  const f=await fixture(t,postgres);await ensureSupporterBlueBeastTitles(f.env);await f.history(9);
  await f.p("INSERT INTO pvp_season_settlements VALUES(21,'PROCESSING','2026-09-01'),(22,'COMPLETED',NULL),(23,'COMPLETED','2026-09-01'),(24,'COMPLETED','2026-09-01')").run();
  await f.p("INSERT INTO pvp_season_settlement_ranks VALUES(21,7,'challenger',1),(22,7,'challenger',1),(23,7,'grandmaster',10),(24,7,'challenger',21),(2,8,'challenger',1),(2,7,'challenger',20)").run();
  assert.equal(await readChallengerTotal(f.env,7),9,'duplicates, pending results and historical non-Challenger tiers do not add a season');
  assert.deepEqual(await syncBlueBeastTitle(f.env,7),{granted:[],progress:{BLUE_BEAST:{owned:9,goal:10,complete:false}}});
  await f.p("INSERT INTO pvp_season_settlements VALUES(25,'COMPLETED','2026-10-01')").run();
  await f.p("INSERT INTO pvp_season_settlement_ranks VALUES(25,7,'challenger',1)").run();
  const result=await syncBlueBeastTitle(f.env,7);assert.equal(result.granted.length,1);assert.equal(result.progress.BLUE_BEAST.owned,10);
  assert.deepEqual(await syncBlueBeastTitle(f.env,7),{granted:[],progress:{}});
  assert.equal((await syncBlueBeastTitle(f.env,8)).granted.length,0);
  const owned=(await f.p('SELECT u.*,t.code FROM user_character_titles u JOIN character_titles t ON t.id=u.title_id').all()).results;
  assert.equal(owned.length,1);assert.equal(owned[0].code,'BLUE_BEAST');assert.equal(owned[0].source_type,'ACHIEVEMENT');assert.equal(Number(owned[0].user_id),7);
 });
 test(`${label}: grant retries, hidden/manual policy and CMS count changes stay safe`,async t=>{
  const f=await fixture(t,postgres);await ensureSupporterBlueBeastTitles(f.env);await f.history();
  f.fail(sql=>sql.includes('INSERT')&&sql.includes('user_character_titles'));
  await assert.rejects(()=>syncBlueBeastTitle(f.env,7),/INJECTED_FAILURE/);f.fail(()=>false);
  const results=await Promise.all([syncBlueBeastTitle(f.env,7),syncBlueBeastTitle(f.env,7)]);
  assert.equal(results.flatMap(r=>r.granted).length,1);
  await f.p('DELETE FROM user_character_titles').run();
  await f.p('UPDATE character_titles SET unlock_config_json=? WHERE code=?',JSON.stringify({count:11}),'BLUE_BEAST').run();
  assert.equal((await syncBlueBeastTitle(f.env,7)).progress.BLUE_BEAST.complete,false);
  await f.p("UPDATE character_titles SET is_public=0 WHERE code='BLUE_BEAST'").run();
  assert.deepEqual(await syncBlueBeastTitle(f.env,7),{granted:[],progress:{}});
  await f.p("UPDATE character_titles SET is_public=1,unlock_config_json='{}' WHERE code='BLUE_BEAST'").run();
  const prepare=f.DB.prepare.bind(f.DB);let changed=false;
  f.DB.prepare=sql=>{
   const statement=prepare(sql);if(!sql.includes('INSERT')||!sql.includes('user_character_titles'))return statement;
   const bind=statement.bind.bind(statement);statement.bind=(...args)=>{const bound=bind(...args),run=bound.run.bind(bound);bound.run=async()=>{
    if(!changed){changed=true;await prepare("UPDATE character_titles SET unlock_type='MANUAL' WHERE code='BLUE_BEAST'").run();}return run();};return bound};return statement;
  };
  assert.equal((await syncBlueBeastTitle(f.env,7)).granted.length,0);
  assert.equal(Number((await f.p('SELECT COUNT(*) n FROM user_character_titles').first()).n),0);
 });
}

test('catalogue upgrade, authenticated title sync, shared styles and CMS are connected to live loaders',()=>{
 const read=p=>readFileSync(new URL('../'+p,import.meta.url),'utf8');
 const equipment=read('functions/_equipment.js');
 assert.match(equipment,/PREDICTION_TITLE_KEY,SUPPORTER_BLUE_BEAST_TITLES_KEY/);
 assert.match(equipment,/await ensureSupporterBlueBeastTitles\(env\)/);
 assert.match(equipment,/syncBlueBeastTitle\(env,user.id\)/);
 assert.match(equipment,/titlePvp=titlePve/);
 for(const path of ['functions/_equipment.js','admin/equipment-admin-v1278.js','js/equipment-v1274.js','js/character-loadout-v2.js']){
  for(const key of ['SUPPORTER_VIP','BLUE_BEAST','CHALLENGER_TOTAL'])assert.ok(read(path).includes(key),path+': '+key);
 }
 for(const path of ['index.html','admin/index.html','js/app.js'])assert.ok(read(path).includes('supporterBlueBeast=20261003'),path);
 const css=read('css/achievement-titles-20260927.css');
 assert.match(css,/prefers-reduced-motion:reduce/);assert.match(css,/supporter-title-sparks/);
 assert.match(css,/supporter-vip-v1.webp/);assert.match(css,/blue-beast-v1.webp/);
});
