import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {PGlite} from '@electric-sql/pglite';
import {SX_ITEM,OPERATION_KEY,registerSxEquipment,verifySxEquipment} from '../scripts/ops/sx-equipment-cms-20261007.mjs';
const asset={url:'https://cnine-card.pages.dev'+SX_ITEM.image,status:200,sha256:SX_ITEM.sha256};
async function setup(){
  const db=new PGlite();
  await db.exec(`CREATE TABLE character_equipment_items(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,code TEXT NOT NULL UNIQUE,name TEXT NOT NULL,slot TEXT NOT NULL,subtype TEXT NOT NULL DEFAULT '',rarity TEXT NOT NULL DEFAULT 'NORMAL',image_url TEXT NOT NULL DEFAULT '',description TEXT NOT NULL DEFAULT '',total_power BIGINT NOT NULL DEFAULT 0,pve_power BIGINT NOT NULL DEFAULT 0,pvp_power BIGINT NOT NULL DEFAULT 0,is_active BIGINT NOT NULL DEFAULT 1,is_public BIGINT NOT NULL DEFAULT 1,sort_order BIGINT NOT NULL DEFAULT 0,supply_enabled BIGINT NOT NULL DEFAULT 1,supply_weight DOUBLE PRECISION NOT NULL DEFAULT 1);
    CREATE TABLE app_meta(key TEXT PRIMARY KEY,value TEXT NOT NULL,updated_at TEXT);
    CREATE TABLE users(id BIGINT PRIMARY KEY,role TEXT,status TEXT);
    CREATE TABLE admin_logs(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,admin_id BIGINT,action_type TEXT,target_type TEXT,target_id TEXT,before_data TEXT,after_data TEXT,created_at TEXT);
    INSERT INTO users VALUES(1,'OWNER','ACTIVE');
    INSERT INTO character_equipment_items(code,name,slot,subtype,pve_power,total_power,sort_order) VALUES('BATTLE_SUIT_X_BODY','X-BODY','BATTLE_SUIT','BATTLE_SUIT',50000000,50000000,70);`);
  return db;
}
test('CMS image is the exact approved standing original',async()=>{
  const image=await readFile(new URL('..'+SX_ITEM.image,import.meta.url));
  assert.equal(createHash('sha256').update(image).digest('hex'),SX_ITEM.sha256);
});
test('SX registers once in CMS with preserved existing equipment and later owner settings',async()=>{
  const db=await setup();try{
    const before=(await db.query('SELECT * FROM character_equipment_items')).rows;
    const first=await registerSxEquipment(db,asset);
    assert.equal(first.alreadyRegistered,false);assert.equal(first.item.name,'SX슈트');
    assert.equal(first.item.slot,'BATTLE_SUIT');assert.equal(Number(first.item.pvp_power),0);
    assert.equal(Number(first.item.pve_power),0);assert.equal(Number(first.item.supply_enabled),0);
    const verified=await verifySxEquipment(db);assert.equal(verified.cmsVisible,true);
    assert.deepEqual((await db.query('SELECT * FROM character_equipment_items WHERE code<>$1',[SX_ITEM.code])).rows,before);
    await db.query("UPDATE character_equipment_items SET pve_power=1234,total_power=1234,rarity='MYTHIC',is_active=1,description='OWNER edit' WHERE code=$1",[SX_ITEM.code]);
    const retry=await registerSxEquipment(db,asset);
    assert.equal(retry.alreadyRegistered,true);assert.equal(Number(retry.item.pve_power),1234);
    assert.equal(retry.item.rarity,'MYTHIC');assert.equal(retry.item.description,'OWNER edit');
    assert.equal((await db.query('SELECT * FROM admin_logs')).rows.length,1);
    assert.equal((await db.query('SELECT * FROM character_equipment_items')).rows.length,2);
  }finally{await db.close();}
});
test('duplicate identity and wrong image proof block registration without overwriting',async()=>{
  const db=await setup();try{
    await assert.rejects(registerSxEquipment(db,{...asset,sha256:'wrong'}),/image mismatch/);
    await db.query("INSERT INTO character_equipment_items(code,name,slot) VALUES('OWNER_SX','SX슈트','BATTLE_SUIT')");
    await assert.rejects(registerSxEquipment(db,asset),/Matching SX/);
    assert.equal((await db.query('SELECT * FROM app_meta')).rows.length,0);
    assert.equal((await db.query('SELECT * FROM admin_logs')).rows.length,0);
  }finally{await db.close();}
});
test('receipt failure rolls back both equipment registration and audit; retry is safe',async()=>{
  const db=await setup();try{
    await db.exec("ALTER TABLE app_meta ADD CONSTRAINT fail_sx CHECK(key NOT LIKE 'ops:sx-%')");
    await assert.rejects(registerSxEquipment(db,asset));
    assert.equal((await db.query('SELECT * FROM character_equipment_items WHERE code=$1',[SX_ITEM.code])).rows.length,0);
    assert.equal((await db.query('SELECT * FROM admin_logs')).rows.length,0);
    await db.exec('ALTER TABLE app_meta DROP CONSTRAINT fail_sx');
    await registerSxEquipment(db,asset);
    assert.equal((await db.query('SELECT * FROM app_meta WHERE key=$1',[OPERATION_KEY])).rows.length,1);
  }finally{await db.close();}
});
