import test from 'node:test';
import assert from 'node:assert/strict';
import {PGlite} from '@electric-sql/pglite';
import {SX_ITEM,registerSxEquipment} from '../scripts/ops/sx-equipment-cms-20261007.mjs';
import {OPERATION_KEY,RUNTIME_VERSION,activateSxLive,verifySxLive} from '../scripts/ops/sx-suit-live-20261007.mjs';
const proof=()=>({origin:'https://cnine-card.pages.dev',runtimeVersion:RUNTIME_VERSION,runtimeEnabled:true,attackSpeedMultiplier:2,sourceSha256:SX_ITEM.sha256,bundleMatchesCommittedBuild:true,mainLoaderCacheVersion:'sx=20261007-2x-v1',commit:'a'.repeat(40),checkedAt:new Date().toISOString()});
async function setup(){
  const db=new PGlite();
  await db.exec(`CREATE TABLE character_equipment_items(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,code TEXT NOT NULL UNIQUE,name TEXT NOT NULL,slot TEXT NOT NULL,subtype TEXT NOT NULL DEFAULT '',rarity TEXT NOT NULL DEFAULT 'NORMAL',image_url TEXT NOT NULL DEFAULT '',description TEXT NOT NULL DEFAULT '',total_power BIGINT NOT NULL DEFAULT 0,pve_power BIGINT NOT NULL DEFAULT 0,pvp_power BIGINT NOT NULL DEFAULT 0,is_active BIGINT NOT NULL DEFAULT 1,is_public BIGINT NOT NULL DEFAULT 1,sort_order BIGINT NOT NULL DEFAULT 0,supply_enabled BIGINT NOT NULL DEFAULT 1,supply_weight DOUBLE PRECISION NOT NULL DEFAULT 1);
    CREATE TABLE app_meta(key TEXT PRIMARY KEY,value TEXT NOT NULL,updated_at TEXT);
    CREATE TABLE users(id BIGINT PRIMARY KEY,role TEXT,status TEXT);
    CREATE TABLE admin_logs(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,admin_id BIGINT,action_type TEXT,target_type TEXT,target_id TEXT,before_data TEXT,after_data TEXT,created_at TEXT);
    INSERT INTO users VALUES(1,'OWNER','ACTIVE');
    INSERT INTO character_equipment_items(code,name,slot,subtype,pve_power,total_power,sort_order) VALUES('BATTLE_SUIT_X_BODY','X-BODY','BATTLE_SUIT','BATTLE_SUIT',50000000,50000000,70);`);
  await registerSxEquipment(db,{url:proof().origin+SX_ITEM.image,status:200,sha256:SX_ITEM.sha256});return db;
}
test('activate the registered SX once using X baseline; keep supply, rarity and later CMS edits',async()=>{
 const db=await setup();try{
  const first=await activateSxLive(db,proof());assert.equal(first.alreadyActivated,false);
  for(const [key,n] of Object.entries({pve_power:50000000,total_power:50000000,pvp_power:0,is_active:1,is_public:1,supply_enabled:0,supply_weight:0}))assert.equal(Number(first.item[key]),n,key);
  assert.equal(first.item.rarity,'NORMAL');assert.equal((await verifySxLive(db)).verified,true);
  await db.query("UPDATE character_equipment_items SET pve_power=777,total_power=777,is_active=0,description='OWNER change' WHERE code=$1",[SX_ITEM.code]);
  const retry=await activateSxLive(db,proof());assert.equal(retry.alreadyActivated,true);assert.equal(Number(retry.item.pve_power),777);assert.equal(Number(retry.item.is_active),0);assert.equal(retry.item.description,'OWNER change');
  assert.equal((await db.query("SELECT * FROM admin_logs WHERE action_type='EQUIPMENT_UPDATE'")).rows.length,1);
 }finally{await db.close();}
});
test('respect pre-existing nonzero SX power and description when first connecting',async()=>{
 const db=await setup();try{
  await db.query("UPDATE character_equipment_items SET pve_power=12345,total_power=12345,description='CMS configured' WHERE code=$1",[SX_ITEM.code]);
  const r=await activateSxLive(db,proof());assert.equal(Number(r.item.pve_power),12345);assert.equal(r.item.description,'CMS configured');
 }finally{await db.close();}
});
test('unpublished runtime and failed receipt never leave a partial activation',async()=>{
 const db=await setup();try{
  await assert.rejects(activateSxLive(db,{...proof(),runtimeEnabled:false}));
  await assert.rejects(activateSxLive(db,{...proof(),checkedAt:'2000-01-01'}),/Fresh verified/);
  await db.exec("ALTER TABLE app_meta ADD CONSTRAINT fail_live CHECK(key NOT LIKE 'ops:sx-suit-live:%')");
  await assert.rejects(activateSxLive(db,proof()));
  const item=(await db.query('SELECT * FROM character_equipment_items WHERE code=$1',[SX_ITEM.code])).rows[0];assert.equal(Number(item.is_active),0);assert.equal(Number(item.pve_power),0);
  assert.equal((await db.query("SELECT * FROM admin_logs WHERE action_type='EQUIPMENT_UPDATE'")).rows.length,0);
  await db.exec('ALTER TABLE app_meta DROP CONSTRAINT fail_live');await activateSxLive(db,proof());
  assert.equal((await db.query('SELECT * FROM app_meta WHERE key=$1',[OPERATION_KEY])).rows.length,1);
 }finally{await db.close();}
});
