import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {PGlite} from '@electric-sql/pglite';
import {restartTerritoryRound,RECEIPT_KEY} from '../scripts/ops/territory-clan-rebalance-20260923.mjs';
const NOW=Date.parse('2026-09-23T14:40:00Z');
async function fixture(t){
  const db=new PGlite();t.after(()=>db.close());
  const client={async query(sql,values=[]){const r=await db.query(sql,values);return {...r,rowCount:r.affectedRows??r.rows.length}}};
  await db.exec(`
    CREATE TABLE app_meta(key TEXT PRIMARY KEY,value TEXT);
    CREATE TABLE users(id BIGINT PRIMARY KEY,role TEXT,status TEXT,nickname TEXT,coin BIGINT);
    INSERT INTO users VALUES(1,'OWNER','ACTIVE','OWNER',123456789);
    CREATE TABLE clan_seasons(id BIGINT,season_no INTEGER,phase TEXT);
    INSERT INTO clan_seasons VALUES(5,2,'ACTIVE');
    CREATE TABLE clan_organizations(id BIGINT,name TEXT,mark_key TEXT,primary_color TEXT,accent_color TEXT,slogan TEXT);
    CREATE TABLE clan_season_teams(season_id BIGINT,clan_id BIGINT,master_user_id BIGINT,score INTEGER,wins INTEGER,losses INTEGER,draft_position INTEGER);
    CREATE TABLE clan_wars(season_id BIGINT,clan_a_id BIGINT,clan_b_id BIGINT,score_a INTEGER,score_b INTEGER,status TEXT,round_no INTEGER);
    CREATE TABLE clan_members(season_id BIGINT,clan_id BIGINT,user_id BIGINT);
    CREATE TABLE territory_war_clans(round_id BIGINT,clan_id BIGINT,side TEXT,position INTEGER,name TEXT,mark_key TEXT,primary_color TEXT,PRIMARY KEY(round_id,clan_id),UNIQUE(round_id,side,position));
    CREATE TABLE territory_war_v3_rounds(id BIGINT PRIMARY KEY,status TEXT,warfare_version INTEGER,clan_season_id BIGINT,settled_at TEXT,current_front_id BIGINT,current_front_index INTEGER,version INTEGER,truce_ends_at TEXT,truce_started_by BIGINT,truce_duration_minutes INTEGER,starts_at TEXT,ends_at TEXT,a_total_damage BIGINT,b_total_damage BIGINT,a_front_wins INTEGER,b_front_wins INTEGER,a_counter_gauge INTEGER,b_counter_gauge INTEGER,a_operation TEXT,b_operation TEXT,a_operation_ends_at TEXT,b_operation_ends_at TEXT,a_capture_streak INTEGER,b_capture_streak INTEGER,skill_action_token TEXT,clan_opened_at TEXT,updated_at TEXT);
    CREATE TABLE territory_war_v3_fronts(id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,round_id BIGINT,sequence INTEGER,node_index INTEGER,node_code TEXT,node_name TEXT,node_type TEXT,status TEXT,a_hp BIGINT,b_hp BIGINT,a_max_hp BIGINT,b_max_hp BIGINT,revisit_count INTEGER,version INTEGER DEFAULT 1,resolved_at TEXT,updated_at TEXT,UNIQUE(round_id,sequence));
    INSERT INTO territory_war_v3_fronts(id,round_id,sequence,node_index,status,a_hp,b_hp,a_max_hp,b_max_hp) VALUES(466,58,1,4,'ACTIVE',830000,495000,2500000,2500000);
    CREATE TABLE territory_war_v3_users(round_id BIGINT,user_id BIGINT,clan_id BIGINT,mandatory_clan INTEGER,side TEXT,status TEXT,formation_power BIGINT,attacks INTEGER,damage BIGINT,energy INTEGER,last_recharged_at TEXT,updated_at TEXT,PRIMARY KEY(round_id,user_id));
    CREATE TABLE territory_war_v3_actions(round_id BIGINT,status TEXT,damage BIGINT,updated_at TEXT);
    INSERT INTO territory_war_v3_actions VALUES(58,'COMPLETED',10000,'2026-09-23T14:21:00Z');
    INSERT INTO territory_war_v3_actions VALUES(NULL,'PENDING',0,'2026-09-22T14:21:00Z');
    CREATE TABLE territory_war_v3_rewards(round_id BIGINT);
    CREATE TABLE territory_war_v3_front_results(round_id BIGINT);
    CREATE TABLE admin_logs(id BIGINT GENERATED ALWAYS AS IDENTITY,admin_id BIGINT,action_type TEXT,target_type TEXT,target_id TEXT,before_data TEXT,after_data TEXT);
    CREATE TABLE territory_war_v3_notices(round_id BIGINT,type TEXT,title TEXT,message TEXT,payload_json TEXT);
  `);
  for(const name of ['operation_votes','commander_overrides','operation_uses','last_defense_uses','mass_assault_uses','mass_assaults'])await db.exec(`CREATE TABLE territory_war_v3_${name}(round_id BIGINT,payload TEXT); INSERT INTO territory_war_v3_${name} VALUES(58,'preserve in archive')`);
  await db.exec('CREATE TABLE territory_war_skill_cooldowns(round_id BIGINT)');
  await client.query("INSERT INTO territory_war_v3_rounds(id,status,warfare_version,clan_season_id,current_front_id,current_front_index,version,truce_ends_at) VALUES(58,'ACTIVE',4,5,466,4,4106,$1)",[new Date(NOW+30*60000).toISOString()]);
  await client.query('INSERT INTO app_meta VALUES($1,$2)',['territory_war_settings_v3',JSON.stringify({mode:'ON',roundMinutes:1200,preparationMinutes:3,baseSiegeHp:5000000,energyMax:15})]);
  const ids=[1,7,3,8,6,4,2,5],names=['DK','FM','T1','DC','롯데','한화','삼성','LG'],scores=[12,9,9,9,3,3,3,0],combat=[6476,6691,6690,6665,5791,5716,5466,4851],counts=[21,22,20,20,19,19,19,16],positions={A:0,B:0};
  let userId=10;
  for(let i=0;i<8;i++){
    const id=ids[i],side=[1,7,2,5].includes(id)?'A':'B';
    await client.query('INSERT INTO clan_organizations(id,name,mark_key,primary_color) VALUES($1,$2,$2,$3)',[id,names[i],'#123456']);
    await client.query('INSERT INTO clan_season_teams VALUES(5,$1,NULL,$2,0,0,$3)',[id,scores[i],i]);
    await client.query("INSERT INTO clan_wars VALUES(5,$1,999,$2,0,'COMPLETED',1)",[id,combat[i]]);
    await client.query('INSERT INTO territory_war_clans VALUES(58,$1,$2,$3,$4,$4,$5)',[id,side,positions[side]++,names[i],'#123456']);
    for(let j=0;j<counts[i];j++){
      await client.query('INSERT INTO clan_members VALUES(5,$1,$2)',[id,userId]);
      await client.query("INSERT INTO territory_war_v3_users(round_id,user_id,clan_id,mandatory_clan,side,status,formation_power,attacks,damage,energy) VALUES(58,$1,$2,1,$3,'ACTIVE',1500000,5,10000,0)",[userId++,id,side]);
    }
  }
  for(let i=0;i<18;i++)await client.query("INSERT INTO territory_war_v3_users(round_id,user_id,mandatory_clan,side,status,formation_power,attacks,damage,energy) VALUES(58,$1,0,$2,'ACTIVE',1400000,3,5000,0)",[userId++,i%2?'A':'B']);
  return {client,q:async(sql,values=[])=>(await client.query(sql,values)).rows};
}
test('dry-run rolls back; restart keeps contributions and wallets; receipt makes retries inert',async t=>{
  const f=await fixture(t),before=await f.q('SELECT * FROM territory_war_v3_rounds');
  const dry=await restartTerritoryRound(f.client,{dryRun:true,expectedVersion:4106,now:NOW});
  assert.equal(dry.dryRun,true);assert.deepEqual(await f.q('SELECT * FROM territory_war_v3_rounds'),before);
  assert.equal((await f.q('SELECT COUNT(*) n FROM territory_war_v3_fronts'))[0].n,1);
  const result=await restartTerritoryRound(f.client,{expectedVersion:4106,now:NOW}),receipt=result.receipt;
  assert.equal(receipt.metrics.aCount,87);assert.equal(receipt.metrics.bCount,87);
  assert.equal(receipt.startsAt,new Date(NOW+180000).toISOString());
  assert.equal(Date.parse(receipt.endsAt)-Date.parse(receipt.startsAt),1200*60000);
  assert.equal((await f.q('SELECT coin FROM users WHERE id=1'))[0].coin,123456789);
  assert.equal((await f.q('SELECT SUM(attacks) n FROM territory_war_v3_users'))[0].n,156*5+18*3);
  assert.equal((await f.q('SELECT COUNT(*) n FROM territory_war_v3_actions'))[0].n,2);
  assert.equal((await f.q('SELECT COUNT(*) n FROM territory_war_v3_rewards'))[0].n,0);
  assert.equal((await f.q('SELECT status FROM territory_war_v3_fronts WHERE id=466'))[0].status,'CANCELLED');
  assert.equal((await f.q('SELECT a_hp FROM territory_war_v3_fronts WHERE id=$1',[receipt.newFrontId]))[0].a_hp,5000000);
  const source=readFileSync(new URL('../functions/_territory_war.js',import.meta.url),'utf8');
  assert.match(source,/SELECT COUNT\(\*\) cnt FROM territory_war_v3_fronts WHERE round_id=\? AND node_index=\? AND status<>'CANCELLED'/);
  assert.equal((await f.q("SELECT COUNT(*) n FROM territory_war_v3_fronts WHERE round_id=58 AND node_index=4 AND status<>'CANCELLED'"))[0].n,1);
  const archive=JSON.parse((await f.q('SELECT value FROM app_meta WHERE key=$1',[RECEIPT_KEY+':before']))[0].value);
  assert.equal(archive.participants.length,174);
  assert.equal(archive.resetBefore.territory_war_v3_operation_votes.length,1);
  const replay=await restartTerritoryRound(f.client,{expectedVersion:4106,now:NOW+999999});
  assert.equal(replay.replayed,true);assert.deepEqual(replay.receipt,receipt);
  assert.equal((await f.q('SELECT COUNT(*) n FROM admin_logs'))[0].n,1);
});
test('stale round, active attack and late failure cannot partially reform a round',async t=>{
  const f=await fixture(t);
  await assert.rejects(restartTerritoryRound(f.client,{expectedVersion:4105,now:NOW}),/Round changed/);
  await f.client.query("INSERT INTO territory_war_v3_actions VALUES(58,'PENDING',0,'2026-09-23T14:40:00Z')");
  await assert.rejects(restartTerritoryRound(f.client,{expectedVersion:4106,now:NOW}),/in flight/);
  await f.client.query("DELETE FROM territory_war_v3_actions WHERE status='PENDING'");
  const before=await f.q('SELECT * FROM territory_war_clans ORDER BY clan_id');
  const failing={query(sql,args){if(sql.startsWith('INSERT INTO admin_logs'))throw Error('injected audit failure');return f.client.query(sql,args)}};
  await assert.rejects(restartTerritoryRound(failing,{expectedVersion:4106,now:NOW}),/injected audit failure/);
  assert.deepEqual(await f.q('SELECT * FROM territory_war_clans ORDER BY clan_id'),before);
  assert.equal((await f.q('SELECT status FROM territory_war_v3_rounds'))[0].status,'ACTIVE');
  assert.equal((await f.q('SELECT COUNT(*) n FROM app_meta WHERE key=$1',[RECEIPT_KEY]))[0].n,0);
  assert.equal((await f.q('SELECT COUNT(*) n FROM territory_war_v3_fronts'))[0].n,1);
});
