import test from 'node:test';
import assert from 'node:assert/strict';
import {PGlite} from '@electric-sql/pglite';
import {grant,verify,CARDS,TARGET} from '../scripts/ops/tmoney-zenith-plus13-20261002.mjs';

async function fixture(t){
 const db=new PGlite();t.after(()=>db.close());
 await db.exec(`CREATE TABLE users(id BIGINT PRIMARY KEY,nickname TEXT,role TEXT,status TEXT,coin BIGINT DEFAULT 123,card_shards BIGINT DEFAULT 456,magic_crystals BIGINT DEFAULT 789);
 INSERT INTO users(id,nickname,role,status) VALUES(1,'관리자','OWNER','ACTIVE'),(5147,'T-Money™','USER','ACTIVE'),(66,'다른계정','USER','ACTIVE');
 CREATE TABLE user_second_verifications(user_id BIGINT,provider TEXT,provider_user_id TEXT);INSERT INTO user_second_verifications VALUES(5147,'PLAYDK','9c5d467b');
 CREATE TABLE members(id BIGINT PRIMARY KEY,name TEXT,is_active INTEGER);
 CREATE TABLE cards_effective_v1210(id TEXT PRIMARY KEY,title TEXT,rarity TEXT,member_id BIGINT,is_active INTEGER DEFAULT 1,card_status TEXT DEFAULT 'PUBLIC');
 CREATE TABLE user_cards(user_id BIGINT,card_id TEXT,quantity BIGINT,breakthrough_level BIGINT,breakthrough_fail_count BIGINT,first_obtained_at TEXT,last_obtained_at TEXT,unique_level BIGINT DEFAULT 7,PRIMARY KEY(user_id,card_id));
 CREATE TABLE app_meta(key TEXT PRIMARY KEY,value TEXT,updated_at TEXT);
 CREATE TABLE admin_logs(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,admin_id BIGINT,action_type TEXT,target_type TEXT,target_id TEXT,before_data TEXT,after_data TEXT,created_at TEXT);
 INSERT INTO user_cards VALUES(5147,'unrelated',4,8,2,'first-other','last-other',9),(66,'unrelated',8,4,3,'other-user','other-user',6);`);
 for(const [index,card] of CARDS.entries()){
  await db.query('INSERT INTO members VALUES($1,$2,1)',[index+1,card.name]);
  await db.query('INSERT INTO cards_effective_v1210(id,title,rarity,member_id) VALUES($1,$2,$3,$4)',[card.id,card.title,card.grade,index+1]);
  await db.query("INSERT INTO user_cards VALUES(5147,$1,$2,$3,$4,'original-first','original-last',7)",[card.id,index?5:1,index?10:11,index?0:3]);
 }
 const snapshot=async()=>{const out={};for(const table of ['users','user_cards','admin_logs','app_meta'])out[table]=(await db.query('SELECT * FROM '+table+' ORDER BY 1,2')).rows;return out;};
 return {db,snapshot,apply:options=>grant(db,{mode:'UPGRADE_ONLY',...options})};
}

test('both cards reach +13 while quantities, timestamps, unique evolution, other cards and wallet remain unchanged; preview and retry are idempotent',async t=>{
 const f=await fixture(t),before=await f.snapshot();assert.equal((await f.apply({dryRun:true})).dryRun,true);assert.deepEqual(await f.snapshot(),before);
 const applied=await f.apply(),after=await f.snapshot();assert.deepEqual(applied.receipt.cards.map(row=>[row.quantityBefore,row.quantityAfter,row.levelAfter,row.failCountAfter]),[[1,1,13,0],[5,5,13,0]]);
 assert.deepEqual(after.users,before.users);
 assert.deepEqual(after.user_cards,before.user_cards.map(row=>Number(row.user_id)===TARGET.id&&CARDS.some(card=>card.id===row.card_id)?{...row,breakthrough_level:13,breakthrough_fail_count:0}:row));
 assert.equal((await verify(f.db)).verified,true);assert.equal((await f.apply()).replayed,true);assert.deepEqual(await f.snapshot(),after);
});

test('late audit failure rolls both upgrades back; lost commit response retries without changing quantities',async t=>{
 const f=await fixture(t);await f.db.exec('ALTER TABLE admin_logs ADD CONSTRAINT forced_failure CHECK(false)');const before=await f.snapshot();
 await assert.rejects(f.apply(),/forced_failure/);assert.deepEqual(await f.snapshot(),before);await f.db.exec('ALTER TABLE admin_logs DROP CONSTRAINT forced_failure');
 const lost={async query(sql,args){const result=await f.db.query(sql,args);if(sql==='COMMIT')throw Error('lost commit acknowledgement');return result;}};
 await assert.rejects(grant(lost,{mode:'UPGRADE_ONLY'}),/lost commit acknowledgement/);const applied=await f.snapshot();assert.equal((await f.apply()).replayed,true);assert.deepEqual(await f.snapshot(),applied);
});

test('extra-copy mode and changed identity or target card block the operation without writes',async t=>{
 const f=await fixture(t),before=await f.snapshot();await assert.rejects(f.apply({mode:'ADD_ONE'}),/preserve existing quantities/);assert.deepEqual(await f.snapshot(),before);
 await f.db.query("UPDATE user_second_verifications SET provider_user_id='wrong' WHERE user_id=5147");await assert.rejects(f.apply(),/Reviewed PLAYDK/);assert.deepEqual(await f.snapshot(),before);
 await f.db.query("UPDATE user_second_verifications SET provider_user_id='9c5d467b' WHERE user_id=5147");await f.db.query("UPDATE cards_effective_v1210 SET rarity='FUR' WHERE id=$1",[CARDS[0].id]);
 await assert.rejects(f.apply(),/Reviewed target card/);assert.deepEqual(await f.snapshot(),before);
});
