import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {validateWorkshopExtension} from '../shared/workshop-extension-contract-v1.mjs';
import {__workshopBattleSuitTest, __workshopCraftTest} from '../functions/_workshop.js';
import {jointFixture} from './helpers/joint-db.mjs';

const draft=()=>({category:'SUIT_CORE_SYNTHESIS',code:'CORE_QA',name:'슈트 코어 합성',outputType:'INVENTORY_ITEM',outputRef:'SUIT_CORE_2',outputQuantity:1,paymentMode:'BOTH',coinCost:5000000000,masterStarCost:100,successRate:25,materials:[{itemCode:'SUIT_CORE_1',quantity:10}],isActive:false,isPublic:false,ownerTestOnly:true});
test('extension categories preserve unspecified costs/rate instead of inventing defaults',async()=>{
  for(const key of ['coinCost','masterStarCost','successRate'])for(const value of [undefined,null,'',NaN,Infinity,-1]){
    assert.throws(()=>validateWorkshopExtension({...draft(),[key]:value}),/명시적으로/);
    await assert.rejects(__workshopBattleSuitTest.saveRecipe({DB:{prepare(){throw Error('must not touch DB');}}},{id:1},{...draft(),[key]:value},{}),/명시적으로/);
  }
  assert.doesNotThrow(()=>validateWorkshopExtension(draft()));
  assert.throws(()=>validateWorkshopExtension({...draft(),successRate:101}),/명시적으로/);
  assert.throws(()=>validateWorkshopExtension({...draft(),coinCost:1.5}),/명시적으로/);
  assert.throws(()=>validateWorkshopExtension({...draft(),outputType:'EQUIPMENT'}),/인벤토리/);
  assert.throws(()=>validateWorkshopExtension({...draft(),outputRef:'SUIT_CORE_1'}),/달라야/);
  assert.throws(()=>validateWorkshopExtension({...draft(),materials:[{itemCode:'MASTER_STAR',quantity:10}]}),/전용 비용/);
  assert.throws(()=>validateWorkshopExtension({...draft(),materials:[{itemCode:'SUIT_CORE_1',quantity:1.5}]}),/정수/);
});

test('shared UI resolves every payment mode and all material shortages without mutating state',()=>{
  const context=vm.createContext({window:{}});vm.runInContext(fs.readFileSync(new URL('../js/workshop-recipes-v1.js',import.meta.url),'utf8'),context);
  const {describe,matches,image}=context.window.WorkshopRecipes;
  const state={wallet:{coin:90,masterStars:20,cardShards:30},inventory:{SUIT_CORE_1:{quantity:9}}};
  const before=JSON.stringify(state),r={name:'슈트 코어 2',coin_cost:100,master_star_cost:10,card_shard_cost:40,materials:[{item_code:'SUIT_CORE_1',item_name:'슈트 코어 1',quantity:10}]};
  for(const [mode,expected] of [['BOTH',[100,10,0]],['COIN_ONLY',[100,0,0]],['MASTER_STAR_ONLY',[0,10,0]],['COIN_AND_CARD_SHARD',[100,0,40]]]){
    const info=describe({...r,payment_mode:mode},state,'MASTER_STAR');
    assert.deepEqual([info.cost.coin,info.cost.stars,info.cost.shards],expected);
    assert.equal(info.ready,false);assert.match(info.shortage,/슈트 코어 1 1개 부족/);
  }
  assert.equal(describe({...r,payment_mode:'COIN_OR_MASTER_STAR',materials:[]},state,'MASTER_STAR').ready,true);
  assert.equal(matches(r,'슈트코어2'),true);assert.equal(matches(r,'슈트코어1'),true);assert.equal(matches(r,'없는 아이템'),false);
  assert.equal(image('javascript:alert(1)'), '');assert.equal(image('//host/a.png'),'');
  assert.equal(JSON.stringify(state),before);
});

for(const postgres of [false,true])for(const success of [true,false])test(`${postgres?'PostgreSQL':'SQLite'} core synthesis is atomic and replay-safe, success=${success}`,async t=>{
  const f=await jointFixture(t,{postgres});
  const schema=sql=>postgres?f.pg.exec(sql.replace(/INTEGER PRIMARY KEY AUTOINCREMENT/g,'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY').replace(/\bINTEGER\b/g,'BIGINT').replace(/CURRENT_TIMESTAMP/g,'sqlite_now()')):f.p(sql).run();
  for(const sql of __workshopCraftTest.FOUNDATION_SQL)await schema(sql);
  for(const sql of [
    'CREATE TABLE IF NOT EXISTS character_garage_items(id INTEGER PRIMARY KEY,name TEXT,image_url TEXT,rarity TEXT,pve_power INTEGER,pvp_power INTEGER)',
    'CREATE TABLE IF NOT EXISTS user_garage_vehicles(user_id INTEGER,garage_id INTEGER,source_type TEXT,source_id TEXT)',
    'CREATE TABLE IF NOT EXISTS equipment_forge_states_v1(instance_id INTEGER,user_id INTEGER,level INTEGER)',
    'CREATE TABLE IF NOT EXISTS shard_logs(user_id INTEGER,change_amount INTEGER,balance_after INTEGER,reason TEXT,card_id TEXT)',
  ])await schema(sql);
  for(const code of ['SUIT_CORE_1','SUIT_CORE_2','MASTER_STAR']){
    await f.p("INSERT INTO inventory_items(code,name,category) VALUES(?,?,'MATERIAL') ON CONFLICT(code) DO NOTHING",code,code).run();
    await f.p('INSERT INTO cnine_user_inventory(user_id,item_code,quantity,unseen_quantity) VALUES(7,?,100,100) ON CONFLICT(user_id,item_code) DO UPDATE SET quantity=100,unseen_quantity=100',code).run();
  }
  await f.p('UPDATE users SET coin=10000000000 WHERE id=7').run();
  const recipeId=await __workshopBattleSuitTest.saveRecipe(f.env,{id:7},{...draft(),successRate:success?100:0},{});
  const craft=requestId=>__workshopCraftTest.craft(f.env,{id:7,role:'USER'},{recipeId,requestId});
  await assert.rejects(craft('off'),/제작할 수 없는/);
  assert.equal(Number((await f.p("SELECT quantity FROM cnine_user_inventory WHERE user_id=7 AND item_code='SUIT_CORE_1'").first()).quantity),100);
  await f.p('UPDATE workshop_recipes_v1668 SET is_active=1,is_public=1,owner_test_only=0 WHERE id=?',recipeId).run();
  f.fail('INSERT INTO coin_logs');
  await assert.rejects(craft('rollback-request'),/INJECTED_FAILURE/);
  f.fail('');
  assert.equal(await f.coin(),10000000000);
  for(const code of ['SUIT_CORE_1','SUIT_CORE_2','MASTER_STAR'])assert.equal(Number((await f.p('SELECT quantity FROM cnine_user_inventory WHERE user_id=7 AND item_code=?',code).first()).quantity),100);
  assert.equal((await f.p("SELECT status FROM workshop_craft_receipts_v1668 WHERE request_id='rollback-request'").first()).status,'FAILED');
  const first=await craft('same-request'),second=await craft('same-request');
  assert.equal(first.success,success);assert.equal(second.replayed,true);
  assert.equal(first.coinSpent,5000000000);assert.equal(first.masterStarSpent,100);
  assert.equal(first.state.wallet.coin,5000000000);assert.equal(second.state.wallet.coin,5000000000);
  assert.equal(first.state.inventory.SUIT_CORE_1.quantity,90);assert.equal(second.state.inventory.SUIT_CORE_1.quantity,90);
  assert.equal(first.state.inventory.SUIT_CORE_2.quantity,success?101:100);
  assert.equal(first.state.wallet.masterStars,0);
  await assert.rejects(craft('insufficient-stars'),/마스터의 별이 부족/);
  assert.equal(Number((await f.p('SELECT COUNT(*) n FROM workshop_craft_logs_v1668').first()).n),1);
});
