import test from 'node:test';
import assert from 'node:assert/strict';
import { PGlite } from '@electric-sql/pglite';
import { __postgresCompatTest } from '../functions/_postgres_d1_compat.js';
import { __workshopCraftTest } from '../functions/_workshop.js';

// Execute the production craft handler and SQL adapter against PostgreSQL WASM.
// The live money columns are already bigint; parameter inference caused the error.
async function fixture({ cost = 5000000000, output = 'VEHICLE' } = {}) {
  const pg = new PGlite();
  await pg.exec(`
    CREATE FUNCTION sqlite_now() RETURNS text LANGUAGE SQL STABLE AS $$SELECT to_char(timezone('UTC',CURRENT_TIMESTAMP),'YYYY-MM-DD HH24:MI:SS')$$;
    CREATE TABLE app_meta(key TEXT PRIMARY KEY,value TEXT);
    CREATE TABLE users(id BIGINT PRIMARY KEY,coin BIGINT,card_shards BIGINT);
    CREATE TABLE inventory_items(code TEXT PRIMARY KEY,name TEXT,category TEXT,rarity TEXT,image_url TEXT,is_active BIGINT DEFAULT 1);
    CREATE TABLE cnine_user_inventory(user_id BIGINT,item_code TEXT,quantity BIGINT,unseen_quantity BIGINT,created_at TEXT DEFAULT sqlite_now(),updated_at TEXT DEFAULT sqlite_now(),PRIMARY KEY(user_id,item_code));
    CREATE TABLE inventory_logs(user_id BIGINT,item_code TEXT,change_amount BIGINT,balance_after BIGINT,reason TEXT,reference_type TEXT,reference_id TEXT);
    CREATE TABLE coin_logs(user_id BIGINT,change_amount BIGINT,balance_after BIGINT,reason TEXT);
    CREATE TABLE shard_logs(user_id BIGINT,change_amount BIGINT,balance_after BIGINT,reason TEXT,card_id TEXT);
    CREATE TABLE character_garage_items(id BIGINT PRIMARY KEY,name TEXT,image_url TEXT,rarity TEXT,pve_power BIGINT,pvp_power BIGINT,is_active BIGINT DEFAULT 1,is_public BIGINT DEFAULT 1);
    CREATE TABLE character_equipment_items(id BIGINT PRIMARY KEY,name TEXT,slot TEXT,image_url TEXT,rarity TEXT,pve_power BIGINT,pvp_power BIGINT,is_active BIGINT DEFAULT 1,is_public BIGINT DEFAULT 1);
    CREATE TABLE user_garage_vehicles(user_id BIGINT,garage_id BIGINT,source_type TEXT,source_id TEXT,UNIQUE(user_id,garage_id));
    CREATE TABLE user_equipment_instances(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id BIGINT,equipment_id BIGINT,source_type TEXT,source_id TEXT,request_id TEXT);
    CREATE TABLE user_equipment_loadout(instance_id BIGINT);
    CREATE TABLE equipment_forge_states_v1(instance_id BIGINT,user_id BIGINT,level BIGINT);
    INSERT INTO inventory_items(code,name) VALUES('MASTER_STAR','별'),('TIRE','타이어'),('FRAME','차체'),('ENGINE','엔진');
    INSERT INTO cnine_user_inventory(user_id,item_code,quantity,unseen_quantity) VALUES(1,'MASTER_STAR',500000,500000),(1,'TIRE',267,267),(1,'FRAME',283,283),(1,'ENGINE',155,155);
    INSERT INTO character_garage_items(id,name) VALUES(1,'솔라리스');
    INSERT INTO character_equipment_items(id,name) VALUES(1,'배틀슈트');
  `);
  // Match the migrated live schema, without running runtime schema upgrades.
  for (const sql of __workshopCraftTest.FOUNDATION_SQL) {
    await pg.exec(sql.replace(/INTEGER PRIMARY KEY AUTOINCREMENT/g, 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY')
      .replace(/\bINTEGER\b/g, 'BIGINT').replace(/CURRENT_TIMESTAMP/g, 'sqlite_now()'));
  }
  await pg.query('INSERT INTO users VALUES(1,$1,100)', [cost * 2]);
  await pg.query(`INSERT INTO workshop_recipes_v1668(id,code,name,category,output_type,output_ref,payment_mode,coin_cost,master_star_cost,success_rate)
    VALUES(1,'WORKSHOP_QA','조립 검증',$1,$2,'1','BOTH',$3,250000,10)`, [output === 'VEHICLE' ? 'VEHICLE' : 'BATTLE_SUIT_CRAFT', output, cost]);
  await pg.exec("INSERT INTO workshop_recipe_materials_v1668(recipe_id,item_code,quantity) VALUES(1,'TIRE',250),(1,'FRAME',250),(1,'ENGINE',150)");
  let failCoinLog = false;
  const client = { async query(input) {
    const sql = typeof input === 'string' ? input : input.text;
    if (failCoinLog && /INSERT INTO coin_logs/.test(sql)) throw new Error('QA coin log failure');
    const result = await pg.query(sql, typeof input === 'string' ? [] : input.values || []);
    const rows = result.rows.map(row => Object.fromEntries(Object.entries(row).map(([key, value]) => [key, typeof value === 'bigint' ? Number(value) : value])));
    return { ...result, rows, rowCount: result.affectedRows ?? rows.length };
  } };
  const DB = new __postgresCompatTest.PostgresD1Database(client);
  let beforeBatch = null, batchSize = 0;
  const batch = DB.batch.bind(DB);
  DB.batch = async statements => { batchSize = statements.length; if (beforeBatch) { const hook = beforeBatch; beforeBatch = null; await hook(); } return batch(statements); };
  return {
    pg, DB, cost,
    craft: (requestId, body = {}) => __workshopCraftTest.craft({ DB }, { id: 1, role: 'USER' }, { recipeId: 1, requestId, ...body }),
    failCoinLog() { failCoinLog = true; },
    beforeBatch(fn) { beforeBatch = fn; },
    batchSize: () => batchSize,
    row: async sql => (await pg.query(sql)).rows[0],
    close: () => pg.close(),
  };
}

test('unary parameters retain large integer, fractional and null values in PostgreSQL', async () => {
  const pg = new PGlite();
  try {
    // The old 0-$1 anchor infers int4 even with a bigint destination column.
    await assert.rejects(pg.query('SELECT 0-$1 AS delta', [5000000000]), error => error.code === '22003');
    const sql = __postgresCompatTest.bindQuestionMarks('SELECT -? AS delta').text;
    for (const value of [0, 2147483647, 2147483648, 5000000000, 10000000000, Number.MAX_SAFE_INTEGER, -5000000000, 1.25, null]) {
      const actual = (await pg.query(sql, [value])).rows[0].delta;
      assert.equal(actual === null ? null : Number(actual), value === null ? null : value === 0 ? 0 : -value);
    }
    const mixed = __postgresCompatTest.bindQuestionMarks("SELECT 10000000000::bigint-? AS balance,CASE WHEN TRUE THEN -? ELSE 0 END AS delta,'-?' AS literal /* -? */ -- -?\n");
    assert.equal(mixed.count, 2);
    assert.deepEqual((await pg.query(mixed.text, [5000000000, 5000000000])).rows.map(row => ({ balance: Number(row.balance), delta: Number(row.delta), literal: row.literal })), [{ balance: 5000000000, delta: -5000000000, literal: '-?' }]);
  } finally { await pg.close(); }
});

async function materialFixture({ mystic = true } = {}) {
  const f = await fixture({ cost: 200000000, output: 'INVENTORY_ITEM' });
  await f.pg.exec(`
    INSERT INTO inventory_items(code,name,category,rarity,image_url) VALUES('STARLIGHT_ARMOR_CORE','미스틱 에너지','MATERIAL','SPECIAL','assets/items/starlight-armor-core-v1749.png'),('EMPEROR_ENERGY','엠퍼러 에너지','MATERIAL','EMPEROR','assets/items/emperor-energy-v1.webp');
    UPDATE users SET coin=20000000000,card_shards=500000000 WHERE id=1;
    DELETE FROM workshop_recipe_materials_v1668;
    UPDATE workshop_recipes_v1668 SET category='MATERIAL_CRAFT',code='${mystic ? 'WORKSHOP_MYSTIC_ENERGY' : 'QA_MATERIAL'}',output_ref='${mystic ? 'STARLIGHT_ARMOR_CORE' : 'EMPEROR_ENERGY'}',output_quantity=${mystic ? 1 : 2},payment_mode='${mystic ? 'COIN_AND_CARD_SHARD' : 'BOTH'}',coin_cost=200000000,master_star_cost=${mystic ? 0 : 100},success_rate=10 WHERE id=1;
  `);
  if (!mystic) await f.pg.exec("INSERT INTO workshop_recipe_materials_v1668(recipe_id,item_code,quantity) VALUES(1,'TIRE',2),(1,'MASTER_STAR',5)");
  return f;
}

test('material batch independently rolls each attempt, spends the total once and replays its receipt', async t => {
  const f = await materialFixture(); let rolls = 0;
  t.mock.method(Math, 'random', () => (++rolls % 3 === 0 ? 0 : 0.99));
  try {
    const result = await f.craft('material-ten', { attempts: 10 });
    assert.deepEqual([result.attempts,result.successCount,result.failureCount,result.output.quantity,rolls], [10,3,7,3,10]);
    assert.deepEqual(result.state.wallet, {coin:18000000000,cardShards:450000000,masterStars:500000});
    assert.equal(result.state.inventory.STARLIGHT_ARMOR_CORE.quantity, 3);
    assert.equal(Number((await f.row('SELECT change_amount FROM shard_logs')).change_amount), -50000000);
    assert.equal(Number((await f.row('SELECT output_quantity FROM workshop_craft_logs_v1668')).output_quantity), 3);
    const replay = await f.craft('material-ten', {attempts:100});
    assert.equal(replay.replayed, true); assert.equal(replay.attempts, 10); assert.equal(rolls, 10);
    assert.deepEqual(replay.state.wallet, result.state.wallet);
    assert.deepEqual(replay.state.inventory, result.state.inventory);
    assert.equal(Number((await f.row('SELECT COUNT(*) n FROM coin_logs')).n), 1);
    await f.pg.exec(`
      INSERT INTO app_meta(key,value) VALUES('safe_runtime_upgrade_emperor_energy_catalog_20260926','1');
      ALTER TABLE users ADD COLUMN nickname TEXT;
      ALTER TABLE inventory_items ADD COLUMN sort_order BIGINT;
      ALTER TABLE character_garage_items ADD COLUMN code TEXT,ADD COLUMN sort_order BIGINT;
      ALTER TABLE character_equipment_items ADD COLUMN code TEXT,ADD COLUMN sort_order BIGINT;
    `);
    const cms = await __workshopCraftTest.adminSnapshot({DB:f.DB},{id:1,role:'OWNER'});
    assert.equal(cms.inventoryItems.some(item=>item.code==='EMPEROR_ENERGY'),true);
    assert.deepEqual([cms.recentLogs[0].attempts,cms.recentLogs[0].success_count,cms.recentLogs[0].failure_count,cms.recentLogs[0].card_shard_spent],[10,3,7,50000000]);
  } finally { await f.close(); }
});

test('all-failed material batches spend every attempt; 100 attempts use a fixed number of SQL statements', async t => {
  const f = await materialFixture(); let rolls = 0;
  t.mock.method(Math, 'random', () => { rolls++; return 0.99; });
  try {
    await f.craft('one-failure'); const singleSize = f.batchSize();
    await f.pg.exec('UPDATE users SET coin=20000000000,card_shards=500000000 WHERE id=1');
    const result = await f.craft('hundred-failures', {attempts:100});
    assert.deepEqual([result.attempts,result.successCount,result.failureCount,result.output,rolls], [100,0,100,null,101]);
    assert.equal(result.state.wallet.coin, 0); assert.equal(result.state.wallet.cardShards, 0);
    assert.equal(f.batchSize(), singleSize);
    assert.equal(result.state.inventory.STARLIGHT_ARMOR_CORE.quantity, 0);
  } finally { await f.close(); }
});

test('CMS material recipe multiplies inventory inputs, combined stars and output quantity', async t => {
  const f = await materialFixture({mystic:false});
  t.mock.method(Math, 'random', () => 0);
  try {
    const result = await f.craft('custom-material', {attempts:10});
    assert.equal(result.output.quantity, 20);
    assert.equal(result.state.inventory.EMPEROR_ENERGY.quantity, 20);
    assert.equal(result.state.inventory.TIRE.quantity, 247);
    assert.equal(result.state.wallet.masterStars, 498950);
    assert.equal(Number((await f.row("SELECT change_amount FROM inventory_logs WHERE reason='WORKSHOP_MATERIAL' AND item_code='TIRE'")).change_amount), -20);
  } finally { await f.close(); }
});

test('invalid counts, unsafe totals, non-material batch and insufficient funds reserve nothing', async () => {
  const f = await materialFixture({mystic:false});
  try {
    for (const attempts of [0,-1,1.5,101,'invalid']) await assert.rejects(f.craft('invalid-'+attempts,{attempts}), /1~100/);
    await f.pg.exec('UPDATE workshop_recipes_v1668 SET coin_cost=9007199254740991');
    await assert.rejects(f.craft('overflow',{attempts:100}), /총 제작 비용/);
    await f.pg.exec("UPDATE workshop_recipes_v1668 SET coin_cost=200000000,category='BATTLE_SUIT_CRAFT'");
    await assert.rejects(f.craft('wrong-category',{attempts:10}), /1회만/);
    await f.pg.exec("UPDATE workshop_recipes_v1668 SET category='MATERIAL_CRAFT'; UPDATE users SET coin=1");
    await assert.rejects(f.craft('poor-coin',{attempts:10}), /코인/);
    await f.pg.exec("UPDATE users SET coin=20000000000; UPDATE cnine_user_inventory SET quantity=1001 WHERE item_code='MASTER_STAR'");
    await assert.rejects(f.craft('combined-star-short',{attempts:10}), /재료가 부족/);
    assert.equal(Number((await f.row('SELECT COUNT(*) n FROM workshop_craft_receipts_v1668')).n), 0);
  } finally { await f.close(); }
});

test('material batch rechecks total inputs under the transaction lock and rolls back a late failure', async t => {
  const f = await materialFixture({mystic:false});
  t.mock.method(Math, 'random', () => 0);
  try {
    f.beforeBatch(() => f.pg.exec("UPDATE cnine_user_inventory SET quantity=19 WHERE item_code='TIRE'"));
    await assert.rejects(f.craft('changed-input',{attempts:10}), /변경되어 제작이 취소/);
    assert.equal(Number((await f.row('SELECT coin FROM users')).coin), 20000000000);
    assert.equal(Number((await f.row("SELECT quantity FROM cnine_user_inventory WHERE item_code='MASTER_STAR'")).quantity), 500000);
    assert.equal(Number((await f.row('SELECT COUNT(*) n FROM coin_logs')).n), 0);
    await f.pg.exec("UPDATE cnine_user_inventory SET quantity=267 WHERE item_code='TIRE'");
    f.failCoinLog();
    await assert.rejects(f.craft('rollback-material',{attempts:10}), /QA coin log failure/);
    assert.equal(Number((await f.row('SELECT coin FROM users')).coin), 20000000000);
    assert.equal(Number((await f.row("SELECT quantity FROM cnine_user_inventory WHERE item_code='TIRE'")).quantity), 267);
    assert.equal(Number((await f.row("SELECT COUNT(*) n FROM cnine_user_inventory WHERE item_code='EMPEROR_ENERGY'")).n), 0);
    assert.equal(Number((await f.row('SELECT COUNT(*) n FROM inventory_logs')).n), 0);
    await assert.rejects(f.craft('rollback-material',{attempts:10}), /QA coin log failure/);
  } finally { await f.close(); }
});

test('overlapping duplicate material submissions cannot debit twice', async t => {
  const f = await materialFixture();
  t.mock.method(Math, 'random', () => 0);
  try {
    const results = await Promise.allSettled([f.craft('same-batch',{attempts:10}), f.craft('same-batch',{attempts:10})]);
    assert.equal(results.filter(row=>row.status==='fulfilled').length, 1);
    assert.match(results.find(row=>row.status==='rejected').reason.message, /처리 중/);
    assert.equal(Number((await f.row('SELECT coin FROM users')).coin), 18000000000);
    assert.equal(Number((await f.row('SELECT COUNT(*) n FROM coin_logs')).n), 1);
  } finally { await f.close(); }
});

for (const { cost, output, success } of [
  { cost: 5000000000, output: 'VEHICLE', success: true },
  { cost: 5000000000, output: 'VEHICLE', success: false },
  { cost: 10000000000, output: 'EQUIPMENT', success: true },
]) {
  test(`PostgreSQL ${output} craft spends ${cost} exactly once (success=${success})`, async t => {
    const f = await fixture({ cost, output });
    t.mock.method(Math, 'random', () => success ? 0 : 0.99);
    try {
      const result = await f.craft('large-coin-craft');
      assert.equal(result.success, success);
      assert.equal(result.coinSpent, cost);
      assert.equal(result.masterStarSpent, 250000);
      assert.equal(result.state.wallet.coin, cost);
      assert.equal(result.state.wallet.masterStars, 250000);
      assert.deepEqual(['TIRE', 'FRAME', 'ENGINE'].map(code => result.state.inventory[code].quantity), [17, 33, 5]);
      const log = await f.row('SELECT * FROM coin_logs');
      assert.equal(Number(log.change_amount), -cost);
      assert.equal(Number(log.balance_after), cost);
      assert.equal(Number((await f.row('SELECT coin_spent FROM workshop_craft_logs_v1668')).coin_spent), cost);
      assert.equal(Number((await f.row('SELECT COUNT(*) n FROM user_garage_vehicles')).n), success && output === 'VEHICLE' ? 1 : 0);
      assert.equal(Number((await f.row('SELECT COUNT(*) n FROM user_equipment_instances')).n), success && output === 'EQUIPMENT' ? 1 : 0);
      const replay = await f.craft('large-coin-craft');
      assert.equal(replay.replayed, true);
      assert.equal(replay.success, success);
      assert.deepEqual(replay.state.wallet, result.state.wallet);
      assert.deepEqual(replay.state.inventory, result.state.inventory);
      assert.equal(Number((await f.row('SELECT COUNT(*) n FROM coin_logs')).n), 1);
      assert.equal(Number((await f.row('SELECT COUNT(*) n FROM workshop_craft_logs_v1668')).n), 1);
      assert.equal(Number((await f.row('SELECT COUNT(*) n FROM inventory_logs')).n), 4);
      assert.equal((await f.row('SELECT status FROM workshop_craft_receipts_v1668')).status, 'COMPLETED');
    } finally { await f.close(); }
  });
}

test('S-BODY spends 100 billion coin and 1 million stars together, rejects stale choice, and replays once', async t => {
  const f = await fixture({ cost: 100000000000, output: 'EQUIPMENT' });
  t.mock.method(Math, 'random', () => 0);
  try {
    await f.pg.exec(`
      INSERT INTO character_equipment_items(id,name,slot) VALUES(47,'S-BODY','BATTLE_SUIT');
      INSERT INTO inventory_items(code,name) VALUES('SUIT_CORE_5','슈트 코어 5');
      INSERT INTO cnine_user_inventory(user_id,item_code,quantity,unseen_quantity) VALUES(1,'SUIT_CORE_5',20,20);
      UPDATE cnine_user_inventory SET quantity=2000000,unseen_quantity=2000000 WHERE user_id=1 AND item_code='MASTER_STAR';
      UPDATE workshop_recipes_v1668 SET code='WORKSHOP_NEW_1790584013750',output_ref='47',master_star_cost=1000000,payment_mode='COIN_OR_MASTER_STAR' WHERE id=1;
      DELETE FROM workshop_recipe_materials_v1668 WHERE recipe_id=1;
      INSERT INTO workshop_recipe_materials_v1668(recipe_id,item_code,quantity) VALUES(1,'SUIT_CORE_5',10);
    `);
    await assert.rejects(f.craft('sbody-wrong-mode', { paymentType: 'COIN' }), /S-BODY 제작 결제 설정/);
    assert.equal(Number((await f.row('SELECT COUNT(*) n FROM workshop_craft_receipts_v1668')).n), 0);
    await f.pg.exec("UPDATE workshop_recipes_v1668 SET payment_mode='BOTH' WHERE id=1");
    await assert.rejects(f.craft('sbody-stale-choice', { paymentType: 'COIN' }), /코인과 마스터의 별을 모두 사용/);
    assert.equal(Number((await f.row('SELECT COUNT(*) n FROM workshop_craft_receipts_v1668')).n), 0);
    const first = await f.craft('sbody-both', { paymentType: 'BOTH' });
    const replay = await f.craft('sbody-both', { paymentType: 'BOTH' });
    assert.equal(first.success, true);
    assert.equal(first.coinSpent, 100000000000);
    assert.equal(first.masterStarSpent, 1000000);
    assert.equal(first.state.wallet.coin, 100000000000);
    assert.equal(first.state.wallet.masterStars, 1000000);
    assert.equal(first.state.inventory.SUIT_CORE_5.quantity, 10);
    assert.equal(replay.replayed, true);
    assert.deepEqual(replay.state.wallet, first.state.wallet);
    assert.equal(Number((await f.row('SELECT COUNT(*) n FROM user_equipment_instances WHERE equipment_id=47')).n), 1);
    assert.equal(Number((await f.row('SELECT COUNT(*) n FROM coin_logs')).n), 1);
    assert.equal(Number((await f.row("SELECT COUNT(*) n FROM inventory_logs WHERE item_code='MASTER_STAR' AND reason='WORKSHOP_PAYMENT'")).n), 1);
  } finally { await f.close(); }
});

test('post-debit SQL failure rolls back large coin, stars, materials, output and logs', async t => {
  const f = await fixture();
  t.mock.method(Math, 'random', () => 0);
  try {
    f.failCoinLog();
    await assert.rejects(f.craft('late-failure'), /QA coin log failure/);
    assert.equal(Number((await f.row('SELECT coin FROM users WHERE id=1')).coin), 10000000000);
    const items = (await f.pg.query('SELECT item_code,quantity FROM cnine_user_inventory')).rows;
    assert.deepEqual(Object.fromEntries(items.map(row => [row.item_code, Number(row.quantity)])), { MASTER_STAR: 500000, TIRE: 267, FRAME: 283, ENGINE: 155 });
    for (const table of ['coin_logs', 'inventory_logs', 'workshop_craft_logs_v1668', 'workshop_craft_guards_v1668', 'user_garage_vehicles', 'user_equipment_instances']) {
      assert.equal(Number((await f.row(`SELECT COUNT(*) n FROM ${table}`)).n), 0, table);
    }
    assert.equal((await f.row('SELECT status FROM workshop_craft_receipts_v1668')).status, 'FAILED');
  } finally { await f.close(); }
});
