import test from 'node:test';
import assert from 'node:assert/strict';
import { PGlite } from '@electric-sql/pglite';
import { __postgresCompatTest } from '../functions/_postgres_d1_compat.js';
import { __workshopCraftTest } from '../functions/_workshop.js';

// Execute the production craft handler and SQL adapter against PostgreSQL WASM.
// The live money columns are already bigint; parameter inference caused the error.
async function fixture({ cost = 5000000000, output = 'VEHICLE' } = {}) {
  const pg = new PGlite();
  await pg.exec(`
    CREATE FUNCTION sqlite_now() RETURNS text LANGUAGE SQL STABLE AS $$SELECT to_char(timezone('UTC',CURRENT_TIMESTAMP),'YYYY-MM-DD HH24:MI:SS')$$;
    CREATE TABLE app_meta(key TEXT PRIMARY KEY,value TEXT);
    CREATE TABLE users(id BIGINT PRIMARY KEY,coin BIGINT,card_shards BIGINT);
    CREATE TABLE inventory_items(code TEXT PRIMARY KEY,name TEXT,category TEXT,rarity TEXT,image_url TEXT,is_active BIGINT DEFAULT 1);
    CREATE TABLE cnine_user_inventory(user_id BIGINT,item_code TEXT,quantity BIGINT,unseen_quantity BIGINT,created_at TEXT DEFAULT sqlite_now(),updated_at TEXT DEFAULT sqlite_now(),PRIMARY KEY(user_id,item_code));
    CREATE TABLE inventory_logs(user_id BIGINT,item_code TEXT,change_amount BIGINT,balance_after BIGINT,reason TEXT,reference_type TEXT,reference_id TEXT);
    CREATE TABLE coin_logs(user_id BIGINT,change_amount BIGINT,balance_after BIGINT,reason TEXT);
    CREATE TABLE shard_logs(user_id BIGINT,change_amount BIGINT,balance_after BIGINT,reason TEXT,card_id TEXT);
    CREATE TABLE character_garage_items(id BIGINT PRIMARY KEY,name TEXT,image_url TEXT,rarity TEXT,pve_power BIGINT,pvp_power BIGINT,is_active BIGINT DEFAULT 1,is_public BIGINT DEFAULT 1);
    CREATE TABLE character_equipment_items(id BIGINT PRIMARY KEY,name TEXT,slot TEXT,image_url TEXT,rarity TEXT,pve_power BIGINT,pvp_power BIGINT,is_active BIGINT DEFAULT 1,is_public BIGINT DEFAULT 1);
    CREATE TABLE user_garage_vehicles(user_id BIGINT,garage_id BIGINT,source_type TEXT,source_id TEXT,UNIQUE(user_id,garage_id));
    CREATE TABLE user_equipment_instances(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id BIGINT,equipment_id BIGINT,source_type TEXT,source_id TEXT,request_id TEXT);
    CREATE TABLE user_equipment_loadout(instance_id BIGINT);
    CREATE TABLE equipment_forge_states_v1(instance_id BIGINT,user_id BIGINT,level BIGINT);
    INSERT INTO inventory_items(code,name) VALUES('MASTER_STAR','별'),('TIRE','타이어'),('FRAME','차체'),('ENGINE','엔진');
    INSERT INTO cnine_user_inventory(user_id,item_code,quantity,unseen_quantity) VALUES(1,'MASTER_STAR',500000,500000),(1,'TIRE',267,267),(1,'FRAME',283,283),(1,'ENGINE',155,155);
    INSERT INTO character_garage_items(id,name) VALUES(1,'솔라리스');
    INSERT INTO character_equipment_items(id,name) VALUES(1,'배틀슈트');
  `);
  // Match the migrated live schema, without running runtime schema upgrades.
  for (const sql of __workshopCraftTest.FOUNDATION_SQL) {
    await pg.exec(sql.replace(/INTEGER PRIMARY KEY AUTOINCREMENT/g, 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY')
      .replace(/\bINTEGER\b/g, 'BIGINT').replace(/CURRENT_TIMESTAMP/g, 'sqlite_now()'));
  }
  await pg.query('INSERT INTO users VALUES(1,$1,100)', [cost * 2]);
  await pg.query(`INSERT INTO workshop_recipes_v1668(id,code,name,category,output_type,output_ref,payment_mode,coin_cost,master_star_cost,success_rate)
    VALUES(1,'WORKSHOP_QA','조립 검증',$1,$2,'1','BOTH',$3,250000,10)`, [output === 'VEHICLE' ? 'VEHICLE' : 'BATTLE_SUIT_CRAFT', output, cost]);
  await pg.exec("INSERT INTO workshop_recipe_materials_v1668(recipe_id,item_code,quantity) VALUES(1,'TIRE',250),(1,'FRAME',250),(1,'ENGINE',150)");
  let failCoinLog = false;
  const client = { async query(input) {
    const sql = typeof input === 'string' ? input : input.text;
    if (failCoinLog && /INSERT INTO coin_logs/.test(sql)) throw new Error('QA coin log failure');
    const result = await pg.query(sql, typeof input === 'string' ? [] : input.values || []);
    const rows = result.rows.map(row => Object.fromEntries(Object.entries(row).map(([key, value]) => [key, typeof value === 'bigint' ? Number(value) : value])));
    return { ...result, rows, rowCount: result.affectedRows ?? rows.length };
  } };
  const DB = new __postgresCompatTest.PostgresD1Database(client);
  return {
    pg, DB, cost,
    craft: requestId => __workshopCraftTest.craft({ DB }, { id: 1, role: 'USER' }, { recipeId: 1, requestId }),
    failCoinLog() { failCoinLog = true; },
    row: async sql => (await pg.query(sql)).rows[0],
    close: () => pg.close(),
  };
}

test('unary parameters retain large integer, fractional and null values in PostgreSQL', async () => {
  const pg = new PGlite();
  try {
    // The old 0-$1 anchor infers int4 even with a bigint destination column.
    await assert.rejects(pg.query('SELECT 0-$1 AS delta', [5000000000]), error => error.code === '22003');
    const sql = __postgresCompatTest.bindQuestionMarks('SELECT -? AS delta').text;
    for (const value of [0, 2147483647, 2147483648, 5000000000, 10000000000, Number.MAX_SAFE_INTEGER, -5000000000, 1.25, null]) {
      const actual = (await pg.query(sql, [value])).rows[0].delta;
      assert.equal(actual === null ? null : Number(actual), value === null ? null : value === 0 ? 0 : -value);
    }
    const mixed = __postgresCompatTest.bindQuestionMarks("SELECT 10000000000::bigint-? AS balance,CASE WHEN TRUE THEN -? ELSE 0 END AS delta,'-?' AS literal /* -? */ -- -?\n");
    assert.equal(mixed.count, 2);
    assert.deepEqual((await pg.query(mixed.text, [5000000000, 5000000000])).rows.map(row => ({ balance: Number(row.balance), delta: Number(row.delta), literal: row.literal })), [{ balance: 5000000000, delta: -5000000000, literal: '-?' }]);
  } finally { await pg.close(); }
});

for (const { cost, output, success } of [
  { cost: 5000000000, output: 'VEHICLE', success: true },
  { cost: 5000000000, output: 'VEHICLE', success: false },
  { cost: 10000000000, output: 'EQUIPMENT', success: true },
]) {
  test(`PostgreSQL ${output} craft spends ${cost} exactly once (success=${success})`, async t => {
    const f = await fixture({ cost, output });
    t.mock.method(Math, 'random', () => success ? 0 : 0.99);
    try {
      const result = await f.craft('large-coin-craft');
      assert.equal(result.success, success);
      assert.equal(result.coinSpent, cost);
      assert.equal(result.masterStarSpent, 250000);
      assert.equal(result.state.wallet.coin, cost);
      assert.equal(result.state.wallet.masterStars, 250000);
      assert.deepEqual(['TIRE', 'FRAME', 'ENGINE'].map(code => result.state.inventory[code].quantity), [17, 33, 5]);
      const log = await f.row('SELECT * FROM coin_logs');
      assert.equal(Number(log.change_amount), -cost);
      assert.equal(Number(log.balance_after), cost);
      assert.equal(Number((await f.row('SELECT coin_spent FROM workshop_craft_logs_v1668')).coin_spent), cost);
      assert.equal(Number((await f.row('SELECT COUNT(*) n FROM user_garage_vehicles')).n), success && output === 'VEHICLE' ? 1 : 0);
      assert.equal(Number((await f.row('SELECT COUNT(*) n FROM user_equipment_instances')).n), success && output === 'EQUIPMENT' ? 1 : 0);
      const replay = await f.craft('large-coin-craft');
      assert.equal(replay.replayed, true);
      assert.equal(replay.success, success);
      assert.deepEqual(replay.state.wallet, result.state.wallet);
      assert.deepEqual(replay.state.inventory, result.state.inventory);
      assert.equal(Number((await f.row('SELECT COUNT(*) n FROM coin_logs')).n), 1);
      assert.equal(Number((await f.row('SELECT COUNT(*) n FROM workshop_craft_logs_v1668')).n), 1);
      assert.equal(Number((await f.row('SELECT COUNT(*) n FROM inventory_logs')).n), 4);
      assert.equal((await f.row('SELECT status FROM workshop_craft_receipts_v1668')).status, 'COMPLETED');
    } finally { await f.close(); }
  });
}

test('post-debit SQL failure rolls back large coin, stars, materials, output and logs', async t => {
  const f = await fixture();
  t.mock.method(Math, 'random', () => 0);
  try {
    f.failCoinLog();
    await assert.rejects(f.craft('late-failure'), /QA coin log failure/);
    assert.equal(Number((await f.row('SELECT coin FROM users WHERE id=1')).coin), 10000000000);
    const items = (await f.pg.query('SELECT item_code,quantity FROM cnine_user_inventory')).rows;
    assert.deepEqual(Object.fromEntries(items.map(row => [row.item_code, Number(row.quantity)])), { MASTER_STAR: 500000, TIRE: 267, FRAME: 283, ENGINE: 155 });
    for (const table of ['coin_logs', 'inventory_logs', 'workshop_craft_logs_v1668', 'workshop_craft_guards_v1668', 'user_garage_vehicles', 'user_equipment_instances']) {
      assert.equal(Number((await f.row(`SELECT COUNT(*) n FROM ${table}`)).n), 0, table);
    }
    assert.equal((await f.row('SELECT status FROM workshop_craft_receipts_v1668')).status, 'FAILED');
  } finally { await f.close(); }
});
