import test from 'node:test';
import assert from 'node:assert/strict';
import {PGlite} from '@electric-sql/pglite';
import {__postgresCompatTest} from '../functions/_postgres_d1_compat.js';
import {__workshopReadTest as read, __workshopCraftTest as write} from '../functions/_workshop.js';

async function fixture(){
 const pg=new PGlite();
 await pg.exec(`
  CREATE FUNCTION sqlite_now() RETURNS text LANGUAGE SQL STABLE AS $$SELECT to_char(timezone('UTC',CURRENT_TIMESTAMP),'YYYY-MM-DD HH24:MI:SS')$$;
  CREATE TABLE app_meta(key TEXT PRIMARY KEY,value TEXT);
  CREATE TABLE users(id BIGINT PRIMARY KEY,coin BIGINT,card_shards BIGINT);
  CREATE TABLE inventory_items(code TEXT PRIMARY KEY,name TEXT,category TEXT,rarity TEXT,image_url TEXT,is_active BIGINT DEFAULT 1);
  CREATE TABLE cnine_user_inventory(user_id BIGINT,item_code TEXT,quantity BIGINT,unseen_quantity BIGINT,PRIMARY KEY(user_id,item_code));
  CREATE TABLE character_equipment_items(id BIGINT PRIMARY KEY,name TEXT,slot TEXT,image_url TEXT,rarity TEXT,pve_power BIGINT,pvp_power BIGINT,is_active BIGINT DEFAULT 1,is_public BIGINT DEFAULT 1);
  CREATE TABLE character_garage_items(id BIGINT PRIMARY KEY,name TEXT,image_url TEXT,rarity TEXT,pve_power BIGINT,pvp_power BIGINT);
  CREATE TABLE user_garage_vehicles(user_id BIGINT,garage_id BIGINT);
  CREATE TABLE user_equipment_instances(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id BIGINT,equipment_id BIGINT,source_type TEXT,source_id TEXT,request_id TEXT);
  CREATE INDEX stock ON user_equipment_instances(user_id,equipment_id,id);
  CREATE TABLE user_equipment_loadout(user_id BIGINT,instance_id BIGINT UNIQUE);
  CREATE TABLE equipment_forge_states_v1(instance_id BIGINT PRIMARY KEY,user_id BIGINT,level BIGINT);
  INSERT INTO users VALUES(7,1000,100),(8,2000,200);
  INSERT INTO character_equipment_items(id,name,slot,image_url,rarity,pve_power,pvp_power)
   SELECT id,'장비 '||id,'WEAPON','test.webp','MYTHIC',10,10 FROM generate_series(1,8) id;
  INSERT INTO user_equipment_instances(user_id,equipment_id) SELECT 7,1 FROM generate_series(1,2105);
  INSERT INTO user_equipment_instances(user_id,equipment_id) SELECT 7,4 FROM generate_series(1,2000);
  INSERT INTO user_equipment_instances(user_id,equipment_id) SELECT 7,8 FROM generate_series(1,100000);
  INSERT INTO user_equipment_instances(user_id,equipment_id) SELECT 8,1 FROM generate_series(1,5000);
  INSERT INTO user_equipment_loadout VALUES(7,1),(7,2);
  INSERT INTO equipment_forge_states_v1 VALUES(3,7,2),(4,7,0);
 `);
 for(const sql of write.FOUNDATION_SQL)await pg.exec(sql.replace(/INTEGER PRIMARY KEY AUTOINCREMENT/g,'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY').replace(/\bINTEGER\b/g,'BIGINT').replace(/CURRENT_TIMESTAMP/g,'sqlite_now()'));
 await pg.exec(`INSERT INTO equipment_synthesis_recipes_v1677(id,code,name,input_equipment_id,output_equipment_id,input_quantity,success_rate,is_active,is_public,owner_test_only)
  VALUES(1,'BULK','대량',1,2,20,100,1,1,0),(2,'EMPTY','미보유',3,2,3,100,1,1,0),(3,'EXACT','정확수량',4,2,20,100,1,1,0),(4,'PRIVATE','비공개',5,2,3,100,1,0,0),(5,'OWNER','운영자',6,2,3,100,1,1,1),(6,'DISABLED','미사용',7,2,3,100,0,1,0); ANALYZE;`);
 const queries=[];let failLog=false;
 const client={async query(input){
  const text=typeof input==='string'?input:input.text,values=typeof input==='string'?[]:input.values||[];
  queries.push({text,values});
  if(failLog&&/INSERT INTO equipment_synthesis_logs/.test(text))throw Error('Isolated receipt failure');
  const result=await pg.query(text,values);
  return {...result,rows:result.rows.map(row=>Object.fromEntries(Object.entries(row).map(([k,v])=>[k,typeof v==='bigint'?Number(v):v]))),rowCount:result.affectedRows??result.rows.length};
 }};
 const env={DB:new __postgresCompatTest.PostgresD1Database(client)},user={id:7,role:'USER'};
 return {pg,env,user,queries,fail:()=>{failLog=true},rows:async()=>read.synthesisRecipeRows(env,user),synth:requestId=>write.synthesizeEquipment(env,user,{recipeId:1,attempts:100,requestId}),stock:async()=>(await pg.query('SELECT equipment_id,count(*)::int AS n FROM user_equipment_instances WHERE user_id=7 GROUP BY equipment_id ORDER BY equipment_id')).rows};
}

test('large inventories count only recipe inputs up to 2,001 and preserve visibility and exclusions',async()=>{
 const f=await fixture();try{
  const rows=await f.rows();assert.deepEqual(rows.map(r=>r.recipe_id),[1,2,3]);
  assert.equal(rows[0].quantity,2001);assert.equal(rows[0].quantity_capped,true);
  assert.equal(rows[1].quantity,0);assert.equal(rows[1].quantity_capped,false);
  assert.equal(rows[2].quantity,2000);assert.equal(rows[2].quantity_capped,false);
  assert.equal(f.queries.length,2,'one bounded stock read plus the existing material config read');
  const query=f.queries[0],plan=(await f.pg.query('EXPLAIN (ANALYZE,FORMAT JSON) '+query.text,query.values)).rows[0]['QUERY PLAN'][0];
  const limits=[];const visit=node=>{if(node['Node Type']==='Limit')limits.push(node);for(const next of node.Plans||[])visit(next)};visit(plan.Plan);
  assert.ok(limits.length);assert.ok(limits.every(n=>n['Actual Rows']<=read.SYNTH_STOCK_READ_LIMIT));
  const owner=await read.synthesisRecipeRows(f.env,{...f.user,role:'OWNER'});assert.deepEqual(owner.map(r=>r.recipe_id),[1,2,3,5]);
  await f.pg.exec('DELETE FROM user_equipment_instances WHERE user_id=7 AND equipment_id=1 AND id>8');
  const exact=(await f.rows())[0];assert.equal(exact.quantity,5,'two equipped and one enhanced instance excluded; level zero usable');assert.equal(exact.quantity_capped,false);
  const foreign=await read.synthesisRecipeRows(f.env,{id:8,role:'USER'});assert.equal(foreign[0].quantity,2001,'other account never supplies missing stock');
 }finally{await f.pg.close()}
});

test('bounded stock still supports the maximum 100 x 20 synthesis, concurrent receipt and replay',async()=>{
 const f=await fixture();try{
  const settled=await Promise.allSettled([f.synth('large-once'),f.synth('large-once')]);
  assert.ok(settled.some(r=>r.status==='fulfilled'));
  const result=settled.find(r=>r.status==='fulfilled').value;
  assert.equal(result.attempts,100);assert.equal(result.input.quantity,2000);assert.equal(result.output.quantity,100);
  const stock=await f.stock();assert.equal(stock.find(r=>Number(r.equipment_id)===1).n,105);assert.equal(stock.find(r=>Number(r.equipment_id)===2).n,100);
  assert.equal(result.state.synthesis[0].quantity,102);assert.equal(result.state.synthesis[0].quantity_capped,false);
  const replay=await f.synth('large-once');assert.equal(replay.replayed,true);assert.deepEqual(await f.stock(),stock);
  assert.equal((await f.pg.query('SELECT count(*)::int AS n FROM user_equipment_instances WHERE id IN (1,2,3)')).rows[0].n,3,'protected instances survive');
  assert.equal((await f.pg.query('SELECT coin::int AS coin FROM users WHERE id=7')).rows[0].coin,1000);
 }finally{await f.pg.close()}
});

test('receipt failure rolls back both consumed and rewarded instances with bounded stock',async()=>{
 const f=await fixture();try{
  const before=await f.stock();f.fail();await assert.rejects(f.synth('large-failure'),/Isolated receipt failure/);
  assert.deepEqual(await f.stock(),before);
  assert.equal((await f.pg.query("SELECT status FROM equipment_synthesis_receipts_v1676 WHERE request_id='large-failure'")).rows[0].status,'FAILED');
 }finally{await f.pg.close()}
});
