import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {PGlite} from '@electric-sql/pglite';
import {__postgresCompatTest} from '../functions/_postgres_d1_compat.js';
import {S_BODY_REFUND_KEY,inspectSBodyRefund,refundSBodyChoiceAttempt} from '../functions/_workshop_s_body_refund_20260930.js';

async function fixture({breakItemLog=false}={}){
  const pg=new PGlite();
  await pg.exec(`
    CREATE FUNCTION sqlite_now() RETURNS text LANGUAGE SQL STABLE AS $$SELECT to_char(timezone('UTC',CURRENT_TIMESTAMP),'YYYY-MM-DD HH24:MI:SS')$$;
    CREATE TABLE app_meta(key TEXT PRIMARY KEY,value TEXT NOT NULL,updated_at TEXT);
    CREATE TABLE users(id BIGINT PRIMARY KEY,nickname TEXT,status TEXT,coin BIGINT);
    CREATE TABLE cnine_user_inventory(user_id BIGINT,item_code TEXT,quantity BIGINT,unseen_quantity BIGINT,updated_at TEXT,PRIMARY KEY(user_id,item_code));
    CREATE TABLE workshop_craft_logs_v1668(id BIGINT PRIMARY KEY,request_id TEXT,user_id BIGINT,recipe_id BIGINT,category TEXT,output_type TEXT,output_ref TEXT,payment_type TEXT,coin_spent BIGINT,master_star_spent BIGINT,success BIGINT,created_at TEXT);
    CREATE TABLE workshop_craft_receipts_v1668(request_id TEXT,user_id BIGINT,status TEXT,payment_type TEXT,result_json TEXT);
    CREATE TABLE coin_logs(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id BIGINT,change_amount BIGINT,balance_after BIGINT,reason TEXT,admin_id BIGINT,created_at TEXT DEFAULT sqlite_now());
    CREATE TABLE inventory_logs(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id BIGINT,item_code TEXT,change_amount BIGINT,balance_after BIGINT,reason TEXT,reference_type TEXT,reference_id TEXT,admin_id BIGINT,created_at TEXT DEFAULT sqlite_now());
    CREATE TABLE admin_logs(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,admin_id BIGINT,action_type TEXT,target_type TEXT,target_id TEXT,before_data TEXT,after_data TEXT);
    INSERT INTO users VALUES(4614,'공단','ACTIVE',2654937684055);
    INSERT INTO cnine_user_inventory VALUES(4614,'SUIT_CORE_5',0,0,NULL);
    INSERT INTO workshop_craft_logs_v1668 VALUES(99,'original-s-body-request',4614,521,'BATTLE_SUIT_CRAFT','EQUIPMENT','47','COIN',100000000000,0,0,'2026-09-29 18:38:40');
    INSERT INTO workshop_craft_receipts_v1668 VALUES('original-s-body-request',4614,'COMPLETED','COIN','{"requestId":"original-s-body-request","success":false,"coinSpent":100000000000,"masterStarSpent":0,"attempts":1}');
    INSERT INTO coin_logs(user_id,change_amount,balance_after,reason,created_at) VALUES(4614,-100000000000,2654937684055,'WORKSHOP_PAYMENT','2026-09-29 18:38:40');
    INSERT INTO inventory_logs(user_id,item_code,change_amount,balance_after,reason,reference_type,reference_id,created_at) VALUES(4614,'SUIT_CORE_5',-10,0,'WORKSHOP_MATERIAL','WORKSHOP','original-s-body-request','2026-09-29 18:38:40');
  `);
  const client={async query(input){
    const sql=typeof input==='string'?input:input.text;
    if(breakItemLog&&/INSERT INTO inventory_logs/.test(sql))throw new Error('injected refund ledger failure');
    const result=await pg.query(sql,typeof input==='string'?[]:input.values||[]);
    const rows=result.rows.map(row=>Object.fromEntries(Object.entries(row).map(([key,value])=>[key,typeof value==='bigint'?Number(value):value])));
    return {...result,rows,rowCount:result.affectedRows??rows.length};
  }};
  return {pg,env:{DB:new __postgresCompatTest.PostgresD1Database(client)},close:()=>pg.close()};
}
const scalar=async(pg,sql)=>Number((await pg.query(sql)).rows[0].value);

test('one authorized refund restores coin and ten cores atomically and replays without a second credit',async()=>{
  const f=await fixture();
  try{
    const reviewed=await inspectSBodyRefund(f.env,99);
    assert.deepEqual([reviewed.userId,reviewed.coinBefore,reviewed.coreBefore,reviewed.saved],[4614,2654937684055,0,null]);
    const result=await refundSBodyChoiceAttempt(f.env,{id:1,role:'OWNER'},99);
    assert.equal(result.replayed,false);
    assert.equal(result.coinAfter,2754937684055);
    assert.equal(result.coreAfter,10);
    assert.equal(await scalar(f.pg,'SELECT coin value FROM users WHERE id=4614'),2754937684055);
    assert.equal(await scalar(f.pg,"SELECT quantity value FROM cnine_user_inventory WHERE user_id=4614 AND item_code='SUIT_CORE_5'"),10);
    assert.equal(await scalar(f.pg,"SELECT unseen_quantity value FROM cnine_user_inventory WHERE user_id=4614 AND item_code='SUIT_CORE_5'"),10);
    assert.equal(await scalar(f.pg,"SELECT count(*) value FROM coin_logs WHERE reason='WORKSHOP_S_BODY_POLICY_REFUND_20260930'"),1);
    assert.equal(await scalar(f.pg,"SELECT count(*) value FROM inventory_logs WHERE reason='WORKSHOP_S_BODY_POLICY_REFUND_20260930'"),1);
    assert.equal(await scalar(f.pg,"SELECT count(*) value FROM admin_logs WHERE action_type='OPS_S_BODY_CHOICE_REFUND'"),1);
    assert.equal((await f.pg.query('SELECT value FROM app_meta WHERE key=$1',[S_BODY_REFUND_KEY])).rows[0].value.includes('COMPLETED'),true);
    assert.equal((await f.pg.query("SELECT status FROM workshop_craft_receipts_v1668 WHERE request_id='original-s-body-request'")).rows[0].status,'COMPLETED');
    const replay=await refundSBodyChoiceAttempt(f.env,{id:1,role:'OWNER'},99);
    assert.equal(replay.replayed,true);
    assert.equal(await scalar(f.pg,"SELECT count(*) value FROM coin_logs WHERE reason='WORKSHOP_S_BODY_POLICY_REFUND_20260930'"),1);
  }finally{await f.close()}
});

test('wrong target and unauthorized operator cannot refund',async()=>{
  const f=await fixture();
  try{
    await assert.rejects(refundSBodyChoiceAttempt(f.env,{id:2,role:'USER'},99),/OWNER/);
    await assert.rejects(refundSBodyChoiceAttempt(f.env,{id:1,role:'OWNER'},100),/대상 제작 기록/);
    await f.pg.exec("UPDATE workshop_craft_logs_v1668 SET success=1 WHERE id=99");
    await assert.rejects(refundSBodyChoiceAttempt(f.env,{id:1,role:'OWNER'},99),/성공한 제작/);
    assert.equal(await scalar(f.pg,'SELECT count(*) value FROM app_meta'),0);
  }finally{await f.close()}
});

test('ledger failure rolls back both refunds and one-time marker',async()=>{
  const f=await fixture({breakItemLog:true});
  try{
    await assert.rejects(refundSBodyChoiceAttempt(f.env,{id:1,role:'OWNER'},99),/injected refund ledger failure/);
    assert.equal(await scalar(f.pg,'SELECT coin value FROM users WHERE id=4614'),2654937684055);
    assert.equal(await scalar(f.pg,"SELECT quantity value FROM cnine_user_inventory WHERE item_code='SUIT_CORE_5'"),0);
    assert.equal(await scalar(f.pg,'SELECT count(*) value FROM app_meta'),0);
    assert.equal(await scalar(f.pg,"SELECT count(*) value FROM coin_logs WHERE reason='WORKSHOP_S_BODY_POLICY_REFUND_20260930'"),0);
    assert.equal(await scalar(f.pg,'SELECT count(*) value FROM admin_logs'),0);
  }finally{await f.close()}
});

test('admin ledger exposes the targeted, idempotent refund control',()=>{
  const client=readFileSync(new URL('../admin/workshop-admin-v1668.js',import.meta.url),'utf8');
  assert.match(client,/data-s-body-refund-log/);
  assert.match(client,/REFUND_S_BODY_POLICY_20260930/);
  assert.match(client,/state\.sBodyRefund\?\.status==='COMPLETED'/);
});
