import test from 'node:test';import assert from 'node:assert/strict';import {PGlite} from '@electric-sql/pglite';
import baseline from './fixtures/world-raid-cms-20261008.json' with {type:'json'};
import {applyWorldRaidRenewal,OPERATION_KEY} from '../scripts/ops/world-raid-renewal-20261008.mjs';
async function fixture(t){const c=new PGlite();t.after(()=>c.close());await c.exec(`CREATE TABLE app_meta(key TEXT PRIMARY KEY,value TEXT,updated_at TEXT);CREATE TABLE raid_bosses(id BIGINT PRIMARY KEY,name TEXT,max_hp BIGINT,defense_rate INT,is_active BIGINT,updated_at TEXT);CREATE TABLE users(id BIGINT PRIMARY KEY,role TEXT,status TEXT);INSERT INTO users VALUES(1,'OWNER','ACTIVE');CREATE TABLE raid_instance_v1293(instance_id BIGINT PRIMARY KEY,settings_json TEXT);INSERT INTO raid_instance_v1293 VALUES(1,'{"bossAttackIntervalMs":30000,"bossProfile":{"maxHp":700000000}}');CREATE TABLE admin_logs(id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,admin_id BIGINT,action_type TEXT,target_type TEXT,target_id TEXT,before_data TEXT,after_data TEXT);`);
 for(const r of baseline.meta)await c.query('INSERT INTO app_meta(key,value) VALUES($1,$2)',[r.key,r.value]);for(const r of baseline.bosses)await c.query('INSERT INTO raid_bosses(id,name,max_hp,defense_rate,is_active) VALUES($1,$2,$3,$4,$5)',Object.values(r));return c;}
const proof={commit:true,releaseCommit:'a'.repeat(40)};
test('CMS dry run, atomic commit and retry preserve existing rooms, rewards and entry policy',async t=>{const c=await fixture(t);const before=(await c.query('SELECT * FROM raid_instance_v1293')).rows;const dry=await applyWorldRaidRenewal(c);assert.equal(dry.committed,false);assert.equal((await c.query('SELECT * FROM admin_logs')).rows.length,0);assert.equal(Number((await c.query('SELECT max_hp FROM raid_bosses WHERE id=4')).rows[0].max_hp),700000000);
 const done=await applyWorldRaidRenewal(c,proof);assert.equal(done.committed,true);assert.deepEqual((await c.query('SELECT * FROM raid_instance_v1293')).rows,before);assert.equal((await c.query('SELECT value FROM app_meta WHERE key=$1',['raid_settings_v1'])).rows[0].value,baseline.meta[0].value);assert.equal((await applyWorldRaidRenewal(c,proof)).replayed,true);assert.equal((await c.query('SELECT * FROM admin_logs')).rows.length,1);assert.equal((await c.query('SELECT * FROM app_meta WHERE key=$1',[OPERATION_KEY])).rows.length,1);
});
test('CMS conflict and late audit failure roll back all three bosses and settings',async t=>{const c=await fixture(t);await c.query("UPDATE app_meta SET value='{}' WHERE key='raid_settings_v1'");await assert.rejects(()=>applyWorldRaidRenewal(c,proof),/CMS changed/);await c.query('UPDATE app_meta SET value=$1 WHERE key=$2',[baseline.meta[0].value,baseline.meta[0].key]);await c.exec("ALTER TABLE admin_logs ADD CONSTRAINT reject_test CHECK(action_type<>'WORLD_RAID_RENEWAL')");await assert.rejects(()=>applyWorldRaidRenewal(c,proof),/reject_test/);assert.deepEqual((await c.query('SELECT key,value FROM app_meta ORDER BY key')).rows,baseline.meta);assert.deepEqual((await c.query('SELECT max_hp FROM raid_bosses ORDER BY id')).rows.map(r=>Number(r.max_hp)),[700000000,750000000,800000000]);});
