import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs/promises';import sharp from'sharp';import{createHash}from'node:crypto';import{fileURLToPath}from'node:url';import{MODES,sample,areaHits,STRIKE}from'./motion.mjs';
const file=p=>fileURLToPath(new URL(p,import.meta.url)),hash=b=>createHash('sha256').update(b).digest('hex'),read=async p=>JSON.parse(await fs.readFile(file(p))),m=await read('manifest.json'),a=await read('approval-20261009.json'),w=m.weapon;
test('approved source and grade, preview release gates',async()=>{assert.equal(hash(await fs.readFile(file('../..'+m.sourceArt))),a.sha256.toLowerCase());assert.equal(m.sourceArtSha256,a.sha256.toLowerCase());assert.equal(a.sourceArtStatus,'USER_APPROVED');assert.equal(a.grade,'SSS');assert.equal(m.edition,'LIMITED');for(const k of ['runtimeEnabled','acquisitionEnabled','formationEnabled','balanceConfigured'])assert.equal(a[k],false);assert.equal(m.runtimeEnabled,false);});
test('all visible weapon pixels match the approved original, hidden grip declared separately',async()=>{
const raw=await sharp(file(w.source)).ensureAlpha().raw().toBuffer({resolveWithObject:true}),v=await sharp(file('assets/locked/v2/original-visible-weapon.png')).ensureAlpha().raw().toBuffer(),full=await sharp(file(w.url)).ensureAlpha().raw().toBuffer();let n=0;
for(let y=0;y<w.height;y++)for(let x=0;x<w.width;x++){const i=(y*w.width+x)*4;if(v[i+3]===0)continue;const o=((y+w.rect.top)*raw.info.width+x+w.rect.left)*4;assert.deepEqual(v.subarray(i,i+4),raw.data.subarray(o,o+4));assert.deepEqual(full.subarray(i,i+4),v.subarray(i,i+4));n++;}
assert.equal(n,w.copiedPixels);assert.equal(w.completion.scope,'ONLY_HANDLE_HIDDEN_BY_ORIGINAL_FINGERS');assert.equal(w.redrawnVisiblePixels,0);assert.equal(hash(await fs.readFile(file(w.url))),w.sha256);});
test('one rigid full sword and original hand occlusion in every packed pose',async()=>{let n=0;for(const s of Object.values(m.motion)){assert.equal(hash(await fs.readFile(file(s.url))),s.sha256);for(const f of s.frames){assert.equal(f.weapon.sourceSha256,w.sha256);assert.equal(f.weapon.gripOcclusion,'BODY_THEN_SINGLE_SWORD_THEN_REGISTERED_SOURCE_HAND');assert.ok(Object.values(f.margin).every(x=>x>=12));assert.equal(hash(await fs.readFile(file(f.file))),f.sha256);const meta=await sharp(file(f.file)).metadata();assert.equal(meta.width,768);assert.equal(meta.height,768);assert.equal(meta.hasAlpha,true);n++;}}assert.equal(n,37);assert.equal(m.rejectedFrames.length,3);});
test('all ten active effects have twelve padded actual alpha frames',async()=>{let n=0;for(const k of m.activeEffects){const e=m.effects[k];assert.equal(e.frames.length,12);assert.equal(new Set(e.frames.map(f=>f.sha256)).size,12);assert.equal(hash(await fs.readFile(file(e.url))),e.sha256);for(const f of e.frames){const bytes=await fs.readFile(file(f.file));assert.equal(hash(bytes),f.sha256);const {data,info}=await sharp(bytes).ensureAlpha().raw().toBuffer({resolveWithObject:true});assert.equal(info.width,384);for(let y=0;y<384;y++)for(let x=0;x<384;x++)if(x<12||x>=372||y<12||y>=372)assert.equal(data[(y*384+x)*4+3],0);n++;}}assert.equal(n,120);assert.ok(!m.activeEffects.includes('skill'));assert.ok(!m.activeEffects.includes('ultimate'));});
test('all actions reference valid body drawings and distinct timing',()=>{const active=new Set();for(const [key,s]of Object.entries(MODES)){assert.ok(s.duration>0);for(const p of s.poses){assert.ok(m.motion[p.bank].frames[p.index]);active.add(p.bank+':'+p.index);}assert.equal(sample(key,s.duration).done,true);}assert.equal(active.size,25);assert.equal(MODES.skill.contacts.length,7);const hits=areaHits([{x:0,y:0},{x:100,y:0},{x:100,y:100}],{x:0,y:0},100);assert.ok(hits.every(h=>h.at>STRIKE));assert.ok(hits[2].at>hits[0].at);});
test('preview bundle contains only one existing V3 renderer and clock',async()=>{const b=await read('build-report.json');assert.equal(b.pixiCopies,1);assert.equal(b.gsapCopies,1);assert.equal(b.previewOnly,true);assert.equal(b.bundleSha256,hash(await fs.readFile(file('preview.bundle.js'))));assert.ok(b.sharedRuntime.some(s=>s.endsWith('/BattleEngine.js')));});
