// Native public archive. The independent art-review preview remains unchanged.
export function publicCodexHtml(){return `<!doctype html>
<html lang="ko" data-codex-mode="public">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#080c17"><meta name="color-scheme" content="dark"><title>용병도감 · 숲켓몬</title><link rel="icon" href="/assets/ui/pwa-icon.svg"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:ital,wght@0,500;0,600;0,700;0,800;1,700;1,800&amp;family=Noto+Sans+KR:wght@400;500;600;700;800;900&amp;display=swap" rel="stylesheet"><link rel="stylesheet" href="/mercenary-codex/style.css?v=2098.1"><link rel="stylesheet" href="/css/adventure-navigation-standalone.css?v=2108"><script defer src="/js/soopketmon-v21-exact-shell-adapter.js?v=2108-shared-navigation&amp;coup=2115" data-enabled="false"></script><script defer src="/js/adventure-lobby-v2107.js?v=2108-shared-navigation&amp;coup=2115"></script><script defer src="/js/adventure-navigation-standalone.js?v=2108" data-route="mercenaryDex"></script></head>
<body><a class="skip-link" href="#catalogControls">용병 검색으로 바로가기</a>
<div class="archive-ribbon"><i></i><b>MERCENARY ARCHIVE</b><span>다섯 장의 덱, 하나의 새로운 전력</span></div>
<div class="archive-shell">
<header class="topbar"><a class="brand" href="/?screen=home" aria-label="숲켓몬 로비로 돌아가기"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 8V3h5m8 0h5v5M3 16v5h5m8 0h5v-5M8 6v12l8-6Z"/></svg><span>숲켓몬<small>MERCENARY DIVISION</small></span></a><nav aria-label="현재 위치"><span>도감</span><i>/</i><b>용병도감</b></nav><a id="lobbyReturn" class="lobby-return" href="/?screen=home">로비로 돌아가기 ↗</a></header>
<main><div class="page-heading"><div class="heading-title"><span class="heading-index">02</span><div><p class="eyebrow">BUILD YOUR NEXT LINEUP</p><h1>용병도감</h1></div><span class="heading-tag">PROJECT V</span></div><a class="quiet-link" href="/equipment-forge/">장비 강화 ↗</a></div>
<section class="archive-status" aria-label="도감 현황"><div><i></i><b>도감 공개 중</b><span id="catalogStatus" role="status">최신 용병 정보를 확인하고 있습니다.</span></div><span class="formation-tag">일반 5장 <em>+</em> 용병 1장</span></section>
<div class="workspace-heading"><h2><span>⌁</span> 용병 명단 <small>ARCHIVE</small></h2><div class="archive-counters"><span>전체 <b id="totalCount">—</b></span><span>배정 스킬 <b id="skillCount">—</b></span><button id="refreshCatalog" type="button" aria-label="최신 도감 정보 새로고침">새로고침 ↻</button></div></div>
<section class="archive-workspace" aria-label="용병 명단과 전투 정보">
<aside class="catalog-panel"><div class="panel-heading"><h2>용병 선택</h2><span id="resultCount" role="status">—</span></div>
<div id="catalogControls" class="catalog-controls"><label class="search-field"><span class="sr-only">용병 이름·코드·스킬 검색</span><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></svg><input id="search" type="search" placeholder="이름 · 코드 · 스킬 검색" maxlength="80" autocomplete="off"></label>
<div id="positions" class="position-filters" role="group" aria-label="전투 위치"><button data-position="" aria-pressed="true">전체</button><button data-position="FRONT" aria-pressed="false">전열</button><button data-position="MIDDLE" aria-pressed="false">중열</button><button data-position="REAR" aria-pressed="false">후열</button></div>
<div class="filter-row"><label><span class="sr-only">등급 필터</span><select id="rank"><option value="">모든 등급</option><option>C</option><option>B</option><option>A</option><option>S</option><option>SS</option><option>SSS</option></select></label><label><span class="sr-only">정렬</span><select id="sort"><option value="code">등록순</option><option value="newest">최신순</option><option value="name">이름순</option><option value="power">전투력순</option></select></label><button id="savedOnly" type="button" aria-pressed="false" aria-label="즐겨찾기만 보기">☆</button></div></div>
<ul id="cardGrid" class="roster-list" aria-label="용병 목록" aria-busy="true"><li class="empty-state">용병 명단을 불러오는 중…</li></ul><div class="catalog-foot"><span>선택한 용병의 전투 정보를 확인하세요.</span><small>즐겨찾기는 이 브라우저에 저장됩니다.</small></div></aside>
<section id="inspection" class="inspection" aria-label="선택한 용병"><div class="empty-selection"><span>PROJECT V</span><h2>당신의 다음 전력을<br>확인하세요.</h2><p>용병을 선택하면 원화와 스킬을 볼 수 있습니다.</p></div></section>
</section>
<section class="archive-guide"><div><span>DEPLOYMENT CONTRACT</span><h2>다섯 장의 덱에, 한 명의 동료.</h2><p>PVE와 PVP가 하나의 용병 전용 슬롯을 함께 사용합니다.<br>용병을 편성하지 않으면 기존 일반 카드 5장으로 출전합니다.</p></div><div class="guide-actions"><a class="primary-link" href="/mercenary-hangar/">내 용병 편성 <span>↗</span></a><a class="quiet-link" href="/?screen=buy&amp;pack=hyper">하이퍼팩 개봉 ↗</a></div></section>
<footer class="page-footer"><span>SOOPKETMON <i>/</i> MERCENARY ARCHIVE</span><p>카드 원화 · 전투 SD · 현재 배정 스킬</p></footer></main></div>
<dialog id="artDialog" class="art-dialog" aria-label="용병 원본 확대 보기"><header><strong id="artTitle"></strong><button id="closeArt" type="button" aria-label="원본 확대 닫기">닫기 ×</button></header><img id="originalArt" alt=""></dialog><div id="toast" role="status" aria-live="polite" hidden></div><noscript><p>용병 정보를 보려면 JavaScript를 켜 주세요.</p></noscript><script type="module" src="/mercenary-codex/app.mjs?v=2098&amp;strength=2103"></script></body></html>
`;}
