const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const nf=v=>Number(v).toLocaleString('ko-KR');
const files=['01-front','02-champions','03-regular-season','04-players','05-club-reviews','06-data-desk'];
const marks={FM:'fm',삼성:'samsung',롯데:'lotte',LG:'lg',DK:'dk',한화:'hanwha',T1:'t1',DC:'dc'};
const logo=name=>`<img src="/assets/ui/clan/marks/${marks[name]}-clan-mark-v1.webp" alt="${esc(name)} 클랜 문장">`;
const hero=(file,caption,kind='')=>`<figure class="hero ${kind}"><img src="assets/${file}.png" alt="${esc(caption)}"><figcaption>${caption} · AI 생성 컨셉 삽화</figcaption></figure>`;
const story=(title,paras)=>`<article class="article"><h3 class="article-title">${title}</h3>${paras.map(p=>`<p>${p}</p>`).join('')}</article>`;
const paper=(n,section,body)=>`<section class="paper" data-page="${n}" aria-label="${n}면 ${section}" ${n===1?'':'hidden'}><div class="paper-content"><div class="mast-top"><span>2026년 9월 14일 월요일</span><span>클랜전 시즌 1 결산 특별판 · 제1호</span></div><header class="masthead"><strong>숲켓몬 스포츠</strong><span>SOOPKETMON<br>THE CLAN JOURNAL</span></header><div class="section-line"><b>${section}</b><span>SEASON 01 / FINAL EDITION</span></div>${body}</div><footer class="folio"><span>숲켓몬 스포츠 · 시즌 1 특별판</span><span>운영 완료 기록 집계 · 2026.09.14 23시대 KST</span><b>${String(n).padStart(2,'0')}</b></footer></section>`;
const stat=(number,title,note='')=>`<div><b>${number}</b><span>${title}</span>${note?`<small>${note}</small>`:''}</div>`;
const trio=items=>`<div class="stat-trio">${items.map(x=>stat(...x)).join('')}</div>`;
function lineChart(points){const x=m=>90+m/60*810,y=v=>345-v/2100*285;return `<svg class="chart" viewBox="0 0 1092 410" role="img" aria-label="결승 10분 단위 누적점수. 40분에 롯데 1803, FM 1772. 종료 때 FM 1970, 롯데 1915.">${[0,500,1000,1500,2000].map(v=>`<line class="gridline" x1="90" x2="900" y1="${y(v)}" y2="${y(v)}"/><text x="74" y="${y(v)+7}" text-anchor="end">${nf(v)}</text>`).join('')}${points.map(p=>`<text x="${x(p.minute)}" y="381" text-anchor="middle">${p.minute}분</text>`).join('')}${[['fm','#176944'],['lotte','#902a4c']].map(([k,c])=>`<polyline points="${points.map(p=>`${x(p.minute)},${y(p[k])}`).join(' ')}" fill="none" stroke="${c}" stroke-width="5"/>${points.map(p=>`<circle cx="${x(p.minute)}" cy="${y(p[k])}" r="6" fill="${c}"/>`).join('')}`).join('')}<text x="930" y="52" style="fill:#176944;font-weight:800">FM 1,970</text><text x="930" y="87" style="fill:#902a4c;font-weight:800">롯데 1,915</text><line x1="630" x2="630" y1="80" y2="345" stroke="#902a4c" stroke-dasharray="6 5"/><text x="615" y="34" text-anchor="middle" style="fill:#902a4c">40분 · 롯데 31점 앞서</text></svg>`;}
async function main(){
 const response=await fetch('facts.json');if(!response.ok)throw Error('집계 자료를 불러오지 못했습니다.');const d=await response.json();
 const reg=d.players.filter(p=>p.scope==='REGULAR'),fin=d.players.filter(p=>p.scope==='FINAL');
 const standings=`<div class="table-wrap" tabindex="0" aria-label="정규시즌 순위표, 좁은 화면에서 가로 스크롤"><table class="standings"><thead><tr><th>순위</th><th>클랜</th><th>승점</th><th>승–패</th><th>누적점수</th><th>득실차</th><th>1 → 7R</th></tr></thead><tbody>${d.teams.map(t=>`<tr><td>${t.rank}</td><td><span class="club">${logo(t.name)}${t.name}</span></td><td><strong>${t.points}</strong></td><td>${t.wins}–${t.losses}</td><td>${nf(t.combat)}</td><td>${t.diff>0?'+':''}${nf(t.diff)}</td><td><span class="form">${t.form.map(x=>`<span class="${x==='L'?'loss':''}" aria-label="${x==='W'?'승':'패'}">${x}</span>`).join('')}</span></td></tr>`).join('')}</tbody></table></div>`;
 const ranking=`<div class="table-wrap" tabindex="0" aria-label="정규시즌 개인 순위표, 좁은 화면에서 가로 스크롤"><table class="rank-table"><thead><tr><th>순위</th><th>선수</th><th>클랜</th><th>합산 승–패</th><th>공격승</th><th>방어승</th><th>승률</th></tr></thead><tbody>${reg.slice(0,10).map((p,i)=>`<tr><td>${i+1}</td><td>${esc(p.name)}</td><td>${p.clan}</td><td>${p.wins}–${p.losses}</td><td>${p.attackWins}</td><td>${p.defenseWins}</td><td>${p.rate.toFixed(1)}%</td></tr>`).join('')}</tbody></table></div>`;
 const pages=[];
 pages.push(paper(1,'종합 · DOUBLE CROWN',`<span class="label">시즌 1 최종 결산 / 정규시즌 & 챔피언스리그</span><h1 class="headline jumbo"><em>FM,</em> 두 개의 왕관을 쓰다</h1><p class="deck">정규시즌 39점 차 정상, 챔스 결승 55점 차 역전승<br>롯데의 거센 추격 넘어… 시즌의 시작과 끝을 모두 차지했다</p>${hero('double-crown','정규시즌 황금 트로피와 챔피언스리그 백금 트로피. 두 우승의 주인은 FM이었다.')}${trio([['2관왕','정규시즌·챔스 동시 제패'],['6승 1패','FM 정규시즌 성적','승점 18 · 누적 전투점수 7,913'],['1,970','챔스 결승 FM 점수','롯데 1,915 · 최종 격차 55']])}<div class="columns">${story('39점으로 얻은 결승 직행권',[
 'FM이 숲켓몬 클랜전 시즌 1의 두 우승을 모두 가져갔다. 정규시즌 6승 1패로 삼성과 승점 18에 나란히 섰지만, 누적 전투점수에서 7,913 대 7,874로 앞섰다. 불과 39점이 정규시즌 우승과 챔스 결승 직행을 갈랐다.',
 '9월 14일 밤 열린 결승에서는 정규시즌에서 유일한 패배를 안겼던 롯데와 다시 만났다. FM은 최종 1,970 대 1,915로 승리하며 그 패배를 설욕하고 2관왕을 완성했다.'
 ])}${story('개인의 빛은 순위표 밖에도 있었다',[
 '챔스의 마지막 주인공은 FM이었지만, 시즌 전체를 한 클랜의 이야기로만 설명할 수는 없다. 롯데는 삼성까지 꺾고 결승에 올랐고, LG는 개막 3연패 뒤 4연승으로 반등했다.',
 '정규시즌 개인 공수 합산 최다승은 7위 T1의 음순이였다. 320승으로 개인 1위를 기록했다. 결승에서는 FM의 Moo날두가 70승으로 양 팀 최다승을 올렸다. 팀 성적과 개인의 활약이 서로 다른 장면을 만들었다.'
 ])}</div><div class="news-teasers"><div><b>40분의 열세를 지운<br>FM의 마지막 20분</b><small>챔스 결승 상세 리포트 → 02면</small></div><div><b>승점은 같았다<br>우승을 가른 것은 39점</b><small>정규시즌 순위·동률 분석 → 03면</small></div><div><b>우승팀 밖에서 나온<br>정규시즌 최다승 선수</b><small>음순이·Moo날두와 주요 선수 → 04면</small></div></div>`));
 pages.push(paper(2,'챔피언스리그 · FINAL REPORT',`<h1 class="headline">55점 차 결승전<br><em>마지막 20분, FM이 뒤집었다</em></h1><p class="deck">22시 40분 집계에서 롯데가 31점 앞서… 최종 승자는 FM</p>${hero('final-night','결승에서 마주한 FM과 롯데를 표현한 챔피언스리그 아레나.','small')}<div class="scoreline"><div class="score-club">${logo('FM')}FM</div><div class="score-number">1,970 : 1,915<small>2026.09.14 22:00–23:00 KST · FINAL</small></div><div class="score-club">${logo('롯데')}롯데</div></div><div class="columns">${story('31점 뒤지던 FM, 86점을 더 벌었다',[
 '결승은 후반에 방향을 바꿨다. 10분 단위 완료 기록을 합산하면 FM은 20분까지 56점 앞섰지만, 30분에는 차이가 9점으로 줄었다. 40분 집계에서는 롯데 1,803점, FM 1,772점. 롯데가 31점 리드를 잡았다.',
 'FM은 남은 20분에 198점을 더했고 롯데는 112점을 보탰다. 이 구간에서 벌어진 86점 차가 승부를 뒤집었다. 50분에는 FM이 11점 앞섰고, 종료 때 격차는 55점으로 늘었다.'
 ])}${story('삼성을 넘은 롯데, 두 번째 문턱에서 멈춰',[
 '앞선 21시 2·3위전에서는 롯데가 삼성에 1,876 대 1,774, 102점 차 승리를 거뒀다. 정규시즌 3위가 2위를 꺾고 결승에 오른 것이다. 정규시즌 삼성전 17점 차 패배도 되갚았다.',
 '롯데는 FM을 상대로도 끝까지 위협적이었다. 진짜디임과 불법사행산업신고센터가 공격 38승씩으로 결승 공동 최다 공격승을 기록했다. 롯데의 결승 준우승은 상위 두 클랜을 모두 흔든 결과였다.'
 ])}</div><hr class="rule"><div class="columns three">${story('결승의 중심, Moo날두',[
 'FM의 Moo날두는 공격 34승·방어 36승, 합산 70승 18패를 기록했다. 결승 전체 최다승과 최다 방어승을 함께 차지했다. 본 특집 결승 MVP로 선정했다.'
 ])}${story('더 많이 공격한 쪽은 롯데',[
 '공격 횟수는 롯데 967회, FM 924회였다. FM은 공격 523승, 롯데는 474승을 올렸다. 공격 승률 56.6% 대 49.0%가 점수 차를 설명한다.'
 ])}${story('화려한 공격, 단단한 방어',[
 '롯데의 진짜디임은 합산 69승, FM의 도댕은 67승으로 뒤를 이었다. 도댕의 방어 35승은 Moo날두에 이은 결승 2위였다.'
 ])}</div><div class="notes-band">결승 MVP는 편집부 선정입니다. 결승 점수는 공격 승리 3점·패배 1점으로 집계되며, 방어 승리는 개인 공수 기록에 포함됩니다. 10분 집계는 완료 영수증 기준으로 경기 중 실시간 화면의 갱신 시각과는 차이가 있을 수 있습니다.</div>`));
 pages.push(paper(3,'정규시즌 · THE TITLE RACE',`<h1 class="headline">같은 18점, <em>다른 결말</em></h1><p class="deck">FM과 삼성의 6승 1패… 누적 전투점수 39점이 우승을 갈랐다</p>${hero('league-race','여덟 클랜의 경쟁을 색으로 표현한 시즌 결산 삽화. 깃발은 상징적 연출이다.','slim')}<h2 class="subhead">정규시즌 최종 순위</h2>${standings}<p class="note">순위 기준: 승점 → 완료 경기 누적 전투점수 → 득실차 → 추가 동률 기준. W는 승리, L은 패배. 챔스 경기는 이 표에 포함하지 않았습니다.</p><div class="columns" style="margin-top:27px">${story('FM의 개막전 승리, 삼성의 6연승',[
 'FM은 첫 경기에서 삼성을 426 대 359로 이겼다. 삼성은 그 뒤 6경기를 모두 잡아 6승 1패로 시즌을 마쳤다. FM은 6라운드에서 롯데에 패했지만 최종 한화전을 2,078 대 1,581로 승리하며 누적점수 우위를 지켰다.',
 '두 팀의 맞대결 결과가 직접적인 동률 기준은 아니다. 공식 순위 계약에 따라 먼저 비교된 것은 누적 전투점수였다. FM 7,913점, 삼성 7,874점. 이 차이가 1위와 2위를 결정했다.'
 ])}${story('3위도 동률… LG는 4연승하고도 4위',[
 '롯데와 LG 역시 4승 3패, 승점 12로 같았다. LG는 마지막 롯데전에서 1,648 대 1,634로 이겼지만 누적 전투점수는 롯데 7,505점, LG 7,085점이었다. 420점 앞선 롯데가 마지막 챔스 티켓을 가져갔다.',
 'LG는 득실차가 +386으로 롯데의 +291보다 좋았다. 그러나 누적점수가 득실차보다 먼저 적용되는 규칙이므로 순위는 바뀌지 않았다. 시즌 내내 점수를 쌓는 일이 중요한 이유다.'
 ])}</div><div class="notes-band">경기별 원점수는 그대로 보존했습니다. 시즌 중 참가 점수와 행동력 규칙이 바뀌었으므로 후반의 큰 점수만으로 전력이 그만큼 상승했다고 단정하지 않았습니다.</div>`));
 pages.push(paper(4,'선수 분석 · PLAYERS OF THE SEASON',`<h1 class="headline">팀 순위를 넘어선 활약<br><em>음순이, 320승의 시즌</em></h1><p class="deck">공격 164승·방어 156승 모두 정규시즌 1위… T1에서 가장 빛났다</p><div class="split-feature"><img src="assets/player-honours.png" alt="T1 문장과 기록 노트로 표현한 개인 활약 특집 삽화"><div class="big-number"><b>음순이 · T1</b><strong>320</strong><span>정규시즌 공수 합산 승리<br>369전 320승 49패 · 승률 86.7%</span></div></div><p class="note">AI 생성 컨셉 삽화. 실제 선수의 모습이나 공식 수상 장면을 표현한 사진이 아닙니다.</p><div class="columns" style="margin:22px 0">${story('개인의 압도는 팀 순위와 달랐다',[
 'T1은 2승 5패로 7위에 머물렀다. 그러나 음순이는 정규시즌 공수 합산 320승으로 전체 선수 중 가장 많은 승리를 기록했다. 공격 164승, 방어 156승도 각각 1위다. 본 특집은 음순이를 정규시즌 MVP로 선정했다.'
 ])}${story('하이희야의 313승, 구와함의 299승',[
 'LG의 하이희야가 합산 313승으로 2위, DK의 구와함이 299승으로 3위였다. FM에서는 뽑기고수71이 297승으로 가장 많았다. 한화의 밍은 공격 160승으로 정규시즌 공격승 3위에 올랐다.'
 ])}</div><h2 class="subhead">정규시즌 개인 공수 합산 승리 TOP 10</h2>${ranking}<div class="honours"><article><span class="micro-title">결승 MVP · 편집부 선정</span><h3>FM Moo날두 · 70승</h3><p>공격 34승과 방어 36승. 결승 최다 합산승·최다 방어승을 기록하며 우승 클랜의 중심에 섰다. 승률은 79.5%였다.</p></article><article><span class="micro-title">결승 공격 부문 공동 최다승</span><h3>진짜디임 · 불법사행산업신고센터</h3><p>두 선수 모두 롯데 소속으로 공격 38승. 공격 기록은 각각 43전 38승, 44전 38승이다. 팀의 준우승 속에서도 공격력은 결승 최고였다.</p></article></div><div class="notes-band">MVP는 본 특집의 기록 기반 선정으로, 게임 공식 수상·보상과 별개입니다. 개인 승수는 공격과 방어를 합산했습니다. 정규시즌과 챔스는 경기 수가 달라 분리했고, 표의 승률은 합산 승수 ÷ 합산 교전 수입니다. ‘하이희야’는 운영 기록의 해당 닉네임 그대로 표기했습니다.</div>`));
 const reviews=[
 ['FM','1위 · 6승 1패 · 챔스 우승','두 번의 접전, 두 번의 정상','정규시즌과 챔스를 모두 잡았다. 정규시즌에서는 뽑기고수71의 297승이 클랜 최다였고, 결승에서는 Moo날두의 70승이 빛났다. 한 선수만의 시즌이 아니라 서로 다른 무대에서 주인공이 바뀐 2관왕이었다.','주목: 뽑기고수71 · Moo날두'],
 ['삼성','2위 · 6승 1패 · 챔스 2·3위전 탈락','6연승의 저력, 남은 것은 39점','개막 FM전 패배 뒤 정규시즌을 6연승으로 끝냈다. 우승과의 누적점수 차는 39점이었다. 챔스에서는 강구열이 양 팀 최다인 합산 70승을 올렸지만 롯데에 102점 차로 패했다. 팀의 다음 과제는 짧은 토너먼트의 마무리다.','주목: 씨나인택갓 · 강구열'],
 ['롯데','3위 · 4승 3패 · 챔스 준우승','우승 후보를 가장 불편하게 만든 팀','정규시즌에서 FM을 꺾은 유일한 클랜. 챔스에서는 삼성도 넘었다. 결승 우승에는 55점이 모자랐지만, 상위 두 팀을 흔든 경기력은 남았다. 본 특집이 선정한 시즌의 다크호스다.','주목: 대저동토마토 · 진짜디임'],
 ['LG','4위 · 4승 3패','개막 3연패 뒤, 전부 이겼다','초반 세 경기를 내준 뒤 DK·T1·DC·롯데를 차례로 잡았다. 마지막 롯데전도 14점 차 승리였지만 누적점수에서 밀려 챔스 티켓을 놓쳤다. 개인 2위 하이희야와 282승의 폭군#이 반등을 뒷받침했다.','주목: 하이희야 · 폭군#'],
 ['DK','5위 · 3승 4패','누적점수 3위, 순위는 5위','정규시즌 7,532점은 FM·삼성 다음이다. 그러나 승점 9로 순위는 5위에 그쳤다. FM전 10점 차 패배가 아쉬운 장면이었다. 개인 3위 구와함과 라페스타다의 합산 286승은 다음 도전의 기반이다.','주목: 구와함 · 라페스타다'],
 ['한화','6위 · 3승 4패','3연승 출발, 후반이 남긴 숙제','첫 세 경기를 모두 이겼지만 이후 네 경기를 내줬다. 롯데와 DK에 각각 21점 차로 패한 승부가 뼈아팠다. 밍은 공격 160승으로 전체 3위였다. 강한 개인 공격력을 팀의 승리로 연결하는 일이 다음 시즌의 관전 포인트다.','주목: 밍 · 라네트'],
 ['T1','7위 · 2승 5패','최다승 선수를 품은 7위의 역설','음순이 320승, 치타구 281승에도 팀은 2승에 그쳤다. 롯데를 3점 차로 꺾고 LG에는 4점 차로 패하는 등 작은 차이가 희비를 갈랐다. 스타의 성과를 클랜 전체의 성적으로 넓힐 수 있을지가 관심사다.','주목: 음순이 · 치타구'],
 ['DC','8위 · 0승 7패','첫 승은 놓쳤지만, 기록은 남았다','시즌 승리를 올리지 못했다. 누적점수 6,355점, 득실차 −1,408이 팀의 과제를 드러냈다. 다만 라피e가 합산 239승, 설윤이가 222승을 기록했다. 이 개인 성과를 조직 전체의 경쟁력으로 연결하는 것이 재도약의 출발점이다.','주목: 라피e · 설윤이']
 ];
 pages.push(paper(5,'클랜별 결산 · EIGHT CLUBS, EIGHT STORIES',`<h1 class="headline">여덟 클랜, <em>서로 다른 시즌</em></h1><p class="deck">우승의 이유, 반등의 단서, 그리고 다음 시즌에 남긴 질문</p><div class="club-grid">${reviews.map(([name,record,title,text,stars])=>`<article class="club-story"><header>${logo(name)}<div><h3>${name}</h3><span>${record}</span></div></header><h4>${title}</h4><p>${text}</p><small>${stars}</small></article>`).join('')}</div><div class="notes-band">‘다크호스’와 다음 시즌 관전 포인트는 본 특집의 기록 기반 분석입니다. 선수 발언이나 인터뷰를 임의로 만들지 않았습니다.</div>`));
 const close=d.wars.filter(w=>w.round<1000).sort((a,b)=>Math.abs(a.scoreA-a.scoreB)-Math.abs(b.scoreA-b.scoreB)).slice(0,5);
 pages.push(paper(6,'데이터 특집 · BEHIND THE NUMBERS',`<h1 class="headline">숫자로 다시 읽는<br><em>시즌의 결정적 장면</em></h1><p class="deck">30경기, 34,104회의 완료 전투… 작은 차이가 큰 결말을 만들었다</p><h2 class="subhead">결승 누적점수 · 40분의 역전, 마지막 20분의 재역전</h2><div class="legend"><span><i></i>FM</span><span><i class="maroon"></i>롯데</span><span>10분 단위 완료 영수증 합산</span></div><div class="chart-scroll">${lineChart(d.timeline)}</div><div class="ledger"><div><strong>86점</strong><h3>FM이 마지막 20분에 번 차이</h3><p>40분 이후 FM 198점, 롯데 112점. 31점 열세가 최종 55점 우세로 바뀌었다.</p></div><div><strong>−43회</strong><h3>FM의 공격 횟수는 더 적었다</h3><p>FM 924회, 롯데 967회. 승리 공격 수는 FM이 49회 더 많아 점수에서 앞섰다.</p></div><div><strong>+7.6%p</strong><h3>결승 공격 승률의 차이</h3><p>FM 56.6%, 롯데 49.0%. 공격의 양과 성공률을 함께 봐야 결승 점수를 이해할 수 있다.</p></div></div><hr class="rule"><div class="columns"><article class="article"><h3 class="article-title">정규시즌의 가장 좁은 승부</h3>${close.map(w=>`<div class="close-match"><span>${w.round}R · ${w.a}–${w.b}</span><b>${nf(w.scoreA)}:${nf(w.scoreB)}</b><span>${Math.abs(w.scoreA-w.scoreB)}점 차</span></div>`).join('')}<p style="margin-top:16px">T1은 개막 롯데전을 3점 차로 이겼지만 LG전은 4점 차로 졌다. FM 역시 DK전에서 10점 차 승리를 거뒀다. 접전에서 남긴 한 번의 결과가 최종 승점에 쌓였다.</p></article>${story('같은 점수라도 맥락은 달랐다',[
 '정규시즌 28경기에서 완료된 전투는 30,445회였다. 챔스 2·3위전 1,768회와 결승 1,891회를 더하면 이번 특집의 집계 대상은 모두 34,104회다.',
 '시즌 중 점수와 행동력 규칙이 바뀌었다. 2라운드부터 공격 승리 3점·패배 1점이 적용됐고, 6라운드부터 공격 상한과 회복 규칙이 확대됐다. 후반의 높은 원점수를 초반과 단순 비교해 전력이 급증했다고 해석해서는 안 된다.'
 ])}</div><section class="method"><h3>이 특집은 이렇게 집계했습니다</h3><p><strong>팀 우승과 순위</strong>는 운영 DB의 완료된 시즌 정산·챔피언스리그 결과와 공식 순위 정렬 기준을 사용했습니다. 정규시즌과 챔스를 분리했습니다.</p><p><strong>개인 활약</strong>은 완료 전투의 공격·방어 승패를 각각 합산했습니다. 한 전투는 양 선수에게 1회씩 기록되며, 방어 참여를 직접 공격 횟수로 표현하지 않았습니다. MVP는 이 기준에 따른 편집부 선정입니다.</p><p><strong>기사와 이미지</strong>에서 우승·점수·닉네임은 집계 자료를 따랐습니다. 실제 인터뷰·현장 사진은 사용하지 않았으며, 우승 장면과 트로피 연출은 게임 공식 자산을 참고한 AI 생성 컨셉 삽화입니다.</p></section>`));
 document.getElementById('edition').innerHTML=pages.join('');
 if(new URLSearchParams(location.search).has('proof'))document.body.classList.add('proof');
 let current=1;
 const show=(n,scroll=true)=>{current=Math.max(1,Math.min(6,Number(n)||1));document.querySelectorAll('.paper').forEach(p=>p.hidden=Number(p.dataset.page)!==current);document.getElementById('page-select').value=String(current);document.getElementById('prev').disabled=current===1;document.getElementById('next').disabled=current===6;document.getElementById('download').href=`pages/${files[current-1]}.png`;history.replaceState(null,'',location.pathname+location.search+'#'+current);if(scroll)window.scrollTo({top:0,behavior:'instant'});};
 document.getElementById('prev').addEventListener('click',()=>show(current-1));document.getElementById('next').addEventListener('click',()=>show(current+1));document.getElementById('page-select').addEventListener('change',e=>show(e.target.value));window.addEventListener('hashchange',()=>show(location.hash.slice(1)));
 show(location.hash.slice(1)||1,false);window.newsEdition={ready:true,data:d,show};
}
main().catch(error=>{document.getElementById('edition').innerHTML=`<p class="loading">${esc(error.message)} 새로고침해 주세요.</p>`;console.error(error);});
