let token=localStorage.getItem('cnine_admin_token')||localStorage.getItem('cnine_card_api_token')||'';
let state={cards:[],members:[],users:[],role:'',view:'dashboard'};
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const img=v=>/^https?:\/\//i.test(v)?v:'../'+String(v||'').replace(/^\//,'');
async function api(path,opt={}){const r=await fetch('../api/'+path,{...opt,headers:{'content-type':'application/json','authorization':'Bearer '+token,...(opt.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'요청 실패');return d}
async function login(){try{const d=await api('auth/login',{method:'POST',body:JSON.stringify({privateKey:$('#key').value.trim()})});token=d.token;localStorage.setItem('cnine_admin_token',token);await boot()}catch(e){alert(e.message)}}
async function boot(){try{const d=await api('admin/dashboard');state.role=d.role;$('#login').hidden=true;$('#cms').hidden=false;$('#roleBadge').textContent=d.role;show('dashboard',d)}catch(e){$('#login').hidden=false;$('#cms').hidden=true;if(token)alert(e.message)}}
function show(view,prefetched){state.view=view;document.querySelectorAll('.view').forEach(x=>x.hidden=x.id!==`view-${view}`);document.querySelectorAll('#nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===view));$('#pageTitle').textContent={dashboard:'대시보드',cards:'카드관리',users:'유저관리',coupons:'쿠폰관리',logs:'관리자로그',settings:'설정'}[view];({dashboard:loadDashboard,cards:loadCards,users:loadUsers,coupons:loadCoupons,logs:loadLogs,settings:loadSettings}[view])(prefetched)}
async function loadDashboard(d){d=d||await api('admin/dashboard');const s=d.stats;$('#stats').innerHTML=[['전체 유저',s.users],['활성 카드',s.cards],['24시간 뽑기',s.draws24h],['전체 보유 코인',Number(s.totalCoin).toLocaleString()],['이용정지',s.banned],['활성 쿠폰',s.coupons]].map(x=>`<div class="stat"><small>${x[0]}</small><b>${x[1]}</b></div>`).join('')}
async function loadCards(){const d=await api('admin/cards');state.cards=d.cards;state.members=d.members;$('#memberId').innerHTML=d.members.map(m=>`<option value="${m.id}">${esc(m.name)}</option>`).join('');renderCards()}
function renderCards(){const q=$('#cardSearch').value.toLowerCase(),g=$('#grade').value;const list=state.cards.filter(c=>(!q||c.title.toLowerCase().includes(q)||c.name.toLowerCase().includes(q))&&(!g||c.grade===g));$('#cards').innerHTML=list.map(c=>`<article class="card" data-id="${c.id}"><img src="${esc(img(c.image))}" style="object-position:${c.focusX}% ${c.focusY}%"><div class="body"><div class="meta">${esc(c.name)} · ${c.id}</div><input class="title" value="${esc(c.title)}"><div class="row"><select class="member">${state.members.map(m=>`<option value="${m.id}" ${m.id==c.memberId?'selected':''}>${esc(m.name)}</option>`).join('')}</select><select class="rarity">${['SSR','UR','HR','SR','R','U','C'].map(r=>`<option ${r===c.grade?'selected':''}>${r}</option>`).join('')}</select></div><input class="image" value="${esc(c.image)}"><div class="row"><input class="fx" type="number" value="${c.focusX}"><input class="fy" type="number" value="${c.focusY}"></div><label><input class="active" type="checkbox" ${c.is_active?'checked':''}> 활성</label><div class="row"><button class="save">저장</button>${state.role==='OWNER'?'<button class="delete danger">삭제</button>':''}</div></div></article>`).join('');document.querySelectorAll('.card').forEach(el=>{el.querySelector('.save').onclick=()=>saveCard(el);el.querySelector('.delete')?.addEventListener('click',()=>deleteCard(el.dataset.id));})}
async function saveCard(el){const p={id:el.dataset.id,memberId:Number(el.querySelector('.member').value),title:el.querySelector('.title').value.trim(),grade:el.querySelector('.rarity').value,image:el.querySelector('.image').value.trim(),focusX:Number(el.querySelector('.fx').value),focusY:Number(el.querySelector('.fy').value),isActive:el.querySelector('.active').checked};await api('admin/cards',{method:'PATCH',body:JSON.stringify(p)});alert('저장 완료');await loadCards()}
async function deleteCard(id){if(!confirm('카드를 완전 삭제할까요?'))return;await api('admin/cards',{method:'DELETE',body:JSON.stringify({id})});await loadCards()}
async function addCard(){const p={memberId:Number($('#memberId').value),title:$('#cardTitle').value.trim(),grade:$('#cardGrade').value,image:$('#cardImage').value.trim(),focusX:Number($('#cardFx').value),focusY:Number($('#cardFy').value),isActive:true};await api('admin/cards',{method:'POST',body:JSON.stringify(p)});$('#cardDialog').close();await loadCards()}
async function loadUsers(){const q=$('#userSearch').value.trim();const d=await api('admin/users?q='+encodeURIComponent(q));state.users=d.users;$('#users').innerHTML=`<div class="tr head"><b>닉네임</b><b>가입일</b><b>최근접속</b><b>코인</b><b>카드</b><b>SSR</b><b></b></div>`+d.users.map(u=>`<div class="tr"><b>${esc(u.nickname)}<small> ${esc(u.role)}</small></b><span>${fmt(u.created_at)}</span><span>${fmt(u.last_login_at)}</span><span>${Number(u.coin).toLocaleString()}</span><span>${u.card_count||0}</span><span>${u.ssr_count||0}</span><button data-user="${u.id}">관리</button></div>`).join('');document.querySelectorAll('[data-user]').forEach(b=>b.onclick=()=>openUser(Number(b.dataset.user)))}
function openUser(id){const u=state.users.find(x=>x.id===id);$('#selectedUserId').value=id;$('#userDialogTitle').textContent=u.nickname;$('#userDetail').innerHTML=`<p>권한 <b>${u.role}</b> · 상태 <b class="status-${u.status}">${u.status}</b></p><p>보유코인 ${Number(u.coin).toLocaleString()} · 카드 ${u.card_count||0} · SSR ${u.ssr_count||0}</p>`;$('#userDialog').showModal()}
async function userAction(action){const userId=Number($('#selectedUserId').value),p={userId,action};if(action==='COIN'){p.amount=Number($('#coinAmount').value);p.reason=$('#coinReason').value.trim()}if(action==='BAN'){p.days=$('#banDays').value;p.reason=$('#banReason').value.trim()}if(!confirm('해당 작업을 실행할까요?'))return;await api('admin/users/action',{method:'POST',body:JSON.stringify(p)});$('#userDialog').close();await loadUsers();alert('처리 완료')}
async function resetKey(){const userId=Number($('#selectedUserId').value);if(!confirm('기존 개인키와 세션이 즉시 무효화됩니다. 계속할까요?'))return;const d=await api('admin/users/private-key-reset',{method:'POST',body:JSON.stringify({userId})});prompt('새 개인키입니다. 지금 복사하세요.',d.privateKey)}
async function loadCoupons(){const d=await api('admin/coupons');$('#coupons').innerHTML=`<div class="tr head"><b>코드</b><b>보상</b><b>사용량</b><b>시작</b><b>종료</b><b>상태</b><b></b></div>`+d.coupons.map(c=>`<div class="tr"><b>${esc(c.code)}</b><span>${Number(c.reward_coin).toLocaleString()}</span><span>${c.used_count}/${c.max_uses}</span><span>${fmt(c.starts_at)}</span><span>${fmt(c.ends_at)}</span><span>${c.is_active?'활성':'중지'}</span><button data-coupon="${c.id}" data-active="${c.is_active}">${c.is_active?'중지':'재개'}</button></div>`).join('');document.querySelectorAll('[data-coupon]').forEach(b=>b.onclick=()=>toggleCoupon(b))}
async function createCoupon(){const p={code:$('#couponCode').value,rewardCoin:Number($('#couponReward').value),maxUses:Number($('#couponMax').value),startsAt:toSql($('#couponStart').value),endsAt:toSql($('#couponEnd').value)};await api('admin/coupons',{method:'POST',body:JSON.stringify(p)});$('#couponCode').value='';await loadCoupons();alert('쿠폰 발급 완료')}
async function toggleCoupon(b){await api('admin/coupons',{method:'PATCH',body:JSON.stringify({id:Number(b.dataset.coupon),isActive:b.dataset.active!=='1'})});await loadCoupons()}
async function loadLogs(){const d=await api('admin/logs');$('#logs').innerHTML=d.logs.map(l=>`<div class="panel"><b>${esc(l.admin_nickname||'알 수 없음')}</b> · ${esc(l.action_type)} · ${esc(l.target_type)} #${esc(l.target_id)}<small> ${fmt(l.created_at)}</small>${l.after_data?`<pre>${esc(l.after_data)}</pre>`:''}</div>`).join('')}
async function loadSettings(){const d=await api('admin/settings');$('#newUserCoin').value=d.settings.new_user_coin||5000;$('#siteNotice').value=d.settings.site_notice||'';$('#maintenance').value=d.settings.maintenance_mode||'0';$('#saveSettingsBtn').disabled=state.role!=='OWNER'}
async function saveSettings(){await api('admin/settings',{method:'POST',body:JSON.stringify({new_user_coin:$('#newUserCoin').value,site_notice:$('#siteNotice').value,maintenance_mode:$('#maintenance').value})});alert('설정 저장 완료')}
const fmt=v=>v?String(v).replace('T',' ').slice(0,16):'-',toSql=v=>v?new Date(v).toISOString().replace('T',' ').slice(0,19):null;
$('#loginBtn').onclick=login;$('#logoutBtn').onclick=()=>{localStorage.removeItem('cnine_admin_token');location.reload()};document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>show(b.dataset.view));$('#cardSearch').oninput=renderCards;$('#grade').onchange=renderCards;$('#addCardBtn').onclick=()=>$('#cardDialog').showModal();$('#saveCardBtn').onclick=addCard;$('#userSearchBtn').onclick=loadUsers;$('#userSearch').onkeydown=e=>{if(e.key==='Enter')loadUsers()};document.querySelectorAll('#userDialog [data-action]').forEach(b=>b.onclick=()=>userAction(b.dataset.action));$('#resetKeyBtn').onclick=resetKey;$('#createCouponBtn').onclick=createCoupon;$('#saveSettingsBtn').onclick=saveSettings;if(token)boot();
