import {AXE_REWARDS,cleanAxeSettings} from '../js/golden-axe-model-v1.js';
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const kst=value=>value?new Date(Date.parse(value)+9*3600000).toISOString().slice(0,16):'';
let panel,revision=null,loaded=false,busy=false;
const token=()=>localStorage.getItem('cnine_admin_token')||sessionStorage.getItem('cnine_admin_token')||'';
const field=name=>panel.querySelector(`[name="${name}"]`),number=name=>field(name).value.trim()===''?null:Number(field(name).value);
async function api(body){const response=await fetch('/api/admin/golden-axe',{method:body?'PATCH':'GET',cache:'no-store',headers:{authorization:'Bearer '+token(),'content-type':'application/json'},...(body?{body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(30000)});const data=await response.json();if(!response.ok)throw Error(data.error||'설정 조회 실패');return data;}
function form(){return {revision,visible:field('visible').checked,enabled:field('enabled').checked,startsAt:field('startsAt').value?field('startsAt').value+':00+09:00':null,endsAt:field('endsAt').value?field('endsAt').value+':00+09:00':null,axeCost:number('axeCost'),dailyLimit:number('dailyLimit'),rates:Object.fromEntries(AXE_REWARDS.map(r=>[r.key,number(r.key)]))};}
function total(){const rates=AXE_REWARDS.map(r=>number(r.key)),sum=rates.reduce((s,v)=>s+(v??0),0),node=panel.querySelector('[data-total]');node.textContent=`확률 합계 ${Number(sum.toFixed(4))}% / 100% · 당첨 ${Number((sum-(number('MISS')??0)).toFixed(4))}% · 꽝 ${number('MISS')??'미설정'}${number('MISS')===null?'':'%'}${rates.includes(null)?' · 미설정 항목 있음':''}`;node.classList.toggle('axe-admin-error',rates.includes(null)||Math.abs(sum-100)>1e-6);}
async function update(save=false){if(busy)return;const output=panel.querySelector('output');let body;if(save){try{body=form();cleanAxeSettings(body);}catch(e){output.textContent=e.message;output.className='axe-admin-error';return;}}busy=true;panel.querySelectorAll('button').forEach(b=>b.disabled=true);output.className='';output.textContent=save?'설정을 저장하고 있습니다…':'운영 설정과 상품 지급 상태를 확인하고 있습니다…';try{const data=await api(body);revision=data.revision;loaded=true;for(const key of ['visible','enabled'])field(key).checked=data.settings[key];for(const key of ['startsAt','endsAt'])field(key).value=kst(data.settings[key]);for(const key of ['axeCost','dailyLimit'])field(key).value=data.settings[key]??'';for(const r of AXE_REWARDS)field(r.key).value=data.settings.rates[r.key]??'';for(const r of data.rewards){const node=panel.querySelector(`[data-ready="${r.key}"]`);node.textContent=r.available?'지급 준비됨':'지급 불가 · 카탈로그 확인';node.classList.toggle('axe-admin-error',!r.available);}total();output.textContent=`${save?'저장 완료 · ':''}${data.settings.enabled?'운영 ON · 지정 기간에만 참가 가능':'운영 OFF · 낡은도끼 차감 없음'} · ${data.complete?'필수 설정 완료':'기간·참가 수량·일일 횟수·확률을 설정하세요.'}`;}catch(e){output.textContent=e.message;output.className='axe-admin-error';}finally{busy=false;panel.querySelectorAll('button').forEach(b=>b.disabled=false);panel.querySelector('[data-save]').disabled=!loaded;}}
function coupon(){const nav=document.querySelector('#nav [data-view="coupons"]'),select=document.getElementById('couponRewardType');if(!nav||nav.hidden||!select){panel.querySelector('output').textContent='쿠폰관리 권한이 있는 관리자 계정으로 발급하세요.';return;}nav.click();select.value='PINGDU_OLD_AXE';select.dispatchEvent(new Event('change',{bubbles:true}));const amount=document.getElementById('couponRewardAmount');if(amount)amount.value='1';document.getElementById('couponCode')?.focus();}
function mount(){const target=document.getElementById('view-settings');if(!target||panel)return;panel=document.createElement('section');panel.id='goldenAxeAdmin';panel.className='axe-admin';panel.innerHTML=`<small>LIMITED EVENT · GOLDEN / SILVER AXE</small><h3>핑두의 금도끼 은도끼</h3><p>낡은도끼로 참가하고, 금도끼 당첨 연출 후 상품 1종을 즉시 지급합니다. 꽝에도 낡은도끼가 소모됩니다.<br>금도끼는 연출이며 별도 교환 아이템이 아닙니다. <b>초기 상태는 OFF · 확률은 모두 미설정</b>입니다.</p><div class="axe-admin-grid"><label>시작 일시 (KST)<input name="startsAt" type="datetime-local"></label><label>종료 일시 (KST)<input name="endsAt" type="datetime-local"></label><label>1회 낡은도끼 수량<input name="axeCost" type="number" min="1" max="1000000" step="1" placeholder="미설정"></label><label>계정당 일일 참가 횟수 · 0 = 무제한<input name="dailyLimit" type="number" min="0" max="100000" step="1" placeholder="미설정"></label></div><div class="axe-admin-flags"><label><input name="visible" type="checkbox"> 유저 메뉴에 공개</label><label><input name="enabled" type="checkbox"> 실제 참가·차감·지급 ON</label></div><div class="axe-admin-note"><p>확률은 <b>최종 등장확률(%)</b>입니다. H-BODY를 포함해 각 상품과 꽝을 직접 입력하세요. 합계가 정확히 100%여야 ON으로 저장됩니다. 일일 제한은 매일 <b>00시 KST</b>에 초기화됩니다.</p></div><div class="axe-admin-table"><table><thead><tr><th>당첨 상품</th><th>등장확률 (%)</th><th>지급 상태</th></tr></thead><tbody>${AXE_REWARDS.map(r=>`<tr><td><img src="${esc(r.image)}" alt="">${esc(r.name)}</td><td><input name="${r.key}" type="number" min="0" max="100" step="0.0001" placeholder="미설정" aria-label="${esc(r.name)} 확률"></td><td data-ready="${r.key}">확인 전</td></tr>`).join('')}</tbody></table></div><div class="axe-admin-total" data-total></div><p>배틀슈트는 새 장비 1개, 코인은 계정 잔액, S용병은 운영 S등급 중 균등 추첨한 1장으로 지급합니다. 중복 당첨도 동일하게 지급합니다.<br>슈퍼스타 +13 강화권·차량부품 150개 선택권은 즉시 인벤토리에 들어가며, 사용 시 대상을 선택합니다. 전직패스권은 기존 전직 화면에서 사용합니다.<br><b>참가 아이템: 낡은도끼 (PINGDU_OLD_AXE)</b> — 쿠폰관리 또는 유저관리에서 지급할 수 있습니다.</p><div class="admin-actions"><button type="button" data-coupon>낡은도끼 쿠폰 만들기</button><button type="button" data-load>다시 불러오기</button><button type="button" class="axe-admin-save" data-save disabled>이벤트 설정 저장</button><a href="/preview/golden-axe-v1/" target="_blank" rel="noopener">연출 검수 열기 ↗</a></div><output aria-live="polite"></output>`;target.querySelector('.sectionIntro')?.after(panel);if(!panel.isConnected)target.append(panel);panel.querySelector('[data-coupon]').onclick=coupon;panel.querySelector('[data-load]').onclick=()=>update();panel.querySelector('[data-save]').onclick=()=>update(true);panel.addEventListener('input',total);total();new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting)&&token()&&!loaded&&!busy)void update();}).observe(panel);}
mount();if(!panel){const observer=new MutationObserver(()=>{mount();if(panel)observer.disconnect();});observer.observe(document.body,{childList:true,subtree:true});}
