(()=>{
  const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
  let candidates=[],lastCriteria=null;
  const token=()=>localStorage.getItem('cnine_admin_token')||sessionStorage.getItem('cnine_admin_token')||'';
  async function request(path,opt={}){const r=await fetch('../api/'+path,{...opt,headers:{'content-type':'application/json','authorization':'Bearer '+token(),...(opt.headers||{})},cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'요청 실패');return d}
  const fmt=n=>Number(n||0).toLocaleString(),bytes=n=>{n=Number(n);if(!Number.isFinite(n))return '-';const u=['B','KB','MB','GB','TB'];let i=0;while(n>=1024&&i<u.length-1){n/=1024;i++}return `${n.toFixed(i>1?2:0)} ${u[i]}`};
  function busy(btn,on,text='처리 중...'){if(!btn)return;btn.disabled=on;if(!btn.dataset.old)btn.dataset.old=btn.textContent;btn.textContent=on?text:btn.dataset.old}
  function criteria(){return {dormantDays:Number($('#cleanupDormantDays').value),maxCards:Number($('#cleanupMaxCards').value),maxDraws:Number($('#cleanupMaxDraws').value),maxCoin:Number($('#cleanupMaxCoin').value),maxShards:Number($('#cleanupMaxShards').value),maxInventory:Number($('#cleanupMaxInventory').value),unverifiedOnly:$('#cleanupUnverifiedOnly').checked,excludeHighGrade:$('#cleanupExcludeHighGrade').checked,excludeActiveCaptain:true,limit:Number($('#cleanupLimit').value)}}
  async function loadSummary(){const b=$('#cleanupSummaryBtn');busy(b,true);try{const d=await request('admin/storage-cleanup/summary');$('#cleanupDbSize').textContent=bytes(d.pages?.sizeBytes);$('#cleanupReusable').textContent=bytes(d.pages?.reusableBytes);$('#cleanupUserCount').textContent=fmt(d.userCount);$('#cleanupBatchLimit').textContent=`${d.limits?.deleteBatch||10}명`;$('#cleanupSummaryState').textContent='현재 DB 페이지 기준 · 삭제 후 빈 페이지는 신규 데이터에 재사용됩니다.'}catch(e){alert(e.message)}finally{busy(b,false)}}
  const tableNames={user_cards:'카드 보유',draw_logs:'카드 추첨 기록',draw_request_receipts:'구형 대형 영수증',draw_request_receipts_v2:'신규 경량 영수증',coin_logs:'코인 기록',shard_logs:'조각 기록',inventory_logs:'인벤토리 기록',battle_logs:'PVE 기록',raid_damage_logs:'레이드 피해 기록',cube_drop_receipts:'큐브 영수증',user_messages:'메시지',pvp_match_history:'PVP 전투 기록',captain_match_history_v2:'대장전 기록'};
  function renderCandidates(d){candidates=d.candidates||[];const box=$('#cleanupCandidateList'),estimate=d.estimate||{total:0,tables:{}};$('#cleanupCandidateMeta').textContent=`후보 ${fmt(candidates.length)}명 · 연관 행 약 ${fmt(estimate.total)}건${d.truncated?' · 조회 제한 도달':''}`;$('#cleanupEstimate').innerHTML=Object.entries(estimate.tables||{}).filter(([,v])=>v>0).map(([k,v])=>`<span>${tableNames[k]||k} <b>${fmt(v)}</b></span>`).join(' · ')||'연관 데이터가 거의 없습니다.';box.innerHTML=`<div class="storageCandidate head"><span><input id="cleanupSelectAll" type="checkbox"></span><span>닉네임 / 최근 활동</span><span>카드</span><span>추첨</span><span>코인</span><span>조각</span><span>인벤</span><span>보호 상태</span></div>`+candidates.map(u=>`<label class="storageCandidate" data-id="${u.id}"><span><input class="cleanupUserCheck" type="checkbox" value="${u.id}" checked></span><b>${escapeHtml(u.nickname)}<small>${escapeHtml(u.activity_at||u.created_at||'')}</small></b><span>${fmt(u.card_count)}</span><span>${fmt(u.draw_count)}</span><span>${fmt(u.coin)}</span><span>${fmt(u.card_shards)}</span><span>${fmt(u.inventory_count)}</span><span class="${u.verified||u.high_grade_count?'risk':'safe'}">${u.verified?'인증 ':''}${u.high_grade_count?`상위 ${u.high_grade_count}`:'정리 가능'}</span></label>`).join('');$('#cleanupSelectAll')?.addEventListener('change',e=>$$('.cleanupUserCheck').forEach(x=>x.checked=e.target.checked));updateSelected()}
  function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
  function updateSelected(){const n=$$('.cleanupUserCheck:checked').length;$('#cleanupSelectedCount').textContent=`선택 ${n}명`}
  async function preview(){const b=$('#cleanupPreviewBtn');busy(b,true,'후보 분석 중...');try{lastCriteria=criteria();const d=await request('admin/storage-cleanup/preview',{method:'POST',body:JSON.stringify({criteria:lastCriteria})});renderCandidates(d)}catch(e){alert(e.message)}finally{busy(b,false)}}
  async function purgeSelected(){let ids=$$('.cleanupUserCheck:checked').map(x=>Number(x.value));if(!ids.length)return alert('삭제할 후보를 선택하세요.');const phrase=prompt(`선택한 ${ids.length}명의 계정과 연관 데이터를 영구 삭제합니다.\nOWNER·ADMIN·최근 활동 계정은 서버가 다시 차단합니다.\n\n계속하려면 휴면계정삭제 를 입력하세요.`,'');if(phrase!=='휴면계정삭제')return alert('삭제를 취소했습니다.');const btn=$('#cleanupDeleteBtn');busy(btn,true,'배치 삭제 중...');let done=0,total=ids.length;try{while(ids.length){const chunk=ids.splice(0,10),d=await request('admin/storage-cleanup/delete',{method:'POST',body:JSON.stringify({ids:chunk,criteria:lastCriteria||criteria(),confirmation:'휴면계정삭제'})});done+=Number(d.deletedUsers||0);chunk.forEach(id=>$(`.storageCandidate[data-id="${id}"]`)?.remove());const pct=Math.min(100,done/total*100);$('#cleanupProgressBar').style.width=pct+'%';$('#cleanupProgressText').textContent=`${done} / ${total}명 삭제 완료 · 현재 단계 ${Object.entries(d.changes||{}).filter(([,v])=>v).map(([k,v])=>`${k} ${v}`).slice(0,3).join(', ')}`}
      alert(`${done}명의 휴면·저활동 계정을 정리했습니다.\nDB 대시보드 용량 반영은 지연될 수 있으며 삭제된 페이지는 신규 데이터에 재사용됩니다.`);await loadSummary();
    }catch(e){alert(`정리 작업이 중단되었습니다. 완료된 배치는 유지됩니다.\n${e.message}`)}finally{busy(btn,false);updateSelected()}}
  function receiptOpts(){return {table:$('#cleanupReceiptTable').value,retentionDays:Number($('#cleanupReceiptDays').value),batchSize:Number($('#cleanupReceiptBatch').value)}}
  async function previewReceipts(){const b=$('#cleanupReceiptPreviewBtn');busy(b,true);try{const d=await request('admin/storage-cleanup/receipts/preview',{method:'POST',body:JSON.stringify(receiptOpts())});$('#cleanupReceiptPreview').innerHTML=`정리 가능 <b>${fmt(d.rows?.length)}</b>건 · 응답 JSON 약 <b>${bytes(d.estimatedBytes)}</b> · ${d.rows?.length?'오래된 완료 영수증만 대상':'현재 조건에 대상 없음'}`;$('#cleanupReceiptDeleteBtn').disabled=!(d.rows?.length)}catch(e){alert(e.message)}finally{busy(b,false)}}
  async function purgeReceipts(){const opts=receiptOpts(),phrase=prompt('오래된 완료·실패 영수증을 한 배치 정리합니다. PENDING 요청은 삭제하지 않습니다.\n\n계속하려면 영수증정리 를 입력하세요.','');if(phrase!=='영수증정리')return;const b=$('#cleanupReceiptDeleteBtn');busy(b,true,'영수증 삭제 중...');try{const d=await request('admin/storage-cleanup/receipts/delete',{method:'POST',body:JSON.stringify({...opts,confirmation:'영수증정리'})});alert(`${fmt(d.deleted)}건의 영수증을 정리했습니다.\n응답 JSON 기준 약 ${bytes(d.estimatedBytes)} 대상이었습니다.`);await previewReceipts();await loadSummary()}catch(e){alert(e.message)}finally{busy(b,false)}}
  document.addEventListener('DOMContentLoaded',()=>{const syncOwnerVisibility=()=>{const role=String($('#roleBadge')?.textContent||'').trim().toUpperCase();if(role)$('#storageCleanupPanel').hidden=role!=='OWNER'};new MutationObserver(syncOwnerVisibility).observe($('#roleBadge'),{childList:true,subtree:true});syncOwnerVisibility();$('#cleanupSummaryBtn')?.addEventListener('click',loadSummary);$('#cleanupPreviewBtn')?.addEventListener('click',preview);$('#cleanupDeleteBtn')?.addEventListener('click',purgeSelected);$('#cleanupCandidateList')?.addEventListener('change',updateSelected);$('#cleanupReceiptPreviewBtn')?.addEventListener('click',previewReceipts);$('#cleanupReceiptDeleteBtn')?.addEventListener('click',purgeReceipts)});
})();
