(()=>{
  const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
  let candidates=[],lastCriteria=null;
  const token=()=>localStorage.getItem('cnine_admin_token')||sessionStorage.getItem('cnine_admin_token')||'';
  async function request(path,opt={}){const r=await fetch('../api/'+path,{...opt,headers:{'content-type':'application/json','authorization':'Bearer '+token(),...(opt.headers||{})},cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'요청 실패');return d}
  const fmt=n=>Number(n||0).toLocaleString(),bytes=n=>{if(n===null||n===undefined||n==='')return '조회 불가';n=Number(n);if(!Number.isFinite(n))return '조회 불가';const u=['B','KB','MB','GB','TB'];let i=0;while(n>=1024&&i<u.length-1){n/=1024;i++}return `${n.toFixed(i>1?2:0)} ${u[i]}`};
  function busy(btn,on,text='처리 중...'){if(!btn)return;btn.disabled=on;if(!btn.dataset.old)btn.dataset.old=btn.textContent;btn.textContent=on?text:btn.dataset.old}
  function criteria(){return {dormantDays:Math.max(1,Number($('#cleanupDormantDays').value)||7)}}
  async function loadSummary(){const b=$('#cleanupSummaryBtn');busy(b,true);try{const d=await request('admin/storage-cleanup/summary');$('#cleanupDbSize').textContent=bytes(d.pages?.sizeBytes);$('#cleanupReusable').textContent=bytes(d.pages?.reusableBytes);$('#cleanupUserCount').textContent=fmt(d.userCount);$('#cleanupBatchLimit').textContent=`${d.limits?.deleteBatch||10}명`;$('#cleanupSummaryState').textContent=d.pages?.sizeSource==='D1_META'?'D1 실제 파일 크기 기준 · 삭제 후 빈 페이지는 신규 데이터에 재사용됩니다.':'DB 용량을 조회하지 못했습니다. Cloudflare D1 대시보드 수치를 확인하세요.'}catch(e){alert(e.message)}finally{busy(b,false)}}
  const tableNames={user_cards:'카드 보유',draw_logs:'카드 추첨 기록',draw_request_receipts:'구형 대형 영수증',draw_request_receipts_v2:'신규 경량 영수증',coin_logs:'코인 기록',shard_logs:'조각 기록',inventory_logs:'인벤토리 기록',battle_logs:'PVE 기록',raid_damage_logs:'레이드 피해 기록',cube_drop_receipts:'큐브 영수증',user_messages:'메시지',pvp_match_history:'PVP 전투 기록',captain_match_history_v2:'대장전 기록'};
  function renderCandidates(d){candidates=d.candidates||[];const box=$('#cleanupCandidateList'),days=Number(d.criteria?.dormantDays||criteria().dormantDays),x=d.excluded||{};$('#cleanupCandidateMeta').textContent=`${fmt(days)}일 이상 미접속 후보 ${fmt(candidates.length)}명${d.truncated?' · 최대 200명 표시':''}`;$('#cleanupEstimate').textContent=`최근 활동·유효 세션 ${fmt(Number(x.recentActivity||0)+Number(x.activeSession||0))}명, LIMITED 이상 ${fmt(x.limitedOrHigher||0)}명, +8강 이상 ${fmt(x.enhancedEightOrHigher||0)}명 자동 제외`;box.innerHTML=`<div class="storageCandidate head"><span><input id="cleanupSelectAll" type="checkbox"></span><span>닉네임 / 최종 활동</span><span>보유 카드 종류</span><span>보유 코인</span></div>`+candidates.map(u=>`<label class="storageCandidate" data-id="${u.id}"><span><input class="cleanupUserCheck" type="checkbox" value="${u.id}" checked></span><b>${escapeHtml(u.nickname)}<small>${escapeHtml(u.activity_at||u.created_at||'')}</small></b><span>${fmt(u.card_count)}</span><span>${fmt(u.coin)}</span></label>`).join('');if(!candidates.length)box.innerHTML+='<div class="storageEmpty">보호 조건을 제외한 삭제 후보가 없습니다.</div>';$('#cleanupSelectAll')?.addEventListener('change',e=>$$('.cleanupUserCheck').forEach(x=>x.checked=e.target.checked));updateSelected()}
  function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
  function updateSelected(){const n=$$('.cleanupUserCheck:checked').length;$('#cleanupSelectedCount').textContent=`선택 ${n}명`}
  async function preview(){const b=$('#cleanupPreviewBtn');busy(b,true,'후보 분석 중...');try{lastCriteria=criteria();const d=await request('admin/storage-cleanup/preview',{method:'POST',body:JSON.stringify({criteria:lastCriteria})});renderCandidates(d)}catch(e){alert(e.message)}finally{busy(b,false)}}
  async function purgeSelected(){let ids=$$('.cleanupUserCheck:checked').map(x=>Number(x.value));if(!ids.length)return alert('삭제할 후보를 선택하세요.');const phrase=prompt(`선택한 ${ids.length}명의 계정과 연관 데이터를 영구 삭제합니다.\n최근 활동·유효 세션·LIMITED 이상·+8강 이상 보유 계정은 서버가 삭제 직전에 다시 차단합니다.\n\n계속하려면 휴면계정삭제 를 입력하세요.`,'');if(phrase!=='휴면계정삭제')return alert('삭제를 취소했습니다.');const btn=$('#cleanupDeleteBtn');busy(btn,true,'배치 삭제 중...');let done=0,total=ids.length;try{while(ids.length){const chunk=ids.splice(0,10),d=await request('admin/storage-cleanup/delete',{method:'POST',body:JSON.stringify({ids:chunk,criteria:lastCriteria||criteria(),confirmation:'휴면계정삭제'})});done+=Number(d.deletedUsers||0);chunk.forEach(id=>$(`.storageCandidate[data-id="${id}"]`)?.remove());const pct=Math.min(100,done/total*100);$('#cleanupProgressBar').style.width=pct+'%';$('#cleanupProgressText').textContent=`${done} / ${total}명 삭제 완료 · 현재 단계 ${Object.entries(d.changes||{}).filter(([,v])=>v).map(([k,v])=>`${k} ${v}`).slice(0,3).join(', ')}`}
      alert(`${done}명의 휴면·저활동 계정을 정리했습니다.\nDB 대시보드 용량 반영은 지연될 수 있으며 삭제된 페이지는 신규 데이터에 재사용됩니다.`);await loadSummary();
    }catch(e){alert(`정리 작업이 중단되었습니다. 완료된 배치는 유지됩니다.\n${e.message}`)}finally{busy(btn,false);updateSelected()}}
  function receiptOpts(){return {table:$('#cleanupReceiptTable').value,retentionDays:Number($('#cleanupReceiptDays').value),batchSize:Number($('#cleanupReceiptBatch').value)}}
  function receiptMetrics(d){return d.metrics||{receiptRows:d.rows?.length||0,responseJsonRows:0,responseJsonBytes:Number(d.estimatedBytes||0),receiptPayloadBytes:Number(d.estimatedBytes||0),assertionRows:0,assertionPayloadBytes:0,estimatedTextBytes:Number(d.estimatedBytes||0),estimatedStorageBytes:Number(d.estimatedBytes||0)}}
  async function previewReceipts(){const b=$('#cleanupReceiptPreviewBtn');busy(b,true);try{const d=await request('admin/storage-cleanup/receipts/preview',{method:'POST',body:JSON.stringify(receiptOpts())}),m=receiptMetrics(d),count=Number(d.rows?.length||0);$('#cleanupReceiptPreview').innerHTML=count?`정리 가능 <b>${fmt(count)}</b>건 · 삭제 대상 전체 추정 <b>${bytes(m.estimatedStorageBytes)}</b><br><small>응답 JSON ${fmt(m.responseJsonRows)}건 / ${bytes(m.responseJsonBytes)} · 영수증 행 텍스트 ${bytes(m.receiptPayloadBytes)} · 지급 검증 ${fmt(m.assertionRows)}건 / ${bytes(m.assertionPayloadBytes)}</small>`:'현재 조건에 정리할 완료·실패 영수증이 없습니다.';$('#cleanupReceiptDeleteBtn').disabled=!count}catch(e){alert(e.message)}finally{busy(b,false)}}
  async function purgeReceipts(){const opts=receiptOpts(),phrase=prompt('오래된 완료·실패 영수증을 한 배치 정리합니다. PENDING 요청은 삭제하지 않습니다.\n\n계속하려면 영수증정리 를 입력하세요.','');if(phrase!=='영수증정리')return;const b=$('#cleanupReceiptDeleteBtn');busy(b,true,'영수증 삭제 중...');try{const d=await request('admin/storage-cleanup/receipts/delete',{method:'POST',body:JSON.stringify({...opts,confirmation:'영수증정리'})}),m=receiptMetrics(d);alert(`${fmt(d.deleted)}건의 영수증을 정리했습니다.\n\n응답 JSON: ${fmt(m.responseJsonRows)}건 / ${bytes(m.responseJsonBytes)}\n영수증 행 텍스트: ${bytes(m.receiptPayloadBytes)}\n지급 검증 기록: ${fmt(d.assertionsDeleted||m.assertionRows)}건 / ${bytes(m.assertionPayloadBytes)}\n삭제 대상 전체 추정: ${bytes(m.estimatedStorageBytes)}\n\n※ 위 수치는 행 데이터 추정치이며 D1 파일 용량 감소량과 동일하지 않습니다. 삭제된 페이지는 신규 데이터에 재사용될 수 있습니다.`);await previewReceipts();await loadSummary()}catch(e){alert(e.message)}finally{busy(b,false)}}
  document.addEventListener('DOMContentLoaded',()=>{const syncOwnerVisibility=()=>{const role=String($('#roleBadge')?.textContent||'').trim().toUpperCase();if(role)$('#storageCleanupPanel').hidden=role!=='OWNER'};new MutationObserver(syncOwnerVisibility).observe($('#roleBadge'),{childList:true,subtree:true});syncOwnerVisibility();$('#cleanupSummaryBtn')?.addEventListener('click',loadSummary);$('#cleanupPreviewBtn')?.addEventListener('click',preview);$('#cleanupDeleteBtn')?.addEventListener('click',purgeSelected);$('#cleanupCandidateList')?.addEventListener('change',updateSelected);$('#cleanupReceiptPreviewBtn')?.addEventListener('click',previewReceipts);$('#cleanupReceiptDeleteBtn')?.addEventListener('click',purgeReceipts)});
})();
