import {showMercenaryReceipt} from '/js/mercenary-pack-live.mjs?v=2098';
import {jointAccountRequest as api} from '/js/joint-account-transport.mjs';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt=n=>Number(n||0).toLocaleString('ko-KR');
let state,selected,busy=false;const pendingKey=()=>`cnine.mercenary.pending:${state?.accountId||''}`;const message=text=>$('message').textContent=text;
function show(){if(!state)return;const card=state.cards.find(c=>c.code===selected),blocked=busy||!state.available||Boolean(localStorage.getItem(pendingKey()));$('coin').textContent=fmt(state.coin);$('count').textContent=String(state.cards.length);$('slot').textContent=state.loadout.mercenaryCode?`${state.cards.find(c=>c.code===state.loadout.mercenaryCode)?.name||state.loadout.mercenaryCode} · 편성 중`:'용병 슬롯이 비어 있습니다.';
 $('roster').innerHTML=state.cards.map(c=>`<button data-code="${c.code}" aria-pressed="${selected===c.code}" ${busy?'disabled':''}><img src="/assets/ui/project-v/mercenaries/codex-v1/${c.code.toLowerCase()}-art-640.webp" alt="${esc(c.name)}" loading="lazy"><span class="rank">${esc(c.rank||'미정')}</span>${state.loadout.mercenaryCode===c.code?'<span class="active">편성</span>':''}<span class="card-caption"><b>${esc(c.name)}</b><small>Lv.${c.level} · 중복 ${c.duplicates}</small></span></button>`).join('')||'<p>아직 계약한 용병이 없습니다.</p>';
 $('selected-stats').hidden=!card;$('portrait').hidden=!card;if(card){$('portrait').src='/'+card.sourceArt;$('portrait').alt=card.name;$('name').textContent=card.name;$('rank').textContent=`${card.rank||'등급 미정'} CLASS`;$('serial').textContent=`PROJECT V / ${card.code}`;$('character-note').textContent='PVE·PVP 공통으로 출전하는 용병 전용 슬롯';$('level').textContent=card.level;$('duplicates').textContent=fmt(card.duplicates);$('power').textContent=fmt(card.basePower);}
 $('assigned-skills').hidden=!card; $('skill-list').innerHTML=card?(card.skills||[]).map(s=>`<article><h4>${esc(s.name)}</h4><p>${esc(s.effect)}</p><small>${esc(s.trigger)}</small>${s.review!=='REVIEWED'||Object.values(s.balance).some(v=>v===null)?'<em>스킬 수치 설정 대기</em>':''}</article>`).join('')||'<p>배정된 스킬이 없습니다.</p>':'';
 $('equip').disabled=blocked||!card||card.canDeploy===false||state.loadout.mercenaryCode===selected;$('equip').textContent=card?state.loadout.mercenaryCode===selected?'현재 편성된 용병':'선택 용병 편성':'용병 선택 대기';$('unequip').disabled=blocked||!state.loadout.mercenaryCode;
 const o=state.policy.opening,count=Number($('draw-count').value);$('draw-cost').textContent=o.paymentKind==='COIN'?`${count}회 · ${fmt(o.coinPerOpen*count)} 코인`:o.paymentKind==='ITEM'?`개봉권 ${fmt(o.itemsPerOpen*count)}장 사용`:'개봉 비용을 준비 중입니다.';$('open').disabled=busy||!(state.openingAvailable??state.available)||o.paymentKind==='UNSET'||count>o.maxBatch;$('open').textContent=o.paymentKind==='UNSET'?'개봉 준비 중':'용병카드 개봉';$('recover').hidden=!localStorage.getItem(pendingKey());
}
async function refresh(){try{state=await api('mercenaries/v3/state');if(!state.cards.some(c=>c.code===selected))selected=state.loadout.mercenaryCode||state.cards[0]?.code;show();}catch(e){message(e.message);$('slot').textContent='공동 업데이트 준비 중';$('roster').textContent=e.message;}}
async function run(action,body){if(busy)return;let pending;try{pending=JSON.parse(localStorage.getItem(pendingKey())||'null');}catch{}if(!pending){pending={action,body:{requestId:crypto.randomUUID(),...body}};localStorage.setItem(pendingKey(),JSON.stringify(pending));}busy=true;show();
 try{const result=await api(`mercenaries/v3/${pending.action}`,{method:'POST',body:pending.body});localStorage.removeItem(pendingKey());
  if(result.draws){void showMercenaryReceipt(result);$('draw-results').hidden=false;$('draw-list').innerHTML=result.draws.map(d=>`<p>${d.mercenaryCode?`${esc(d.name||state.cards.find(c=>c.code===d.mercenaryCode)?.name||d.mercenaryCode)} · ${d.rank} ${d.duplicate?`중복 +1 (누적 ${d.duplicateCount})`:'첫 계약'}`:d.outcomeId==='NONE'?'다음 계약을 기약합니다.':`${d.outcomeId==='MASTER_STAR'?'마스터의 별':'미스틱에너지'} ${fmt(d.quantity)}개`}</p>`).join('');}
  if(pending.action==='loadout')localStorage.setItem('cnine.mercenary.loadout.changed',String(Date.now()));
  message(result.replayed?'저장된 처리 결과를 복구했습니다.':'요청이 완료됐습니다.');await refresh();
 }catch(e){message(e.message);if(e.status>=400&&e.status<500&&!['JOINT_REQUEST_CONFLICT','MERCENARY_CLOSED'].includes(e.code))localStorage.removeItem(pendingKey());}
 finally{busy=false;show();}}
$('roster').onclick=e=>{const b=e.target.closest('[data-code]');if(b&&!busy){selected=b.dataset.code;show();}};$('draw-count').onchange=show;
$('equip').onclick=()=>run('loadout',{mercenaryCode:selected,revision:state.loadout.revision});$('unequip').onclick=()=>run('loadout',{mercenaryCode:null,revision:state.loadout.revision});
$('open').onclick=()=>void globalThis.MercenaryPack.open(Number($('draw-count').value));
window.addEventListener('mercenary-pack:complete',()=>void refresh());$('refresh').onclick=()=>{if(!busy)void refresh();};$('recover').onclick=()=>run();
await refresh();
window.addEventListener('mercenary-pack:availability',event=>{if(state){state.openingAvailable=event.detail?.userOpeningEnabled===true;show();}});
