(()=>{
  'use strict';
  sessionStorage.setItem('cnine:raid-content-v1924','core');
  const clone=value=>JSON.parse(JSON.stringify(value));
  const settings={mode:'TEST',title:'심연 관측소: 붕괴 코어',subtitle:'ABYSS OBSERVATORY / CORE PROTOCOL',description:'속성 약점을 분석하고 세 작전을 분담해 멸절 프로토콜을 차단하십시오.',bossName:'오메가 코어 · 아르케온',bossImage:'/assets/responsive/project-v/monsters/hunt-068-omega-09-sd-v1-768.webp',windowMinutes:20,dailyEntries:3,maxParticipants:30,bossMaxHp:300000000,analysisRequired:200,coreRequired:120,suppressionRequired:300,rewardLocked:true};
  const operations=[{key:'BREAK',name:'파쇄',label:'BREACH',roles:['ATTACK','SPEED'],description:'공격형·속도형 카드로 붕괴 코어의 외피를 파괴합니다.'},{key:'BLOCK',name:'차단',label:'INTERCEPT',roles:['DEFENSE'],description:'방어형 카드로 코어 간 에너지 연결을 차단합니다.'},{key:'STABILIZE',name:'안정화',label:'STABILIZE',roles:['HP'],description:'HP형·회복 카드로 폭주 에너지를 안정화합니다.'}];
  const coreBuffs=[{id:'GRAVITY_ARMOR',core:'BREAK',name:'초중력 외피',effect:'누적 피해 18% 경감',damageReductionPct:18},{id:'COUNTER_CURRENT',core:'BLOCK',name:'역류 전도체',effect:'누적 피해 14% 경감',damageReductionPct:14},{id:'REGEN_LOOP',core:'STABILIZE',name:'자가 복원 루프',effect:'누적 피해 16% 경감',damageReductionPct:16}];
  // Preview-only PVE snapshot. `image` is the live card/source art used by the
  // V3 roster; `battleSprite` is a separate battle-engine-only character asset.
  const deck=[
    {id:'CN-02D9DC1E8A8A4209',cardId:'CN-02D9DC1E8A8A4209',title:'철와대 킴성태',name:'킴성태',grade:'FUR',power_type:'ATTACK',power:62000,image:'/assets/NEWCARD/24.png',battleSprite:'/assets/ui/project-v/characters/fur/fur-cn-02d9dc1e8a8a4209-sd-v1.png'},
    {id:'CN-0505936A0CBB4E59',cardId:'CN-0505936A0CBB4E59',title:'구수댕',name:'남수댕',grade:'ZENITH',power_type:'DEFENSE',power:58000,image:'/assets/cards/남수댕/031.webp',battleSprite:'/assets/ui/project-v/characters/zenith/zenith-cn-0505936a0cbb4e59-sd-v1.png'},
    {id:'CN-25F931CE393D474E',cardId:'CN-25F931CE393D474E',title:'딤우스',name:'디임',grade:'ZENITH',power_type:'SPEED',power:56000,image:'/assets/cards/976467971.jpg',battleSprite:'/assets/ui/project-v/characters/zenith/zenith-cn-25f931ce393d474e-sd-v1.png'},
    {id:'CN-23EB4B19986D4818',cardId:'CN-23EB4B19986D4818',title:'Lionel Messi',name:'Lionel Messi',grade:'SUPERSTAR',power_type:'HP',power:60000,image:'/assets/superstar/3.jpg',battleSprite:'/assets/ui/project-v/characters/superstar/superstar-cn-23eb4b19986d4818-sd-v1.png'},
    {id:'CN-519C181C18DF4B8E',cardId:'CN-519C181C18DF4B8E',title:'토마토',name:'토마토',grade:'ZENITH',power_type:'ATTACK',power:54000,image:'/assets/cards/ZENITH/1.jpg',battleSprite:'/assets/ui/project-v/characters/zenith/zenith-cn-519c181c18df4b8e-sd-v1.png'}
  ];
  const challenge={challengeId:'QTE-PREVIEW-V1',weaknessCycle:['ATTACK','DEFENSE','SPEED','HP','ATTACK'],sequence:['UP','RIGHT','DOWN','LEFT','UP','RIGHT'],sequenceWindowMs:5500,mashTarget:24,mashWindowMs:5000};
  let state;
  function reset(){state={ok:true,settings,current:{id:'CORE-PREVIEW-001',status:'BATTLE',startsAt:new Date().toISOString(),endsAt:new Date(Date.now()+20*60000).toISOString(),bossName:settings.bossName,bossImage:settings.bossImage,bossHp:231000000,bossMaxHp:settings.bossMaxHp,participantCount:5,phase:1,phaseLabel:'코어 탐색',analysisScore:128,analysisRequired:settings.analysisRequired,coreScores:{BREAK:72,BLOCK:54,STABILIZE:46},coreRequired:settings.coreRequired,suppressionScore:80,suppressionRequired:settings.suppressionRequired,analysisReady:false,bossBuffs:[],bossDamageReductionPct:0},me:null,participants:[{userId:2,nickname:'선발대 알파',operation:'BREAK',status:'RESOLVED',mechanicScore:188,totalDamage:22800000},{userId:3,nickname:'방벽대 브라보',operation:'BLOCK',status:'RESOLVED',mechanicScore:174,totalDamage:19400000},{userId:4,nickname:'의무대 찰리',operation:'STABILIZE',status:'RESOLVED',mechanicScore:162,totalDamage:17100000}],entry:{date:'PREVIEW',used:0,limit:3,remaining:3},operations,serverNow:new Date().toISOString()}}
  reset();
  function battlePayload(){const boss={id:'MONSTER:CORE:ARCHEON',cardId:'MONSTER:CORE:ARCHEON',monsterId:'CORE-ARCHEON',name:settings.bossName,title:settings.bossName,image:settings.bossImage,image_url:settings.bossImage,grade:'BOSS',isBoss:true,mode:'RAID',contentType:'CORE_PROTOCOL',hp:100,maxHp:100,projectVMonsterArt:{scope:'BATTLE_ENGINE_ONLY',kind:'CORE_PROTOCOL_BOSS_SD',primaryUrl:settings.bossImage,pngFallbackUrl:settings.bossImage,footAnchor:{x:.5,y:.94},objectFit:'contain',objectPosition:'50% 100%',scaleMultiplier:1.15,approved:true,technicalPass:true}},timeline=[{type:'RAID_PHASE_CHANGE',phase:1,label:'1페이즈 · 코어 탐색'}];let hp=100;
    deck.forEach((card,index)=>{timeline.push({type:'RAID_WEAKNESS_REVEAL',weakness:challenge.weaknessCycle[index],matched:true,label:`약점 ${challenge.weaknessCycle[index]} · 분석 성공`});hp=Math.max(70,hp-6);timeline.push({type:index===2||index===4?'SKILL':'TURN',actorId:card.cardId,targetId:boss.cardId,damage:680000,targetHpAfter:hp,critical:true,label:'약점 공명 타격'})});
    timeline.push({type:'RAID_PHASE_CHANGE',phase:2,label:'2페이즈 · 삼중 코어 분리'},{type:'RAID_OPERATION_REVEAL',operation:state.me?.operation||'BREAK',label:`${state.me?.operation==='BLOCK'?'차단':state.me?.operation==='STABILIZE'?'안정화':'파쇄'} 작전 전개`},...coreBuffs.map(buff=>({type:'RAID_BOSS_BUFF',buffId:buff.id,core:buff.core,label:`${buff.name} 활성`,effect:buff.effect,damageReductionPct:buff.damageReductionPct})),{type:'SKILL',actorId:deck[0].cardId,targetId:boss.cardId,damage:920000,targetHpAfter:52,critical:true,label:'코어 기여 타격'},{type:'RAID_CORE_BREAK',operation:state.me?.operation||'BREAK',label:'작전 신호 전송'},{type:'RAID_PHASE_CHANGE',phase:3,label:'3페이즈 · 멸절 프로토콜'},{type:'RAID_QTE_SEQUENCE',qteId:'SEQUENCE',title:'방향 신호 추적',sequence:challenge.sequence,windowMs:challenge.sequenceWindowMs,label:'화면을 지정 방향으로 밀거나 방향키를 순서대로 입력하십시오.'},{type:'RAID_QTE_MASH',qteId:'MASH',title:'구속 파쇄',target:challenge.mashTarget,windowMs:challenge.mashWindowMs,label:'연타하여 즉사 구속을 파괴하십시오.'},{type:'RAID_STAGGER',qteCondition:'ALL_SUCCESS',label:'멸절 프로토콜 차단 · 코어 그로기'},{type:'SKILL',qteCondition:'ALL_SUCCESS',actorId:deck[0].cardId,targetId:boss.cardId,damage:2400000,targetHpAfter:4,critical:true,label:'공동 제압 반격'},{type:'BOSS_ULTIMATE',qteCondition:'ANY_FAILURE',actorId:boss.cardId,label:'멸절 프로토콜',hits:deck.map(card=>({targetId:card.cardId,damage:999999,targetHpAfter:0,critical:true}))},{type:'RESULT',qteCondition:'ALL_SUCCESS',winner:'A'},{type:'RESULT',qteCondition:'ANY_FAILURE',winner:'B'});timeline.forEach((event,index)=>event.seq=index+1);return {ok:true,mode:'RAID',battlefieldMode:'RAID',contentType:'CORE_PROTOCOL',monster:boss,challenge,battleV2:{teams:{A:{cards:deck},B:{cards:[boss]}},result:{timeline,winner:'PENDING',actions:timeline.length}}}}
  async function apiRequest(path,options={}){await new Promise(resolve=>setTimeout(resolve,100));if(path==='raid/core/feature')return {ok:true,visible:true,accessible:true,tester:true,mode:'TEST',rewardLocked:true,title:settings.title,subtitle:settings.subtitle};if(path==='raid/core/status')return clone(state);if(path==='raid/core/join'){const body=JSON.parse(options.body||'{}');state.me={userId:1,nickname:'프리뷰 지휘관',operation:body.operation||'BREAK',status:'JOINED',totalPower:290000,analysisScore:0,coreScore:0,suppressionScore:0,mechanicScore:0,totalDamage:0,isMe:true};state.participants.unshift(state.me);state.entry.used=1;state.entry.remaining=2;state.current.participantCount=state.participants.length;return clone(state)}if(path.startsWith('raid/core/battle'))return battlePayload();if(path==='raid/core/resolve'){const body=JSON.parse(options.body||'{}'),sequenceOk=(body.results?.sequence?.inputs||[]).length>=challenge.sequence.length,mashOk=(body.results?.mash?.presses||[]).length>=challenge.mashTarget,success=sequenceOk&&mashOk,suppression=(sequenceOk?50:0)+(mashOk?50:0);Object.assign(state.me,{status:'RESOLVED',analysisScore:100,coreScore:70,suppressionScore:suppression,mechanicScore:170+suppression,totalDamage:47600000});state.current.analysisScore+=100;state.current.coreScores[state.me.operation]+=70;state.current.suppressionScore+=suppression;state.current.analysisReady=state.current.analysisScore>=state.current.analysisRequired;state.current.phase=state.current.analysisReady?2:1;state.current.phaseLabel=state.current.phase===2?'삼중 코어 분리':'코어 탐색';state.current.bossBuffs=state.current.analysisReady?coreBuffs.filter(buff=>state.current.coreScores[buff.core]<state.current.coreRequired):[];state.current.bossDamageReductionPct=state.current.bossBuffs.reduce((sum,buff)=>sum+buff.damageReductionPct,0);return {ok:true,personalResult:success?'SUCCESS':'FAILED',verified:{sequence:{success:sequenceOk},mash:{success:mashOk},suppressionScore:suppression},contribution:clone(state.me),current:clone(state.current)}}throw new Error(`지원하지 않는 프리뷰 경로: ${path}`)}
  // The live V3 roster resolves artwork from the card catalog before any
  // battleSprite-mutated payload. Mirror that contract in the standalone preview.
  globalThis.cnineCardCatalog=()=>deck.map(card=>({...card}));
  globalThis.CNineCoreRaidBridge={apiRequest,loadUser:()=>({id:1,nickname:'프리뷰 지휘관'}),saveUser:()=>{},ensureFeatureResources:async()=>true,escapeHtml:value=>String(value),activateLegacyRaid(){document.getElementById('pveRaidView').hidden=false;document.getElementById('pveCoreRaidView').hidden=true},stopLegacyRaid(){}};
  addEventListener('DOMContentLoaded',()=>{globalThis.CoreProtocolRaidV1924?.openActive?.();document.getElementById('resetPreview')?.addEventListener('click',()=>{try{document.getElementById('modal').__battleV2Renderer?.destroy?.()}catch(_){}document.getElementById('modal').className='modal';document.getElementById('modal').innerHTML='';reset();globalThis.CoreProtocolRaidV1924?.activate?.('core')})});
})();
