#!/usr/bin/env python3
# -*- coding: utf-8 -*-
r"""
D1(SQLite) 덤프 → PostgreSQL 스키마 변환기
==========================================

사용법
------
  # 스키마만
  python3 d1-to-postgres.py d1-export.sql -o pg-schema.sql

  # 운영 덤프: 스키마와 데이터는 분리 처리한다
  python3 d1-to-postgres.py d1-export.sql -o pg-schema.sql \
    --post-data pg-post-data.sql --fk-validate pg-fk-validate.sql \
    --defer-foreign-keys-post-data
  python3 d1-copy-export.py d1-export.sql \
    --copy-dir pg-copy --manifest pg-copy-manifest.json

  # 타임스탬프를 진짜 timestamptz 로 바꾸고 싶을 때 (아래 주의 참고)
  python3 d1-to-postgres.py d1-export.sql -o pg-schema.sql --timestamps timestamptz

입력은 `npx wrangler d1 export cnine-card-db --remote --output d1-export.sql` 결과물이다.


⚠ 가장 중요한 결정: 타임스탬프는 TEXT 로 둔다 (기본값)
------------------------------------------------------
숲켓몬의 시각 컬럼은 전부 이렇게 생겼다.

    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP     -- '2026-08-22 13:05:00'

코드도 그 전제로 짜여 있다.

    WHERE created_at < datetime('now','-30 days')
    WHERE expires_at > datetime('now')
    ORDER BY created_at DESC

이걸 timestamptz 로 바꾸면 위 비교가 전부 깨지고, 90만 줄을 동시에 고쳐야 한다.
그래서 기본값은 **TEXT 유지**다. Postgres 에서도 'YYYY-MM-DD HH:MM:SS' 문자열은
사전순 = 시간순이라 부등호 비교가 그대로 맞는다. datetime() 만 아래처럼 바꾸면 된다.

    datetime('now')               → to_char(now() AT TIME ZONE 'UTC','YYYY-MM-DD HH24:MI:SS')
    datetime('now','-30 days')    → to_char(now() AT TIME ZONE 'UTC' - interval '30 days', ...)

타입 정리는 이관이 안정된 뒤에 따로 해도 늦지 않다.


변환 규칙
---------
  INTEGER PRIMARY KEY [AUTOINCREMENT]  →  BIGINT GENERATED BY DEFAULT AS IDENTITY
  INTEGER                              →  BIGINT          (SQLite INTEGER 는 64비트)
  REAL / FLOAT / DOUBLE                →  DOUBLE PRECISION
  BLOB                                 →  BYTEA
  타입 없음                            →  TEXT
  DEFAULT CURRENT_TIMESTAMP (TEXT 컬럼) →  DEFAULT to_char(now() AT TIME ZONE 'UTC', …)
  WITHOUT ROWID                        →  삭제
  `백틱` / [대괄호] 따옴표             →  "쌍따옴표"
  Postgres 예약어 컬럼/테이블명        →  "쌍따옴표" 로 감쌈
  sqlite_* / _cf_* 내부 테이블         →  건너뜀
  X'..' BLOB 리터럴 (데이터)           →  '\x..'::bytea

손 못 대는 건 조용히 넘기지 않고 전부 리포트에 남긴다.
"""

import argparse
import hashlib
import os
import re
import sys

# Postgres 예약어 (컬럼/테이블명으로 쓰이면 따옴표 필요)
RESERVED = {
    'all','analyse','analyze','and','any','array','as','asc','asymmetric','authorization',
    'binary','both','case','cast','check','collate','collation','column','concurrently',
    'constraint','create','cross','current_catalog','current_date','current_role',
    'current_schema','current_time','current_timestamp','current_user','default',
    'deferrable','desc','distinct','do','else','end','except','false','fetch','for',
    'foreign','freeze','from','full','grant','group','having','ilike','in','initially',
    'inner','intersect','into','is','isnull','join','lateral','leading','left','like',
    'limit','localtime','localtimestamp','natural','not','notnull','null','offset','on',
    'only','or','order','outer','overlaps','placing','primary','references','returning',
    'right','select','session_user','similar','some','symmetric','table','tablesample',
    'then','to','trailing','true','union','unique','user','using','variadic','verbose',
    'when','where','window','with',
}

PG_NOW_TEXT = "to_char(now() AT TIME ZONE 'UTC','YYYY-MM-DD HH24:MI:SS')"

SKIP_TABLE = re.compile(r'^(sqlite_|_cf_|d1_)', re.I)

warnings = []
deferred_foreign_keys = []


def warn(msg):
    warnings.append(msg)


def unquote_ident(name):
    name = name.strip()
    for a, b in (('"', '"'), ('`', '`'), ('[', ']')):
        if name.startswith(a) and name.endswith(b):
            return name[1:-1]
    return name


def quote_ident(name):
    """예약어이거나 소문자+숫자+_ 가 아니면 쌍따옴표로 감싼다."""
    bare = unquote_ident(name)
    if bare.lower() in RESERVED or not re.fullmatch(r'[a-z_][a-z0-9_]*', bare):
        return '"' + bare.replace('"', '""') + '"'
    return bare


def split_top_level(body):
    """괄호 깊이를 세면서 최상위 쉼표로만 자른다 (CHECK(...) 안의 쉼표 보호)."""
    parts, depth, buf, quote = [], 0, [], None
    for ch in body:
        if quote:
            buf.append(ch)
            if ch == quote:
                quote = None
            continue
        if ch in "'\"`":
            quote = ch
            buf.append(ch)
            continue
        if ch == '(':
            depth += 1
        elif ch == ')':
            depth -= 1
        if ch == ',' and depth == 0:
            parts.append(''.join(buf))
            buf = []
            continue
        buf.append(ch)
    if ''.join(buf).strip():
        parts.append(''.join(buf))
    return [p.strip() for p in parts if p.strip()]


# SQLite 타입을 이루는 단어들 (여러 단어짜리 타입이 있어서 집합으로 판별한다)
TYPE_WORDS = {
    'int','integer','tinyint','smallint','mediumint','bigint','unsigned','big','int2','int8',
    'character','varchar','varying','nchar','native','nvarchar','text','clob','blob',
    'real','double','precision','float','numeric','decimal','boolean','date','datetime','timestamp',
}
# 타입이 끝났음을 알리는 단어들
STOP_WORDS = {
    'primary','not','null','default','unique','check','references','collate',
    'generated','constraint','autoincrement','as','on','conflict',
}


def split_type_and_tail(rest):
    """컬럼 정의에서 '타입'과 '나머지 제약조건'을 정확히 갈라낸다.

    예전 버전은 정규식이 공백까지 먹어서 'INTEGER PRIMARY KEY AUTOINCREMENT' 를
    통째로 타입으로 잡았다. 그 결과 NOT NULL / DEFAULT / UNIQUE 가 전부 사라졌다.
    이제 타입 단어인 동안만 소비하고, STOP_WORDS 를 만나면 즉시 멈춘다.
    """
    i, n = 0, len(rest)
    type_tokens = []
    while i < n:
        while i < n and rest[i].isspace():
            i += 1
        m = re.match(r'[A-Za-z_][A-Za-z0-9_]*', rest[i:])
        if not m:
            break
        word = m.group(0)
        low = word.lower()
        if low in STOP_WORDS or low not in TYPE_WORDS:
            break
        type_tokens.append(word)
        i += len(word)
        # VARCHAR(255) 같은 괄호 인자
        j = i
        while j < n and rest[j].isspace():
            j += 1
        if j < n and rest[j] == '(':
            depth = 0
            k = j
            while k < n:
                if rest[k] == '(':
                    depth += 1
                elif rest[k] == ')':
                    depth -= 1
                    if depth == 0:
                        k += 1
                        break
                k += 1
            type_tokens.append(rest[j:k])
            i = k
    return ' '.join(type_tokens), rest[i:]


def convert_type(sqltype, ts_mode, is_pk_autoinc):
    t = sqltype.strip().upper()
    if is_pk_autoinc:
        return 'BIGINT GENERATED BY DEFAULT AS IDENTITY'
    if not t:
        return 'TEXT'
    if 'INT' in t:
        return 'BIGINT'
    if any(k in t for k in ('CHAR', 'CLOB', 'TEXT')):
        return 'TEXT'
    if 'BLOB' in t:
        return 'BYTEA'
    if any(k in t for k in ('REAL', 'FLOA', 'DOUB')):
        return 'DOUBLE PRECISION'
    if 'BOOL' in t:
        return 'BOOLEAN'
    if 'NUMERIC' in t or 'DECIMAL' in t:
        return 'NUMERIC'
    warn(f'알 수 없는 타입 "{sqltype}" → TEXT 로 둠')
    return 'TEXT'


COLUMN_RE = re.compile(
    r'^(?P<name>"[^"]+"|`[^`]+`|\[[^\]]+\]|[A-Za-z_][A-Za-z0-9_]*)(?P<rest>.*)$',
    re.S)

TABLE_CONSTRAINT = re.compile(
    r'^\s*(PRIMARY\s+KEY|UNIQUE|CHECK|FOREIGN\s+KEY|CONSTRAINT)\b', re.I)


def convert_column(defn, ts_mode, table):
    m = COLUMN_RE.match(defn.strip())
    if not m:
        warn(f'[{table}] 컬럼 해석 실패, 원문 유지: {defn[:80]}')
        return defn
    raw_name = m.group('name')
    sqltype, tail = split_type_and_tail(m.group('rest'))

    is_pk = bool(re.search(r'\bPRIMARY\s+KEY\b', tail, re.I))
    is_int = 'INT' in sqltype.upper()
    # SQLite 에서 INTEGER PRIMARY KEY 는 AUTOINCREMENT 유무와 무관하게 자동 증가한다
    is_pk_autoinc = is_pk and is_int

    pgtype = convert_type(sqltype, ts_mode, is_pk_autoinc)
    tail = re.sub(r'\bAUTOINCREMENT\b', '', tail, flags=re.I)
    if is_pk_autoinc:
        # identity 뒤에 PRIMARY KEY 를 한 번만 붙인다
        tail = re.sub(r'\bPRIMARY\s+KEY\b', '', tail, flags=re.I)

    if re.search(r'DEFAULT\s+CURRENT_TIMESTAMP', tail, re.I):
        repl = ('DEFAULT ' + PG_NOW_TEXT) if (pgtype == 'TEXT' and ts_mode == 'text') else 'DEFAULT now()'
        tail = re.sub(r'DEFAULT\s+CURRENT_TIMESTAMP', repl, tail, flags=re.I)

    if ts_mode == 'timestamptz' and pgtype == 'TEXT' \
            and re.search(r'(_at|_date|_time)$', unquote_ident(raw_name), re.I):
        pgtype = 'TIMESTAMPTZ'
        warn(f'[{table}] {unquote_ident(raw_name)} → TIMESTAMPTZ '
             f'(코드의 datetime()/문자열 비교를 반드시 같이 고쳐야 함)')

    if re.search(r'COLLATE\s+NOCASE', tail, re.I):
        warn(f'[{table}] {unquote_ident(raw_name)} 에 COLLATE NOCASE 가 있다. '
             f'Postgres 엔 없다 → citext 확장이나 lower() 인덱스로 따로 처리 필요')
        tail = re.sub(r'COLLATE\s+NOCASE', '', tail, flags=re.I)

    tail = re.sub(r'\s+', ' ', tail).strip()
    out = f'{quote_ident(raw_name)} {pgtype}'
    if is_pk_autoinc:
        out += ' PRIMARY KEY'
    if tail:
        out += ' ' + tail
    return out


def convert_constraint(defn, table):
    """테이블 레벨 제약조건. 외래키는 반드시 DEFERRABLE 로 만든다.

    D1(SQLite)은 기본적으로 외래키를 강제하지 않고, export 결과도 의존 순서대로
    나오지 않는다. Postgres 는 즉시 강제하므로 그냥 넣으면 적재가 통째로 실패한다.
    (실측: tricky.id → users.id 참조가 users 적재 전에 걸려서 전량 실패)
    DEFERRABLE INITIALLY DEFERRED 로 만들면 트랜잭션 끝에서 한 번만 검사한다.
    슈퍼유저 권한(session_replication_role)이 없어도 되는 방식이다."""
    # 식별자 따옴표만 정리
    def q(m):
        return quote_ident(m.group(0))
    defn = re.sub(r'`([^`]+)`', lambda m: quote_ident(m.group(1)), defn)
    defn = re.sub(r'\[([^\]]+)\]', lambda m: quote_ident(m.group(1)), defn)
    defn = re.sub(r'\s+', ' ', defn).strip()
    if re.match(r'^(CONSTRAINT\s+\S+\s+)?FOREIGN\s+KEY\b', defn, re.I) \
            and not re.search(r'DEFERRABLE', defn, re.I):
        defn += ' DEFERRABLE INITIALLY DEFERRED'
    return defn


CREATE_TABLE_RE = re.compile(
    r'CREATE\s+TABLE\s+(IF\s+NOT\s+EXISTS\s+)?'
    r'(?P<name>"[^"]+"|`[^`]+`|\[[^\]]+\]|[A-Za-z_][A-Za-z0-9_]*)\s*\((?P<body>.*)\)'
    r'(?P<opts>[^)]*)$',
    re.S | re.I)


def convert_fk_post_data(defn, table, ordinal):
    """테이블 FK를 적재 후 추가할 ALTER/VALIDATE SQL로 분리한다."""
    cleaned = re.sub(r'`([^`]+)`', lambda m: quote_ident(m.group(1)), defn)
    cleaned = re.sub(r'\[([^\]]+)\]', lambda m: quote_ident(m.group(1)), cleaned)
    cleaned = re.sub(r'\s+', ' ', cleaned).strip()
    m = re.match(
        r'FOREIGN\s+KEY\s*\((?P<cols>.*?)\)\s+REFERENCES\s+'
        r'(?P<ref>"[^"]+"|[A-Za-z_][A-Za-z0-9_]*)\s*'
        r'\((?P<refcols>.*?)\)(?P<tail>.*)$',
        cleaned, re.I | re.S)
    if not m:
        warn(f'[{table}] FK 분리 실패: {defn[:100]}')
        return None
    cols = ', '.join(quote_ident(c.strip()) for c in split_top_level(m.group('cols')))
    refcols = ', '.join(quote_ident(c.strip()) for c in split_top_level(m.group('refcols')))
    tail = re.sub(r'\bDEFERRABLE\b(?:\s+INITIALLY\s+DEFERRED)?', '', m.group('tail'), flags=re.I)
    tail = re.sub(r'\s+', ' ', tail).strip()
    raw_name = f'fk_{table}_{ordinal}'
    if len(raw_name) > 63:
        digest = hashlib.sha1(raw_name.encode('utf-8')).hexdigest()[:10]
        raw_name = raw_name[:52] + '_' + digest
    name = quote_ident(raw_name)
    base = (f'ALTER TABLE {quote_ident(table)} ADD CONSTRAINT {name} '
            f'FOREIGN KEY ({cols}) REFERENCES {quote_ident(m.group("ref"))} ({refcols})')
    if tail:
        base += ' ' + tail
    return base + ' NOT VALID;', f'ALTER TABLE {quote_ident(table)} VALIDATE CONSTRAINT {name};'


def convert_create_table(stmt, ts_mode, defer_fks=False):
    m = CREATE_TABLE_RE.match(stmt.strip())
    if not m:
        warn(f'CREATE TABLE 해석 실패, 건너뜀: {stmt[:90]}')
        return None
    table = unquote_ident(m.group('name'))
    if SKIP_TABLE.match(table):
        return None
    body = m.group('body')
    opts = (m.group('opts') or '')
    if re.search(r'WITHOUT\s+ROWID', opts + body, re.I):
        warn(f'[{table}] WITHOUT ROWID 는 Postgres 에 없다 → 제거함(동작 영향 없음)')
        body = re.sub(r'WITHOUT\s+ROWID', '', body, flags=re.I)

    parts = split_top_level(body)
    out = []
    fk_ordinal = 0
    for p in parts:
        if TABLE_CONSTRAINT.match(p):
            if defer_fks and re.match(r'^\s*FOREIGN\s+KEY\b', p, re.I):
                fk_ordinal += 1
                converted = convert_fk_post_data(p, table, fk_ordinal)
                if converted:
                    deferred_foreign_keys.append(converted)
                continue
            out.append('  ' + convert_constraint(p, table))
        else:
            out.append('  ' + convert_column(p, ts_mode, table))
    return (f'CREATE TABLE IF NOT EXISTS {quote_ident(table)} (\n'
            + ',\n'.join(out) + '\n);')


CREATE_INDEX_RE = re.compile(
    r'CREATE\s+(?P<uniq>UNIQUE\s+)?INDEX\s+(IF\s+NOT\s+EXISTS\s+)?'
    r'(?P<name>"[^"]+"|`[^`]+`|\[[^\]]+\]|[A-Za-z_][A-Za-z0-9_]*)\s+'
    r'ON\s+(?P<table>"[^"]+"|`[^`]+`|\[[^\]]+\]|[A-Za-z_][A-Za-z0-9_]*)\s*'
    r'\((?P<cols>.*?)\)\s*(?P<where>WHERE\s+.*)?$',
    re.S | re.I)


def convert_create_index(stmt):
    m = CREATE_INDEX_RE.match(stmt.strip())
    if not m:
        warn(f'CREATE INDEX 해석 실패, 건너뜀: {stmt[:90]}')
        return None
    table = unquote_ident(m.group('table'))
    if SKIP_TABLE.match(table):
        return None
    cols = ', '.join(convert_index_term(c, table) for c in split_top_level(m.group('cols')))
    uniq = 'UNIQUE ' if m.group('uniq') else ''
    where = (' ' + re.sub(r'\s+', ' ', m.group('where')).strip()) if m.group('where') else ''
    return (f'CREATE {uniq}INDEX IF NOT EXISTS {quote_ident(m.group("name"))} '
            f'ON {quote_ident(table)} ({cols}){where};')


INDEX_IDENT_RE = r'(?P<ident>"[^"]+"|`[^`]+`|\[[^\]]+\]|[A-Za-z_][A-Za-z0-9_]*)'


def convert_index_term(term, table):
    """인덱스 컬럼/표현식을 PostgreSQL 문법으로 변환한다.

    운영 스키마에는 `datetime(expires_at)` 표현식 인덱스가 하나 있다. 시각을
    SQLite 형식의 TEXT로 유지하므로 PostgreSQL에서는 원본 컬럼 인덱스가 같은
    정렬/범위 검색 목적을 충족한다. 표현식 전체를 식별자로 따옴표 처리하면
    존재하지 않는 `"datetime(expires_at)"` 컬럼이 되어 스키마 적용이 실패한다.
    """
    value = term.strip()
    simple = re.fullmatch(INDEX_IDENT_RE + r'(?P<order>\s+(?:ASC|DESC))?', value, re.I)
    if simple:
        return quote_ident(simple.group('ident')) + (simple.group('order') or '')

    sqlite_datetime = re.fullmatch(
        r'datetime\s*\(\s*' + INDEX_IDENT_RE + r'\s*\)(?P<order>\s+(?:ASC|DESC))?',
        value, re.I)
    if sqlite_datetime:
        column = quote_ident(sqlite_datetime.group('ident'))
        warn(f'[{table}] 인덱스 datetime({unquote_ident(sqlite_datetime.group("ident"))}) '
             f'→ {column} (TEXT 시각 형식 유지)')
        return column + (sqlite_datetime.group('order') or '')

    warn(f'[{table}] 인덱스 표현식은 PostgreSQL 호환 여부를 확인할 것: {value}')
    return value


def convert_data_line(stmt):
    """INSERT 문의 SQLite 전용 리터럴만 손본다."""
    # X'deadbeef' → '\xdeadbeef'::bytea
    stmt = re.sub(r"\bX'([0-9a-fA-F]*)'", lambda m: r"'\x" + m.group(1) + "'::bytea", stmt)
    stmt = re.sub(r'\bINSERT\s+OR\s+(IGNORE|REPLACE|ABORT|FAIL|ROLLBACK)\s+INTO\b',
                  'INSERT INTO', stmt, flags=re.I)
    stmt = re.sub(r'`([^`]+)`', lambda m: quote_ident(m.group(1)), stmt)
    return stmt


def split_statements(text):
    """따옴표를 존중하며 세미콜론으로 자른다."""
    out, buf, quote = [], [], None
    i = 0
    while i < len(text):
        ch = text[i]
        if quote:
            buf.append(ch)
            if ch == quote:
                # '' 이스케이프
                if i + 1 < len(text) and text[i + 1] == quote:
                    buf.append(text[i + 1]); i += 2; continue
                quote = None
            i += 1
            continue
        if ch in "'\"`":
            quote = ch; buf.append(ch); i += 1; continue
        if ch == ';':
            s = ''.join(buf).strip()
            if s:
                out.append(s)
            buf = []; i += 1; continue
        buf.append(ch); i += 1
    s = ''.join(buf).strip()
    if s:
        out.append(s)
    return out


def read_source(path, include_data):
    """운영 덤프를 스키마 변환할 때 4GB INSERT를 메모리에 올리지 않는다.

    Wrangler D1 export의 데이터 INSERT는 최상위(들여쓰기 없음) 단일 행이다.
    트리거 본문 안의 들여쓴 INSERT는 보존한다. `--data`는 작은 검증 fixture를
    위한 레거시 경로이며 운영 데이터는 d1-copy-export.py를 사용한다.
    """
    if include_data:
        size = os.path.getsize(path)
        if size > 256 * 1024 * 1024:
            raise SystemExit(
                '--data는 256MB 초과 덤프에서 금지됩니다. '
                '운영 데이터는 d1-copy-export.py로 COPY 파일을 생성하세요.')
        with open(path, encoding='utf-8', errors='strict') as source:
            return source.read(), 0

    chunks = []
    skipped_inserts = 0
    with open(path, encoding='utf-8', errors='strict', newline='') as source:
        for line_no, line in enumerate(source, 1):
            if line.startswith('INSERT INTO '):
                if not line.rstrip('\r\n').endswith(');'):
                    raise SystemExit(
                        f'{line_no}행: 단일 행이 아닌 데이터 INSERT입니다. '
                        '스키마 추출을 안전하게 중단합니다.')
                skipped_inserts += 1
                continue
            chunks.append(line)
    return ''.join(chunks), skipped_inserts


def extract_sqlite_schema_objects(text):
    """세미콜론을 포함하는 SQLite 트리거와 여러 줄 뷰를 통째로 분리한다."""
    clean_lines = []
    objects = []
    lines = text.splitlines(keepends=True)
    index = 0
    while index < len(lines):
        stripped = lines[index].lstrip().upper()
        is_trigger = stripped.startswith('CREATE TRIGGER')
        is_view = stripped.startswith('CREATE VIEW')
        if not (is_trigger or is_view):
            clean_lines.append(lines[index])
            index += 1
            continue

        block = []
        while index < len(lines):
            line = lines[index]
            block.append(line)
            index += 1
            tail = line.rstrip().upper()
            if is_trigger and tail.endswith('END;'):
                break
            if is_view and tail.endswith(';'):
                break
        else:
            kind = 'TRIGGER' if is_trigger else 'VIEW'
            raise SystemExit(f'닫히지 않은 CREATE {kind} 문장')
        objects.append(''.join(block).strip())
        clean_lines.extend('\n' for _ in block)
    return ''.join(clean_lines), objects


def main():
    # Windows PowerShell may expose legacy CP949 stdout even though both the
    # source and generated SQL are UTF-8. A progress glyph must never abort a
    # completed multi-gigabyte conversion.
    for stream in (sys.stdout, sys.stderr):
        if hasattr(stream, 'reconfigure'):
            stream.reconfigure(encoding='utf-8', errors='replace')
    ap = argparse.ArgumentParser(description='D1(SQLite) 덤프를 PostgreSQL 로 변환')
    ap.add_argument('input', help='wrangler d1 export 결과 .sql')
    ap.add_argument('-o', '--out', required=True, help='변환된 스키마 출력 경로')
    ap.add_argument('--data', help='데이터(INSERT) 출력 경로 (생략하면 스키마만)')
    ap.add_argument('--timestamps', choices=['text', 'timestamptz'], default='text',
                    help='기본 text (권장). timestamptz 는 코드도 같이 고쳐야 함')
    ap.add_argument('--post-data', help='인덱스·identity 시퀀스·FK 추가 SQL 출력 경로')
    ap.add_argument('--fk-validate', help='적재 후 FK 검증 SQL 출력 경로')
    ap.add_argument('--defer-foreign-keys-post-data', action='store_true',
                    help='FK를 CREATE TABLE에서 빼고 데이터 적재 후 NOT VALID로 추가')
    ap.add_argument('--include-unconverted-objects', action='store_true',
                    help='자동 변환하지 않은 SQLite 뷰/트리거를 주 스키마에 포함(비권장)')
    args = ap.parse_args()

    text, skipped_data_inserts = read_source(args.input, include_data=bool(args.data))
    text, sqlite_objects = extract_sqlite_schema_objects(text)
    stmts = split_statements(text)

    tables, indexes, views, data, skipped = [], [], list(sqlite_objects), [], []
    for obj in sqlite_objects:
        warn(f'뷰/트리거는 자동 변환하지 않았다. PostgreSQL 업무 객체 파일 확인: {obj[:70]}…')
    for s in stmts:
        head = s.lstrip()[:24].upper()
        if head.startswith('PRAGMA') or head.startswith('BEGIN') or head.startswith('COMMIT'):
            continue
        if head.startswith('CREATE TABLE'):
            r = convert_create_table(s, args.timestamps, args.defer_foreign_keys_post_data)
            if r: tables.append(r)
        elif head.startswith('CREATE INDEX') or head.startswith('CREATE UNIQUE'):
            r = convert_create_index(s)
            if r: indexes.append(r)
        elif head.startswith('CREATE VIEW') or head.startswith('CREATE TRIGGER'):
            views.append(s + ';')
            warn(f'뷰/트리거는 자동 변환하지 않았다. 손으로 확인할 것: {s[:70]}…')
        elif head.startswith('INSERT'):
            data.append(convert_data_line(s) + ';')
        elif re.match(r'^DELETE\s+FROM\s+sqlite_sequence\b', s, re.I):
            continue
        else:
            skipped.append(s[:90])

    # identity 시퀀스 맞추기 (데이터를 넣은 뒤 실행)
    seq_fix = []
    for t in tables:
        mt = re.match(r'CREATE TABLE IF NOT EXISTS (\S+) \(', t)
        if not mt: continue
        tname = mt.group(1)
        mc = re.search(r'\n  (\S+) BIGINT GENERATED BY DEFAULT AS IDENTITY', t)
        if mc:
            col = mc.group(1)
            seq_fix.append(
                f"SELECT setval(pg_get_serial_sequence('{tname}','{unquote_ident(col)}'), "
                f"COALESCE((SELECT MAX({col}) FROM {tname}),0)+1, false);")

    with open(args.out, 'w', encoding='utf-8') as f:
        f.write('-- D1(SQLite) → PostgreSQL 변환 결과\n')
        f.write(f'-- 원본: {args.input}\n')
        f.write(f'-- 타임스탬프 모드: {args.timestamps}\n')
        f.write(f'-- 테이블 {len(tables)} · 인덱스 {len(indexes)} · 뷰/트리거 {len(views)}\n\n')
        f.write('BEGIN;\n\n')
        if args.timestamps == 'text':
            f.write("CREATE OR REPLACE FUNCTION sqlite_now(shift interval DEFAULT interval '0')\n")
            f.write("RETURNS text LANGUAGE sql STABLE AS $$\n")
            f.write("  SELECT to_char(now() AT TIME ZONE 'UTC' + shift,'YYYY-MM-DD HH24:MI:SS')\n")
            f.write("$$;\n\n")
        f.write('\n\n'.join(tables))
        if not args.post_data:
            f.write('\n\n' + '\n'.join(indexes))
        if views and args.include_unconverted_objects:
            f.write('\n\n-- ⚠ 아래는 원문 그대로다. 반드시 손으로 확인할 것.\n')
            f.write('\n'.join(views))
        elif views:
            f.write(f'\n\n-- SQLite 뷰/트리거 {len(views)}개는 의도적으로 제외함.\n')
            f.write('-- 검증된 PostgreSQL 구현: scripts/postgres-business-objects.sql\n')
        f.write('\n\nCOMMIT;\n')
        if seq_fix and not args.post_data:
            f.write('\n-- 데이터를 다 넣은 뒤에 실행 (자동 증가 번호 맞추기)\n')
            f.write('\n'.join(seq_fix) + '\n')

    if args.post_data:
        with open(args.post_data, 'w', encoding='utf-8') as f:
            f.write('-- 데이터 COPY 적재 후 실행: identity, 보조 인덱스, FK 추가\n')
            f.write('\\set ON_ERROR_STOP on\n')
            if seq_fix:
                f.write('\n-- identity 시퀀스 맞추기\n' + '\n'.join(seq_fix) + '\n')
            if indexes:
                f.write('\n-- 인덱스는 각각 커밋되어 실패 지점부터 안전하게 재실행할 수 있다.\n')
                f.write('\n-- 보조 인덱스 생성\n' + '\n'.join(indexes) + '\n')
            if deferred_foreign_keys:
                f.write('\n-- FK 7개 추가는 하나의 원자적 작업으로 처리\nBEGIN;\n')
                f.write('-- 기존 행을 즉시 검사하지 않고 FK 추가\n')
                f.write('\n'.join(x[0] for x in deferred_foreign_keys) + '\n')
                f.write('COMMIT;\n')

    if args.fk_validate:
        with open(args.fk_validate, 'w', encoding='utf-8') as f:
            f.write('-- 별도 실행: 고아 참조가 있으면 해당 FK에서 명확히 실패한다.\n')
            f.write('\\set ON_ERROR_STOP on\n')
            f.write('\n'.join(x[1] for x in deferred_foreign_keys) + '\n')

    if args.data:
        with open(args.data, 'w', encoding='utf-8') as f:
            f.write('-- 데이터. 스키마를 먼저 넣은 뒤 실행할 것.\n')
            f.write('-- 외래키는 DEFERRABLE INITIALLY DEFERRED 라서, 한 트랜잭션 안에서\n')
            f.write('-- 순서에 상관없이 넣을 수 있다. COMMIT 시점에 한 번만 검사한다.\n')
            f.write('BEGIN;\nSET CONSTRAINTS ALL DEFERRED;\n')
            f.write('\n'.join(data))
            f.write('\nCOMMIT;\n')

    print(f'테이블  {len(tables)}')
    print(f'인덱스  {len(indexes)}')
    print(f'뷰/트리거 {len(views)}   (자동 변환 안 함)')
    print(f'INSERT  {len(data)}')
    if skipped_data_inserts:
        print(f'스키마 처리 중 건너뛴 데이터 INSERT  {skipped_data_inserts:,}')
    print(f'적재 후 FK  {len(deferred_foreign_keys)}')
    if skipped:
        print(f'\n분류 못 한 문장 {len(skipped)}건:')
        for s in skipped[:10]:
            print('  ', s)
    if warnings:
        print(f'\n⚠ 확인 필요 {len(warnings)}건:')
        seen = set()
        for w in warnings:
            if w in seen: continue
            seen.add(w)
            print('  -', w)
    else:
        print('\n확인 필요 항목 없음')


if __name__ == '__main__':
    main()
