-- V1820 clan system foundation for the authoritative Neon PostgreSQL database.
-- Safe to run repeatedly. Public access remains disabled by TEST mode.

BEGIN;

CREATE TABLE IF NOT EXISTS clan_seasons (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_no BIGINT NOT NULL UNIQUE,
  phase TEXT NOT NULL DEFAULT 'REGISTRATION',
  max_members BIGINT NOT NULL DEFAULT 20,
  registration_ends_at TEXT NOT NULL,
  draft_ends_at TEXT NOT NULL,
  starts_at TEXT NOT NULL,
  ends_at TEXT NOT NULL,
  draft_pick_count BIGINT NOT NULL DEFAULT 0,
  next_pick_deadline TEXT,
  created_at TEXT NOT NULL DEFAULT sqlite_now(),
  updated_at TEXT NOT NULL DEFAULT sqlite_now()
);

CREATE TABLE IF NOT EXISTS clan_organizations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  mark_key TEXT NOT NULL DEFAULT 'SHIELD',
  primary_color TEXT NOT NULL DEFAULT '#31d7e8',
  accent_color TEXT NOT NULL DEFAULT '#e4f8ff',
  slogan TEXT NOT NULL DEFAULT '',
  trophies BIGINT NOT NULL DEFAULT 0,
  is_active BIGINT NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT sqlite_now(),
  updated_at TEXT NOT NULL DEFAULT sqlite_now()
);

CREATE TABLE IF NOT EXISTS clan_season_teams (
  season_id BIGINT NOT NULL,
  clan_id BIGINT NOT NULL,
  master_user_id BIGINT NOT NULL,
  draft_position BIGINT NOT NULL,
  score BIGINT NOT NULL DEFAULT 0,
  wins BIGINT NOT NULL DEFAULT 0,
  losses BIGINT NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT sqlite_now(),
  updated_at TEXT NOT NULL DEFAULT sqlite_now(),
  PRIMARY KEY (season_id, clan_id),
  UNIQUE (season_id, master_user_id),
  UNIQUE (season_id, draft_position)
);

CREATE TABLE IF NOT EXISTS clan_draft_pool (
  season_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  candidate_key TEXT NOT NULL,
  preferred_role TEXT NOT NULL DEFAULT 'BALANCED',
  activity_window TEXT NOT NULL DEFAULT 'EVENING',
  activity_score BIGINT NOT NULL DEFAULT 0,
  rank_score BIGINT NOT NULL DEFAULT 0,
  contribution_score BIGINT NOT NULL DEFAULT 0,
  reliability_score BIGINT NOT NULL DEFAULT 0,
  master_score BIGINT NOT NULL DEFAULT 0,
  total_score BIGINT NOT NULL DEFAULT 0,
  rank_band TEXT NOT NULL DEFAULT 'UNRANKED',
  activity_band TEXT NOT NULL DEFAULT 'NEW',
  deck_snapshot TEXT NOT NULL DEFAULT '[]',
  status TEXT NOT NULL DEFAULT 'AVAILABLE',
  drafted_clan_id BIGINT,
  pick_no BIGINT,
  registered_at TEXT NOT NULL DEFAULT sqlite_now(),
  updated_at TEXT NOT NULL DEFAULT sqlite_now(),
  PRIMARY KEY (season_id, user_id),
  UNIQUE (season_id, candidate_key)
);

CREATE TABLE IF NOT EXISTS clan_members (
  season_id BIGINT NOT NULL,
  clan_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  member_role TEXT NOT NULL DEFAULT 'MEMBER',
  preferred_role TEXT NOT NULL DEFAULT 'BALANCED',
  draft_pick_no BIGINT NOT NULL DEFAULT 0,
  contribution_score BIGINT NOT NULL DEFAULT 0,
  battle_wins BIGINT NOT NULL DEFAULT 0,
  battle_losses BIGINT NOT NULL DEFAULT 0,
  joined_at TEXT NOT NULL DEFAULT sqlite_now(),
  updated_at TEXT NOT NULL DEFAULT sqlite_now(),
  PRIMARY KEY (season_id, user_id),
  UNIQUE (season_id, clan_id, user_id)
);

CREATE TABLE IF NOT EXISTS clan_wars (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_id BIGINT NOT NULL,
  round_no BIGINT NOT NULL DEFAULT 1,
  clan_a_id BIGINT NOT NULL,
  clan_b_id BIGINT NOT NULL,
  status TEXT NOT NULL DEFAULT 'ACTIVE',
  score_a BIGINT NOT NULL DEFAULT 0,
  score_b BIGINT NOT NULL DEFAULT 0,
  battle_count BIGINT NOT NULL DEFAULT 0,
  starts_at TEXT NOT NULL,
  ends_at TEXT NOT NULL,
  winner_clan_id BIGINT,
  created_at TEXT NOT NULL DEFAULT sqlite_now(),
  updated_at TEXT NOT NULL DEFAULT sqlite_now(),
  UNIQUE (season_id, round_no, clan_a_id, clan_b_id)
);

CREATE TABLE IF NOT EXISTS clan_war_battles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id TEXT NOT NULL UNIQUE,
  season_id BIGINT NOT NULL,
  war_id BIGINT NOT NULL,
  attacker_clan_id BIGINT NOT NULL,
  defender_clan_id BIGINT NOT NULL,
  attacker_user_id BIGINT NOT NULL,
  defender_user_id BIGINT NOT NULL,
  battle_seed BIGINT NOT NULL,
  status TEXT NOT NULL DEFAULT 'PENDING',
  winner_clan_id BIGINT,
  result_json TEXT,
  error_message TEXT,
  created_at TEXT NOT NULL DEFAULT sqlite_now(),
  updated_at TEXT NOT NULL DEFAULT sqlite_now()
);

CREATE TABLE IF NOT EXISTS clan_draft_locks (
  season_id BIGINT PRIMARY KEY,
  token TEXT NOT NULL,
  expires_at TEXT NOT NULL,
  updated_at TEXT NOT NULL DEFAULT sqlite_now()
);

CREATE INDEX IF NOT EXISTS idx_clan_pool_status ON clan_draft_pool(season_id, status, total_score DESC, user_id);
CREATE INDEX IF NOT EXISTS idx_clan_members_team ON clan_members(season_id, clan_id, draft_pick_no, user_id);
CREATE INDEX IF NOT EXISTS idx_clan_teams_rank ON clan_season_teams(season_id, score DESC, wins DESC, clan_id);
CREATE INDEX IF NOT EXISTS idx_clan_wars_team_a ON clan_wars(season_id, clan_a_id, status);
CREATE INDEX IF NOT EXISTS idx_clan_wars_team_b ON clan_wars(season_id, clan_b_id, status);
CREATE INDEX IF NOT EXISTS idx_clan_battles_cleanup ON clan_war_battles(status, updated_at, id);

INSERT INTO app_meta(key, value, updated_at)
VALUES ('clan_settings_v1', '{"mode":"TEST"}', sqlite_now())
ON CONFLICT(key) DO NOTHING;

COMMIT;
