import {MECHANICS,cursorPosition,gradeTiming,circuitOrder,circuitTarget,safeCells,insidePort,summarize} from './model.mjs';
const symbols=['Ⅰ','Ⅱ','Ⅲ'],clamp=(v,min,max)=>Math.max(min,Math.min(max,v));
let active=null;
const rings=`<svg class="cqm-orbit" viewBox="0 0 300 300" aria-hidden="true"><circle cx="150" cy="150" r="136"/><circle cx="150" cy="150" r="122" stroke-dasharray="2 10"/><circle class="cqm-orbit-spin" cx="150" cy="150" r="103" stroke-dasharray="115 47"/><path d="M150 7v26M150 267v26M7 150h26M267 150h26"/><circle cx="150" cy="150" r="77"/></svg>`;
const shield='<svg viewBox="0 0 32 32" aria-hidden="true"><path d="M16 3 27 7v9c0 7-11 13-11 13S5 23 5 16V7Z"/><path d="m11 16 4 4 7-8"/></svg>';
function instrument(kind,seed){
 if(kind==='CENTER')return `<div class="cqm-sync-core">${rings}<div><small>CORE FREQUENCY</small><b data-core-value>00</b><span data-core-label>동조 대기</span></div></div><div class="cqm-meter-label"><span>− DESYNC</span><b>중앙 동조 영역</b><span>DESYNC +</span></div><div class="cqm-meter" data-meter><div class="cqm-meter-grid"></div><div class="cqm-hit-zone"><i></i></div><div class="cqm-cursor" data-cursor><i></i></div></div><div class="cqm-rounds">${[0,1,2].map(i=>`<span data-round="${i}"><small>0${i+1}</small><b>대기</b></span>`).join('')}</div>`;
 if(kind==='CIRCUIT'){const order=circuitOrder(seed);return `<div class="cqm-wiring-label"><span>CORE OUTPUT</span><b>단자를 같은 기호끼리 연결</b><span>SHIELD INPUT</span></div><div class="cqm-wiring" data-wiring><div class="cqm-wire-grid"></div><svg viewBox="0 0 1000 1000" preserveAspectRatio="none" aria-hidden="true"><g data-wires></g><path data-drag-wire class="cqm-drag-wire"/></svg><div class="cqm-wire-reactor">${rings}<b data-connections>0<span>/3</span></b></div>${symbols.map((symbol,i)=>`<button class="cqm-port cqm-source" data-source="${i}" style="--y:${22+i*28}%" aria-label="${symbol} 출력 단자">${symbol}<small>OUTPUT</small></button>`).join('')}${order.map((source,i)=>`<button class="cqm-port cqm-target" data-target="${i}" style="--y:${22+i*28}%" aria-label="${symbols[source]} 입력 단자">${symbols[source]}<small>INPUT</small></button>`).join('')}</div><p class="cqm-inline-hint" data-wire-hint>출력 단자를 잡고 같은 기호까지 끌어주세요.</p>`;}
 return `<div class="cqm-shelter-head"><span>폭발 예고</span><b data-wave-label>WAVE 01 / 03</b><span data-wave-time>3.0s</span></div><div class="cqm-shelter-grid" data-shelter>${Array.from({length:9},(_,i)=>`<button class="cqm-cell" data-cell="${i}" aria-label="${i+1}번 구역"><small>0${i+1}</small><span class="cqm-cell-sign">${shield}</span><i>차폐</i><b class="cqm-player">${shield}<em>내 위치</em></b></button>`).join('')}</div><div class="cqm-wave-bar"><i data-wave-bar></i></div><div class="cqm-rounds">${[0,1,2].map(i=>`<span data-round="${i}"><small>0${i+1}</small><b>대기</b></span>`).join('')}</div>`;
}
export function cancel(){active?.();}
export function run(kind,{stage,seed=0}={}){
 cancel();const spec=MECHANICS[kind];if(!stage||!spec)return Promise.resolve({kind,success:false,cancelled:true});
 return new Promise(resolve=>{
  const overlay=document.createElement('section');overlay.className='cqm-overlay cqm-'+kind.toLowerCase();overlay.dataset.state='ready';overlay.dataset.mechanic=kind;overlay.setAttribute('role','dialog');overlay.setAttribute('aria-modal','true');overlay.setAttribute('aria-label',spec.name);
  overlay.innerHTML=`<div class="cqm-noise"></div><header class="cqm-hud"><div><small>CORE PROTOCOL / ${spec.english}</small><b>${spec.name}</b></div><div class="cqm-clock"><small>TIME REMAINING</small><b data-time>—</b></div></header><main><div class="cqm-instruction"><small>MANUAL OVERRIDE · 0${Object.keys(MECHANICS).indexOf(kind)+1}</small><h2>${spec.instruction}</h2><p>${spec.detail}</p></div><div class="cqm-instrument">${instrument(kind,seed)}</div></main><footer><div class="cqm-feedback" data-feedback role="status">준비되면 시작하세요.</div><button type="button" class="cqm-action" data-action><span>시작하기</span><i>↗</i></button><small>기믹 검수용 · 계정 재화와 전투 결과에 영향 없음</small></footer><div class="cqm-verdict" hidden><small data-verdict-en></small><strong data-verdict-ko></strong><span data-verdict-score></span></div>`;
  stage.append(overlay);const $=s=>overlay.querySelector(s),listeners=[];const on=(node,type,fn,options)=>{node.addEventListener(type,fn,options);listeners.push(()=>node.removeEventListener(type,fn,options));};
  const previousFocus=document.activeElement;let started=0,raf=0,finishTimer=0,settled=false,resolved=false,round=0,roundStarted=0,nextRoundAt=0,selectedCell=4,selectedSource=null,drag=null;
  const rounds=[],trace=[],connected=new Set(),order=circuitOrder(seed);let waveResolved=-1;
  const time=()=>started?performance.now()-started:0;
  const feedback=(text,tone='')=>{$('[data-feedback]').textContent=text;$('[data-feedback]').dataset.tone=tone;};
  const inputAllowed=()=>started&&!settled&&time()<spec.windowMs;
  const dropCapture=()=>{const held=drag;drag=null;if(held)try{overlay.releasePointerCapture(held.id);}catch{}};
  const dispose=()=>{cancelAnimationFrame(raf);clearTimeout(finishTimer);listeners.forEach(fn=>fn());dropCapture();overlay.remove();if(previousFocus?.isConnected)previousFocus.focus({preventScroll:true});if(active===abort)active=null;};
  const complete=value=>{if(resolved)return;resolved=true;dispose();resolve(value);};
  const abort=()=>{settled=true;complete({kind,success:false,cancelled:true,rounds:rounds.slice(),trace:trace.slice(),durationMs:Math.round(time())});};active=abort;
  const finish=()=>{if(settled)return;settled=true;cancelAnimationFrame(raf);dropCapture();const result={kind,...summarize(kind,rounds),rounds:rounds.slice(),trace:trace.slice(),durationMs:Math.round(time()),authority:'PREVIEW_ONLY'};overlay.dataset.state=result.success?'success':'failure';$('[data-action]').disabled=true;$('[data-verdict-en]').textContent=result.success?'PROTOCOL RESTORED':'OVERRIDE FAILED';$('[data-verdict-ko]').textContent=result.success?'코어 제어 성공':'다시 도전하세요';$('[data-verdict-score]').textContent=`${result.score} / ${result.total} · ${result.perfect?'PERFECT':result.success?'SUCCESS':'FAILED'}`;$('.cqm-verdict').hidden=false;finishTimer=setTimeout(()=>complete(result),1100);};
  const paintRound=(i,label,good)=>{const node=$(`[data-round="${i}"]`);if(node){node.classList.add(good?'is-good':'is-miss');node.querySelector('b').textContent=label;}};
  function paintWave(){const safe=safeCells(round,seed);overlay.querySelectorAll('[data-cell]').forEach(cell=>{const id=Number(cell.dataset.cell),allowed=safe.includes(id);cell.classList.toggle('is-safe',allowed);cell.classList.toggle('is-danger',!allowed);cell.classList.toggle('is-selected',id===selectedCell);cell.querySelector('.cqm-cell-sign').innerHTML=allowed?shield:'!';cell.querySelector('i').textContent=allowed?'차폐':'위험';cell.setAttribute('aria-label',`${id+1}번 ${allowed?'차폐':'위험'} 구역`);});$('[data-wave-label]').textContent=`WAVE 0${round+1} / 03`;}
  function begin(){if(started||settled)return;started=performance.now();roundStarted=0;overlay.dataset.state='running';$('[data-action] span').textContent=kind==='CENTER'?'지금 정지':kind==='CIRCUIT'?'단자를 연결하세요':'안전 구역을 선택하세요';$('[data-action]').disabled=kind!=='CENTER';feedback(kind==='CENTER'?'중앙에 들어오는 순간, 버튼을 누르세요.':kind==='CIRCUIT'?'기호가 같은 단자끼리 연결하세요.':'파란 구역으로 이동하고 폭발을 피하세요.');trace.push({action:'START',at:0});if(kind==='SHELTER')paintWave();tick();}
  function stop(){if(!inputAllowed()||kind!=='CENTER'||nextRoundAt)return;const at=time(),position=cursorPosition(at-roundStarted,round),grade=gradeTiming(position);rounds.push({round,at:Math.round(at),position,grade});trace.push({action:'STOP',at:Math.round(at)});paintRound(round,grade,grade!=='MISS');$('[data-core-value]').textContent=grade==='PERFECT'?'100':grade==='GOOD'?'SYNC':'MISS';$('[data-core-label]').textContent=grade;feedback(grade==='PERFECT'?'완벽한 동조!':grade==='GOOD'?'동조 성공':'중앙 영역을 조금 벗어났습니다.',grade==='MISS'?'bad':'good');overlay.classList.remove('is-impact');void overlay.offsetWidth;overlay.classList.add('is-impact');$('[data-action]').disabled=true;if(round===2){finish();return;}nextRoundAt=at+520;}
  function action(){if(!started)begin();else stop();}
  on($('[data-action]'),'pointerdown',e=>{if(e.pointerType==='mouse'&&e.button!==0)return;e.preventDefault();action();},{passive:false});
  on($('[data-action]'),'click',e=>{if(e.detail===0)action();});
  on(globalThis,'keydown',e=>{if(e.key==='Escape'){e.preventDefault();abort();return;}if([' ','Enter'].includes(e.key)&&e.target===$('[data-action]')&&!e.repeat){e.preventDefault();e.stopImmediatePropagation();action();}},{capture:true});
  on(globalThis,'pagehide',abort);on(document,'visibilitychange',()=>{if(document.hidden)abort();});
  function wirePath(source,target,point){const y1=(22+source*28)*10,y2=point?point.y:(22+target*28)*10,x2=point?point.x:820;return `M180 ${y1} C430 ${y1} 570 ${y2} ${x2} ${y2}`;}
  function connect(source,target){if(!inputAllowed()||source===null||connected.has(source))return;const correct=circuitTarget(source,order)===target,at=Math.round(time());trace.push({action:'CONNECT',source,target,at,correct});if(correct){connected.add(source);rounds.push({source,target,correct,at});$(`[data-source="${source}"]`).classList.add('is-connected');$(`[data-target="${target}"]`).classList.add('is-connected');$('[data-wires]').insertAdjacentHTML('beforeend',`<path d="${wirePath(source,target)}" class="cqm-connected-wire"/>`);$('[data-connections]').innerHTML=`${connected.size}<span>/3</span>`;feedback(`${connected.size} / 3 회로 복원`,'good');if(connected.size===3)finish();}else feedback('기호가 맞지 않습니다. 같은 기호를 찾아주세요.','bad');selectedSource=null;$('[data-drag-wire]').setAttribute('d','');overlay.querySelectorAll('.is-picked').forEach(n=>n.classList.remove('is-picked'));}
  if(kind==='CIRCUIT'){
   const board=$('[data-wiring]'),coords=e=>{const rect=board.getBoundingClientRect();return {x:clamp((e.clientX-rect.left)/rect.width*1000,0,1000),y:clamp((e.clientY-rect.top)/rect.height*1000,0,1000)};};
   on(overlay,'pointerdown',e=>{if(!inputAllowed()||drag||e.isPrimary===false||(e.pointerType==='mouse'&&e.button!==0))return;const source=e.target.closest('[data-source]'),target=e.target.closest('[data-target]');if(target&&selectedSource!==null){e.preventDefault();connect(selectedSource,Number(target.dataset.target));return;}if(!source||connected.has(Number(source.dataset.source)))return;e.preventDefault();selectedSource=Number(source.dataset.source);overlay.querySelectorAll('.is-picked').forEach(n=>n.classList.remove('is-picked'));source.classList.add('is-picked');trace.push({action:'PICK',source:selectedSource,at:Math.round(time())});drag={id:e.pointerId,source:selectedSource,x:e.clientX,y:e.clientY,moved:false};try{overlay.setPointerCapture(e.pointerId);}catch{};$('[data-drag-wire]').setAttribute('d',wirePath(selectedSource,0,coords(e)));},{passive:false});
   on(overlay,'pointermove',e=>{if(!drag||drag.id!==e.pointerId)return;e.preventDefault();drag.moved ||= Math.hypot(e.clientX-drag.x,e.clientY-drag.y)>8;$('[data-drag-wire]').setAttribute('d',wirePath(drag.source,0,coords(e)));},{passive:false});
   on(overlay,'pointerup',e=>{if(!drag||drag.id!==e.pointerId)return;e.preventDefault();const held=drag;dropCapture();if(!held.moved){$('[data-drag-wire]').setAttribute('d','');feedback('같은 기호의 입력 단자를 터치하세요.');return;}let hit=null;overlay.querySelectorAll('[data-target]').forEach(node=>{const r=node.getBoundingClientRect();if(insidePort({x:e.clientX,y:e.clientY},{x:r.x+r.width/2,y:r.y+r.height/2},Math.min(r.width,r.height)/2+12))hit=Number(node.dataset.target);});if(hit!==null)connect(held.source,hit);else{selectedSource=null;$('[data-drag-wire]').setAttribute('d','');overlay.querySelectorAll('.is-picked').forEach(n=>n.classList.remove('is-picked'));feedback('단자 안에 놓아주세요.');}},{passive:false});
   const lost=e=>{if(drag?.id===e.pointerId){dropCapture();selectedSource=null;$('[data-drag-wire]').setAttribute('d','');overlay.querySelectorAll('.is-picked').forEach(n=>n.classList.remove('is-picked'));}};on(overlay,'pointercancel',lost);on(overlay,'lostpointercapture',lost);
   on(board,'click',e=>{if(e.detail!==0||!inputAllowed())return;const source=e.target.closest('[data-source]'),target=e.target.closest('[data-target]');if(source&&!connected.has(Number(source.dataset.source))){selectedSource=Number(source.dataset.source);source.classList.add('is-picked');}else if(target)connect(selectedSource,Number(target.dataset.target));});
  }
  if(kind==='SHELTER'){
   const select=e=>{if(!inputAllowed()||waveResolved===round)return;const node=e.target.closest('[data-cell]');if(!node)return;e.preventDefault();selectedCell=Number(node.dataset.cell);trace.push({action:'MOVE',cell:selectedCell,at:Math.round(time())});paintWave();};on($('[data-shelter]'),'pointerdown',e=>{if(e.pointerType==='mouse'&&e.button!==0)return;select(e);},{passive:false});on($('[data-shelter]'),'click',e=>{if(e.detail===0)select(e);});paintWave();
  }
  function tick(){if(settled||!started)return;const t=time(),remaining=Math.max(0,spec.windowMs-t);$('[data-time]').textContent=(remaining/1000).toFixed(1);
   if(kind==='CENTER'){if(nextRoundAt&&t>=nextRoundAt){round++;roundStarted=t;nextRoundAt=0;$('[data-action]').disabled=false;feedback('다음 신호를 중앙에 맞추세요.');overlay.classList.remove('is-impact');}if(!nextRoundAt){const pos=cursorPosition(t-roundStarted,round);$('[data-cursor]').style.left=`${pos*100}%`;$('[data-core-value]').textContent=String(Math.round(pos*100)).padStart(2,'0');$('[data-core-label]').textContent=gradeTiming(pos)==='MISS'?'위상 이동 중':'동조 가능';overlay.classList.toggle('is-aligned',gradeTiming(pos)!=='MISS');}}
   if(kind==='SHELTER'){const phase=t-roundStarted,left=Math.max(0,3000-phase);$('[data-wave-time]').textContent=(left/1000).toFixed(1)+'s';$('[data-wave-bar]').style.width=`${left/30}%`;if(phase>=3000&&waveResolved!==round){waveResolved=round;const safe=safeCells(round,seed).includes(selectedCell);rounds.push({round,cell:selectedCell,safe,at:Math.round(t)});paintRound(round,safe?'회피':'피격',safe);overlay.classList.add('is-blast');feedback(safe?'차폐 성공. 다음 폭발에 대비하세요.':'피격! 다음 차폐 구역을 확인하세요.',safe?'good':'bad');}if(phase>=3500){if(round===2){finish();return;}round++;roundStarted=t;overlay.classList.remove('is-blast');paintWave();}}
   if(remaining<=0){finish();return;}raf=requestAnimationFrame(tick);
  }
  $('[data-action]').focus({preventScroll:true});
 });
}
