import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.dirname(fileURLToPath(import.meta.url)),ice=path.resolve(root,'../mercenary-ice-crystal-dual-sword-v1');
await fs.mkdir(path.join(root,'source'),{recursive:true});
const replace=(s,a,b)=>{if(!s.includes(a))throw Error('Reuse source changed: '+a);return s.replaceAll(a,b);};
let fx=await fs.readFile(path.join(ice,'source/IceDualSwordFX.js'),'utf8');
for(const[a,b]of [['IceDualSwordFX','KnightFX'],['loadIceAssets','loadKnightAssets'],['mercenary-ice-crystal-dual-sword-v1','mercenary-crimson-silver-knight-battle-v1'],['IceEnhancementSilhouette','CrimsonGoldSilhouette'],['strength:14,quality:2,resolution:.65','strength:14,quality:2,resolution:.65,legacy:true'],['strength:5,quality:2,resolution:1','strength:5,quality:2,resolution:1,legacy:true'],['solidColor([.025,.19,1])','solidColor([1,.018,.065])'],['solidColor([.04,.72,1])','solidColor([1,.55,.08])'],['solidColor([.025,.33,1])','solidColor([.9,.015,.035])'],['solidColor([.46,.92,1])','solidColor([1,.87,.44])'],['0x1552ff','0xfd1534'],['0x32cfff','0xffbc48'],['0x0854ff','0xb9081d'],['0x89edff','0xffe298'],['0xc2f6ff','0xffd8a0'],['0x07152c','0x22060d'],['0x66dfff','0xffbd52'],['0xe6fbff','0xfff0cf'],['0x4fcfff','0xff243b'],['0x49bdff','0xff3140'],['0x91d3ef','0xda633f'],['0xc8faff','0xffe8a5'],['0xb5f3ff','0xffcc72'],['0x358cff','0xdd112c'],['0x70d7ff','0xff9639'],['0xdbf8ff','0xffe8c6']])fx=replace(fx,a,b);
fx=replace(fx,'scale=this.bodyHeight/spec.bodyPixels','scale=this.bodyHeight/spec.frames[contact.frame??0].bodyPixels');
fx=replace(fx,'this.destination=this.destinations.attack[0];','this.destination=this.destinations.attack[0];if(this.destinations.ultimate?.length)this.destinations.ultimate.unshift(this.destination);');
fx=replace(fx,'spec.cellSize/spec.bodyPixels','spec.cellSize/f.bodyPixels');
fx=replace(fx,'motionFrames:54,effectFrames:80','motionFrames:this.manifest.counts.motion,effectFrames:this.manifest.counts.effects');
fx=replace(fx,"state.pose);this.updateAura(state)","state.pose);this.updateAura(state)");
fx=replace(fx,'y:mix(this.start.y,mix(a.y,b.y,q),state.travel)','y:mix(this.start.y,mix(a.y,b.y,q),state.travel)-(state.lift||0)');
fx=replace(fx,"else if(effect.anchor==='targetGround')", "else if(effect.anchor==='selfGround'){p={...foot};size=unit*3.25;}else if(effect.anchor==='dash'){p={x:foot.x-unit*.55,y:foot.y-unit*.4};size=unit*3.4;}else if(effect.anchor==='targetGround')");
fx=replace(fx,'const age=time-2.62;','const age=time-3.25;');
fx=replace(fx,"if(time<=0||state.done||state.cancelled)","if(time<=0||state.done||state.cancelled)");
fx=replace(fx,'this.drawSequence(effect.key,effect,p,size);',`this.drawSequence(effect.key,effect,p,size);
   if(this.plan.mode==='ultimate'&&effect.key==='ultimate')for(const target of this.targets.slice(1)){const side=this.point(target);this.drawSequence(effect.key,{...effect,alpha:effect.alpha*.72},side,size*.72);}`);
fx=replace(fx,'clockOwner:\'V3_REGISTERED_GSAP\'',"weaponHash:this.manifest.weapon.sha256,weaponRigid:true,clockOwner:'V3_REGISTERED_GSAP'");
 fx=replace(fx,"makeTimeline(){this.removeTimeline();this.timeline=", "makeTimeline(){this.removeTimeline();this.clock.time=0;this.timeline=");
 fx=replace(fx,"this.registration={instance:this.timeline,settle:()=>this.cancel()};",`if(this.engine.camera&&!this.engine.reducedMotion)for(const at of this.plan.contacts){const big=this.plan.mode==='ultimate'&&at===3.25||this.plan.mode==='execution',remaining=this.plan.stop===null?Infinity:this.plan.stop-at-.07;if(remaining>.02)this.engine.camera.addShake(this.timeline,{at,intensity:big?42:18,duration:Math.min(big?.42:.22,remaining),rotation:big?.009:.003});}this.registration={instance:this.timeline,settle:()=>this.cancel()};`);
 fx=replace(fx,'cancel(){this.audio.stop();this.removeTimeline();','cancel(){if(this.destroyed)return;this.audio.stop();this.removeTimeline();this.engine.camera?.reset(true);');
 fx=fx.replaceAll('Ice effect sprite pool exhausted','Knight effect sprite pool exhausted');
await fs.writeFile(path.join(root,'source/KnightFX.js'),fx);
await fs.copyFile(path.join(ice,'source/CueAudio.js'),path.join(root,'source/CueAudio.js'));
let entry=(await fs.readFile(path.join(ice,'source/preview.js'),'utf8')).replaceAll('\r\n','\n');
for(const[a,b]of [['IceDualSwordPreview','CrimsonKnightPreview'],['IceDualSwordFX','KnightFX'],['loadIceAssets','loadKnightAssets'],['{ICE,MODES,makePlan}','{KNIGHT,MODES,makePlan}'],['ICE.name','KNIGHT.name'],['ICE_PREVIEW','CRIMSON_KNIGHT_PREVIEW'],['mercenary-ice-crystal-dual-sword-v1','mercenary-crimson-silver-knight-battle-v1'],['빙정 이도류 · SSS','은백·금색 대검 기사'],['빙정 이도류','대검 기사'],['SSS 용병 · 동작과 스킬 연출 검수','종결 용병 · 대검과 전장 연출 검수'],['fullBodyHeight:380','fullBodyHeight:manifest.displaySizing.fullBodyHeight'],['0x75dcff','0xffa74b']])entry=replace(entry,a,b);
entry=replace(entry,"  fx.play();\n  window.addEventListener","  fx.setPlan(makePlan({mode:'ultimate'}));$('mode').value='ultimate';fx.play();\n  window.addEventListener");
entry=entry.replaceAll('[IceDualSword]','[CrimsonKnight]');
entry=replace(entry,'fx.pause();engine.setFormationMercenaries([merc]);fx.captureFormation();fx.render(fx.time);','const at=fx.time;fx.pause();fx.removeTimeline();engine.setFormationMercenaries([merc]);fx.captureFormation();fx.makeTimeline();fx.seek(at);');
entry=replace(entry,'fx?.destroy();merc?.destroy();renderer?.destroy();',"fx?.destroy();for(const actor of new Set([...(engine?.allies||[]),...(engine?.enemies||[])])){actor.animationAdapter?.destroy?.();actor.animationController?.kill?.();}merc?.destroy();renderer?.destroy();");
entry=replace(entry,"webglcontextlost',()=>{fx.cancel();","webglcontextlost',()=>{if(disposed)return;fx.cancel();");
await fs.writeFile(path.join(root,'source/preview.js'),entry);
let battle=await fs.readFile(path.join(ice,'battle.html'),'utf8');battle=battle.replaceAll('빙정 이도류','대검 기사').replace('20260922-ice-v1','20261001-crimson-v2');await fs.writeFile(path.join(root,'battle.html'),battle);
let serve=await fs.readFile(path.join(ice,'serve.mjs'),'utf8');serve=serve.replaceAll('ICE_PREVIEW_PORT','CRIMSON_KNIGHT_PREVIEW_PORT').replace('8818','8850').replaceAll('mercenary-ice-crystal-dual-sword-v1','mercenary-crimson-silver-knight-battle-v1').replaceAll('Ice dual-sword','Crimson knight');await fs.writeFile(path.join(root,'serve.mjs'),serve);
let css=await fs.readFile(path.join(ice,'preview.css'),'utf8');for(const[a,b]of [['#88deff','#f6bc6e'],['#499ee2','#af2035'],['#b7f2ff','#f6bd6c'],['#163955','#48101b'],['#d6f6ff','#ffe3bb'],['#6acbf2','#d68254'],['#63c9f4','#d67a51'],['#c8faff','#ffdb9c'],['#24a9ff','#ff2b45'],['#185cbd','#9d152f'],['#25344966','#47202b66']])css=css.replaceAll(a,b);await fs.writeFile(path.join(root,'preview.css'),css);
await fs.copyFile(path.resolve(root,'../mercenary-ragniel-v1/build.mjs'),path.join(root,'build.mjs'));
let build=await fs.readFile(path.join(root,'build.mjs'),'utf8');await fs.writeFile(path.join(root,'build.mjs'),build.replaceAll('Ragniel preview','Crimson knight preview'));
console.log('Shared V3 renderer, alpha-follow aura and GSAP controls reused');
