import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium}=require('C:/Users/User/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=fileURLToPath(new URL('.',import.meta.url)),out=path.join(root,'qa',process.argv[2]||'');await fs.mkdir(out,{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true}),results=[];
try{
 for(const [name,viewport] of [['desktop',{width:1440,height:1000}],['mobile',{width:390,height:844}]]){
  const page=await browser.newPage({viewport,deviceScaleFactor:1}),errors=[],failed=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)failed.push({status:r.status(),url:r.url()});});
  await page.goto('http://127.0.0.1:8850/preview/mercenary-crimson-silver-knight-battle-v1/',{waitUntil:'networkidle',timeout:60000});await page.addStyleTag({content:'html{scroll-behavior:auto!important}'});
  await page.waitForFunction(()=>window.CrimsonKnightPreview?.diagnostics().ready||document.getElementById('health')?.textContent.startsWith('시연 준비 실패'),null,{timeout:60000});if(!await page.evaluate(()=>!!window.CrimsonKnightPreview))throw Error(await page.locator('#health').textContent());
  await page.evaluate(()=>window.CrimsonKnightPreview.fx.pause());const overflow=await page.evaluate(()=>({client:document.documentElement.clientWidth,scroll:document.documentElement.scrollWidth}));await page.locator('.mode-tabs').screenshot({path:path.join(out,name+'-modes.png')});await page.locator('.battle-viewport').scrollIntoViewIfNeeded();await page.waitForTimeout(100);
  const modes=[];for(const [mode,t] of [['aura',.5],['dash',.3],['attack',1.62],['attack',1.98],['skill',1.98],['overhead',1.98],['execution',1.98],['guard',1.62],['guard',1.98],['guard',2.50],['hit',.2],['defeat',2.6],['ultimate',1.98],['ultimate',3.16]]){
   await page.selectOption('#mode',mode);await page.evaluate(t=>window.CrimsonKnightPreview.fx.seek(t),t);await page.waitForTimeout(70);const diagnostic=await page.evaluate(()=>window.CrimsonKnightPreview.diagnostics());
   if(mode==='guard'){diagnostic.guardPlacement=await page.evaluate(()=>window.CrimsonKnightPreview.fx.guardPlacement());const g=diagnostic.guardPlacement,actual=diagnostic.activeFrames.find(f=>f.key==='guard');if(!actual||Math.abs(actual.anchor.y-g.point.y)>.01||Math.abs((g.foot.y-g.point.y)/g.bodyHeight-.54)>.001)errors.push('ward below wearer / actor attachment');}
   if(t===1.98&&diagnostic.pose.key!=='twohandStrike')errors.push(mode+' failed adopted motion');modes.push(diagnostic);
   if(['attack','skill','execution','guard','ultimate'].includes(mode))await page.locator('.battle-viewport').screenshot({path:path.join(out,name+'-'+mode+'-'+t+'.png')});
  }
  await page.check('#motion-only');await page.selectOption('#mode','attack');await page.evaluate(()=>window.CrimsonKnightPreview.fx.seek(1.98));await page.waitForTimeout(100);await page.locator('.battle-viewport').screenshot({path:path.join(out,name+'-motion-only.png')});const bare=await page.evaluate(()=>({sprites:window.CrimsonKnightPreview.diagnostics().visibleSprites,aura:window.CrimsonKnightPreview.fx.aura.visible}));if(bare.sprites||bare.aura)errors.push('motion-only leaked effects');await page.uncheck('#motion-only');await page.selectOption('#mode','ultimate');
  await page.selectOption('#scenario','interrupt');await page.evaluate(()=>window.CrimsonKnightPreview.fx.seek(3.25));const interruption=await page.evaluate(()=>window.CrimsonKnightPreview.diagnostics());await page.selectOption('#scenario','lost');await page.evaluate(()=>window.CrimsonKnightPreview.fx.seek(3.25));const targetLost=await page.evaluate(()=>window.CrimsonKnightPreview.diagnostics());await page.selectOption('#scenario','normal');
  const speeds=[];for(const speed of [.25,.5,1,2]){const result=await page.evaluate(async speed=>{const f=window.CrimsonKnightPreview.fx;f.seek(0);f.setSpeed(speed);f.play();const start=performance.now();await new Promise(r=>setTimeout(r,500));f.pause();return {elapsed:f.time,wall:(performance.now()-start)/1000};},speed);await page.waitForTimeout(120);const at=await page.evaluate(()=>window.CrimsonKnightPreview.fx.time);speeds.push({speed,...result,pauseStable:at===result.elapsed});}
  await page.click('#cancel');const stopped=await page.evaluate(()=>window.CrimsonKnightPreview.diagnostics());await page.check('#sound');await page.evaluate(()=>{const f=window.CrimsonKnightPreview.fx;f.seek(1.6);f.setSpeed(1);f.play();});await page.waitForTimeout(150);const sound=await page.evaluate(()=>window.CrimsonKnightPreview.diagnostics().audio);await page.click('#cancel');
  await page.uncheck('#aura');const auraOff=await page.evaluate(()=>window.CrimsonKnightPreview.fx.aura.visible);await page.check('#aura');
  await page.uncheck('#sound');await page.check('#motion-only');await page.selectOption('#speed','2');await page.click('#showcase');
  const showcaseStart=await page.evaluate(()=>({queue:window.CrimsonKnightPreview.showcase.diagnostics(),aura:window.CrimsonKnightPreview.fx.auraEnabled,motionOnly:!!window.CrimsonKnightPreview.fx.motionOnly}));
  await page.waitForFunction(()=>window.CrimsonKnightPreview.showcase.completed,null,{timeout:30000});
  const showcaseDone=await page.evaluate(()=>window.CrimsonKnightPreview.diagnostics());if(!showcaseStart.aura||showcaseStart.motionOnly||showcaseDone.showcase.index!==6||showcaseDone.registeredTimelines||showcaseDone.visibleSprites)errors.push('full showcase/cleanup');
  await page.click('#showcase');await page.click('#cancel');if(await page.evaluate(()=>window.CrimsonKnightPreview.showcase.active))errors.push('showcase cancellation');
  const disposed=await page.evaluate(()=>{const p=window.CrimsonKnightPreview,e=p.engine;p.dispose();return {timelines:e.simpleTimelines.size,effectLayers:e.effectLayer.destroyed?0:e.effectLayer.children.length,destroyed:p.fx.destroyed};});await page.waitForTimeout(180);results.push({name,overflow,errors,failed,modes,interruption,targetLost,speeds,stopped,sound,auraOff,showcaseStart,showcaseDone,disposed});await page.close();
 }
}finally{await browser.close();}
await fs.writeFile(path.join(out,'browser-report.json'),JSON.stringify(results,null,2)+'\n');
const failures=results.flatMap(r=>[...r.errors,...r.failed.map(x=>x.url),...(r.overflow.scroll>r.overflow.client?['horizontal overflow']:[]),...(!r.interruption.cancelled||!r.targetLost.cancelled||r.interruption.visibleSprites||r.targetLost.visibleSprites?['cancellation']:[]),...(!r.disposed.destroyed||r.disposed.timelines||r.disposed.effectLayers?['dispose']:[]),...(r.stopped.visibleSprites||r.stopped.registeredTimelines?['stop']:[]),...(r.auraOff?['aura switch']:[]),...r.speeds.filter(s=>!s.pauseStable||s.elapsed<=0||Math.abs(s.elapsed/s.wall-s.speed)>Math.max(.2,s.speed*.3)).map(()=> 'speed/pause'),...r.modes.filter(m=>m.regularAllies!==5||m.mercenaryInRegularArray||!m.aura.textureMatchesPose||m.effectLayers!==1).map(()=> 'formation/pose')]);
console.log(JSON.stringify({results:results.map(r=>({name:r.name,errors:r.errors,failed:r.failed,overflow:r.overflow,speeds:r.speeds,interruption:r.interruption.cancelled,targetLost:r.targetLost.cancelled,sound:r.sound,disposed:r.disposed})),failures},null,2));if(failures.length)process.exitCode=1;
