import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { transform } from 'esbuild';

const page = await readFile('raid/lich-king/index.html', 'utf8');
const ids = [...page.matchAll(/\bid="([^"]+)"/g)].map(match => match[1]);
const fonts = new Set();
const sources = [];
for (const file of ['preview/lich-king-raid-v1/raid.css', 'preview/lich-king-raid-v1/mechanics.css', 'raid/lich-king/live.css', 'raid/lich-king/lobby.css']) {
  let css = await readFile(file, 'utf8');
  css = css.replace(/@font-face\{[^}]+\}/g, font => { fonts.add(font); return ''; })
    .replace(/:root|\bbody(?=[.\s{>])/g, '&')
    .replace(/url\(['"]?(\.\.?\/[^)'"\s]+)['"]?\)/g,
      (_, asset) => `url('/${path.posix.normalize(path.posix.join(path.posix.dirname(file), asset))}')`);
  for (const id of ids) css = css.replace(new RegExp('#' + id + '(?![\\w-])', 'g'), '#lich-' + id);
  sources.push(css);
}
const adjustments = await readFile('raid/lich-king/inline-layout.css', 'utf8');
const result = await transform([...fonts, '#pveLichRaidView {', ...sources, adjustments, '}'].join('\n'), {
  loader: 'css', target: ['chrome100', 'firefox100', 'safari15.4'], legalComments: 'none',
});
if (result.warnings.length) throw new Error(JSON.stringify(result.warnings));
await writeFile('raid/lich-king/inline.css', '/* Generated by raid/lich-king/build-inline.mjs. */\n' + result.code);
console.log('Built scoped Lich raid presentation for the PVE raid hub.');
