import {Application,Assets,Container,Graphics} from 'pixi.js';
import {AccountBattleUnit} from '../../project-v-v3/source/battle/AccountBattleUnit.js';
const $=id=>document.getElementById(id);
const state={weaponIndex:4,suitIndex:0,auto:false,loading:true,shots:0,error:null,light:false};
const shortNames=['아발론 M4A1','인피니티 AK','인피니티 M200','소버린 SKS','금룡 돌격소총','금룡 대물저격총'];
let app,manifest,units=[],floor,targets=[],requestId=0,timer;
function layout(){if(!app)return;const host=$('stage'),width=host.clientWidth,height=host.clientHeight;app.renderer.resize(width,height);const mobile=window.innerWidth<=760,half=mobile?width:width/2,size=Math.min(1.27,(half-30)/360,(height-28)/435);floor.clear().rect(0,0,width,height).fill(state.light?0xced8e3:0x0a1523);const grid=state.light?0x768ca3:0x31485d;
 for(let y=30;y<height;y+=42)floor.moveTo(0,y).lineTo(width,y).stroke({color:grid,width:1,alpha:.17});
 if(!mobile)floor.moveTo(half,0).lineTo(half,height).stroke({color:grid,width:1,alpha:.4});
 units.forEach((u,i)=>{u.root.visible=u.active&&(!mobile||i===state.suitIndex);const start=mobile?0:i*half;u.setFormation(start+half*(mobile?.14:.23),height-24,size);u.shadow.scale.x=mobile?.6:1;targets[i]={x:start+half*.95,y:u.muzzlePoint().y};if(u.root.visible){const{x,y}=targets[i];floor.circle(x,y,10).stroke({color:grid,width:1,alpha:.7});floor.moveTo(x-16,y).lineTo(x+16,y).moveTo(x,y-16).lineTo(x,y+16).stroke({color:grid,width:1,alpha:.6});}});
}
function stopAuto(){state.auto=false;clearTimeout(timer);$('auto').setAttribute('aria-pressed','false');$('auto').textContent='연속 사격 OFF';}
async function selectWeapon(index){if(!Number.isInteger(index)||index<0||index>=6)return false;const id=++requestId;state.weaponIndex=index;state.loading=true;stopAuto();$('fire').disabled=true;$('auto').disabled=true;document.querySelectorAll('.weapon').forEach((b,i)=>{b.classList.toggle('active',i===index);b.setAttribute('aria-pressed',String(i===index));});units.forEach(u=>{u.cancelFire();u.setActive(false);});
 try{const entries=manifest.suits.map(s=>s.entries[index]),textures=await Promise.all(entries.map(e=>Assets.load(e.profile.sheetUrl)));if(id!==requestId)return false;
  manifest.suits.forEach((s,i)=>{const e=entries[i];if(!units[i].setAuthoredSheet(textures[i],e.profile,{height:430,source:e.profile.sheetUrl}))throw Error('사격 아틀라스 설정 실패');units[i].setName(s.name);units[i].nameHud.visible=false;units[i].setActive(true,{deployed:true});});
  $('downloads').innerHTML=manifest.suits.map((s,i)=>{const e=entries[i];return `<article class="download"><strong class="body-tag">${s.name}</strong><div class="download-links"><a href="${e.highResolution}" download>고해상도 PNG ↓</a><a href="${e.image}" download>전투 PNG ↓</a><a href="${e.profile.sheetUrl}" download>아틀라스 ↓</a></div></article>`;}).join('');$('weapon-name').textContent=shortNames[index];state.loading=false;state.error=null;$('loading').hidden=true;$('fire').disabled=false;$('auto').disabled=false;layout();return true;
 }catch(error){if(id!==requestId)return false;state.error=String(error.message||error);$('loading').hidden=false;$('loading').textContent=state.error;return false;}
}
function selectSuit(index){if(index!==0&&index!==1)return;stopAuto();units.forEach(u=>u.cancelFire());state.suitIndex=index;document.querySelectorAll('[data-suit]').forEach((b,i)=>b.setAttribute('aria-pressed',String(i===index)));layout();}
async function fire(){if(state.loading)return false;const results=await Promise.all(units.map((u,i)=>u.root.visible?u.playRangedFire({targetX:targets[i].x,targetY:u.muzzlePoint().y,weaponCode:manifest.weapons[state.weaponIndex].equipmentCode}):Promise.resolve(true)));if(results.every(Boolean))state.shots++;$('shot-status').textContent=`사격 ${state.shots}회`;return results.every(Boolean);}
async function autoLoop(){if(!state.auto)return;await fire();if(state.auto)timer=setTimeout(autoLoop,[160,200,750,470,160,850][state.weaponIndex]);}
async function main(){const response=await fetch('./manifest.json');if(!response.ok)throw Error('리소스 명세를 불러올 수 없습니다.');manifest=await response.json();app=new Application();await app.init({width:1100,height:530,backgroundAlpha:0,antialias:true,resolution:Math.min(2,devicePixelRatio||1),autoDensity:true});$('stage').appendChild(app.canvas);floor=new Graphics();app.stage.addChild(floor);const effects=new Container();effects.sortableChildren=true;units=manifest.suits.map(()=>new AccountBattleUnit({effectLayer:effects}));units.forEach(u=>app.stage.addChild(u.root));app.stage.addChild(effects);
 $('weapons').innerHTML=manifest.weapons.map((w,i)=>`<button class="weapon" type="button" data-index="${i}" aria-pressed="false"><img src="${w.battleSprite}" alt=""><span>${shortNames[i]}</span></button>`).join('');$('weapons').addEventListener('click',e=>{const button=e.target.closest('button');if(button)selectWeapon(Number(button.dataset.index));});document.querySelector('.suit-headings').addEventListener('click',e=>{const button=e.target.closest('[data-suit]');if(button)selectSuit(Number(button.dataset.suit));});$('fire').addEventListener('click',fire);$('auto').addEventListener('click',()=>{if(state.auto)stopAuto();else{state.auto=true;$('auto').setAttribute('aria-pressed','true');$('auto').textContent='연속 사격 ON';autoLoop();}});$('background').addEventListener('click',()=>{state.light=!state.light;document.body.classList.toggle('light',state.light);$('background').textContent=state.light?'어두운 배경':'밝은 배경';layout();});new ResizeObserver(layout).observe($('stage'));document.addEventListener('visibilitychange',()=>{if(document.hidden){stopAuto();units.forEach(u=>u.cancelFire());}});await Promise.all(units.map(u=>u.prepareRangedFireEffects()));await selectWeapon(4);window.szSuitPreview={diagnostics:()=>({...state,scope:'PREVIEW_ONLY',liveEnabled:false,profileSource:'S_Z_RESOURCE_MANIFEST',geometry:units.map((u,i)=>({visible:u.root.visible,muzzle:u.muzzlePoint(),target:targets[i]})),units:units.map(u=>u.diagnostics())}),selectWeapon,selectSuit,fire,stop:()=>{stopAuto();units.forEach(u=>u.cancelFire());}};
}
main().catch(error=>{state.error=String(error.message||error);$('loading').textContent=state.error;console.error(error);});
